"use client"

import { useEffect, useMemo, useState } from "react"
import { loadHQExecutiveAnalytics, type HQExecutiveAnalytics } from "@/lib/hq/operating"

const C={panel:"#0d1b2f",border:"rgba(255,255,255,.08)",muted:"rgba(255,255,255,.46)",green:"#34d399",blue:"#60a5fa",amber:"#f59e0b",violet:"#a78bfa",red:"#ef4444"}
function Card({title,value}:{title:string;value:string|number}){return <div style={{background:C.panel,border:`1px solid ${C.border}`,borderRadius:14,padding:13}}><div style={{fontSize:21,fontWeight:900}}>{value}</div><div style={{fontSize:11,fontWeight:800,marginTop:5}}>{title}</div></div>}
function Breakdown({title,rows}:{title:string;rows:Array<{name:string;value:number}>}){const total=Math.max(1,rows.reduce((s,r)=>s+r.value,0));return <div style={{background:C.panel,border:`1px solid ${C.border}`,borderRadius:14,padding:13}}><div style={{fontSize:11,fontWeight:900,marginBottom:8}}>{title}</div>{rows.map(r=><div key={r.name} style={{display:"flex",gap:8,fontSize:10.5,marginTop:7}}><span style={{flex:1}}>{r.name}</span><strong>{r.value}</strong><span style={{width:40,textAlign:"right",color:C.muted}}>{Math.round(r.value/total*100)}%</span></div>)}</div>}
export default function HQExecutiveAnalytics(){const[a,setA]=useState<HQExecutiveAnalytics|null>(null);const[error,setError]=useState("");useEffect(()=>{loadHQExecutiveAnalytics().then(setA).catch(e=>setError(e instanceof Error?e.message:"Analytics unavailable"))},[]);const roles=useMemo(()=>a?.roles.map(x=>({name:x.role,value:x.count}))??[],[a]);const schools=useMemo(()=>a?.schools.map(x=>({name:x.status,value:x.count}))??[],[a]);if(error)return <div style={{color:"#fca5a5",fontSize:11}}>{error};if(!a)return <div style={{color:C.muted,fontSize:11}}>Loading executive analytics…</div>;return <div><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(150px,1fr))",gap:9}}><Card title="30d payments" value={`KES ${a.finance.payments_30d.toLocaleString("en-KE")}`}/><Card title="30d expenses" value={`KES ${a.finance.expenses_30d.toLocaleString("en-KE")}`}/><Card title="Marking backlog" value={a.operations.marking_backlog}/><Card title="Open incidents" value={a.operations.open_incidents}/><Card title="Publication reads" value={a.content.publication_reads}/><Card title="Parent messages · 30d" value={a.communications.parent_messages_30d}/></div><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(260px,1fr))",gap:10,marginTop:10}}><Breakdown title="User composition" rows={roles}/><Breakdown title="School operating status" rows={schools}/></div><div style={{background:C.panel,border:`1px solid ${C.border}`,borderRadius:14,padding:13,marginTop:10}}><div style={{fontSize:11,fontWeight:900,marginBottom:8}}>14-day operating activity</div>{a.daily.map(r=><div key={r.date} style={{display:"grid",gridTemplateColumns:"80px repeat(4,1fr)",gap:8,fontSize:10,padding:"5px 0",borderTop:`1px solid ${C.border}`}}><span style={{color:C.muted}}>{new Date(r.date+"T00:00:00").toLocaleDateString("en-KE",{month:"short",day:"numeric"})}</span><span>Users {r.signups}</span><span>Plans {r.lesson_plans}</span><span>HW {r.homework}</span><span>Subs {r.submissions}</span></div>)}</div></div>}
