"use client"

import { useEffect, useMemo, useState } from "react"
import { loadHQExecutiveAnalytics, type HQExecutiveAnalytics } from "@/lib/hq/operating"

const C={panel:"#0d1b2f",border:"rgba(255,255,255,.08)",text:"#f8fafc",muted:"rgba(255,255,255,.46)",green:"#34d399",blue:"#60a5fa",amber:"#f59e0b",violet:"#a78bfa",red:"#ef4444"}
const palette=[C.green,C.blue,C.violet,C.amber,C.red,"#22d3ee","#f472b6"]
function Card({title,value,note}:{title:string;value:string|number;note?:string}){return <div style={{background:C.panel,border:`1px solid ${C.border}`,borderRadius:14,padding:13}}><div style={{fontSize:21,fontWeight:900}}>{value}</div><div style={{fontSize:11,fontWeight:800,marginTop:5}}>{title}</div>{note&&<div style={{fontSize:10,color:C.muted,marginTop:3}}>{note}</div>}</div>}
function Donut({rows,title}:{rows:Array<{name:string;value:number}>;title:string}){const total=Math.max(1,rows.reduce((s,r)=>s+r.value,0));let cursor=0;const stops=rows.map((r,i)=>{const start=cursor;cursor+=r.value/total*100;return `${palette[i%palette.length]} ${start}% ${cursor}%`}).join(",");return <div style={{background:C.panel,border:`1px solid ${C.border}`,borderRadius:14,padding:13}}><div style={{fontSize:11,fontWeight:900,marginBottom:10}}>{title}</div><div style={{display:"flex",alignItems:"center",gap:16}}><div style={{width:112,height:112,borderRadius:"50%",background:`conic-gradient(${stops})`,position:"relative",flexShrink:0}}><div style={{position:"absolute",inset:24,borderRadius:"50%",background:C.panel,display:"grid",placeItems:"center",fontSize:15,fontWeight:900}}>{total}</div></div><div style={{flex:1}}>{rows.map((r,i)=><div key={r.name} style={{display:"flex",alignItems:"center",fontSize:10.5,marginBottom:7}}><span style={{width:8,height:8,borderRadius:99,background:palette[i%palette.length],marginRight:7}}/><span style={{flex:1}}>{r.name}</span><strong>{r.value}</strong><span style={{width:42,textAlign:"right",color:C.muted}}>{Math.round(r.value/total*100)}%</span></div>)}</div></div></div>}
function Trend({a}:{a:HQExecutiveAnalytics}){const rows=a.daily;const peak=Math.max(1,...rows.flatMap(x=>[x.signups,x.lesson_plans,x.homework,x.submissions]));const w=720,h=180,p=18;const point=(v:number,i:number)=>`${p+(i/(Math.max(1,rows.length-1)))*(w-2*p)},${h-p-(v/peak)*(h-2*p)}`;const series=[{k:"signups",label:"Signups",c:C.green},{k:"lesson_plans",label:"Lesson plans",c:C.violet},{k:"homework",label:"Homework",c:C.amber},{k:"submissions",label:"Submissions",c:C.blue}] as const;return <div style={{background:C.panel,border:`1px solid ${C.border}`,borderRadius:14,padding:13,overflow:"hidden"}}><div style={{display:"flex",justifyContent:"space-between",gap:8,flexWrap:"wrap",marginBottom:8}}><div style={{fontSize:11,fontWeight:900}}>14-day operating trend</div><div style={{display:"flex",gap:10,flexWrap:"wrap"}}>{series.map(s=><span key={s.k} style={{fontSize:9.5,color:C.muted}}><i style={{display:"inline-block",width:7,height:7,borderRadius:99,background:s.c,marginRight:4}}/>{s.label}</span>)}</div></div><svg viewBox={`0 0 ${w} ${h}`} style={{width:"100%",height:190,display:"block"}} role="img" aria-label="14-day VibeSchool activity trend"><line x1={p} y1={h-p} x2={w-p} y2={h-p} stroke="rgba(255,255,255,.12)"/><line x1={p} y1={p} x2={p} y2={h-p} stroke="rgba(255,255,255,.12)"/>{series.map(s=><polyline key={s.k} points={rows.map((r,i)=>point(Number(r[s.k]),i)).join(" ")} fill="none" stroke={s.c} strokeWidth="3" strokeLinecap="round" strokeLinejoin="round"/>)}{rows.map((r,i)=>i%Math.max(1,Math.ceil(rows.length/7))===0?<text key={r.date} x={p+(i/(Math.max(1,rows.length-1)))*(w-2*p)} y={h-2} fill="rgba(255,255,255,.4)" fontSize="9" textAnchor="middle">{new Date(r.date+"T00:00:00").toLocaleDateString("en-KE",{month:"short",day:"numeric"})}</text>:null)}</svg></div>}

export default function HQExecutiveAnalytics(){const[a,setA]=useState<HQExecutiveAnalytics|null>(null);const[error,setError]=useState("");useEffect(()=>{loadHQExecutiveAnalytics().then(setA).catch(e=>setError(e instanceof Error?e.message:"Analytics unavailable"))},[]);const roleRows=useMemo(()=>a?.roles.map(x=>({name:x.role,value:x.count}))??[],[a]);const schoolRows=useMemo(()=>a?.schools.map(x=>({name:x.status,value:x.count}))??[],[a]);if(error)return <div style={{color:"#fca5a5",fontSize:11}}>{error}</div>;if(!a)return <div style={{color:C.muted,fontSize:11}}>Loading analytics…</div>;return <div><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(150px,1fr))",gap:9}}><Card title="30d payments" value={`KES ${a.finance.payments_30d.toLocaleString("en-KE")}`}/><Card title="30d expenses" value={`KES ${a.finance.expenses_30d.toLocaleString("en-KE")}`}/><Card title="Marking backlog" value={a.operations.marking_backlog}/><Card title="Open incidents" value={a.operations.open_incidents}/><Card title="Publication reads" value={a.content.publication_reads}/><Card title="Parent messages · 30d" value={a.communications.parent_messages_30d}/></div><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(300px,1fr))",gap:10,marginTop:10}}><Donut rows={roleRows} title="User composition"/><Donut rows={schoolRows} title="School operating status"/></div><div style={{marginTop:10}}><Trend a={a}/></div></div>}
