"use client"

import Link from "next/link"
import { usePathname } from "next/navigation"
import { useEffect, useMemo, useState, type CSSProperties, type ReactNode } from "react"
import HQNotificationCenter from "@/components/hq/NotificationCenter"

export const HQ_THEME = {
  bg: "#06101d", panel: "#0b1728", panelSoft: "#0e1d31", border: "rgba(148,163,184,.13)", text: "#f8fafc", muted: "#8fa2ba", green: "#22c55e", blue: "#3b82f6", amber: "#f59e0b", red: "#ef4444", violet: "#8b5cf6", cyan: "#06b6d4",
} as const

type NavItem = readonly [string,string,string]
type NavGroup = {label:string;items:readonly NavItem[]}
export const HQ_NAV_GROUPS: readonly NavGroup[] = [
  {label:"Overview",items:[["Home","/hq","⌂"],["Decisions","/hq/decisions","✓"],["Operations","/hq/intelligence","◈"],["Alerts","/hq/notifications","!"]]},
  {label:"Business",items:[["Product","/hq/analytics","◎"],["Schools","/hq/schools","⌂"],["Users","/hq/users","♙"],["Marketing","/hq/marketing","↗"],["Geography","/hq/geography","⌖"],["Support","/hq/support","?"]]},
  {label:"Learning",items:[["Content","/hq/content","▣"],["Curriculum Authority","/hq/curriculum-authority","A"],["Content Factory","/hq/curriculum-intelligence/engine","✦"],["Studio","/hq/studio","✎"]]},
  {label:"Operations",items:[["Departments","/hq/departments","▦"],["Workroom","/hq/workroom","□"],["Workforce","/hq/workforce","⚙"],["Revenue","/hq/billing","$"],["System","/hq/security","◇"],["Commissioning","/hq/workforce/readiness","✓"]]},
]

const mobileLinks: readonly NavItem[] = [["Home","/hq","⌂"],["Decisions","/hq/decisions","✓"],["Alerts","/hq/notifications","!"],["Operations","/hq/intelligence","◈"]]
const allItems=HQ_NAV_GROUPS.flatMap(group=>group.items.map(item=>({group:group.label,item})))
function isActive(pathname:string,href:string){return href==="/hq"?pathname===href:pathname===href||pathname.startsWith(`${href}/`)}

function NavGroups({pathname,onNavigate,compact=false}:{pathname:string;onNavigate?:()=>void;compact?:boolean}){
  return <>{HQ_NAV_GROUPS.map(group=><section key={group.label} className="hq-side-group"><div className="hq-side-group-label">{group.label}</div>{group.items.map(([label,href,icon])=>{const active=isActive(pathname,href);return <Link key={`${label}-${href}`} href={href} onClick={onNavigate} title={compact?label:undefined} className={`hq-side-link${active?" is-active":""}`} aria-current={active?"page":undefined}><span className="hq-side-icon" aria-hidden>{icon}</span><span className="hq-side-label">{label}</span></Link>})}</section>)}</>
}

export function HQNavigation(){
  const pathname=usePathname();const[drawerOpen,setDrawerOpen]=useState(false);const[collapsed,setCollapsed]=useState(false);const[searchOpen,setSearchOpen]=useState(false);const[query,setQuery]=useState("")
  useEffect(()=>{setDrawerOpen(false);setSearchOpen(false);setQuery("")},[pathname])
  useEffect(()=>{try{setCollapsed(localStorage.getItem("hq-nav-collapsed")==="1")}catch{}},[])
  function toggleCollapsed(){setCollapsed(value=>{const next=!value;try{localStorage.setItem("hq-nav-collapsed",next?"1":"0")}catch{}return next})}
  const matches=useMemo(()=>{const q=query.trim().toLowerCase();return q?allItems.filter(({group,item:[label,href]})=>`${group} ${label} ${href}`.toLowerCase().includes(q)).slice(0,12):allItems.slice(0,8)},[query])
  return <>
    <aside className={`hq-sidebar${collapsed?" is-collapsed":""}`} aria-label="HQ owner navigation">
      <div className="hq-side-brand-row"><Link href="/hq" className="hq-side-brand" aria-label="VibeSchool HQ home"><span className="hq-side-logo">V</span><span className="hq-side-brand-copy"><strong>VibeSchool HQ</strong><small>Company Operating System</small></span></Link><button className="hq-collapse-btn" onClick={toggleCollapsed} aria-label={collapsed?"Expand navigation":"Collapse navigation"}>{collapsed?"›":"‹"}</button></div>
      <button className="hq-search-trigger" onClick={()=>setSearchOpen(true)}><span>⌕</span><span className="hq-side-label">Search HQ</span><kbd className="hq-side-label">/</kbd></button>
      <div className="hq-side-scroll"><NavGroups pathname={pathname} compact={collapsed}/></div>
      <div className="hq-side-owner"><span className="hq-owner-avatar">F</span><span className="hq-side-label"><strong>Founder</strong><small>System Owner</small></span></div>
    </aside>

    <header className="hq-mobile-topbar"><button className="hq-menu-btn" onClick={()=>setDrawerOpen(true)} aria-label="Open HQ navigation">☰</button><Link href="/hq" className="hq-mobile-brand"><span className="hq-side-logo">V</span><span><strong>VibeSchool HQ</strong><i>Owner</i></span></Link><div className="hq-mobile-actions"><button className="hq-mobile-search" onClick={()=>setSearchOpen(true)} aria-label="Search HQ">⌕</button><HQNotificationCenter /></div></header>

    <nav className="hq-bottom-nav" aria-label="HQ mobile shortcuts">{mobileLinks.map(([label,href,icon])=>{const active=isActive(pathname,href);return <Link key={label} href={href} aria-current={active?"page":undefined} className={`hq-bottom-link${active?" is-active":""}`}><span className="hq-bottom-icon" aria-hidden>{icon}</span><span>{label}</span></Link>})}<button className={`hq-bottom-link${drawerOpen?" is-active":""}`} onClick={()=>setDrawerOpen(true)}><span className="hq-bottom-icon">≡</span><span>Menu</span></button></nav>

    {drawerOpen&&<div className="hq-drawer-layer" role="presentation" onClick={()=>setDrawerOpen(false)}><aside className="hq-drawer" role="dialog" aria-modal="true" aria-label="HQ navigation" onClick={event=>event.stopPropagation()}><header><div><strong>VibeSchool HQ</strong><span>All company areas</span></div><button onClick={()=>setDrawerOpen(false)} aria-label="Close navigation">×</button></header><button className="hq-drawer-search" onClick={()=>{setDrawerOpen(false);setSearchOpen(true)}}>⌕ Search everything in HQ</button><div className="hq-drawer-scroll"><NavGroups pathname={pathname} onNavigate={()=>setDrawerOpen(false)}/></div></aside></div>}

    {searchOpen&&<div className="hq-search-layer" role="presentation" onClick={()=>setSearchOpen(false)}><section className="hq-command" role="dialog" aria-modal="true" aria-label="Search HQ" onClick={event=>event.stopPropagation()}><header><span>⌕</span><input autoFocus value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search pages, teams, content, revenue, workforce…" aria-label="Search HQ destinations"/><button onClick={()=>setSearchOpen(false)}>Esc</button></header><div className="hq-command-results">{matches.length?matches.map(({group,item:[label,href,icon]})=><Link key={href} href={href}><span className="hq-command-icon">{icon}</span><span><strong>{label}</strong><small>{group}</small></span><em>→</em></Link>):<p>No HQ destination matches “{query}”.</p>}</div></section></div>}
  </>
}

export function HQPage({title,description,actions,children}:{title:string;description?:string;actions?:ReactNode;children:ReactNode}){return <main className="hq-page"><div className="hq-container"><header className="hq-page-header"><div><h1>{title}</h1>{description&&<p>{description}</p>}</div>{actions&&<div className="hq-page-actions">{actions}</div>}</header>{children}</div></main>}
export function HQPanel({title,description,children,className=""}:{title?:string;description?:string;children:ReactNode;className?:string}){return <section className={`hq-panel ${className}`}>{(title||description)&&<header className="hq-panel-header">{title&&<h2>{title}</h2>}{description&&<p>{description}</p>}</header>}<div className="hq-panel-body">{children}</div></section>}
export const hqButtonStyle:CSSProperties={minHeight:44,padding:"0 14px",borderRadius:10,border:`1px solid ${HQ_THEME.border}`,background:"rgba(255,255,255,.04)",color:HQ_THEME.text,fontSize:13,fontWeight:800,cursor:"pointer",touchAction:"manipulation"}

export function HQStyles(){return <style jsx global>{`
:root{--hq-bg:#06101d;--hq-panel:#0b1728;--hq-panel2:#0e1d31;--hq-border:rgba(148,163,184,.13);--hq-text:#f8fafc;--hq-muted:#8fa2ba;--hq-green:#22c55e;--hq-blue:#3b82f6;--hq-amber:#f59e0b;--hq-red:#ef4444;--hq-sidebar-width:248px}*{box-sizing:border-box}body{background:var(--hq-bg)}
.hq-sidebar{position:fixed;z-index:120;inset:0 auto 0 0;width:var(--hq-sidebar-width);background:linear-gradient(180deg,#071426,#071321);border-right:1px solid var(--hq-border);font-family:Inter,system-ui,sans-serif;display:flex;flex-direction:column;padding:12px;transition:width .18s ease}.hq-sidebar.is-collapsed{width:76px}.hq-side-brand-row{display:flex;align-items:center;min-width:0}.hq-side-brand{min-height:60px;flex:1;display:flex;align-items:center;gap:11px;padding:0 8px;text-decoration:none;color:var(--hq-text);min-width:0}.hq-side-logo{flex:0 0 auto;width:36px;height:36px;border-radius:10px;display:grid;place-items:center;background:linear-gradient(145deg,#0ea5e9,#22c55e);color:#04101d;font-size:17px;font-weight:1000;transform:skew(-10deg)}.hq-side-brand-copy{min-width:0}.hq-side-brand strong{display:block;font-size:14px;white-space:nowrap}.hq-side-brand small,.hq-side-owner small{display:block;color:var(--hq-muted);font-size:10px;margin-top:3px;white-space:nowrap}.hq-collapse-btn{width:30px;height:34px;border:1px solid var(--hq-border);border-radius:8px;background:#0d1b2d;color:#9fb2c8;cursor:pointer}.hq-sidebar.is-collapsed .hq-side-label,.hq-sidebar.is-collapsed .hq-side-brand-copy,.hq-sidebar.is-collapsed .hq-side-group-label,.hq-sidebar.is-collapsed .hq-collapse-btn{display:none}.hq-sidebar.is-collapsed .hq-side-brand{justify-content:center;padding:0}.hq-search-trigger{width:100%;min-height:42px;margin:5px 0 8px;display:flex;align-items:center;gap:10px;padding:0 11px;border:1px solid var(--hq-border);border-radius:10px;background:rgba(255,255,255,.025);color:#9fb2c8;cursor:pointer}.hq-search-trigger kbd{margin-left:auto;border:1px solid var(--hq-border);border-radius:5px;padding:2px 5px;background:#07111f}.hq-side-scroll{overflow-y:auto;scrollbar-width:none}.hq-side-group{margin:8px 0 12px}.hq-side-group-label{padding:0 11px 6px;color:#7e91a9;text-transform:uppercase;font-size:9px;letter-spacing:.1em;font-weight:900}.hq-side-link{min-height:40px;display:flex;align-items:center;gap:10px;padding:0 11px;border-radius:9px;text-decoration:none;color:#b9c7d7;font-size:12px;font-weight:720;margin:2px 0;border:1px solid transparent}.hq-side-link:hover{background:rgba(255,255,255,.04);color:#fff}.hq-side-link.is-active{color:#fff;background:linear-gradient(90deg,rgba(37,99,235,.33),rgba(37,99,235,.16));border-color:rgba(59,130,246,.18);box-shadow:inset 2px 0 #3b82f6}.hq-side-icon{flex:0 0 20px;text-align:center;color:#9fb2c8;font-size:14px}.hq-sidebar.is-collapsed .hq-side-link{justify-content:center;padding:0}.hq-side-owner{margin-top:auto;border-top:1px solid var(--hq-border);padding:12px 8px 2px;display:flex;gap:10px;align-items:center;color:#fff}.hq-owner-avatar{flex:0 0 auto;width:34px;height:34px;border-radius:50%;display:grid;place-items:center;background:linear-gradient(145deg,#cbd5e1,#64748b);color:#08111e;font-weight:950;font-size:12px}.hq-mobile-topbar,.hq-bottom-nav{display:none}
.hq-page{min-height:100dvh;margin-left:var(--hq-sidebar-width);background:radial-gradient(circle at 90% -10%,rgba(37,99,235,.12),transparent 30rem),linear-gradient(180deg,#06101d,#071321 46%,#06101d);color:var(--hq-text);font-family:Inter,system-ui,sans-serif;transition:margin-left .18s ease}.hq-sidebar.is-collapsed~.hq-mobile-topbar~.hq-bottom-nav~.hq-page{margin-left:76px}.hq-container{width:min(100%,1450px);margin:auto;padding:24px 22px 52px}.hq-page-header{display:flex;align-items:flex-start;justify-content:space-between;gap:18px;margin-bottom:18px}.hq-page-header h1{margin:0;font-size:clamp(24px,2.1vw,30px);letter-spacing:-.035em}.hq-page-header p{margin:7px 0 0;color:var(--hq-muted);font-size:13px;line-height:1.5}.hq-page-actions{display:flex;gap:8px;flex-wrap:wrap;justify-content:flex-end}.hq-panel{border:1px solid var(--hq-border);border-radius:14px;background:linear-gradient(180deg,rgba(15,32,53,.93),rgba(10,24,41,.98));overflow:hidden;box-shadow:0 15px 42px rgba(0,0,0,.13)}.hq-panel-header{padding:15px 16px;border-bottom:1px solid var(--hq-border)}.hq-panel-header h2{margin:0;font-size:13px;text-transform:uppercase;letter-spacing:.035em}.hq-panel-header p{margin:5px 0 0;color:var(--hq-muted);font-size:12px;line-height:1.45}.hq-panel-body{min-width:0}.hq-mobile-stack{display:grid;grid-template-columns:minmax(0,1fr) auto;gap:10px;align-items:center}
.hq-drawer-layer,.hq-search-layer{position:fixed;z-index:300;inset:0;background:rgba(1,6,13,.7);backdrop-filter:blur(6px)}.hq-drawer{position:absolute;inset:0 auto 0 0;width:min(88vw,360px);background:#071426;border-right:1px solid var(--hq-border);display:flex;flex-direction:column;font-family:Inter,system-ui,sans-serif;color:#fff}.hq-drawer>header{display:flex;align-items:center;justify-content:space-between;padding:18px 16px 12px;border-bottom:1px solid var(--hq-border)}.hq-drawer>header strong,.hq-drawer>header span{display:block}.hq-drawer>header span{font-size:11px;color:var(--hq-muted);margin-top:3px}.hq-drawer>header button{width:42px;height:42px;border:1px solid var(--hq-border);border-radius:10px;background:#0d1b2d;color:#fff;font-size:24px}.hq-drawer-search{margin:12px;min-height:46px;border:1px solid var(--hq-border);border-radius:10px;background:#0d1b2d;color:#cbd5e1;text-align:left;padding:0 14px}.hq-drawer-scroll{overflow-y:auto;padding:0 12px 24px}.hq-drawer .hq-side-link{min-height:44px;font-size:13px}.hq-drawer .hq-side-group-label{font-size:10px;margin-top:7px}.hq-search-layer{display:grid;place-items:start center;padding:9vh 16px}.hq-command{width:min(680px,100%);max-height:78vh;border:1px solid var(--hq-border);border-radius:16px;background:#081626;box-shadow:0 28px 90px rgba(0,0,0,.45);overflow:hidden;font-family:Inter,system-ui,sans-serif}.hq-command>header{display:grid;grid-template-columns:auto 1fr auto;align-items:center;gap:10px;padding:13px;border-bottom:1px solid var(--hq-border)}.hq-command input{width:100%;height:46px;border:0;outline:0;background:transparent;color:#fff;font-size:16px}.hq-command button{border:1px solid var(--hq-border);border-radius:7px;background:#0d1b2d;color:#94a3b8;padding:6px 8px}.hq-command-results{max-height:60vh;overflow-y:auto;padding:8px}.hq-command-results a{min-height:54px;padding:8px 10px;display:grid;grid-template-columns:32px 1fr auto;align-items:center;gap:9px;text-decoration:none;color:#fff;border-radius:10px}.hq-command-results a:hover{background:#10233b}.hq-command-results small{display:block;color:var(--hq-muted);font-size:10px;margin-top:2px}.hq-command-results em{font-style:normal;color:#60a5fa}.hq-command-results p{color:var(--hq-muted);padding:20px}
@media(max-width:980px){.hq-sidebar{width:210px}.hq-page{margin-left:210px}.hq-container{padding:20px 15px 44px}}
@media(max-width:900px){.hq-sidebar{display:none}.hq-page,.hq-sidebar.is-collapsed~.hq-mobile-topbar~.hq-bottom-nav~.hq-page{margin-left:0;padding-top:62px}.hq-mobile-topbar{position:fixed;z-index:120;top:0;left:0;right:0;height:62px;padding:0 10px;display:grid;grid-template-columns:42px 1fr auto;gap:7px;align-items:center;background:rgba(6,16,29,.97);backdrop-filter:blur(18px);border-bottom:1px solid var(--hq-border);font-family:Inter,system-ui,sans-serif}.hq-menu-btn,.hq-mobile-search{width:40px;height:40px;border:1px solid var(--hq-border);border-radius:10px;background:#0c1a2b;color:#dbeafe;font-size:18px}.hq-mobile-brand{display:flex;align-items:center;gap:8px;color:#fff;text-decoration:none;min-width:0}.hq-mobile-brand .hq-side-logo{width:30px;height:30px;font-size:13px}.hq-mobile-brand strong{font-size:13px;display:block;white-space:nowrap}.hq-mobile-brand i{display:block;font-style:normal;color:var(--hq-green);font-size:9px;margin-top:1px}.hq-mobile-actions{display:flex;align-items:center;gap:4px}.hq-container{padding:16px 12px calc(88px + env(safe-area-inset-bottom))}.hq-page-header{display:block;margin-bottom:14px}.hq-page-header h1{font-size:22px}.hq-page-header p{font-size:12px;line-height:1.45}.hq-page-actions{margin-top:12px;display:flex;flex-wrap:nowrap;overflow-x:auto;justify-content:flex-start;padding-bottom:3px;scrollbar-width:none}.hq-page-actions>*{flex:0 0 auto}.hq-panel{border-radius:13px}.hq-mobile-stack{grid-template-columns:1fr}.hq-bottom-nav{position:fixed;z-index:125;left:0;right:0;bottom:0;display:grid;grid-template-columns:repeat(5,1fr);gap:2px;padding:5px 6px calc(5px + env(safe-area-inset-bottom));background:rgba(6,16,29,.985);backdrop-filter:blur(20px);border-top:1px solid var(--hq-border)}.hq-bottom-link{border:0;background:transparent;min-height:54px;display:flex;flex-direction:column;align-items:center;justify-content:center;gap:3px;color:#8799b0;text-decoration:none;font-size:9px;font-weight:800;border-radius:10px}.hq-bottom-icon{font-size:16px}.hq-bottom-link.is-active{color:#60a5fa}.hq-search-layer{padding-top:70px}.hq-command{border-radius:14px}.hq-command input{font-size:14px}}
@media(max-width:520px){.hq-container{padding-left:10px;padding-right:10px}.hq-page-header h1{font-size:20px}.hq-page-actions{gap:6px}.hq-panel-header{padding:13px}.hq-panel-header h2{font-size:12px}.hq-panel-header p{font-size:11px}.hq-mobile-brand .hq-side-logo{display:none}}
@media(prefers-reduced-motion:reduce){*,*::before,*::after{scroll-behavior:auto!important;transition:none!important;animation:none!important}}
`}</style>}
