"use client"

export function PortalLoading({ role }: { role: "Teacher" | "School Admin" }) {
  return <main aria-busy="true" aria-label={`${role} workspace loading`} style={{minHeight:"100dvh",background:"#f8fafc",padding:"clamp(16px,4vw,32px)"}}><section style={{maxWidth:1180,margin:"0 auto"}}><div style={{height:64,borderRadius:18,background:"linear-gradient(110deg,#e2e8f0 8%,#f8fafc 18%,#e2e8f0 33%)",backgroundSize:"200% 100%",animation:"portalShimmer 1.4s linear infinite",marginBottom:18}}/><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(220px,1fr))",gap:14,marginBottom:18}}>{[1,2,3].map(i=><div key={i} style={{height:116,borderRadius:20,background:"#fff",border:"1px solid #e2e8f0",boxShadow:"0 8px 30px rgba(15,23,42,.05)"}}/>)}</div><div style={{height:280,borderRadius:22,background:"#fff",border:"1px solid #e2e8f0",boxShadow:"0 8px 30px rgba(15,23,42,.05)"}}/></section><style>{`@keyframes portalShimmer{to{background-position-x:-200%}} @media(prefers-reduced-motion:reduce){*{animation:none!important}}`}</style></main>
}

export function PortalError({ role, error, reset, homeHref, signInHref }: { role: string; error: Error & { digest?: string }; reset: () => void; homeHref: string; signInHref: string }) {
  return <main style={{minHeight:"100dvh",background:"#f8fafc",display:"grid",placeItems:"center",padding:24}}><section role="alert" style={{width:"100%",maxWidth:460,background:"#fff",border:"1px solid #e2e8f0",borderRadius:24,padding:"28px 24px",boxShadow:"0 20px 60px rgba(15,23,42,.10)"}}><div style={{width:48,height:48,borderRadius:16,display:"grid",placeItems:"center",background:"#fef3c7",color:"#92400e",fontSize:22,fontWeight:900,marginBottom:18}}>!</div><p style={{margin:"0 0 6px",fontSize:12,fontWeight:800,letterSpacing:1,textTransform:"uppercase",color:"#64748b"}}>{role} workspace</p><h1 style={{margin:"0 0 10px",fontSize:24,lineHeight:1.2,color:"#0f172a"}}>This page could not open</h1><p style={{margin:"0 0 22px",fontSize:14,lineHeight:1.6,color:"#64748b"}}>Your session is protected. Retry first. If the problem continues, return to the workspace home or sign in again.</p>{error.digest&&<p style={{fontSize:11,color:"#94a3b8",margin:"0 0 18px"}}>Reference: {error.digest}</p>}<div style={{display:"grid",gap:10}}><button onClick={reset} style={{minHeight:46,border:0,borderRadius:12,background:"#10b981",color:"#fff",fontWeight:800,cursor:"pointer"}}>Retry</button><button onClick={()=>{window.location.href=homeHref}} style={{minHeight:46,border:"1px solid #cbd5e1",borderRadius:12,background:"#fff",color:"#0f172a",fontWeight:750,cursor:"pointer"}}>Return to workspace</button><button onClick={()=>{window.location.href=signInHref}} style={{minHeight:44,border:0,background:"transparent",color:"#475569",fontWeight:700,cursor:"pointer"}}>Sign in again</button></div></section></main>
}
