import type { Metadata } from 'next'
import Link from 'next/link'
import { PublicHeader } from '@/components/public/PublicHeader'
import { PublicFooter } from '@/components/public/PublicFooter'

export const metadata: Metadata = { title:'Responsible AI & Automation | VibeSchool', description:'How VibeSchool approaches AI, automation, evidence, human responsibility and learner safety.' }

const rules=[
['Assist, do not quietly decide','AI may help explain, organise, generate practice or suggest options. It should not silently create institutional authority or high-consequence educational truth.'],
['Evidence matters','When a claim can affect a learner, school or pathway decision, VibeSchool should distinguish sourced evidence from generated guidance.'],
['Human responsibility remains','Teachers, parents, school leaders and authorised operators remain responsible for decisions that require professional, safeguarding or institutional judgement.'],
['Uncertainty should be visible','A system should be able to say “uncertain”, “not verified” or “needs review” rather than force a confident answer.'],
['Protect learner information','AI features should receive only the data needed for the task and must respect the same role, relationship and privacy boundaries as the rest of VibeSchool.'],
['Measure real value','Automation is useful when it improves learning, reduces legitimate workload or strengthens consistency—not merely because it increases engagement or looks impressive.'],
]

export default function ResponsibleAIPage(){return <div className="page"><PublicHeader product="Responsible AI"/><main id="main-content"><section className="hero"><div className="wrap"><p className="eyebrow">RESPONSIBLE AI & AUTOMATION</p><h1>Technology should increase understanding without hiding responsibility.</h1><p className="lead">VibeSchool can use AI and automation to support learning and operations. Those systems must stay inside educational, privacy and authority boundaries rather than becoming a shortcut around them.</p></div></section><section className="section wrap"><p className="eyebrow dark">OPERATING PRINCIPLES</p><div className="grid">{rules.map(([t,d])=><article key={t}><h2>{t}</h2><p>{d}</p></article>)}</div></section><section className="section alt"><div className="wrap two"><div><p className="eyebrow dark">FOR LEARNERS</p><h2 className="big">AI support should help you learn, not impersonate your learning.</h2></div><div><p>Where an assessment or teacher expects independent work, AI assistance should not be used to misrepresent generated work as the learner’s own. Learning tools should prioritise explanation, practice, feedback and understanding.</p><p>Recommendations such as Pathways direction are guidance. They should explain their basis and limits rather than present themselves as destiny.</p></div></div></section><section className="section wrap"><div className="two"><div><p className="eyebrow dark">FOR INSTITUTIONS</p><h2 className="big">Automation needs authority, verification and an audit trail.</h2></div><div><p>Institutional automation should define what a system may observe, recommend or change; which policy authorises it; what evidence proves completion; when human approval is required; and how unsafe or incorrect actions are stopped or reversed.</p><Link className="text" href="/trust/security">Security & data governance →</Link></div></div></section><section className="report"><div className="wrap"><h2>Questions about AI use at VibeSchool?</h2><p>Ask what information a feature uses, whether output is guidance or a verified fact, and who remains responsible for the resulting decision.</p><div className="links"><Link href="/contact">Contact VibeSchool</Link><Link href="/trust">Trust Centre</Link><Link href="/legal/aup">Acceptable Use</Link></div></div></section></main><PublicFooter/><style>{styles}</style></div>}
const styles=`.page{background:#f8f8f5;color:#111827;font-family:var(--font-jakarta),Arial,sans-serif;line-height:1.7}.page *{box-sizing:border-box}.wrap{max-width:1080px;margin:auto}.hero{background:#07111f;color:#fff;padding:88px 24px}.eyebrow{font:850 11px var(--font-mono),monospace;letter-spacing:.15em;color:#d0b154}.eyebrow.dark{color:#755b17}h1,.big{font-family:var(--font-display),Arial,sans-serif;letter-spacing:-.04em;line-height:1.06}h1{font-size:clamp(41px,6vw,69px);max-width:900px;margin:14px 0 24px}.lead{font-size:18px;color:#c6cfda;max-width:780px}.section{padding:82px 24px}.grid{display:grid;grid-template-columns:repeat(2,1fr);gap:14px}.grid article{background:#fff;border:1px solid #e0e3e7;border-radius:14px;padding:27px}.grid h2{font-size:21px;margin:0 0 8px}.grid p,.two p{color:#5c6673}.alt{background:#eeeae0}.two{display:grid;grid-template-columns:1fr 1fr;gap:64px}.big{font-size:clamp(31px,4vw,47px);margin:10px 0}.text{font-weight:850;color:#6f5615;text-decoration:none}.report{background:#13243a;color:#fff;padding:62px 24px}.report h2{font-size:30px;margin:0}.report p{color:#c6cfda;max-width:780px}.links{display:flex;gap:18px;flex-wrap:wrap}.links a{color:#e4c96f;font-weight:800;text-decoration:none}@media(max-width:700px){.hero,.section{padding:60px 18px}.grid,.two{grid-template-columns:1fr}.two{gap:18px}}`