"use client"

import { useCallback, useEffect, useMemo, useState } from "react"
import type { CSSProperties, ReactNode } from "react"
import { hqSupabase } from "@/lib/hq/supabase"
import { HQPage, HQPanel, HQ_THEME as C, hqButtonStyle } from "@/components/hq/HQShell"

type Report = Record<string, any>
const sb=hqSupabase as any
const fmt=(n:unknown)=>typeof n==="number"?new Intl.NumberFormat("en-KE",{maximumFractionDigits:1}).format(n):"Not available"
const pct=(n:unknown)=>typeof n==="number"?`${(n*100).toFixed(1)}%`:"Not enough data yet"
const metricLabels:Record<string,string>={dau:"Active today",wau:"Active this week",mau:"Active this month",signups_day:"Signups today",activated_new_users_7d:"New users activated in 7 days",lesson_plans_created_day:"Lesson plans created today",lessons_completed_day:"Lessons completed today",homework_created_day:"Homework created today",homework_submissions_day:"Homework submissions today",assessments_created_day:"Assessments created today",assessments_released_day:"Assessments released today"}
const words=(v:unknown)=>{const raw=String(v??"");return metricLabels[raw.toLowerCase()]??raw.replaceAll("_"," ").replace(/\b\w/g,m=>m.toUpperCase())}
const safeArray=(v:unknown):any[]=>Array.isArray(v)?v:[]
const count=(v:unknown)=>typeof v==="number"?v:null

function Metric({label,value,note,tone=C.green}:{label:string;value:ReactNode;note?:string;tone?:string}){return <div style={{padding:14,border:`1px solid ${C.border}`,borderRadius:14,background:C.panelSoft}}><div style={{fontSize:23,fontWeight:950,color:tone}}>{value}</div><div style={{fontSize:11,fontWeight:900,marginTop:5}}>{label}</div>{note&&<div style={{fontSize:10,color:C.muted,marginTop:4,lineHeight:1.45}}>{note}</div>}</div>}
function Rows({rows,empty="Nothing needs attention in this area."}:{rows:any[];empty?:string}){if(!rows.length)return <div style={{padding:14,color:C.muted,fontSize:11}}>{empty}</div>;return <div>{rows.slice(0,12).map((r,i)=><div key={r.id??r.work_id??r.case_no??i} style={{padding:"11px 14px",borderTop:i?`1px solid ${C.border}`:0}}><div style={{fontSize:11.5,fontWeight:850}}>{r.title??r.finding??words(r.key)??`Case ${r.case_no??""}`}</div><div style={{fontSize:10.5,color:C.muted,marginTop:4,lineHeight:1.5}}>{r.explanation??r.why_it_matters??r.recommended_action??words(r.status)??"Review the supporting evidence."}</div></div>)}</div>}
function Evidence({value}:{value:unknown}){if(value==null)return null;return <details style={{marginTop:8}}><summary style={{cursor:"pointer",fontSize:10.5,color:C.blue}}>View technical evidence</summary><pre style={pre}>{JSON.stringify(value,null,2)}</pre></details>}
function Brief({label,children,evidence}:{label:string;children:ReactNode;evidence?:unknown}){return <div style={{padding:14,borderBottom:`1px solid ${C.border}`}}><div style={{fontSize:10,fontWeight:950,color:C.muted,textTransform:"uppercase",letterSpacing:".08em"}}>{label}</div><div style={{marginTop:7,fontSize:12,lineHeight:1.6}}>{children}</div><Evidence value={evidence}/></div>}

export default function HQIntelligencePage(){
 const[report,setReport]=useState<Report|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState("")
 const refresh=useCallback(async()=>{setLoading(true);setError("");try{const{data,error}=await sb.rpc("hq_get_seven_day_owner_report");if(error)throw error;setReport(data as Report)}catch{setError("Company intelligence could not be refreshed. Nothing was changed. Try again.")}finally{setLoading(false)}},[])
 useEffect(()=>{void refresh()},[refresh])
 const d=report?.executive_dashboard??{},h=d.headline??{},comp=d.composition??{},growth=d.growth_vs_activation??{},er=d.engagement_vs_retention??{},finance=report?.finance??{},product=report?.product_engagement??{},ops=report?.operations??{},out=report?.outstanding??{},brief=report?.executive_questions??{},control=report?.control_plane??{},goals=report?.goals??{}
 const findings=safeArray(out.findings??d.declining_kpis),work=safeArray(out.work??d.action_required),incidents=safeArray(out.incidents),support=safeArray(out.support_cases),lineage=safeArray(d.metric_lineage)
 const roleEntries=useMemo(()=>Object.entries(comp.accounts_by_role??{}).sort((a:any,b:any)=>b[1]-a[1]),[comp.accounts_by_role])
 const signups=count(growth.signups_7d),activated=count(growth.activated_new_users_7d),activation=count(growth.activation_rate)
 const happened=`${fmt(h.dau)} active today, ${fmt(h.wau)} active this week and ${fmt(h.mau)} active this month.${signups!==null?` ${fmt(signups)} people signed up in the last 7 days.`:""}`
 const grew=typeof brief.what_grew==="string"?brief.what_grew:count(brief.what_grew?.reading_sessions)!==null?`${fmt(brief.what_grew.reading_sessions)} reading sessions were recorded in the growth view.`:"No verified growth signal is available for this reporting period."
 const declined=findings.length?(findings[0].title??findings[0].finding??"A material metric needs attention."):activation!==null&&activation<.3?`New-user activation needs attention. ${fmt(signups)} people signed up in the last 7 days and ${fmt(activated)} became active (${pct(activation)}).`:"No material decline is currently surfaced by the owner report."
 const broke=incidents.length?`${incidents.length} unresolved incident${incidents.length===1?"":"s"} need review.`:"Nothing broke. No unresolved product or infrastructure incident is recorded for this reporting period."
 const why=findings.length?(findings[0].explanation??findings[0].why_it_matters??findings[0].recommended_action??"The evidence shows a material exception, but HQ has not established a confirmed cause yet."):"No confirmed cause requires founder attention in the current evidence set."
 const d1=count(h.d1_retention),d7=count(h.d7_retention)
 if(loading&&!report)return <main className="hq-page" style={{display:"grid",placeItems:"center"}}>Loading company intelligence…</main>
 return <HQPage title="Decision Intelligence" description="Understand what is happening, why it matters and what needs action." actions={<button onClick={()=>void refresh()} style={hqButtonStyle} disabled={loading}>{loading?"Refreshing…":"Refresh HQ"}</button>}>
  {error&&<div role="alert" style={{padding:12,border:`1px solid ${C.red}`,borderRadius:12,color:C.red,marginBottom:14}}>{error}</div>}
  <section><div style={title}>Company activity</div><div style={grid}><Metric label="Active today" value={fmt(h.dau)} note="People who meaningfully used VibeSchool today"/><Metric label="Active this week" value={fmt(h.wau)} tone={C.blue}/><Metric label="Active this month" value={fmt(h.mau)} tone={C.violet}/><Metric label="New-user activation" value={pct(activation)} note={signups!==null&&activated!==null?`${activated} of ${signups} new users became active`:"Activation cohort is not available yet"} tone={activation!==null&&activation<.3?C.red:C.green}/><Metric label="Next-day retention" value={d1===null?"Not enough data yet":pct(d1)} note={d1===null?"No reliable completed cohort is available yet":undefined} tone={d1!==null&&d1<.2?C.amber:C.green}/><Metric label="7-day retention" value={d7===null?"Not enough data yet":pct(d7)} note={d7===null?"No reliable completed 7-day cohort is available yet":undefined} tone={d7!==null&&d7<.15?C.amber:C.green}/><Metric label="Open incidents" value={incidents.length} note={incidents.length?"Incidents need review":"No unresolved incidents recorded"} tone={incidents.length?C.red:C.green}/><Metric label="Open work" value={work.length} note={work.length?"Open company work awaiting completion or verification":"No open work surfaced"} tone={work.length?C.amber:C.green}/></div></section>
  <section style={{marginTop:24}}><div style={title}>Founder morning brief</div><HQPanel><Brief label="What happened">{happened}</Brief><Brief label="What grew" evidence={typeof brief.what_grew==="object"?brief.what_grew:undefined}>{grew}</Brief><Brief label="What declined" evidence={findings[0]}>{declined}</Brief><Brief label="What broke" evidence={incidents.length?incidents:undefined}>{broke}</Brief><Brief label="Why" evidence={findings[0]?.evidence}>{why}</Brief><Brief label="Decision required" evidence={typeof brief.what_decision_is_required==="object"?brief.what_decision_is_required:undefined}>{typeof brief.what_decision_is_required==="string"?brief.what_decision_is_required:work.length?`${work.length} open work item${work.length===1?"":"s"} may require review. Open the intervention queue below for accountable actions.`:"No founder decision is currently required."}</Brief><Brief label="Automatically handled" evidence={typeof brief.what_was_automatically_done==="object"?brief.what_was_automatically_done:undefined}>{typeof brief.what_was_automatically_done==="string"?brief.what_was_automatically_done:"No verified automatic action is reported for this period."}</Brief><Brief label="Did it work?" evidence={typeof brief.did_it_work==="object"?brief.did_it_work:undefined}>{typeof brief.did_it_work==="string"?brief.did_it_work:"Verification evidence is not available yet."}</Brief></HQPanel></section>
  <section style={{marginTop:24}}><div style={title}>Live operations</div><div style={grid}><Metric label="Open support cases" value={fmt(ops.support?.open_cases)}/><Metric label="SLA breaches" value={fmt(ops.support?.sla_breaches)} tone={ops.support?.sla_breaches?C.red:C.green}/><Metric label="Critical support" value={fmt(ops.support?.critical_cases)} tone={ops.support?.critical_cases?C.red:C.green}/><Metric label="Notifications pending" value={fmt(ops.notifications?.pending)}/><Metric label="Notification failures · 24h" value={fmt(ops.notifications?.failed_24h)} tone={ops.notifications?.failed_24h?C.red:C.green}/><Metric label="Delivered · 24h" value={fmt(ops.notifications?.delivered_24h)}/><Metric label="Payment attempts · 7d" value={fmt(ops.payments?.attempts_7d)}/><Metric label="Payment failures · 7d" value={fmt(ops.payments?.failed_7d)} tone={ops.payments?.failed_7d?C.red:C.green}/></div></section>
  <section style={{marginTop:24}}><div style={title}>Intervention queue</div><div style={two}><HQPanel title="Incidents" description="Broken journeys and operational failures"><Rows rows={incidents}/></HQPanel><HQPanel title="Priority findings" description="Exceptions with business impact"><Rows rows={findings}/></HQPanel><HQPanel title="Accountable work" description="Owner, action and verification path"><Rows rows={work}/></HQPanel><HQPanel title="Customer voice" description="Open support and experience signals"><Rows rows={support}/></HQPanel></div></section>
  <section style={{marginTop:24}}><div style={title}>Growth & retention</div><div style={grid}><Metric label="Signups · 7 days" value={fmt(signups)}/><Metric label="New users activated · 7 days" value={fmt(activated)}/><Metric label="Activation rate" value={pct(activation)} tone={activation!==null&&activation<.3?C.red:C.green}/><Metric label="Returned next day" value={fmt(er.retention?.retained_d1)} note={`${fmt(er.retention?.eligible_d1)} eligible`}/><Metric label="Returned after 7 days" value={fmt(er.retention?.retained_d7)} note={`${fmt(er.retention?.eligible_d7)} eligible`}/></div></section>
  <section style={{marginTop:24}}><div style={title}>Audience composition</div><div style={grid}>{roleEntries.map(([role,n])=><Metric key={role} label={`${words(role)} accounts`} value={fmt(n)}/>)}</div></section>
  <section style={{marginTop:24}}><div style={title}>Learning & product evidence</div><div style={grid}><Metric label="Reading sessions · 7d" value={fmt(product.vibelearn?.reading_sessions)}/><Metric label="Active reading seconds" value={fmt(product.vibelearn?.active_seconds)}/><Metric label="Adaptive sessions" value={fmt(product.twin?.adaptive_sessions)}/><Metric label="Twin sessions" value={fmt(product.twin?.twin_sessions)}/><Metric label="VibeLab starts" value={fmt(product.vibelabs?.sessions_started)}/><Metric label="VibeLab completions" value={fmt(product.vibelabs?.sessions_completed)}/><Metric label="Published resources" value={fmt(comp.publications_by_status?.published)}/><Metric label="Draft resources" value={fmt(comp.publications_by_status?.draft)} tone={C.amber}/></div></section>
  <section style={{marginTop:24}}><div style={title}>Business truth</div><div style={grid}><Metric label="MRR" value={`KES ${fmt(finance.mrr)}`}/><Metric label="Cash received · 30d" value={`KES ${fmt(finance.cash_received_30d)}`}/><Metric label="Outstanding invoices" value={`KES ${fmt(finance.outstanding_invoices)}`} tone={finance.outstanding_invoices?C.amber:C.green}/><Metric label="Active subscriptions" value={fmt(finance.active_subscriptions)}/></div></section>
  <section style={{marginTop:24}}><div style={title}>Governance & goals</div><div style={two}><HQPanel title="Control plane" description="Simple status first; technical evidence is optional"><Brief label="Current state" evidence={control}>{Object.keys(control).length?"Governance evidence is available. Open technical evidence only when you need implementation detail.":"No control-plane evidence is available right now."}</Brief></HQPanel><HQPanel title="Company goals" description="Target progress and strategic accountability"><Brief label="Goal status" evidence={goals}>{Object.keys(goals).length?"Company goal evidence is available for review.":"No company goals are currently reported."}</Brief></HQPanel></div></section>
  <section style={{marginTop:24}}><div style={title}>Metric trust & provenance</div><HQPanel title="Certified metric definitions" description="Definitions and sources behind executive numbers"><Rows rows={lineage}/></HQPanel></section>
  <footer style={{marginTop:22,textAlign:"center",fontSize:10,color:C.muted}}>Updated {report?.generated_at?new Date(report.generated_at).toLocaleString("en-KE"):"time unavailable"} · source-backed · owner-gated</footer>
 </HQPage>
}
const grid:CSSProperties={display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(145px,1fr))",gap:9}
const two:CSSProperties={display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(min(100%,360px),1fr))",gap:10}
const title:CSSProperties={fontSize:10.5,fontWeight:950,color:"rgba(255,255,255,.4)",letterSpacing:".09em",textTransform:"uppercase",marginBottom:9}
const pre:CSSProperties={margin:"8px 0 0",padding:12,whiteSpace:"pre-wrap",overflowWrap:"anywhere",fontSize:10,lineHeight:1.5,color:C.muted,fontFamily:"ui-monospace,SFMono-Regular,Menlo,monospace",maxHeight:280,overflow:"auto"}
