"use client"

import { useCallback, useEffect, useMemo, useState } from "react"
import type { CSSProperties } from "react"
import { hqSupabase } from "@/lib/hq/supabase"
import { HQPage, HQPanel, HQ_THEME as C, hqButtonStyle } from "@/components/hq/HQShell"

type Report = Record<string, any>
const sb = hqSupabase as any
const fmt=(n:unknown)=>typeof n==="number"?new Intl.NumberFormat("en-KE",{maximumFractionDigits:1}).format(n):String(n??"—")
const pct=(n:unknown)=>typeof n==="number"?`${(n*100).toFixed(1)}%`:"—"
function Metric({label,value,note,tone=C.green}:{label:string;value:unknown;note?:string;tone?:string}){return <div style={{padding:14,border:`1px solid ${C.border}`,borderRadius:14,background:C.panelSoft}}><div style={{fontSize:23,fontWeight:950,color:tone}}>{fmt(value)}</div><div style={{fontSize:11,fontWeight:900,marginTop:5}}>{label}</div>{note&&<div style={{fontSize:10,color:C.muted,marginTop:4,lineHeight:1.45}}>{note}</div>}</div>}
function Rows({rows,empty="No evidence in this lane."}:{rows:any[];empty?:string}){if(!rows?.length)return <div style={{padding:14,color:C.muted,fontSize:11}}>{empty}</div>;return <div>{rows.slice(0,12).map((r,i)=><div key={r.id??r.work_id??r.case_no??r.key??r.source??i} style={{padding:"11px 14px",borderTop:i?`1px solid ${C.border}`:0}}><div style={{fontSize:11.5,fontWeight:850}}>{r.title??r.finding??r.key??r.source??`Case ${r.case_no??""}`}</div><div style={{fontSize:10.5,color:C.muted,marginTop:4,lineHeight:1.5}}>{r.explanation??r.why_it_matters??r.recommended_action??r.department??r.category??r.definition??r.status??(r.accounts!=null?`${fmt(r.accounts)} accounts`:"")}</div></div>)}</div>}
function Brief({label,value}:{label:string;value:unknown}){return <div style={{padding:12,borderBottom:`1px solid ${C.border}`}}><div style={{fontSize:10,fontWeight:950,color:C.muted,textTransform:"uppercase",letterSpacing:".08em"}}>{label}</div><div style={{marginTop:5,fontSize:11.5,lineHeight:1.55}}>{typeof value==="string"?value:JSON.stringify(value??"—")}</div></div>}

export default function HQIntelligencePage(){
 const [report,setReport]=useState<Report|null>(null),[measurement,setMeasurement]=useState<Report|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState("")
 const refresh=useCallback(async()=>{setLoading(true);setError("");try{const [owner,measure]=await Promise.all([sb.rpc("hq_get_seven_day_owner_report"),sb.rpc("hq_measurement_founder_command",{p_days:30})]);if(owner.error)throw owner.error;if(measure.error)throw measure.error;setReport(owner.data as Report);setMeasurement(measure.data as Report)}catch(e){setError(e instanceof Error?e.message:"Intelligence could not be loaded")}finally{setLoading(false)}},[])
 useEffect(()=>{void refresh()},[refresh])
 const d=report?.executive_dashboard??{},h=d.headline??{},comp=d.composition??{},growth=d.growth_vs_activation??{},er=d.engagement_vs_retention??{},finance=report?.finance??{},product=report?.product_engagement??{},ops=report?.operations??{},out=report?.outstanding??{},brief=report?.executive_questions??{},control=report?.control_plane??{},goals=report?.goals??{}
 const m=measurement??{},acq=m.acquisition??{},activation=m.activation??{},ret=m.retention??{},sessions=m.sessions??{},experiments=m.experiments??{},roleValue=m.role_value??{}
 const findings=(out.findings??d.declining_kpis??[]) as any[],work=(out.work??d.action_required??[]) as any[],incidents=(out.incidents??[]) as any[],support=(out.support_cases??[]) as any[]
 const lineage=[...((d.metric_lineage??[]) as any[]),...((m.lineage??[]) as any[])],anomalies=((m.anomalies??[]) as any[]).filter((x:any)=>x.active)
 const roleEntries=useMemo(()=>Object.entries(comp.accounts_by_role??{}).sort((a:any,b:any)=>b[1]-a[1]),[comp.accounts_by_role])
 if(loading&&!report)return <main className="hq-page" style={{display:"grid",placeItems:"center"}}>Loading company intelligence…</main>
 return <HQPage title="Decision Intelligence" description="Founder operating system · observe, explain, decide, act, verify" actions={<button onClick={()=>void refresh()} style={hqButtonStyle}>Refresh intelligence</button>}>
  {error&&<div role="alert" style={{padding:12,border:`1px solid ${C.red}`,borderRadius:12,color:C.red,marginBottom:14}}>{error}</div>}
  <section><div style={title}>North-star command strip</div><div style={grid}><Metric label="Operational DAU" value={h.dau}/><Metric label="Operational WAU" value={h.wau} tone={C.blue}/><Metric label="Operational MAU" value={h.mau} tone={C.violet}/><Metric label="Certified session DAU" value={sessions.dau}/><Metric label="Open incidents" value={incidents.length} tone={incidents.length?C.red:C.green}/><Metric label="Open work" value={work.length} tone={work.length?C.amber:C.green}/></div></section>
  <section style={{marginTop:24}}><div style={title}>Certified growth kernel</div><div style={grid}><Metric label="New accounts · 30d" value={acq.new_accounts}/><Metric label="Attribution coverage" value={pct(acq.attribution_coverage)} note={`${fmt(acq.attributed_accounts)} accounts with source/referrer`}/><Metric label="Session activation" value={pct(activation.rate)} note={`${fmt(activation.activated_with_session_7d)} of ${fmt(activation.new_accounts)} post-kernel signups`}/><Metric label="D1 retention" value={pct(ret.d1_rate)} note={`${fmt(ret.retained_d1)} / ${fmt(ret.eligible_d1)} eligible`}/><Metric label="D7 retention" value={pct(ret.d7_rate)} note={`${fmt(ret.retained_d7)} / ${fmt(ret.eligible_d7)} eligible`}/><Metric label="D30 retention" value={pct(ret.d30_rate)} note={`${fmt(ret.retained_d30)} / ${fmt(ret.eligible_d30)} eligible`}/><Metric label="Certified WAU" value={sessions.wau}/><Metric label="Certified MAU" value={sessions.mau}/></div><div style={{fontSize:10,color:C.muted,marginTop:8}}>Certified from {m.certified_from?new Date(m.certified_from).toLocaleString("en-KE"):"—"}. Pre-kernel retention is not backfilled or inferred from login timestamps.</div></section>
  <section style={{marginTop:24}}><div style={title}>Acquisition & experiments</div><div style={two}><HQPanel title="First-touch sources" description="UTM source or external referrer host; no full URLs stored"><Rows rows={acq.first_touch_sources??[]} empty="No post-kernel attributed accounts yet."/></HQPanel><HQPanel title="Experiment registry" description={`${fmt(experiments.running)} running · ${fmt(experiments.assignments)} stable assignments · ${fmt(experiments.exposures_window)} exposures in window`}><Rows rows={experiments.registry??[]} empty="No governed experiments are running."/></HQPanel></div></section>
  <section style={{marginTop:24}}><div style={title}>Founder morning brief</div><HQPanel><Brief label="What happened" value={brief.what_happened}/><Brief label="What grew" value={brief.what_grew}/><Brief label="What declined" value={brief.what_declined}/><Brief label="What broke" value={brief.what_broke}/><Brief label="Why" value={brief.why}/><Brief label="Decision required" value={brief.what_decision_is_required}/><Brief label="Automatically handled" value={brief.what_was_automatically_done}/><Brief label="Did it work?" value={brief.did_it_work}/></HQPanel></section>
  <section style={{marginTop:24}}><div style={title}>Live operations</div><div style={grid}><Metric label="Open support cases" value={ops.support?.open_cases}/><Metric label="SLA breaches" value={ops.support?.sla_breaches} tone={ops.support?.sla_breaches?C.red:C.green}/><Metric label="Critical support" value={ops.support?.critical_cases} tone={ops.support?.critical_cases?C.red:C.green}/><Metric label="Notifications pending" value={ops.notifications?.pending}/><Metric label="Notification failures · 24h" value={ops.notifications?.failed_24h} tone={ops.notifications?.failed_24h?C.red:C.green}/><Metric label="Delivered · 24h" value={ops.notifications?.delivered_24h}/><Metric label="Payment attempts · 7d" value={ops.payments?.attempts_7d}/><Metric label="Payment failures · 7d" value={ops.payments?.failed_7d} tone={ops.payments?.failed_7d?C.red:C.green}/><Metric label="Security denials · 24h" value={ops.security?.denied_24h} tone={ops.security?.denied_24h?C.amber:C.green}/><Metric label="Runtime denials · 24h" value={ops.runtime?.denials_24h} tone={ops.runtime?.denials_24h?C.amber:C.green}/></div></section>
  <section style={{marginTop:24}}><div style={title}>Value creation</div><div style={grid}><Metric label="Teachers with class" value={roleValue.teachers_with_class}/><Metric label="Teachers creating value · 7d" value={roleValue.teachers_creating_value_7d}/><Metric label="Learners with value · 7d" value={roleValue.learners_with_value_7d}/><Metric label="Parents linked to learner" value={roleValue.parents_linked_to_learner}/><Metric label="Reading sessions · 7d" value={product.vibelearn?.reading_sessions}/><Metric label="Adaptive sessions" value={product.twin?.adaptive_sessions}/><Metric label="VibeLab completions" value={product.vibelabs?.sessions_completed}/><Metric label="Published resources" value={comp.publications_by_status?.published}/></div></section>
  <section style={{marginTop:24}}><div style={title}>Intervention queue</div><div style={two}><HQPanel title="Measurement anomalies" description="Thresholds activate only after sample-size gates"><Rows rows={anomalies} empty="No certified measurement anomaly is active."/></HQPanel><HQPanel title="Incidents" description="Broken journeys and operational failures"><Rows rows={incidents}/></HQPanel><HQPanel title="Priority findings" description="Exceptions with business impact"><Rows rows={findings}/></HQPanel><HQPanel title="Accountable work" description="Owner, action and verification path"><Rows rows={work}/></HQPanel><HQPanel title="Customer voice" description="Open support and experience signals"><Rows rows={support}/></HQPanel></div></section>
  <section style={{marginTop:24}}><div style={title}>Audience composition</div><div style={grid}>{roleEntries.map(([role,count])=><Metric key={role} label={`${role} accounts`} value={count}/>)}</div></section>
  <section style={{marginTop:24}}><div style={title}>Business truth</div><div style={grid}><Metric label="MRR" value={`KES ${fmt(finance.mrr)}`}/><Metric label="Cash received · 30d" value={`KES ${fmt(finance.cash_received_30d)}`}/><Metric label="Outstanding invoices" value={`KES ${fmt(finance.outstanding_invoices)}`} tone={finance.outstanding_invoices?C.amber:C.green}/><Metric label="Active subscriptions" value={finance.active_subscriptions}/><Metric label="New subscribers · 30d" value={finance.new_subscribers_30d}/><Metric label="Signup → paid" value={pct(finance.signup_to_subscription_conversion_30d)}/></div></section>
  <section style={{marginTop:24}}><div style={title}>Governance & goals</div><div style={two}><HQPanel title="Control plane" description="Worker/runtime controls and platform guardrails"><pre style={pre}>{JSON.stringify(control,null,2)}</pre></HQPanel><HQPanel title="Company goals" description="Target progress and strategic accountability"><pre style={pre}>{JSON.stringify(goals,null,2)}</pre></HQPanel></div></section>
  <section style={{marginTop:24}}><div style={title}>Metric trust & provenance</div><HQPanel title="Certified metric definitions" description="Every executive number has source, grain, definition and certification boundary"><Rows rows={lineage}/></HQPanel></section>
  <footer style={{marginTop:22,textAlign:"center",fontSize:10,color:C.muted}}>Generated {report?.generated_at?new Date(report.generated_at).toLocaleString("en-KE"):"—"} · privacy-minimized · source-backed · owner-gated</footer>
 </HQPage>
}
const grid:CSSProperties={display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(145px,1fr))",gap:9}
const two:CSSProperties={display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(min(100%,360px),1fr))",gap:10}
const title:CSSProperties={fontSize:10.5,fontWeight:950,color:"rgba(255,255,255,.4)",letterSpacing:".09em",textTransform:"uppercase",marginBottom:9}
const pre:CSSProperties={margin:0,padding:14,whiteSpace:"pre-wrap",fontSize:10.5,lineHeight:1.5,color:C.muted,fontFamily:"ui-monospace,SFMono-Regular,Menlo,monospace"}
