"use client"

import { useCallback, useEffect, useMemo, useState } from "react"
import type { CSSProperties } from "react"
import { hqSupabase } from "@/lib/hq/supabase"
import { HQPage, HQPanel, HQ_THEME as C, hqButtonStyle } from "@/components/hq/HQShell"

type Report = Record<string, any>
const sb = hqSupabase as any
const fmt=(n:unknown)=>typeof n==="number"?new Intl.NumberFormat("en-KE",{maximumFractionDigits:1}).format(n):String(n??"—")
const pct=(n:unknown)=>typeof n==="number"?`${(n*100).toFixed(1)}%`:"—"
const words=(s:string)=>s.replaceAll("_"," ").replace(/\b\w/g,m=>m.toUpperCase())
function Metric({label,value,note,tone=C.green}:{label:string;value:unknown;note?:string;tone?:string}){return <div style={{padding:14,border:`1px solid ${C.border}`,borderRadius:14,background:C.panelSoft}}><div style={{fontSize:23,fontWeight:950,color:tone}}>{fmt(value)}</div><div style={{fontSize:11,fontWeight:900,marginTop:5}}>{label}</div>{note&&<div style={{fontSize:10,color:C.muted,marginTop:4,lineHeight:1.45}}>{note}</div>}</div>}
function Rows({rows,empty="Nothing needs attention in this area."}:{rows:any[];empty?:string}){if(!rows?.length)return <div style={{padding:14,color:C.muted,fontSize:11}}>{empty}</div>;return <div>{rows.slice(0,12).map((r,i)=><div key={r.id??r.work_id??r.case_no??i} style={{padding:"11px 14px",borderTop:i?`1px solid ${C.border}`:0}}><div style={{fontSize:11.5,fontWeight:850}}>{r.title??r.finding??r.key??`Case ${r.case_no??""}`}</div><div style={{fontSize:10.5,color:C.muted,marginTop:4,lineHeight:1.5}}>{r.explanation??r.why_it_matters??r.recommended_action??r.department??r.category??r.definition??r.status??""}</div></div>)}</div>}
function HumanValue({value}:{value:unknown}){
 if(value===null||value===undefined)return <>No information is available yet.</>
 if(typeof value==="string"||typeof value==="number"||typeof value==="boolean")return <>{String(value)}</>
 if(Array.isArray(value)){if(!value.length)return <>Nothing was reported.</>;return <div style={{display:"grid",gap:8}}>{value.slice(0,8).map((v,i)=><HumanCard key={i} value={v}/>)}</div>}
 if(typeof value==="object")return <HumanCard value={value as Record<string,unknown>}/>
 return <>Information unavailable.</>
}
function HumanCard({value}:{value:unknown}){if(!value||typeof value!=="object")return <div>{String(value??"—")}</div>;const o=value as Record<string,unknown>;const title=String(o.title??o.finding??o.message??o.status??"");const explanation=o.explanation??o.why_it_matters??o.recommended_action??o.evidence;return <div style={{padding:10,border:`1px solid ${C.border}`,borderRadius:10,background:C.panelSoft}}>{title&&<strong style={{display:"block",fontSize:11.5}}>{title}</strong>}{typeof explanation==="string"&&<span style={{display:"block",marginTop:4,color:C.muted}}>{explanation}</span>}<div style={{display:"flex",flexWrap:"wrap",gap:8,marginTop:6}}>{Object.entries(o).filter(([k,v])=>!["id","snapshot_id","title","finding","message","explanation","why_it_matters","recommended_action","evidence"].includes(k)&&["string","number","boolean"].includes(typeof v)).slice(0,8).map(([k,v])=><span key={k} style={{fontSize:9.5,color:C.muted}}><b style={{color:C.text}}>{words(k)}:</b> {String(v)}</span>)}</div></div>}
function Brief({label,value}:{label:string;value:unknown}){return <div style={{padding:12,borderBottom:`1px solid ${C.border}`}}><div style={{fontSize:10,fontWeight:950,color:C.muted,textTransform:"uppercase",letterSpacing:".08em"}}>{label}</div><div style={{marginTop:7,fontSize:11.5,lineHeight:1.55}}><HumanValue value={value}/></div></div>}

export default function HQIntelligencePage(){
 const [report,setReport]=useState<Report|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState("")
 const refresh=useCallback(async()=>{setLoading(true);setError("");try{const {data,error}=await sb.rpc("hq_get_seven_day_owner_report");if(error)throw error;setReport(data as Report)}catch{setError("Company intelligence could not be loaded. Nothing was changed. Try again.")}finally{setLoading(false)}},[])
 useEffect(()=>{void refresh()},[refresh])
 const d=report?.executive_dashboard??{},h=d.headline??{},comp=d.composition??{},growth=d.growth_vs_activation??{},er=d.engagement_vs_retention??{},finance=report?.finance??{},product=report?.product_engagement??{},ops=report?.operations??{},out=report?.outstanding??{},brief=report?.executive_questions??{},control=report?.control_plane??{},goals=report?.goals??{}
 const findings=(out.findings??d.declining_kpis??[]) as any[],work=(out.work??d.action_required??[]) as any[],incidents=(out.incidents??[]) as any[],support=(out.support_cases??[]) as any[],lineage=(d.metric_lineage??[]) as any[]
 const roleEntries=useMemo(()=>Object.entries(comp.accounts_by_role??{}).sort((a:any,b:any)=>b[1]-a[1]),[comp.accounts_by_role])
 if(loading&&!report)return <main className="hq-page" style={{display:"grid",placeItems:"center"}}>Loading company intelligence…</main>
 return <HQPage title="Company Intelligence" description="What happened, what matters, what needs you, and what should happen next." actions={<button onClick={()=>void refresh()} style={hqButtonStyle}>Refresh</button>}>
  {error&&<div role="alert" style={{padding:12,border:`1px solid ${C.red}`,borderRadius:12,color:C.red,marginBottom:14}}>{error}</div>}
  <section><div style={title}>VibeSchool now</div><div style={grid}><Metric label="Daily active users" value={h.dau}/><Metric label="Weekly active users" value={h.wau} tone={C.blue}/><Metric label="Monthly active users" value={h.mau} tone={C.violet}/><Metric label="New-user activation · 7d" value={pct(growth.activation_rate)} note={`${fmt(growth.activated_new_users_7d)} of ${fmt(growth.signups_7d)} new users became active`} tone={(growth.activation_rate??1)<.3?C.red:C.green}/><Metric label="Open incidents" value={incidents.length} tone={incidents.length?C.red:C.green}/><Metric label="Open work" value={work.length} tone={work.length?C.amber:C.green}/></div></section>
  <section style={{marginTop:24}}><div style={title}>Founder morning brief</div><HQPanel><Brief label="What happened" value={brief.what_happened}/><Brief label="What improved" value={brief.what_grew}/><Brief label="What declined" value={brief.what_declined}/><Brief label="What broke" value={brief.what_broke}/><Brief label="Why it matters" value={brief.why}/><Brief label="What needs your decision" value={brief.what_decision_is_required}/><Brief label="Handled automatically" value={brief.what_was_automatically_done}/><Brief label="Did it work?" value={brief.did_it_work}/></HQPanel></section>
  <section style={{marginTop:24}}><div style={title}>Needs attention</div><div style={two}><HQPanel title="Incidents" description="Confirmed failures"><Rows rows={incidents}/></HQPanel><HQPanel title="Priority findings" description="Evidence-backed business problems"><Rows rows={findings}/></HQPanel><HQPanel title="Accountable work" description="Work already assigned"><Rows rows={work}/></HQPanel><HQPanel title="Customer voice" description="Open support signals"><Rows rows={support}/></HQPanel></div></section>
  <section style={{marginTop:24}}><div style={title}>Growth & retention</div><div style={grid}><Metric label="Signups · 7d" value={growth.signups_7d}/><Metric label="Activated · 7d" value={growth.activated_new_users_7d}/><Metric label="Activation rate" value={pct(growth.activation_rate)} tone={(growth.activation_rate??1)<.3?C.red:C.green}/><Metric label="D1 retained" value={er.retention?.retained_d1} note={`${fmt(er.retention?.eligible_d1)} eligible`}/><Metric label="D7 retained" value={er.retention?.retained_d7} note={`${fmt(er.retention?.eligible_d7)} eligible`}/><Metric label="D30 retained" value={er.retention?.retained_d30} note={`${fmt(er.retention?.eligible_d30)} eligible`}/></div></section>
  <section style={{marginTop:24}}><div style={title}>Audience</div><div style={grid}>{roleEntries.map(([role,count])=><Metric key={role} label={`${words(role)} accounts`} value={count}/>)}</div></section>
  <section style={{marginTop:24}}><div style={title}>Learning & product evidence</div><div style={grid}><Metric label="Reading sessions · 7d" value={product.vibelearn?.reading_sessions}/><Metric label="Active reading seconds" value={product.vibelearn?.active_seconds}/><Metric label="Adaptive sessions" value={product.twin?.adaptive_sessions}/><Metric label="Twin sessions" value={product.twin?.twin_sessions}/><Metric label="VibeLab starts" value={product.vibelabs?.sessions_started}/><Metric label="VibeLab completions" value={product.vibelabs?.sessions_completed}/><Metric label="Published resources" value={comp.publications_by_status?.published}/><Metric label="Draft resources" value={comp.publications_by_status?.draft} tone={C.amber}/></div></section>
  <section style={{marginTop:24}}><div style={title}>Business truth</div><div style={grid}><Metric label="MRR" value={`KES ${fmt(finance.mrr)}`}/><Metric label="Cash received · 30d" value={`KES ${fmt(finance.cash_received_30d)}`}/><Metric label="Outstanding invoices" value={`KES ${fmt(finance.outstanding_invoices)}`} tone={finance.outstanding_invoices?C.amber:C.green}/><Metric label="Active subscriptions" value={finance.active_subscriptions}/><Metric label="New subscribers · 30d" value={finance.new_subscribers_30d}/><Metric label="Signup → paid" value={pct(finance.signup_to_subscription_conversion_30d)}/></div></section>
  <section style={{marginTop:24}}><div style={title}>Governance & goals</div><div style={two}><HQPanel title="Control plane" description="Current safeguards and runtime state"><HumanValue value={control}/></HQPanel><HQPanel title="Company goals" description="Targets and progress"><HumanValue value={goals}/></HQPanel></div></section>
  <section style={{marginTop:24}}><div style={title}>Metric trust</div><HQPanel title="Definitions & sources" description="How executive numbers are calculated"><Rows rows={lineage}/></HQPanel></section>
  <footer style={{marginTop:22,textAlign:"center",fontSize:10,color:C.muted}}>Updated {report?.generated_at?new Date(report.generated_at).toLocaleString("en-KE"):"—"} · owner-authorized evidence</footer>
 </HQPage>
}
const grid:CSSProperties={display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(145px,1fr))",gap:9}
const two:CSSProperties={display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(min(100%,360px),1fr))",gap:10}
const title:CSSProperties={fontSize:10.5,fontWeight:950,color:"rgba(255,255,255,.4)",letterSpacing:".09em",textTransform:"uppercase",marginBottom:9}
