'use client'

import { useEffect, useState } from 'react'
import { useRouter } from 'next/navigation'
import type { VibeTwinProps, TwinMode } from './types'
import { useTwinSession } from './hooks/useTwinSession'
import { useTwinSpeech } from './hooks/useTwinSpeech'
import { useTwinRecognition } from './hooks/useTwinRecognition'
import TwinHeader from './ui/TwinHeader'
import TwinInput from './ui/TwinInput'
import TwinLearningCanvas from './ui/TwinLearningCanvas'
import { T } from './ui/TwinHeader'
import { routeTwinCore, type TwinCoreRouteResult } from '@/lib/student/twinCore'
import { answerAdaptivePracticeQuestion, generateAdaptivePracticeQuestion, getAdaptiveTeachingTurn, getLearnerTwinState, type AdaptivePracticeQuestion, type AdaptiveTeachingTurn, type LearnerTwinState } from '@/lib/student/twin'
import { askLearnerTwinWithSession, type LearnerTwinChatMessage } from '@/lib/student/twinAuthority'
import { consumeTwinSession, getTwinPolicyState } from '@/lib/student/twinPolicy'

export default function VibeTwin({ isOpen, onClose, userName, learnerState }: VibeTwinProps) {
  const router = useRouter()
  const [input,setInput]=useState(''); const [mode,setMode]=useState<TwinMode>('text'); const [resolvedState,setResolvedState]=useState<LearnerTwinState|null>(learnerState??null); const [practiceQuestion,setPracticeQuestion]=useState<AdaptivePracticeQuestion|null>(null); const [practiceLoading,setPracticeLoading]=useState(false); const [practiceFeedback,setPracticeFeedback]=useState<string|null>(null); const [sessionSummary,setSessionSummary]=useState<string|null>(null); const [coreResult,setCoreResult]=useState<TwinCoreRouteResult|null>(null); const [hintIndex,setHintIndex]=useState(0); const [coachTurn,setCoachTurn]=useState<AdaptiveTeachingTurn|null>(null); const [coachStage,setCoachStage]=useState(0); const [policyBlocked,setPolicyBlocked]=useState(false); const [policyMessage,setPolicyMessage]=useState(''); const [sessionAuthorized,setSessionAuthorized]=useState(false)
  const { messages,twinState,setTwinState,greeted,setGreeted,addMessage,acquireProcessing,releaseProcessing,sessionId } = useTwinSession(isOpen)
  const { speak,cancel:cancelSpeech }=useTwinSpeech()

  useEffect(()=>{
    if(!isOpen){setMode('text');setInput('');setPracticeQuestion(null);setPracticeFeedback(null);setSessionSummary(null);setCoreResult(null);setHintIndex(0);setCoachTurn(null);setCoachStage(0);setPolicyBlocked(false);setPolicyMessage('');setSessionAuthorized(false);cancelSpeech();return}
    let cancelled=false
    void (async()=>{try{const policy=await getTwinPolicyState();if(cancelled)return;if(!policy.enabled){setPolicyBlocked(true);setPolicyMessage('Twin is temporarily disabled by VibeSchool policy.');return}if(policy.remaining<=0){setPolicyBlocked(true);setPolicyMessage('You have reached today’s Twin session limit.');return}await consumeTwinSession(sessionId);if(cancelled)return;setSessionAuthorized(true)}catch(cause){if(!cancelled){setPolicyBlocked(true);setPolicyMessage(cause instanceof Error?cause.message:'Twin policy could not be verified. Please try again shortly.')}}})()
    return()=>{cancelled=true}
  },[isOpen,sessionId,cancelSpeech])
  useEffect(()=>{if(learnerState)setResolvedState(learnerState)},[learnerState])
  useEffect(()=>{if(!isOpen||learnerState!==undefined||resolvedState)return;let cancelled=false;void getLearnerTwinState().then(s=>{if(!cancelled)setResolvedState(s)}).catch(()=>{if(!cancelled)setResolvedState(null)});return()=>{cancelled=true}},[isOpen,learnerState,resolvedState])
  useEffect(()=>{if(!isOpen||greeted||policyBlocked||!sessionAuthorized)return;if(learnerState===undefined&&!resolvedState)return;setGreeted(true);const now=resolvedState?.decision.now,weakest=resolvedState?.mastery.outcomes[0];const greeting=now?`${userName}, ${now.title} matters most right now.${now.reason?` ${now.reason}`:''}`:weakest?`${userName}, you are caught up on assigned work. We can strengthen ${weakest.outcomeText} next.`:`${userName}, I am ready to learn with you.`;addMessage('twin',greeting);const timer=setTimeout(()=>speak(greeting),250);return()=>clearTimeout(timer)},[isOpen,userName,greeted,setGreeted,addMessage,speak,learnerState,resolvedState,policyBlocked,sessionAuthorized])

  function finish(response:string,shouldSpeak=false){addMessage('twin',response);releaseProcessing();if(shouldSpeak||mode==='audio'){setTwinState('speaking');speak(response,()=>setTwinState('idle'))}else setTwinState('idle')}
  async function ensurePolicy(){if(!sessionAuthorized)return false;try{const p=await getTwinPolicyState();if(!p.enabled){setPolicyBlocked(true);setPolicyMessage('Twin is temporarily disabled by VibeSchool policy.');return false}return true}catch{setPolicyBlocked(true);setPolicyMessage('Twin policy could not be verified. Please try again shortly.');return false}}
  async function startAdaptivePractice(){if(practiceLoading||!(await ensurePolicy()))return;setPracticeLoading(true);setPracticeFeedback(null);setSessionSummary(null);setCoreResult(null);setHintIndex(0);setCoachTurn(null);setCoachStage(0);try{const weakest=resolvedState?.mastery.outcomes[0];const q=await generateAdaptivePracticeQuestion(weakest?.outcomeId??null);setPracticeQuestion(q);addMessage('twin',`Let’s work on ${q.outcomeText}. I’ll adapt the next step from how you respond.`)}catch(c){setPracticeFeedback(c instanceof Error?c.message:'Adaptive practice could not be prepared.')}finally{setPracticeLoading(false)}}
  async function requestCoaching(){if(!practiceQuestion||practiceLoading||!(await ensurePolicy()))return;setPracticeLoading(true);try{const latest=[...messages].reverse().find(m=>m.role==='user')?.text??null;const turn=await getAdaptiveTeachingTurn(practiceQuestion.outcomeId,coachStage,latest);setCoachTurn(turn);setCoachStage(turn.nextStage)}catch(c){setPracticeFeedback(c instanceof Error?c.message:'Adaptive coaching could not be prepared.')}finally{setPracticeLoading(false)}}
  async function submitAdaptiveAnswer(selectedIndex:number){if(!practiceQuestion||practiceLoading||!(await ensurePolicy()))return;setPracticeLoading(true);setPracticeFeedback(null);try{const result=await answerAdaptivePracticeQuestion({questionId:practiceQuestion.id,selectedIndex});const next=await getLearnerTwinState({force:true});setResolvedState(next);const mastery=result.effectiveMasteryAfter==null?'':` Effective mastery is now ${Math.round(result.effectiveMasteryAfter)}%.`;setPracticeFeedback(result.correct?`Correct. ${result.explanation}${mastery}`:`Not yet. ${result.explanation}${mastery}`);setPracticeQuestion(result.nextQuestion);setHintIndex(0);setCoachTurn(null);setCoachStage(0);if(!result.nextQuestion){const summary=result.correct?'You completed this practice set. Twin will use the recorded evidence to decide what comes next.':'This practice set is complete. Twin will keep the recorded difficulty signal and revisit it differently.';setSessionSummary(summary);addMessage('twin',summary)}}catch(c){setPracticeFeedback(c instanceof Error?c.message:'Your answer could not be recorded.')}finally{setPracticeLoading(false)}}
  async function handleQuery(query:string){const q=query.trim();if(!q||!acquireProcessing())return;if(!(await ensurePolicy())){releaseProcessing();return}const history:LearnerTwinChatMessage[]=messages.slice(-8).map(m=>({role:m.role==='user'?'user':'assistant',content:m.text}));addMessage('user',q);setInput('');setTwinState('processing');try{const core=await routeTwinCore(q);setCoreResult(core.handled?core:null);if(core.handled&&!core.requiresAi){finish(core.reply||'Done.',false);return}if(practiceQuestion){const turn=await getAdaptiveTeachingTurn(practiceQuestion.outcomeId,coachStage,q);setCoachTurn(turn);setCoachStage(turn.nextStage)}const response=await askLearnerTwinWithSession({firstName:userName,messages:[...history,{role:'user',content:q}],sessionId});finish(response,true)}catch(c){const msg=c instanceof Error?c.message:'Twin is temporarily unavailable.';finish(msg.includes('policy')||msg.includes('limit')?msg:'Twin Core is temporarily limited. Please try again shortly.')}}
  const recognition=useTwinRecognition({onTranscript:text=>void handleQuery(text),onStateChange:state=>setTwinState(state),onError:msg=>{addMessage('twin',msg);releaseProcessing();setTwinState('idle')}})
  if(!isOpen)return null
  if(policyBlocked||!sessionAuthorized)return <div role="dialog" aria-modal="true" aria-label="Vibe Twin policy state" style={{position:'fixed',inset:0,zIndex:10000,background:T.bg,display:'grid',placeItems:'center',padding:24}}><div style={{maxWidth:420,textAlign:'center'}}><div style={{fontSize:30}}>✦</div><h2>{policyBlocked?'VibeTwin unavailable':'Authorizing VibeTwin…'}</h2><p style={{opacity:.72}}>{policyMessage||'Checking your current VibeSchool learning policy.'}</p><button onClick={onClose}>Back</button></div></div>
  return <div role="dialog" aria-modal="true" aria-label="Vibe Twin learning workspace" style={{position:'fixed',inset:0,zIndex:10000,background:T.bg,display:'flex',flexDirection:'column',animation:'vl-slide-up 300ms cubic-bezier(0.34,1.56,0.64,1)',WebkitUserSelect:'none',userSelect:'none'}}><TwinHeader mode={mode} onMode={(m:TwinMode)=>{cancelSpeech();recognition.abort();setTwinState('idle');setMode(m)}} onClose={()=>{cancelSpeech();recognition.abort();onClose()}}/><TwinLearningCanvas userName={userName} learnerState={resolvedState} practiceQuestion={practiceQuestion} coachTurn={coachTurn} practiceFeedback={practiceFeedback} sessionSummary={sessionSummary} coreResult={coreResult} messages={messages} twinState={twinState} hintIndex={hintIndex} practiceLoading={practiceLoading} onStartPractice={()=>void startAdaptivePractice()} onContinueTask={href=>router.push(href)} onAnswer={i=>void submitAdaptiveAnswer(i)} onHint={()=>setHintIndex(i=>i+1)} onCoach={()=>void requestCoaching()} onExplainAnotherWay={()=>void requestCoaching()} onEasier={()=>void requestCoaching()} onHarder={()=>void requestCoaching()} onEndPractice={()=>{setPracticeQuestion(null);setCoachTurn(null);setPracticeFeedback(null);setSessionSummary('Practice ended. Your recorded evidence is saved.')}} onResumeCompanion={()=>void handleQuery('What do you remember about my learning?')}/><TwinInput mode={mode} input={input} onInput={setInput} twinState={twinState} onSubmit={text=>void handleQuery(text)} onStartListen={recognition.start} onStopListen={recognition.stop} onCancelListen={recognition.cancel} onStopSpeak={()=>{cancelSpeech();setTwinState('idle')}} /></div>
}
