"use client";

import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { getParentAssessmentSummary, type ParentAssessmentSummary } from "@/lib/assessment/integration";
import { supabase } from "@/lib/supabase";

interface Child { child_id:string; child_name:string; class_name:string; school_name:string; attendance_pct:number|null; status_label:string }

export default function ParentLearnPage(){
  const router=useRouter();const[child,setChild]=useState<Child|null>(null);const[summary,setSummary]=useState<ParentAssessmentSummary|null>(null);const[loading,setLoading]=useState(true);const[error,setError]=useState("");
  useEffect(()=>{let cancelled=false;(async()=>{try{const{data,error:dashboardError}=await supabase.rpc("get_parent_dashboard");if(dashboardError)throw dashboardError;const children=(Array.isArray(data?.children)?data.children:[]) as Child[];const first=children[0]??null;if(!first){if(!cancelled)setChild(null);return}const assessment=await getParentAssessmentSummary(first.child_id);if(!cancelled){setChild(first);setSummary(assessment)}}catch(cause){if(!cancelled)setError(cause instanceof Error?cause.message:"Could not load learning support.")}finally{if(!cancelled)setLoading(false)}})();return()=>{cancelled=true}},[]);
  if(loading)return <div style={shell}><section style={card}>Loading your family learning view…</section></div>;
  if(error)return <div style={shell}><section style={card}><h1 style={title}>Learning support isn't available yet</h1><p style={muted}>{error}</p></section></div>;
  if(!child)return <div style={shell}><section style={{...card,textAlign:"center"}}><div style={{fontSize:42}}>📚</div><h1 style={title}>Connect a child first</h1><p style={muted}>Once a child is connected, VibeSchool can show you evidence-based ways to support learning at home.</p><button onClick={()=>router.push("/parent/link-child")} style={primary}>Connect a child</button></section></div>;
  return <div style={shell}>
    <section style={{...card,background:"linear-gradient(135deg,#1e1b4b,#312e81)",color:"#fff",border:"none"}}><div style={eyebrow}>Parent learning guide</div><h1 style={{fontSize:21,margin:"5px 0"}}>Help {child.child_name.split(" ")[0]} learn</h1><p style={{fontSize:12,color:"rgba(255,255,255,.7)",margin:0}}>Simple support based on what the school has actually recorded.</p></section>
    <section style={card}><div style={sectionTitle}>What we know</div><div style={grid}><Metric label="Class" value={child.class_name}/><Metric label="School" value={child.school_name}/></div><div style={{marginTop:10,fontSize:12,color:"#374151"}}>Learning status: <strong>{child.status_label}</strong></div></section>
    <section style={card}><div style={sectionTitle}>Released learning evidence</div>{!summary||summary.results.length===0?<p style={muted}>No released assessment evidence yet. When teachers release results, they will appear here.</p>:<div style={{display:"grid",gap:8}}>{summary.results.slice(0,4).map(result=><div key={result.attemptId} style={row}><div><strong>{result.assessmentTitle}</strong><div style={muted}>{result.assessmentType.replaceAll("_"," ")}</div></div><strong>{result.percentage===null?"—":`${result.percentage.toFixed(1)}%`}</strong></div>)}</div>}</section>
    <section style={card}><div style={sectionTitle}>How to support at home</div><div style={{display:"grid",gap:9}}><Tip icon="💬" title="Ask, don't interrogate" detail="Ask what felt easy, what felt difficult, and what your child wants to understand better."/><Tip icon="⏱️" title="Keep practice small" detail="A short, consistent practice session is easier to sustain than a long session."/><Tip icon="👩‍🏫" title="Use teacher feedback" detail="When feedback is released, use it to choose one specific thing to practise together."/></div></section>
    <div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:9}}><button onClick={()=>router.push(`/parent/assessments?studentId=${child.child_id}`)} style={primary}>Learning progress</button><button onClick={()=>router.push(`/parent/child/${child.child_id}`)} style={secondary}>View child</button></div>
  </div>
}
function Tip({icon,title,detail}:{icon:string;title:string;detail:string}){return <div style={{display:"flex",gap:10,padding:11,border:"1px solid #e5e7eb",borderRadius:12}}><div style={{fontSize:20}}>{icon}</div><div><div style={{fontSize:13,fontWeight:800}}>{title}</div><div style={{fontSize:11,color:"#6b7280",marginTop:2,lineHeight:1.45}}>{detail}</div></div></div>}
function Metric({label,value}:{label:string;value:string}){return <div style={{background:"#f8fafc",borderRadius:11,padding:10}}><div style={{fontSize:13,fontWeight:800}}>{value}</div><div style={{fontSize:10,color:"#6b7280",marginTop:2}}>{label}</div></div>}
const shell:React.CSSProperties={maxWidth:768,margin:"0 auto",paddingBottom:24};const card:React.CSSProperties={background:"#fff",border:"1px solid #e5e7eb",borderRadius:16,padding:15,marginBottom:12};const eyebrow:React.CSSProperties={fontSize:10,fontWeight:800,color:"rgba(255,255,255,.55)",textTransform:"uppercase",letterSpacing:1};const title:React.CSSProperties={fontSize:18,margin:"8px 0"};const sectionTitle:React.CSSProperties={fontSize:15,fontWeight:850,marginBottom:10};const muted:React.CSSProperties={fontSize:12,lineHeight:1.5,color:"#6b7280",margin:0};const grid:React.CSSProperties={display:"grid",gridTemplateColumns:"1fr 1fr",gap:8};const row:React.CSSProperties={display:"flex",justifyContent:"space-between",gap:12,alignItems:"center",padding:10,border:"1px solid #e5e7eb",borderRadius:11};const primary:React.CSSProperties={border:"none",borderRadius:11,padding:"11px 13px",background:"#1e1b4b",color:"#fff",fontWeight:800,fontSize:12,cursor:"pointer"};const secondary:React.CSSProperties={border:"1px solid #d1d5db",borderRadius:11,padding:"11px 13px",background:"#fff",color:"#1e1b4b",fontWeight:800,fontSize:12,cursor:"pointer"}