'use client'

export const dynamic = 'force-dynamic'
import { Suspense, useEffect, useMemo, useState } from 'react'
import { useRouter, useSearchParams } from 'next/navigation'
import { supabase } from '@/lib/supabase'
import { addDraftItem, completeLessonAssessmentGeneration, failLessonAssessmentGeneration, requestLessonAssessment } from '@/lib/assessment'
import type { LessonAssessmentType, QuestionType, AutoMarkingMode } from '@/lib/assessment'
type StudioType='exercise'|'quiz'|'homework'|'test'
type DraftQuestion={prompt:string;answer:string;marks:number;questionType:QuestionType;autoMarkingMode:AutoMarkingMode;difficulty:'easy'|'medium'|'hard';bloomLevel:string}
const LABEL:Record<StudioType,string>={exercise:'Class Exercise',quiz:'Quick Quiz',homework:'Homework',test:'CAT'}
const SPEC:Record<StudioType,{minutes:number;purpose:string}>={exercise:{minutes:25,purpose:'Guided practice on today’s lesson outcomes.'},quiz:{minutes:15,purpose:'A short independent mastery check.'},homework:{minutes:35,purpose:'Independent reinforcement and transfer after the lesson.'},test:{minutes:40,purpose:'A formal assessment candidate. Cumulative CATs should include outcomes from multiple completed lessons.'}}
function section(body:string,name:string){return body.match(new RegExp(`<${name}>([\\s\\S]*?)<\\/${name}>`,'i'))?.[1]?.trim()??''}
function objectives(body:string){return section(body,'objectives').split('\n').map(v=>v.replace(/^\s*\d+[.)]\s*/,'').trim()).filter(Boolean)}
function item(prompt:string,marks:number,bloomLevel:string,difficulty:'easy'|'medium'|'hard'):DraftQuestion{return{prompt,answer:'',marks,questionType:'structured',autoMarkingMode:'none',difficulty,bloomLevel}}
function questionsFor(type:StudioType,body:string):DraftQuestion[]{const o=objectives(body);if(!o.length)return[];if(type==='exercise')return o.map((x,i)=>item(`${x} Give a clear answer using evidence or an example from the lesson.`,i?4:2,i?'apply':'understand',i?'medium':'easy'));if(type==='quiz')return o.slice(0,3).map((x,i)=>item(`Show independently that you can: ${x}`,i?3:2,i?'understand':'remember',i?'medium':'easy'));if(type==='homework'){const h=section(body,'homework');if(!h||/no certified homework task|do not invent/i.test(h))return[];return[item(h,10,'apply','medium'),item(`Apply this taught outcome in a new context: ${o[0]}`,5,'create','hard')]}return o.map((x,i)=>item(`Assess this taught outcome: ${x}`,i?6:4,i<2?'apply':'analyse',i?'hard':'medium'))}
function Studio(){const router=useRouter(),params=useSearchParams();const lessonPlanId=params.get('lessonPlanId')??'',requested=params.get('type');const initial:StudioType=requested==='exercise'||requested==='homework'||requested==='test'?requested:'quiz';const[type,setType]=useState<StudioType>(initial),[body,setBody]=useState(''),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState('')
useEffect(()=>{let active=true;(async()=>{if(!lessonPlanId){setLoading(false);return}const{data,error}=await supabase.from('lesson_plans').select('body').eq('id',lessonPlanId).maybeSingle();if(!active)return;if(error){setError(error.message);setLoading(false);return}setBody(data?.body??'');setLoading(false)})();return()=>{active=false}},[lessonPlanId])
const questions=useMemo(()=>questionsFor(type,body),[type,body]),marks=questions.reduce((s,x)=>s+x.marks,0)
async function prepare(advanced:boolean){if(!lessonPlanId||saving||!questions.length)return;setSaving(true);setError('');let id:string|null=null;try{const r=await requestLessonAssessment({lessonPlanId,assessmentType:type as LessonAssessmentType,requestKey:`lesson:${lessonPlanId}:${type}:v3`,title:`${LABEL[type]} — lesson outcomes`,generationMetadata:{generator_version:'curriculum-outcome-assessment-v3',ai_used:false,source:'authoritative_lesson_body',blueprint:{question_count:questions.length,estimated_minutes:SPEC[type].minutes}}});id=r.assessmentId;if(r.created){for(let i=0;i<questions.length;i++){const x=questions[i];await addDraftItem({assessmentId:id,questionType:x.questionType,prompt:x.prompt,marks:x.marks,orderNum:i+1,acceptedAnswers:[],correctAnswer:null,autoMarkingMode:'none',difficulty:x.difficulty,bloomLevel:x.bloomLevel,generatedBy:'curriculum_outcome_material'})}await completeLessonAssessmentGeneration({assessmentId:id,itemCount:questions.length,totalMarks:marks,estimatedMinutes:SPEC[type].minutes,generationMetadata:{generated_from:'authoritative_lesson_body',ai_used:false,teacher_review_required:true}})}router.push(`/teacher/assessment/builder/${id}${advanced?'':'?mode=review'}`)}catch(e){if(id)try{await failLessonAssessmentGeneration({assessmentId:id,errorCode:'draft_generation_failed',errorMessage:e instanceof Error?e.message:null})}catch{}setError(e instanceof Error?e.message:'Material could not be prepared.')}finally{setSaving(false)}}
if(!lessonPlanId)return <main style={page}><section style={card}><h1>Lesson Materials</h1><p>Open materials from a saved lesson plan.</p></section></main>
return <main style={page}><div style={{maxWidth:760,margin:'0 auto'}}><button onClick={()=>router.back()} style={secondary}>← Back to lesson</button><section style={card}><div style={eyebrow}>Prepared assessment pack · No AI</div><h1>Ready from the lesson outcomes</h1><p style={{color:'#6b7280'}}>Curriculum outcomes—not activity labels—are the source of truth. Each material has a distinct teaching purpose.</p></section><section style={card}><div style={{display:'grid',gridTemplateColumns:'repeat(2,minmax(0,1fr))',gap:10}}>{(Object.keys(LABEL) as StudioType[]).map(t=><button key={t} onClick={()=>setType(t)} style={{padding:14,borderRadius:12,border:type===t?'2px solid #4338ca':'1px solid #d1d5db',background:type===t?'#eef2ff':'#fff',fontWeight:800}}>{LABEL[t]}</button>)}</div></section><section style={card}><div style={eyebrow}>{LABEL[type]}</div><h2>{SPEC[type].purpose}</h2>{loading?<p>Loading authoritative lesson…</p>:questions.length===0?<div style={notice}>{type==='homework'?'No certified homework is attached. VibeSchool will not invent one. Advanced Edit remains available from the assessment workspace for intentional teacher authoring.':'Automatic generation is blocked because authoritative lesson outcomes are unavailable.'}</div>:<><div>{questions.length} questions · {marks} marks · about {SPEC[type].minutes} minutes</div><ol>{questions.map((x,i)=><li key={i} style={{marginBottom:10}}>{x.prompt} <strong>({x.marks})</strong></li>)}</ol></>}</section>{error&&<div style={errorBox}>{error}</div>}{questions.length>0&&<div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:10}}><button disabled={saving} onClick={()=>prepare(false)} style={primary}>{saving?'Preparing…':'Review & assign'}</button><button disabled={saving} onClick={()=>prepare(true)} style={secondary}>Advanced Edit</button></div>}</div></main>}
const page:React.CSSProperties={minHeight:'100vh',background:'#f8fafc',padding:'18px 14px 80px',fontFamily:"'Plus Jakarta Sans', sans-serif",color:'#111827'},card:React.CSSProperties={background:'#fff',border:'1px solid #e5e7eb',borderRadius:16,padding:16,marginBottom:12},eyebrow:React.CSSProperties={fontSize:10,fontWeight:800,color:'#4338ca',textTransform:'uppercase',letterSpacing:1},primary:React.CSSProperties={border:'none',borderRadius:12,padding:'14px 16px',background:'#4338ca',color:'#fff',fontWeight:800,cursor:'pointer'},secondary:React.CSSProperties={border:'1px solid #d1d5db',borderRadius:10,padding:'10px 14px',background:'#fff',color:'#374151',fontWeight:700,cursor:'pointer'},notice:React.CSSProperties={padding:12,borderRadius:10,background:'#fffbeb',border:'1px solid #fde68a',color:'#92400e'},errorBox:React.CSSProperties={padding:12,borderRadius:10,background:'#fef2f2',border:'1px solid #fecaca',color:'#b91c1c',marginBottom:12}
export default function NewAssessmentPage(){return <Suspense fallback={<main style={{padding:20}}>Loading lesson materials…</main>}><Studio/></Suspense>}
