"use client";
export const dynamic = "force-dynamic";

import { useState, useEffect, useCallback } from "react";
import { useRouter, usePathname } from "next/navigation";
import BottomNav from "@/components/student/BottomNav";
import OfflineBar from "@/components/student/OfflineBar";
import TwinWorkspaceProvider from "@/components/student/VibeTwin/TwinWorkspaceProvider";
import { ToastContext, ThemeContext } from "@/components/student/StudentUiContext";
import ProductAuthorityGate from "@/components/company/ProductAuthorityGate";
import { StudentProvider, useStudent } from "@/lib/student-context";
import { readTheme, writeTheme, resolveTheme, StudentTheme } from "@/lib/student-theme";

function TopBar({ name, className, schoolName }: { name: string; className: string; schoolName: string }) {
  const router=useRouter(); const pathname=usePathname(); const isRoot=pathname==="/student"||pathname==="/student/";
  const initials=name.trim().split(" ").filter(Boolean).slice(0,2).map(w=>w[0].toUpperCase()).join("")||"S";
  return <div style={{background:"#1C1A2E",color:"#fff",padding:"0 20px",height:56,display:"flex",alignItems:"center",justifyContent:"space-between",position:"sticky",top:0,zIndex:600,boxShadow:"0 2px 12px rgba(0,0,0,0.18)"}}>
    <div style={{display:"flex",alignItems:"center",gap:10}}>{!isRoot&&<div onClick={()=>router.back()} style={{cursor:"pointer",fontSize:22,minWidth:44,minHeight:44,display:"flex",alignItems:"center",justifyContent:"center"}}>‹</div>}<div onClick={()=>router.push("/student")} style={{display:"flex",alignItems:"center",gap:10,cursor:"pointer"}}><div style={{width:30,height:30,borderRadius:9,background:"#7C6EF8",display:"flex",alignItems:"center",justifyContent:"center",fontSize:15,fontWeight:900}}>V</div><div><div style={{fontSize:15,fontWeight:800}}>VibeSchool</div><div style={{fontSize:10,color:"rgba(255,255,255,0.4)"}}>{schoolName||className||"Student"}</div></div></div></div>
    <div style={{display:"flex",alignItems:"center",gap:12}}><div onClick={()=>router.push("/student/notifications")} style={{cursor:"pointer",minWidth:44,minHeight:44,display:"flex",alignItems:"center",justifyContent:"center"}}>◌</div><div onClick={()=>router.push("/student/profile")} style={{width:34,height:34,borderRadius:"50%",background:"#7C6EF8",display:"flex",alignItems:"center",justifyContent:"center",fontSize:13,fontWeight:800,cursor:"pointer"}}>{initials}</div></div>
  </div>;
}
function Toast({msg}:{msg:string}){return <div style={{position:"fixed",bottom:140,left:"50%",transform:"translateX(-50%)",background:"#1C1A2E",color:"#fff",padding:"11px 22px",borderRadius:12,fontSize:13,fontWeight:600,zIndex:9999}}>{msg}</div>}
function StudentShell({children}:{children:React.ReactNode}){const {identity,loading,error}=useStudent();const router=useRouter();if(loading)return <div style={{minHeight:"100dvh",background:"#0F0F1A"}}/>;if(error)return <div style={{minHeight:"100dvh",background:"#0F0F1A",color:"#F87171",display:"flex",alignItems:"center",justifyContent:"center",padding:24}}><div>{error}<button onClick={()=>router.replace("/student")}>Try Again</button></div></div>;return <><TopBar name={identity?.name??""} className={identity?.className??""} schoolName={identity?.schoolName??""}/><OfflineBar/><main style={{maxWidth:768,margin:"0 auto",padding:"clamp(12px, 3vw, 20px) clamp(12px, 4vw, 20px) 160px",minHeight:"calc(100dvh - 120px)"}}>{children}</main><BottomNav/></>}
export default function StudentLayout({children}:{children:React.ReactNode}){const [toast,setToast]=useState<string|null>(null);const [theme,setThemeState]=useState<StudentTheme>("auto");const [resolved,setResolved]=useState<"light"|"dark">("dark");useEffect(()=>{const t=readTheme();setThemeState(t);setResolved(resolveTheme(t))},[]);const setTheme=useCallback((t:StudentTheme)=>{writeTheme(t);setThemeState(t);setResolved(resolveTheme(t))},[]);const showToast=useCallback((msg:string)=>{setToast(msg);setTimeout(()=>setToast(null),2800)},[]);return <ToastContext.Provider value={{showToast}}><ThemeContext.Provider value={{theme,setTheme}}><style>{`:root{--vs-bg:${resolved==="dark"?"#0F0F1A":"#F7F5FF"};--vs-surface:${resolved==="dark"?"#1A1A2E":"#FFFFFF"};--vs-border:${resolved==="dark"?"#2D2D4E":"#E5E3F5"};--vs-text:${resolved==="dark"?"#F0EFFF":"#1C1A2E"};--vs-muted:${resolved==="dark"?"#9090B0":"#6B6880"};--vs-accent:${resolved==="dark"?"#7C6EF8":"#5B4EE8"}}body{background:var(--vs-bg);color:var(--vs-text)}`}</style><div style={{minHeight:"100dvh",background:"var(--vs-bg)"}}><StudentProvider><ProductAuthorityGate productKey="student" policyKey="student.enabled" label="Student"><TwinWorkspaceProvider><StudentShell>{children}</StudentShell></TwinWorkspaceProvider></ProductAuthorityGate></StudentProvider>{toast&&<Toast msg={toast}/>}</div></ThemeContext.Provider></ToastContext.Provider>}
