'use client'

import { useCallback,useEffect,useMemo,useState } from 'react'
import { useParams,useRouter } from 'next/navigation'
import { supabase } from '@/lib/supabase'
import { normalizeProgressBand,type ProgressBand } from '@/lib/learner-intelligence/progress-record'

export const dynamic='force-dynamic'
type Learner={id:string;name:string;admission_number:string|null}
type Evidence={student_id:string;score:number|null;max_score:number|null;proficiency:string|null;observed_at:string}
const order:Record<ProgressBand,number>={BE:0,AE:1,NE:2,ME:3,EE:4}
const label:Record<ProgressBand,string>={EE:'Exceeding',ME:'Meeting',AE:'Approaching',BE:'Below',NE:'No evidence'}

export default function ClassStudentProgressPage(){const {id:classId}=useParams<{id:string}>();const router=useRouter();const [learners,setLearners]=useState<Learner[]>([]);const [evidence,setEvidence]=useState<Evidence[]>([]);const [className,setClassName]=useState('Class');const [query,setQuery]=useState('');const [loading,setLoading]=useState(true);const [error,setError]=useState('')
const load=useCallback(async()=>{setLoading(true);setError('');try{const {data:auth}=await supabase.auth.getUser();if(!auth.user){router.replace('/login');return}const {data:ctx,error:ce}=await supabase.rpc('teacher_get_operating_context');if(ce)throw ce;const c:any=ctx;const assignment=c?.classes?.find((x:any)=>x.class_id===classId);if(!c?.school_id||!assignment)throw new Error('This class is not assigned to you in the active school.');setClassName(`${assignment.class_name}${assignment.stream?` ${assignment.stream}`:''}`)
const enrollment=await supabase.from('student_classes').select('student_id,students(id,name,admission_number,deleted_at)').eq('school_id',c.school_id).eq('class_id',classId).eq('is_current',true);if(enrollment.error)throw enrollment.error;const ls:Learner[]=(enrollment.data??[]).map((r:any)=>Array.isArray(r.students)?r.students[0]:r.students).filter((s:any)=>s&&!s.deleted_at).map((s:any)=>({id:s.id,name:s.name,admission_number:s.admission_number??null}));setLearners(ls)
const er=await supabase.from('competency_evidence_ledger').select('student_id,score,max_score,proficiency,observed_at').eq('school_id',c.school_id).eq('class_id',classId).order('observed_at',{ascending:false}).limit(2000);if(er.error)throw er.error;setEvidence((er.data??[]).map((r:any)=>({...r,score:r.score==null?null:Number(r.score),max_score:r.max_score==null?null:Number(r.max_score)})))}catch(e){console.error('[ClassStudentProgress] load',e);setError(e instanceof Error?e.message:'Class progress could not be loaded.')}finally{setLoading(false)}},[classId,router]);useEffect(()=>{void load()},[load])
const cards=useMemo(()=>learners.map(l=>{const rows=evidence.filter(e=>e.student_id===l.id);const scored=rows.filter(r=>r.score!=null&&r.max_score!=null&&r.max_score>0);const avg=scored.length?Math.round(scored.reduce((n,r)=>n+(r.score!/r.max_score!)*100,0)/scored.length):null;const latest=rows[0];const band=normalizeProgressBand(latest?.proficiency??null,avg);return{...l,count:rows.length,avg,band,last:latest?.observed_at??null}}).filter(l=>!query||`${l.name} ${l.admission_number??''}`.toLowerCase().includes(query.toLowerCase())).sort((a,b)=>order[a.band]-order[b.band]||a.name.localeCompare(b.name)),[learners,evidence,query])
if(loading)return <main style={{padding:20}}><div style={{height:180,borderRadius:20,background:'#e5e7eb'}}/></main>
return <main style={{maxWidth:900,margin:'0 auto',padding:'16px 14px 112px'}}><section style={{padding:18,borderRadius:21,background:'linear-gradient(135deg,#0f172a,#1d4ed8)',color:'#fff'}}><button onClick={()=>router.push(`/teacher/classhub/${classId}`)} style={{border:0,borderRadius:10,minHeight:38,padding:'0 11px',background:'rgba(255,255,255,.14)',color:'#fff',fontWeight:800}}>‹ Class</button><div style={{marginTop:13,fontSize:11,fontWeight:900,opacity:.7}}>STUDENT PROGRESS</div><h1 style={{margin:'4px 0',fontSize:24}}>{className}</h1><p style={{margin:0,fontSize:12,opacity:.75}}>Learners needing support appear first. Open a learner for the professional evidence-backed progress record.</p></section>
{error?<div role="alert" style={{marginTop:12,padding:14,borderRadius:14,background:'#fef2f2',color:'#991b1b'}}>{error}</div>:<><input aria-label="Search learners" placeholder="Search learner or admission number" value={query} onChange={e=>setQuery(e.target.value)} style={{width:'100%',boxSizing:'border-box',minHeight:46,margin:'12px 0',border:'1px solid #d1d5db',borderRadius:13,padding:'0 13px'}}/><div style={{display:'grid',gap:9}}>{cards.map(l=><button key={l.id} onClick={()=>router.push(`/teacher/classhub/${classId}/student/${l.id}/progress`)} style={{border:'1px solid #e5e7eb',borderRadius:16,background:'#fff',padding:14,textAlign:'left',font:'inherit',cursor:'pointer'}}><div style={{display:'flex',justifyContent:'space-between',gap:10}}><div><strong>{l.name}</strong><div style={{marginTop:4,fontSize:11,color:'#6b7280'}}>{l.admission_number?`Adm ${l.admission_number} · `:''}{l.count} evidence item{l.count===1?'':'s'}{l.avg==null?'':` · ${l.avg}% avg`}</div></div><span style={{fontSize:11,fontWeight:900,color:l.band==='BE'?'#991b1b':l.band==='AE'?'#92400e':l.band==='NE'?'#6b7280':'#065f46'}}>{l.band} · {label[l.band]}</span></div></button>)}{!cards.length&&<div style={{padding:28,textAlign:'center',border:'1px solid #e5e7eb',borderRadius:16}}>No learners match this view.</div>}</div></>}
</main>}
