"use client"

import { useCallback,useEffect,useMemo,useState } from "react"
import { useRouter } from "next/navigation"
import { supabase } from "@/lib/supabase"
const rpc=supabase.rpc.bind(supabase) as any
const C={bg:"#07111f",panel:"#0d1b2f",line:"rgba(255,255,255,.09)",text:"#f8fafc",muted:"rgba(255,255,255,.48)",green:"#34d399",amber:"#f59e0b",red:"#fb7185"}
type Row={id:string;curriculum:string;grade:string;subject:string;term:number;week:number;strand:string;sub_strand:string;topic:string;periods:number;reference:string|null;lesson_context:Record<string,unknown>|null}
export default function CurriculumStudio(){const router=useRouter();const[rows,setRows]=useState<Row[]>([]);const[selected,setSelected]=useState<Row|null>(null);const[error,setError]=useState("");const[filter,setFilter]=useState("");const[busy,setBusy]=useState(false);const[topic,setTopic]=useState("");const[periods,setPeriods]=useState(1);const[reference,setReference]=useState("");const[tips,setTips]=useState("");const[mistakes,setMistakes]=useState("");const[outcome,setOutcome]=useState("")
 const load=useCallback(async()=>{const{data,error:e}=await rpc("hq_list_curriculum_rows",{p_limit:1000});if(e)setError(e.message);else setRows(data??[])},[]);useEffect(()=>{void load()},[load]);function pick(r:Row){setSelected(r);setTopic(r.topic??"");setPeriods(r.periods??1);setReference(r.reference??"");setTips(typeof r.lesson_context?.teaching_tips==='string'?String(r.lesson_context.teaching_tips):"");setMistakes(typeof r.lesson_context?.common_mistakes==='string'?String(r.lesson_context.common_mistakes):"")}
 const shown=useMemo(()=>{const q=filter.toLowerCase();return q?rows.filter(r=>[r.grade,r.subject,r.strand,r.sub_strand,r.topic].join(' ').toLowerCase().includes(q)):rows},[rows,filter])
 async function save(){if(!selected)return;setBusy(true);const{error:e}=await rpc("hq_update_curriculum_row",{p_id:selected.id,p_topic:topic,p_periods:periods,p_reference:reference,p_teaching_tips:tips,p_common_mistakes:mistakes});if(e)setError(e.message);else{await load();setSelected(null)}setBusy(false)}
 async function addOutcome(){if(!selected||!outcome.trim())return;setBusy(true);const{error:e}=await rpc("hq_add_curriculum_outcome",{p_curriculum_id:selected.id,p_outcome_text:outcome.trim()});if(e)setError(e.message);else setOutcome("");setBusy(false)}
 return <main style={{minHeight:"100dvh",background:C.bg,color:C.text,padding:18,fontFamily:"Inter,system-ui,sans-serif"}}><div style={{maxWidth:1160,margin:"0 auto"}}><button onClick={()=>router.push("/hq/studio")} style={btn}>← Studio</button><h1>CBC/CBE Curriculum Editor</h1><p style={{color:C.muted,fontSize:12}}>Real grade → subject → term/week → strand/substrand records, with teaching context and draft outcomes.</p>{error&&<div style={{color:"#fecdd3"}}>{error}</div>}<input value={filter} onChange={e=>setFilter(e.target.value)} placeholder="Filter grade, subject, strand, topic…" style={{...input,marginBottom:10}}/>
 <div style={{display:"grid",gridTemplateColumns:"minmax(0,1fr) minmax(320px,.75fr)",gap:12}}><section style={panel}>{shown.slice(0,400).map((r,i)=><button key={r.id} onClick={()=>pick(r)} style={{width:"100%",textAlign:"left",display:"grid",gridTemplateColumns:"100px 130px 70px 1fr",gap:8,padding:"10px 6px",border:0,borderTop:i?`1px solid ${C.line}`:0,background:selected?.id===r.id?'rgba(52,211,153,.07)':'transparent',color:C.text,cursor:"pointer"}}><strong style={{fontSize:11}}>{r.grade}</strong><span style={{fontSize:11}}>{r.subject}</span><span style={{fontSize:10,color:C.muted}}>T{r.term} W{r.week}</span><span><b style={{fontSize:11}}>{r.sub_strand||r.strand}</b><small style={{display:"block",color:C.muted,marginTop:3}}>{r.topic}</small></span></button>)}</section>
 <aside style={panel}>{!selected?<div style={{color:C.muted}}>Select a curriculum row to edit its instructional context.</div>:<><div style={{fontSize:11,color:C.green,fontWeight:900}}>{selected.grade} · {selected.subject} · T{selected.term} W{selected.week}</div><h2 style={{fontSize:16}}>{selected.sub_strand||selected.strand}</h2><label style={lab}>Topic<input value={topic} onChange={e=>setTopic(e.target.value)} style={input}/></label><label style={lab}>Periods<input type="number" min={1} value={periods} onChange={e=>setPeriods(Number(e.target.value)||1)} style={input}/></label><label style={lab}>Reference<input value={reference} onChange={e=>setReference(e.target.value)} style={input}/></label><label style={lab}>Teaching tips<textarea rows={4} value={tips} onChange={e=>setTips(e.target.value)} style={input}/></label><label style={lab}>Common learner mistakes<textarea rows={4} value={mistakes} onChange={e=>setMistakes(e.target.value)} style={input}/></label><button disabled={busy} onClick={()=>void save()} style={{...btn,color:C.green}}>Save curriculum context</button><div style={{borderTop:`1px solid ${C.line}`,margin:"14px 0"}}/><label style={lab}>Add draft learning outcome<textarea rows={3} value={outcome} onChange={e=>setOutcome(e.target.value)} style={input}/></label><button disabled={busy} onClick={()=>void addOutcome()} style={{...btn,color:C.amber}}>Add outcome for review</button></>}</aside></div></div></main>}
const panel:React.CSSProperties={background:C.panel,border:`1px solid ${C.line}`,borderRadius:14,padding:14,overflow:'auto',maxHeight:'72dvh'};const btn:React.CSSProperties={border:`1px solid ${C.line}`,background:"rgba(255,255,255,.04)",color:C.text,borderRadius:9,padding:"8px 10px",fontSize:11,fontWeight:800,cursor:"pointer"};const input:React.CSSProperties={width:"100%",boxSizing:"border-box",background:"#0a1628",border:`1px solid ${C.line}`,borderRadius:9,padding:10,color:C.text,marginTop:5};const lab:React.CSSProperties={display:'block',fontSize:10,color:C.muted,fontWeight:800,marginBottom:10}
