"use client"

import { useCallback, useEffect, useState } from "react"
import { useRouter } from "next/navigation"
import { supabase } from "@/lib/supabase"

type Action={id:string;action_type:string;status:string;priority:number;attempt_count:number;max_attempts:number;last_error:string|null;next_attempt_at:string|null;locked_at:string|null;proposal_id:string|null;created_at:string}
type Effect={id:string;proposal_id:string;chapter_id:string|null;outcome_id:string|null;baseline:Record<string,unknown>;followup:Record<string,unknown>;evaluation_due_at:string|null;evaluated_at:string|null;verdict:string;effect_score:number|null;sample_size:number}

const C={bg:"#0a1628",panel:"#0f1d33",line:"rgba(255,255,255,.08)",text:"#fff",muted:"rgba(255,255,255,.5)",green:"#10b981",amber:"#f59e0b",red:"#ef4444",blue:"#3b82f6"}
const btn=(c:string)=>({border:`1px solid ${c}66`,background:`${c}12`,color:C.text,borderRadius:8,padding:"7px 10px",fontWeight:800,fontSize:11,cursor:"pointer" as const})

export default function EditorialEffectivenessPage(){
 const router=useRouter();const [actions,setActions]=useState<Action[]>([]);const [effects,setEffects]=useState<Effect[]>([]);const [busy,setBusy]=useState<string|null>(null);const [message,setMessage]=useState("");const [error,setError]=useState("")
 const load=useCallback(async()=>{const [a,e]=await Promise.all([
  supabase.from("curriculum_editorial_actions").select("id,action_type,status,priority,attempt_count,max_attempts,last_error,next_attempt_at,locked_at,proposal_id,created_at").order("created_at",{ascending:false}).limit(100),
  supabase.from("curriculum_editorial_effectiveness").select("id,proposal_id,chapter_id,outcome_id,baseline,followup,evaluation_due_at,evaluated_at,verdict,effect_score,sample_size").order("created_at",{ascending:false}).limit(200),
 ]);const err=a.error||e.error;if(err)setError(err.message);else{setActions((a.data||[]) as Action[]);setEffects((e.data||[]) as Effect[])}},[])
 useEffect(()=>{void load()},[load])
 const run=async(key:string,fn:()=>Promise<{data:any;error:any}>,ok:(d:any)=>string)=>{setBusy(key);setError("");setMessage("");const {data,error:e}=await fn();if(e)setError(e.message);else setMessage(ok(data));await load();setBusy(null)}
 const requeue=(id:string)=>run(`requeue:${id}`,()=>supabase.rpc("hq_requeue_editorial_action",{p_action_id:id}),()=>"Editorial action requeued")
 const evaluate=(id:string)=>run(`eval:${id}`,()=>supabase.rpc("hq_effectiveness_decision",{p_proposal_id:id}),d=>`Effectiveness decision: ${d?.decision||"review"}`)
 const grouped=effects.reduce<Record<string,Effect[]>>((m,e)=>{(m[e.proposal_id]??=[]).push(e);return m},{})
 return <div style={{minHeight:"100dvh",background:C.bg,color:C.text,fontFamily:"Inter,system-ui,sans-serif"}}><header style={{borderBottom:`1px solid ${C.line}`,padding:"14px 18px",position:"sticky",top:0,background:"rgba(10,22,40,.97)",zIndex:10}}><div style={{maxWidth:1100,margin:"0 auto"}}><button onClick={()=>router.push("/hq/curriculum-intelligence/engine")} style={{border:0,background:"transparent",color:C.muted,padding:0,cursor:"pointer"}}>← Content Production Engine</button><h1 style={{fontSize:20,margin:"5px 0 0"}}>Editorial Recovery & Effectiveness</h1><div style={{fontSize:12,color:C.muted}}>Retries, dead letters, and evidence showing whether an applied editorial change actually improved learning.</div></div></header><main style={{maxWidth:1100,margin:"0 auto",padding:18}}>
 {error&&<div style={{padding:12,border:`1px solid ${C.red}55`,borderRadius:10,color:"#fecaca",marginBottom:12}}>{error}</div>}{message&&<div style={{padding:12,border:`1px solid ${C.green}55`,borderRadius:10,color:"#bbf7d0",marginBottom:12}}>{message}</div>}
 <section style={{background:C.panel,border:`1px solid ${C.line}`,borderRadius:14,padding:14,marginBottom:16}}><h2 style={{fontSize:15,margin:"0 0 5px"}}>Action recovery</h2><div style={{fontSize:11,color:C.muted,marginBottom:8}}>Workers claim actions atomically. Failures retry with backoff and eventually enter dead-letter status instead of remaining stuck.</div>{actions.length===0?<div style={{color:C.muted}}>No editorial actions.</div>:actions.map(a=><div key={a.id} style={{borderTop:`1px solid ${C.line}`,padding:"10px 0",display:"grid",gridTemplateColumns:"1fr auto",gap:10}}><div><strong style={{fontSize:12}}>{a.action_type.replaceAll("_"," ")}</strong><div style={{fontSize:10.5,color:C.muted}}>status {a.status.replaceAll("_"," ")} · priority {a.priority} · attempts {a.attempt_count}/{a.max_attempts}{a.next_attempt_at?` · retry ${new Date(a.next_attempt_at).toLocaleString()}`:""}</div>{a.last_error&&<div style={{fontSize:10.5,color:"#fecaca",marginTop:4}}>{a.last_error}</div>}</div>{["failed","dead_letter"].includes(a.status)&&<button disabled={!!busy} onClick={()=>void requeue(a.id)} style={btn(C.amber)}>Requeue</button>}</div>)}</section>
 <section style={{background:C.panel,border:`1px solid ${C.line}`,borderRadius:14,padding:14}}><h2 style={{fontSize:15,margin:"0 0 5px"}}>Post-edit learning evidence</h2><div style={{fontSize:11,color:C.muted,marginBottom:8}}>Approval captures a baseline. After use, HQ compares learner mastery and recommends retain, review/revert, or collect more evidence. No automatic rollback.</div>{Object.keys(grouped).length===0?<div style={{color:C.muted}}>No applied editorial changes have an effectiveness window yet.</div>:Object.entries(grouped).map(([proposalId,rows])=>{const improved=rows.filter(x=>x.verdict==="improved").length,worse=rows.filter(x=>x.verdict==="worse").length,ins=rows.filter(x=>x.verdict==="insufficient_evidence").length;return <div key={proposalId} style={{borderTop:`1px solid ${C.line}`,padding:"12px 0",display:"grid",gridTemplateColumns:"1fr auto",gap:10}}><div><strong style={{fontSize:12}}>Proposal {proposalId.slice(0,8)}</strong><div style={{fontSize:10.5,color:C.muted}}>{rows.length} outcome(s) · improved {improved} · worse {worse} · insufficient {ins}</div><div style={{fontSize:10.5,color:C.muted,marginTop:3}}>Next evaluation: {rows[0]?.evaluation_due_at?new Date(rows[0].evaluation_due_at).toLocaleString():"not scheduled"}</div></div><button disabled={!!busy} onClick={()=>void evaluate(proposalId)} style={btn(C.blue)}>Evaluate</button></div>})}</section>
 </main></div>
}
