"use client"
export const dynamic="force-dynamic"

import Link from "next/link"
import {useCallback,useEffect,useState} from "react"
import {supabase} from "@/lib/supabase"
import {HQPage,HQPanel,HQ_THEME as C,hqButtonStyle} from "@/components/hq/HQShell"

type Obj=Record<string,any>
type Snapshot={generated_at:string;company_state:"LIVE"|"ATTENTION"|"DEGRADED"|"INCIDENT";summary:Obj;execution_integrity:Obj;engine:Obj;attention:Obj[];recent_execution:Obj[];notifications:Obj}
const sb=supabase as any
const tones={LIVE:C.green,ATTENTION:C.amber,DEGRADED:C.red,INCIDENT:C.red} as const
const fmt=(v:unknown)=>typeof v==="number"?new Intl.NumberFormat("en-KE").format(v):String(v??"—")
const when=(v:unknown)=>v?new Date(String(v)).toLocaleString("en-KE"):"—"

function Stat({label,value,tone=C.text}:{label:string;value:unknown;tone?:string}){return <article style={{padding:14,border:`1px solid ${C.border}`,borderRadius:13,background:C.panelSoft}}><strong style={{display:"block",fontSize:23,color:tone}}>{fmt(value)}</strong><span style={{display:"block",marginTop:4,fontSize:11,color:C.muted}}>{label}</span></article>}
function Badge({children,tone=C.blue}:{children:React.ReactNode;tone?:string}){return <span style={{display:"inline-flex",minHeight:24,alignItems:"center",padding:"0 8px",borderRadius:999,border:`1px solid ${tone}55`,color:tone,fontSize:10,fontWeight:900}}>{children}</span>}

export default function FounderOperationsPage(){
 const[data,setData]=useState<Snapshot|null>(null);const[loading,setLoading]=useState(true);const[error,setError]=useState("")
 const load=useCallback(async()=>{setLoading(true);setError("");try{const{data,error}=await sb.rpc("hq_founder_os_snapshot",{p_recent_limit:30});if(error)throw error;setData(data as Snapshot)}catch(e){setError(e instanceof Error?e.message:"Founder operations state could not be loaded.")}finally{setLoading(false)}},[])
 useEffect(()=>{void load()},[load])
 const e=data?.engine??{};const integrity=data?.execution_integrity??{};const state=data?.company_state??"ATTENTION";const safeRuntime=!e.runtime_execution_enabled&&Number(e.runtime_autonomy_level??0)===0&&Number(e.runtime_max_risk??0)===0
 return <HQPage title="Operations" description="Company exceptions, execution integrity and governed runtime in one owner surface" actions={<button onClick={()=>void load()} disabled={loading} style={hqButtonStyle}>{loading?"Refreshing…":"Refresh"}</button>}>
  {error&&<div role="alert" style={{marginBottom:12,padding:12,border:"1px solid rgba(239,68,68,.35)",borderRadius:12,color:"#fecaca",background:"rgba(239,68,68,.08)"}}>{error}</div>}
  {!data?<HQPanel><div style={{padding:28,color:C.muted}}>{loading?"Loading canonical company state…":"No operations snapshot is available."}</div></HQPanel>:<div style={{display:"grid",gap:13}}>
   <section aria-label="Company state" style={{padding:18,border:`1px solid ${tones[state]}55`,borderRadius:15,background:`${tones[state]}0d`}}><div style={{display:"flex",gap:10,alignItems:"center",flexWrap:"wrap"}}><strong style={{fontSize:25,color:tones[state]}}>{state}</strong><Badge tone={safeRuntime?C.green:C.red}>Runtime {safeRuntime?"OFF · L0 · R0":"ACTIVE"}</Badge><Badge tone={e.shadow_global_stop?C.green:C.red}>Global Stop {e.shadow_global_stop?"ACTIVE":"NOT ACTIVE"}</Badge></div><p style={{margin:"8px 0 0",color:C.muted,fontSize:12}}>Canonical state generated {when(data.generated_at)}. Incident precedence cannot be masked by healthy metrics.</p></section>
   <section style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(140px,1fr))",gap:9}}><Stat label="Open incidents" value={data.summary.open_incidents} tone={Number(data.summary.open_incidents)>0?C.red:C.green}/><Stat label="Open findings" value={data.summary.open_findings} tone={Number(data.summary.open_findings)>0?C.amber:C.green}/><Stat label="Needs founder decision" value={data.summary.actionable_decisions} tone={Number(data.summary.actionable_decisions)>0?C.amber:C.green}/><Stat label="Overdue high work" value={data.summary.overdue_high_work} tone={Number(data.summary.overdue_high_work)>0?C.red:C.green}/><Stat label="Open breakers" value={data.summary.open_breakers} tone={Number(data.summary.open_breakers)>0?C.red:C.green}/></section>
   <HQPanel title="Attention Required" description="Canonical priority order: incidents → findings → decisions → consequential work."><div style={{display:"grid"}}>{data.attention.length?data.attention.map((x,i)=><article key={x.id} style={{padding:14,borderBottom:i===data.attention.length-1?"none":`1px solid ${C.border}`}}><div style={{display:"flex",gap:7,alignItems:"center",flexWrap:"wrap"}}><Badge tone={x.severity==="critical"?C.red:x.severity==="high"?C.amber:C.blue}>{String(x.severity).toUpperCase()}</Badge><Badge>{String(x.type).toUpperCase()}</Badge><strong style={{fontSize:13}}>{x.title}</strong></div><p style={{margin:"7px 0",fontSize:11.5,lineHeight:1.55,color:C.text}}>{x.explanation}</p><div style={{fontSize:10.5,color:C.muted}}>Owner {x.owner??"Unassigned"} · detected {when(x.detected_at)} · priority {x.rank_score}</div>{x.route&&<Link href={x.route} style={{display:"inline-block",marginTop:8,color:C.blue,fontSize:11,fontWeight:900,textDecoration:"none"}}>Review evidence →</Link>}</article>):<div style={{padding:24,color:C.muted}}>No consequential attention items.</div>}</div></HQPanel>
   <HQPanel title="Execution integrity" description="Historical activity is not treated as governed execution without intent and verification evidence."><div style={{padding:14,display:"grid",gap:12}}><section style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(130px,1fr))",gap:8}}><Stat label="Runs" value={integrity.runs}/><Stat label="Execution intents" value={integrity.intents} tone={integrity.verification_gap?C.red:C.green}/><Stat label="Execution verifications" value={integrity.execution_verifications} tone={integrity.verification_gap?C.red:C.green}/><Stat label="Task verifications" value={integrity.task_verifications}/><Stat label="Heartbeat runs" value={integrity.heartbeat_runs}/><Stat label="Scheduler events" value={integrity.scheduler_events}/></section>{integrity.verification_gap&&<div role="alert" style={{padding:12,border:`1px solid ${C.red}55`,borderRadius:11,background:`${C.red}0d`,color:"#fecaca",fontSize:11.5,lineHeight:1.55}}><strong>Verification deficit.</strong> {integrity.historical_gap_note}</div>}</div></HQPanel>
   <div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(280px,1fr))",gap:12}}><HQPanel title="Worker Engine safety"><div style={{padding:14,display:"grid",gap:8,fontSize:11.5}}><div>Runtime execution <strong>{e.runtime_execution_enabled?"ON":"OFF"}</strong></div><div>Autonomy <strong>L{fmt(e.runtime_autonomy_level)}</strong></div><div>Maximum risk <strong>R{fmt(e.runtime_max_risk)}</strong></div><div>Global Stop <strong style={{color:e.shadow_global_stop?C.green:C.red}}>{e.shadow_global_stop?"ACTIVE":"NOT ACTIVE"}</strong></div><div>Factory <strong>{e.factory_enabled?"ON":"OFF"}</strong></div><div>Heartbeat <strong>{e.heartbeat_enabled?"ON":"OFF"}</strong></div><Link href="/hq/workforce" style={{marginTop:5,color:C.blue,textDecoration:"none",fontWeight:900}}>Open Worker Engine Control Room →</Link></div></HQPanel><HQPanel title="Notification pressure"><div style={{padding:14}}><section style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:8}}><Stat label="Open exceptions" value={data.notifications.open}/><Stat label="Deduplicated repeats" value={data.notifications.deduplicated_repeat_events}/></section><Link href="/hq/notifications" style={{display:"inline-block",marginTop:12,color:C.blue,textDecoration:"none",fontSize:11,fontWeight:900}}>Open Signal Center →</Link></div></HQPanel></div>
   <HQPanel title="Recent execution lineage" description="Runs without canonical intent/verification remain visibly unverified."><div style={{display:"grid"}}>{data.recent_execution.map((x,i)=><article key={x.id} style={{padding:12,borderBottom:i===data.recent_execution.length-1?"none":`1px solid ${C.border}`}}><div style={{display:"flex",gap:7,flexWrap:"wrap",alignItems:"center"}}><strong style={{fontSize:11.5}}>{x.lane_key}</strong><Badge tone={x.status==="verified"&&x.has_intent&&x.has_task_verification?C.green:C.amber}>{x.status}</Badge><Badge tone={x.has_intent?C.green:C.red}>{x.has_intent?"intent linked":"no intent"}</Badge><Badge tone={x.has_task_verification?C.green:C.red}>{x.has_task_verification?"verified trail":"no task verification"}</Badge></div><div style={{marginTop:5,fontSize:10.5,color:C.muted}}>Authority {x.authority_result??"—"} · {when(x.created_at)}</div></article>)}</div></HQPanel>
  </div>}
 </HQPage>
}
