"use client"

import { useCallback,useEffect,useMemo,useState } from "react"
import { useRouter } from "next/navigation"
import { supabase } from "@/lib/supabase"
const rpc=supabase.rpc.bind(supabase) as any
const C={bg:'#07111f',panel:'#0d1b2f',line:'rgba(255,255,255,.09)',text:'#f8fafc',muted:'rgba(255,255,255,.48)',green:'#34d399',amber:'#f59e0b',blue:'#60a5fa',red:'#fb7185'}
type Course={id:string;slug:string;title:string;institution:string|null;level:string|null;duration_label:string|null;domain:string;status:string;badge:string|null;description:string|null;weeks_count:number|null;modules_count:number|null};type Mod={id:string;course_id:string;slug:string;title:string;sequence_number:number;weeks_label:string|null};type Topic={id:string;module_id:string;slug:string;title:string;subtitle:string|null;sequence_number:number;week_number:number|null;concept_tab:any;kenya_context_tab:any;common_errors_tab:any;clinical_tip_tab:any;content_status:string};type Catalog={courses:Course[];modules:Mod[];topics:Topic[]}
const courseBlank={id:null as string|null,title:'',slug:'',institution:'',level:'',duration:'',domain:'education',status:'coming_soon',badge:'',description:'',weeks:0};const modBlank={id:null as string|null,courseId:'',title:'',slug:'',sequence:1,weeks:''};const topicBlank={id:null as string|null,moduleId:'',title:'',slug:'',subtitle:'',sequence:1,week:1,concept:'',kenya:'',errors:'',clinical:'',status:'draft'}
const txt=(v:any)=>typeof v?.text==='string'?v.text:''
export default function Academy(){const router=useRouter();const[data,setData]=useState<Catalog>({courses:[],modules:[],topics:[]});const[error,setError]=useState('');const[busy,setBusy]=useState('');const[course,setCourse]=useState(courseBlank);const[mod,setMod]=useState(modBlank);const[topic,setTopic]=useState(topicBlank)
 const load=useCallback(async()=>{const{data:d,error:e}=await rpc('hq_list_academy_catalog');if(e)setError(e.message);else setData(d??{courses:[],modules:[],topics:[]})},[]);useEffect(()=>{void load()},[load]);const mods=useMemo(()=>data.modules.filter(m=>!mod.courseId||m.course_id===mod.courseId),[data.modules,mod.courseId]);const topics=useMemo(()=>data.topics.filter(t=>!topic.moduleId||t.module_id===topic.moduleId),[data.topics,topic.moduleId])
 async function saveCourse(){setBusy('course');const{error:e}=await rpc('hq_upsert_academy_course',{p_id:course.id,p_slug:course.slug,p_title:course.title,p_institution:course.institution,p_level:course.level,p_duration_label:course.duration,p_domain:course.domain,p_status:course.status,p_badge:course.badge,p_description:course.description,p_weeks_count:course.weeks||null});if(e)setError(e.message);else{setCourse(courseBlank);await load()}setBusy('')}
 async function saveMod(){setBusy('module');const{error:e}=await rpc('hq_upsert_academy_module',{p_id:mod.id,p_course_id:mod.courseId,p_slug:mod.slug,p_title:mod.title,p_sequence_number:mod.sequence,p_weeks_label:mod.weeks});if(e)setError(e.message);else{setMod(modBlank);await load()}setBusy('')}
 async function saveTopic(){setBusy('topic');const{error:e}=await rpc('hq_upsert_academy_topic',{p_id:topic.id,p_module_id:topic.moduleId,p_slug:topic.slug,p_title:topic.title,p_subtitle:topic.subtitle,p_sequence_number:topic.sequence,p_week_number:topic.week,p_concept:topic.concept,p_kenya_context:topic.kenya,p_common_errors:topic.errors,p_clinical_tip:topic.clinical,p_content_status:topic.status});if(e)setError(e.message);else{setTopic(topicBlank);await load()}setBusy('')}
 return <main style={{minHeight:'100dvh',background:C.bg,color:C.text,padding:18,fontFamily:'Inter,system-ui,sans-serif'}}><div style={{maxWidth:1180,margin:'0 auto'}}><button onClick={()=>router.push('/hq/studio')} style={btn}>← Studio</button><h1>Academy</h1><p style={{color:C.muted,fontSize:12}}>Real course → module → topic management. Topic content preserves Concept, Kenya Context, Common Errors and specialist tip sections from the original HQ design.</p>{error&&<div style={{color:'#fecdd3'}}>{error}</div>}<div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(330px,1fr))',gap:12}}>
 <section style={panel}><h2 style={heading}>Courses · {data.courses.length}</h2>{[['Title','title'],['Slug','slug'],['Institution','institution'],['Level','level'],['Duration','duration'],['Badge','badge'],['Description','description']].map(([l,k])=><Field key={k} label={l} value={(course as any)[k]} onChange={v=>setCourse({...course,[k]:v})}/>)}<label style={lab}>Domain<select value={course.domain} onChange={e=>setCourse({...course,domain:e.target.value})} style={input}><option value="education">Education</option><option value="health">Health</option><option value="trade">Trade</option><option value="tech">Technology</option></select></label><label style={lab}>Status<select value={course.status} onChange={e=>setCourse({...course,status:e.target.value})} style={input}><option value="coming_soon">Coming soon</option><option value="live">Live</option></select></label><button disabled={busy==='course'} onClick={()=>void saveCourse()} style={{...btn,color:C.green}}>Save course</button><List>{data.courses.map(c=><button key={c.id} style={row} onClick={()=>{setCourse({id:c.id,title:c.title,slug:c.slug,institution:c.institution??'',level:c.level??'',duration:c.duration_label??'',domain:c.domain,status:c.status,badge:c.badge??'',description:c.description??'',weeks:c.weeks_count??0});setMod({...modBlank,courseId:c.id})}}><b>{c.title}</b><small>{c.domain} · {c.status} · {c.modules_count??0} modules</small></button>)}</List></section>
 <section style={panel}><h2 style={heading}>Modules · {data.modules.length}</h2><label style={lab}>Course<select value={mod.courseId} onChange={e=>setMod({...mod,courseId:e.target.value})} style={input}><option value="">Select course</option>{data.courses.map(c=><option key={c.id} value={c.id}>{c.title}</option>)}</select></label><Field label="Title" value={mod.title} onChange={v=>setMod({...mod,title:v})}/><Field label="Slug" value={mod.slug} onChange={v=>setMod({...mod,slug:v})}/><Field label="Weeks label" value={mod.weeks} onChange={v=>setMod({...mod,weeks:v})}/><label style={lab}>Sequence<input type="number" min={1} value={mod.sequence} onChange={e=>setMod({...mod,sequence:Number(e.target.value)||1})} style={input}/></label><button disabled={busy==='module'} onClick={()=>void saveMod()} style={{...btn,color:C.blue}}>Save module</button><List>{mods.map(m=><button key={m.id} style={row} onClick={()=>{setMod({id:m.id,courseId:m.course_id,title:m.title,slug:m.slug,sequence:m.sequence_number,weeks:m.weeks_label??''});setTopic({...topicBlank,moduleId:m.id})}}><b>{m.sequence_number} · {m.title}</b><small>{m.weeks_label||'No week label'}</small></button>)}</List></section>
 <section style={panel}><h2 style={heading}>Topics · {data.topics.length}</h2><label style={lab}>Module<select value={topic.moduleId} onChange={e=>setTopic({...topic,moduleId:e.target.value})} style={input}><option value="">Select module</option>{data.modules.map(m=><option key={m.id} value={m.id}>{m.title}</option>)}</select></label><Field label="Title" value={topic.title} onChange={v=>setTopic({...topic,title:v})}/><Field label="Subtitle" value={topic.subtitle} onChange={v=>setTopic({...topic,subtitle:v})}/><Field label="Concept" value={topic.concept} onChange={v=>setTopic({...topic,concept:v})} area/><Field label="Kenya Context" value={topic.kenya} onChange={v=>setTopic({...topic,kenya:v})} area/><Field label="Common Errors" value={topic.errors} onChange={v=>setTopic({...topic,errors:v})} area/><Field label="Specialist / Clinical Tip" value={topic.clinical} onChange={v=>setTopic({...topic,clinical:v})} area/><label style={lab}>Status<select value={topic.status} onChange={e=>setTopic({...topic,status:e.target.value})} style={input}><option value="draft">Draft</option><option value="in_review">In review</option><option value="published">Published</option></select></label><button disabled={busy==='topic'} onClick={()=>void saveTopic()} style={{...btn,color:C.amber}}>Save topic</button><List>{topics.map(t=><button key={t.id} style={row} onClick={()=>setTopic({id:t.id,moduleId:t.module_id,title:t.title,slug:t.slug,subtitle:t.subtitle??'',sequence:t.sequence_number,week:t.week_number??1,concept:txt(t.concept_tab),kenya:txt(t.kenya_context_tab),errors:txt(t.common_errors_tab),clinical:txt(t.clinical_tip_tab),status:t.content_status})}><b>{t.title}</b><small>{t.content_status} · week {t.week_number??'—'}</small></button>)}</List></section></div></div></main>}
function Field({label,value,onChange,area=false}:{label:string;value:string;onChange:(v:string)=>void;area?:boolean}){return <label style={lab}>{label}{area?<textarea rows={3} value={value} onChange={e=>onChange(e.target.value)} style={input}/>:<input value={value} onChange={e=>onChange(e.target.value)} style={input}/>}</label>};function List({children}:{children:React.ReactNode}){return <div style={{borderTop:`1px solid ${C.line}`,marginTop:12,paddingTop:6,maxHeight:260,overflow:'auto'}}>{children}</div>};const panel:React.CSSProperties={background:C.panel,border:`1px solid ${C.line}`,borderRadius:14,padding:14};const heading:React.CSSProperties={fontSize:14,margin:'0 0 10px'};const btn:React.CSSProperties={border:`1px solid ${C.line}`,background:'rgba(255,255,255,.04)',color:C.text,borderRadius:9,padding:'8px 10px',fontSize:11,fontWeight:800,cursor:'pointer'};const input:React.CSSProperties={width:'100%',boxSizing:'border-box',background:'#0a1628',border:`1px solid ${C.line}`,borderRadius:9,padding:9,color:C.text,marginTop:4};const lab:React.CSSProperties={display:'block',fontSize:10,color:C.muted,fontWeight:800,marginBottom:8};const row:React.CSSProperties={width:'100%',display:'block',textAlign:'left',border:0,borderTop:`1px solid ${C.line}`,background:'transparent',color:C.text,padding:'9px 3px',cursor:'pointer'}
