import type { Metadata } from 'next'
import Link from 'next/link'
import { PublicHeader } from '@/components/public/PublicHeader'
import { PublicFooter } from '@/components/public/PublicFooter'

export const metadata: Metadata = {
  title: 'VibeSchool for Families | Understand and support learning',
  description: 'See how VibeSchool is designed to help authorised parents and guardians understand learner progress, attendance, school communication and future pathways.',
}

const needs = [
  ['Understand progress', 'See learning context in language intended to help a family understand what is going well, what needs attention and what may happen next.'],
  ['Stay connected', 'Receive relevant school and teacher communication through the authorised learner relationship instead of relying on disconnected messages.'],
  ['See attendance context', 'Where enabled by the school, attendance information can contribute to the wider picture of learner participation.'],
  ['Support next actions', 'Progress should lead to useful follow-up: revision, practice, teacher support or another appropriate educational action.'],
  ['Navigate Pathways', 'Families can explore Senior School pathways, tracks, subjects, careers and school information with the learner.'],
  ['Respect boundaries', 'Parent access is relationship-based. Teacher-only, learner-private and administrative information should not become broadly visible.'],
]

export default function FamiliesPage(){return <div className="page"><PublicHeader product="Families"/><main id="main-content">
<section className="hero"><div className="wrap"><p className="eyebrow">VIBESCHOOL FOR FAMILIES</p><h1>Know how learning is going — before the report card arrives.</h1><p className="lead">VibeSchool is designed to help authorised parents and guardians understand the learner journey: participation, progress, evidence, school communication and the next support that may matter.</p><div className="actions"><Link className="primary" href="/global">Explore learning</Link><Link className="secondary" href="/pathways">Explore Pathways</Link></div></div></section>
<section className="section wrap"><p className="eyebrow dark">THE FAMILY EXPERIENCE</p><h2>Useful context, not another stream of school notifications.</h2><p className="intro">A family should be able to understand the child’s education without needing access to every teacher or administrative workspace. VibeSchool separates the family relationship from internal school authority.</p><div className="grid">{needs.map(([t,d])=><article key={t}><h3>{t}</h3><p>{d}</p></article>)}</div></section>
<section className="section alt"><div className="wrap two"><div><p className="eyebrow dark">ONE LEARNER STORY</p><h2>Connect the report to what happened before it.</h2></div><div className="story"><p><strong>Learning activity</strong><span>What the learner engaged with.</span></p><p><strong>Evidence & assessment</strong><span>What the learner demonstrated.</span></p><p><strong>Progress</strong><span>What appears understood and what needs more support.</span></p><p><strong>Next action</strong><span>What the learner, teacher or family can do next.</span></p></div></div></section>
<section className="section dark"><div className="wrap"><p className="eyebrow">PRIVACY IS PART OF THE PRODUCT</p><h2>Being a parent does not mean seeing everything.</h2><p className="lead small">VibeSchool is designed around verified relationships and role-aware access. Families should receive the information appropriate to supporting their learner while school, teacher and learner boundaries remain protected.</p><div className="actions"><Link className="gold" href="/trust/child-safety">Child safety</Link><Link className="darkLink" href="/trust/security">Security approach</Link><Link className="darkLink" href="/legal/privacy">Privacy</Link></div></div></section>
<section className="section wrap"><div className="two"><div><p className="eyebrow dark">LEARNING BEYOND SCHOOL HOURS</p><h2>A continuing learning place for the learner.</h2></div><div><p className="copy">The public VibeSchool learning library and Pathways experiences are designed to give learners and families useful educational resources beyond a single school report. As personalised experiences expand, they should remain connected to trustworthy learner context rather than becoming an isolated content feed.</p><div className="actions"><Link className="primary" href="/global">Open learning library</Link><Link className="outline" href="/product">See the whole product</Link></div></div></div></section>
</main><PublicFooter/><style>{styles}</style></div>}

const styles=`.page{background:#fbfaf7;color:#15161c;font-family:var(--font-jakarta),Arial,sans-serif;line-height:1.7}.page *{box-sizing:border-box}.wrap{width:min(1120px,100%);margin:auto}.hero{padding:92px 22px 100px;background:radial-gradient(circle at 82% 18%,rgba(215,177,87,.19),transparent 30%),linear-gradient(180deg,#fff9e9,#fff)}.eyebrow{font:900 11px var(--font-mono),monospace;letter-spacing:.15em;color:#856519}.eyebrow.dark{color:#765b18}h1,h2{font-family:var(--font-display),Arial,sans-serif;letter-spacing:-.045em;line-height:1.04}h1{font-size:clamp(44px,6.6vw,76px);max-width:900px;margin:14px 0 22px}h2{font-size:clamp(32px,4.5vw,52px);margin:10px 0 20px;max-width:850px}.lead,.intro,.copy{color:#62636c;font-size:18px;max-width:820px}.actions{display:flex;gap:11px;flex-wrap:wrap;margin-top:27px}.actions a{display:inline-flex;align-items:center;justify-content:center;min-height:46px;padding:0 18px;border-radius:11px;text-decoration:none;font-weight:850}.primary{background:#17171d;color:#fff}.secondary,.outline{background:#fff;color:#24252c;border:1px solid #d7d5cd}.section{padding:86px 22px}.grid{display:grid;grid-template-columns:repeat(3,1fr);gap:13px;margin-top:32px}.grid article{background:#fff;border:1px solid #e3e0d7;border-radius:18px;padding:26px;min-height:205px}.grid h3{font-size:21px;margin:0 0 9px}.grid p{color:#64656d;margin:0}.alt{background:#eee9de}.two{display:grid;grid-template-columns:1fr 1fr;gap:68px}.story{display:grid;gap:9px}.story p{background:#fff;border:1px solid #ddd7ca;border-radius:14px;padding:17px 19px;margin:0;display:flex;flex-direction:column}.story span{color:#696a70;font-size:14px}.dark{background:#101218;color:#fff}.dark .lead{color:#b8bac2}.lead.small{font-size:17px}.gold{background:#d5b45c;color:#101218}.darkLink{border:1px solid #454852;color:#fff}@media(max-width:800px){.grid{grid-template-columns:1fr 1fr}.two{grid-template-columns:1fr;gap:18px}}@media(max-width:600px){.hero,.section{padding:62px 18px}.grid{grid-template-columns:1fr}.primary,.secondary,.outline{width:100%}}`
