"use client";
export const dynamic = "force-dynamic";

import { useEffect, useMemo, useRef, useState } from 'react'
import { useRouter } from 'next/navigation'
import { supabase } from '@/lib/supabase'
import { Card, SectionLabel, Btn, C } from '@/components/teacher/ui'

type EventRow={id:string;title:string;description:string|null;event_type:string;starts_at:string;ends_at:string|null;all_day:boolean;location:string|null;priority:string}
type Notice={id:string;title:string;body:string;sent_at:string;requires_ack:boolean;ack_deadline:string|null;ack_at:string|null}
type Exception={id:string;exception_date:string;kind:string;label:string;suppress_ordinary_teaching:boolean}
type Info={school_id:string|null;events:EventRow[];notices:Notice[];calendar_exceptions:Exception[]}
type TeachingRole={class_id:string;class_name:string;subject_name:string;is_class_teacher:boolean}
type Appointment={id:string;title:string;category:string;scope_label:string;sharing_mode:'shared'|'lead_and_support';member_role:'lead'|'member';starts_on:string;ends_on:string|null;colleagues:Array<{name:string;role:string}>}
type TeacherOption={id:string;name:string}
type AdminResponsibility={id:string;title:string;category:string;scope_label:string;sharing_mode:'shared'|'lead_and_support';starts_on:string;ends_on:string|null;members:Array<{id:string;name:string;role:'lead'|'member'}>;upcoming_members:Array<{id:string;name:string;role:'lead'|'member';starts_on:string}>;history:Array<{id:string;name:string;role:'lead'|'member';starts_on:string;ends_on:string|null;end_reason:'handover'|'rescheduled'|null;ended_by_name:string}>}
type ResponsibilityContext={school_id:string|null;teaching_roles:TeachingRole[];appointments:Appointment[];upcoming_appointments:Appointment[]}
type ResponsibilityAdminContext={school_id:string|null;teachers:TeacherOption[];responsibilities:AdminResponsibility[]}
const inputStyle:React.CSSProperties={width:'100%',minHeight:42,border:'1px solid #d1d5db',borderRadius:10,padding:'8px 10px',fontSize:13,boxSizing:'border-box'}
const nairobiToday=()=>new Date().toLocaleDateString('en-CA',{timeZone:'Africa/Nairobi'})
const addSchoolDays=(value:string,days:number)=>{const [year,month,day]=value.split('-').map(Number);const date=new Date(Date.UTC(year,month-1,day+days));return `${date.getUTCFullYear()}-${String(date.getUTCMonth()+1).padStart(2,'0')}-${String(date.getUTCDate()).padStart(2,'0')}`}
const laterDate=(left:string,right:string)=>left>right?left:right

function fmt(v:string){return new Date(v).toLocaleString('en-KE',{timeZone:'Africa/Nairobi',weekday:'short',day:'numeric',month:'short',hour:'numeric',minute:'2-digit'})}
export default function SchoolHubPage(){
 const assignmentRequest=useRef<{payload:string;id:string}|null>(null)
 const handoverRequest=useRef<{payload:string;id:string}|null>(null)
 const router=useRouter(); const [info,setInfo]=useState<Info|null>(null); const [school,setSchool]=useState<{name:string;county:string|null;school_type:string|null}|null>(null); const [responsibility,setResponsibility]=useState<ResponsibilityContext|null>(null); const [adminContext,setAdminContext]=useState<ResponsibilityAdminContext|null>(null); const [loading,setLoading]=useState(true); const [error,setError]=useState(''); const [actionError,setActionError]=useState(''); const [actionMessage,setActionMessage]=useState(''); const [saving,setSaving]=useState(false)
 const [title,setTitle]=useState(''); const [category,setCategory]=useState('games'); const [scopeLabel,setScopeLabel]=useState(''); const [sharingMode,setSharingMode]=useState<'shared'|'lead_and_support'>('shared'); const [startsOn,setStartsOn]=useState(nairobiToday()); const [endsOn,setEndsOn]=useState(''); const [teacherIds,setTeacherIds]=useState<string[]>([]); const [leadId,setLeadId]=useState('')
 const [transferId,setTransferId]=useState(''); const [transferDate,setTransferDate]=useState(nairobiToday()); const [transferTeacherIds,setTransferTeacherIds]=useState<string[]>([]); const [transferLeadId,setTransferLeadId]=useState('')
 async function load(){
  setLoading(true);setError('')
  try{
   const {data:{user}}=await supabase.auth.getUser(); if(!user){router.replace('/');return}
   const [{data:context,error:contextError},{data,error:e}]=await Promise.all([
    supabase.rpc('get_my_teacher_school_context'),
    supabase.rpc('get_my_teacher_school_information',{p_from:new Date().toISOString(),p_until:new Date(Date.now()+14*86400000).toISOString()})
   ])
   if(contextError)throw contextError
   const activeSchoolId=(context as {active_school_id?:string|null}|null)?.active_school_id??null
   if(!activeSchoolId){setInfo({school_id:null,events:[],notices:[],calendar_exceptions:[]});setSchool(null);setResponsibility(null);setAdminContext(null);return}
   // Information is optional enrichment. It cannot revoke a canonical active-school membership.
   if(e)console.error('[SchoolHub] information enrichment failed',e)
   const raw=(data??{}) as Partial<Info>
   const x:Info={school_id:activeSchoolId,events:raw.events??[],notices:raw.notices??[],calendar_exceptions:raw.calendar_exceptions??[]}; setInfo(x)
   const [schoolResult,rolesResult,adminResult]=await Promise.all([
    supabase.from('schools').select('name,county,school_type').eq('id',activeSchoolId).single(),
    supabase.rpc('teacher_get_my_school_responsibilities' as never,{} as never),
    supabase.rpc('teacher_get_school_responsibility_admin_context' as never,{} as never),
   ]);
   if(schoolResult.error)throw schoolResult.error;setSchool(schoolResult.data)
   const roles=rolesResult.data as ResponsibilityContext|null;if(rolesResult.error)throw rolesResult.error;if(roles?.school_id!==activeSchoolId)throw new Error('Your school responsibilities could not be matched to the active school.');setResponsibility(roles)
   const admin=adminResult.data as ResponsibilityAdminContext|null;setAdminContext(!adminResult.error&&admin?.school_id===activeSchoolId?admin:null)
  }catch(c){setError(c instanceof Error?c.message:'School information could not be loaded.')}finally{setLoading(false)}
 }
 useEffect(()=>{void load()},[])
 const urgent=useMemo(()=>info?.notices.filter(n=>n.requires_ack&&!n.ack_at)??[],[info])
 const adminTeachers=adminContext?.teachers??[];const adminResponsibilities=adminContext?.responsibilities??[];const selectedTransfer=adminResponsibilities.find(row=>row.id===transferId)
 async function assignResponsibility(){if(!info?.school_id||!title.trim()||!scopeLabel.trim()||teacherIds.length===0){setActionError('Add a name, scope and at least one teacher.');return}if(sharingMode==='lead_and_support'&&(teacherIds.length<2||!leadId||!teacherIds.includes(leadId))){setActionError('Choose a lead and at least one supporting teacher.');return}setSaving(true);setActionError('');setActionMessage('');try{const members=teacherIds.map(profile_id=>({profile_id,role:sharingMode==='shared'?'member':profile_id===leadId?'lead':'member'}));const args={p_school_id:info.school_id,p_title:title.trim(),p_category:category,p_scope_label:scopeLabel.trim(),p_sharing_mode:sharingMode,p_starts_on:startsOn,p_ends_on:endsOn||null,p_members:members};const payload=JSON.stringify(args);if(assignmentRequest.current?.payload!==payload)assignmentRequest.current={payload,id:crypto.randomUUID()};const requestId=assignmentRequest.current!.id;const {error:saveError}=await supabase.rpc('admin_assign_school_responsibility' as never,{...args,p_request_id:requestId} as never);if(saveError)throw saveError;assignmentRequest.current=null;setTitle('');setScopeLabel('');setTeacherIds([]);setLeadId('');setActionMessage('Responsibility assigned. It will appear in each teacher’s School Hub while active.');await load()}catch(e){setActionError(e instanceof Error?e.message:'The responsibility could not be assigned.')}finally{setSaving(false)}}
 async function transferResponsibility(){const selected=selectedTransfer;if(!selected||transferTeacherIds.length===0){setActionError('Choose an appointment and at least one teacher for the handover.');return}if(selected.sharing_mode==='lead_and_support'&&(transferTeacherIds.length<2||!transferLeadId||!transferTeacherIds.includes(transferLeadId))){setActionError('Choose one lead and at least one supporting teacher.');return}const minimumDate=laterDate(addSchoolDays(nairobiToday(),1),addSchoolDays(selected.starts_on,1));if(transferDate<minimumDate){setActionError(`Choose a handover date on or after ${minimumDate}.`);return}setSaving(true);setActionError('');setActionMessage('');try{const members=transferTeacherIds.map(profile_id=>({profile_id,role:selected.sharing_mode==='shared'?'member':profile_id===transferLeadId?'lead':'member'}));const rpcName=selected.upcoming_members.length?'admin_reschedule_school_responsibility_handover':'admin_transfer_school_responsibility';const args={p_responsibility_id:transferId,p_effective_on:transferDate,p_members:members};const payload=JSON.stringify({rpcName,...args});if(handoverRequest.current?.payload!==payload)handoverRequest.current={payload,id:crypto.randomUUID()};(args as typeof args&{p_request_id:string}).p_request_id=handoverRequest.current.id;const {error:transferError}=await supabase.rpc(rpcName as never,args as never);if(transferError)throw transferError;handoverRequest.current=null;setActionMessage(selected.upcoming_members.length?'The handover was rescheduled. The previous schedule remains in the appointment history.':'The handover is recorded. The previous team remains in the appointment history.');setTransferId('');setTransferTeacherIds([]);setTransferLeadId('');await load()}catch(e){setActionError(e instanceof Error?e.message:'The responsibility could not be handed over.')}finally{setSaving(false)}}
 if(loading)return <div style={{padding:16}}><Card><div style={{color:C.textMuted}}>Loading your school…</div></Card></div>
 if(!info?.school_id)return <div style={{padding:16}}><Card><SectionLabel>School setup</SectionLabel><h1 style={{fontSize:20}}>Connect your school</h1><p style={{color:C.textMuted,fontSize:13}}>School information becomes available after your active school membership is confirmed.</p><Btn onClick={()=>router.push('/teacher/onboarding/school')}>Find or connect school</Btn></Card></div>
 return <div style={{padding:'16px 16px 32px',display:'grid',gap:12}}>
  <section style={{background:'linear-gradient(135deg,#0f172a,#312e81)',color:'#fff',borderRadius:20,padding:18}}>
   <div style={{fontSize:10,fontWeight:900,letterSpacing:1,textTransform:'uppercase',color:'#a7f3d0'}}>My school</div>
   <h1 style={{fontSize:21,margin:'5px 0'}}>{school?.name??'School'}</h1>
   <div style={{fontSize:11,color:'#cbd5e1'}}>{[school?.school_type,school?.county].filter(Boolean).join(' · ')}</div>
   <div style={{display:'flex',gap:8,marginTop:12,flexWrap:'wrap'}}><Btn small onClick={()=>router.push('/teacher/classhub')}>My classes</Btn><Btn small variant="ghost" onClick={()=>router.push('/teacher/timetable')}>Timetable</Btn><Btn small variant="ghost" onClick={()=>router.push('/teacher/onboarding/school')}>Change school</Btn></div>
  </section>
  {error&&<div style={{padding:11,border:'1px solid #fecaca',background:'#fef2f2',borderRadius:12,color:'#b91c1c',fontSize:12}}>{error}<button onClick={()=>void load()} style={{marginLeft:8}}>Retry</button></div>}
  <Card><SectionLabel>Needs your attention</SectionLabel>{urgent.length===0?<p style={{fontSize:12,color:C.textMuted}}>No acknowledgement is waiting for you.</p>:urgent.slice(0,3).map(n=><button key={n.id} onClick={()=>router.push('/teacher/vibeconnect')} style={rowButton}><span><b>{n.title}</b><small>{fmt(n.sent_at)} · acknowledgement required</small></span><b>›</b></button>)}</Card>
  <Card><SectionLabel>Coming up</SectionLabel>{info.events.length===0?<p style={{fontSize:12,color:C.textMuted}}>No targeted school events in the next 14 days.</p>:info.events.slice(0,5).map(e=><div key={e.id} style={row}><div><b style={{fontSize:12}}>{e.title}</b><small>{e.all_day?new Date(e.starts_at).toLocaleDateString('en-KE',{timeZone:'Africa/Nairobi',weekday:'short',day:'numeric',month:'short'}):fmt(e.starts_at)}{e.location?' · '+e.location:''}</small></div><span style={pill}>{e.event_type.replace('_',' ')}</span></div>)}</Card>
  <Card><SectionLabel>School calendar</SectionLabel>{info.calendar_exceptions.length===0?<p style={{fontSize:12,color:C.textMuted}}>No school calendar exception in the next 14 days.</p>:info.calendar_exceptions.map(x=><div key={x.id} style={row}><div><b style={{fontSize:12}}>{x.label}</b><small>{new Date(x.exception_date+'T12:00:00+03:00').toLocaleDateString('en-KE',{weekday:'long',day:'numeric',month:'short'})}</small></div>{x.suppress_ordinary_teaching&&<span style={pill}>No ordinary lessons</span>}</div>)}</Card>
  <Card><SectionLabel>Official notices</SectionLabel>{info.notices.length===0?<p style={{fontSize:12,color:C.textMuted}}>No official school notice has been delivered to you.</p>:info.notices.slice(0,4).map(n=><button key={n.id} onClick={()=>router.push('/teacher/vibeconnect')} style={rowButton}><span><b>{n.title}</b><small>{fmt(n.sent_at)}{n.requires_ack?(n.ack_at?' · acknowledged':' · acknowledgement required'):''}</small></span><b>›</b></button>)}<div style={{marginTop:10}}><Btn small variant="ghost" onClick={()=>router.push('/teacher/vibeconnect')}>Open communications</Btn></div></Card>
  <Card><SectionLabel>School resources</SectionLabel><p style={{fontSize:12,color:C.textMuted,margin:'4px 0 10px'}}>Policies, circular documents and staff resources remain in the School Resources authority.</p><Btn small variant="ghost" onClick={()=>router.push('/teacher/resources')}>Open resources</Btn></Card>
  <Card><SectionLabel>My responsibilities</SectionLabel><p style={{fontSize:12,color:C.textMuted}}>Your teaching roles come from your class and subject assignments. Extra school duties can be shared or given to a lead with supporting teachers.</p>
   <div style={{display:'grid',gap:7}}>{responsibility?.teaching_roles.map((role,index)=><div key={`${role.class_id}:${role.subject_name}:${index}`} style={row}><span><b>{role.is_class_teacher?'Class teacher':'Subject teacher'}</b><small>{role.class_name} · {role.subject_name}</small></span><span style={pill}>{role.is_class_teacher?'Class':'Subject'}</span></div>)}</div>
   <div style={{display:'grid',gap:8,marginTop:8}}>{responsibility?.appointments.map(appointment=><div key={appointment.id} style={{...row,display:'block'}}><div style={{display:'flex',justifyContent:'space-between',gap:8}}><b>{appointment.title}</b><span style={pill}>{appointment.member_role==='lead'?'Lead':'Shared'}</span></div><small style={{display:'block'}}>{appointment.scope_label} · {appointment.category.replaceAll('_',' ')} · {appointment.starts_on}{appointment.ends_on?` to ${appointment.ends_on}`:' · ongoing'}</small>{appointment.colleagues.length>0&&<small style={{display:'block'}}>Working with {appointment.colleagues.map(p=>p.name).join(', ')}</small>}</div>)}</div>
   {!!responsibility?.upcoming_appointments.length&&<div style={{marginTop:12}}><SectionLabel>Upcoming responsibilities</SectionLabel><p style={{fontSize:11,color:C.textMuted}}>These appointments are scheduled for a future date. They do not grant access to the records before they start.</p>{responsibility.upcoming_appointments.map(appointment=><div key={appointment.id} style={{...row,display:'block'}}><div style={{display:'flex',justifyContent:'space-between',gap:8}}><b>{appointment.title}</b><span style={pill}>{appointment.member_role==='lead'?'Lead':'Shared'}</span></div><small style={{display:'block'}}>{appointment.scope_label} · starts {appointment.starts_on}{appointment.ends_on?` · ends ${appointment.ends_on}`:''}</small>{appointment.colleagues.length>0&&<small style={{display:'block'}}>Scheduled with {appointment.colleagues.map(p=>p.name).join(', ')}</small>}</div>)}</div>}
   {!responsibility?.teaching_roles.length&&!responsibility?.appointments.length&&!responsibility?.upcoming_appointments.length&&<p style={{fontSize:12,color:C.textMuted}}>No teaching assignments or extra responsibilities are connected to this school yet.</p>}
   {adminContext&&<details style={{marginTop:12}}><summary style={{cursor:'pointer',fontSize:13,fontWeight:850}}>Assign a school responsibility</summary><div style={{display:'grid',gap:9,marginTop:10}}>
    <label style={formLabel}>Name<input style={inputStyle} maxLength={100} value={title} onChange={e=>setTitle(e.target.value)} placeholder="e.g. Games teacher"/></label>
    <label style={formLabel}>Area<select style={inputStyle} value={category} onChange={e=>setCategory(e.target.value)}><option value="games">Games</option><option value="department">Department</option><option value="club">Club</option><option value="teacher_duty">Teacher duty</option><option value="examination">Examinations</option><option value="event">Event</option><option value="other">Other</option></select></label>
    <label style={formLabel}>What is the responsibility for?<input style={inputStyle} maxLength={120} value={scopeLabel} onChange={e=>setScopeLabel(e.target.value)} placeholder="e.g. Athletics team · Term 3"/></label>
    <label style={formLabel}>How will teachers share it?<select style={inputStyle} value={sharingMode} onChange={e=>setSharingMode(e.target.value as typeof sharingMode)}><option value="shared">Shared responsibility</option><option value="lead_and_support">One lead with supporting teachers</option></select></label>
    {sharingMode==='lead_and_support'&&<label style={formLabel}>Lead teacher<select style={inputStyle} value={leadId} onChange={e=>setLeadId(e.target.value)}><option value="">Choose lead</option>{adminContext.teachers.filter(t=>teacherIds.includes(t.id)).map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select></label>}
    <fieldset style={{border:'1px solid #d1d5db',borderRadius:11,padding:10}}><legend style={{fontSize:12,fontWeight:800}}>Teachers assigned</legend><div style={{maxHeight:180,overflowY:'auto',display:'grid',gap:4}}>{adminContext.teachers.map(t=><label key={t.id} style={{fontSize:13}}><input type="checkbox" checked={teacherIds.includes(t.id)} onChange={()=>setTeacherIds(ids=>ids.includes(t.id)?ids.filter(id=>id!==t.id):ids.length<20?[...ids,t.id]:ids)}/> {t.name}</label>)}</div></fieldset>
    <div style={{display:'grid',gridTemplateColumns:'repeat(2,minmax(0,1fr))',gap:8}}><label style={formLabel}>Starts<input style={inputStyle} type="date" value={startsOn} onChange={e=>setStartsOn(e.target.value)}/></label><label style={formLabel}>Ends (optional)<input style={inputStyle} type="date" min={startsOn} value={endsOn} onChange={e=>setEndsOn(e.target.value)}/></label></div>
    {actionError&&<p role="alert" style={{fontSize:12,color:'#b91c1c'}}>{actionError}</p>}{actionMessage&&<p role="status" style={{fontSize:12,color:'#047857'}}>{actionMessage}</p>}
    <Btn small disabled={saving} onClick={()=>void assignResponsibility()}>{saving?'Assigning…':'Assign responsibility'}</Btn><small style={{color:C.textMuted}}>Only a school administrator can make an official school assignment. It grants no access to unrelated school records.</small>
   </div></details>}
   {adminResponsibilities.length>0&&<details style={{marginTop:12}}><summary style={{cursor:'pointer',fontSize:13,fontWeight:850}}>Hand over a responsibility</summary><div style={{display:'grid',gap:9,marginTop:10}}>
    <label style={formLabel}>Responsibility<select style={inputStyle} value={transferId} onChange={e=>{const id=e.target.value;setTransferId(id);const row=adminResponsibilities.find(item=>item.id===id);const team=row?.upcoming_members.length?row.upcoming_members:row?.members;setTransferTeacherIds(team?.map(m=>m.id)??[]);setTransferLeadId(team?.find(m=>m.role==='lead')?.id??'');if(row)setTransferDate(laterDate(addSchoolDays(nairobiToday(),1),addSchoolDays(row.starts_on,1)))}}><option value="">Choose an appointment</option>{adminResponsibilities.map(row=><option key={row.id} value={row.id}>{row.title} · {row.scope_label}</option>)}</select></label>
    {transferId&&<><div style={{fontSize:12,color:C.textMuted}}>Current team: {selectedTransfer?.members.map(m=>m.name).join(', ')||'No current members'}{selectedTransfer?.upcoming_members.length?` · Scheduled from ${selectedTransfer.upcoming_members[0].starts_on}: ${selectedTransfer.upcoming_members.map(m=>m.name).join(', ')}`:''}</div>{selectedTransfer&&selectedTransfer.history&&selectedTransfer.history.length>0&&<div style={{fontSize:11,color:C.textMuted}}>Previous team history: {selectedTransfer.history.map(m=>`${m.name} · ${m.role} · ${m.starts_on}${m.ends_on?` to ${m.ends_on}`:''} · ${m.end_reason==='rescheduled'?'rescheduled':'handed over'} by ${m.ended_by_name}`).join('; ')}</div>}<label style={formLabel}>{selectedTransfer?.upcoming_members.length?'Rescheduled team starts on':'New team starts on'}<input style={inputStyle} type="date" min={selectedTransfer?laterDate(addSchoolDays(nairobiToday(),1),addSchoolDays(selectedTransfer.starts_on,1)):addSchoolDays(nairobiToday(),1)} max={selectedTransfer?.ends_on??undefined} value={transferDate} onChange={e=>setTransferDate(e.target.value)}/></label><fieldset style={{border:'1px solid #d1d5db',borderRadius:11,padding:10}}><legend style={{fontSize:12,fontWeight:800}}>{selectedTransfer?.upcoming_members.length?'Teachers in the corrected handover':'Teachers taking over'}</legend><div style={{maxHeight:180,overflowY:'auto',display:'grid',gap:4}}>{adminTeachers.map(t=><label key={t.id} style={{fontSize:13}}><input type="checkbox" checked={transferTeacherIds.includes(t.id)} onChange={()=>setTransferTeacherIds(ids=>ids.includes(t.id)?ids.filter(id=>id!==t.id):ids.length<20?[...ids,t.id]:ids)}/> {t.name}</label>)}</div></fieldset>{selectedTransfer?.sharing_mode==='lead_and_support'&&<label style={formLabel}>New lead teacher<select style={inputStyle} value={transferLeadId} onChange={e=>setTransferLeadId(e.target.value)}><option value="">Choose lead</option>{adminTeachers.filter(t=>transferTeacherIds.includes(t.id)).map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select></label>}<Btn small disabled={saving||!selectedTransfer||transferDate<laterDate(addSchoolDays(nairobiToday(),1),addSchoolDays(selectedTransfer.starts_on,1))} onClick={()=>void transferResponsibility()}>{saving?'Saving handover…':selectedTransfer?.upcoming_members.length?'Reschedule handover':'Record handover'}</Btn></>}
   </div></details>}
   {(actionError||actionMessage)&&<div role={actionError?'alert':'status'} style={{fontSize:12,color:actionError?'#b91c1c':'#047857',marginTop:8}}>{actionError||actionMessage}</div>}
  </Card>
 </div>
}
const row:React.CSSProperties={display:'flex',justifyContent:'space-between',alignItems:'center',gap:10,padding:'10px 0',borderBottom:`1px solid ${C.border}`}
const rowButton:React.CSSProperties={...row,width:'100%',background:'transparent',borderTop:0,borderLeft:0,borderRight:0,textAlign:'left',fontFamily:'inherit',cursor:'pointer'}
const pill:React.CSSProperties={fontSize:9,fontWeight:800,borderRadius:999,padding:'3px 7px',background:'#eef2ff',color:'#4338ca',textTransform:'capitalize'}
const formLabel:React.CSSProperties={display:'grid',gap:5,fontSize:12,fontWeight:800}
