"use client"

import React, { useMemo, useState } from 'react'
import type { ContentBlock } from '@/lib/publishTypes'

const TEXT='#fff', MUTED='rgba(255,255,255,.65)', ACCENT='#CCFF00', CARD='#111827', INNER='#0b1220', BORDER='rgba(255,255,255,.1)'
export const CHEMISTRY_G10_LABS=['chemistry_lab_safety','chemistry_atomic_structure','chemistry_periodic_table','chemistry_bonding_properties_lab','chemistry_periodicity_lab','chemistry_acid_base_lab','chemistry_salts_lab'] as const
export type ChemistryG10Lab=typeof CHEMISTRY_G10_LABS[number]
export const isChemistryG10Lab=(v:unknown):v is ChemistryG10Lab=>typeof v==='string'&&(CHEMISTRY_G10_LABS as readonly string[]).includes(v)
function Shell({title,purpose,children}:{title:string;purpose:string;children:React.ReactNode}){return <section style={{background:CARD,border:`1px solid ${BORDER}`,borderRadius:16,padding:16}}><div style={{color:ACCENT,fontSize:10,fontWeight:900,letterSpacing:'.12em'}}>VIBELAB · GRADE 10 CHEMISTRY</div><h3 style={{color:TEXT,fontSize:18,margin:'6px 0'}}>{title}</h3><p style={{color:MUTED,fontSize:13,lineHeight:1.6}}>{purpose}</p>{children}</section>}
const button:React.CSSProperties={minHeight:44,border:`1px solid ${BORDER}`,borderRadius:10,background:INNER,color:TEXT,padding:'10px 12px',fontWeight:800}
function Safety({block}:{block:ContentBlock}){const cases=[['Heating a test tube','Point its open end away from people.','Correct: heated containers must never point towards anyone.'],['Chemical splashes into an eye','Use the approved eyewash/running clean water and alert the teacher immediately.','Correct: immediate rinsing and teacher assistance are essential.'],['Broken glass on the bench','Tell the teacher and use the approved glass-disposal procedure.','Correct: do not pick broken glass up with bare hands.']];const[i,setI]=useState(0);const[msg,setMsg]=useState('');return <Shell title={block.content||'Laboratory safety decisions'} purpose="Choose the safest response to common school-laboratory situations."><div style={{color:TEXT,fontWeight:850,marginBottom:10}}>{cases[i][0]}</div>{[cases[i][1],'Continue working and deal with it later.','Handle the hazard with bare hands if you are careful.'].sort().map(x=><button key={x} style={{...button,width:'100%',marginBottom:7,textAlign:'left'}} onClick={()=>setMsg(x===cases[i][1]?cases[i][2]:'Not safe. Stop, protect people from the hazard, and follow the teacher-approved laboratory procedure.')}>{x}</button>)}<p aria-live="polite" style={{color:msg.startsWith('Correct')?ACCENT:TEXT,minHeight:38}}>{msg}</p><button style={{...button,width:'100%'}} onClick={()=>{setI(v=>(v+1)%cases.length);setMsg('')}}>Next situation</button></Shell>}
const elements=[['H','Hydrogen',1,1,1,'non-metal'],['He','Helium',2,18,1,'noble gas'],['Li','Lithium',3,1,2,'metal'],['C','Carbon',6,14,2,'non-metal'],['O','Oxygen',8,16,2,'non-metal'],['Na','Sodium',11,1,3,'metal'],['Mg','Magnesium',12,2,3,'metal'],['Cl','Chlorine',17,17,3,'non-metal'],['Ar','Argon',18,18,3,'noble gas'],['K','Potassium',19,1,4,'metal'],['Ca','Calcium',20,2,4,'metal']] as const
function Atom({block}:{block:ContentBlock}){const[p,setP]=useState(6),[n,setN]=useState(6),[e,setE]=useState(6);const charge=p-e;return <Shell title={block.content||'Build an atom'} purpose="Change protons, neutrons and electrons. Observe how atomic number, mass number and charge respond."><div style={{display:'grid',gridTemplateColumns:'repeat(3,minmax(0,1fr))',gap:8}}>{[['Protons',p,setP],['Neutrons',n,setN],['Electrons',e,setE]].map(([l,v,s]:any)=><label key={l} style={{color:MUTED,fontSize:11}}>{l}<input aria-label={l} type="number" min={0} max={20} value={v} onChange={x=>s(Math.max(0,Math.min(20,Number(x.target.value))))} style={{width:'100%',boxSizing:'border-box',marginTop:5,padding:10,borderRadius:9,background:INNER,color:TEXT,border:`1px solid ${BORDER}`}}/></label>)}</div><div style={{marginTop:14,color:TEXT,lineHeight:1.8}}>Atomic number: <b>{p}</b> · Mass number: <b>{p+n}</b> · Charge: <b>{charge===0?'neutral':charge>0?`+${charge}`:charge}</b><br/><span style={{color:MUTED}}>Model note: particle positions and sizes are simplified and not drawn to scale.</span></div></Shell>}
function Periodic({block}:{block:ContentBlock}){const[selected,setSelected]=useState(elements[5]);return <Shell title={block.content||'Explore the periodic table'} purpose="Select an element and connect atomic number with group and period position."><div style={{display:'flex',flexWrap:'wrap',gap:7}}>{elements.map(el=><button key={el[0]} style={{...button,minWidth:52,color:selected[0]===el[0]?ACCENT:TEXT}} onClick={()=>setSelected(el)}>{el[0]}<small style={{display:'block'}}>{el[2]}</small></button>)}</div><div style={{marginTop:14,padding:12,background:INNER,borderRadius:10,color:TEXT}}><b>{selected[1]} ({selected[0]})</b><br/>Atomic number {selected[2]} · Group {selected[3]} · Period {selected[4]} · {selected[5]}</div></Shell>}
function Bonding({block}:{block:ContentBlock}){const[kind,setKind]=useState<'ionic'|'covalent'>('ionic');return <Shell title={block.content||'Explore chemical bonding'} purpose="Compare electron transfer in an ionic model with electron sharing in a covalent model."><div style={{display:'flex',gap:8}}><button style={{...button,flex:1,color:kind==='ionic'?ACCENT:TEXT}} onClick={()=>setKind('ionic')}>Ionic: NaCl</button><button style={{...button,flex:1,color:kind==='covalent'?ACCENT:TEXT}} onClick={()=>setKind('covalent')}>Covalent: H₂</button></div><div style={{marginTop:12,padding:14,background:INNER,borderRadius:10,color:TEXT,lineHeight:1.7}}>{kind==='ionic'?<>Na has one outer electron and Cl needs one to complete its outer shell. The model shows <b>transfer</b>: Na → Na⁺ + e⁻; Cl + e⁻ → Cl⁻. Electrostatic attraction holds the oppositely charged ions together.</>:<>Each H contributes one electron. The atoms <b>share a pair of electrons</b>, forming an H—H covalent bond. Sharing lets each hydrogen attain a stable first shell.</>}</div></Shell>}
function Trends({block}:{block:ContentBlock}){const[period,setPeriod]=useState(3);const data=period===2?['Li','Be','B','C','N','O','F','Ne']:['Na','Mg','Al','Si','P','S','Cl','Ar'];return <Shell title={block.content||'Investigate periodic trends'} purpose="Move across a period and identify patterns in group position and metallic character."><label style={{color:MUTED}}>Period <select value={period} onChange={e=>setPeriod(Number(e.target.value))} style={{marginLeft:8,...button}}><option value={2}>2</option><option value={3}>3</option></select></label><div style={{display:'flex',gap:6,overflowX:'auto',marginTop:12}}>{data.map((x,i)=><div key={x} style={{minWidth:52,padding:10,background:INNER,borderRadius:9,textAlign:'center',color:TEXT}}><b>{x}</b><small style={{display:'block',color:MUTED}}>G{i+1===8?18:i+1}</small></div>)}</div><p style={{color:TEXT,lineHeight:1.6}}>Across the period, elements change broadly from metallic to non-metallic character as outer-electron arrangement changes. Noble gases at the end have filled outer shells.</p></Shell>}
const substances=[['Lemon juice',2,'red'],['Vinegar',3,'orange'],['Water',7,'green'],['Baking-soda solution',8,'blue'],['Soap solution',10,'purple']] as const
function AcidBase({block}:{block:ContentBlock}){const[s,setS]=useState(substances[2]);return <Shell title={block.content||'pH and indicator investigation'} purpose="Test representative household substances virtually and relate pH to acidic, neutral and basic behaviour."><select aria-label="Virtual sample" value={s[0]} onChange={e=>setS(substances.find(x=>x[0]===e.target.value)??substances[2])} style={{...button,width:'100%'}}>{substances.map(x=><option key={x[0]}>{x[0]}</option>)}</select><div style={{marginTop:12,padding:14,background:INNER,borderRadius:10,color:TEXT}}>Representative pH: <b>{s[1]}</b> · universal-indicator colour: <b>{s[2]}</b> · classification: <b>{s[1]<7?'acidic':s[1]>7?'basic':'neutral'}</b></div><p style={{color:MUTED,fontSize:12}}>Values are representative for learning; real samples vary with concentration and composition. Do not taste laboratory chemicals.</p></Shell>}
const saltRoutes=[['Copper(II) sulfate','copper(II) oxide + dilute sulfuric acid','CuO + H₂SO₄ → CuSO₄ + H₂O'],['Zinc sulfate','zinc + dilute sulfuric acid','Zn + H₂SO₄ → ZnSO₄ + H₂'],['Sodium chloride','sodium hydroxide + hydrochloric acid','NaOH + HCl → NaCl + H₂O']] as const
function Salts({block}:{block:ContentBlock}){const[s,setS]=useState(saltRoutes[0]);return <Shell title={block.content||'Prepare a salt virtually'} purpose="Choose a target salt, predict suitable reactants, then inspect the balanced reaction and preparation idea."><select aria-label="Target salt" value={s[0]} onChange={e=>setS(saltRoutes.find(x=>x[0]===e.target.value)??saltRoutes[0])} style={{...button,width:'100%'}}>{saltRoutes.map(x=><option key={x[0]}>{x[0]}</option>)}</select><div style={{marginTop:12,padding:14,background:INNER,borderRadius:10,color:TEXT,lineHeight:1.8}}>Suitable reactants: <b>{s[1]}</b><br/>Balanced equation: <b>{s[2]}</b></div><p style={{color:MUTED,fontSize:12}}>Virtual investigation only. Actual school practicals require teacher supervision, approved concentrations, PPE and the school's laboratory safety procedure.</p></Shell>}
export function ChemistryInteractiveBlock({block}:{block:ContentBlock}){switch(block.meta?.interactiveType){case'chemistry_lab_safety':return <Safety block={block}/>;case'chemistry_atomic_structure':return <Atom block={block}/>;case'chemistry_periodic_table':return <Periodic block={block}/>;case'chemistry_bonding_properties_lab':return <Bonding block={block}/>;case'chemistry_periodicity_lab':return <Trends block={block}/>;case'chemistry_acid_base_lab':return <AcidBase block={block}/>;case'chemistry_salts_lab':return <Salts block={block}/>;default:return null}}
