"use client"
import React,{useState}from'react'
import type{ContentBlock}from'@/lib/publishTypes'
const T='#fff',M='rgba(255,255,255,.65)',A='#CCFF00',C='#111827',I='#0b1220',B='rgba(255,255,255,.1)'
export const CHEMISTRY_G10_LABS=['chemistry_lab_safety','chemistry_atomic_structure','chemistry_periodic_table','chemistry_bonding_properties_lab','chemistry_periodicity_lab','chemistry_acid_base_lab','chemistry_salts_lab']as const
export type ChemistryG10Lab=typeof CHEMISTRY_G10_LABS[number]
export const isChemistryG10Lab=(v:unknown):v is ChemistryG10Lab=>typeof v==='string'&&(CHEMISTRY_G10_LABS as readonly string[]).includes(v)
const btn:React.CSSProperties={minHeight:44,border:`1px solid ${B}`,borderRadius:10,background:I,color:T,padding:'10px 12px',fontWeight:800}
function S({title,purpose,children}:{title:string;purpose:string;children:React.ReactNode}){return <section style={{background:C,border:`1px solid ${B}`,borderRadius:16,padding:16}}><div style={{color:A,fontSize:10,fontWeight:900,letterSpacing:'.12em'}}>VIBELAB · GRADE 10 CHEMISTRY</div><h3 style={{color:T,fontSize:18,margin:'6px 0'}}>{title}</h3><p style={{color:M,fontSize:13,lineHeight:1.6}}>{purpose}</p>{children}</section>}
function Safety({b}:{b:ContentBlock}){const q=[['Heating a test tube','Point its open end away from people.','Correct. Heated containers must never point towards anyone.'],['Chemical splashes into an eye','Use the approved eyewash or running clean water and alert the teacher immediately.','Correct. Immediate rinsing and teacher assistance are essential.'],['Broken glass on the bench','Tell the teacher and use the approved glass-disposal procedure.','Correct. Never pick broken glass up with bare hands.']]as const;const[i,setI]=useState(0),[m,setM]=useState('');const good=q[i][1];return <S title={b.content||'Laboratory safety decisions'} purpose="Choose the safest response to common school-laboratory situations."><b style={{color:T}}>{q[i][0]}</b>{[good,'Continue working and deal with it later.','Handle the hazard with bare hands if you are careful.'].map(x=><button key={x} style={{...btn,width:'100%',marginTop:7,textAlign:'left'}} onClick={()=>setM(x===good?q[i][2]:'Not safe. Stop, protect people from the hazard and follow the teacher-approved laboratory procedure.')}>{x}</button>)}<p aria-live="polite" style={{color:m.startsWith('Correct')?A:T,minHeight:38}}>{m}</p><button style={{...btn,width:'100%'}} onClick={()=>{setI(v=>(v+1)%q.length);setM('')}}>Next situation</button></S>}
function Atom({b}:{b:ContentBlock}){const[p,setP]=useState(6),[n,setN]=useState(6),[e,setE]=useState(6),charge=p-e;const shell=e<=2?`${e}`:e<=10?`2, ${e-2}`:`2, 8, ${Math.min(8,e-10)}${e>18?`, ${e-18}`:''}`;return <S title={b.content||'Build an atom'} purpose="Change particle numbers and observe atomic number, mass number, charge and a simplified shell arrangement."><div style={{display:'grid',gridTemplateColumns:'repeat(3,minmax(0,1fr))',gap:8}}>{[['Protons',p,setP],['Neutrons',n,setN],['Electrons',e,setE]].map(([l,v,s])=><label key={String(l)} style={{color:M,fontSize:11}}>{String(l)}<input aria-label={String(l)} type="number" min={0} max={20} value={Number(v)} onChange={x=>(s as React.Dispatch<React.SetStateAction<number>>)(Math.max(0,Math.min(20,Number(x.target.value))))} style={{width:'100%',boxSizing:'border-box',marginTop:5,padding:10,borderRadius:9,background:I,color:T,border:`1px solid ${B}`}}/></label>)}</div><p style={{color:T,lineHeight:1.8}}>Atomic number <b>{p}</b> · Mass number <b>{p+n}</b> · Charge <b>{charge===0?'neutral':charge>0?`+${charge}`:charge}</b><br/>Simplified electron shells: <b>{shell||'0'}</b></p><small style={{color:M}}>This is a learning model: particle sizes, distances and shell drawings are not to scale.</small></S>}
const els=[['H','Hydrogen',1,1,1,'non-metal'],['He','Helium',2,18,1,'noble gas'],['Li','Lithium',3,1,2,'metal'],['C','Carbon',6,14,2,'non-metal'],['O','Oxygen',8,16,2,'non-metal'],['Na','Sodium',11,1,3,'metal'],['Mg','Magnesium',12,2,3,'metal'],['Cl','Chlorine',17,17,3,'non-metal'],['Ar','Argon',18,18,3,'noble gas'],['K','Potassium',19,1,4,'metal'],['Ca','Calcium',20,2,4,'metal']]as const
function Table({b}:{b:ContentBlock}){const[s,setS]=useState<(typeof els)[number]>(els[5]);return <S title={b.content||'Explore the periodic table'} purpose="Select an element and connect atomic number with its group and period."><div style={{display:'flex',flexWrap:'wrap',gap:7}}>{els.map(x=><button key={x[0]} style={{...btn,minWidth:52,color:s[0]===x[0]?A:T}} onClick={()=>setS(x)}>{x[0]}<small style={{display:'block'}}>{x[2]}</small></button>)}</div><div style={{marginTop:14,padding:12,background:I,borderRadius:10,color:T}}><b>{s[1]} ({s[0]})</b><br/>Atomic number {s[2]} · Group {s[3]} · Period {s[4]} · {s[5]}</div></S>}
function Bond({b}:{b:ContentBlock}){const[k,setK]=useState('ionic');return <S title={b.content||'Explore chemical bonding'} purpose="Compare electron transfer in an ionic model with electron sharing in a covalent model."><div style={{display:'flex',gap:8}}><button style={{...btn,flex:1,color:k==='ionic'?A:T}} onClick={()=>setK('ionic')}>Ionic: NaCl</button><button style={{...btn,flex:1,color:k==='covalent'?A:T}} onClick={()=>setK('covalent')}>Covalent: H₂</button></div><div style={{marginTop:12,padding:14,background:I,borderRadius:10,color:T,lineHeight:1.7}}>{k==='ionic'?<>Na transfers one outer electron to Cl, producing Na⁺ and Cl⁻. Electrostatic attraction between oppositely charged ions forms the ionic bond.</>:<>Two H atoms share a pair of electrons, forming an H—H covalent bond. Each H then has two electrons in its first shell.</>}</div></S>}
const groups=[1,2,13,14,15,16,17,18]
function Trends({b}:{b:ContentBlock}){const[p,setP]=useState(3),names=p===2?['Li','Be','B','C','N','O','F','Ne']:['Na','Mg','Al','Si','P','S','Cl','Ar'];return <S title={b.content||'Investigate periodic trends'} purpose="Move across Period 2 or 3 and inspect the change in group position and broad metallic character."><label style={{color:M}}>Period <select value={p} onChange={e=>setP(Number(e.target.value))} style={{marginLeft:8,...btn}}><option value={2}>2</option><option value={3}>3</option></select></label><div style={{display:'flex',gap:6,overflowX:'auto',marginTop:12}}>{names.map((x,i)=><div key={x} style={{minWidth:52,padding:10,background:I,borderRadius:9,textAlign:'center',color:T}}><b>{x}</b><small style={{display:'block',color:M}}>G{groups[i]}</small></div>)}</div><p style={{color:T,lineHeight:1.6}}>Across each period, elements change broadly from metallic towards non-metallic character as outer-electron arrangement changes; the noble gas ends the period with a filled outer shell.</p></S>}
const subs=[['Lemon juice',2,'red'],['Vinegar',3,'orange'],['Water',7,'green'],['Baking-soda solution',8,'blue-green'],['Soap solution',10,'blue-purple']]as const
function Acid({b}:{b:ContentBlock}){const[s,setS]=useState<(typeof subs)[number]>(subs[2]);return <S title={b.content||'pH and indicator investigation'} purpose="Test representative substances virtually and relate pH to acidic, neutral and basic behaviour."><select aria-label="Virtual sample" value={s[0]} onChange={e=>setS(subs.find(x=>x[0]===e.target.value)??subs[2])} style={{...btn,width:'100%'}}>{subs.map(x=><option key={x[0]}>{x[0]}</option>)}</select><div style={{marginTop:12,padding:14,background:I,borderRadius:10,color:T}}>Representative pH <b>{s[1]}</b> · universal-indicator colour <b>{s[2]}</b> · <b>{s[1]<7?'acidic':s[1]>7?'basic':'neutral'}</b></div><p style={{color:M,fontSize:12}}>Representative learning values vary in real samples with concentration and composition. Never taste laboratory chemicals.</p></S>}
const routes=[['Copper(II) sulfate','copper(II) oxide + dilute sulfuric acid','CuO + H₂SO₄ → CuSO₄ + H₂O'],['Zinc sulfate','zinc + dilute sulfuric acid','Zn + H₂SO₄ → ZnSO₄ + H₂'],['Sodium chloride','sodium hydroxide + hydrochloric acid','NaOH + HCl → NaCl + H₂O']]as const
function Salts({b}:{b:ContentBlock}){const[s,setS]=useState<(typeof routes)[number]>(routes[0]);return <S title={b.content||'Prepare a salt virtually'} purpose="Choose a target salt and inspect a suitable reaction and balanced equation."><select aria-label="Target salt" value={s[0]} onChange={e=>setS(routes.find(x=>x[0]===e.target.value)??routes[0])} style={{...btn,width:'100%'}}>{routes.map(x=><option key={x[0]}>{x[0]}</option>)}</select><div style={{marginTop:12,padding:14,background:I,borderRadius:10,color:T,lineHeight:1.8}}>Suitable reactants: <b>{s[1]}</b><br/>Balanced equation: <b>{s[2]}</b></div><p style={{color:M,fontSize:12}}>Virtual investigation only. Real practicals require teacher supervision, approved concentrations, PPE and school laboratory procedures.</p></S>}
export function ChemistryInteractiveBlock({block:b}:{block:ContentBlock}){switch(b.meta?.interactiveType){case'chemistry_lab_safety':return <Safety b={b}/>;case'chemistry_atomic_structure':return <Atom b={b}/>;case'chemistry_periodic_table':return <Table b={b}/>;case'chemistry_bonding_properties_lab':return <Bond b={b}/>;case'chemistry_periodicity_lab':return <Trends b={b}/>;case'chemistry_acid_base_lab':return <Acid b={b}/>;case'chemistry_salts_lab':return <Salts b={b}/>;default:return null}}
