"use client"
import React from 'react'
import type { ContentBlock } from '@/lib/publishTypes'
import { InteractiveLab, type InteractiveLabConfig } from './InteractiveLab'
import { ChemistryInteractiveBlock, isChemistryG10Lab } from './ChemistryInteractiveBlock'

const TEXT='#fff',MUTED='rgba(255,255,255,.58)',CARD='#111827',BORDER='rgba(255,255,255,.09)'
export const CROSS_SUBJECT_LAB_TYPES=['chemistry_titration_lab','chemistry_rate_lab','chemistry_solubility_lab','chemistry_lab_safety','chemistry_atomic_structure','chemistry_periodic_table','chemistry_bonding_properties_lab','chemistry_periodicity_lab','chemistry_acid_base_lab','chemistry_salts_lab','physics_motion_lab','physics_electricity_lab','physics_moments_lab','mathematics_statistics_lab','mathematics_probability_lab','agriculture_germination_lab','agriculture_soil_lab'] as const
export type CrossSubjectLabType=typeof CROSS_SUBJECT_LAB_TYPES[number]
const presets:Record<string,InteractiveLabConfig>={
 chemistry_titration_lab:{title:'Titration data lab',question:'How consistent are repeated titre values?',instructions:'Record concordant titre values in cm³ as comma-separated measurements, then interpret precision and consistency.',sampleValues:'24.80,24.70,24.75,24.70',unit:'cm³',binSize:1,conclusionHint:'Close repeated titres strengthen confidence in precision; precision is not the same as accuracy.'},
 chemistry_rate_lab:{title:'Rate of reaction lab',question:'How does changing a condition affect reaction time?',instructions:'Enter repeated reaction times in seconds for comparable trials. Smaller time indicates a faster reaction when the endpoint is unchanged.',sampleValues:'82,78,80,46,44,48,25,27,24',unit:'s',binSize:10,conclusionHint:'State the changed variable and controlled variables when drawing a conclusion.'},
 chemistry_solubility_lab:{title:'Solubility investigation',question:'How does temperature affect the mass of solute that dissolves?',instructions:'Enter comparable solubility measurements and use the pattern to discuss change under the tested conditions.',sampleValues:'32,36,41,47,54,62,71',unit:'g per 100 g water',binSize:10,conclusionHint:'Describe only the observed range; do not extrapolate without evidence.'},
 physics_motion_lab:{title:'Motion and speed lab',question:'What do repeated times reveal about motion over a fixed distance?',instructions:'Enter repeated times in seconds, compare their spread and use distance ÷ time to reason about speed.',sampleValues:'2.4,2.3,2.5,2.4,2.2',unit:'s',binSize:1},
 physics_electricity_lab:{title:'Electrical measurements lab',question:'How consistent are repeated electrical readings?',instructions:'Enter repeated readings for one controlled circuit condition and discuss reliability.',sampleValues:'0.42,0.41,0.43,0.42,0.42',unit:'A',binSize:1},
 physics_moments_lab:{title:'Moments and balance lab',question:'How do repeated measurements support the principle of moments?',instructions:'Enter comparable moment values and inspect agreement within practical uncertainty.',sampleValues:'1.98,2.02,2.01,1.99,2.00',unit:'N m',binSize:1},
 mathematics_statistics_lab:{title:'Statistics data lab',question:'What can a dataset tell us about centre and spread?',instructions:'Enter numerical values and compare mean, range and the frequency distribution.',sampleValues:'12,14,15,15,16,17,18,18,19,21,24,25',unit:'value',binSize:5},
 mathematics_probability_lab:{title:'Experimental probability lab',question:'How does repeated experimentation help estimate probability?',instructions:'Enter frequencies from repeated equal-sized trials and compare variation.',sampleValues:'48,52,50,47,53,51,49,50',unit:'successes per 100 trials',binSize:5},
 agriculture_germination_lab:{title:'Seed germination investigation',question:'How does an environmental condition affect germination?',instructions:'Enter germination percentages from comparable repeated containers.',sampleValues:'88,92,90,86,91,89',unit:'% germinated',binSize:5},
 agriculture_soil_lab:{title:'Soil investigation lab',question:'What do repeated measurements reveal about a soil sample?',instructions:'Enter comparable soil measurements such as pH and interpret only that measured property.',sampleValues:'6.2,6.4,6.3,6.5,6.3',unit:'pH',binSize:1}
}
export function isCrossSubjectLabType(v:unknown):v is CrossSubjectLabType{return typeof v==='string'&&(CROSS_SUBJECT_LAB_TYPES as readonly string[]).includes(v)}
export function CrossSubjectInteractiveBlock({block}:{block:ContentBlock}){const kind=block.meta?.interactiveType;if(isChemistryG10Lab(kind))return <ChemistryInteractiveBlock block={block}/>;if(typeof kind==='string'&&presets[kind])return <InteractiveLab config={{...presets[kind],title:block.content||presets[kind].title}}/>;return <section style={{background:CARD,border:`1px solid ${BORDER}`,borderRadius:16,padding:16}}><div style={{color:TEXT,fontSize:15,fontWeight:850}}>{block.content||'Interactive learning block'}</div><p style={{color:MUTED,fontSize:13,marginBottom:0}}>This interaction type is not available yet.</p></section>}
