"use client"

import React, { useState } from 'react'
import { createBrowserClient } from '@supabase/ssr'

const SURF='#111827', CARD='#1a2235', TEXT='#fff', MUTED='rgba(255,255,255,.48)', ACCENT='#CCFF00', BORDER='rgba(255,255,255,.08)'

export function CurriculumImportDrawer({authorId,initialGrade,initialSubject,isOpen,onClose}:{authorId:string;initialGrade?:string|null;initialSubject?:string|null;isOpen:boolean;onClose:()=>void}) {
 const [authorityName,setAuthorityName]=useState('Kenya Institute of Curriculum Development'); const [sourceUrl,setSourceUrl]=useState(''); const [sourceRef,setSourceRef]=useState(''); const [curriculumName,setCurriculumName]=useState('Kenya Curriculum'); const [grade,setGrade]=useState(initialGrade??''); const [subject,setSubject]=useState(initialSubject??''); const [versionLabel,setVersionLabel]=useState(''); const [notes,setNotes]=useState(''); const [saving,setSaving]=useState(false); const [message,setMessage]=useState('')
 if(!isOpen)return null
 const input:React.CSSProperties={width:'100%',background:CARD,border:`1px solid ${BORDER}`,borderRadius:10,padding:'11px 12px',color:TEXT,outline:'none',boxSizing:'border-box',fontFamily:'inherit',fontSize:13}
 async function saveImport(){ if(saving)return; if(!authorityName.trim()||!curriculumName.trim()||!grade.trim()||!subject.trim()){setMessage('Authority, curriculum, grade/form and subject are required.');return} if(sourceUrl.trim()){try{const parsed=new URL(sourceUrl.trim());if(!['https:','http:'].includes(parsed.protocol))throw new Error('invalid')}catch{setMessage('Source URL must be a valid http/https address.');return}} setSaving(true);setMessage('');try{const sb=createBrowserClient(process.env.NEXT_PUBLIC_SUPABASE_URL!,process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!);const{error}=await sb.from('curriculum_imports').insert({created_by:authorId,source_type:'official',authority_name:authorityName.trim(),source_url:sourceUrl.trim()||null,source_ref:sourceRef.trim()||null,curriculum_name:curriculumName.trim(),grade:grade.trim(),subject:subject.trim(),version_label:versionLabel.trim()||null,status:'draft',payload:{notes:notes.trim()||null}});if(error)throw error;setMessage('Source registered as a draft import. It is not marked verified until reviewed against the authoritative curriculum.')}catch(error){setMessage(error instanceof Error?error.message:'Could not register curriculum source.')}finally{setSaving(false)}}
 const fields:Array<[string,string,React.Dispatch<React.SetStateAction<string>>,string]>=[['Authority',authorityName,setAuthorityName,'Kenya Institute of Curriculum Development'],['Curriculum',curriculumName,setCurriculumName,'Kenya Curriculum'],['Grade / Form',grade,setGrade,'Form 4'],['Subject',subject,setSubject,'Biology'],['Version / edition',versionLabel,setVersionLabel,'e.g. 2026 edition'],['Source reference',sourceRef,setSourceRef,'Document title / reference'],['Official source URL',sourceUrl,setSourceUrl,'https://kicd.ac.ke/...']]
 return <><button type="button" aria-label="Close curriculum import" onClick={onClose} style={{position:'fixed',inset:0,background:'rgba(0,0,0,.68)',border:0,zIndex:320}}/><aside style={{position:'fixed',inset:'0 0 0 auto',width:'min(94vw,460px)',background:SURF,borderLeft:`1px solid ${BORDER}`,zIndex:330,padding:'20px 16px 32px',overflowY:'auto',boxSizing:'border-box'}}><div style={{display:'flex',justifyContent:'space-between',alignItems:'center',gap:12,marginBottom:18}}><div><div style={{color:ACCENT,fontSize:9,fontWeight:850,letterSpacing:'.12em'}}>CURRICULUM SOURCE</div><h2 style={{color:TEXT,fontSize:20,margin:'5px 0 0'}}>Register authoritative design</h2></div><button type="button" onClick={onClose} style={{width:36,height:36,borderRadius:10,border:`1px solid ${BORDER}`,background:CARD,color:TEXT,cursor:'pointer',fontSize:18}}>×</button></div><div style={{border:'1px solid rgba(204,255,0,.22)',background:'rgba(204,255,0,.05)',borderRadius:12,padding:12,color:MUTED,fontSize:12,lineHeight:1.55,marginBottom:16}}>Register the Ministry/KICD source first. This step does not invent outcomes and does not mark the book curriculum-verified automatically.</div>{fields.map(([label,value,setter,placeholder])=><label key={label} style={{display:'block',marginBottom:12}}><span style={{display:'block',color:MUTED,fontSize:10,fontWeight:800,letterSpacing:'.08em',marginBottom:6}}>{label}</span><input value={value} onChange={e=>setter(e.target.value)} placeholder={placeholder} style={input}/></label>)}<label style={{display:'block',marginBottom:14}}><span style={{display:'block',color:MUTED,fontSize:10,fontWeight:800,letterSpacing:'.08em',marginBottom:6}}>IMPORT NOTES</span><textarea value={notes} onChange={e=>setNotes(e.target.value)} rows={5} placeholder="What was received, pages/sections covered, or review notes…" style={{...input,resize:'vertical',lineHeight:1.55}}/></label>{message&&<div style={{color:message.startsWith('Source registered')?ACCENT:'#ff7b7b',fontSize:12,lineHeight:1.5,marginBottom:12}}>{message}</div>}<button type="button" onClick={saveImport} disabled={saving} style={{width:'100%',border:0,borderRadius:12,padding:13,background:ACCENT,color:'#090D16',fontWeight:850,cursor:saving?'not-allowed':'pointer',opacity:saving?.6:1}}>{saving?'Registering…':'Register source as draft'}</button></aside></>
}
