import type { Metadata } from 'next'
import Link from 'next/link'
import { PublicHeader } from '@/components/public/PublicHeader'
import { PublicFooter } from '@/components/public/PublicFooter'

export const metadata: Metadata = { title:'Security & Data Governance | VibeSchool', description:'How VibeSchool approaches identity, access, data boundaries, auditability and responsible governance.' }

const controls=[
['Identity before authority','Authentication proves who a person is. It should not by itself grant a teacher, parent, school or administrative role.'],
['Role and relationship boundaries','Access to learner and school information should follow verified relationships, assignments and institutional authority.'],
['Least-necessary access','People and systems should receive only the information and capabilities required for the task they are authorised to perform.'],
['Server and database enforcement','Sensitive authority should be enforced beyond the browser. A client-side button, URL or role selector is not an access-control system.'],
['Evidence and auditability','Consequential changes should preserve enough evidence to understand who or what acted, under which authority and what outcome followed.'],
['Fail closed for uncertainty','When identity, authority or required evidence cannot be established, the safer default is to withhold the sensitive action rather than guess.'],
]

export default function SecurityPage(){return <div className="page"><PublicHeader product="Security"/><main id="main-content"><section className="hero"><div className="wrap"><p className="eyebrow">SECURITY & DATA GOVERNANCE</p><h1>Security is about who may do what — not just whether a password exists.</h1><p className="lead">VibeSchool’s trust model separates identity, authority, data purpose and evidence. The goal is to make private educational information useful to the right people without making it broadly accessible.</p></div></section><section className="section wrap"><p className="eyebrow dark">CORE PRINCIPLES</p><div className="grid">{controls.map(([t,d])=><article key={t}><h2>{t}</h2><p>{d}</p></article>)}</div></section><section className="section alt"><div className="wrap two"><div><p className="eyebrow dark">PUBLIC VS PRIVATE</p><h2 className="big">A useful public website should not expose private educational operations.</h2></div><div><p>Public pages can explain VibeSchool, show public catalogue information and provide safe discovery experiences. Learner records, private school operations, family relationships and authenticated support remain behind appropriate identity and authority boundaries.</p><p>When public information is evidence-backed, VibeSchool should preserve provenance so users can distinguish a verified claim from guidance or an incomplete record.</p></div></div></section><section className="section wrap"><div className="two"><div><p className="eyebrow dark">DATA GOVERNANCE</p><h2 className="big">Data should have a purpose, owner and lifecycle.</h2></div><div><p>Good governance requires understanding why information is collected, who can access it, how long it is needed, what source supports it where relevant and how corrections or deletion requests are handled.</p><p>VibeSchool’s formal privacy commitments are described in the Privacy Policy. Institutional deployments may require additional agreements and controls appropriate to the participating organisation.</p><Link className="text" href="/legal/privacy">Read the Privacy Policy →</Link></div></div></section><section className="report"><div className="wrap"><h2>Found a security or privacy concern?</h2><p>Do not post credentials or sensitive learner information publicly. Contact VibeSchool with the minimum information needed to reproduce or understand the concern.</p><div className="links"><Link href="/contact">Contact VibeSchool</Link><Link href="/trust">Trust Centre</Link><Link href="/institutions">Institutional due diligence</Link></div></div></section></main><PublicFooter/><style>{styles}</style></div>}
const styles=`.page{background:#f8f8f5;color:#111827;font-family:var(--font-jakarta),Arial,sans-serif;line-height:1.7}.page *{box-sizing:border-box}.wrap{max-width:1080px;margin:auto}.hero{background:#07111f;color:#fff;padding:88px 24px}.eyebrow{font:850 11px var(--font-mono),monospace;letter-spacing:.15em;color:#d0b154}.eyebrow.dark{color:#755b17}h1,.big{font-family:var(--font-display),Arial,sans-serif;letter-spacing:-.04em;line-height:1.06}h1{font-size:clamp(41px,6vw,69px);max-width:900px;margin:14px 0 24px}.lead{font-size:18px;color:#c6cfda;max-width:780px}.section{padding:82px 24px}.grid{display:grid;grid-template-columns:repeat(2,1fr);gap:14px}.grid article{background:#fff;border:1px solid #e0e3e7;border-radius:14px;padding:27px}.grid h2{font-size:21px;margin:0 0 8px}.grid p,.two p{color:#5c6673}.alt{background:#eeeae0}.two{display:grid;grid-template-columns:1fr 1fr;gap:64px}.big{font-size:clamp(31px,4vw,47px);margin:10px 0}.text{font-weight:850;color:#6f5615;text-decoration:none}.report{background:#13243a;color:#fff;padding:62px 24px}.report h2{font-size:30px;margin:0}.report p{color:#c6cfda;max-width:780px}.links{display:flex;gap:18px;flex-wrap:wrap}.links a{color:#e4c96f;font-weight:800;text-decoration:none}@media(max-width:700px){.hero,.section{padding:60px 18px}.grid,.two{grid-template-columns:1fr}.two{gap:18px}}`