import type { Metadata } from 'next'
import Link from 'next/link'
import { PublicHeader } from '@/components/public/PublicHeader'
import { PublicFooter } from '@/components/public/PublicFooter'
import { knowledgeVerifiedOn, listKnowledgeArticles, listKnowledgeSources } from '@/lib/educationKnowledge'

export const metadata: Metadata = {
  alternates: { canonical: '/kenya-education' },
  title: 'Kenya Education Guide | CBE, Grade 10 & Senior School | VibeSchool',
  description: 'Source-backed explanations of Kenya CBE, Grade 10, Senior School pathways, subject combinations and school choices from VibeSchool.',
}

export default function KenyaEducationPage(){
  const articles=listKnowledgeArticles()
  const sources=listKnowledgeSources()
  return <div className="page"><PublicHeader product="Kenya Education"/><main id="main-content">
    <section className="hero"><div className="wrap"><p className="eyebrow">VIBESCHOOL · KENYA EDUCATION KNOWLEDGE</p><h1>Understand the system before making the decision.</h1><p className="lead">Clear explanations of Kenyan education should distinguish official facts, practical guidance and uncertainty. Every factual section in this knowledge base points back to a current source authority.</p></div></section>
    <section className="section wrap"><div className="intro"><div><p className="eyebrow dark">START HERE</p><h2>Grade 10 and Senior School</h2></div><p>These first guides focus on a high-consequence transition where learners and families need to connect pathways, subject combinations, schools, curriculum and assessment without treating guidance as official placement information.</p></div><div className="cards">{articles.map(article=><Link href={`/kenya-education/${article.slug}`} key={article.slug}><span>{article.audience.join(' · ')}</span><h3>{article.title}</h3><p>{article.description}</p><strong>Read guide →</strong></Link>)}</div></section>
    <section className="section alt"><div className="wrap"><p className="eyebrow dark">EVIDENCE STANDARD</p><h2>Fact, guidance and boundary are different content types.</h2><div className="types"><article><strong>FACT</strong><p>A statement attributed to an official or authoritative source and linked to its evidence.</p></article><article><strong>GUIDANCE</strong><p>A practical recommendation that helps a learner, family, teacher or school act on the facts without pretending the recommendation is an official rule.</p></article><article><strong>BOUNDARY</strong><p>A warning about concepts that are easy to confuse — for example selection versus placement, curriculum versus textbook approval, or guidance versus verified school offering.</p></article></div></div></section>
    <section className="section wrap"><p className="eyebrow dark">SOURCE REGISTER</p><h2>Current authorities used by this knowledge release.</h2><div className="sources">{sources.map(source=><a href={source.url} target="_blank" rel="noopener noreferrer" key={source.id}><strong>{source.authority}</strong><span>{source.title}</span><small>Verified {source.verified_on} · {source.source_type}</small></a>)}</div><p className="review">Knowledge release verified {knowledgeVerifiedOn()}. If an official source changes, the affected explanation should be reviewed before VibeSchool treats it as current.</p></section>
  </main><PublicFooter/><style>{styles}</style></div>
}

const styles=`.page{background:#f8f8f5;color:#101827;font-family:var(--font-jakarta),Arial,sans-serif;line-height:1.7}.page *{box-sizing:border-box}.wrap{max-width:1120px;margin:auto}.hero{background:#07111f;color:#fff;padding:94px 24px}.eyebrow{font:850 11px var(--font-mono),monospace;letter-spacing:.15em;color:#d0b154}.eyebrow.dark{color:#755b17}h1,h2{font-family:var(--font-display),Arial,sans-serif;letter-spacing:-.04em;line-height:1.05}h1{font-size:clamp(44px,6vw,72px);max-width:900px;margin:14px 0 23px}h2{font-size:clamp(31px,4.4vw,50px);margin:10px 0 24px}.lead{font-size:18px;color:#c6cfda;max-width:790px}.section{padding:82px 24px}.alt{background:#eeeae0}.intro{display:grid;grid-template-columns:1fr 1fr;gap:60px;align-items:end}.intro>p{color:#5e6773}.cards{display:grid;grid-template-columns:repeat(2,1fr);gap:13px;margin-top:32px}.cards a{background:#fff;border:1px solid #dfe2e7;border-radius:16px;padding:25px;text-decoration:none;color:#121a27}.cards span{font:750 11px var(--font-mono);text-transform:uppercase;color:#755b17}.cards h3{font-size:22px;line-height:1.25}.cards p{color:#606976}.cards strong{color:#6f5615}.types{display:grid;grid-template-columns:repeat(3,1fr);gap:12px}.types article{background:#fff;border:1px solid #dedbd2;border-radius:14px;padding:22px}.types strong{font:850 12px var(--font-mono);letter-spacing:.08em}.types p{color:#5e6773}.sources{display:grid;grid-template-columns:repeat(2,1fr);gap:10px}.sources a{display:grid;gap:4px;padding:20px;background:#fff;border:1px solid #dfe2e7;border-radius:13px;text-decoration:none;color:#151b25}.sources span{color:#555e69}.sources small,.review{color:#747b85}.review{font-size:13px;margin-top:18px}@media(max-width:760px){.hero,.section{padding:62px 18px}.intro,.cards,.types,.sources{grid-template-columns:1fr}.intro{gap:8px}}`
