"use client"
export const dynamic = "force-dynamic"

import {useCallback,useEffect,useMemo,useState} from "react"
import {supabase} from "@/lib/supabase"
import {HQPage,HQPanel,HQ_THEME as C,hqButtonStyle} from "@/components/hq/HQShell"
import {isHQOnline,readHQCache,readHQDraft,saveHQCache,saveHQDraft} from "@/lib/hq/offline"

type WorkforceDecision={id:string;decision_key:string;worker_key:string|null;lane_key:string;job_key:string;proposed_action:string;reason:string;risk:string;status:string;revision:string|null;run_id:string|null;evidence_snapshot_id:string|null;created_at:string}
type Action="approve"|"revise"|"reject"|"skip"
type Group="Needs Me Now"|"Waiting"|"Recently Resolved"
const sb=supabase as any
const riskTone=(risk:string)=>risk==="critical"?C.red:risk==="high"?C.amber:risk==="normal"?C.blue:C.muted
const actionable=(x:WorkforceDecision)=>x.status==="pending"||x.status==="revision_requested"
const groupOf=(x:WorkforceDecision):Group=>x.status==="revision_requested"?"Waiting":x.status==="pending"?"Needs Me Now":"Recently Resolved"

function DecisionCard({item,working,note,onNote,onAction}:{item:WorkforceDecision;working:boolean;note:string;onNote:(v:string)=>void;onAction:(a:Action)=>void}){
 const canAct=actionable(item)
 return <HQPanel><div style={{padding:14,borderBottom:`1px solid ${C.border}`}}><div style={{display:"flex",gap:7,alignItems:"center",flexWrap:"wrap"}}><strong style={{fontSize:13}}>{item.proposed_action}</strong><span className="hq-status" style={{color:riskTone(item.risk),borderColor:`${riskTone(item.risk)}55`}}>{item.risk.toUpperCase()}</span><span className="hq-status" style={{color:item.status==="approved"?C.green:item.status==="rejected"?C.red:item.status==="revision_requested"?C.violet:C.muted}}>{item.status.replaceAll("_"," ")}</span></div><div style={{fontSize:10.5,color:C.muted,marginTop:5}}>{item.lane_key} · {item.worker_key??"Unassigned worker"} · {new Date(item.created_at).toLocaleString("en-KE")}</div></div><div style={{padding:14,display:"grid",gap:10}}><section><div style={{fontSize:10,fontWeight:900,color:C.muted,textTransform:"uppercase"}}>Observation / reason</div><div style={{fontSize:11.5,lineHeight:1.6,marginTop:4}}>{item.reason}</div></section><section style={{padding:10,border:`1px solid ${C.border}`,borderRadius:10,background:"rgba(255,255,255,.02)"}}><div style={{fontSize:10,fontWeight:900,color:C.muted,textTransform:"uppercase"}}>Recommendation</div><div style={{fontSize:11.5,lineHeight:1.55,marginTop:4}}>{item.proposed_action}</div><div style={{fontSize:10.5,color:C.muted,marginTop:5}}>This is a proposal, not an executed fact.</div></section><details style={{fontSize:10.5,color:C.muted}}><summary style={{cursor:"pointer"}}>Evidence & authority references</summary><div style={{marginTop:7,overflowWrap:"anywhere"}}>Job {item.job_key}<br/>Run {item.run_id??"Unavailable"}<br/>Evidence snapshot {item.evidence_snapshot_id??"Unavailable"}<br/>Authority action: founder decision state only; downstream execution remains separately gated.</div></details>{item.revision&&<div style={{padding:10,borderRadius:10,background:"rgba(167,139,250,.08)",fontSize:11}}><strong>Founder correction:</strong> {item.revision}</div>}{canAct&&<><textarea aria-label={`Founder note for ${item.proposed_action}`} value={note} onChange={e=>onNote(e.target.value)} placeholder="Revision or rejection reason · saved locally" rows={3} style={{width:"100%",boxSizing:"border-box",resize:"vertical",border:`1px solid ${C.border}`,borderRadius:10,background:"rgba(255,255,255,.035)",color:C.text,padding:10,font:"inherit",fontSize:11.5}}/><div className="hq-action-row"><button disabled={working} onClick={()=>onAction("approve")} style={{...hqButtonStyle,color:C.green}}>Approve judgment</button><button disabled={working} onClick={()=>onAction("revise")} style={{...hqButtonStyle,color:C.violet}}>Request revision</button><button disabled={working} onClick={()=>onAction("reject")} style={{...hqButtonStyle,color:C.red}}>Reject</button><button disabled={working} onClick={()=>onAction("skip")} style={{...hqButtonStyle,color:C.muted}}>Skip</button></div></>}</div></HQPanel>
}

export default function HQWorkforceDecisionsPage(){
 const[items,setItems]=useState<WorkforceDecision[]>([]);const[notes,setNotes]=useState<Record<string,string>>({});const[busy,setBusy]=useState("");const[loading,setLoading]=useState(true);const[error,setError]=useState("");const[message,setMessage]=useState("");const[pending,setPending]=useState<{item:WorkforceDecision;action:Action}|null>(null);const[cachedAt,setCachedAt]=useState<number|null>(null)
 const restore=useCallback(()=>{const cached=readHQCache<WorkforceDecision[]>('decisions');if(!cached)return false;setItems(cached.value);setCachedAt(cached.savedAt);setLoading(false);return true},[])
 const load=useCallback(async()=>{setError("");try{const{data,error}=await sb.rpc("hq_workforce_list_decisions",{p_status:null,p_limit:200});if(error)throw error;const next=(data??[]) as WorkforceDecision[];setItems(next);setCachedAt(null);saveHQCache('decisions',next)}catch(e){const restored=restore();setError(restored?"Live decision state is unavailable. Showing the last-known inbox.":e instanceof Error?e.message:"Decision inbox could not be loaded.")}finally{setLoading(false)}},[restore])
 useEffect(()=>{const draft=readHQDraft<Record<string,string>>('decision-notes');if(draft)setNotes(draft.value);if(!isHQOnline())restore();void load()},[load,restore]);useEffect(()=>{saveHQDraft('decision-notes',notes)},[notes])
 const groups=useMemo(()=>({"Needs Me Now":items.filter(x=>groupOf(x)==="Needs Me Now"),Waiting:items.filter(x=>groupOf(x)==="Waiting"),"Recently Resolved":items.filter(x=>groupOf(x)==="Recently Resolved").slice(0,30)}),[items])
 const counts=useMemo(()=>({needs:groups["Needs Me Now"].length,waiting:groups.Waiting.length,resolved:groups["Recently Resolved"].length,critical:items.filter(x=>actionable(x)&&x.risk==="critical").length,high:items.filter(x=>actionable(x)&&x.risk==="high").length}),[groups,items])
 function requestDecision(item:WorkforceDecision,action:Action){const note=(notes[item.id]??"").trim();if((action==="revise"||action==="reject")&&!note){setError(`${action==="revise"?"Revision":"Rejection reason"} is required.`);return}if(!isHQOnline()){setError("Founder notes are saved locally, but decisions require a live connection.");return}setError("");setPending({item,action})}
 async function confirmDecision(){if(!pending)return;if(!isHQOnline()){setError("Reconnect before authorizing a workforce decision.");setPending(null);return}const{item,action}=pending;const note=(notes[item.id]??"").trim();setBusy(item.id);setError("");setMessage("");try{const{data,error}=await sb.rpc("hq_workforce_decide",{p_id:item.id,p_action:action,p_revision:note||null});if(error)throw error;const result=data as Record<string,unknown>|null;setMessage(`${item.decision_key}: ${String(result?.status??action)}`);setNotes(prev=>{const n={...prev};delete n[item.id];return n});setPending(null);await load()}catch(e){setError(e instanceof Error?e.message:"Decision action failed.")}finally{setBusy("")}}
 return <><HQPage title="Decision Inbox" description="Observation → evidence → recommendation → founder judgment → separately gated execution" actions={<button onClick={()=>void load()} disabled={loading} style={hqButtonStyle}>{loading?"Loading…":"Refresh"}</button>}>
  {cachedAt&&<div style={{marginBottom:10,fontSize:10.5,color:C.amber}}>Last-known inbox from {new Date(cachedAt).toLocaleString("en-KE")} · do not authorize from stale evidence.</div>}
  <section style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(120px,1fr))",gap:9}}>{[["Needs me now",counts.needs,C.amber],["Waiting",counts.waiting,C.violet],["Recently resolved",counts.resolved,C.green],["Critical",counts.critical,C.red],["High",counts.high,C.amber]].map(([caption,value,tone])=><div key={String(caption)} style={{padding:13,border:`1px solid ${C.border}`,borderRadius:14,background:C.panelSoft}}><div style={{fontSize:23,fontWeight:950,color:String(tone)}}>{String(value)}</div><div style={{fontSize:10.5,color:C.muted,marginTop:4}}>{String(caption)}</div></div>)}</section>
  {error&&<div role="alert" style={{marginTop:12,padding:12,border:"1px solid rgba(251,113,133,.3)",borderRadius:11,background:"rgba(251,113,133,.08)",color:"#fecdd3",fontSize:12}}>{error}</div>}{message&&<div role="status" style={{marginTop:12,padding:12,border:"1px solid rgba(52,211,153,.3)",borderRadius:11,background:"rgba(52,211,153,.08)",color:"#bbf7d0",fontSize:12}}>{message}</div>}
  {(["Needs Me Now","Waiting","Recently Resolved"] as Group[]).map(group=><section key={group} style={{marginTop:16}}><h2 style={{fontSize:13,margin:"0 0 9px"}}>{group}</h2><div style={{display:"grid",gap:10}}>{groups[group].length?groups[group].map(item=><DecisionCard key={item.id} item={item} working={busy===item.id} note={notes[item.id]??""} onNote={v=>setNotes(p=>({...p,[item.id]:v}))} onAction={a=>requestDecision(item,a)}/>):<HQPanel><div style={{padding:22,color:C.muted,fontSize:11.5}}>No decisions in this state.</div></HQPanel>}</div></section>)}
 </HQPage>{pending&&<div role="dialog" aria-modal="true" aria-labelledby="decision-confirm-title" style={{position:"fixed",inset:0,zIndex:200,display:"grid",placeItems:"center",padding:18,background:"rgba(2,6,23,.78)"}}><div style={{width:"min(100%,500px)",border:`1px solid ${C.border}`,borderRadius:16,background:C.panel,padding:18,color:C.text}}><h2 id="decision-confirm-title" style={{margin:"0 0 7px",fontSize:17,textTransform:"capitalize"}}>{pending.action} founder judgment?</h2><p style={{margin:"0 0 8px",fontSize:12,lineHeight:1.55}}>{pending.item.proposed_action}</p><p style={{margin:0,fontSize:11,color:C.muted,lineHeight:1.5}}>{pending.action==="approve"?"This records founder approval of the decision. It does not activate Worker Engine runtime or bypass downstream authority, precondition and verification gates.":pending.action==="skip"?"This closes the proposal without treating it as executed.":"Your correction will be captured as decision-learning evidence."}</p><div className="hq-action-row" style={{justifyContent:"flex-end",marginTop:14}}><button onClick={()=>setPending(null)} style={hqButtonStyle}>Cancel</button><button onClick={()=>void confirmDecision()} style={{...hqButtonStyle,color:pending.action==="reject"?C.red:pending.action==="approve"?C.green:C.amber}}>Confirm</button></div></div></div>}</>
}
