"use client"

import { useEffect, useMemo, useState } from "react"
import { useRouter } from "next/navigation"
import { approveHQDecision, cancelHQDecision, createHQAmendment, createHQDecision, emergencySetHQPolicy, getHQDecisionDetail, listHQDecisions, listHQPolicies, lockHQDecision, markHQDecisionReviewed, observeTwinRuntime, rollbackHQDecision, updateHQDraftDecision, verifyHQDecision, type HQDecision, type HQDecisionDetail, type HQPolicy } from "@/lib/hq/operating"

const products=["student","teacher","parent","school_admin","twin","vibelearn","vibebooks","vibelabs","billing","analytics","global"]
const parseValue=(raw:string):unknown=>{try{return JSON.parse(raw)}catch{return raw}}
type Form={title:string;category:string;decisionType:string;ruleKey:string;ruleValue:string;reason:string;effectiveAt:string;affectedProducts:string[]}
const empty:Form={title:"",category:"product",decisionType:"configuration",ruleKey:"",ruleValue:"true",reason:"",effectiveAt:"",affectedProducts:["student"]}

export default function HQDecisionsPage(){
  const router=useRouter(); const [items,setItems]=useState<HQDecision[]>([]); const [detail,setDetail]=useState<HQDecisionDetail|null>(null); const [policies,setPolicies]=useState<HQPolicy[]>([]); const [busy,setBusy]=useState(false); const [error,setError]=useState(""); const [editing,setEditing]=useState(false); const [form,setForm]=useState<Form>(empty); const [emergency,setEmergency]=useState({policyKey:"twin.enabled",productKey:"twin",value:"false",reason:""})
  async function refresh():Promise<void>{try{const[d,p]=await Promise.all([listHQDecisions(),listHQPolicies()]);setItems(d);setPolicies(p)}catch(e){setError(e instanceof Error?e.message:"Could not load Boardroom")}}
  useEffect(()=>{void refresh()},[])
  async function open(id:string):Promise<void>{setDetail(await getHQDecisionDetail(id));setEditing(false)}
  async function act(fn:()=>Promise<unknown>,reopen=true):Promise<unknown|undefined>{setBusy(true);setError("");try{const value=await fn();await refresh();if(reopen&&detail)await open(detail.decision.id);return value}catch(e){setError(e instanceof Error?e.message:"Action failed");return undefined}finally{setBusy(false)}}
  async function save():Promise<void>{if(!form.title.trim())return;const input={title:form.title,category:form.category,decisionType:form.decisionType,ruleKey:form.ruleKey||null,ruleValue:parseValue(form.ruleValue),reason:form.reason,affectedProducts:form.affectedProducts,effectiveAt:form.effectiveAt||null};setBusy(true);try{if(editing&&detail){await updateHQDraftDecision(detail.decision.id,input);await open(detail.decision.id)}else{const id=await createHQDecision(input);setForm(empty);await open(id)}await refresh()}catch(e){setError(e instanceof Error?e.message:"Save failed")}finally{setBusy(false)}}
  async function emergencyApply():Promise<void>{if(!emergency.reason.trim()){setError("Emergency actions require a reason.");return}const policy=policies.find(p=>p.policy_key===emergency.policyKey);if(!policy)return;const value=parseValue(emergency.value);if(!window.confirm(`Emergency apply ${policy.policy_key}=${JSON.stringify(value)} to ${emergency.productKey}?`))return;const id=await act(()=>emergencySetHQPolicy(policy.policy_key,emergency.productKey,value,emergency.reason),false);if(typeof id==="string")await open(id)}
  const counts=useMemo(()=>({draft:items.filter(x=>x.status==='draft').length,waiting:items.filter(x=>['reviewed','approved'].includes(x.status)).length,active:items.filter(x=>['active','locked'].includes(x.status)).length}),[items])
  function fill(d:HQDecision){setForm({title:d.title,category:d.category,decisionType:d.decision_type,ruleKey:d.rule_key??"",ruleValue:JSON.stringify(d.rule_value),reason:d.reason??"",effectiveAt:d.effective_at?new Date(d.effective_at).toISOString().slice(0,16):"",affectedProducts:d.affected_products});setEditing(true)}
  const panel={background:'#0d1b2f',border:'1px solid rgba(255,255,255,.08)',borderRadius:15,padding:13} as const
  return <main style={{minHeight:'100dvh',background:'#07111f',color:'#f8fafc',padding:18}}><div style={{maxWidth:1180,margin:'auto'}}>
    <header style={{display:'flex',gap:10,alignItems:'center',marginBottom:16}}><button onClick={()=>router.push('/hq')}>← HQ</button><div style={{flex:1}}><h1 style={{margin:0}}>Boardroom · Decisions</h1><small>Validate → approve → publish → enforce → observe → verify / rollback</small></div><span>{counts.draft} drafts · {counts.waiting} waiting · {counts.active} active</span></header>
    {error&&<div style={{color:'#fca5a5',marginBottom:12}}>{error}</div>}
    <section style={{...panel,marginBottom:14}}><b>Emergency controls</b><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(170px,1fr))',gap:7,marginTop:10}}><select value={emergency.policyKey} onChange={e=>{const p=policies.find(x=>x.policy_key===e.target.value);setEmergency({...emergency,policyKey:e.target.value,productKey:p?.allowed_products[0]??'global',value:JSON.stringify(p?.default_value??true)})}}>{policies.map(p=><option key={p.policy_key}>{p.policy_key}</option>)}</select><select value={emergency.productKey} onChange={e=>setEmergency({...emergency,productKey:e.target.value})}>{(policies.find(p=>p.policy_key===emergency.policyKey)?.allowed_products??products).map(p=><option key={p}>{p}</option>)}</select><input value={emergency.value} onChange={e=>setEmergency({...emergency,value:e.target.value})}/><input value={emergency.reason} onChange={e=>setEmergency({...emergency,reason:e.target.value})} placeholder="Mandatory reason"/><button disabled={busy} onClick={()=>void emergencyApply()}>Emergency apply</button><button disabled={busy} onClick={()=>void act(()=>observeTwinRuntime(),false)}>Observe Twin runtime</button></div></section>
    <div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(320px,1fr))',gap:14}}><section style={panel}><b>{editing?'Edit draft':'Create decision'}</b><input placeholder="Title" value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/><select value={form.ruleKey} onChange={e=>{const p=policies.find(x=>x.policy_key===e.target.value);setForm({...form,ruleKey:e.target.value,ruleValue:JSON.stringify(p?.default_value??true),affectedProducts:p?.allowed_products.slice(0,1)??[]})}}><option value="">Select registered policy</option>{policies.map(p=><option key={p.policy_key} value={p.policy_key}>{p.policy_key} · {p.risk_level}</option>)}</select><input value={form.ruleValue} onChange={e=>setForm({...form,ruleValue:e.target.value})}/><input placeholder="Reason" value={form.reason} onChange={e=>setForm({...form,reason:e.target.value})}/><div>{products.map(p=><button key={p} disabled={!!form.ruleKey&&!policies.find(x=>x.policy_key===form.ruleKey)?.allowed_products.includes(p)} onClick={()=>setForm({...form,affectedProducts:form.affectedProducts.includes(p)?form.affectedProducts.filter(x=>x!==p):[...form.affectedProducts,p]})}>{form.affectedProducts.includes(p)?'✓ ':''}{p}</button>)}</div><button disabled={busy} onClick={()=>void save()}>{editing?'Save draft version':'Create draft'}</button></section>
    <section style={panel}><b>Decision registry</b>{items.map(d=><button key={d.id} onClick={()=>void open(d.id)} style={{display:'block',width:'100%',textAlign:'left',padding:10}}><strong>{d.code}</strong> · {d.status}<div>{d.title}</div><small>{d.rule_key??d.category} · {d.affected_products.join(', ')}</small></button>)}</section></div>
    {detail&&<section style={{...panel,marginTop:14}}><h2>{detail.decision.code} · {detail.decision.status}</h2><p>{detail.decision.title}</p><pre style={{whiteSpace:'pre-wrap'}}>Rule: {detail.decision.rule_key??'—'} = {JSON.stringify(detail.decision.rule_value)}</pre><div>{detail.decision.status==='draft'&&<><button onClick={()=>fill(detail.decision)}>Edit</button><button onClick={()=>void act(()=>markHQDecisionReviewed(detail.decision.id))}>Mark reviewed</button></>}{detail.decision.status==='reviewed'&&<button onClick={()=>void act(()=>approveHQDecision(detail.decision.id))}>Approve</button>}{detail.decision.status==='approved'&&<button onClick={()=>void act(()=>lockHQDecision(detail.decision.id))}>Publish policy</button>}{['draft','reviewed','approved'].includes(detail.decision.status)&&<button onClick={()=>void act(()=>cancelHQDecision(detail.decision.id,'Cancelled from Boardroom'))}>Cancel</button>}{['active','locked'].includes(detail.decision.status)&&<><button onClick={()=>void act(()=>verifyHQDecision(detail.decision.id))}>Verify observed state</button><button onClick={async()=>{const id=await act(()=>createHQAmendment(detail.decision.id,{reason:`Amendment of ${detail.decision.code}`}),false);if(typeof id==='string')await open(id)}}>Amend</button></>}{['active','locked'].includes(detail.decision.status)&&detail.decision.supersedes_id&&<button onClick={async()=>{if(!window.confirm('Rollback to the previous decision?'))return;const id=await act(()=>rollbackHQDecision(detail.decision.id,'Executive rollback from HQ'),false);if(typeof id==='string')await open(id)}}>Rollback</button>}</div><h3>Product state</h3>{detail.targets.map(t=><div key={t.id}>{t.product_key} · {t.status}{t.error?` · ${t.error}`:''}</div>)}<h3>Audit</h3>{detail.audit.slice(0,12).map(a=><div key={a.id}>{a.action} · {new Date(a.created_at).toLocaleString('en-KE')}</div>)}</section>}
  </div></main>
}
