import Link from "next/link"
import type { Metadata } from "next"
import { PublicHeader } from "@/components/public/PublicHeader"
import { PublicFooter } from "@/components/public/PublicFooter"

export const metadata: Metadata = { title: "About VibeSchool", description: "Why VibeSchool exists and how it connects learning, teaching, evidence and future decisions in Kenya." }

const audiences = [
  ["Learners", "Learn in a clearer structure, practise with purpose and understand what to work on next."],
  ["Teachers", "Plan, teach, assess and act on evidence without rebuilding context across disconnected tools."],
  ["Parents", "Understand what a learner is working on, where support may help and how home can reinforce learning."],
  ["Schools", "Coordinate curriculum, people, learning activity and evidence around a shared educational picture."],
  ["Institutions", "See a platform designed around traceable educational objects, role boundaries and responsible adoption."],
  ["Public sector", "Engage with a Kenyan education platform that treats provenance, child protection and evidence as product requirements."],
]

export default function AboutPage() {
  return <div className="about-page"><PublicHeader /><main id="main-content">
    <section className="hero"><div className="wrap"><p className="eyebrow">WHY VIBESCHOOL EXISTS</p><h1>Education works better when the people around a learner can work from <em>trusted context.</em></h1><p className="lead">A learner can have teachers, parents, a school and thousands of resources around them and still experience education as disconnected pieces. VibeSchool is being built to connect those pieces.</p><p className="statement">Curriculum → learning → evidence → understanding → pathways → better decisions.</p><div className="actions"><Link href="/pathways" className="primary">Explore Pathways</Link><Link href="/contact" className="secondary">Talk to VibeSchool</Link></div></div></section>
    <section className="section wrap"><p className="eyebrow dark">THE PROBLEM</p><div className="two"><h2>People are already trying. The system should help them connect the dots.</h2><div><p>Teachers are busy. Parents care. Learners are trying to progress. School leaders coordinate people, curriculum and results.</p><p>Fragmentation makes that work harder: curriculum in one place, resources in another, classroom activity somewhere else, and decisions made with only part of the picture.</p><p><strong>VibeSchool is designed around that gap.</strong></p></div></div></section>
    <section className="section darkSection"><div className="wrap"><p className="eyebrow">THE CONNECTED JOURNEY</p><h2>Not another collection of isolated education features.</h2><div className="journey">{[["01","Curriculum","Know what should be learned and how it progresses."],["02","Learning","Turn curriculum into lessons, resources, practice and teaching."],["03","Evidence","Capture what the learner actually demonstrates."],["04","Understanding","Turn evidence into useful context rather than disconnected records."],["05","Direction","Connect learning to subjects, pathways, careers and schools."]].map(([n,t,d])=><article key={n}><span>{n}</span><h3>{t}</h3><p>{d}</p></article>)}</div></div></section>
    <section className="section wrap"><p className="eyebrow dark">WHO VIBESCHOOL SERVES</p><h2>Different responsibilities. One educational journey.</h2><p className="intro">Simple enough to understand quickly, with enough depth for professionals and institutions to inspect what is underneath.</p><div className="audiences">{audiences.map(([t,d])=><article key={t}><h3>{t}</h3><p>{d}</p></article>)}</div></section>
    <section className="section trust"><div className="wrap"><p className="eyebrow dark">HOW WE EARN TRUST</p><div className="two"><h2>Trust is a product requirement, not a slogan.</h2><div><p><strong>Evidence before assumptions.</strong> Important educational claims should be traceable to evidence or clearly presented as guidance.</p><p><strong>Human responsibility stays central.</strong> Technology can assist judgement; it should not quietly manufacture educational truth.</p><p><strong>Privacy follows purpose.</strong> Access to learner information should reflect role and legitimate need.</p><p><strong>Kenyan realities matter.</strong> Mobile access, bandwidth, curriculum context and how families and schools communicate shape the product.</p></div></div></div></section>
    <section className="section wrap"><p className="eyebrow dark">FOR INSTITUTIONS & INVESTORS</p><div className="two"><h2>The interface is the visible layer. The connected education model is the larger product.</h2><div><p>VibeSchool is being built so curriculum, learning activity, assessment evidence, learner understanding, pathways and school context can become connected rather than duplicated across separate products.</p><p>We do not use invented adoption statistics as proof. Where public product evidence exists, we prefer to let people inspect the experience.</p><Link href="/pathways" className="textLink">Inspect the public Pathways experience →</Link></div></div></section>
    <section className="cta"><div className="wrap"><p className="eyebrow">SEE THE PRODUCT</p><h2>Understand VibeSchool by exploring it.</h2><p>Start with a public experience, or talk to us about a learner, school or institutional need.</p><div className="actions center"><Link href="/pathways" className="primary">Explore Pathways</Link><Link href="/contact" className="secondary">Contact VibeSchool</Link></div></div></section>
  </main><PublicFooter /><style>{styles}</style></div>
}

const styles=`.about-page{font-family:var(--font-jakarta),Arial,sans-serif;color:#101827;background:#f8f8f5;line-height:1.7}.about-page *{box-sizing:border-box}.wrap{max-width:1160px;margin:auto}.hero{background:#07111f;color:#fff;padding:92px 24px 105px}.eyebrow{font-family:var(--font-mono),monospace;letter-spacing:.16em;font-size:11px;font-weight:800;color:#c9aa50}.eyebrow.dark{color:#80651f}.hero h1,.section h2,.cta h2{font-family:var(--font-display),Arial,sans-serif;letter-spacing:-.04em;line-height:1.05}.hero h1{font-size:clamp(42px,6.5vw,76px);max-width:980px;margin:18px 0 28px;font-weight:650}.hero h1 em{font-family:var(--font-serif),Georgia,serif;color:#d4b65b;font-weight:400}.lead{font-size:19px;color:#c6cfdb;max-width:780px}.statement{font-weight:750;font-size:18px}.actions{display:flex;gap:12px;flex-wrap:wrap;margin-top:30px}.primary,.secondary{display:inline-flex;padding:13px 20px;border-radius:9px;text-decoration:none;font-weight:800}.primary{background:#d0b154;color:#07111f}.secondary{border:1px solid #738094;color:#fff}.section{padding:96px 24px}.section h2,.cta h2{font-size:clamp(33px,4.7vw,55px);margin:10px 0 25px}.two{display:grid;grid-template-columns:1fr 1fr;gap:72px}.two p,.intro{color:#596474;font-size:17px}.darkSection{background:#07111f;color:#fff}.journey{display:grid;grid-template-columns:repeat(5,1fr);margin-top:50px;border-top:1px solid #2c3847}.journey article{padding:25px 18px 0 0}.journey span{font-family:var(--font-mono);font-size:11px;color:#d0b154}.journey h3{font-size:20px;margin:10px 0 6px}.journey p{font-size:14px;color:#9ba7b5}.audiences{display:grid;grid-template-columns:repeat(3,1fr);gap:14px;margin-top:38px}.audiences article{background:#fff;border:1px solid #e2e5e8;border-radius:13px;padding:27px}.audiences h3{margin:0 0 8px}.audiences p{margin:0;color:#626c78}.trust{background:#eeeae0}.textLink{font-weight:800;color:#725914;text-decoration:none}.cta{text-align:center;background:#13243a;color:#fff;padding:88px 24px}.cta p{color:#c5ced8;max-width:650px;margin:0 auto}.center{justify-content:center}@media(max-width:800px){.hero{padding:68px 20px 76px}.section{padding:68px 20px}.two{grid-template-columns:1fr;gap:18px}.journey{grid-template-columns:1fr;border-top:0}.journey article{border-top:1px solid #2c3847;padding:18px 0}.audiences{grid-template-columns:1fr}.cta{padding:68px 20px}}`