"use client"
import {useCallback,useEffect,useState} from "react"
import {hqSupabase} from "@/lib/hq/supabase"
import {HQPage,HQPanel,HQ_THEME as C} from "@/components/hq/HQShell"

type U={id:string;full_name:string|null;role:string|null;account_status:string;created_at:string;school_id:string|null;vc_id:string|null;active_subscription_count:number;last_sign_in_at:string|null}
type M={total_users:number;new_24h:number;new_7d:number;new_30d:number;signed_in_24h:number;signed_in_7d:number;signed_in_30d:number;never_signed_in:number;active_accounts:number;unaffiliated_profiles:number;active_subscriptions:number;trialing_subscriptions:number;past_due_subscriptions:number}
const empty:M={total_users:0,new_24h:0,new_7d:0,new_30d:0,signed_in_24h:0,signed_in_7d:0,signed_in_30d:0,never_signed_in:0,active_accounts:0,unaffiliated_profiles:0,active_subscriptions:0,trialing_subscriptions:0,past_due_subscriptions:0}
function since(v:string|null){if(!v)return "Never";const ms=Date.now()-new Date(v).getTime(),m=Math.floor(ms/60000);if(m<1)return "Just now";if(m<60)return `${m}m ago`;const h=Math.floor(m/60);if(h<24)return `${h}h ago`;const d=Math.floor(h/24);return d<30?`${d}d ago`:new Date(v).toLocaleDateString()}
function Metric({label,value,sub}:{label:string;value:number|string;sub?:string}){return <div style={{padding:14,border:`1px solid ${C.border}`,borderRadius:12,background:C.panel,minWidth:0}}><div style={{fontSize:11,color:C.muted}}>{label}</div><div style={{fontSize:24,fontWeight:800,marginTop:4}}>{value}</div>{sub?<div style={{fontSize:10,color:C.muted,marginTop:3}}>{sub}</div>:null}</div>}
export default function HQUsers(){const [users,setUsers]=useState<U[]>([]),[metrics,setMetrics]=useState<M>(empty),[q,setQ]=useState(""),[loading,setLoading]=useState(true),[error,setError]=useState("");const load=useCallback(async()=>{setError("");const [u,m]=await Promise.all([hqSupabase.rpc("hq_user_directory",{p_search:q||null,p_limit:200}),hqSupabase.rpc("hq_user_intelligence_overview")]);if(u.error||m.error){setError(u.error?.message||m.error?.message||"Unable to load intelligence");return}setUsers((u.data||[]) as U[]);setMetrics((m.data||empty) as M)},[q]);useEffect(()=>{void(async()=>{await load();setLoading(false)})()},[load]);const signedInRate=metrics.total_users?Math.round(metrics.signed_in_30d/metrics.total_users*100):0;return <HQPage title="User intelligence" description="Founder view of growth, recent sign-ins, account health, affiliation and billing. Owner-gated and privacy-minimized." actions={<button onClick={()=>void load()} style={{padding:"9px 12px",borderRadius:9,border:`1px solid ${C.border}`,background:"transparent",color:C.text}}>Refresh</button>}>
<div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(120px,1fr))",gap:8}}><Metric label="Total users" value={metrics.total_users}/><Metric label="Signed in today" value={metrics.signed_in_24h}/><Metric label="Signed in 7d" value={metrics.signed_in_7d}/><Metric label="New 7d" value={metrics.new_7d}/><Metric label="30d reach" value={`${signedInRate}%`} sub={`${metrics.signed_in_30d} signed in`}/><Metric label="Need attention" value={metrics.never_signed_in+metrics.past_due_subscriptions} sub="Never signed in + past due"/></div>
<div style={{height:12}}/><HQPanel title="Founder signals"><div style={{padding:14,display:"grid",gap:7,fontSize:12}}><div><b>Activation proxy:</b> {metrics.total_users-metrics.never_signed_in} of {metrics.total_users} accounts have signed in at least once.</div><div><b>School identity:</b> {metrics.unaffiliated_profiles} profiles are not attached to a school.</div><div><b>Revenue:</b> {metrics.active_subscriptions} active, {metrics.trialing_subscriptions} trialing, {metrics.past_due_subscriptions} past due.</div><div style={{color:C.muted}}>Sign-in is an authentication signal, not proof of meaningful learning or teaching. Product-event activation and retention should be measured separately.</div></div></HQPanel>
<div style={{height:12}}/><HQPanel><div style={{padding:14}}><input aria-label="Search users" value={q} onChange={e=>setQ(e.target.value)} onKeyDown={e=>{if(e.key==='Enter')void load()}} placeholder="Search name or VibeSchool ID" style={{width:"100%",boxSizing:"border-box",padding:10,borderRadius:9,border:`1px solid ${C.border}`,background:C.panel,color:C.text}}/></div></HQPanel><div style={{height:12}}/><HQPanel title="Registered accounts">{error?<div style={{padding:14,color:C.red}}>{error}</div>:loading?<div style={{padding:14,color:C.muted}}>Loading…</div>:users.length===0?<div style={{padding:14,color:C.muted}}>No users found.</div>:users.map(u=><div key={u.id} style={{padding:"12px 14px",borderTop:`1px solid ${C.border}`,display:"grid",gridTemplateColumns:"minmax(0,2fr) 1fr 1fr",gap:10,fontSize:12}}><div style={{minWidth:0}}><b>{u.full_name||"Unnamed user"}</b><div style={{color:C.muted,fontSize:10,overflowWrap:"anywhere"}}>{u.vc_id||u.id}</div></div><div><div style={{color:C.muted,fontSize:10}}>Last sign-in</div><b>{since(u.last_sign_in_at)}</b><div style={{fontSize:10,color:C.muted}}>{u.last_sign_in_at?new Date(u.last_sign_in_at).toLocaleString():"No recorded sign-in"}</div></div><div><div style={{color:u.account_status==='active'?C.green:C.amber}}>{u.account_status}</div><div style={{fontSize:10,marginTop:3}}>{u.role||"Role —"}</div><div style={{fontSize:10,color:C.muted,marginTop:3}}>{u.active_subscription_count>0?`${u.active_subscription_count} billing record(s)`:"No active billing"}</div></div></div>)}</HQPanel></HQPage>}
