"use client"

import { useEffect, useState } from "react"
import { useRouter } from "next/navigation"
import { createHQWorkItem, listHQDepartments, listHQWorkItems, updateHQWorkItem, type HQDepartment, type HQWorkItem } from "@/lib/hq/operating"
import { HQPage, HQPanel, HQ_THEME as C, hqButtonStyle } from "@/components/hq/HQShell"
import { clearHQDraft, isHQOnline, readHQCache, readHQDraft, saveHQCache, saveHQDraft } from "@/lib/hq/offline"

const fieldStyle:React.CSSProperties={minHeight:40,padding:"8px 10px",borderRadius:10,background:"rgba(255,255,255,.04)",color:C.text,border:`1px solid ${C.border}`,font:"inherit",fontSize:12}
type WorkForm={department:string;title:string;summary:string;priority:HQWorkItem["priority"];dueAt:string;approvalRequired:boolean}
type DepartmentsCache={departments:HQDepartment[];items:HQWorkItem[];selected:string|null}
const emptyForm:WorkForm={department:"executive",title:"",summary:"",priority:"normal",dueAt:"",approvalRequired:false}
export default function HQDepartmentsPage(){
 const router=useRouter();const[departments,setDepartments]=useState<HQDepartment[]>([]);const[items,setItems]=useState<HQWorkItem[]>([]);const[selected,setSelected]=useState<string|null>(null);const[error,setError]=useState("");const[form,setForm]=useState<WorkForm>(emptyForm);const[cachedAt,setCachedAt]=useState<number|null>(null)
 useEffect(()=>{const draft=readHQDraft<WorkForm>('department-work');if(draft)setForm(draft.value)},[])
 useEffect(()=>{if(form.title||form.summary||form.dueAt||form.approvalRequired)saveHQDraft('department-work',form)},[form])
 function restoreCache(){const cached=readHQCache<DepartmentsCache>('departments');if(!cached)return false;setDepartments(cached.value.departments);setItems(cached.value.items);setSelected(cached.value.selected);setCachedAt(cached.savedAt);return true}
 async function refresh(dep=selected){setError("");try{const[d,w]=await Promise.all([listHQDepartments(),listHQWorkItems(dep,100)]);setDepartments(d);setItems(w);setCachedAt(null);saveHQCache('departments',{departments:d,items:w,selected:dep});if(!form.department&&d[0])setForm(f=>({...f,department:d[0].key}))}catch(e){const restored=restoreCache();setError(restored?"Live department state is unavailable. Showing the last-known queue.":e instanceof Error?e.message:"Could not load departments")}}
 useEffect(()=>{if(!isHQOnline())restoreCache();void refresh(null)},[])
 async function choose(k:string|null){setSelected(k);if(!isHQOnline()){const cached=readHQCache<DepartmentsCache>('departments');if(cached){setItems(cached.value.items.filter(w=>!k||w.department_key===k));setCachedAt(cached.savedAt)}return}await refresh(k)}
 async function setStatus(id:string,status:HQWorkItem["status"]){if(!isHQOnline()){setError("Reconnect before changing company work status.");return}try{await updateHQWorkItem(id,status);await refresh(selected)}catch(e){setError(e instanceof Error?e.message:"Could not update work")}}
 async function create(){if(!form.title.trim())return;if(!isHQOnline()){saveHQDraft('department-work',form);setError("Work draft saved locally. Reconnect to create it in HQ.");return}try{await createHQWorkItem({department:form.department,title:form.title.trim(),summary:form.summary.trim(),priority:form.priority,dueAt:form.dueAt||null,approvalRequired:form.approvalRequired,route:"/hq/departments"});setForm(emptyForm);clearHQDraft('department-work');await refresh(selected)}catch(e){setError(e instanceof Error?e.message:"Could not create company work")}}
 return <HQPage title="Company operations" description="Department queues, ownership, approvals and follow-through" actions={<button onClick={()=>router.push("/hq")} style={hqButtonStyle}>Command center</button>}>
  {cachedAt&&<div style={{marginBottom:10,fontSize:10.5,color:C.amber}}>Last-known queue from {new Date(cachedAt).toLocaleString("en-KE")}</div>}{error&&<div role="alert" style={{padding:11,borderRadius:10,border:"1px solid rgba(251,113,133,.3)",background:"rgba(251,113,133,.08)",color:"#fecdd3",fontSize:11,marginBottom:12}}>{error}</div>}
  <HQPanel title="Create company work" description="Drafts persist on this device. Creating or changing work requires a live connection."><div style={{padding:14}}><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(min(100%,180px),1fr))",gap:8}}><select aria-label="Department" value={form.department} onChange={e=>setForm({...form,department:e.target.value})} style={fieldStyle}>{departments.map(d=><option key={d.key} value={d.key}>{d.name}</option>)}</select><input aria-label="Work title" placeholder="Work title" value={form.title} onChange={e=>setForm({...form,title:e.target.value})} style={fieldStyle}/><input aria-label="Summary" placeholder="Summary" value={form.summary} onChange={e=>setForm({...form,summary:e.target.value})} style={fieldStyle}/><select aria-label="Priority" value={form.priority} onChange={e=>setForm({...form,priority:e.target.value as HQWorkItem["priority"]})} style={fieldStyle}><option value="low">Low</option><option value="normal">Normal</option><option value="high">High</option><option value="critical">Critical</option></select><input aria-label="Due date" type="datetime-local" value={form.dueAt} onChange={e=>setForm({...form,dueAt:e.target.value})} style={fieldStyle}/><label style={{fontSize:11,color:C.muted,display:"flex",alignItems:"center",gap:7,minHeight:40}}><input type="checkbox" checked={form.approvalRequired} onChange={e=>setForm({...form,approvalRequired:e.target.checked})}/> Needs my approval</label></div><div className="hq-action-row" style={{marginTop:10}}><button onClick={()=>void create()} disabled={!form.title.trim()} style={{...hqButtonStyle,background:C.green,color:"#06281c",border:0}}>{isHQOnline()?"Add work":"Save draft"}</button>{(form.title||form.summary)&&<button onClick={()=>{setForm(emptyForm);clearHQDraft('department-work')}} style={hqButtonStyle}>Clear draft</button>}</div></div></HQPanel>
  <section style={{marginTop:14}}><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(min(100%,220px),1fr))",gap:9}}><button onClick={()=>void choose(null)} style={{padding:13,textAlign:"left",borderRadius:13,border:`1px solid ${selected===null?C.green:C.border}`,background:selected===null?"rgba(52,211,153,.08)":C.panel,color:C.text,cursor:"pointer"}}><strong>All company work</strong><div style={{fontSize:10,color:C.muted,marginTop:5}}>{items.length} items loaded</div></button>{departments.map(d=><button key={d.key} onClick={()=>void choose(d.key)} style={{padding:13,textAlign:"left",borderRadius:13,border:`1px solid ${selected===d.key?C.green:C.border}`,background:selected===d.key?"rgba(52,211,153,.08)":C.panel,color:C.text,cursor:"pointer"}}><div style={{display:"flex",gap:8}}><strong style={{fontSize:12}}>{d.name}</strong><span style={{marginLeft:"auto",fontSize:10,color:d.critical_count?C.red:C.muted}}>{d.open_count} open</span></div><div style={{fontSize:10,color:C.muted,marginTop:5,lineHeight:1.45}}>{d.mandate}</div>{d.waiting_approval_count>0&&<div style={{fontSize:9.5,color:C.amber,marginTop:6}}>{d.waiting_approval_count} waiting approval</div>}</button>)}</div></section>
  <HQPanel title={selected?departments.find(d=>d.key===selected)?.name??"Department work":"All company work"} description={`${items.length} routed item${items.length===1?"":"s"}`}><div>{items.length===0?<div style={{padding:20,color:C.muted,fontSize:12}}>No routed work in this queue.</div>:items.map((w,i)=><div key={w.id} className="hq-mobile-stack" style={{padding:14,borderTop:i?`1px solid ${C.border}`:0}}><div><div style={{display:"flex",gap:7,alignItems:"center",flexWrap:"wrap"}}><span className="hq-status" style={{color:w.priority==="critical"?C.red:w.priority==="high"?C.amber:C.blue}}>{w.priority}</span><span style={{fontSize:10,color:C.muted}}>{w.department_key}</span><span style={{fontSize:10,color:C.muted}}>{w.status}</span>{w.approval_required&&<span className="hq-status" style={{color:C.amber}}>Approval</span>}</div><div style={{fontSize:13,fontWeight:850,marginTop:7}}>{w.title}</div>{w.summary&&<div style={{fontSize:11,color:C.muted,marginTop:4,lineHeight:1.5}}>{w.summary}</div>}{w.due_at&&<div style={{fontSize:10,color:C.muted,marginTop:5}}>Due {new Date(w.due_at).toLocaleString("en-KE")}</div>}</div><div className="hq-action-row">{w.route&&<button onClick={()=>router.push(w.route!)} style={hqButtonStyle}>Open</button>}{w.status!=="in_progress"&&w.status!=="resolved"&&<button onClick={()=>void setStatus(w.id,"in_progress")} style={hqButtonStyle}>Start</button>}{w.status!=="resolved"&&<button onClick={()=>void setStatus(w.id,"resolved")} style={{...hqButtonStyle,color:C.green}}>Resolve</button>}</div></div>)}</div></HQPanel>
 </HQPage>
}