import type { Metadata } from 'next'
import Link from 'next/link'
import { PublicHeader } from '@/components/public/PublicHeader'
import { PublicFooter } from '@/components/public/PublicFooter'

export const metadata: Metadata = { title:'Child Safety & Safeguarding | VibeSchool', description:'How VibeSchool approaches child safety, safeguarding, learner privacy and adult responsibility.' }

const principles=[
['Best interests first','Features involving children should be designed around educational benefit, safety and age-appropriate use—not engagement at any cost.'],
['Verified relationships matter','A person saying they are a parent, teacher or administrator in a browser must not by itself create authority over a learner.'],
['Private by default where it matters','Public learning and discovery should not expose a learner’s private records, family relationships, school membership or sensitive support history.'],
['Minimise what is needed','Child data should have a defined purpose. VibeSchool should avoid collecting or retaining information merely because it may be useful someday.'],
['Human escalation remains possible','Technology should not trap a learner or family inside automation when a safety, identity or safeguarding concern needs responsible human attention.'],
['No false certainty','Pathways, recommendations and educational guidance must not be presented as destiny or as a substitute for appropriate adult and professional judgement.'],
]
export default function ChildSafetyPage(){return <div className="page"><PublicHeader product="Child Safety"/><main id="main-content"><section className="hero"><div className="wrap"><p className="eyebrow">CHILD SAFETY & SAFEGUARDING</p><h1>Children need stronger boundaries, not just smaller screens.</h1><p className="lead">VibeSchool is built for education, which means some users are children. Safeguarding therefore affects identity, privacy, recommendations, communication, data access and how adults interact with learner information.</p></div></section><section className="section wrap"><p className="eyebrow dark">OUR DESIGN PRINCIPLES</p><div className="grid">{principles.map(([t,d])=><article key={t}><h2>{t}</h2><p>{d}</p></article>)}</div></section><section className="section alt"><div className="wrap two"><div><p className="eyebrow dark">FOR PARENTS & GUARDIANS</p><h2 className="big">You should be able to understand what the platform is doing.</h2></div><div><p>VibeSchool should explain when information is guidance, what is being saved, who can access learner information and when an adult-owned planning activity is different from a learner-owned record.</p><p>Never share a learner’s password, one-time code or other authentication secret with someone claiming to be VibeSchool support.</p><Link className="button" href="/contact">Ask a safety or privacy question</Link></div></div></section><section className="section wrap"><div className="two"><div><p className="eyebrow dark">FOR SCHOOLS & INSTITUTIONS</p><h2 className="big">Safeguarding is also an authority problem.</h2></div><div><p>Institutional adoption should define which adults may see or change which learner information, how those relationships are verified, how access is removed, what support escalation exists and what evidence is retained for consequential actions.</p><Link className="text" href="/institutions">Institutional due diligence →</Link></div></div></section><section className="report"><div className="wrap"><h2>Concern about a learner’s safety or inappropriate use?</h2><p>Use VibeSchool’s Contact page and provide only the information necessary to explain the concern. For immediate danger, use the appropriate local emergency or safeguarding authority rather than waiting for a website response.</p><div className="links"><Link href="/contact">Contact VibeSchool</Link><Link href="/trust">Back to Trust Centre</Link><Link href="/legal/privacy">Privacy Policy</Link></div></div></section></main><PublicFooter/><style>{styles}</style></div>}
const styles=`.page{background:#f8f8f5;color:#111827;font-family:var(--font-jakarta),Arial,sans-serif;line-height:1.7}.page *{box-sizing:border-box}.wrap{max-width:1080px;margin:auto}.hero{background:#07111f;color:#fff;padding:88px 24px}.eyebrow{font:850 11px var(--font-mono),monospace;letter-spacing:.15em;color:#d0b154}.eyebrow.dark{color:#755b17}h1,.big{font-family:var(--font-display),Arial,sans-serif;letter-spacing:-.04em;line-height:1.06}h1{font-size:clamp(41px,6vw,69px);max-width:900px;margin:14px 0 24px}.lead{font-size:18px;color:#c6cfda;max-width:780px}.section{padding:82px 24px}.grid{display:grid;grid-template-columns:repeat(2,1fr);gap:14px}.grid article{background:#fff;border:1px solid #e0e3e7;border-radius:14px;padding:27px}.grid h2{font-size:21px;margin:0 0 8px}.grid p,.two p{color:#5c6673}.alt{background:#eeeae0}.two{display:grid;grid-template-columns:1fr 1fr;gap:64px}.big{font-size:clamp(31px,4vw,47px);margin:10px 0}.button{display:inline-flex;background:#111827;color:#fff;padding:12px 17px;border-radius:9px;text-decoration:none;font-weight:850}.text{font-weight:850;color:#6f5615;text-decoration:none}.report{background:#13243a;color:#fff;padding:62px 24px}.report h2{font-size:30px;margin:0}.report p{color:#c6cfda;max-width:780px}.links{display:flex;gap:18px;flex-wrap:wrap}.links a{color:#e4c96f;font-weight:800;text-decoration:none}@media(max-width:700px){.hero,.section{padding:60px 18px}.grid,.two{grid-template-columns:1fr}.two{gap:18px}}`