"use client"
export const dynamic="force-dynamic"

import {useEffect,useMemo,useState} from "react"
import {useRouter} from "next/navigation"
import {hqSupabase} from "@/lib/hq/supabase"

const inputStyle:React.CSSProperties={width:"100%",boxSizing:"border-box",marginTop:7,padding:"13px 14px",borderRadius:12,border:"1px solid rgba(255,255,255,.12)",background:"rgba(255,255,255,.05)",color:"white",fontSize:15,outline:"none"}

export default function HQResetPasswordPage(){
 const router=useRouter();const[password,setPassword]=useState("");const[confirmPassword,setConfirmPassword]=useState("");const[showPassword,setShowPassword]=useState(false);const[ready,setReady]=useState(false);const[checking,setChecking]=useState(true);const[error,setError]=useState("");const[success,setSuccess]=useState("");const[loading,setLoading]=useState(false)
 const checks=useMemo(()=>({length:password.length>=12,letter:/[A-Za-z]/.test(password),number:/\d/.test(password),match:password.length>0&&password===confirmPassword}),[password,confirmPassword]);const validPassword=checks.length&&checks.letter&&checks.number&&checks.match
 useEffect(()=>{let mounted=true;async function establish(){setChecking(true);setError("");try{const code=new URL(window.location.href).searchParams.get("code");if(code){const{error:e}=await hqSupabase.auth.exchangeCodeForSession(code);if(e)throw e;const clean=new URL(window.location.href);clean.searchParams.delete("code");window.history.replaceState({},"",`${clean.pathname}${clean.search}${clean.hash}`)}const{data,error:userError}=await hqSupabase.auth.getUser();if(!mounted)return;if(userError||!data.user){setReady(false);setError("This recovery link is invalid, expired or already used. Ask the Founder to send a new password setup/reset email from HQ Team.");return}setReady(true)}catch(e){if(mounted){setReady(false);setError(e instanceof Error?e.message:"The recovery link could not be verified.")}}finally{if(mounted)setChecking(false)}}const{data:listener}=hqSupabase.auth.onAuthStateChange((event,session)=>{if(mounted&&event==="PASSWORD_RECOVERY"&&session?.user){setReady(true);setChecking(false);setError("")}});void establish();return()=>{mounted=false;listener.subscription.unsubscribe()}},[])
 async function handleReset(){setError("");setSuccess("");if(!ready)return setError("A valid recovery session is required.");if(!validPassword)return setError("Use at least 12 characters with letters and a number, and make sure both passwords match.");setLoading(true);try{const{error:updateError}=await hqSupabase.auth.updateUser({password,data:{hq_password_ready:true}});if(updateError)throw updateError;const{data:sessionData}=await hqSupabase.auth.getSession();const token=sessionData.session?.access_token;if(!token)throw new Error("Password changed but the HQ session expired. Sign in and retry.");const completion=await fetch("/api/hq/complete-password-setup",{method:"POST",headers:{Authorization:`Bearer ${token}`}});const completionBody=await completion.json();if(!completion.ok)throw new Error(completionBody.error||"HQ account status could not be activated.");await hqSupabase.auth.signOut({scope:"local"});setReady(false);setPassword("");setConfirmPassword("");setSuccess("Password created successfully. Your HQ account is Active and ready for sign-in.");window.setTimeout(()=>router.replace("/hq/login?reset=success"),900)}catch(e){setError(e instanceof Error?e.message:"Password could not be changed.");setLoading(false)}}
 const disabled=checking||!ready||loading||Boolean(success)
 return <main style={{minHeight:"100dvh",display:"grid",placeItems:"center",background:"radial-gradient(circle at top,#10233d 0,#07111f 46%,#040a12 100%)",color:"#f8fafc",padding:"24px 16px",fontFamily:"Inter,system-ui,sans-serif"}}><section style={{width:"100%",maxWidth:440,border:"1px solid rgba(255,255,255,.1)",borderRadius:24,padding:"clamp(22px,6vw,34px)",background:"rgba(7,17,31,.88)"}}><div style={{fontSize:11,fontWeight:950,letterSpacing:".13em",color:"#34d399",textTransform:"uppercase",marginBottom:10}}>VibeSchool HQ secure recovery</div><h1>Choose your HQ password</h1><p style={{fontSize:13,lineHeight:1.6,color:"rgba(255,255,255,.52)"}}>Only you choose and know this password. HQ becomes Active only after the recovery is fully completed.</p>{checking&&<div role="status">Verifying secure recovery link…</div>}{error&&<div role="alert" style={{color:"#fecaca",marginBottom:12}}>{error}</div>}{success&&<div role="status" style={{color:"#bbf7d0",marginBottom:12}}>{success}</div>}<div><label htmlFor="new-password">New password</label><button type="button" onClick={()=>setShowPassword(v=>!v)} disabled={disabled} style={{float:"right"}}>{showPassword?"Hide":"Show"}</button></div><input id="new-password" value={password} onChange={e=>setPassword(e.target.value)} type={showPassword?"text":"password"} autoComplete="new-password" minLength={12} disabled={disabled} style={{...inputStyle,marginBottom:14}}/><label htmlFor="confirm-password">Confirm new password</label><input id="confirm-password" value={confirmPassword} onChange={e=>setConfirmPassword(e.target.value)} onKeyDown={e=>{if(e.key==="Enter"&&!disabled&&validPassword)void handleReset()}} type={showPassword?"text":"password"} autoComplete="new-password" minLength={12} disabled={disabled} style={{...inputStyle,marginBottom:14}}/><div style={{fontSize:11,marginBottom:18}}>{checks.length?"✓":"○"} 12+ characters · {checks.letter?"✓":"○"} letters · {checks.number?"✓":"○"} number · {checks.match?"✓":"○"} match</div><button disabled={disabled||!validPassword} onClick={()=>void handleReset()} style={{width:"100%",padding:14,borderRadius:12}}>{loading?"Saving password…":"Save password & activate HQ"}</button></section></main>
}
