"use client"

import Link from "next/link"
import { useCallback,useEffect,useState } from "react"
import { useRouter,useSearchParams } from "next/navigation"
import { hqSupabase } from "@/lib/hq/supabase"
import { HQPage,HQPanel,HQ_THEME as C } from "@/components/hq/HQShell"

type Row={id:string;name:string;county:string|null;sub_county:string|null;knec_code:string|null;source:string;linked_users:number|null;active_users:number|null}
type Result={state:string;total:number;offset:number;limit:number;rows:Row[];generated_at:string}
const states=["known","canonical","connected","active"] as const

export default function HQSchoolExplorer(){
 const router=useRouter();const params=useSearchParams();const initial=(params.get("state")||"canonical") as typeof states[number];const [state,setState]=useState(states.includes(initial)?initial:"canonical");const [county,setCounty]=useState(params.get("county")||"");const [query,setQuery]=useState("");const [offset,setOffset]=useState(0);const [result,setResult]=useState<Result|null>(null);const [loading,setLoading]=useState(true);const [error,setError]=useState("")
 const load=useCallback(async()=>{setLoading(true);setError("");const {data,error:e}=await hqSupabase.rpc("hq_school_network_explorer",{p_state:state,p_county:county||null,p_query:query.trim()||null,p_days:30,p_offset:offset,p_limit:50});if(e){setResult(null);setError("School Explorer is unavailable in this environment.")}else setResult(data as Result);setLoading(false)},[state,county,query,offset]);useEffect(()=>{const t=setTimeout(()=>void load(),query?220:0);return()=>clearTimeout(t)},[load,query]);const changeState=(s:typeof states[number])=>{setState(s);setOffset(0)};const total=result?.total??0;const limit=result?.limit??50
 return <HQPage title="School Explorer" description="Paginated evidence explorer across known directory records and canonical VibeSchool schools."><div className="se-stack"><nav className="se-tabs"><Link href="/hq/schools">Overview</Link><Link className="active" href="/hq/schools/explorer">Explorer</Link><Link href="/hq/schools/intelligence">Intelligence</Link><Link href="/hq/schools/data-quality">Data quality</Link></nav>
  <div className="se-tools"><div className="se-states" role="group" aria-label="School network state">{states.map(s=><button key={s} className={state===s?"active":""} onClick={()=>changeState(s)}>{s}</button>)}</div><input value={query} onChange={e=>{setQuery(e.target.value);setOffset(0)}} placeholder="Search name or school code" aria-label="Search schools"/><input value={county} onChange={e=>{setCounty(e.target.value);setOffset(0)}} placeholder="County (optional)" aria-label="County filter"/></div>
  <div className="se-semantic"><strong>{state}</strong><span>{state==="known"?"Directory evidence; not necessarily canonical.":state==="canonical"?"Canonical non-deleted schools.":state==="connected"?"Canonical schools with VibeSchool membership.":"Connected schools with recent school-scoped activity."}</span></div>
  {error&&<div className="se-notice" role="status">{error}</div>}{loading?<div className="se-empty">Loading schools…</div>:result?<HQPanel title={`${total.toLocaleString()} ${state} schools`} description={`Showing ${total?offset+1:0}–${Math.min(offset+limit,total)}. Every canonical row opens School 360.`}><div className="se-list">{result.rows.length===0?<div className="se-empty">No school evidence matches this scope.</div>:result.rows.map(r=><button key={`${r.source}-${r.id}`} disabled={r.source!=="CANONICAL"} onClick={()=>r.source==="CANONICAL"&&router.push(`/hq/schools/${r.id}`)}><div><strong>{r.name}</strong><span>{[r.sub_county,r.county].filter(Boolean).join(" · ")||"Location unavailable"}</span></div><div className="se-right"><b>{r.source}</b>{r.source==="CANONICAL"&&<small>{r.linked_users??0} linked · {r.active_users??0} active</small>}</div></button>)}</div><div className="se-pager"><button disabled={offset===0} onClick={()=>setOffset(Math.max(0,offset-limit))}>Previous</button><span>Page {Math.floor(offset/limit)+1} of {Math.max(1,Math.ceil(total/limit))}</span><button disabled={offset+limit>=total} onClick={()=>setOffset(offset+limit)}>Next</button></div></HQPanel>:null}
 </div><style jsx global>{`
  .se-stack{display:grid;gap:14px}.se-tabs{display:flex;gap:6px;overflow:auto}.se-tabs a{padding:11px 14px;border:1px solid ${C.border};border-radius:10px;color:${C.muted};text-decoration:none;font-size:11px;font-weight:850;white-space:nowrap}.se-tabs a.active{background:rgba(59,130,246,.16);color:#fff}.se-tools{display:grid;grid-template-columns:auto minmax(220px,1fr) minmax(150px,.45fr);gap:8px;padding:12px;border:1px solid ${C.border};border-radius:12px;background:${C.panel}.se-states{display:flex;gap:4px}.se-states button,.se-tools input,.se-pager button{min-height:42px;border:1px solid ${C.border};border-radius:9px;background:rgba(255,255,255,.035);color:#fff;padding:0 11px}.se-states button{text-transform:capitalize;font-weight:850}.se-states button.active{background:rgba(59,130,246,.2);border-color:rgba(96,165,250,.35)}.se-semantic{display:flex;gap:8px;align-items:center;color:${C.muted};font-size:10px}.se-semantic strong{text-transform:uppercase;color:#93c5fd}.se-notice,.se-empty{padding:14px;color:${C.muted};font-size:11px}.se-notice{border:1px solid rgba(245,158,11,.25);border-radius:10px}.se-list{padding:0 13px}.se-list>button{width:100%;display:flex;justify-content:space-between;align-items:center;gap:12px;padding:12px 3px;border:0;border-bottom:1px solid ${C.border};background:none;color:#fff;text-align:left;cursor:pointer}.se-list>button:disabled{cursor:default;opacity:.72}.se-list strong,.se-list span,.se-right b,.se-right small{display:block}.se-list strong{font-size:11px}.se-list span,.se-right small{font-size:9px;color:${C.muted};margin-top:4px}.se-right{text-align:right}.se-right b{font-size:8px;color:#93c5fd}.se-pager{display:flex;justify-content:space-between;align-items:center;padding:12px;font-size:9px;color:${C.muted}.se-pager button:disabled{opacity:.4}
  @media(max-width:900px){.hq-sidebar{display:none!important}.hq-page{margin-left:0!important;padding-top:60px!important}.hq-mobile-topbar{display:flex!important}.hq-bottom-nav{display:grid!important}.se-tools{grid-template-columns:1fr}.se-states{overflow:auto}.se-states button{flex:1 0 auto}}@media(max-width:520px){.se-list>button{align-items:flex-start}.se-right small{max-width:100px}.se-semantic{display:block}.se-semantic span{display:block;margin-top:3px}}
 `}</style></HQPage>
}
