"use client"

import Link from "next/link"
import {useEffect,useMemo,useState} from "react"
import {HQPage,HQPanel,HQ_THEME as C,hqButtonStyle} from "@/components/hq/HQShell"
import {hqSupabase} from "@/lib/hq/supabase"

type OwnerReport={executive_dashboard?:{headline?:{wau?:number|null}}}
type Source={source:string;touches:number;signups:number;activated:number;returned_day2:number;paid:number;revenue_kes:number}
type Growth={summary?:Record<string,number>;sources?:Source[]}
type Studio={publications?:{published?:number;draft?:number};assessment_bank?:{questions?:number};curriculum?:{outcomes?:number};moderation?:{exam_flags?:number;open_incidents?:number;assessment_requests?:number}}

const number=(value:unknown)=>Number(value||0).toLocaleString()
const money=(value:unknown)=>`KES ${Number(value||0).toLocaleString()}`
const percent=(value:number,total:number)=>total>0?Math.round(value/total*100):0
function ownerReport(value:unknown):OwnerReport{return value&&typeof value==="object"?value as OwnerReport:{}}
function growthReport(value:unknown):Growth{return value&&typeof value==="object"?value as Growth:{}}
function studioReport(value:unknown):Studio{return value&&typeof value==="object"?value as Studio:{}}
function Metric({label,value,note}:{label:string;value:string;note:string}){return <article className="metric"><span>{label}</span><strong>{value}</strong><small>{note}</small></article>}

const doctrine=[
 ["What we sell","Continuous educational progress: learn, practise, receive feedback, understand weakness, improve, then know the next useful action."],
 ["Why customers return","Retention should come from another real educational need tomorrow, not artificial lock-in."],
 ["Wallet & pricing","Keep learner access highly affordable and reduce payment friction. Scale, schools, teacher productivity, premium learning and sponsorship expand the economics."],
 ["Access","Do not deliberately reduce educational quality because a family cannot pay. Use free baseline, sponsorship, school licences and scholarship mechanisms."],
 ["Growth","Teachers, TikTok challenges, school-gate QR campaigns, referrals, creators, agents and schools are measurable distribution channels."],
 ["Studio","Studio creates; Growth distributes; Product delivers value; Finance measures economics; Intelligence identifies what works."],
 ["School conversion","Track adoption from learners and teacher champions toward active schools and institutional customers."],
 ["Moat","The deeper moat is trusted educational continuity across learner, teacher, family, school, curriculum, evidence and next actions."],
] as const

export default function HQCompany(){
 const[owner,setOwner]=useState<OwnerReport>({}),[growth,setGrowth]=useState<Growth>({}),[studio,setStudio]=useState<Studio>({}),[error,setError]=useState(""),[loading,setLoading]=useState(true)
 async function load(){setLoading(true);setError("");try{const[r,g,s]=await Promise.all([hqSupabase.rpc("hq_get_seven_day_owner_report"),hqSupabase.rpc("hq_growth_command_overview",{p_days:30}),hqSupabase.rpc("hq_studio_overview")]);for(const result of[r,g,s])if(result.error)throw new Error(result.error.message);setOwner(ownerReport(r.data));setGrowth(growthReport(g.data));setStudio(studioReport(s.data))}catch(e){setError(e instanceof Error?e.message:"Company evidence unavailable")}finally{setLoading(false)}}
 useEffect(()=>{void load()},[])
 const headline=owner.executive_dashboard?.headline??{},summary=growth.summary??{},sources=growth.sources??[]
 const evidencedSchools=Number(summary.school_customers??0)+Number(summary.schools_in_pipeline??0)
 const maxPaid=Math.max(1,...sources.map(source=>source.paid||0))
 const heat=useMemo(()=>sources.slice(0,8).map(source=>({source,stages:[source.touches,source.signups,source.activated,source.returned_day2,source.paid]})),[sources])
 return <HQPage title="Company Doctrine & Business Plan" description="Founder-readable strategy connected to live HQ evidence." actions={<><Link href="/hq/growth" style={{...hqButtonStyle,textDecoration:"none"}}>Growth Command</Link><Link href="/hq/studio" style={{...hqButtonStyle,textDecoration:"none"}}>Studio</Link><button style={hqButtonStyle} disabled={loading} onClick={()=>void load()}>Refresh</button></>}>
  {error&&<div className="error">Live evidence unavailable: {error}. Doctrine remains readable; unavailable evidence is not treated as zero.</div>}
  <section className="hero"><div><span>BUSINESS NORTH STAR</span><h2>Continuous educational progress, every learning day.</h2><p>Learn → Practise → Feedback → Understand weakness → Improve → Next action.</p></div><aside><b>Operating loop</b><p>Doctrine → Product → Studio → Growth → Finance → Intelligence → Founder decisions</p></aside></section>
  <section className="metrics"><Metric label="Weekly active users" value={headline.wau==null?"NOT INSTRUMENTED":number(headline.wau)} note="Trailing 7-day authoritative activity"/><Metric label="Paying learners" value={number(summary.paid)} note="30-day attributed payment evidence"/><Metric label="Evidenced schools" value={number(evidencedSchools)} note="Customers plus Growth pipeline"/><Metric label="PAL / active school" value="NOT INSTRUMENTED" note="Needs a canonical active-school denominator"/><Metric label="Attributed revenue" value={money(summary.revenue_kes)} note="Recorded 30-day attribution"/><Metric label="Published content" value={number(studio.publications?.published)} note={`${number(studio.publications?.draft)} drafts in Studio`}/></section>
  <div className="grid"><HQPanel title="Business doctrine" description="Readable commercial principles below the locked Mission/Vision constitution."><div className="doctrine">{doctrine.map(([title,body],index)=><article key={title}><b>{String(index+1).padStart(2,"0")}</b><div><h3>{title}</h3><p>{body}</p></div></article>)}</div></HQPanel><HQPanel title="Revenue engines" description="Reinforcing engines governed by unit economics and authority."><div className="engines">{["Learning-day / wallet access","Premium revision, mastery, mocks & holiday programmes","Teacher professional tools","School / institutional licences","Sponsored learning credits / CSR","Publishing & marketplace distribution","Governed sponsorship / advertising"].map((item,index)=><div key={item}><span>{index+1}</span><strong>{item}</strong></div>)}</div></HQPanel></div>
  <div className="grid"><HQPanel title="Paid learners by acquisition source" description="Recorded attributed outcomes only."><div className="bars">{sources.length?sources.slice(0,8).map(source=><div className="bar" key={source.source}><span>{source.source.replaceAll("_"," ")}</span><div><i style={{width:`${Math.max(2,source.paid/maxPaid*100)}%`}}/></div><strong>{number(source.paid)}</strong></div>):<div className="empty">No attributed source evidence yet.</div>}</div></HQPanel><HQPanel title="Studio production pulse"><div className="studio">{[["Published",studio.publications?.published],["Drafts",studio.publications?.draft],["Assessment questions",studio.assessment_bank?.questions],["Curriculum outcomes",studio.curriculum?.outcomes],["Moderation items",Number(studio.moderation?.exam_flags??0)+Number(studio.moderation?.open_incidents??0)+Number(studio.moderation?.assessment_requests??0)]].map(([label,value])=><div key={String(label)}><span>{label}</span><strong>{number(value)}</strong></div>)}</div></HQPanel></div>
  <HQPanel title="Acquisition conversion heatmap" description="Stage retention against each source's own touch count.">{heat.length?<div className="heat"><div className="heatrow head"><span>Source</span>{["Touch","Signup","Activated","D2","Paid"].map(stage=><b key={stage}>{stage}</b>)}</div>{heat.map(({source,stages})=><div className="heatrow" key={source.source}><span>{source.source.replaceAll("_"," ")}</span>{stages.map((value,index)=>{const intensity=index===0?100:percent(value,Math.max(1,source.touches));return <b key={index} title={`${number(value)} · ${intensity}% of touches`} style={{background:`rgba(34,197,94,${Math.max(.06,Math.min(.9,intensity/100))})`}}>{index===0?number(value):`${intensity}%`}</b>})}</div>)}</div>:<div className="empty">Heatmap will populate when Growth attribution evidence exists.</div>}</HQPanel>
  <HQPanel title="Founder measurement contract" description="Unknown metrics remain explicit rather than fabricated."><div className="contract">{["WAU by role","Learning days / active learner","Activation","D2 / W1 / W2 / 30-day retention","Wallet conversion","Repeat payment","PAL / active school","CAC by channel when spend is known","Revenue and gross margin by channel","Studio throughput / release cycle time","AI/inference unit-cost trend","Sponsored learner reach"].map(item=><div key={item}><span>MEASURE</span><strong>{item}</strong></div>)}</div><p className="rule">Unknown values must remain <b>NOT INSTRUMENTED</b> or unavailable. HQ must never fabricate business evidence.</p></HQPanel>
  <div className="links"><Link href="/hq/analytics">Product →</Link><Link href="/hq/marketing">Marketing →</Link><Link href="/hq/growth">Growth →</Link><Link href="/hq/studio">Studio →</Link><Link href="/hq/billing">Finance →</Link><Link href="/hq/intelligence">Intelligence →</Link></div>
  <style jsx>{`.error{padding:12px;margin-bottom:12px;border:1px solid rgba(239,68,68,.4);border-radius:12px;color:#fecaca}.hero{display:grid;grid-template-columns:1.5fr .8fr;gap:12px;margin-bottom:12px}.hero>div,.hero>aside{border:1px solid ${C.border};border-radius:16px;background:${C.panel};padding:20px}.hero span,.contract span{font-size:9px;letter-spacing:.1em;font-weight:900;color:${C.green}}.hero h2{font-size:clamp(22px,3vw,34px);margin:7px 0}.hero p,.doctrine p,.rule{color:${C.muted};font-size:11px;line-height:1.6}.metrics{display:grid;grid-template-columns:repeat(auto-fit,minmax(165px,1fr));gap:9px;margin-bottom:12px}.metric{border:1px solid ${C.border};background:${C.panel};border-radius:13px;padding:14px;display:grid;gap:5px}.metric span,.metric small,.studio span{color:${C.muted};font-size:10px}.metric strong{font-size:22px}.grid{display:grid;grid-template-columns:minmax(0,1.45fr) minmax(280px,.75fr);gap:12px;margin:12px 0}.doctrine,.engines,.bars,.studio,.contract{padding:12px;display:grid;gap:8px}.doctrine article{display:grid;grid-template-columns:32px 1fr;gap:8px;padding:10px 0;border-bottom:1px solid ${C.border}}.doctrine h3,.doctrine p{margin:0}.doctrine p{margin-top:4px}.engines div,.contract div,.studio div{padding:10px;border:1px solid ${C.border};border-radius:10px}.engines span{margin-right:8px;color:${C.green}}.bar{display:grid;grid-template-columns:130px 1fr 50px;gap:8px;align-items:center}.bar span{font-size:10px;color:${C.muted};text-transform:capitalize}.bar>div{height:10px;background:rgba(255,255,255,.05);border-radius:999px;overflow:hidden}.bar i{display:block;height:100%;background:linear-gradient(90deg,${C.blue},${C.green})}.studio{grid-template-columns:repeat(2,1fr)}.studio strong{display:block;margin-top:4px;font-size:18px}.heat{overflow:auto;padding:12px}.heatrow{min-width:650px;display:grid;grid-template-columns:180px repeat(5,1fr);gap:5px;margin-bottom:5px}.heatrow span,.heatrow b{padding:9px;font-size:10px}.heatrow span{text-transform:capitalize}.heatrow b{display:grid;place-items:center;border-radius:7px}.head b,.head span{color:${C.muted};font-size:9px;text-transform:uppercase}.contract{grid-template-columns:repeat(auto-fit,minmax(210px,1fr))}.contract strong{display:block;font-size:11px;margin-top:3px}.rule{padding:0 12px 12px}.empty{padding:16px;color:${C.muted};font-size:11px}.links{display:flex;gap:9px;flex-wrap:wrap;margin-top:12px}.links a{padding:9px 11px;border:1px solid ${C.border};border-radius:9px;color:#bfdbfe;text-decoration:none;font-size:11px;font-weight:800}@media(max-width:820px){.hero,.grid{grid-template-columns:1fr}.bar{grid-template-columns:100px 1fr 45px}}`}</style>
 </HQPage>
}
