'use client'

import { Modal, Btn, C } from "@/components/teacher/ui";
import type { TimetableSlot } from "@/lib/types";

const PLAN = {
  objectives: [
    "Solve linear equations with one variable",
    "Apply equations to real-world contexts",
  ],
  introduction:    "Begin with a real-world problem: 'If a matatu carries 14 passengers and 3 get off at each stop, how many stops before it is empty?' Students model this as an equation.",
  development:     "Introduce the balance method. Students work in pairs on differentiated worksheets. Higher: multi-step. On-track: single-step with negatives. Support: pictorial balance with guided steps.",
  consolidation:   "Exit card: solve 3x + 7 = 22. Students write one real-world equation of their own.",
  assessmentHook:  "Moment 3 exit check — auto-marked. Results feed progressive record.",
  homework:        "Textbook p.84 Exercise 3B — Questions 1–10.",
  differentiation: {
    higher:   "Multi-step equations with brackets and fractions.",
    on_track: "Single-step equations with negative numbers.",
    support:  "Pictorial balance method with step-by-step scaffold.",
  },
};

interface Props {
  slot:    TimetableSlot;
  onClose: () => void;
}

export default function LessonPlanModal({ slot, onClose }: Props) {
  const sections = [
    { label: "Learning Objectives",    content: PLAN.objectives.map((o, i) => `${i + 1}. ${o}`).join("\n") },
    { label: "Introduction (5–7 min)", content: PLAN.introduction },
    { label: "Development (20–25 min)", content: PLAN.development },
    { label: "Consolidation (10 min)", content: PLAN.consolidation },
    { label: "Assessment Hook",        content: PLAN.assessmentHook },
    { label: "Homework",               content: PLAN.homework },
  ];

  return (
    <Modal open onClose={onClose} title={`Lesson Plan — ${slot.subject} ${slot.class} · ${slot.start}`}>
      <div style={{ fontSize: 12, color: C.textMuted, marginBottom: 14 }}>
        Generated by Pedagogical Chain · 12hrs before lesson
      </div>

      {sections.map(s => (
        <div key={s.label} style={{ marginBottom: 14 }}>
          <div style={{ fontSize: 10, fontWeight: 800, color: C.textMuted, letterSpacing: 1, textTransform: "uppercase", marginBottom: 5 }}>
            {s.label}
          </div>
          <div style={{ fontSize: 13, color: C.textPrimary, lineHeight: 1.6, whiteSpace: "pre-line" }}>
            {s.content}
          </div>
        </div>
      ))}

      <div style={{ marginBottom: 14 }}>
        <div style={{ fontSize: 10, fontWeight: 800, color: C.textMuted, letterSpacing: 1, textTransform: "uppercase", marginBottom: 8 }}>
          Differentiation
        </div>
        {Object.entries(PLAN.differentiation).map(([level, desc]) => (
          <div key={level} style={{ marginBottom: 8, padding: "10px 14px", borderRadius: 10, background: C.surface }}>
            <span style={{
              fontSize: 10, fontWeight: 800, textTransform: "uppercase", marginRight: 8,
              color: level === "higher" ? "#7c3aed" : level === "on_track" ? C.accent : "#f59e0b",
            }}>
              {level.replace("_", " ")}
            </span>
            <span style={{ fontSize: 13, color: C.textPrimary }}>{desc}</span>
          </div>
        ))}
      </div>

      <div style={{ display: "flex", gap: 10, justifyContent: "flex-end" }}>
        <Btn variant="ghost" onClick={onClose}>Close</Btn>
        <Btn>Edit Plan</Btn>
      </div>
    </Modal>
  );
}