"use client";

import { useEffect, useMemo, useState } from "react";
import { useRouter } from "next/navigation";
import { supabase } from "@/lib/supabase";
import type { PulseSnapshot } from "@/lib/types";
const WEEK_TYPE_LABELS:Record<string,string>={exam:"Exams",midterm_break:"Mid-Term Break",sports:"Sports",holiday:"Holiday"};
const p={width:18,height:18,viewBox:"0 0 24 24",fill:"none",stroke:"currentColor",strokeWidth:2,strokeLinecap:"round" as const,strokeLinejoin:"round" as const};
const Bell=()=> <svg {...p}><path d="M6 8a6 6 0 0 1 12 0c0 3 1 5 1.5 6H4.5C5 13 6 11 6 8z"/><path d="M10 20a2 2 0 0 0 4 0"/></svg>;
const ClassIcon=()=> <svg {...p}><circle cx="9" cy="8" r="3"/><path d="M3.5 19a5.5 5.5 0 0 1 11 0M16 6a3 3 0 0 1 0 6M17.5 14.5A5 5 0 0 1 21 19"/></svg>;
const Chevron=()=> <svg width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.2"><path d="M6 9l6 6 6-6"/></svg>;
function greeting(){const h=new Date().getHours();return h<12?"Good morning":h<17?"Good afternoon":"Good evening"}
export default function PulseHeader({snap,name,selectedKey,onSelectedKeyChange,onOpenNotifications,offline=false,contextRefreshing=false}:{snap:PulseSnapshot;name:string;avatarUrl?:string;selectedKey:string;onSelectedKeyChange:(key:string)=>void;onOpenNotifications?:()=>void;schools?:{id:string;name:string}[];activeSchoolId?:string|null;onSchoolChange?:(id:string)=>void;offline?:boolean;contextRefreshing?:boolean}){
 const router=useRouter(),[unread,setUnread]=useState(0);useEffect(()=>{let x=false;supabase.from("notifications").select("id",{count:"exact",head:true}).eq("user_id",snap.userId).eq("is_read",false).then(({count})=>{if(!x)setUnread(count??0)});return()=>{x=true}},[snap.userId]);
 const key=(c:string,s:string)=>`${c}::${s}`,[cid,sid]=selectedKey.split("::"),slot=snap.todaySlots.find(s=>s.class_id===cid&&s.subject_id===sid),roster=snap.myClasses.find(c=>c.class_id===cid&&c.subject_id===sid),options=useMemo(()=>[...snap.myClasses].sort((a,b)=>`${a.class_name} ${a.subject}`.localeCompare(`${b.class_name} ${b.subject}`)),[snap.myClasses]);
 const date=new Date().toLocaleDateString("en-KE",{weekday:"short",day:"numeric",month:"short"}),week=snap.weekNumber==null?"No active term":snap.weekType&&snap.weekType!=="normal"?`Term ${snap.termNumber??"—"} · Week ${snap.weekNumber} · ${WEEK_TYPE_LABELS[snap.weekType]??snap.weekType}`:`Term ${snap.termNumber??"—"} · Week ${snap.weekNumber}`;
 return <header style={{marginBottom:14}}><div style={{display:"flex",alignItems:"center",justifyContent:"space-between",gap:12,marginBottom:12}}><div><h1 style={{margin:0,fontSize:20,fontWeight:900,color:"#111827"}}>{greeting()}{name?`, ${name}`:""}</h1><div style={{fontSize:12,color:"#6b7280",marginTop:4}}>{date} · {week}{offline?" · Offline snapshot":""}</div></div><button type="button" onClick={()=>{onOpenNotifications?.();router.push("/teacher/notifications")}} aria-label="Open notifications" style={{position:"relative",width:44,height:44,border:"1px solid #e5e7eb",borderRadius:14,background:"#fff",display:"grid",placeItems:"center"}}><Bell/>{unread>0&&<span style={{position:"absolute",top:-4,right:-4,minWidth:18,height:18,borderRadius:99,background:"#dc2626",color:"#fff",fontSize:9,fontWeight:900,display:"grid",placeItems:"center"}}>{unread>9?"9+":unread}</span>}</button></div><section style={{background:"#fff",border:"1px solid #e5e7eb",borderRadius:18,padding:12,boxShadow:"0 2px 10px rgba(15,23,42,.045)"}}>{options.length?<label style={{display:"flex",alignItems:"center",gap:11}}><span style={{width:36,height:36,borderRadius:12,background:"#ecfdf5",color:"#047857",display:"grid",placeItems:"center"}}><ClassIcon/></span><span style={{minWidth:0,flex:1}}><span style={{display:"block",fontSize:10,color:"#6b7280",fontWeight:900,textTransform:"uppercase",letterSpacing:.8}}>Teaching context</span><span style={{position:"relative",display:"block"}}><select disabled={contextRefreshing} value={selectedKey} onChange={e=>onSelectedKeyChange(e.target.value)} aria-label="Change class and subject" style={{width:"100%",height:36,appearance:"none",border:0,background:"transparent",paddingRight:30,fontSize:14,fontWeight:900,color:"#111827",fontFamily:"inherit",opacity:contextRefreshing?.65:1}}>{options.map(i=><option key={key(i.class_id,i.subject_id)} value={key(i.class_id,i.subject_id)}>{i.class_name} · {i.subject}</option>)}</select><span style={{pointerEvents:"none",position:"absolute",right:0,top:10}}><Chevron/></span></span>{contextRefreshing?<span style={{display:"block",fontSize:11,color:"#047857",fontWeight:800}}>Refreshing this class…</span>:!slot&&roster?<button type="button" onClick={()=>router.push(`/teacher/classhub/${roster.class_id}`)} style={{border:0,background:"transparent",padding:0,color:"#047857",fontSize:11,fontWeight:800}}>No lesson today · Open class</button>:slot?<span style={{display:"block",fontSize:11,color:"#6b7280"}}>Today · {slot.start_time}–{slot.end_time}</span>:null}</span></label>:<button onClick={()=>router.push("/teacher/onboarding/class")} style={{border:0,background:"transparent",fontWeight:900}}>No classes assigned · Add class</button>}</section></header>
}