"use client";

import { useEffect, useMemo, useState } from "react";
import { useRouter } from "next/navigation";
import { supabase } from "@/lib/supabase";
import type { PulseSnapshot } from "@/lib/types";

const WEEK_TYPE_LABELS: Record<string, string> = { exam: "Exams", midterm_break: "Mid-Term Break", sports: "Sports", holiday: "Holiday" };
const iconProps = { width: 18, height: 18, viewBox: "0 0 24 24", fill: "none", stroke: "currentColor", strokeWidth: 2, strokeLinecap: "round" as const, strokeLinejoin: "round" as const };
function IconBell(){return <svg {...iconProps}><path d="M6 8a6 6 0 0 1 12 0c0 3 1 5 1.5 6H4.5C5 13 6 11 6 8z"/><path d="M10 20a2 2 0 0 0 4 0"/></svg>}
function IconClass(){return <svg {...iconProps}><circle cx="9" cy="8" r="3"/><path d="M3.5 19a5.5 5.5 0 0 1 11 0"/><path d="M16 6a3 3 0 0 1 0 6"/><path d="M17.5 14.5A5 5 0 0 1 21 19"/></svg>}
function IconChevron(){return <svg width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.2" strokeLinecap="round" strokeLinejoin="round"><path d="M6 9l6 6 6-6"/></svg>}
function greeting(){const h=new Date().getHours();return h<12?"Good morning":h<17?"Good afternoon":"Good evening"}

export default function PulseHeader({snap,name,selectedKey,onSelectedKeyChange,onOpenNotifications,offline=false,contextRefreshing=false}:{snap:PulseSnapshot;name:string;avatarUrl?:string;selectedKey:string;onSelectedKeyChange:(key:string)=>void;onOpenNotifications?:()=>void;schools?:{id:string;name:string}[];activeSchoolId?:string|null;onSchoolChange?:(id:string)=>void;offline?:boolean;contextRefreshing?:boolean}){
 const router=useRouter(); const [unread,setUnread]=useState(0);
 useEffect(()=>{let cancelled=false;supabase.from("notifications").select("id",{count:"exact",head:true}).eq("user_id",snap.userId).eq("is_read",false).then(({count})=>{if(!cancelled)setUnread(count??0)});return()=>{cancelled=true}},[snap.userId]);
 const keyOf=(c:string,s:string)=>`${c}::${s}`; const [classId,subjectId]=selectedKey.split("::");
 const selectedSlot=snap.todaySlots.find(s=>s.class_id===classId&&s.subject_id===subjectId); const selectedRoster=snap.myClasses.find(i=>i.class_id===classId&&i.subject_id===subjectId);
 const dateLabel=new Date().toLocaleDateString("en-KE",{weekday:"short",day:"numeric",month:"short"});
 const weekLabel=snap.weekNumber==null?"No active term":snap.weekType&&snap.weekType!=="normal"?`Term ${snap.termNumber??"—"} · Week ${snap.weekNumber} · ${WEEK_TYPE_LABELS[snap.weekType]??snap.weekType}`:`Term ${snap.termNumber??"—"} · Week ${snap.weekNumber}`;
 const options=useMemo(()=>[...snap.myClasses].sort((a,b)=>`${a.class_name} ${a.subject}`.localeCompare(`${b.class_name} ${b.subject}`)),[snap.myClasses]);
 return <header style={{marginBottom:14}}>
  <div style={{display:"flex",alignItems:"center",justifyContent:"space-between",gap:12,marginBottom:12}}><div style={{minWidth:0}}><h1 style={{margin:0,fontSize:20,fontWeight:900,color:"#111827",letterSpacing:-.35,lineHeight:1.2}}>{greeting()}{name?`, ${name}`:""}</h1><div style={{display:"flex",gap:7,marginTop:4,fontSize:12,color:"#6b7280",flexWrap:"wrap"}}><span>{dateLabel}</span><span>·</span><span>{weekLabel}</span>{offline&&<><span>·</span><span style={{color:"#92400e",fontWeight:800}}>Offline snapshot</span></>}</div></div><button type="button" onClick={()=>{onOpenNotifications?.();router.push("/teacher/notifications")}} aria-label={unread?`${unread} unread notifications`:"Open notifications"} style={{position:"relative",width:44,height:44,border:"1px solid #e5e7eb",borderRadius:14,background:"#fff",color:"#374151",display:"flex",alignItems:"center",justifyContent:"center",cursor:"pointer"}}><IconBell/>{unread>0&&<span style={{position:"absolute",top:-4,right:-4,minWidth:18,height:18,borderRadius:999,background:"#dc2626",color:"#fff",fontSize:9,fontWeight:900,display:"flex",alignItems:"center",justifyContent:"center",border:"2px solid #fff"}}>{unread>9?"9+":unread}</span>}</button></div>
  <section style={{background:"#fff",border:"1px solid #e5e7eb",borderRadius:18,padding:12,boxShadow:"0 2px 10px rgba(15,23,42,.045)"}} aria-label="Teaching context">
   {options.length>0?<label style={{display:"flex",alignItems:"center",gap:11,minWidth:0}}><span style={{width:36,height:36,borderRadius:12,background:"#ecfdf5",color:"#047857",display:"flex",alignItems:"center",justifyContent:"center",flexShrink:0}}><IconClass/></span><span style={{minWidth:0,flex:1}}><span style={{display:"block",fontSize:10,color:"#6b7280",fontWeight:900,textTransform:"uppercase",letterSpacing:.8}}>Teaching context</span><span style={{position:"relative",display:"block",marginTop:2}}><select disabled={contextRefreshing} value={selectedKey} onChange={e=>onSelectedKeyChange(e.target.value)} aria-label="Change class and subject" style={{width:"100%",minHeight:34,appearance:"none",border:0,outline:0,background:"transparent",padding:"0 30px 0 0",fontSize:14,fontWeight:900,color:"#111827",fontFamily:"inherit",opacity:contextRefreshing?.65:1}}>{options.map(i=><option key={keyOf(i.class_id,i.subject_id)} value={keyOf(i.class_id,i.subject_id)}>{i.class_name} · {i.subject}</option>)}</select><span style={{pointerEvents:"none",position:"absolute",right:0,top:9,color:"#6b7280"}}><IconChevron/></span></span>{contextRefreshing?<span role="status" style={{display:"block",marginTop:4,fontSize:11,color:"#047857",fontWeight:800}}>Refreshing this class…</span>:!selectedSlot&&selectedRoster?<button type="button" onClick={()=>router.push(`/teacher/classhub/${selectedRoster.class_id}`)} style={{marginTop:4,border:0,background:"transparent",padding:0,color:"#047857",fontSize:11,fontWeight:800,fontFamily:"inherit"}}>No lesson today · Open class</button>:selectedSlot?<span style={{display:"block",marginTop:4,fontSize:11,color:"#6b7280"}}>Today · {selectedSlot.start_time}–{selectedSlot.end_time}</span>:null}</span></label>:<button type="button" onClick={()=>router.push("/teacher/onboarding/class")} style={{width:"100%",minHeight:54,border:0,background:"transparent",textAlign:"left",fontFamily:"inherit"}}><strong>No classes assigned</strong><span style={{display:"block",fontSize:11,color:"#047857",marginTop:3}}>Add your class</span></button>}
  </section>
 </header>
}