"use client"
export const dynamic = "force-dynamic"

import { useCallback, useEffect, useMemo, useState } from "react"
import { useRouter } from "next/navigation"
import { supabase } from "@/lib/supabase"
import HQTwinDrawer from "@/components/hq/TwinDrawer"
import HQNotificationCenter from "@/components/hq/NotificationCenter"
import HQExecutiveAnalytics from "@/components/hq/ExecutiveAnalytics"
import { loadHQMorningBrief, loadHQNotifications, loadHQSnapshot, runHQRules, type HQMorningBrief, type HQNotification, type HQSnapshot } from "@/lib/hq/operating"

const C={bg:"#07111f",panel:"#0d1b2f",border:"rgba(255,255,255,.08)",text:"#f8fafc",muted:"rgba(255,255,255,.45)",green:"#34d399",blue:"#60a5fa",amber:"#f59e0b",red:"#ef4444",violet:"#a78bfa"}
function fmt(v:number){return new Intl.NumberFormat("en-KE").format(v??0)}
function age(iso:string){const m=Math.max(0,Math.floor((Date.now()-new Date(iso).getTime())/60000));if(m<1)return"now";if(m<60)return`${m}m ago`;if(m<1440)return`${Math.floor(m/60)}h ago`;return`${Math.floor(m/1440)}d ago`}
function Metric({value,label,note,tone=C.green}:{value:number|string;label:string;note?:string;tone?:string}){return <div style={{border:`1px solid ${C.border}`,background:"rgba(255,255,255,.025)",borderRadius:15,padding:"14px 15px"}}><div style={{fontSize:24,lineHeight:1,fontWeight:900,color:tone}}>{typeof value==="number"?fmt(value):value}</div><div style={{marginTop:7,fontSize:11.5,color:C.text,fontWeight:750}}>{label}</div>{note&&<div style={{marginTop:4,fontSize:10.5,color:C.muted}}>{note}</div>}</div>}
function Section({title,children,action}:{title:string;children:React.ReactNode;action?:React.ReactNode}){return <section style={{marginTop:22}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginBottom:9}}><div style={{fontSize:10.5,fontWeight:900,color:"rgba(255,255,255,.34)",textTransform:"uppercase",letterSpacing:".08em"}}>{title}</div>{action}</div>{children}</section>}

export default function HQOperatingPage(){const router=useRouter();const[snapshot,setSnapshot]=useState<HQSnapshot|null>(null);const[brief,setBrief]=useState<HQMorningBrief|null>(null);const[activity,setActivity]=useState<HQNotification[]>([]);const[loading,setLoading]=useState(true);const[error,setError]=useState("");const[twinOpen,setTwinOpen]=useState(false);const[runningRules,setRunningRules]=useState(false)
 const refresh=useCallback(async(runRules=false)=>{setError("");try{if(runRules)await runHQRules();const[s,n,b]=await Promise.all([loadHQSnapshot(),loadHQNotifications(12),loadHQMorningBrief()]);setSnapshot(s);setActivity(n);setBrief(b)}catch(e){setError(e instanceof Error?e.message:"HQ data could not be loaded.")}finally{setLoading(false)}},[])
 useEffect(()=>{void refresh(true)},[refresh]);const attention=useMemo(()=>activity.filter(i=>i.severity==="critical"||i.severity==="warning").slice(0,4),[activity]);async function executeRules(){setRunningRules(true);try{await refresh(true)}finally{setRunningRules(false)}}async function signOut(){await supabase.auth.signOut();router.replace("/hq/login")}
 if(loading&&!snapshot)return <main style={{minHeight:"100dvh",background:C.bg,color:C.text,display:"grid",placeItems:"center",fontFamily:"Inter,system-ui,sans-serif"}}>Loading HQ operating state…</main>
 const h=brief?.headline
 return <main style={{minHeight:"100dvh",background:C.bg,color:C.text,fontFamily:"Inter,system-ui,sans-serif"}}><div style={{maxWidth:1180,margin:"0 auto",padding:"0 18px 70px"}}>
  <header style={{position:"sticky",top:0,zIndex:50,margin:"0 -18px",padding:"14px 18px",background:"rgba(7,17,31,.94)",backdropFilter:"blur(16px)",borderBottom:`1px solid ${C.border}`}}><div style={{maxWidth:1180,margin:"0 auto",display:"flex",alignItems:"center",gap:10}}><div style={{flex:1}}><div style={{fontSize:18,fontWeight:950}}>VibeSchool HQ</div><div style={{fontSize:10.5,color:C.muted,marginTop:2}}>Company command center · decisions · operations · deterministic intelligence</div></div><button onClick={()=>router.push("/hq/decisions")}>Boardroom</button><button onClick={()=>router.push("/hq/departments")}>Company</button><button onClick={()=>void refresh(false)}>Refresh</button><HQNotificationCenter unread={snapshot?.notifications.unread??0} onChange={()=>void refresh(false)}/><button onClick={signOut}>Sign out</button></div></header>
  {error&&<div style={{marginTop:16,padding:"12px 14px",borderRadius:12,border:"1px solid rgba(239,68,68,.28)",background:"rgba(239,68,68,.08)",color:"#fca5a5",fontSize:12}}>{error}</div>}
  {brief&&<Section title="Executive brief"><div style={{background:C.panel,border:`1px solid ${C.border}`,borderRadius:16,padding:14}}><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(120px,1fr))",gap:7}}>{[[h?.new_users_today??0,"New users"],[h?.active_schools??0,"Active schools"],[h?.lesson_plans_today??0,"Lesson plans"],[h?.submissions_today??0,"Submissions"],[h?.open_incidents??0,"Incidents"],[h?.decisions_waiting??0,"Decisions waiting"],[h?.work_waiting_approval??0,"Approvals"]].map(([v,l])=><div key={String(l)} style={{padding:9,borderRadius:10,background:"rgba(255,255,255,.025)",border:`1px solid ${C.border}`}}><div style={{fontSize:16,fontWeight:900}}>{v}</div><div style={{fontSize:9.5,color:C.muted,marginTop:3}}>{l}</div></div>)}</div>{brief.priorities.length>0&&<div style={{marginTop:12}}>{brief.priorities.slice(0,4).map((p,i)=><button key={`${p.department}-${i}`} onClick={()=>p.route&&router.push(p.route)} style={{display:"flex",width:"100%",gap:8,padding:"8px 0",border:0,borderTop:i?`1px solid ${C.border}`:0,background:"transparent",color:C.text,textAlign:"left",cursor:p.route?"pointer":"default"}}><span style={{fontSize:9.5,fontWeight:900,color:p.priority==="critical"?C.red:p.priority==="high"?C.amber:C.blue,textTransform:"uppercase",minWidth:52}}>{p.priority}</span><span style={{fontSize:10.5,flex:1}}>{p.title}</span><span style={{fontSize:9.5,color:C.muted}}>{p.department}</span></button>)}</div>}</div></Section>}
  <Section title="Company pulse"><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(145px,1fr))",gap:9}}><Metric value={snapshot?.users.today??0} label="New users today" note={`${fmt(snapshot?.users.total??0)} total users`}/><Metric value={snapshot?.schools.active??0} label="Active schools" note={`${fmt(snapshot?.schools.total??0)} total schools`} tone={C.blue}/><Metric value={snapshot?.teaching.lesson_plans_today??0} label="Lesson plans today" note={`${fmt(snapshot?.teaching.lesson_plans_7d??0)} in 7 days`} tone={C.violet}/><Metric value={snapshot?.teaching.lessons_taught_today??0} label="Lessons taught today"/><Metric value={snapshot?.teaching.submissions_today??0} label="Submissions today" tone={C.blue}/><Metric value={snapshot?.events.last_hour??0} label="Platform events / hour" note={`${fmt(snapshot?.events.today??0)} today`} tone={C.amber}/></div></Section>
  <section id="analytics"><Section title="Executive analytics"><HQExecutiveAnalytics/></Section></section>
  <Section title="Digital company"><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(210px,1fr))",gap:9}}><button onClick={()=>router.push("/hq/departments")} style={{padding:14,textAlign:"left",borderRadius:14,border:`1px solid ${C.green}44`,background:`${C.green}08`,color:C.text,cursor:"pointer"}}><div style={{fontWeight:900,fontSize:12.5,color:C.green}}>16 operating departments</div><div style={{fontSize:10.5,color:C.muted,marginTop:4}}>Executive, Finance, Technology, Operations, Product, Growth, Support, Content, People, Trust, Marketing, Procurement, Programs, Data, Quality and Knowledge.</div></button><button onClick={()=>router.push("/hq/decisions")} style={{padding:14,textAlign:"left",borderRadius:14,border:`1px solid ${C.violet}44`,background:`${C.violet}08`,color:C.text,cursor:"pointer"}}><div style={{fontWeight:900,fontSize:12.5,color:C.violet}}>Boardroom authority</div><div style={{fontSize:10.5,color:C.muted,marginTop:4}}>Approve, lock, schedule, propagate, verify, amend and audit company decisions.</div></button></div></Section>
  <Section title="Teaching operations"><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(145px,1fr))",gap:9}}><Metric value={snapshot?.users.teachers??0} label="Registered teachers"/><Metric value={snapshot?.users.learners??0} label="Learners" tone={C.blue}/><Metric value={snapshot?.teaching.homework_today??0} label="Homework assigned today" tone={C.violet}/><Metric value={snapshot?.teaching.unreviewed_submissions??0} label="Awaiting review" tone={(snapshot?.teaching.unreviewed_submissions??0)>=50?C.amber:C.green}/></div></Section>
  <Section title="Content operations" action={<button onClick={()=>router.push("/hq/studio")} style={{border:0,background:"transparent",color:C.green,fontSize:11,fontWeight:850,cursor:"pointer"}}>Open content studio →</button>}><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(145px,1fr))",gap:9}}><Metric value={snapshot?.content.publications_live??0} label="Published"/><Metric value={snapshot?.content.publications_draft??0} label="Draft publications" tone={C.amber}/><Metric value={snapshot?.content.publications_total??0} label="All publications" tone={C.blue}/><Metric value={snapshot?.content.reads_total??0} label="Publication reads" tone={C.violet}/></div></Section>
  <Section title="Needs attention" action={<button disabled={runningRules} onClick={()=>void executeRules()}>{runningRules?"Checking…":"Run rules"}</button>}><div style={{border:`1px solid ${C.border}`,borderRadius:15,background:"rgba(255,255,255,.02)",overflow:"hidden"}}>{attention.length===0?<div style={{padding:20,color:C.muted,fontSize:12}}>No deterministic warnings are active.</div>:attention.map((item,i)=><button key={item.id} onClick={()=>item.route&&router.push(item.route)} style={{width:"100%",border:0,borderBottom:i<attention.length-1?`1px solid ${C.border}`:0,padding:"13px 14px",background:"transparent",color:C.text,textAlign:"left",display:"flex",gap:11}}><span style={{width:9,height:9,marginTop:4,borderRadius:10,background:item.severity==="critical"?C.red:C.amber}}/><span style={{flex:1}}><span style={{display:"block",fontSize:12.5,fontWeight:850}}>{item.title}</span><span style={{display:"block",fontSize:11,color:C.muted,marginTop:3}}>{item.body}</span></span><span style={{fontSize:10,color:C.muted}}>{age(item.created_at)}</span></button>)}</div></Section>
  <Section title="HQ controls"><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(180px,1fr))",gap:9}}><button onClick={()=>router.push("/hq/decisions")}>Boardroom</button><button onClick={()=>router.push("/hq/departments")}>Digital Company</button><button onClick={()=>router.push("/hq/studio")}>Content Studio</button><button onClick={()=>setTwinOpen(true)}>HQ Twin</button></div></Section>
 </div><HQTwinDrawer open={twinOpen} onClose={()=>setTwinOpen(false)}/></main>
}
