"use client"
export const dynamic = "force-dynamic"

import { useCallback, useEffect, useMemo, useState } from "react"
import { useRouter } from "next/navigation"
import { supabase } from "@/lib/supabase"
import HQTwinDrawer from "@/components/hq/TwinDrawer"
import { HQPage, HQPanel, HQ_THEME as C, hqButtonStyle } from "@/components/hq/HQShell"
import { clearAllHQOfflineData, isHQOnline, readHQCache, saveHQCache } from "@/lib/hq/offline"

type Json = null | boolean | number | string | Json[] | { [key: string]: Json }
type Control = { product_key:string; policy_key:string; desired_value:Json; observed_value:Json; state:string; verified_at?:string|null; last_error?:string|null }
type Report = Record<string, any>
type CommandCache={report:Report|null;controls:Control[];health:Report|null;actionableDecisions:number}
const sb = supabase as any
const labelize=(s:string)=>s.replaceAll("_"," ").replace(/\b\w/g,m=>m.toUpperCase())
const fmt=(n:unknown)=>typeof n==="number"?new Intl.NumberFormat("en-KE").format(n):String(n??"—")
function Card({title,value,note,tone=C.green}:{title:string;value:unknown;note?:string;tone?:string}){return <div style={{border:`1px solid ${C.border}`,borderRadius:15,padding:14,background:C.panelSoft}}><div style={{fontSize:24,fontWeight:950,color:tone}}>{fmt(value)}</div><div style={{fontSize:11.5,fontWeight:800,marginTop:6}}>{title}</div>{note&&<div style={{fontSize:10.5,color:C.muted,marginTop:4}}>{note}</div>}</div>}
function displayValue(v:unknown){if(v==null)return "—";if(typeof v!=="object")return String(v);if(Array.isArray(v))return v.map(x=>typeof x==="object"?Object.values(x as Record<string,unknown>).filter(y=>typeof y!=="object").join(" · "):String(x)).join("\n");return Object.entries(v as Record<string,unknown>).map(([k,x])=>`${labelize(k)}: ${typeof x==="object"?JSON.stringify(x):String(x??"—")}`).join("\n")}
function JsonList({value,empty="Nothing requires attention."}:{value:unknown;empty?:string}){if(!value||(Array.isArray(value)&&value.length===0)||(typeof value==="object"&&!Array.isArray(value)&&Object.keys(value as object).length===0))return <div style={{padding:14,color:C.muted,fontSize:12}}>{empty}</div>;if(Array.isArray(value))return <div>{value.map((item,i)=><div key={i} style={{padding:"11px 14px",borderTop:i?`1px solid ${C.border}`:0,fontSize:11.5,lineHeight:1.55,whiteSpace:"pre-wrap"}}>{displayValue(item)}</div>)}</div>;if(typeof value==="object")return <div>{Object.entries(value as Record<string,unknown>).map(([k,v],i)=><div key={k} className="hq-mobile-stack" style={{padding:"10px 14px",borderTop:i?`1px solid ${C.border}`:0,fontSize:11.5}}><strong>{labelize(k)}</strong><span style={{color:C.muted,overflowWrap:"anywhere",whiteSpace:"pre-wrap"}}>{displayValue(v)}</span></div>)}</div>;return <div style={{padding:14,fontSize:12}}>{String(value)}</div>}
export default function HQCommandCenter(){
 const router=useRouter();const[report,setReport]=useState<Report|null>(null);const[controls,setControls]=useState<Control[]>([]);const[health,setHealth]=useState<Report|null>(null);const[loading,setLoading]=useState(true);const[error,setError]=useState("");const[busy,setBusy]=useState("");const[twinOpen,setTwinOpen]=useState(false);const[actionableDecisions,setActionableDecisions]=useState(0);const[pending,setPending]=useState<Control|null>(null);const[reason,setReason]=useState("");const[cachedAt,setCachedAt]=useState<number|null>(null)
 const applyCache=useCallback(()=>{const cached=readHQCache<CommandCache>('command-center');if(!cached)return false;setReport(cached.value.report);setControls(cached.value.controls);setHealth(cached.value.health);setActionableDecisions(cached.value.actionableDecisions);setCachedAt(cached.savedAt);setLoading(false);return true},[])
 const refresh=useCallback(async()=>{setError("");try{const[r,c,h,d]=await Promise.all([sb.rpc("hq_get_seven_day_owner_report"),sb.rpc("hq_get_product_controls"),sb.rpc("hq_get_control_health_v2"),sb.rpc("hq_workforce_list_decisions",{p_status:"actionable",p_limit:100})]);for(const result of[r,c,h,d])if(result.error)throw result.error;const next={report:r.data as Report,controls:(c.data??[])as Control[],health:h.data as Report,actionableDecisions:Array.isArray(d.data)?d.data.length:0};setReport(next.report);setControls(next.controls);setHealth(next.health);setActionableDecisions(next.actionableDecisions);setCachedAt(null);saveHQCache('command-center',next)}catch(e){const restored=applyCache();setError(restored?"Live HQ is unavailable. Showing the last-known certified snapshot.":e instanceof Error?e.message:"HQ operating state could not be loaded.")}finally{setLoading(false)}},[applyCache])
 useEffect(()=>{if(!isHQOnline())applyCache();void refresh()},[applyCache,refresh]);const q=report?.executive_questions??{};const headline=report?.executive_dashboard?.headline??report?.executive_dashboard?.headline_metrics??{};const finance=report?.finance??{};const certs=(health?.runtime_certifications??[])as Report[];const passing=certs.filter(c=>c.result==="pass").length;const controlsByProduct=useMemo(()=>[...controls].sort((a,b)=>a.product_key.localeCompare(b.product_key)),[controls])
 async function confirmPolicy(){if(!pending||!reason.trim())return;if(!isHQOnline()){setError("Reconnect before changing product authority.");return}const next=pending.desired_value!==true;const id=`${pending.product_key}:${pending.policy_key}`;setBusy(id);try{const{error}=await sb.rpc("hq_set_product_policy",{p_product_key:pending.product_key,p_policy_key:pending.policy_key,p_value:next,p_reason:reason.trim()});if(error)throw error;setPending(null);setReason("");await refresh()}catch(e){setError(e instanceof Error?e.message:"Policy change failed.")}finally{setBusy("")}}
 async function runCycle(){if(!isHQOnline()){setError("Reconnect before running the operating cycle.");return}setBusy("cycle");try{const{error}=await sb.rpc("hq_run_operating_cycle");if(error)throw error;await refresh()}catch(e){setError(e instanceof Error?e.message:"Operating cycle failed.")}finally{setBusy("")}}
 async function signOut(){clearAllHQOfflineData();await supabase.auth.signOut();router.replace("/hq/login")}
 if(loading&&!report)return <main className="hq-page" style={{display:"grid",placeItems:"center"}}>Loading live HQ…</main>
 return <><HQPage title="VibeSchool HQ" description="Owner command center · live company state" actions={<><button onClick={()=>router.push("/hq/decisions")} style={{...hqButtonStyle,color:actionableDecisions?C.amber:C.green}}>Decisions{actionableDecisions?` · ${actionableDecisions}`:""}</button><button onClick={()=>void refresh()} style={hqButtonStyle}>Refresh</button><button onClick={()=>void runCycle()} disabled={busy==="cycle"} style={hqButtonStyle}>{busy==="cycle"?"Running…":"Run cycle"}</button><button onClick={()=>setTwinOpen(true)} style={hqButtonStyle}>HQ Twin</button><button onClick={()=>void signOut()} style={{...hqButtonStyle,color:C.red}}>Sign out</button></>}>
 {cachedAt&&<div style={{marginBottom:12,fontSize:10.5,color:C.amber}}>Last-known snapshot from {new Date(cachedAt).toLocaleString("en-KE")}</div>}{error&&<div role="alert" style={{marginBottom:14,padding:12,borderRadius:11,border:"1px solid rgba(251,113,133,.3)",background:"rgba(251,113,133,.08)",color:"#fecdd3",fontSize:12}}>{error}</div>}
 <section><div style={sectionTitle}>Company now</div><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(145px,1fr))",gap:9}}><Card title="DAU" value={headline.dau??report?.company_period?.daily?.at?.(-1)?.metrics?.dau??0}/><Card title="WAU" value={headline.wau??0} tone={C.blue}/><Card title="MAU" value={headline.mau??0} tone={C.violet}/><Card title="Open incidents" value={headline.open_incidents??0} tone={(headline.open_incidents??0)>0?C.red:C.green}/><Card title="Open findings" value={headline.open_findings??0} tone={(headline.open_findings??0)>0?C.amber:C.green}/><Card title="Outstanding work" value={headline.open_work??0} tone={(headline.open_work??0)>0?C.amber:C.green}/><Card title="Founder decisions" value={actionableDecisions} tone={actionableDecisions?C.amber:C.green}/></div></section>
 <section style={{marginTop:24}}><div style={sectionTitle}>Owner questions</div><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(min(100%,320px),1fr))",gap:10}}>{[["What happened?",q.what_happened],["What grew?",q.what_grew],["What declined?",q.what_declined],["What broke?",q.what_broke],["Why?",q.why],["Who owns it?",q.who_owns_it],["What decision is required?",q.what_decision_is_required],["What was automatically done?",q.what_was_automatically_done],["Did it work?",q.did_it_work]].map(([title,value])=><HQPanel key={String(title)} title={String(title)}><JsonList value={value}/></HQPanel>)}</div></section>
 <section style={{marginTop:24}}><div style={sectionTitle}>Product authority</div><HQPanel>{controlsByProduct.length===0?<JsonList value={null} empty="No product controls configured."/>:controlsByProduct.map((c,i)=>{const enabled=c.desired_value===true;const id=`${c.product_key}:${c.policy_key}`;return <div key={id} className="hq-mobile-stack" style={{padding:"12px 14px",borderTop:i?`1px solid ${C.border}`:0}}><div><div style={{fontSize:12,fontWeight:900}}>{labelize(c.product_key)}</div><div style={{fontSize:10,color:C.muted,marginTop:3}}>{c.policy_key} · <span style={{color:c.state==="verified"?C.green:c.state==="drift"?C.red:C.amber}}>{labelize(c.state)}</span></div>{c.verified_at&&<div style={{fontSize:9.5,color:C.muted,marginTop:3}}>Verified {new Date(c.verified_at).toLocaleString("en-KE")}</div>}</div><div className="hq-action-row"><span className="hq-status" style={{color:enabled?C.green:C.red}}>{enabled?"Enabled":"Disabled"}</span><button onClick={()=>{if(!isHQOnline()){setError("Reconnect before changing product authority.");return}setPending(c);setReason("")}} disabled={busy===id} style={{...hqButtonStyle,color:enabled?C.red:C.green}}>{enabled?"Disable":"Enable"}</button></div></div>})}</HQPanel></section>
 <section style={{marginTop:24,display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(min(100%,300px),1fr))",gap:10}}><HQPanel title="Control health"><JsonList value={{verified:health?.verified_states??0,pending:health?.pending_states??0,drifted:health?.drifted_states??0,failed:health?.failed_states??0,policy_failures_24h:health?.policy_failures_24h??0,runtime_certifications_pass:passing}}/></HQPanel><HQPanel title="Finance truth"><JsonList value={finance}/></HQPanel><HQPanel title="Product engagement"><JsonList value={report?.product_engagement}/></HQPanel></section>
 <section style={{marginTop:24}}><div style={sectionTitle}>Runtime certification evidence</div><HQPanel><JsonList value={certs.slice(0,15)} empty="No runtime certifications recorded."/></HQPanel></section><footer style={{marginTop:22,textAlign:"center",fontSize:10,color:"rgba(255,255,255,.28)"}}>Generated {report?.generated_at?new Date(report.generated_at).toLocaleString("en-KE"):"—"} · Source-backed HQ</footer>
 </HQPage><HQTwinDrawer open={twinOpen} onClose={()=>setTwinOpen(false)}/>{pending&&<div role="dialog" aria-modal="true" aria-labelledby="policy-dialog-title" style={{position:"fixed",inset:0,zIndex:200,display:"grid",placeItems:"center",padding:18,background:"rgba(2,6,23,.78)"}}><div style={{width:"min(100%,480px)",border:`1px solid ${C.border}`,borderRadius:16,background:C.panel,padding:18,color:C.text}}><h2 id="policy-dialog-title" style={{margin:"0 0 6px",fontSize:17}}>{pending.desired_value===true?"Disable":"Enable"} {labelize(pending.product_key)}</h2><p style={{margin:"0 0 14px",fontSize:11.5,lineHeight:1.5,color:C.muted}}>This changes live product authority. Record the operational reason before publishing the policy.</p><textarea autoFocus value={reason} onChange={e=>setReason(e.target.value)} placeholder="Reason for this change" rows={4} style={{width:"100%",boxSizing:"border-box",resize:"vertical",borderRadius:10,border:`1px solid ${C.border}`,background:"rgba(255,255,255,.04)",color:C.text,padding:10,font:"inherit"}}/><div className="hq-action-row" style={{justifyContent:"flex-end",marginTop:12}}><button onClick={()=>{setPending(null);setReason("")}} style={hqButtonStyle}>Cancel</button><button onClick={()=>void confirmPolicy()} disabled={!reason.trim()||Boolean(busy)} style={{...hqButtonStyle,color:pending.desired_value===true?C.red:C.green}}>Confirm change</button></div></div></div>}</>
}
const sectionTitle:React.CSSProperties={fontSize:10.5,fontWeight:950,color:"rgba(255,255,255,.4)",letterSpacing:".09em",textTransform:"uppercase",marginBottom:9}
