"use client";
export const dynamic = "force-dynamic";

import { useEffect, useState } from "react";
import { useParams, useRouter } from "next/navigation";
import { supabase } from "@/lib/supabase";
import { TOKENS } from "@/lib/tokens";

interface Submission { status:string; mark:number|null; feedback:string|null; photo_url:string|null }
interface Child { student_id:string; student_name:string; submission:Submission|null }
interface Payload { homework:{id:string;title:string;subject:string;instructions:string|null;due_date:string;type:string;teacher_name:string}; children:Child[] }
function autoBandLabel(mark:number){if(mark>=80)return "Excellent";if(mark>=60)return "Good";if(mark>=40)return "Fair";return "Needs Improvement"}
function daysUntil(d:string){const t=new Date();t.setHours(0,0,0,0);const due=new Date(d);due.setHours(0,0,0,0);return Math.round((due.getTime()-t.getTime())/86400000)}
function dueBadge(due:string,status:string){if(status==="marked")return{label:"Marked",bg:"#d1fae5",color:"#065f46"};if(status==="submitted"||status==="received"||status==="under_review")return{label:"Submitted",bg:"#dbeafe",color:"#1e40af"};const n=daysUntil(due);if(n<0)return{label:"Overdue",bg:"#fee2e2",color:"#991b1b"};if(n===0)return{label:"Due Today",bg:"#fef3c7",color:"#92400e"};if(n===1)return{label:"Due Tomorrow",bg:"#fff7ed",color:"#c2410c"};return{label:`Due in ${n}d`,bg:"#f0fdf4",color:"#166534"}}

export default function ParentHomeworkDetailPage(){
  const {id}=useParams<{id:string}>();const router=useRouter();const[payload,setPayload]=useState<Payload|null>(null);const[loading,setLoading]=useState(true);const[error,setError]=useState("");
  useEffect(()=>{if(!id)return;let cancelled=false;(async()=>{const{data,error:rpcError}=await supabase.rpc("get_parent_homework_detail",{p_homework_id:id});if(cancelled)return;if(rpcError){setError(rpcError.message.toLowerCase().includes("authorized")?"You don't have access to this homework.":"We couldn't load this homework.");setLoading(false);return}setPayload(data as Payload);setLoading(false)})().catch(()=>{if(!cancelled){setError("We couldn't load this homework.");setLoading(false)}});return()=>{cancelled=true}},[id]);
  if(loading)return <div style={{padding:24,textAlign:"center",color:TOKENS.textMuted,fontFamily:TOKENS.fontFamily}}>Loading…</div>;
  if(error||!payload)return <div style={{padding:24,textAlign:"center",color:TOKENS.textMuted,fontFamily:TOKENS.fontFamily}}>{error||"Assignment not found."}<div style={{marginTop:12}}><button onClick={()=>router.back()} style={{border:"none",borderRadius:10,padding:"10px 14px",background:"#1e1b4b",color:"#fff",fontWeight:800}}>Back</button></div></div>;
  const hw=payload.homework;const child=payload.children[0];const sub=child?.submission??null;const badge=dueBadge(hw.due_date,sub?.status??"pending");
  return <div style={{maxWidth:480,margin:"0 auto",padding:"20px 16px 100px",fontFamily:TOKENS.fontFamily,color:TOKENS.textPrimary}}>
    <button onClick={()=>router.back()} style={{display:"flex",alignItems:"center",gap:6,background:"none",border:"none",cursor:"pointer",color:TOKENS.textMuted,fontSize:13,fontWeight:600,marginBottom:16,padding:0,fontFamily:"inherit"}}>← Back</button>
    <div style={{background:"linear-gradient(135deg,#1e1b4b,#312e81)",borderRadius:16,padding:16,marginBottom:16,color:"#fff"}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"flex-start",gap:8,marginBottom:10}}><h1 style={{fontSize:17,fontWeight:800,color:"#fff",lineHeight:1.3,margin:0,flex:1}}>{hw.title}</h1><span style={{padding:"4px 10px",borderRadius:20,background:badge.bg,color:badge.color,fontSize:10,fontWeight:700,flexShrink:0}}>{badge.label}</span></div><div style={{fontSize:12,color:"rgba(255,255,255,.65)"}}>{hw.subject} · {hw.teacher_name} · Due {new Date(hw.due_date).toLocaleDateString("en-KE",{day:"numeric",month:"short"})}</div>{child?.student_name&&<div style={{marginTop:6,fontSize:11,color:"rgba(255,255,255,.5)"}}>👤 {child.student_name}</div>}</div>
    {hw.instructions&&<div style={section}><div style={label}>Instructions</div><p style={{fontSize:13,lineHeight:1.7,margin:0}}>{hw.instructions}</p></div>}
    {!sub?<div style={warning}><div style={{fontSize:13,fontWeight:800,color:"#92400e"}}>Not submitted yet</div><div style={{fontSize:12,color:"#b45309",marginTop:4}}>Remind {child?.student_name||"your child"} to complete and submit this.</div></div>:sub.status==="marked"?<div style={success}><div style={label}>Teacher Feedback</div>{sub.mark!==null&&<div style={{fontSize:22,fontWeight:800,color:"#166534",marginBottom:4}}>{sub.mark} marks · <span style={{fontSize:15}}>{autoBandLabel(sub.mark)}</span></div>}{sub.feedback&&<p style={{fontSize:13,lineHeight:1.6,margin:0}}>{sub.feedback}</p>}</div>:<div style={info}><div style={{fontSize:13,fontWeight:800,color:"#1e40af"}}>✅ Submitted — waiting for teacher to mark</div></div>}
    {sub?.photo_url&&<div style={section}><div style={label}>Submitted Work</div><img src={sub.photo_url} alt="Submitted work" style={{width:"100%",borderRadius:10,objectFit:"cover",maxHeight:320}}/></div>}
  </div>
}
const section:React.CSSProperties={background:"#fff",border:"1px solid #e5e7eb",borderRadius:14,padding:"14px 16px",marginBottom:14};const label:React.CSSProperties={fontSize:11,fontWeight:800,color:TOKENS.textMuted,textTransform:"uppercase",letterSpacing:.8,marginBottom:8};const warning:React.CSSProperties={background:"#fef3c7",border:"1px solid #fcd34d",borderRadius:14,padding:"14px 16px",marginBottom:14};const success:React.CSSProperties={background:"#f0fdf4",border:"1px solid #86efac",borderRadius:14,padding:"14px 16px",marginBottom:14};const info:React.CSSProperties={background:"#dbeafe",border:"1px solid #93c5fd",borderRadius:14,padding:"14px 16px",marginBottom:14}