"use client"
import {useCallback,useEffect,useState} from "react"
import {HQPage,HQPanel,hqButtonStyle} from "@/components/hq/HQShell"
import {hqSupabase} from "@/lib/hq/supabase"
type Member={id:string;email:string|null;role:string;status:string;permissions:string[];accessExpiresAt:string|null;createdAt:string;lastSignInAt:string|null}
type Event={id:number;actor_id:string;target_id:string;action:string;created_at:string}
const roleNames:Record<string,string>={founder:"Founder/Owner",partner_admin:"Partner/Admin",hq_admin:"HQ Admin",reviewer:"Reviewer",support:"Support",finance:"Finance",viewer:"Viewer"}
const permissions=["content.approve","users.manage","schools.manage","finance.view","finance.approve","workforce.operate","team.manage","support.manage"]
export default function HQTeamPage(){const[email,setEmail]=useState("");const[role,setRole]=useState("partner_admin");const[members,setMembers]=useState<Member[]>([]);const[events,setEvents]=useState<Event[]>([]);const[error,setError]=useState("");const[msg,setMsg]=useState("");const[busy,setBusy]=useState("");
const call=useCallback(async(init?:RequestInit)=>{const{data}=await hqSupabase.auth.getSession();if(!data.session)throw new Error("HQ session expired");return fetch("/api/hq/invite-member",{...init,headers:{...(init?.headers||{}),Authorization:`Bearer ${data.session.access_token}`}})},[])
const load=useCallback(async()=>{try{const r=await call();const p=await r.json();if(!r.ok)throw new Error(p.error);setMembers(p.members||[]);setEvents(p.events||[])}catch(e){setError(e instanceof Error?e.message:"Could not load HQ Team")}},[call]);useEffect(()=>{void load()},[load])
async function mutate(member:Member,action:string,extra={}){if((action==="suspend"||action==="revoke")&&!confirm(`${action==="revoke"?"Revoke":"Suspend"} HQ access for ${member.email}? Active sessions will be terminated.`))return;setBusy(member.id+action);setError("");try{const r=await call({method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({id:member.id,email:member.email,action,...extra})});const p=await r.json();if(!r.ok)throw new Error(p.error);setMsg(p.message);await load()}catch(e){setError(e instanceof Error?e.message:"Action failed")}finally{setBusy("")}}
async function invite(){setBusy("invite");try{const r=await call({method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({email,role})});const p=await r.json();if(!r.ok)throw new Error(p.error);setEmail("");setMsg(p.message);await load()}catch(e){setError(e instanceof Error?e.message:"Invite failed")}finally{setBusy("")}}
const active=members.filter(m=>m.status==="active").length, attention=members.filter(m=>m.status!=="active").length, privileged=members.filter(m=>["founder","partner_admin","hq_admin","finance"].includes(m.role)).length;
return <HQPage title="HQ Team" description="Human company operators: identity, authority, security and accountability. Digital workers remain in Workforce."><div style={{display:"grid",gap:16,maxWidth:1100}}>
<div style={{display:"grid",gridTemplateColumns:"repeat(3,minmax(0,1fr))",gap:10}}>{[["Active humans",active],["Security attention",attention],["Privileged accounts",privileged]].map(([k,v])=><div key={String(k)} style={{padding:14,border:"1px solid rgba(148,163,184,.14)",borderRadius:12}}><b style={{fontSize:22}}>{v}</b><div style={{fontSize:11,color:"#8fa2ba"}}>{k}</div></div>)}</div>
<HQPanel title="Invite a human operator" description="Founder grants the initial role. Access remains deny-by-default outside granted authority."><div style={{padding:16,display:"grid",gap:10}}>{error&&<div role="alert" style={{color:"#fecaca"}}>{error}</div>}{msg&&<div role="status" style={{color:"#bbf7d0"}}>{msg}</div>}<div style={{display:"grid",gridTemplateColumns:"minmax(0,1fr) 180px auto",gap:8}}><input value={email} onChange={e=>setEmail(e.target.value)} type="email" placeholder="person@example.com" style={{minHeight:44,borderRadius:10,padding:"0 12px",background:"rgba(255,255,255,.035)",color:"white",border:"1px solid rgba(148,163,184,.2)"}}/><select value={role} onChange={e=>setRole(e.target.value)} style={{borderRadius:10,background:"#111827",color:"white"}}>{Object.entries(roleNames).filter(([r])=>r!=="founder").map(([r,n])=><option key={r} value={r}>{n}</option>)}</select><button onClick={()=>void invite()} disabled={busy==="invite"} style={hqButtonStyle}>Send invite</button></div></div></HQPanel>
<HQPanel title="People, roles & access" description="Founder-only crown-jewel controls cannot be delegated here. Suspension/revocation terminates active sessions."><div style={{padding:16,display:"grid",gap:9}}>{members.map(m=><div key={m.id} style={{padding:13,border:"1px solid rgba(148,163,184,.13)",borderRadius:11,display:"grid",gap:9}}><div style={{display:"flex",justifyContent:"space-between",gap:12,flexWrap:"wrap"}}><div><b>{m.email||"Pending identity"}</b><div style={{fontSize:11,color:"#8fa2ba",marginTop:3}}>{roleNames[m.role]||m.role} · {m.status} {m.lastSignInAt?`· Last sign-in ${new Date(m.lastSignInAt).toLocaleString()}`:""}</div></div>{m.role!=="founder"&&<div style={{display:"flex",gap:6,flexWrap:"wrap"}}><button style={hqButtonStyle} onClick={()=>void mutate(m,"password_reset")}>Password reset</button>{m.status==="suspended"||m.status==="revoked"?<button style={hqButtonStyle} onClick={()=>void mutate(m,"reactivate")}>Reactivate</button>:<button style={hqButtonStyle} onClick={()=>void mutate(m,"suspend")}>Suspend</button>}<button style={{...hqButtonStyle,borderColor:"rgba(239,68,68,.4)"}} onClick={()=>void mutate(m,"revoke")}>Revoke</button></div>}</div>{m.role!=="founder"&&<div><div style={{fontSize:10,fontWeight:800,marginBottom:5}}>PERMISSIONS</div><div style={{display:"flex",gap:7,flexWrap:"wrap"}}>{permissions.map(p=><label key={p} style={{fontSize:10}}><input type="checkbox" checked={m.permissions.includes(p)} onChange={e=>{const next=e.target.checked?[...m.permissions,p]:m.permissions.filter(x=>x!==p);void mutate(m,"update_access",{permissions:next})}}/> {p}</label>)}</div></div>}</div>)}</div></HQPanel>
<HQPanel title="Authority rules" description="Security invariants enforced outside presentation."><div style={{padding:16,fontSize:12,lineHeight:1.7,color:"#cbd5e1"}}>Founder ownership cannot be changed from member administration. Permissions are explicit and deny-by-default. Temporary access can expire. Revocation terminates sessions. High-risk actions are designed for separation-of-duties / dual approval. Human-to-worker delegation remains governed by Workforce authority, never by role name alone.</div></HQPanel>
<HQPanel title="Recent security & access activity" description="Append-only human authority events."><div style={{padding:16,display:"grid",gap:7}}>{events.length?events.map(e=><div key={e.id} style={{fontSize:11,borderBottom:"1px solid rgba(148,163,184,.09)",paddingBottom:7}}><b>{e.action}</b> · {new Date(e.created_at).toLocaleString()}<div style={{color:"#64748b"}}>actor {e.actor_id?.slice(0,8)} → target {e.target_id?.slice(0,8)}</div></div>):<span style={{fontSize:11,color:"#8fa2ba"}}>No authority events yet.</span>}</div></HQPanel>
</div></HQPage>}
