"use client"

import { useCallback, useEffect, useMemo, useState } from "react"
import { HQPage, HQPanel, HQ_THEME as C, hqButtonStyle } from "@/components/hq/HQShell"
import { hqSupabase } from "@/lib/hq/supabase"

type GeoItem={id:string;name:string;country_id?:string;county_id?:string}
type Hierarchy={countries?:GeoItem[];counties?:GeoItem[]}
type Summary={schools?:{total?:number;verified_geography?:number;unresolved_geography?:number;mapped_coordinates?:number};users?:{teachers?:number;learners?:number;parents?:number;school_admins?:number};activity?:{active_schools?:number;evidence?:string};support?:{open_cases?:number;incidents?:number};freshness?:{generated_at?:string;activity_window_days?:number}}
type Quality={without_mapping?:number;without_county?:number;without_coordinates?:number;conflicting?:number;unresolved?:number}
type Opportunity={signal_type?:string;school_id?:string;school_name?:string;county?:string|null;state?:string;recommended_investigation?:string;evidence?:Record<string,unknown>}
type School={id:string;name:string;levels?:string[];knec_code?:string|null;nemis_code?:string|null;geography_state?:string;county?:string|null;subcounty?:string|null;learners?:number;teachers?:number;active_users?:number;open_support_cases?:number}

const sb=hqSupabase as any
const safeArray=<T,>(v:unknown):T[]=>Array.isArray(v)?v as T[]:[]
const n=(v:unknown)=>typeof v==="number"&&Number.isFinite(v)?v:0
function Metric({label,value,note,tone=C.text}:{label:string;value:string|number;note?:string;tone?:string}){return <div className="pi-metric"><strong style={{color:tone}}>{value}</strong><span>{label}</span>{note&&<small>{note}</small>}</div>}

export default function HQProductIntelligence(){
 const[h,setH]=useState<Hierarchy>({});const[s,setS]=useState<Summary>({});const[q,setQ]=useState<Quality|null>(null);const[o,setO]=useState<Opportunity[]>([]);const[schools,setSchools]=useState<School[]>([]);const[country,setCountry]=useState("");const[county,setCounty]=useState("");const[search,setSearch]=useState("");const[days,setDays]=useState(30);const[loading,setLoading]=useState(true);const[error,setError]=useState("")
 const countries=safeArray<GeoItem>(h.countries);const counties=useMemo(()=>safeArray<GeoItem>(h.counties).filter(x=>!country||x.country_id===country),[h.counties,country])
 const load=useCallback(async()=>{setLoading(true);setError("");const scope={p_country_id:country||null,p_county_id:county||null,p_subcounty_id:null,p_ward_id:null};try{const[hr,qr,sr,or,er]=await Promise.all([sb.rpc("hq_geography_hierarchy"),sb.rpc("hq_geographic_data_quality"),sb.rpc("hq_geography_summary",{...scope,p_school_id:null,p_days:days}),sb.rpc("hq_geographic_opportunities",{...scope,p_days:days,p_limit:20}),sb.rpc("hq_school_explorer_list",{...scope,p_school_level:null,p_search:search.trim()||null,p_days:days,p_limit:50})]);const fail=hr.error||qr.error||sr.error||or.error||er.error;if(fail)throw fail;setH((hr.data??{}) as Hierarchy);setQ((qr.data??null) as Quality|null);setS((sr.data??{}) as Summary);setO(safeArray<Opportunity>(or.data));setSchools(safeArray<School>(er.data))}catch{setError("Product and school intelligence could not be loaded. No fallback numbers are being shown.");setO([]);setSchools([])}finally{setLoading(false)}},[country,county,days,search])
 useEffect(()=>{void load()},[load])
 const summary=s.schools??{},users=s.users??{},activity=s.activity??{},support=s.support??{};const activeKnown=activity.evidence==="available";const verified=n(summary.verified_geography),total=n(summary.total);const coverage=total?Math.round(verified/total*100):null
 return <HQPage title="Product & School Intelligence" description="Schools, adoption, users and evidence quality in human terms. Unknown data stays unknown." actions={<button style={hqButtonStyle} onClick={()=>void load()} disabled={loading}>{loading?"Refreshing…":"Refresh"}</button>}>
  <HQPanel title="Scope" description="Filter VibeSchool evidence by country, county and time window."><div className="pi-filters"><label><span>Country</span><select value={country} onChange={e=>{setCountry(e.target.value);setCounty("")}}><option value="">All available</option>{countries.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label><span>County</span><select value={county} onChange={e=>setCounty(e.target.value)}><option value="">All counties</option>{counties.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label><span>Period</span><select value={days} onChange={e=>setDays(Number(e.target.value))}><option value={7}>7 days</option><option value={30}>30 days</option><option value={90}>90 days</option></select></label><label className="pi-search"><span>Find a school</span><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Name, KNEC or NEMIS"/></label></div></HQPanel>
  {error&&<div role="alert" className="pi-error"><strong>Intelligence unavailable</strong><span>{error}</span></div>}
  {!error&&<><section className="pi-metrics"><Metric label="Canonical schools" value={total}/><Metric label="Verified geography" value={verified} note={coverage===null?"Coverage unknown":`${coverage}% of canonical schools`}/><Metric label="Teachers" value={n(users.teachers)}/><Metric label="Learners" value={n(users.learners)}/><Metric label="Parents" value={n(users.parents)}/><Metric label="School admins" value={n(users.school_admins)}/><Metric label="Active schools" value={activeKnown?n(activity.active_schools):"Unknown"} note={`${days}-day evidence`}/><Metric label="Open support cases" value={n(support.open_cases)} tone={n(support.open_cases)?C.amber:C.green}/></section>
  <div className="pi-grid"><HQPanel title="Needs attention" description="Evidence-backed signals for investigation. These are not automatic decisions.">{o.length===0?<div className="pi-empty">No evidenced opportunity or risk signal in this scope.</div>:<div>{o.slice(0,12).map((x,i)=><article className="pi-signal" key={`${x.signal_type}-${x.school_id}-${i}`}><div><strong>{(x.signal_type||"signal").replaceAll("_"," ")}</strong><span>{x.school_name||"School"}{x.county?` · ${x.county}`:""}</span></div><p>{x.recommended_investigation||"Review the supporting evidence before acting."}</p></article>)}</div>}</HQPanel><HQPanel title="Data quality" description="Missing school evidence is shown as a gap, not converted to zero."><div className="pi-quality"><Metric label="Without governed mapping" value={q?n(q.without_mapping):"Unknown"}/><Metric label="Without county" value={q?n(q.without_county):"Unknown"}/><Metric label="Without coordinates" value={q?n(q.without_coordinates):"Unknown"}/><Metric label="Conflicting records" value={q?n(q.conflicting):"Unknown"} tone={q&&n(q.conflicting)?C.amber:C.text}/></div></HQPanel></div>
  <HQPanel title="Schools" description="Canonical school intelligence. Open support pressure and activity are evidence, not judgments about a school.">{loading?<div className="pi-empty">Loading school evidence…</div>:schools.length===0?<div className="pi-empty">No schools match this scope.</div>:<div className="pi-schools">{schools.map(x=><article key={x.id}><div className="pi-school-main"><strong>{x.name}</strong><span>{[x.subcounty,x.county].filter(Boolean).join(" · ")||"Location not yet verified"}</span><small>{safeArray<string>(x.levels).join(", ")||"Level not recorded"}{x.knec_code?` · KNEC ${x.knec_code}`:""}</small></div><div className="pi-school-stats"><span><b>{n(x.teachers)}</b> teachers</span><span><b>{n(x.learners)}</b> learners</span><span><b>{n(x.active_users)}</b> active users</span>{n(x.open_support_cases)>0&&<span className="warn"><b>{n(x.open_support_cases)}</b> support cases</span>}</div></article>)}</div>}</HQPanel></>}
  <style jsx global>{`.pi-filters{display:grid;grid-template-columns:1fr 1fr 120px minmax(220px,1.5fr);gap:10px;padding:14px}.pi-filters label{display:grid;gap:5px}.pi-filters label>span{font-size:10px;color:${C.muted};font-weight:800}.pi-filters select,.pi-filters input{min-height:42px;border-radius:9px;border:1px solid ${C.border};background:rgba(255,255,255,.035);color:${C.text};padding:0 10px}.pi-error{display:grid;gap:4px;margin:14px 0;padding:13px;border:1px solid rgba(239,68,68,.35);border-radius:12px;color:#fecaca}.pi-error span{font-size:12px}.pi-metrics{display:grid;grid-template-columns:repeat(4,1fr);gap:9px;margin:14px 0}.pi-metric{border:1px solid ${C.border};border-radius:12px;padding:12px;background:${C.panelSoft};min-width:0}.pi-metric strong{display:block;font-size:24px}.pi-metric span,.pi-metric small{display:block;margin-top:4px}.pi-metric span{font-size:10.5px;font-weight:850}.pi-metric small{font-size:9.5px;color:${C.muted};line-height:1.4}.pi-grid{display:grid;grid-template-columns:1.2fr .8fr;gap:12px;margin-bottom:12px}.pi-signal{padding:12px 14px;border-top:1px solid ${C.border}}.pi-signal:first-child{border-top:0}.pi-signal div{display:flex;justify-content:space-between;gap:10px}.pi-signal strong{font-size:12px;text-transform:capitalize}.pi-signal span{font-size:10px;color:${C.muted}}.pi-signal p{font-size:11px;line-height:1.5;color:#cbd5e1;margin:6px 0 0}.pi-quality{display:grid;grid-template-columns:1fr 1fr;gap:8px;padding:12px}.pi-empty{padding:18px;color:${C.muted};font-size:11.5px}.pi-schools article{display:grid;grid-template-columns:minmax(0,1fr) auto;gap:14px;padding:13px 14px;border-top:1px solid ${C.border}}.pi-schools article:first-child{border-top:0}.pi-school-main strong,.pi-school-main span,.pi-school-main small{display:block}.pi-school-main strong{font-size:13px}.pi-school-main span{font-size:10.5px;color:${C.muted};margin-top:3px}.pi-school-main small{font-size:9.5px;color:#71849b;margin-top:4px}.pi-school-stats{display:flex;gap:12px;align-items:center;flex-wrap:wrap;justify-content:flex-end;font-size:10px;color:${C.muted}}.pi-school-stats b{color:${C.text}}.pi-school-stats .warn,.pi-school-stats .warn b{color:${C.amber}}@media(max-width:900px){.pi-filters{grid-template-columns:1fr 1fr}.pi-metrics{grid-template-columns:repeat(2,1fr)}.pi-grid{grid-template-columns:1fr}}@media(max-width:720px){.pi-filters{grid-template-columns:1fr}.pi-search{grid-column:auto}.pi-schools article{grid-template-columns:1fr}.pi-school-stats{justify-content:flex-start}.pi-signal div{display:block}.pi-signal span{display:block;margin-top:3px}}@media(max-width:360px){.pi-metrics,.pi-quality{grid-template-columns:1fr}}`}</style>
 </HQPage>
}
