// ── Minimal Supabase types ──────────────────────────────────────────────
// Generated by hand from live schema queries (information_schema.columns,
// pg_proc, pg_enum) on 2026-06-20. Covers only the tables/RPCs touched by
// app/api/exam/generate/route.ts and app/api/exam/flag/route.ts so far.
//
// This is NOT a full schema dump. As more routes are typed, either extend
// this file or replace it with a real `supabase gen types` output once the
// CLI platform issue (Android/ARM64 unsupported) is worked around — e.g.
// via GitHub Codespaces, as previously discussed.

export type ExamSubject =
  | 'Mathematics' | 'English' | 'Biology' | 'Chemistry' | 'History'
  | 'Physics' | 'Geography' | 'Kiswahili' | 'CRE' | 'Business Studies'

export type ExamForm = 'Form 1' | 'Form 2' | 'Form 3' | 'Form 4'

export type ExamDifficulty = 'easy' | 'medium' | 'hard'

export interface Database {
  __InternalSupabase: {
    PostgrestVersion: '12'
  }
  public: {
    Views: {}
    Tables: {
      exam_question_bank: {
        Row: {
          id: string
          subject: ExamSubject
          form: ExamForm
          topic: string
          difficulty: ExamDifficulty
          question: string
          options: string[]
          correct_index: number
          explanation: string
          teaching_note: string
          hint: string | null
          status: string
          times_served: number
          times_flagged: number
          source: string
          created_at: string
        }
        Insert: {
          id?: string
          subject: ExamSubject
          form: ExamForm
          topic: string
          difficulty: ExamDifficulty
          question: string
          options: string[]
          correct_index: number
          explanation: string
          teaching_note: string
          hint?: string | null
          status?: string
          times_served?: number
          times_flagged?: number
          source: string
          created_at?: string
        }
        Update: {
          id?: string
          subject?: ExamSubject
          form?: ExamForm
          topic?: string
          difficulty?: ExamDifficulty
          question?: string
          options?: string[]
          correct_index?: number
          explanation?: string
          teaching_note?: string
          hint?: string | null
          status?: string
          times_served?: number
          times_flagged?: number
          source?: string
          created_at?: string
        }
      }
      exam_flags: {
        Row: {
          id: string
          session_id: string | null
          user_id: string | null
          question_text: string
          flag_type: string
          reason: string | null
          status: string
          created_at: string
        }
        Insert: {
          id?: string
          session_id?: string | null
          user_id?: string | null
          question_text: string
          flag_type: string
          reason?: string | null
          status?: string
          created_at?: string
        }
        Update: {
          id?: string
          session_id?: string | null
          user_id?: string | null
          question_text?: string
          flag_type?: string
          reason?: string | null
          status?: string
          created_at?: string
        }
      }
    }
    Functions: {
      count_bank_questions: {
        Args: {
          p_subject: ExamSubject
          p_form: ExamForm
          p_topic: string
          p_difficulty: ExamDifficulty
        }
        Returns: number
      }
      get_bank_questions: {
        Args: {
          p_subject: ExamSubject
          p_form: ExamForm
          p_topic: string
          p_difficulty: ExamDifficulty
          p_count: number
        }
        Returns: Database['public']['Tables']['exam_question_bank']['Row'][]
      }
      bump_bank_served: {
        Args: { p_ids: string[] }
        Returns: void
      }
      dismiss_bank_question: {
        Args: { p_id: string }
        Returns: void
      }
    }
  }
}
