import { ExamForm } from '@/lib/types'

export const EXAM_DATA: Record<ExamForm, string[]> = {
  'Form 1': [
    'Numbers',
    'Fractions',
    'Decimals',
    'Squares and Square Roots',
    'Algebraic Expressions',
    'Linear Equations',
    'Commercial Arithmetic',
    'Coordinates',
    'Angles',
    'Triangles',
  ],
  'Form 2': [
    'Formulae and Variations',
    'Sequences',
    'Indices',
    'Logarithms',
    'Further Logarithms',
    'Quadratic Expressions',
    'Linear Inequalities',
    'Statistics',
    'Circles',
    'Scale Drawing',
  ],
  'Form 3': [
    'Quadratic Equations and Graphs',
    'Approximations and Errors',
    'Trigonometry',
    'Surds',
    'Further Trigonometry',
    'Matrices',
    'Formulae and Variations',
    'Sequence and Series',
    'Vectors',
  ],
  'Form 4': [
    'Matrices and Transformations',
    'Statistics II',
    'Loci',
    'Longitudes and Latitudes',
    'Linear Programming',
    'Integration',
    'Area Approximations',
    'Probability',
    'Compound Proportions',
  ],
}
