import jsPDF from 'jspdf'
import autoTable from 'jspdf-autotable'
import * as XLSX from 'xlsx'
import { supabase } from '@/lib/supabase'

interface SchoolMeta {
  name: string
  logo_url: string | null
}

async function getSchoolMeta(schoolId: string): Promise<SchoolMeta> {
  const { data } = await supabase
    .from('schools')
    .select('name, logo_url')
    .eq('id', schoolId)
    .single()
  return {
    name: data?.name ?? 'EduWorld Kenya',
    logo_url: data?.logo_url ?? null,
  }
}

function formatDate(): string {
  return new Date().toLocaleDateString('en-KE', {
    day: '2-digit',
    month: 'long',
    year: 'numeric',
  })
}

async function addPDFHeader(
  doc: jsPDF,
  school: SchoolMeta,
  reportTitle: string,
  generatedBy: string
): Promise<number> {
  const pageWidth = doc.internal.pageSize.getWidth()

  // Logo
  if (school.logo_url) {
    try {
      const img = new Image()
      img.crossOrigin = 'anonymous'
      await new Promise<void>((resolve) => {
        img.onload = () => resolve()
        img.onerror = () => resolve()
        img.src = school.logo_url!
      })
      doc.addImage(img, 'PNG', 14, 10, 20, 20)
    } catch {
      // logo failed — skip silently
    }
  }

  // School name
  doc.setFontSize(16)
  doc.setTextColor(15, 23, 42)
  doc.setFont('helvetica', 'bold')
  doc.text(school.name, pageWidth / 2, 16, { align: 'center' })

  // Report title
  doc.setFontSize(11)
  doc.setFont('helvetica', 'normal')
  doc.setTextColor(71, 85, 105)
  doc.text(reportTitle, pageWidth / 2, 23, { align: 'center' })

  // Meta row
  doc.setFontSize(8)
  doc.setTextColor(100, 116, 139)
  doc.text(`Generated: ${formatDate()}`, 14, 32)
  doc.text(`Generated by: ${generatedBy}`, pageWidth - 14, 32, { align: 'right' })

  // Divider
  doc.setDrawColor(226, 232, 240)
  doc.setLineWidth(0.4)
  doc.line(14, 35, pageWidth - 14, 35)

  return 40 // Y cursor after header
}

export async function exportToPDF({
  schoolId,
  reportTitle,
  generatedBy,
  columns,
  rows,
}: {
  schoolId: string
  reportTitle: string
  generatedBy: string
  columns: string[]
  rows: (string | number | null)[][]
}) {
  const school = await getSchoolMeta(schoolId)
  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' })

  const startY = await addPDFHeader(doc, school, reportTitle, generatedBy)

  autoTable(doc, {
    head: [columns],
    body: rows.map((r) => r.map((v) => (v === null || v === undefined ? '—' : String(v)))),
    startY,
    styles: {
      fontSize: 8,
      cellPadding: 3,
      textColor: [15, 23, 42],
    },
    headStyles: {
      fillColor: [15, 23, 42],
      textColor: [248, 250, 252],
      fontStyle: 'bold',
    },
    alternateRowStyles: {
      fillColor: [241, 245, 249],
    },
    margin: { left: 14, right: 14 },
  })

  // Page numbers
  const pageCount = (doc as jsPDF & { internal: { getNumberOfPages: () => number } }).internal.getNumberOfPages()
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i)
    doc.setFontSize(7)
    doc.setTextColor(148, 163, 184)
    doc.text(
      `Page ${i} of ${pageCount}`,
      doc.internal.pageSize.getWidth() / 2,
      doc.internal.pageSize.getHeight() - 8,
      { align: 'center' }
    )
  }

  const fileName = `${reportTitle.replace(/\s+/g, '_')}_${formatDate().replace(/\s/g, '_')}.pdf`
  doc.save(fileName)
}

export async function exportToExcel({
  schoolId,
  reportTitle,
  generatedBy,
  columns,
  rows,
}: {
  schoolId: string
  reportTitle: string
  generatedBy: string
  columns: string[]
  rows: (string | number | null)[][]
}) {
  const school = await getSchoolMeta(schoolId)

  const metaRows = [
    [school.name],
    [reportTitle],
    [`Generated: ${formatDate()}    Generated by: ${generatedBy}`],
    [],
    columns,
    ...rows.map((r) => r.map((v) => (v === null || v === undefined ? '—' : v))),
  ]

  const ws = XLSX.utils.aoa_to_sheet(metaRows)

  // Column widths
  ws['!cols'] = columns.map(() => ({ wch: 20 }))

  const wb = XLSX.utils.book_new()
  XLSX.utils.book_append_sheet(wb, ws, reportTitle.slice(0, 31))

  const fileName = `${reportTitle.replace(/\s+/g, '_')}_${formatDate().replace(/\s/g, '_')}.xlsx`
  XLSX.writeFile(wb, fileName)
}

export function exportToCSV({
  reportTitle,
  columns,
  rows,
}: {
  reportTitle: string
  columns: string[]
  rows: (string | number | null)[][]
}) {
  const escape = (v: string | number | null) => {
    const s = v === null || v === undefined ? '' : String(v)
    return s.includes(',') || s.includes('"') || s.includes('\n')
      ? `"${s.replace(/"/g, '""')}"`
      : s
  }

  const csvContent = [columns, ...rows]
    .map((row) => row.map(escape).join(','))
    .join('\n')

  const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8;' })
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = `${reportTitle.replace(/\s+/g, '_')}_${formatDate().replace(/\s/g, '_')}.csv`
  a.click()
  URL.revokeObjectURL(url)
}