"use client"

import { useCallback, useEffect, useState } from "react"
import { useRouter } from "next/navigation"
import { hqSupabase } from "@/lib/hq/supabase"

type Overview={publications?:{total?:number;draft?:number;published?:number;textbooks?:number;ebooks?:number};assessment_bank?:{questions?:number;definitions?:number};curriculum?:{rows?:number;imports?:number;outcomes?:number};funhub?:{active_vouchers?:number;voucher_pool?:number;learners_with_xp?:number};moderation?:{exam_flags?:number;open_incidents?:number;assessment_requests?:number}}
const C={bg:"#07111f",panel:"#0d1b2f",line:"rgba(255,255,255,.09)",text:"#f8fafc",muted:"rgba(255,255,255,.48)",green:"#34d399",blue:"#60a5fa",amber:"#f59e0b",violet:"#a78bfa",red:"#fb7185"}
type UntypedRpc=<T=unknown>(name:string,args?:Record<string,unknown>)=>PromiseLike<{data:T|null;error:{message?:string}|null}>
const rpc=hqSupabase.rpc.bind(hqSupabase) as unknown as UntypedRpc
export default function HQStudioPage(){
 const router=useRouter();const[data,setData]=useState<Overview>({});const[error,setError]=useState("");const[loading,setLoading]=useState(true)
 const load=useCallback(async()=>{setError("");const{data:d,error:e}=await rpc<Overview>("hq_studio_overview");if(e)setError(e.message||"Studio state could not be loaded");else setData(d??{});setLoading(false)},[]);useEffect(()=>{void load()},[load])
 const cards=[["Academy","Operate real courses, modules and topics with Concept, Kenya Context, Common Errors and specialist-tip sections.","/hq/studio/academy",C.green,"Live course → module → topic catalog"],["Publishing Factory","Review, verify, apply and release publications using the hardened publishing pipeline.","/hq/content",C.green,`${data.publications?.published??0} published · ${data.publications?.draft??0} drafts`],["Rich Authoring","Human block editor for textbooks and eBooks: concepts, Kenya context, examples, visuals, VibeLab, activities and questions.","/hq/studio/editor?format=vibetextbook",C.blue,`${data.publications?.textbooks??0} textbooks · ${data.publications?.ebooks??0} eBooks`],["Sources & History","Register and review curriculum provenance and inspect publication revision history across HQ.","/hq/studio/governance",C.amber,`${data.curriculum?.imports??0} curriculum source imports`],["Curriculum Intelligence","Research, source rights, health signals, proposals, exact patches, regeneration and effectiveness.","/hq/curriculum-intelligence/engine",C.violet,`${data.curriculum?.outcomes??0} outcomes · ${data.curriculum?.imports??0} source imports`],["Curriculum Editor","Browse and operate real curriculum rows, grades, subjects, weeks and outcomes.","/hq/studio/curriculum",C.blue,`${data.curriculum?.rows??0} curriculum rows`],["Exam & Question Bank","Inspect the real assessment bank and its curriculum/outcome linkage instead of hardcoded KCSE subjects.","/hq/studio/exams",C.amber,`${data.assessment_bank?.questions??0} bank questions · ${data.assessment_bank?.definitions??0} assessments`],["Moderation & Trust","One owner queue for incidents, exam flags and assessment moderation evidence.","/hq/studio/moderation",C.red,`${(data.moderation?.exam_flags??0)+(data.moderation?.open_incidents??0)+(data.moderation?.assessment_requests??0)} items requiring review`],["FunHub Economy","Operate sponsor vouchers and inspect the live XP economy.","/hq/studio/funhub",C.violet,`${data.funhub?.active_vouchers??0} active vouchers · ${data.funhub?.voucher_pool??0} remaining`],["Domains & Taxonomy","Manage the content-domain vocabulary and connect it to Academy, curriculum and publishing tags.","/hq/studio/domains",C.green,"Governed taxonomy"]] as const
 return <main style={{minHeight:"100dvh",background:C.bg,color:C.text,fontFamily:"Inter,system-ui,sans-serif",padding:"18px 18px 80px"}}><div style={{maxWidth:1160,margin:"0 auto"}}><div style={{display:"flex",gap:10,alignItems:"center",marginBottom:18}}><button onClick={()=>router.push("/hq")} style={btn}>← HQ</button><div style={{flex:1}}><div style={{fontSize:10,fontWeight:900,color:C.green,letterSpacing:".12em"}}>HQ CONTENT OPERATIONS</div><h1 style={{margin:"4px 0 0",fontSize:27}}>HQ Studio</h1><div style={{fontSize:12,color:C.muted,marginTop:4}}>Live content operations on the isolated HQ session.</div></div><button onClick={()=>void load()} style={btn}>Refresh</button></div>{error&&<div style={{padding:12,border:`1px solid ${C.red}55`,borderRadius:12,color:"#fecdd3",marginBottom:14}}>{error}</div>}{loading?<div style={{color:C.muted}}>Loading live Studio state…</div>:<div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(260px,1fr))",gap:12}}>{cards.map(([title,desc,route,tone,stat])=><button key={title} onClick={()=>router.push(route)} style={{textAlign:"left",padding:17,borderRadius:16,border:`1px solid ${tone}44`,background:`${tone}08`,color:C.text,cursor:"pointer"}}><div style={{fontSize:15,fontWeight:900,color:tone}}>{title}</div><div style={{fontSize:11.5,lineHeight:1.6,color:C.muted,marginTop:7}}>{desc}</div><div style={{fontSize:10.5,fontWeight:800,marginTop:14}}>{stat}</div></button>)}</div>}</div></main>
}
const btn:React.CSSProperties={border:"1px solid rgba(255,255,255,.1)",background:"rgba(255,255,255,.04)",color:"#f8fafc",borderRadius:10,padding:"8px 11px",fontSize:11,fontWeight:800,cursor:"pointer"}
