"use client";
import {useEffect,useState} from 'react'; import {supabase} from '@/lib/supabase';
type E={id:string;title:string;starts_at:string;status:string;audience_type:string;event_type:string}
export default function SchoolEventsAdmin(){
 const [schoolId,setSchoolId]=useState(''),[rows,setRows]=useState<E[]>([]),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 const [title,setTitle]=useState(''),[starts,setStarts]=useState(''),[type,setType]=useState('event'),[audience,setAudience]=useState('all_staff');
 async function load(){setError('');const {data:{user}}=await supabase.auth.getUser();if(!user)return;const {data:sm,error:e}=await supabase.from('school_members').select('school_id').eq('profile_id',user.id).in('role',['admin','owner']).limit(1).maybeSingle();if(e){setError(e.message);return}if(!sm)return;setSchoolId(sm.school_id);const {data,error:x}=await supabase.from('school_events').select('id,title,starts_at,status,audience_type,event_type').eq('school_id',sm.school_id).order('starts_at');if(x)setError(x.message);else setRows((data??[]) as E[])}
 useEffect(()=>{void load()},[]);
 async function create(){if(!schoolId||!title.trim()||!starts)return;setBusy(true);setError('');const {data,error}=await supabase.from('school_events').insert({school_id:schoolId,title:title.trim(),starts_at:new Date(starts).toISOString(),event_type:type,audience_type:audience,status:'draft'}).select('id').single();if(error)setError(error.message);else if(data){const {error:p}=await supabase.rpc('admin_publish_school_event',{p_event_id:data.id});if(p)setError(p.message);else{setTitle('');setStarts('');await load()}}setBusy(false)}
 async function cancel(id:string){setBusy(true);const {error}=await supabase.rpc('admin_cancel_school_event',{p_event_id:id});if(error)setError(error.message);else await load();setBusy(false)}
 return <main style={{padding:20,maxWidth:800,margin:'0 auto'}}><h1>School events</h1><p>Create official events here. Timetable suppression remains controlled by the calendar authority.</p>{error&&<p style={{color:'#b91c1c'}}>{error}</p>}<section style={{display:'grid',gap:8,padding:16,border:'1px solid #e2e8f0',borderRadius:12}}><input aria-label="Event title" placeholder="Event title" value={title} onChange={e=>setTitle(e.target.value)}/><input aria-label="Start" type="datetime-local" value={starts} onChange={e=>setStarts(e.target.value)}/><select value={type} onChange={e=>setType(e.target.value)}><option value="event">Event</option><option value="meeting">Meeting</option><option value="activity">Activity</option><option value="ceremony">Ceremony</option><option value="trip">Trip</option><option value="deadline">Deadline</option><option value="exam_event">Exam event</option></select><select value={audience} onChange={e=>setAudience(e.target.value)}><option value="all_staff">All staff</option><option value="all_teachers">All teachers</option><option value="everyone">Everyone</option></select><button disabled={busy} onClick={()=>void create()}>{busy?'Saving…':'Publish event'}</button></section><section>{rows.map(r=><article key={r.id} style={{padding:'12px 0',borderBottom:'1px solid #e2e8f0'}}><b>{r.title}</b><div>{new Date(r.starts_at).toLocaleString('en-KE',{timeZone:'Africa/Nairobi'})} · {r.audience_type} · {r.status}</div>{r.status==='published'&&<button disabled={busy} onClick={()=>void cancel(r.id)}>Cancel event</button>}</article>)}</section></main>
}