import { supabase } from "@/lib/supabase"

export type HQSnapshot={generated_at:string;users:{total:number;today:number;teachers:number;learners:number};schools:{total:number;active:number;today:number};teaching:{lesson_plans_today:number;lesson_plans_7d:number;lessons_taught_today:number;homework_today:number;submissions_today:number;unreviewed_submissions:number};content:{publications_total:number;publications_live:number;publications_draft:number;reads_total:number};events:{today:number;last_hour:number};notifications:{unread:number;critical:number};incidents:{open:number}}
export type HQNotification={id:string;category:string;severity:"info"|"success"|"warning"|"critical";title:string;body:string;route:string|null;status:"unread"|"read"|"resolved";metadata:Record<string,unknown>;created_at:string}
export type HQDecision={id:string;code:string;title:string;category:string;decision_type:string;status:"draft"|"reviewed"|"approved"|"locked"|"active"|"superseded"|"rolled_back"|"cancelled";rule_key:string|null;rule_value:unknown;reason:string|null;affected_products:string[];effective_at:string|null;approved_at:string|null;locked_at:string|null;supersedes_id:string|null;rollback_of_id:string|null;created_at:string;updated_at:string}
export type HQDecisionDetail={decision:HQDecision;versions:Array<Record<string,unknown>>;targets:Array<{id:string;product_key:string;expected_config_key:string|null;expected_value:unknown;status:string;applied_at:string|null;verified_at:string|null;error:string|null}>;audit:Array<{id:string;action:string;actor_id:string|null;details:Record<string,unknown>;created_at:string}>}
export type HQPolicy={id:string;policy_key:string;domain:string;owner_department:string;value_type:"boolean"|"integer"|"number"|"string"|"json";default_value:unknown;allowed_products:string[];risk_level:"low"|"normal"|"high"|"critical";failure_mode:"fail_open"|"fail_closed"|"last_known_good";min_number:number|null;max_number:number|null;allowed_values:unknown;description:string;active:boolean}
export type HQExecutiveAnalytics={generated_at:string;daily:Array<{date:string;signups:number;lesson_plans:number;homework:number;submissions:number}>;roles:Array<{role:string;count:number}>;schools:Array<{status:string;count:number}>;finance:{payments_30d:number;expenses_30d:number;publication_earnings:number};communications:{parent_messages_30d:number;vc_messages_30d:number};content:{publication_reads:number};operations:{open_incidents:number;marking_backlog:number}}
export type HQDepartment={key:string;name:string;mandate:string;icon:string|null;open_count:number;critical_count:number;waiting_approval_count:number}
export type HQWorkItem={id:string;department_key:string;work_type:string;priority:"low"|"normal"|"high"|"critical";status:"open"|"in_progress"|"waiting_approval"|"resolved"|"cancelled";title:string;summary:string|null;source_type:string|null;source_id:string|null;route:string|null;approval_required:boolean;due_at:string|null;evidence:Record<string,unknown>;created_at:string;updated_at:string;resolved_at:string|null}
export type HQMorningBrief={generated_at:string;headline:{new_users_today:number;active_schools:number;lesson_plans_today:number;submissions_today:number;open_incidents:number;decisions_waiting:number;work_waiting_approval:number};priorities:Array<{department:string;priority:string;title:string;summary:string|null;route:string|null}>;decisions:Array<{id:string;code:string;title:string;status:string}>}
export type HQOrgSummary={departments:number;functions:number;open_work:number;waiting_approval:number;overdue:number}
export type HQWorkHealth={open:number;overdue:number;due_24h:number;waiting_approval:number;critical_open:number}
export type HQControlHealth={events:{total:number;fresh:number;duplicates:number};notifications:{unread:number;active:number};incidents:{open:number};decisions:{total:number;active:number;waiting:number};propagation:{targets:number;drift:number;configs:number};work:HQWorkHealth;checked_at:string}
export type HQMetricDefinition={key:string;source:string;definition:string}
type UntypedRpc=<T=unknown>(name:string,args?:Record<string,unknown>)=>PromiseLike<{data:T|null;error:{message?:string}|null}>
const rawRpc=supabase.rpc.bind(supabase) as unknown as UntypedRpc
async function rpc<T>(name:string,args?:Record<string,unknown>):Promise<T>{const{data,error}=await rawRpc<T>(name,args);if(error)throw new Error(error.message||`RPC ${name} failed`);return data as T}
export const loadHQSnapshot=()=>rpc<HQSnapshot>("hq_get_snapshot");export const loadHQExecutiveAnalytics=()=>rpc<HQExecutiveAnalytics>("hq_get_executive_analytics");export const loadHQNotifications=(limit=60)=>rpc<HQNotification[]>("hq_list_notifications",{p_limit:limit});export async function markHQNotificationRead(id:string){await rpc("hq_mark_notification_read",{p_id:id})}export async function resolveHQNotification(id:string){await rpc("hq_resolve_notification",{p_id:id})}export async function runHQRules(){return Number(await rpc("hq_generate_operational_alerts")??0)}
export const listHQDecisions=(limit=100)=>rpc<HQDecision[]>("hq_list_decisions",{p_limit:limit});export const getHQDecisionDetail=(id:string)=>rpc<HQDecisionDetail>("hq_get_decision_detail",{p_id:id});export const createHQDecision=(i:{title:string;category:string;decisionType:string;ruleKey:string|null;ruleValue:unknown;reason:string;affectedProducts:string[];effectiveAt:string|null})=>rpc<string>("hq_create_decision",{p_title:i.title,p_category:i.category,p_decision_type:i.decisionType,p_rule_key:i.ruleKey,p_rule_value:i.ruleValue,p_reason:i.reason,p_affected_products:i.affectedProducts,p_effective_at:i.effectiveAt});export async function updateHQDraftDecision(id:string,i:{title:string;category:string;decisionType:string;ruleKey:string|null;ruleValue:unknown;reason:string;affectedProducts:string[];effectiveAt:string|null}){await rpc("hq_update_draft_decision",{p_id:id,p_title:i.title,p_category:i.category,p_decision_type:i.decisionType,p_rule_key:i.ruleKey,p_rule_value:i.ruleValue,p_reason:i.reason,p_affected_products:i.affectedProducts,p_effective_at:i.effectiveAt})}export async function markHQDecisionReviewed(id:string){await rpc("hq_mark_decision_reviewed",{p_id:id})}export async function approveHQDecision(id:string){await rpc("hq_approve_decision",{p_id:id})}export async function lockHQDecision(id:string){await rpc("hq_lock_decision",{p_id:id})}export const verifyHQDecision=(id:string)=>rpc<{applied:number;drift:number;pending?:number}>("hq_verify_decision_propagation",{p_id:id});export const createHQAmendment=(id:string,i?:{title?:string;ruleValue?:unknown;reason?:string;effectiveAt?:string|null})=>rpc<string>("hq_create_amendment",{p_old_id:id,p_title:i?.title??null,p_rule_value:i?.ruleValue??null,p_reason:i?.reason??null,p_effective_at:i?.effectiveAt??null});export async function cancelHQDecision(id:string,reason:string){await rpc("hq_cancel_decision",{p_id:id,p_reason:reason})}export const rollbackHQDecision=(id:string,reason:string)=>rpc<string>("hq_rollback_decision",{p_id:id,p_reason:reason});export const emergencySetHQPolicy=(policyKey:string,productKey:string,value:unknown,reason:string)=>rpc<string>("hq_emergency_set_policy",{p_policy_key:policyKey,p_product_key:productKey,p_value:value,p_reason:reason});export const listHQPolicies=()=>rpc<HQPolicy[]>("hq_list_policy_registry");export const observeTwinRuntime=()=>rpc<Record<string,unknown>>("hq_observe_twin_runtime");
export const getHQProductConfig=(productKey:string,configKey:string)=>rpc<unknown>("hq_get_product_config",{p_product_key:productKey,p_config_key:configKey});export const listHQDepartments=()=>rpc<HQDepartment[]>("hq_list_departments");export const listHQWorkItems=(department:string|null=null,limit=100)=>rpc<HQWorkItem[]>("hq_list_work_items",{p_department:department,p_limit:limit});export const createHQWorkItem=(i:{department:string;title:string;summary?:string;priority?:HQWorkItem["priority"];dueAt?:string|null;approvalRequired?:boolean;route?:string|null;evidence?:Record<string,unknown>})=>rpc<string>("hq_create_work_item",{p_department:i.department,p_title:i.title,p_summary:i.summary??null,p_priority:i.priority??"normal",p_due_at:i.dueAt??null,p_approval_required:i.approvalRequired??false,p_route:i.route??null,p_evidence:i.evidence??{}});export async function updateHQWorkItem(id:string,status:HQWorkItem["status"]){await rpc("hq_update_work_item",{p_id:id,p_status:status})}export async function approveHQWorkItem(id:string){await rpc("hq_approve_work_item",{p_id:id})}export const loadHQMorningBrief=()=>rpc<HQMorningBrief>("hq_get_morning_brief");export const loadHQOrgSummary=()=>rpc<HQOrgSummary>("hq_get_org_summary");export const loadHQWorkHealth=()=>rpc<HQWorkHealth>("hq_get_work_health");export const loadHQControlHealth=()=>rpc<HQControlHealth>("hq_get_control_health");export const loadHQMetricCatalog=()=>rpc<HQMetricDefinition[]>("hq_metric_catalog")