"use client"

import { useCallback,useEffect,useState } from "react"
import { useRouter } from "next/navigation"
import { supabase } from "@/lib/supabase"
const rpc=supabase.rpc.bind(supabase) as any
const C={bg:"#07111f",panel:"#0d1b2f",line:"rgba(255,255,255,.09)",text:"#f8fafc",muted:"rgba(255,255,255,.48)",green:"#34d399",red:"#fb7185"}
type Domain={key:string;name:string;icon:string|null;description:string|null;tags:string[];active:boolean;sort_order:number}
const blank={key:"",name:"",icon:"",description:"",tags:"",active:true,sort:100}
export default function DomainsStudio(){const router=useRouter();const[items,setItems]=useState<Domain[]>([]);const[form,setForm]=useState(blank);const[error,setError]=useState("");const[busy,setBusy]=useState(false)
 const load=useCallback(async()=>{const{data,error:e}=await rpc("hq_list_content_domains");if(e)setError(e.message);else setItems(data??[])},[]);useEffect(()=>{void load()},[load]);function edit(d:Domain){setForm({key:d.key,name:d.name,icon:d.icon??"",description:d.description??"",tags:(d.tags??[]).join(', '),active:d.active,sort:d.sort_order})}
 async function save(){setBusy(true);const{error:e}=await rpc("hq_upsert_content_domain",{p_key:form.key,p_name:form.name,p_icon:form.icon,p_description:form.description,p_tags:form.tags.split(',').map(x=>x.trim()).filter(Boolean),p_active:form.active,p_sort_order:form.sort});if(e)setError(e.message);else{setForm(blank);await load()}setBusy(false)}
 return <main style={{minHeight:'100dvh',background:C.bg,color:C.text,padding:18,fontFamily:'Inter,system-ui,sans-serif'}}><div style={{maxWidth:1000,margin:'0 auto'}}><button onClick={()=>router.push('/hq/studio')} style={btn}>← Studio</button><h1>Domains & Taxonomy</h1><p style={{fontSize:12,color:C.muted}}>Governed vocabulary for Academy/content categories. The original Health, Trade, Education, Transportation and Technology domains are preserved as real data.</p>{error&&<div style={{color:'#fecdd3'}}>{error}</div>}<div style={{display:'grid',gridTemplateColumns:'minmax(300px,.7fr) minmax(0,1fr)',gap:12}}><section style={panel}>{[['Key','key'],['Name','name'],['Icon','icon'],['Description','description'],['Tags (comma-separated)','tags']].map(([label,key])=><label key={key} style={lab}>{label}<input value={(form as any)[key]} onChange={e=>setForm({...form,[key]:e.target.value})} style={input}/></label>)}<label style={lab}>Sort order<input type="number" value={form.sort} onChange={e=>setForm({...form,sort:Number(e.target.value)||100})} style={input}/></label><label style={{...lab,display:'flex',gap:8}}><input type="checkbox" checked={form.active} onChange={e=>setForm({...form,active:e.target.checked})}/> Active</label><button disabled={busy} onClick={()=>void save()} style={{...btn,color:C.green}}>Save domain</button></section><section style={panel}>{items.map((d,i)=><button key={d.key} onClick={()=>edit(d)} style={{width:'100%',border:0,borderTop:i?`1px solid ${C.line}`:0,background:'transparent',color:C.text,textAlign:'left',padding:'12px 4px',cursor:'pointer',display:'flex',gap:10,alignItems:'center'}}><span style={{fontSize:22}}>{d.icon||'◉'}</span><span style={{flex:1}}><b>{d.name}</b><small style={{display:'block',color:C.muted,marginTop:3}}>{d.key} · {(d.tags??[]).join(' · ')}</small></span><span style={{fontSize:10,color:d.active?C.green:C.red}}>{d.active?'ACTIVE':'INACTIVE'}</span></button>)}</section></div></div></main>}
const panel:React.CSSProperties={background:C.panel,border:`1px solid ${C.line}`,borderRadius:14,padding:14};const btn:React.CSSProperties={border:`1px solid ${C.line}`,background:'rgba(255,255,255,.04)',color:C.text,borderRadius:9,padding:'8px 10px',fontSize:11,fontWeight:800,cursor:'pointer'};const input:React.CSSProperties={width:'100%',boxSizing:'border-box',background:'#0a1628',border:`1px solid ${C.line}`,borderRadius:9,padding:10,color:C.text,marginTop:5};const lab:React.CSSProperties={display:'block',fontSize:10,color:C.muted,fontWeight:800,marginBottom:10}
