"use client"

import Link from "next/link"
import { useCallback, useEffect, useMemo, useState } from "react"
import { hqSupabase } from "@/lib/hq/supabase"
import { HQPage, HQPanel, HQ_THEME as C } from "@/components/hq/HQShell"

type Point={date:string;connected_schools:number;active_schools:number;active_users:number}
type Trend={window_days:number;series:Point[];semantics:Record<string,string>;generated_at:string}
type CountyDetail={county:string;window_days:number;people:{linked_profiles:number;teachers:number;learners:number;parents:number;admins:number};activity:{active_schools:number;active_users:number;events:number;previous_active_users:number;active_user_change_pct:number|null};revenue:{currency:string;attributed_paid_orders:number;attributed_paid_kes:number;institution_paid_claimable:boolean};data_quality:{pending_identity_candidates:number};generated_at:string}

function LineChart({series,keyName,label}:{series:Point[];keyName:"connected_schools"|"active_schools"|"active_users";label:string}){
 const width=760,height=180,pad=24;const values=series.map(x=>x[keyName]);const max=Math.max(1,...values);const points=series.map((p,i)=>`${pad+(i/Math.max(series.length-1,1))*(width-pad*2)},${height-pad-(p[keyName]/max)*(height-pad*2)}`).join(" ");const latest=values.at(-1)??0
 return <div className="si-chart"><div className="si-chart-head"><strong>{label}</strong><span>{latest.toLocaleString()} latest</span></div><svg viewBox={`0 0 ${width} ${height}`} role="img" aria-label={`${label} daily trend`} preserveAspectRatio="none"><line x1={pad} y1={height-pad} x2={width-pad} y2={height-pad}/><polyline points={points}/></svg><div className="si-chart-axis"><span>{series[0]?.date?new Date(series[0].date).toLocaleDateString():""}</span><span>{series.at(-1)?.date?new Date(series.at(-1)!.date).toLocaleDateString():""}</span></div></div>
}

export default function HQSchoolsIntelligence(){
 const [days,setDays]=useState(30);const [trend,setTrend]=useState<Trend|null>(null);const [county,setCounty]=useState("");const [detail,setDetail]=useState<CountyDetail|null>(null);const [error,setError]=useState("");const [loading,setLoading]=useState(true)
 const counties=["Baringo","Bomet","Bungoma","Busia","Elgeyo-Marakwet","Embu","Garissa","Homa Bay","Isiolo","Kajiado","Kakamega","Kericho","Kiambu","Kilifi","Kirinyaga","Kisii","Kisumu","Kitui","Kwale","Laikipia","Lamu","Machakos","Makueni","Mandera","Marsabit","Meru","Migori","Mombasa","Murang'a","Nairobi","Nakuru","Nandi","Narok","Nyamira","Nyandarua","Nyeri","Samburu","Siaya","Taita-Taveta","Tana River","Tharaka-Nithi","Trans Nzoia","Turkana","Uasin Gishu","Vihiga","Wajir","West Pokot"]
 const load=useCallback(async()=>{setLoading(true);setError("");const {data,error:e}=await hqSupabase.rpc("hq_school_network_trend",{p_days:days});if(e){setTrend(null);setError("Network trend intelligence is not commissioned in this environment yet.")}else setTrend(data as Trend);setLoading(false)},[days])
 useEffect(()=>{void load()},[load])
 useEffect(()=>{if(!county){setDetail(null);return}void(async()=>{const {data,error:e}=await hqSupabase.rpc("hq_school_network_county_detail",{p_county:county,p_days:days});if(!e)setDetail(data as CountyDetail)})()},[county,days])
 const totals=useMemo(()=>{const last=trend?.series.at(-1);return last?{connected:last.connected_schools,active:last.active_schools,users:last.active_users}:null},[trend])
 return <HQPage title="School Intelligence — Kenya" description="Evidence-backed network trends and county drill-down. Activity and revenue attribution are not treated as retention or institutional payment.">
  <div className="si-stack"><nav className="si-tabs"><Link href="/hq/schools">Overview</Link><Link className="active" href="/hq/schools/intelligence">Intelligence</Link><Link href="/hq/schools/data-quality">Data quality</Link></nav>
   <div className="si-toolbar"><div><span>Period</span><div>{[30,90,365].map(d=><button key={d} className={days===d?"active":""} onClick={()=>setDays(d)}>{d===365?"12M":`${d}D`}</button>)}</div></div><label><span>County detail</span><select value={county} onChange={e=>setCounty(e.target.value)}><option value="">All Kenya</option>{counties.map(c=><option key={c}>{c}</option>)}</select></label></div>
   {error&&<div className="si-notice" role="status">{error}</div>}{loading?<div className="si-empty">Loading school intelligence…</div>:trend?<>
    <section className="si-summary"><div><span>Connected schools</span><strong>{totals?.connected??0}</strong></div><div><span>Active today</span><strong>{totals?.active??0}</strong></div><div><span>Active users today</span><strong>{totals?.users??0}</strong></div></section>
    <HQPanel title="Network trend" description="Daily evidence; connected is cumulative while active schools/users are observed per day."><div className="si-charts"><LineChart series={trend.series} keyName="connected_schools" label="Connected schools"/><LineChart series={trend.series} keyName="active_schools" label="Active schools"/><LineChart series={trend.series} keyName="active_users" label="Active users"/></div><details className="si-table"><summary>Accessible trend data</summary><div><table><thead><tr><th>Date</th><th>Connected</th><th>Active schools</th><th>Active users</th></tr></thead><tbody>{trend.series.map(p=><tr key={p.date}><td>{p.date}</td><td>{p.connected_schools}</td><td>{p.active_schools}</td><td>{p.active_users}</td></tr>)}</tbody></table></div></details></HQPanel>
    {county&&<HQPanel title={`${county} County`} description="County evidence uses canonical school relationships and settlement/order attribution.">{detail?<div className="si-county"><div><span>Teachers</span><strong>{detail.people.teachers}</strong></div><div><span>Learners</span><strong>{detail.people.learners}</strong></div><div><span>Parents</span><strong>{detail.people.parents}</strong></div><div><span>Admins</span><strong>{detail.people.admins}</strong></div><div><span>Active users</span><strong>{detail.activity.active_users}</strong><small>{detail.activity.active_user_change_pct===null?"Previous comparison unavailable":`${detail.activity.active_user_change_pct>0?"+":""}${detail.activity.active_user_change_pct}% vs prior period`}</small></div><div><span>Attributed revenue</span><strong>KES {detail.revenue.attributed_paid_kes.toLocaleString()}</strong><small>Not proof the institution paid</small></div><div><span>Identity backlog</span><strong>{detail.data_quality.pending_identity_candidates}</strong></div><div><span>Events</span><strong>{detail.activity.events}</strong></div></div>:<div className="si-empty">Loading county evidence…</div>}</HQPanel>}
   </>:null}
  </div><style jsx global>{`
   .si-stack{display:grid;gap:14px}.si-tabs{display:flex;gap:6px;overflow:auto}.si-tabs a{padding:11px 14px;border:1px solid ${C.border};border-radius:10px;color:${C.muted};text-decoration:none;font-size:11px;font-weight:850;white-space:nowrap}.si-tabs a.active{background:rgba(59,130,246,.16);color:#fff}.si-toolbar{display:flex;justify-content:space-between;gap:12px;align-items:end;padding:13px;border:1px solid ${C.border};border-radius:13px;background:${C.panel}.si-toolbar span{display:block;color:${C.muted};font-size:9px;font-weight:850;margin-bottom:5px}.si-toolbar>div>div{display:flex;gap:4px}.si-toolbar button,.si-toolbar select{min-height:40px;border:1px solid ${C.border};border-radius:9px;background:rgba(255,255,255,.035);color:#fff;padding:0 11px}.si-toolbar button.active{background:rgba(59,130,246,.2);border-color:rgba(96,165,250,.35)}.si-toolbar select{min-width:170px}.si-notice,.si-empty{padding:14px;border-radius:10px;color:${C.muted};font-size:11px}.si-notice{border:1px solid rgba(245,158,11,.25);background:rgba(245,158,11,.06)}.si-summary{display:grid;grid-template-columns:repeat(3,1fr);gap:8px}.si-summary>div,.si-county>div{padding:12px;border:1px solid ${C.border};border-radius:11px;background:${C.panel}.si-summary span,.si-county span,.si-county small{display:block;color:${C.muted};font-size:9px}.si-summary strong,.si-county strong{display:block;margin-top:6px;font-size:20px}.si-charts{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:10px;padding:13px}.si-chart{min-width:0;padding:11px;border:1px solid ${C.border};border-radius:11px;background:rgba(255,255,255,.018)}.si-chart-head{display:flex;justify-content:space-between;gap:8px;font-size:10px}.si-chart-head span{color:${C.muted}}.si-chart svg{width:100%;height:150px;margin-top:7px}.si-chart line{stroke:rgba(148,163,184,.24);stroke-width:1}.si-chart polyline{fill:none;stroke:#60a5fa;stroke-width:3;vector-effect:non-scaling-stroke}.si-chart-axis{display:flex;justify-content:space-between;color:${C.muted};font-size:8px}.si-table{margin:0 13px 13px;color:${C.muted};font-size:10px}.si-table summary{cursor:pointer}.si-table>div{overflow:auto;margin-top:8px}.si-table table{width:100%;border-collapse:collapse}.si-table th,.si-table td{padding:7px;border-bottom:1px solid ${C.border};text-align:left}.si-county{display:grid;grid-template-columns:repeat(4,1fr);gap:8px;padding:13px}.si-county small{margin-top:4px;line-height:1.35}
   @media(max-width:1100px){.si-charts{grid-template-columns:1fr}.si-county{grid-template-columns:repeat(2,1fr)}}@media(max-width:900px){.hq-sidebar{display:none!important}.hq-page{margin-left:0!important;padding-top:60px!important}.hq-mobile-topbar{display:flex!important;position:fixed!important;top:0!important;left:0!important;right:0!important;z-index:120!important;height:60px!important;padding:0 13px!important;align-items:center!important;justify-content:space-between!important;background:rgba(6,16,29,.96)!important}.hq-bottom-nav{display:grid!important}.si-toolbar{display:block}.si-toolbar label{display:block;margin-top:10px}.si-toolbar select{width:100%}}@media(max-width:520px){.si-summary{grid-template-columns:1fr 1fr}.si-county{grid-template-columns:1fr 1fr}.si-chart svg{height:120px}}
  `}</style>
 </HQPage>
}
