'use client'
import {useMemo,useState} from 'react'
const fmt=(n:number)=>new Intl.NumberFormat('en-KE',{style:'currency',currency:'KES',maximumFractionDigits:0}).format(n)
export default function InvestorPage(){
 const [schools,setSchools]=useState(1000),[users,setUsers]=useState(5),[price,setPrice]=useState(80),[capital,setCapital]=useState(100000),[persona,setPersona]=useState('Teacher')
 const r=useMemo(()=>{const w=schools*users*price;return{w,m:w*52/12,y:w*52}},[schools,users,price])
 const copy:Record<string,string>={Teacher:'Curriculum → scheme → lesson → teaching → assignment → evidence.',Learner:'Learn → practise → revise → submit → improve, beyond the classroom.',Parent:'See progress clearly and know where support is needed.',School:'Connect teachers, classes, curriculum and learning activity in one view.'}
 return <main className="invest"><style>{`.invest{font-family:Inter,system-ui;background:#07111f;color:#f8fafc;min-height:100vh}.wrap{max-width:980px;margin:auto;padding:22px}.hero{padding:70px 0 48px}.eye{color:#67e8f9;font-weight:800;letter-spacing:.12em;text-transform:uppercase;font-size:12px}h1{font-size:clamp(44px,10vw,86px);line-height:.95;margin:14px 0}h2{font-size:clamp(30px,6vw,48px);margin:8px 0 18px}.lead{font-size:clamp(19px,4vw,27px);color:#cbd5e1;max-width:760px}.sec{padding:46px 0;border-top:1px solid #1e293b}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(210px,1fr));gap:14px}.card{background:#0f1c2e;border:1px solid #24364f;border-radius:20px;padding:20px}.flow{display:flex;gap:8px;align-items:center;flex-wrap:wrap}.btn,.pill{border:1px solid #334155;background:#0f1c2e;color:#e2e8f0;border-radius:999px;padding:12px 16px;font-weight:750}.btn{cursor:pointer}.on{background:#22d3ee;color:#06202a;border-color:#22d3ee}.muted{color:#94a3b8}.big{font-size:clamp(27px,6vw,44px);font-weight:850}.controls label{display:block;margin:18px 0 6px;font-weight:700}.controls input{width:100%;accent-color:#22d3ee}.arrow{color:#67e8f9}.note{font-size:13px;color:#94a3b8}.cta{text-align:center;padding:60px 0 90px}.cta a{text-decoration:none;display:inline-block;margin-top:14px}@media(max-width:520px){.wrap{padding:18px}.hero{padding-top:46px}.sec{padding:36px 0}}`}</style><div className="wrap">
 <section className="hero"><div className="eye">VibeSchool · Investor story</div><h1>Learning should not stop when school ends.</h1><p className="lead">VibeSchool connects the Kenyan curriculum, teachers, learners, parents and schools into one continuous learning experience.</p><div className="flow" style={{marginTop:26}}><a className="btn on" href="#story" style={{textDecoration:'none'}}>Explore VibeSchool</a><a className="btn" href="#numbers" style={{textDecoration:'none'}}>Play with the numbers</a></div></section>
 <section className="sec" id="story"><div className="eye">01 · The gap</div><h2>One learner. One day. Several disconnected worlds.</h2><div className="grid"><div className="card"><b>8:00 AM · Classroom</b><p className="muted">A teacher teaches. The curriculum is moving.</p></div><div className="card"><b>4:30 PM · Home</b><p className="muted">The learner leaves school, but learning needs continue.</p></div><div className="card"><b>7:00 PM · Homework</b><p className="muted">The teacher may be unavailable. The parent may not know what was taught.</p></div></div><p className="lead" style={{marginTop:24}}>VibeSchool is the bridge between what happens in class and what happens next.</p></section>
 <section className="sec"><div className="eye">02 · One ecosystem</div><h2>Different people. One learning journey.</h2><div className="flow">{['Teacher','Learner','Parent','School'].map(p=><button key={p} className={'btn '+(persona===p?'on':'')} onClick={()=>setPersona(p)}>{p}</button>)}</div><div className="card" style={{marginTop:18}}><div className="big">{persona}</div><p className="lead" style={{fontSize:20}}>{copy[persona]}</p></div></section>
 <section className="sec"><div className="eye">03 · The system</div><h2>Curriculum becomes an experience.</h2><div className="flow">{['Official curriculum','Outcomes','Teacher experience','Learner experience','Assessment','Evidence'].map((x,i)=><span key={x} className="flow"><span className="pill">{x}</span>{i<5&&<span className="arrow">→</span>}</span>)}</div><p className="muted">Build the production system once, improve it continuously, then expand it across subjects.</p></section>
 <section className="sec" id="numbers"><div className="eye">04 · Interactive business model</div><h2>Change the assumptions. See what happens.</h2><div className="grid"><div className="card controls"><label>Schools: {schools.toLocaleString()}</label><input type="range" min="100" max="20000" step="100" value={schools} onChange={e=>setSchools(+e.target.value)}/><label>Paying users per school: {users}</label><input type="range" min="1" max="30" value={users} onChange={e=>setUsers(+e.target.value)}/><label>Weekly payment: {fmt(price)}</label><input type="range" min="20" max="500" step="10" value={price} onChange={e=>setPrice(+e.target.value)}/></div><div className="card"><span className="muted">Weekly</span><div className="big">{fmt(r.w)}</div><span className="muted">Average monthly</span><div className="big">{fmt(r.m)}</div><span className="muted">Annualised</span><div className="big">{fmt(r.y)}</div></div></div><p className="note">Illustrative scenario only — not current revenue, a forecast, or a financial guarantee.</p></section>
 <section className="sec"><div className="eye">05 · Capital</div><h2>Investment scales the speed, not the vision.</h2><div className="flow">{[50000,100000,500000,1000000].map(n=><button key={n} className={'btn '+(capital===n?'on':'')} onClick={()=>setCapital(n)}>{fmt(n)}</button>)}</div><div className="card" style={{marginTop:18}}><div className="big">{fmt(capital)}</div><div className="grid" style={{marginTop:16}}><div><b>35% · Product & infrastructure</b><p className="muted">{fmt(capital*.35)}</p></div><div><b>25% · Curriculum & content</b><p className="muted">{fmt(capital*.25)}</p></div><div><b>25% · Distribution & customer proof</b><p className="muted">{fmt(capital*.25)}</p></div><div><b>15% · Operations & reserve</b><p className="muted">{fmt(capital*.15)}</p></div></div></div><p className="note">Illustrative use of funds. Final allocation, investment structure and ownership are agreed separately.</p></section>
 <section className="sec"><div className="eye">06 · What capital must prove</div><h2>Money has a job.</h2><div className="flow">{['Capital','Product readiness','Users','Paying customers','Retention','Scale what works'].map((x,i)=><span key={x} className="flow"><span className="pill">{x}</span>{i<5&&<span className="arrow">→</span>}</span>)}</div></section>
 <section className="sec"><div className="eye">07 · Vision</div><h2>Start with a lesson. Build the infrastructure around learning.</h2><p className="lead">Today: help a teacher teach and a learner learn. Next: connect the parent and school. Long term: make high-quality Kenyan learning accessible wherever the learner is.</p></section>
 <section className="cta"><div className="eye">VibeSchool</div><h2>Built for Kenyan education.</h2><p className="muted">A better learning experience can begin with one teacher, one learner and one lesson.</p><a className="btn on" href="/">Explore the product</a></section>
 </div></main>
}