"use client"

import { useCallback,useEffect,useState } from "react"
import { useRouter } from "next/navigation"
import { supabase } from "@/lib/supabase"
const rpc=supabase.rpc.bind(supabase) as any
const C={bg:"#07111f",panel:"#0d1b2f",line:"rgba(255,255,255,.09)",text:"#f8fafc",muted:"rgba(255,255,255,.48)",green:"#34d399",violet:"#a78bfa",red:"#fb7185"}
type Voucher={id:string;sponsor_name:string;title:string;description:string|null;category:string;xp_cost:number;total_pool:number;claimed_count:number;is_active:boolean;remaining:number;created_at:string}
const empty={id:null as string|null,sponsor:"",title:"",description:"",category:"physical",xp:100,pool:1,active:true}
export default function FunHubStudio(){const router=useRouter();const[items,setItems]=useState<Voucher[]>([]);const[form,setForm]=useState(empty);const[busy,setBusy]=useState(false);const[error,setError]=useState("")
 const load=useCallback(async()=>{const{data,error:e}=await rpc("hq_list_funhub_vouchers",{p_include_inactive:true});if(e)setError(e.message);else setItems(data??[])},[]);useEffect(()=>{void load()},[load])
 function edit(v:Voucher){setForm({id:v.id,sponsor:v.sponsor_name,title:v.title,description:v.description??"",category:v.category,xp:v.xp_cost,pool:v.total_pool,active:v.is_active})}
 async function save(){setBusy(true);setError("");const{error:e}=await rpc("hq_upsert_funhub_voucher",{p_id:form.id,p_sponsor_name:form.sponsor,p_title:form.title,p_description:form.description,p_category:form.category,p_xp_cost:form.xp,p_total_pool:form.pool,p_is_active:form.active});if(e)setError(e.message);else{setForm(empty);await load()}setBusy(false)}
 return <main style={{minHeight:"100dvh",background:C.bg,color:C.text,padding:18,fontFamily:"Inter,system-ui,sans-serif"}}><div style={{maxWidth:1050,margin:"0 auto"}}><button onClick={()=>router.push("/hq/studio")} style={btn}>← Studio</button><h1>FunHub Economy</h1><p style={{color:C.muted,fontSize:12}}>Real sponsor voucher inventory and XP pricing. Claimed stock cannot be reduced below claims already made.</p>{error&&<div style={{color:"#fecdd3"}}>{error}</div>}<div style={{display:"grid",gridTemplateColumns:"minmax(300px,.7fr) minmax(0,1fr)",gap:12}}><section style={panel}><h2 style={{fontSize:14}}>{form.id?'Edit voucher':'New voucher'}</h2>{[['Sponsor','sponsor'],['Title','title'],['Description','description']].map(([label,key])=><label key={key} style={lab}>{label}<input value={(form as any)[key]} onChange={e=>setForm({...form,[key]:e.target.value})} style={input}/></label>)}<label style={lab}>Category<select value={form.category} onChange={e=>setForm({...form,category:e.target.value})} style={input}><option value="physical">Physical</option><option value="digital">Digital</option><option value="experience">Experience</option></select></label><label style={lab}>XP cost<input type="number" min={0} value={form.xp} onChange={e=>setForm({...form,xp:Number(e.target.value)||0})} style={input}/></label><label style={lab}>Total pool<input type="number" min={0} value={form.pool} onChange={e=>setForm({...form,pool:Number(e.target.value)||0})} style={input}/></label><label style={{...lab,display:'flex',gap:8,alignItems:'center'}}><input type="checkbox" checked={form.active} onChange={e=>setForm({...form,active:e.target.checked})}/> Active</label><div style={{display:'flex',gap:8}}><button disabled={busy} onClick={()=>void save()} style={{...btn,color:C.green}}>{busy?'Saving…':'Save voucher'}</button>{form.id&&<button onClick={()=>setForm(empty)} style={btn}>Cancel</button>}</div></section><section style={panel}>{items.length===0?<div style={{color:C.muted}}>No vouchers configured.</div>:items.map((v,i)=><button key={v.id} onClick={()=>edit(v)} style={{width:'100%',textAlign:'left',border:0,borderTop:i?`1px solid ${C.line}`:0,background:'transparent',color:C.text,padding:'12px 4px',cursor:'pointer'}}><div style={{display:'flex',justifyContent:'space-between',gap:12}}><div><strong>{v.title}</strong><div style={{fontSize:10.5,color:C.muted,marginTop:4}}>{v.sponsor_name} · {v.category} · {v.claimed_count} claimed / {v.total_pool} pool</div></div><div style={{textAlign:'right'}}><b style={{color:C.violet}}>{v.xp_cost} XP</b><div style={{fontSize:10,color:v.is_active?C.green:C.red,marginTop:4}}>{v.is_active?'ACTIVE':'INACTIVE'} · {v.remaining} left</div></div></div></button>)}</section></div></div></main>}
const panel:React.CSSProperties={background:C.panel,border:`1px solid ${C.line}`,borderRadius:14,padding:14};const btn:React.CSSProperties={border:`1px solid ${C.line}`,background:"rgba(255,255,255,.04)",color:C.text,borderRadius:9,padding:"8px 10px",fontSize:11,fontWeight:800,cursor:"pointer"};const input:React.CSSProperties={width:'100%',boxSizing:'border-box',background:'#0a1628',border:`1px solid ${C.line}`,borderRadius:9,padding:10,color:C.text,marginTop:5};const lab:React.CSSProperties={display:'block',fontSize:10,color:C.muted,fontWeight:800,marginBottom:10}
