import "jsr:@supabase/functions-js/edge-runtime.d.ts"
import { createClient } from "https://esm.sh/@supabase/supabase-js@2"
import { groqText, invokeCyborgEdgeModel } from "../_shared/cyborg-model-client.ts"
const H={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type","Content-Type":"application/json"}
const R=(b:unknown,s=200)=>new Response(JSON.stringify(b),{status:s,headers:H})
const TAVILY=Deno.env.get("TAVILY_API_KEY")??"",MODEL=Deno.env.get("CURRICULUM_EDITORIAL_MODEL")??"llama-3.3-70b-versatile"
type J=Record<string,any>
const enums={decision:["proposal","no_change"],proposal_type:["correction","enrichment","new_content","assessment_update","teacher_guidance","review_candidate"],curriculum_relevance:["C1","C2","C3","C4"],verification_status:["verified","insufficient_evidence","unverified"],volatility:["low","medium","high"]}
function parse(raw:string){const m=raw.match(/<editorial_json>([\s\S]*?)<\/editorial_json>/i)?.[1]||raw;try{return JSON.parse(m.trim().replace(/^```json\s*/i,"").replace(/```$/,""))}catch{return null}}
function valid(o:J,blockCount:number){if(!o||!enums.decision.includes(o.decision))return false;if(o.decision==="no_change")return typeof o.diagnosis==="string";return enums.proposal_type.includes(o.proposal_type)&&enums.curriculum_relevance.includes(o.curriculum_relevance)&&enums.verification_status.includes(o.verification_status)&&enums.volatility.includes(o.volatility)&&Number.isFinite(Number(o.confidence))&&Number(o.confidence)>=0&&Number(o.confidence)<=1&&Number.isInteger(Number(o.target_sequence))&&Number(o.target_sequence)>=1&&Number(o.target_sequence)<=blockCount&&typeof o.proposed_content==="string"&&o.proposed_content.trim().length>=40&&typeof o.rationale==="string"&&Array.isArray(o.followup_actions||[])}
function words(s:string){return s.toLowerCase().replace(/[^a-z0-9\s]/g," ").split(/\s+/).filter(Boolean)}
function ngrams(s:string,n=8){const w=words(s),set=new Set<string>();for(let i=0;i<=w.length-n;i++)set.add(w.slice(i,i+n).join(" "));return set}
function overlap(a:string,b:string){const A=ngrams(a),B=ngrams(b);if(!A.size||!B.size)return 0;let hit=0;for(const x of A)if(B.has(x))hit++;return hit/Math.min(A.size,B.size)}
Deno.serve(async(req)=>{if(req.method==="OPTIONS")return new Response("ok",{headers:H});if(req.method!=="POST")return R({error:"method_not_allowed"},405)
 const auth=req.headers.get("Authorization");if(!auth)return R({error:"Unauthorized"},401);const url=Deno.env.get("SUPABASE_URL")!,anon=Deno.env.get("SUPABASE_ANON_KEY")!,service=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!,userDb=createClient(url,anon,{global:{headers:{Authorization:auth}}}),admin=createClient(url,service);let action:J|null=null
 try{
  const{data:{user}}=await userDb.auth.getUser();if(!user)return R({error:"Unauthorized"},401);const{data:isOwner}=await userDb.rpc("is_platform_owner");if(!isOwner)return R({error:"HQ platform owner required"},403)
  const body=await req.json().catch(()=>({})) as J;const{data:claimed,error:claimErr}=await userDb.rpc("hq_claim_next_editorial_action",{p_action_id:body.action_id||null});if(claimErr)throw claimErr;action=claimed as J|null;if(!action)return R({status:"no_work"})
  const[{data:signal,error:sErr},{data:chapter,error:cErr}]=await Promise.all([admin.from("curriculum_content_health_signals").select("*").eq("id",action.health_signal_id).single(),admin.from("vibe_chapters").select("id,publication_id,title,number,learning_outcomes,cbc_strand,curriculum_id").eq("id",action.chapter_id).single()]);if(sErr)throw sErr;if(cErr)throw cErr
  const{data:blocks,error:bErr}=await admin.from("content_blocks").select("id,legacy_block_id,sequence,block_type,title,plain_text,is_assessable").eq("chapter_id",chapter.id).order("sequence");if(bErr)throw bErr
  const sources:J[]=[];const researchNeeded=["fact_check","investigate","rights_review"].includes(action.action_type);if(researchNeeded&&TAVILY){const q=`${chapter.title} ${chapter.cbc_strand||""} ${action.rationale} Kenya curriculum authoritative source`;const t=await fetch("https://api.tavily.com/search",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({api_key:TAVILY,query:q,max_results:6,include_answer:false})});if(t.ok){const td=await t.json();for(const r of td.results||[])sources.push({url:r.url,title:r.title,content:String(r.content||"").slice(0,3500),score:Number(r.score||0)})}}
  const blockText=(blocks||[]).map((b:J)=>`BLOCK ${b.sequence} (${b.legacy_block_id||b.id}) [${b.block_type}]\n${b.plain_text||""}`).join("\n\n"),evidence=sources.map((s,i)=>`SOURCE ${i+1}\nURL: ${s.url}\nTITLE: ${s.title}\nEVIDENCE: ${s.content}`).join("\n\n")
  const prompt=`You are Vibeschool's senior editorial board. Diagnose before editing. Preserve correct material. Use natural, precise, warm, intellectually serious Kenyan educational prose. Never copy source wording. Distinguish established facts from emerging evidence. Prefer the smallest useful change. Return no_change when evidence does not justify editing.\n\nACTION ${action.action_type}; PRIORITY ${action.priority}; RATIONALE ${action.rationale}\nSIGNAL ${signal.signal_type}; severity=${signal.severity}; score=${signal.score}; evidence_count=${signal.evidence_count}\nSIGNAL EVIDENCE ${JSON.stringify(signal.evidence)}\nCHAPTER ${chapter.title}; STRAND ${chapter.cbc_strand||""}; OUTCOMES ${JSON.stringify(chapter.learning_outcomes||[])}\n\nCANONICAL BLOCKS\n${blockText}\n\nSTRUCTURED WEB EVIDENCE\n${evidence||"none"}\n\nReturn ONLY <editorial_json>{"decision":"proposal|no_change","title":"...","diagnosis":"...","proposal_type":"correction|enrichment|new_content|assessment_update|teacher_guidance|review_candidate","curriculum_relevance":"C1|C2|C3|C4","target_sequence":1,"current_content":"...","proposed_content":"...","rationale":"...","confidence":0.0,"verification_status":"verified|insufficient_evidence|unverified","volatility":"low|medium|high","followup_actions":["rewrite_explanation|add_example|add_activity|add_vibelab|expand_assessment|refresh_teacher_guide|fact_check|rights_review"]}</editorial_json>`
  const governed=await invokeCyborgEdgeModel({callerServiceId:"edge.curriculum-intelligence-health-action",actorKey:`user:${user.id}`,externalChatId:`editorial-action:${action.id}`,objective:`Run governed curriculum health editorial action ${action.action_type}`,provider:"groq",model:MODEL,maxTokens:4200,messages:[{role:"user",content:prompt}],metadata:{feature:"curriculum-intelligence-health-action",temperature:0.15,responseFormat:"json_object"},dataClassification:"restricted"});const out=parse(groqText(governed.output));if(!valid(out,(blocks||[]).length))throw new Error("invalid_editorial_output")
  if(out.decision==="no_change"){await admin.from("curriculum_editorial_actions").update({status:"completed",completed_at:new Date().toISOString(),locked_at:null,locked_by:null,output:{decision:"no_change",diagnosis:out.diagnosis,cyborg_mission_id:governed.missionId,cyborg_invocation_id:governed.invocationId}}).eq("id",action.id);await admin.from("curriculum_content_health_signals").update({status:"resolved",updated_at:new Date().toISOString()}).eq("id",signal.id);return R({status:"no_change",action_id:action.id,diagnosis:out.diagnosis,missionId:governed.missionId})}
  const target=(blocks||[]).find((b:J)=>b.sequence===Number(out.target_sequence));if(!target)throw new Error("target_sequence_not_found");const maxOverlap=sources.reduce((m,s)=>Math.max(m,overlap(out.proposed_content,s.content)),0);if(maxOverlap>0.22)throw new Error(`source_similarity_too_high:${maxOverlap.toFixed(3)}`);if(out.verification_status==="verified"&&sources.length<2)out.verification_status="insufficient_evidence"
  const patch={operation:"research_draft",auto_apply:false,sequence:target.sequence,legacy_block_id:target.legacy_block_id||null,health_action_id:action.id,evidence:sources.map(s=>({url:s.url,title:s.title,score:s.score})),followup_actions:out.followup_actions,max_source_similarity:maxOverlap,cyborg_mission_id:governed.missionId,cyborg_invocation_id:governed.invocationId}
  const{data:proposal,error:pErr}=await admin.from("curriculum_intelligence_proposals").insert({publication_id:chapter.publication_id,chapter_id:chapter.id,proposal_type:out.proposal_type,title:out.title||`Editorial review: ${chapter.title}`,claim:out.diagnosis,current_content:target.plain_text||null,proposed_content:out.proposed_content,patch,rationale:out.rationale,curriculum_relevance:out.curriculum_relevance,confidence:Number(out.confidence),verification_status:out.verification_status,volatility:out.volatility,status:"pending_review",generated_by:`cyborg:content_health_editorial:${MODEL}`}).select("id").single();if(pErr)throw pErr
  if(sources.length)await admin.from("curriculum_intelligence_sources").insert(sources.map(s=>({proposal_id:proposal.id,url:s.url,title:s.title,publisher:new URL(s.url).hostname,source_type:"web",authority_score:Math.max(0,Math.min(1,s.score||0)),supports_claim:true,evidence_summary:s.content.slice(0,800)})))
  await admin.from("curriculum_editorial_actions").update({status:"proposal_created",proposal_id:proposal.id,completed_at:new Date().toISOString(),locked_at:null,locked_by:null,output:{diagnosis:out.diagnosis,followup_actions:out.followup_actions,max_source_similarity:maxOverlap,cyborg_mission_id:governed.missionId,cyborg_invocation_id:governed.invocationId},updated_at:new Date().toISOString()}).eq("id",action.id);await admin.from("curriculum_content_health_signals").update({status:"proposal_created",updated_at:new Date().toISOString()}).eq("id",signal.id)
  return R({status:"proposal_created",action_id:action.id,proposal_id:proposal.id,target_sequence:target.sequence,followup_actions:out.followup_actions,max_source_similarity:maxOverlap,missionId:governed.missionId,lineage:governed.lineage})
 }catch(e){const msg=e instanceof Error?e.message:String(e);console.error(msg);if(action?.id){const{error}=await userDb.rpc("hq_fail_editorial_action",{p_action_id:action.id,p_error:msg});if(error)console.error("fail_state_update",error.message)}return R({error:msg},500)}
})
