"use client"
export const dynamic="force-dynamic"
import {useCallback,useEffect,useMemo,useState} from "react"
import {hqSupabase} from "@/lib/hq/supabase"
import {HQPage,HQPanel,HQ_THEME as C,hqButtonStyle} from "@/components/hq/HQShell"
type School={school_id:string;school_name:string;school_status:string;current_learners:number;teachers:number;attendance_marks_7d:number;learners_with_attendance_7d:number;homework_created_7d:number;homework_submissions_7d:number;learners_with_parent_link:number;risk_reasons:string[];risk_count:number}
type Snap={observed_at:string;schools:School[]}
const label=(v:string)=>v.replaceAll("_"," ").replace(/\b\w/g,m=>m.toUpperCase())
export default function SchoolSuccessPage(){const[data,setData]=useState<Snap|null>(null),[error,setError]=useState(""),[loading,setLoading]=useState(true);const load=useCallback(async()=>{setLoading(true);setError("");const{data,error}=await hqSupabase.rpc("hq_school_success_snapshot",{p_limit:150});if(error)setError(error.message);else setData(data as Snap);setLoading(false)},[]);useEffect(()=>{void load()},[load]);const summary=useMemo(()=>{const rows=data?.schools??[];return{total:rows.length,attention:rows.filter(s=>s.risk_count>0).length,noTeachers:rows.filter(s=>s.current_learners>0&&s.teachers===0).length,noAttendance:rows.filter(s=>s.current_learners>0&&s.attendance_marks_7d===0).length}},[data]);return <HQPage title="School Success" description="Explainable adoption and operational evidence by school · no opaque health score" actions={<button onClick={()=>void load()} disabled={loading} style={hqButtonStyle}>{loading?"Refreshing…":"Refresh"}</button>}>
{error&&<div role="alert" style={{padding:11,border:`1px solid ${C.red}55`,borderRadius:10,color:"#fecaca",marginBottom:12}}>{error}</div>}
<section style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(140px,1fr))",gap:9,marginBottom:12}}>{[["Schools observed",summary.total,C.blue],["Need attention",summary.attention,summary.attention?C.amber:C.green],["Learners, no teacher",summary.noTeachers,summary.noTeachers?C.red:C.green],["No attendance · 7d",summary.noAttendance,summary.noAttendance?C.amber:C.green]].map(([a,v,t])=><div key={String(a)} style={{padding:13,border:`1px solid ${C.border}`,borderRadius:13,background:C.panelSoft}}><strong style={{fontSize:23,color:String(t)}}>{String(v)}</strong><div style={{fontSize:10.5,color:C.muted,marginTop:4}}>{String(a)}</div></div>)}</section>
<HQPanel title="Institutional operating evidence" description="Each risk is traceable to a visible component. Zero activity is shown as zero evidence, not interpreted as a hidden score."><div style={{display:"grid"}}>{data?.schools?.length?data.schools.map((s,i)=><article key={s.school_id} style={{padding:14,borderTop:i?`1px solid ${C.border}`:"none"}}><div style={{display:"flex",gap:8,alignItems:"center",flexWrap:"wrap"}}><strong style={{fontSize:13}}>{s.school_name}</strong><span style={{fontSize:9.5,color:s.school_status==="active"?C.green:C.amber}}>{s.school_status.toUpperCase()}</span>{s.risk_count>0&&<span style={{fontSize:9.5,color:C.amber}}>{s.risk_count} risk signal{s.risk_count===1?"":"s"}</span>}</div><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(115px,1fr))",gap:7,marginTop:10}}>{[["Current learners",s.current_learners],["Teachers",s.teachers],["Attendance marks · 7d",s.attendance_marks_7d],["Learners seen · 7d",s.learners_with_attendance_7d],["Homework created · 7d",s.homework_created_7d],["Submissions · 7d",s.homework_submissions_7d],["Learners with parent link",s.learners_with_parent_link]].map(([a,v])=><div key={String(a)} style={{padding:8,borderRadius:9,background:"rgba(255,255,255,.025)"}}><strong style={{fontSize:14}}>{String(v)}</strong><div style={{fontSize:9.5,color:C.muted}}>{String(a)}</div></div>)}</div>{s.risk_reasons.length>0&&<div style={{display:"flex",gap:6,flexWrap:"wrap",marginTop:10}}>{s.risk_reasons.map(r=><span key={r} style={{padding:"5px 7px",borderRadius:999,border:`1px solid ${C.amber}45`,color:"#fde68a",fontSize:9.5}}>{label(r)}</span>)}</div>}</article>):<div style={{padding:24,color:C.muted}}>{loading?"Loading school evidence…":"No school evidence is available."}</div>}</div></HQPanel>
</HQPage>}
