"use client"

import { useCallback, useEffect, useState } from "react"
import { useRouter } from "next/navigation"
import { hqSupabase } from "@/lib/hq/supabase"

type Target={id:string;label:string;subject:string|null;grade:string|null;cadence:string;enabled:boolean;last_checked_at:string|null;next_check_at:string|null}
type Run={id:string;watch_target_id:string|null;status:string;trigger_type:string;started_at:string;completed_at:string|null;model:string|null;search_requests:number;proposals_created:number;sources_found:number;summary:string|null;error:string|null}
type Proposal={id:string;title:string;status:string;editorial_status:string;chapter_id:string|null;curriculum_relevance:string;verification_status:string}
type RegenJob={id:string;proposal_id:string;job_type:string;status:string;result:any;last_error:string|null;created_at:string;completed_at:string|null}
type HealthSignal={id:string;publication_id:string|null;chapter_id:string|null;signal_type:string;severity:string;score:number;evidence_count:number;status:string;evidence:Record<string,unknown>;last_detected_at:string}
type EditorialAction={id:string;health_signal_id:string|null;chapter_id:string|null;action_type:string;rationale:string;status:string;priority:number;proposal_id:string|null;created_at:string}
type RightsRow={id:string;proposal_id:string|null;source_url:string;source_domain:string|null;rights_class:string;can_quote:boolean;can_adapt:boolean;can_reproduce_media:boolean;notes:string|null}

const supabase=hqSupabase as any
const C={bg:"#0a1628",panel:"#0f1d33",line:"rgba(255,255,255,.08)",text:"#fff",muted:"rgba(255,255,255,.48)",accent:"#10b981",amber:"#f59e0b",red:"#ef4444",blue:"#3b82f6",violet:"#8b5cf6"}
const button=(border:string,color:string)=>({border:`1px solid ${border}`,background:"rgba(255,255,255,.03)",color,borderRadius:8,padding:"9px 11px",minHeight:40,fontSize:10.5,fontWeight:800,cursor:"pointer" as const})
const asArray=<T,>(value:unknown):T[]=>Array.isArray(value)?value as T[]:[]
const humanError=(kind:"load"|"research"|"editorial"|"regeneration"|"action")=>kind==="load"?"Content operations could not be loaded. Nothing was changed. Try again.":kind==="research"?"Research could not start. Nothing was changed. Check your connection and try again.":kind==="editorial"?"Editorial review could not start. Nothing was changed. Try again.":kind==="regeneration"?"Regeneration could not start. Nothing was changed. Refresh before retrying.":"That content action could not be completed. Nothing should be assumed changed; refresh before retrying."

export default function CurriculumIntelligenceEnginePage(){
 const router=useRouter(); const [targets,setTargets]=useState<Target[]>([]); const [runs,setRuns]=useState<Run[]>([]); const [proposals,setProposals]=useState<Proposal[]>([]); const [jobs,setJobs]=useState<RegenJob[]>([]); const [signals,setSignals]=useState<HealthSignal[]>([]); const [actions,setActions]=useState<EditorialAction[]>([]); const [rights,setRights]=useState<RightsRow[]>([]); const [busy,setBusy]=useState<string|null>(null); const [message,setMessage]=useState(""); const [error,setError]=useState("")
 const load=useCallback(async()=>{const [t,r,p,j,h,a,cr]=await Promise.all([
  supabase.from("curriculum_intelligence_watch_targets").select("id,label,subject,grade,cadence,enabled,last_checked_at,next_check_at").order("created_at"),
  supabase.from("curriculum_intelligence_runs").select("id,watch_target_id,status,trigger_type,started_at,completed_at,model,search_requests,proposals_created,sources_found,summary,error").order("started_at",{ascending:false}).limit(30),
  supabase.from("curriculum_intelligence_proposals").select("id,title,status,editorial_status,chapter_id,curriculum_relevance,verification_status").order("generated_at",{ascending:false}).limit(50),
  supabase.from("curriculum_intelligence_regeneration_jobs").select("id,proposal_id,job_type,status,result,last_error,created_at,completed_at").order("created_at",{ascending:false}).limit(50),
  supabase.from("curriculum_content_health_signals").select("id,publication_id,chapter_id,signal_type,severity,score,evidence_count,status,evidence,last_detected_at").order("last_detected_at",{ascending:false}).limit(50),
  supabase.from("curriculum_editorial_actions").select("id,health_signal_id,chapter_id,action_type,rationale,status,priority,proposal_id,created_at").order("priority",{ascending:false}).order("created_at",{ascending:false}).limit(50),
  supabase.from("curriculum_content_rights").select("id,proposal_id,source_url,source_domain,rights_class,can_quote,can_adapt,can_reproduce_media,notes").order("created_at",{ascending:false}).limit(100),
 ]); const e=t.error||r.error||p.error||j.error||h.error||a.error||cr.error; if(e){setError(humanError("load"));setTargets([]);setRuns([]);setProposals([]);setJobs([]);setSignals([]);setActions([]);setRights([])}else{setTargets(asArray<Target>(t.data));setRuns(asArray<Run>(r.data));setProposals(asArray<Proposal>(p.data));setJobs(asArray<RegenJob>(j.data));setSignals(asArray<HealthSignal>(h.data));setActions(asArray<EditorialAction>(a.data));setRights(asArray<RightsRow>(cr.data))}},[])
 useEffect(()=>{void load()},[load])
 const run=async(key:string,kind:"research"|"editorial"|"regeneration"|"action",fn:()=>Promise<{data:any;error:any}>,ok:(d:any)=>string)=>{setBusy(key);setError("");setMessage("");try{const {data,error:e}=await fn();if(e||data?.error)setError(humanError(kind));else setMessage(ok(data))}catch{setError(humanError(kind))}finally{await load();setBusy(null)}}
 const runResearch=()=>run("research","research",()=>supabase.functions.invoke("curriculum-intelligence-research",{body:{}}),d=>d?.status==="no_work"?"No queued research needs processing right now.":`${d?.status||"Research completed"}${d?.proposalId?" · evidence attached to the queued proposal":""}`)
 const prepareEditorial=(id:string)=>run(`editorial:${id}`,"editorial",()=>supabase.functions.invoke("curriculum-intelligence-editorial",{body:{proposal_id:id}}),d=>`Editorial ${d?.status||"completed"}`)
 const enqueueRegeneration=(id:string)=>run(`enqueue:${id}`,"action",()=>supabase.rpc("hq_enqueue_curriculum_intelligence_regeneration",{p_proposal_id:id}),d=>`${Number(d||0)} regeneration jobs queued`)
 const runNextRegeneration=(id?:string)=>run(`regen:${id||"next"}`,"regeneration",()=>supabase.functions.invoke("curriculum-intelligence-regenerate",{body:id?{proposal_id:id}:{}}),d=>`Regeneration ${d?.status||"completed"}${d?.job_type?` · ${d.job_type}`:""}`)
 const refreshHealth=()=>run("health-refresh","action",()=>supabase.rpc("hq_refresh_content_health_signals",{p_publication_id:null}),d=>`Content health refreshed · ${d?.low_mastery_signals_created||0} new mastery signal(s)`)
 const promoteSignal=(id:string)=>run(`promote:${id}`,"action",()=>supabase.rpc("hq_promote_health_signal_to_action",{p_signal_id:id}),d=>`Editorial action queued · ${d?.action_type||"review"} · priority ${d?.priority??"?"}`)
 const runHealthAction=(id?:string)=>run(`health-action:${id||"next"}`,"editorial",()=>supabase.functions.invoke("curriculum-intelligence-health-action",{body:id?{action_id:id}:{}}),d=>`Editorial action ${d?.status||"completed"}${d?.proposal_id?" · proposal sent to HQ inbox":""}`)
 const statusColor=(s:string)=>["completed","prepared","applied","resolved"].includes(s)?C.accent:["failed","rejected","critical"].includes(s)?C.red:["no_change","duplicate"].includes(s)?C.blue:C.amber
 return <div style={{minHeight:"100dvh",background:C.bg,color:C.text,fontFamily:"Inter,system-ui,sans-serif"}}><header className="cpe-header" style={{position:"sticky",top:0,zIndex:20,background:"rgba(10,22,40,.96)",borderBottom:`1px solid ${C.line}`,padding:"14px 18px"}}><div className="cpe-head-inner" style={{maxWidth:1100,margin:"0 auto",display:"flex",justifyContent:"space-between",alignItems:"center",gap:12}}><div><button onClick={()=>router.push("/hq/curriculum-intelligence")} style={{border:0,background:"transparent",color:C.muted,padding:0,cursor:"pointer"}}>← Curriculum Intelligence</button><h1 style={{margin:"4px 0 0",fontSize:20}}>Content Production Engine</h1><div style={{fontSize:12,color:C.muted}}>Research → evidence → editorial review → human approval → regeneration. Published content never changes automatically.</div></div><div className="cpe-actions" style={{display:"flex",gap:8,flexWrap:"wrap",justifyContent:"flex-end"}}><button disabled={!!busy} onClick={()=>void refreshHealth()} style={button(C.blue,C.text)}>Refresh health</button><button disabled={!!busy} onClick={()=>void runHealthAction()} style={button(C.violet,C.text)}>Next editorial action</button><button disabled={!!busy} onClick={()=>void runNextRegeneration()} style={button(C.line,C.text)}>Run regeneration</button><button disabled={!!busy} onClick={()=>void runResearch()} style={{border:0,borderRadius:10,padding:"10px 14px",minHeight:40,background:C.accent,color:"#052e22",fontWeight:900}}>Run next queued research</button></div></div></header><main style={{maxWidth:1100,margin:"0 auto",padding:18}}>
 {error&&<div role="alert" style={{border:`1px solid ${C.red}55`,background:`${C.red}16`,padding:12,borderRadius:12,color:"#fecaca",marginBottom:12}}><strong style={{display:"block"}}>Action not completed</strong><span style={{display:"block",marginTop:4}}>{error}</span></div>}{message&&<div style={{border:`1px solid ${C.accent}55`,background:`${C.accent}12`,padding:12,borderRadius:12,color:"#bbf7d0",marginBottom:12}}>{message}</div>}
 <section style={{background:C.panel,border:`1px solid ${C.line}`,borderRadius:14,padding:14,marginBottom:16}}><div style={{fontWeight:850}}>Content health</div><div style={{fontSize:11,color:C.muted,marginBottom:8}}>Learner and platform evidence can trigger investigation. Signals never change books automatically.</div>{signals.length===0?<div style={{color:C.muted,padding:"14px 0"}}>No content-health signals currently need review.</div>:signals.map(s=><div className="cpe-row" key={s.id} style={{padding:"11px 0",borderTop:`1px solid ${C.line}`,display:"grid",gridTemplateColumns:"1fr auto",gap:10,alignItems:"center"}}><div><strong style={{fontSize:12.5}}>{s.signal_type.replaceAll("_"," ")}</strong><div style={{fontSize:10.5,color:C.muted,marginTop:3}}>{s.severity} · score {Number(s.score).toFixed(2)} · {s.evidence_count} evidence · {s.status.replaceAll("_"," ")}</div></div>{s.status==="open"&&<button disabled={!!busy} onClick={()=>void promoteSignal(s.id)} style={button(C.amber,"#fde68a")}>Create editorial action</button>}</div>)}</section>
 <section style={{background:C.panel,border:`1px solid ${C.line}`,borderRadius:14,padding:14,marginBottom:16}}><div style={{fontWeight:850}}>Editorial actions</div><div style={{fontSize:11,color:C.muted,marginBottom:8}}>Editorial review diagnoses evidence and may create a draft. It may also conclude no change is needed.</div>{actions.length===0?<div style={{color:C.muted,padding:"14px 0"}}>No editorial actions are waiting.</div>:actions.map(a=><div className="cpe-row" key={a.id} style={{padding:"11px 0",borderTop:`1px solid ${C.line}`,display:"grid",gridTemplateColumns:"1fr auto",gap:10,alignItems:"center"}}><div><strong style={{fontSize:12.5}}>{a.action_type.replaceAll("_"," ")}</strong><div style={{fontSize:10.5,color:C.muted,marginTop:3}}>Priority {a.priority} · {a.status.replaceAll("_"," ")}{a.proposal_id?" · proposal created":""}</div><div style={{fontSize:11,color:C.text,marginTop:4}}>{a.rationale}</div></div>{a.status==="queued"&&<button disabled={!!busy} onClick={()=>void runHealthAction(a.id)} style={button(C.violet,"#ddd6fe")}>Run editorial review</button>}</div>)}</section>
 <section style={{background:C.panel,border:`1px solid ${C.line}`,borderRadius:14,padding:14,marginBottom:16}}><div style={{fontWeight:850}}>Research watchlist</div><div style={{fontSize:11,color:C.muted,marginBottom:8}}>These topics are monitored by the research system. The manual control above processes the next governed research job; it does not bypass the queue.</div>{targets.length===0?<div style={{color:C.muted,padding:"14px 0"}}>No research watch targets are available.</div>:targets.map(t=><div className="cpe-row" key={t.id} style={{display:"grid",gridTemplateColumns:"1fr auto",gap:12,alignItems:"center",padding:"11px 0",borderTop:`1px solid ${C.line}`}}><div><div style={{fontSize:13,fontWeight:750}}>{t.label}</div><div style={{fontSize:10.5,color:C.muted}}>{[t.grade,t.subject,t.cadence].filter(Boolean).join(" · ")}</div></div><span style={{fontSize:10.5,color:t.enabled?C.accent:C.muted,fontWeight:800}}>{t.enabled?"Monitoring active":"Monitoring off"}</span></div>)}</section>
 <section style={{background:C.panel,border:`1px solid ${C.line}`,borderRadius:14,padding:14,marginBottom:16}}><div style={{fontWeight:850}}>Editorial proposal pipeline</div>{proposals.length===0?<div style={{color:C.muted,padding:"14px 0"}}>No proposals are waiting.</div>:proposals.map(p=><div className="cpe-row" key={p.id} style={{padding:"11px 0",borderTop:`1px solid ${C.line}`,display:"grid",gridTemplateColumns:"1fr auto",gap:10,alignItems:"center"}}><div><strong style={{fontSize:12.5}}>{p.title}</strong><div style={{fontSize:10.5,color:C.muted}}>{p.status.replaceAll("_"," ")} · editorial {p.editorial_status.replaceAll("_"," ")} · {p.curriculum_relevance} · {p.verification_status}</div></div><div style={{display:"flex",gap:6,flexWrap:"wrap"}}>{p.chapter_id&&p.editorial_status!=="prepared"&&p.status!=="rejected"&&<button disabled={!!busy} onClick={()=>void prepareEditorial(p.id)} style={button(C.violet,"#ddd6fe")}>Prepare patch</button>}{p.status==="applied"&&<button disabled={!!busy} onClick={()=>void enqueueRegeneration(p.id)} style={button(C.accent,"#bbf7d0")}>Queue regeneration</button>}</div></div>)}</section>
 <section style={{background:C.panel,border:`1px solid ${C.line}`,borderRadius:14,padding:14,marginBottom:16}}><div style={{fontWeight:850}}>Source rights & provenance</div><div style={{fontSize:11,color:C.muted,marginBottom:8}}>Public availability never means permission to reproduce. Media remains blocked unless rights are explicit.</div>{rights.length===0?<div style={{color:C.muted,padding:"14px 0"}}>No source-rights records yet.</div>:rights.map(x=><div key={x.id} style={{padding:"9px 0",borderTop:`1px solid ${C.line}`}}><div style={{display:"flex",justifyContent:"space-between",gap:8,flexWrap:"wrap"}}><span style={{fontSize:11.5,overflowWrap:"anywhere"}}>{x.source_domain||x.source_url}</span><strong style={{fontSize:10.5,color:x.rights_class==="do_not_reproduce"?C.red:x.rights_class==="unknown_review_required"?C.amber:C.accent}}>{x.rights_class.replaceAll("_"," ")}</strong></div><div style={{fontSize:10,color:C.muted}}>quote {x.can_quote?"yes":"no"} · adapt {x.can_adapt?"yes":"no"} · reproduce media {x.can_reproduce_media?"yes":"no"}</div></div>)}</section>
 <section style={{background:C.panel,border:`1px solid ${C.line}`,borderRadius:14,padding:14,marginBottom:16}}><div style={{fontWeight:850}}>Regeneration & QA</div>{jobs.length===0?<div style={{color:C.muted,padding:"14px 0"}}>No regeneration jobs.</div>:jobs.map(j=><div key={j.id} style={{padding:"10px 0",borderTop:`1px solid ${C.line}`}}><div style={{display:"flex",justifyContent:"space-between",gap:8}}><strong style={{fontSize:12}}>{j.job_type.replaceAll("_"," ")}</strong><span style={{fontSize:10,fontWeight:850,color:statusColor(j.status)}}>{j.status}</span></div></div>)}</section>
 <section style={{background:C.panel,border:`1px solid ${C.line}`,borderRadius:14,padding:14}}><div style={{display:"flex",justifyContent:"space-between",gap:10}}><div><div style={{fontWeight:850}}>Recent research runs</div><div style={{fontSize:11,color:C.muted}}>A human summary of every research attempt.</div></div><button onClick={()=>void load()} style={button(C.line,C.text)}>Refresh</button></div>{runs.length===0?<div style={{color:C.muted,padding:"14px 0"}}>No recent research runs.</div>:runs.map(r=><div key={r.id} style={{padding:"11px 0",borderTop:`1px solid ${C.line}`}}><div style={{display:"flex",justifyContent:"space-between",gap:8,flexWrap:"wrap"}}><strong style={{fontSize:12}}>{r.status.replaceAll("_"," ")}</strong><span style={{fontSize:10,color:statusColor(r.status)}}>{new Date(r.started_at).toLocaleString("en-KE")}</span></div><div style={{fontSize:10.5,color:C.muted}}>{r.search_requests} searches · {r.sources_found} sources · {r.proposals_created} proposals{r.model?` · ${r.model}`:""}</div>{r.summary&&<div style={{fontSize:11,marginTop:4}}>{r.summary}</div>}</div>)}</section>
 </main><style jsx global>{`@media(max-width:720px){.cpe-header{top:60px!important}.cpe-head-inner{display:block!important}.cpe-actions{margin-top:12px;display:grid!important;grid-template-columns:1fr 1fr}.cpe-actions button{width:100%}.cpe-row{grid-template-columns:1fr!important}.cpe-row>button,.cpe-row>div+div{justify-self:stretch}.cpe-row button{width:100%}}@media(max-width:380px){.cpe-actions{grid-template-columns:1fr}}`}</style></div>
}
