"use client"

export const dynamic="force-dynamic"

import Link from "next/link"
import { useCallback, useEffect, useState } from "react"
import { hqSupabase } from "@/lib/hq/supabase"
import { HQPage, HQPanel, HQ_THEME as C, hqButtonStyle } from "@/components/hq/HQShell"

type Candidate={id:string;status:string;confidence:number|null;match_reason:string|null;directory_name:string|null;directory_county:string|null;directory_sub_county:string|null}
type Request={id:string;status:string;name:string;county:string|null;sub_county:string|null;ward:string|null;level:string|null;school_code:string|null;alternative_name:string|null;notes:string|null}
type Queue={candidates:Candidate[];requests:Request[]}
type TeacherClaim={id:string;reference_code:string;status:string;requested_levels:string[];created_at:string;school_name:string|null;county:string|null;teacher_name:string|null;school_id:string|null;directory_school_id:string|null;discovery_request_id:string|null}
type Canonical={id:string;name:string;county:string|null;sub_county:string|null;source:string}

type Target={kind:"candidate"|"request";id:string}

export default function HQSchoolDataQualityPage(){
 const [queue,setQueue]=useState<Queue>({candidates:[],requests:[]});const [claims,setClaims]=useState<TeacherClaim[]>([]);const [loading,setLoading]=useState(true);const [error,setError]=useState("");const [busy,setBusy]=useState("");const [dialog,setDialog]=useState<Target|null>(null);const [query,setQuery]=useState("");const [rows,setRows]=useState<Canonical[]>([]);const [selected,setSelected]=useState<Canonical|null>(null);const [alias,setAlias]=useState("");const [note,setNote]=useState("")
 const refresh=useCallback(async()=>{setLoading(true);setError("");const [identity,teacherClaims]=await Promise.all([hqSupabase.rpc("hq_list_school_identity_queue",{p_status:"pending",p_limit:100}),hqSupabase.rpc("hq_list_teacher_school_claims",{p_status:"pending",p_limit:100})]);if(identity.error||teacherClaims.error){setError("HQ could not access one or more owner-authorized reconciliation services.");setQueue({candidates:[],requests:[]});setClaims([])}else{setQueue((identity.data||{candidates:[],requests:[]}) as Queue);setClaims((teacherClaims.data||[]) as TeacherClaim[])}setLoading(false)},[])
 useEffect(()=>{void refresh()},[refresh])
 useEffect(()=>{if(!dialog||query.trim().length<2){setRows([]);return}const t=setTimeout(async()=>{const {data,error:e}=await hqSupabase.rpc("search_school_directory",{p_query:query.trim(),p_level:null,p_county:null,p_sub_county:null,p_lat:null,p_lng:null,p_limit:20});if(!e)setRows(((data||[]) as Canonical[]).filter(x=>x.source==="CANONICAL"))},180);return()=>clearTimeout(t)},[dialog,query])
 const open=(target:Target)=>{setDialog(target);setQuery("");setRows([]);setSelected(null);setAlias("");setNote("");setError("")}
 const act=async(target:Target,action:"matched"|"new"|"created"|"rejected")=>{setBusy(target.id);setError("");const {error:e}=target.kind==="candidate"?await hqSupabase.rpc("hq_review_school_identity_candidate",{p_candidate_id:target.id,p_action:action==="created"?"new":action,p_canonical_school_id:action==="matched"?selected?.id:null,p_alias:alias.trim()||null,p_note:note.trim()||null}):await hqSupabase.rpc("hq_resolve_school_discovery_request",{p_request_id:target.id,p_action:action==="new"?"created":action,p_canonical_school_id:action==="matched"?selected?.id:null,p_school_name:null,p_alias:alias.trim()||null,p_note:note.trim()||null});if(e)setError("The identity action could not be completed. No school identity was changed.");else{setDialog(null);await refresh()}setBusy("")}
 const reviewClaim=async(id:string,action:"approved"|"rejected"|"needs_information")=>{const reviewNote=action==="approved"?null:window.prompt(action==="needs_information"?"What information should the teacher provide?":"Why is this claim rejected?");if(action!=="approved"&&!reviewNote)return;setBusy(id);setError("");const {error:e}=await hqSupabase.rpc("review_teacher_school_claim",{p_claim_id:id,p_action:action,p_note:reviewNote});if(e)setError(`Teacher claim review failed: ${e.message}`);else await refresh();setBusy("")}
 return <HQPage title="School Data Quality" description="Identity reconciliation, discovery requests and canonical-link review. This workspace is operational; it is not the Schools overview.">
  <div className="dq-stack">
   <div className="dq-top"><Link href="/hq/schools">← Schools overview</Link><button style={hqButtonStyle} onClick={()=>void refresh()}>Refresh</button></div>
   {error&&<div className="dq-alert" role="status"><strong>Identity operations unavailable</strong><span>{error}</span></div>}
   <section className="dq-metrics"><HQPanel title="Pending teacher claims"><div className="dq-number">{error?"—":claims.length}</div><small>Membership authority awaiting review</small></HQPanel><HQPanel title="Pending identity matches"><div className="dq-number">{error?"—":queue.candidates.length}</div><small>First 100 owner-review candidates</small></HQPanel><HQPanel title="Pending school requests"><div className="dq-number">{error?"—":queue.requests.length}</div><small>Teacher-submitted discovery requests</small></HQPanel></section>
   <HQPanel title="Teacher-school membership claims" description="Approval grants school membership. Directory-only claims must be reconciled to a canonical school first.">{loading?<div className="dq-empty">Loading teacher claims…</div>:claims.length===0?<div className="dq-empty">No pending teacher-school claims.</div>:<div className="dq-list">{claims.map(c=><article key={c.id}><div><strong>{c.teacher_name||"Teacher"} · {c.school_name||"Unresolved school"}</strong><span>{c.reference_code} · {[c.county,...c.requested_levels].filter(Boolean).join(" · ")}</span><small>{c.school_id?"Canonical school resolved":"Resolve the school identity before approval"}</small></div><div><button disabled={!c.school_id||busy===c.id} onClick={()=>void reviewClaim(c.id,"approved")}>Approve membership</button><button disabled={busy===c.id} onClick={()=>void reviewClaim(c.id,"needs_information")}>Need information</button><button disabled={busy===c.id} onClick={()=>void reviewClaim(c.id,"rejected")}>Reject</button></div></article>)}</div>}</HQPanel>
   <HQPanel title="Directory identity queue" description="Review candidates without silently creating duplicate canonical schools.">{loading?<div className="dq-empty">Loading queue…</div>:queue.candidates.length===0?<div className="dq-empty">{error?"Queue hidden while owner access is unavailable.":"No pending identity candidates in this page."}</div>:<div className="dq-list">{queue.candidates.map(c=><article key={c.id}><div><strong>{c.directory_name||"Unnamed directory record"}</strong><span>{[c.directory_sub_county,c.directory_county].filter(Boolean).join(" · ")||"Location unavailable"}</span><small>{c.match_reason||"No deterministic canonical match"}</small></div><div><button onClick={()=>open({kind:"candidate",id:c.id})}>Match canonical</button><button disabled={busy===c.id} onClick={()=>void act({kind:"candidate",id:c.id},"new")}>Create pending</button><button disabled={busy===c.id} onClick={()=>void act({kind:"candidate",id:c.id},"rejected")}>Reject</button></div></article>)}</div>}</HQPanel>
   <HQPanel title="Teacher discovery requests">{loading?<div className="dq-empty">Loading requests…</div>:queue.requests.length===0?<div className="dq-empty">No pending school discovery requests.</div>:<div className="dq-list">{queue.requests.map(r=><article key={r.id}><div><strong>{r.name}</strong><span>{[r.sub_county,r.county,r.level,r.school_code].filter(Boolean).join(" · ")||"No extra identity data"}</span></div><div><button onClick={()=>open({kind:"request",id:r.id})}>Match existing</button><button disabled={busy===r.id} onClick={()=>void act({kind:"request",id:r.id},"created")}>Create pending</button><button disabled={busy===r.id} onClick={()=>void act({kind:"request",id:r.id},"rejected")}>Reject</button></div></article>)}</div>}</HQPanel>
   {dialog&&<div className="dq-modal" role="dialog" aria-modal="true" aria-label="Match canonical school"><div className="dq-dialog"><h2>Match canonical school</h2><p>Search the canonical registry and choose the exact institution. Name similarity alone is not sufficient when location is ambiguous.</p><input autoFocus value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search canonical school"/>
    <div className="dq-results">{rows.map(r=><button key={r.id} className={selected?.id===r.id?"selected":""} onClick={()=>setSelected(r)}><strong>{r.name}</strong><span>{[r.sub_county,r.county].filter(Boolean).join(" · ")||"Location unavailable"}</span></button>)}</div>
    <input value={alias} onChange={e=>setAlias(e.target.value)} placeholder="Verified alias (optional)"/><textarea value={note} onChange={e=>setNote(e.target.value)} placeholder="Review note (optional)" rows={3}/><div className="dq-actions"><button onClick={()=>setDialog(null)}>Cancel</button><button disabled={!selected||Boolean(busy)} onClick={()=>void act(dialog,"matched")}>{busy?"Saving…":"Confirm match"}</button></div></div></div>}
  </div>
  <style jsx global>{`
   .dq-stack{display:grid;gap:14px}.dq-top{display:flex;justify-content:space-between;align-items:center}.dq-top>a{color:#93c5fd;text-decoration:none;font-size:12px;font-weight:850}.dq-alert{padding:12px;border:1px solid rgba(239,68,68,.28);background:rgba(239,68,68,.07);border-radius:11px}.dq-alert strong,.dq-alert span{display:block}.dq-alert strong{font-size:11px;color:#fecaca}.dq-alert span{font-size:10px;color:${C.muted};margin-top:3px}.dq-metrics{display:grid;grid-template-columns:repeat(3,1fr);gap:10px}.dq-number{font-size:27px;font-weight:950;padding:14px 14px 2px}.dq-metrics small{display:block;padding:0 14px 14px;color:${C.muted};font-size:9px}.dq-empty{padding:15px;color:${C.muted};font-size:11px}.dq-list{padding:0 13px}.dq-list article{display:flex;justify-content:space-between;gap:15px;padding:13px 0;border-bottom:1px solid ${C.border}.dq-list strong,.dq-list span,.dq-list small{display:block}.dq-list strong{font-size:11px}.dq-list span,.dq-list small{font-size:9px;color:${C.muted};margin-top:4px}.dq-list article>div:last-child{display:flex;gap:6px;flex-wrap:wrap;justify-content:flex-end}.dq-list button,.dq-actions button{min-height:38px;padding:0 10px;border:1px solid ${C.border};border-radius:9px;background:rgba(255,255,255,.035);color:#dbeafe;font-size:9px;font-weight:850;cursor:pointer}.dq-list button:disabled{opacity:.4;cursor:not-allowed}.dq-modal{position:fixed;z-index:200;inset:0;display:grid;place-items:center;padding:18px;background:rgba(2,6,23,.82)}.dq-dialog{width:min(100%,560px);max-height:90dvh;overflow:auto;padding:18px;border:1px solid ${C.border};border-radius:15px;background:${C.panel};color:#fff}.dq-dialog h2{margin:0;font-size:17px}.dq-dialog p{color:${C.muted};font-size:10px;line-height:1.5}.dq-dialog>input,.dq-dialog textarea{width:100%;margin-top:8px;padding:11px;border:1px solid ${C.border};border-radius:9px;background:rgba(255,255,255,.035);color:#fff}.dq-results{display:grid;gap:6px;margin-top:8px}.dq-results button{padding:10px;text-align:left;border:1px solid ${C.border};border-radius:9px;background:transparent;color:#fff}.dq-results button.selected{border-color:#22c55e;background:rgba(34,197,94,.08)}.dq-results strong,.dq-results span{display:block}.dq-results strong{font-size:11px}.dq-results span{font-size:9px;color:${C.muted};margin-top:3px}.dq-actions{display:flex;justify-content:flex-end;gap:7px;margin-top:11px}
   @media(max-width:720px){.dq-list article{display:block}.dq-list article>div:last-child{justify-content:flex-start;margin-top:10px}.dq-list button{min-height:42px}.dq-dialog{padding:14px}}
   @media(max-width:390px){.dq-metrics{grid-template-columns:1fr}}
  `}</style>
 </HQPage>
}
