"use client"

import { useCallback,useEffect,useState } from "react"
import { useRouter } from "next/navigation"
import { supabase } from "@/lib/supabase"
const rpc=supabase.rpc.bind(supabase) as any
const C={bg:"#07111f",panel:"#0d1b2f",line:"rgba(255,255,255,.09)",text:"#f8fafc",muted:"rgba(255,255,255,.48)",green:"#34d399",amber:"#f59e0b",red:"#fb7185",blue:"#60a5fa"}
type Flag={id:string;question_text:string;flag_type:string;reason:string|null;status:string;created_at:string};type Incident={id:string;incident_type:string;severity:string;status:string;title:string;summary:string;route:string|null;detected_at:string;owner_department:string|null;verification_status:string};type Request={id:string;requested_score:number;request_reason:string;status:string;created_at:string};type Queue={exam_flags:Flag[];incidents:Incident[];assessment_requests:Request[]}
export default function ModerationStudio(){const router=useRouter();const[data,setData]=useState<Queue>({exam_flags:[],incidents:[],assessment_requests:[]});const[error,setError]=useState("");const[busy,setBusy]=useState("")
 const load=useCallback(async()=>{const{data:d,error:e}=await rpc("hq_list_moderation_queue",{p_limit:300});if(e)setError(e.message);else setData(d??{exam_flags:[],incidents:[],assessment_requests:[]})},[]);useEffect(()=>{void load()},[load]);async function decide(source:string,id:string,decision:string){const reason=source==='incident'||source==='assessment_request'?window.prompt('Decision note / evidence (recommended):')??'':null;setBusy(id);const{error:e}=await rpc("hq_decide_moderation_item",{p_source:source,p_id:id,p_decision:decision,p_reason:reason});if(e)setError(e.message);else await load();setBusy("")}
 return <main style={{minHeight:'100dvh',background:C.bg,color:C.text,padding:18,fontFamily:'Inter,system-ui,sans-serif'}}><div style={{maxWidth:1100,margin:'0 auto'}}><button onClick={()=>router.push('/hq/studio')} style={btn}>← Studio</button><h1>Moderation & Trust</h1><p style={{color:C.muted,fontSize:12}}>Unified owner queue over real exam flags, company incidents and assessment moderation requests.</p>{error&&<div style={{color:'#fecdd3'}}>{error}</div>}<Section title={`Exam flags · ${data.exam_flags.length}`}>{data.exam_flags.map((x,i)=><Row key={x.id} border={i>0} title={x.question_text||'Flagged exam question'} meta={`${x.flag_type} · ${x.status} · ${x.reason||'No reason'}`}><button disabled={busy===x.id} onClick={()=>void decide('exam_flag',x.id,'reviewed')} style={{...btn,color:C.green}}>Reviewed</button><button disabled={busy===x.id} onClick={()=>void decide('exam_flag',x.id,'dismissed')} style={{...btn,color:C.red}}>Dismiss</button></Row>)}</Section><Section title={`HQ incidents · ${data.incidents.length}`}>{data.incidents.map((x,i)=><Row key={x.id} border={i>0} title={x.title} meta={`${x.severity} · ${x.status} · ${x.owner_department||'unassigned'} · verification ${x.verification_status}`}><button disabled={busy===x.id} onClick={()=>void decide('incident',x.id,'acknowledged')} style={{...btn,color:C.amber}}>Acknowledge</button><button disabled={busy===x.id} onClick={()=>void decide('incident',x.id,'resolved')} style={{...btn,color:C.green}}>Resolve</button></Row>)}</Section><Section title={`Assessment moderation · ${data.assessment_requests.length}`}>{data.assessment_requests.map((x,i)=><Row key={x.id} border={i>0} title={x.request_reason} meta={`requested score ${x.requested_score} · ${x.status}`}><button disabled={busy===x.id||x.status!=='pending'} onClick={()=>void decide('assessment_request',x.id,'approved')} style={{...btn,color:C.green}}>Approve</button><button disabled={busy===x.id||x.status!=='pending'} onClick={()=>void decide('assessment_request',x.id,'rejected')} style={{...btn,color:C.red}}>Reject</button></Row>)}</Section></div></main>}
function Section({title,children}:{title:string;children:React.ReactNode}){return <section style={{background:C.panel,border:`1px solid ${C.line}`,borderRadius:14,padding:14,marginTop:12}}><h2 style={{fontSize:13,margin:'0 0 7px'}}>{title}</h2>{children||<div style={{color:C.muted}}>Nothing in queue.</div>}</section>};function Row({title,meta,border,children}:{title:string;meta:string;border:boolean;children:React.ReactNode}){return <div style={{display:'flex',gap:10,alignItems:'center',padding:'11px 0',borderTop:border?`1px solid ${C.line}`:0}}><div style={{flex:1,minWidth:0}}><div style={{fontSize:12,fontWeight:800}}>{title}</div><div style={{fontSize:10.5,color:C.muted,marginTop:4}}>{meta}</div></div><div style={{display:'flex',gap:6}}>{children}</div></div>};const btn:React.CSSProperties={border:`1px solid ${C.line}`,background:'rgba(255,255,255,.04)',color:C.text,borderRadius:9,padding:'8px 10px',fontSize:11,fontWeight:800,cursor:'pointer'}
