"use client"
export const dynamic = "force-dynamic"
import { useMemo, useState } from "react"
import { useRouter } from "next/navigation"
import { hqSupabase } from "@/lib/hq/supabase"
const fieldStyle: React.CSSProperties={width:"100%",boxSizing:"border-box",marginTop:7,padding:"13px 14px",borderRadius:12,border:"1px solid rgba(255,255,255,.12)",outline:"none",background:"rgba(255,255,255,.05)",color:"white",fontSize:15}
export default function HQLoginPage(){
 const router=useRouter(); const [email,setEmail]=useState(""); const [password,setPassword]=useState(""); const [showPassword,setShowPassword]=useState(false); const [error,setError]=useState(""); const [message,setMessage]=useState(""); const [loading,setLoading]=useState(false); const [recovering,setRecovering]=useState(false); const normalizedEmail=useMemo(()=>email.trim().toLowerCase(),[email])
 async function handleLogin(){setError("");setMessage("");if(!normalizedEmail||!password)return setError("Email and password are required.");setLoading(true);try{const{data,error:authError}=await hqSupabase.auth.signInWithPassword({email:normalizedEmail,password});if(authError||!data.user)throw new Error("Invalid email or password.");const{data:access,error:accessError}=await hqSupabase.rpc("hq_check_owner_access",{p_surface:"/hq/login"});const allowed=!accessError&&Boolean((access as {allowed?:boolean}|null)?.allowed);if(!allowed){await hqSupabase.auth.signOut({scope:"local"});throw new Error("This account is not authorized for VibeSchool HQ.")}router.replace("/hq");router.refresh()}catch(e){setError(e instanceof Error?e.message:"HQ access could not be verified.");setLoading(false)}}
 async function handleRecovery(){setError("");setMessage("");if(!normalizedEmail)return setError("Enter your HQ email first.");setRecovering(true);try{const response=await fetch("/api/hq/auth/recovery",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({email:normalizedEmail,redirectTo:`${window.location.origin}/hq/reset-password`})});const body=await response.json() as {message?:string};setMessage(body.message||"If this address is authorized for HQ recovery, a secure reset email has been sent.")}catch{setMessage("If this address is authorized for HQ recovery, a secure reset email has been sent.")}finally{setRecovering(false)}}
 const busy=loading||recovering
 return <main style={{minHeight:"100dvh",display:"grid",placeItems:"center",background:"#07111f",color:"#f8fafc",padding:"24px 16px",fontFamily:"Inter,system-ui,sans-serif"}}><section style={{width:"100%",maxWidth:440,border:"1px solid rgba(255,255,255,.1)",borderRadius:24,padding:34,background:"rgba(7,17,31,.86)"}}><div style={{fontSize:11,fontWeight:900,color:"#34d399",textTransform:"uppercase"}}>Owner authority</div><h1 style={{fontSize:32,margin:"8px 0"}}>Enter VibeSchool HQ</h1><p style={{fontSize:13,lineHeight:1.6,color:"rgba(255,255,255,.52)"}}>HQ uses an isolated session. Other Vibeschool product sessions are not replaced.</p>{error&&<div role="alert" style={{color:"#fecaca",margin:"16px 0"}}>{error}</div>}{message&&<div role="status" style={{color:"#bbf7d0",margin:"16px 0"}}>{message}</div>}<label>Email<input value={email} onChange={e=>setEmail(e.target.value)} type="email" autoComplete="email" disabled={busy} style={{...fieldStyle,marginBottom:17}}/></label><div style={{display:"flex",justifyContent:"space-between"}}><label>Password</label><button type="button" onClick={()=>setShowPassword(v=>!v)} style={{background:"none",border:0,color:"#93c5fd"}}>{showPassword?"Hide":"Show"}</button></div><input value={password} onChange={e=>setPassword(e.target.value)} onKeyDown={e=>{if(e.key==="Enter"&&!busy)void handleLogin()}} type={showPassword?"text":"password"} autoComplete="current-password" disabled={busy} style={{...fieldStyle,marginBottom:8}}/><div style={{textAlign:"right",marginBottom:20}}><button type="button" disabled={busy} onClick={()=>void handleRecovery()} style={{border:0,background:"transparent",color:"#93c5fd",cursor:"pointer"}}>{recovering?"Sending secure link…":"Forgot password?"}</button></div><button disabled={busy} onClick={()=>void handleLogin()} style={{width:"100%",padding:14,border:0,borderRadius:12,background:"#10b981",fontWeight:900}}>{loading?"Verifying owner authority…":"Enter HQ"}</button><p style={{fontSize:11,color:"rgba(255,255,255,.36)",marginTop:18}}>Recovery responses are deliberately generic. Only the configured HQ owner can receive an HQ recovery message; owner authority is checked again before HQ access.</p></section></main>}
