import type { ContentEngineClient } from './client'
import {
  assertRequiredId,
  toContentEngineError,
} from './errors'
import type {
  ChapterLearningOutcomeLink,
  ContentBlockOutcomeLink,
  CurriculumLearningOutcome,
  CurriculumOutcomeFilters,
  OutcomeAlignmentStrength,
  ReplaceBlockOutcomeLinksInput,
  ReplaceChapterOutcomeLinksInput,
} from './types'

const DEFAULT_LIMIT = 50
const MAX_LIMIT = 200
const DEFAULT_ALIGNMENT_STRENGTH: OutcomeAlignmentStrength = 'supports'
const UUID_PATTERN =
  /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i

function normalizeLimit(limit: number | undefined): number {
  if (limit === undefined || !Number.isFinite(limit)) {
    return DEFAULT_LIMIT
  }

  return Math.min(Math.max(Math.trunc(limit), 1), MAX_LIMIT)
}

function dedupeOutcomeIds(
  outcomeIds: readonly string[],
  operation: string,
): string[] {
  const normalized = Array.from(
    new Set(outcomeIds.map(id => id.trim()).filter(Boolean)),
  )

  for (const id of normalized) {
    if (!UUID_PATTERN.test(id)) {
      throw toContentEngineError(
        operation,
        new Error(`"${id}" is not a valid outcome id.`),
      )
    }
  }

  return normalized
}

async function requireAuthenticatedUserId(
  client: ContentEngineClient,
  operation: string,
): Promise<string> {
  const {
    data: { user },
    error,
  } = await client.auth.getUser()

  if (error) {
    throw toContentEngineError(operation, error)
  }

  if (!user) {
    throw toContentEngineError(
      operation,
      new Error('An authenticated author is required.'),
    )
  }

  return user.id
}

/**
 * Discovery is intentionally restricted to verified outcomes — RLS also
 * enforces this (curriculum_learning_outcomes_public_read), so this filter
 * is defence in depth, not the sole guard.
 */
export async function listVerifiedCurriculumOutcomes(
  client: ContentEngineClient,
  filters: CurriculumOutcomeFilters = {},
): Promise<CurriculumLearningOutcome[]> {
  const operation = 'listVerifiedCurriculumOutcomes'

  let query = client
    .from('curriculum_learning_outcomes')
    .select('*')
    .eq('status', 'verified')
    .order('outcome_text', { ascending: true })
    .limit(normalizeLimit(filters.limit))

  if (filters.curriculumId?.trim()) {
    query = query.eq('curriculum_id', filters.curriculumId.trim())
  }

  if (filters.subStrandId?.trim()) {
    query = query.eq('sub_strand_id', filters.subStrandId.trim())
  }

  if (filters.search?.trim()) {
    query = query.ilike('outcome_text', `%${filters.search.trim()}%`)
  }

  const { data, error } = await query

  if (error) {
    throw toContentEngineError(operation, error)
  }

  return data
}

export async function listChapterOutcomeLinks(
  client: ContentEngineClient,
  chapterId: string,
): Promise<ChapterLearningOutcomeLink[]> {
  const operation = 'listChapterOutcomeLinks'
  const id = assertRequiredId(chapterId, 'chapterId', operation)

  const { data, error } = await client
    .from('chapter_learning_outcome_links')
    .select('*')
    .eq('chapter_id', id)
    .order('sequence', { ascending: true })

  if (error) {
    throw toContentEngineError(operation, error)
  }

  return data
}

/**
 * Replaces the full set of author-selected outcome links for a chapter.
 * Existing selected links are upserted first (preserving their id/created_at),
 * then any link no longer present in outcomeIds is removed. This does not
 * touch the auto-synced 'creator_claimed' links generated by the
 * ce_sync_chapter_learning_outcomes trigger from the legacy
 * vibe_chapters.learning_outcomes text array — those are a separate
 * authority and are reconciled independently on chapter save.
 */
export async function replaceChapterOutcomeLinks(
  client: ContentEngineClient,
  input: ReplaceChapterOutcomeLinksInput,
): Promise<ChapterLearningOutcomeLink[]> {
  const operation = 'replaceChapterOutcomeLinks'
  const publicationId = assertRequiredId(
    input.publicationId,
    'publicationId',
    operation,
  )
  const chapterId = assertRequiredId(
    input.chapterId,
    'chapterId',
    operation,
  )
  const outcomeIds = dedupeOutcomeIds(input.outcomeIds, operation)
  const alignmentStrength =
    input.alignmentStrength ?? DEFAULT_ALIGNMENT_STRENGTH

  const authorId = await requireAuthenticatedUserId(client, operation)

  if (outcomeIds.length === 0) {
    const { error: deleteAllError } = await client
      .from('chapter_learning_outcome_links')
      .delete()
      .eq('chapter_id', chapterId)

    if (deleteAllError) {
      throw toContentEngineError(operation, deleteAllError)
    }

    return []
  }

  const rows = outcomeIds.map((outcomeId, index) => ({
    publication_id: publicationId,
    chapter_id: chapterId,
    outcome_id: outcomeId,
    alignment_strength: alignmentStrength,
    sequence: index + 1,
    created_by: authorId,
  }))

  const { data, error } = await client
    .from('chapter_learning_outcome_links')
    .upsert(rows, { onConflict: 'chapter_id,outcome_id' })
    .select('*')

  if (error) {
    throw toContentEngineError(operation, error)
  }

  const keepList = outcomeIds.map(id => `"${id}"`).join(',')

  const { error: staleError } = await client
    .from('chapter_learning_outcome_links')
    .delete()
    .eq('chapter_id', chapterId)
    .not('outcome_id', 'in', `(${keepList})`)

  if (staleError) {
    throw toContentEngineError(operation, staleError)
  }

  return data
}

export async function listContentBlockOutcomeLinks(
  client: ContentEngineClient,
  contentBlockId: string,
): Promise<ContentBlockOutcomeLink[]> {
  const operation = 'listContentBlockOutcomeLinks'
  const id = assertRequiredId(
    contentBlockId,
    'contentBlockId',
    operation,
  )

  const { data, error } = await client
    .from('content_block_outcome_links')
    .select('*')
    .eq('content_block_id', id)

  if (error) {
    throw toContentEngineError(operation, error)
  }

  return data
}

/**
 * Replaces the full set of outcome links for a single content block.
 * The DB trigger ce_validate_block_outcome_link requires each outcome to
 * already be linked to the block's chapter (via
 * chapter_learning_outcome_links) — call replaceChapterOutcomeLinks first,
 * or this will surface that as a ContentEngineError from Postgres.
 */
export async function replaceBlockOutcomeLinks(
  client: ContentEngineClient,
  input: ReplaceBlockOutcomeLinksInput,
): Promise<ContentBlockOutcomeLink[]> {
  const operation = 'replaceBlockOutcomeLinks'
  const publicationId = assertRequiredId(
    input.publicationId,
    'publicationId',
    operation,
  )
  const chapterId = assertRequiredId(
    input.chapterId,
    'chapterId',
    operation,
  )
  const contentBlockId = assertRequiredId(
    input.contentBlockId,
    'contentBlockId',
    operation,
  )
  const outcomeIds = dedupeOutcomeIds(input.outcomeIds, operation)
  const relationship = input.relationship ?? 'supports'

  const authorId = await requireAuthenticatedUserId(client, operation)

  if (outcomeIds.length === 0) {
    const { error: deleteAllError } = await client
      .from('content_block_outcome_links')
      .delete()
      .eq('content_block_id', contentBlockId)

    if (deleteAllError) {
      throw toContentEngineError(operation, deleteAllError)
    }

    return []
  }

  const rows = outcomeIds.map(outcomeId => ({
    publication_id: publicationId,
    chapter_id: chapterId,
    content_block_id: contentBlockId,
    outcome_id: outcomeId,
    relationship,
    created_by: authorId,
  }))

  const { data, error } = await client
    .from('content_block_outcome_links')
    .upsert(rows, { onConflict: 'content_block_id,outcome_id' })
    .select('*')

  if (error) {
    throw toContentEngineError(operation, error)
  }

  const keepList = outcomeIds.map(id => `"${id}"`).join(',')

  const { error: staleError } = await client
    .from('content_block_outcome_links')
    .delete()
    .eq('content_block_id', contentBlockId)
    .not('outcome_id', 'in', `(${keepList})`)

  if (staleError) {
    throw toContentEngineError(operation, staleError)
  }

  return data
}

/**
 * The author editor works with legacy client-generated block ids until a
 * block is persisted and reconciled into public.content_blocks (see
 * CE-003). Block-level outcome linking is only possible after that
 * reconciliation, so callers must resolve the authoritative id first.
 * Returns null if the block has not been reconciled yet — callers should
 * treat that as "save the chapter first", not as an error.
 */
export async function resolveContentBlockId(
  client: ContentEngineClient,
  chapterId: string,
  legacyBlockId: string,
): Promise<string | null> {
  const operation = 'resolveContentBlockId'
  const cId = assertRequiredId(chapterId, 'chapterId', operation)
  const legacyId = assertRequiredId(
    legacyBlockId,
    'legacyBlockId',
    operation,
  )

  const { data, error } = await client
    .from('content_blocks')
    .select('id')
    .eq('chapter_id', cId)
    .eq('legacy_block_id', legacyId)
    .maybeSingle()

  if (error) {
    throw toContentEngineError(operation, error)
  }

  return data?.id ?? null
}
