'use client'

import Link from 'next/link'
import { useEffect, useState } from 'react'
import { supabase } from '@/lib/supabase'

type Passport={student_id:string;pathway_slug:string;pathway_name:string;summary:string;rule_version:string;adopted_at:string;reviewed_at:string|null;updated_at:string}

export default function StudentPathwaysPage(){
 const[passport,setPassport]=useState<Passport|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState('')
 useEffect(()=>{let live=true;void(async()=>{const{data,error}=await supabase.rpc('pathways_get_my_passport');if(!live)return;if(error){setError('Your Pathway Passport could not be loaded safely.');setLoading(false);return}setPassport(data&&typeof data==='object'&&!Array.isArray(data)?data as unknown as Passport:null);setLoading(false)})();return()=>{live=false}},[])
 return <main className="page"><div className="wrap"><Link href="/student/profile" className="back">← Learner profile</Link><p className="eyebrow">MY PATHWAY PASSPORT</p><h1>A direction you own, not a label that owns you.</h1><p className="lead">Your Passport is bound to your canonical learner record and keeps the rule version behind the saved direction.</p>{loading&&<section className="card">Loading your Passport…</section>}{error&&<section className="error" role="alert">{error}</section>}{!loading&&!error&&!passport&&<section className="card"><strong>No pathway saved yet.</strong><p>You can explore freely without adopting a direction.</p><Link className="primary" href="/pathways/check">Check my direction</Link></section>}{passport&&<><section className="passport"><span>CURRENT DIRECTION</span><h2>{passport.pathway_name}</h2><p>{passport.summary}</p><small>Rule {passport.rule_version} · adopted {new Date(passport.adopted_at).toLocaleDateString('en-KE')}</small></section><section className="card"><strong>What this means</strong><p>This is guidance, not an official placement. Parents and assigned teachers may view it to support you, but they cannot silently replace it.</p><div className="actions"><Link className="primary" href={`/pathways/${encodeURIComponent(passport.pathway_slug)}`}>Understand this pathway</Link><Link href={`/pathways/schools?pathway=${encodeURIComponent(passport.pathway_slug)}`}>Find verified schools</Link><Link href="/pathways/check">Review my direction</Link></div></section></>}</div><style jsx>{styles}</style></main>
}

const styles=`.page{min-height:100dvh;background:#f3f4f6;color:#111827}.wrap{max-width:720px;margin:0 auto;padding:24px 16px 60px}.back,.actions a,.primary{color:#4f46e5;font-weight:800;text-decoration:none}.eyebrow{margin:28px 0 8px;font-size:10px;font-weight:900;letter-spacing:.15em;color:#4f46e5}h1{font-size:clamp(32px,6vw,48px);line-height:1.06;letter-spacing:-.04em;margin:0}.lead,.card p{color:#626b7b;line-height:1.65}.card{margin-top:16px;background:white;border:1px solid #e5e7eb;border-radius:18px;padding:20px}.passport{margin-top:22px;background:#1e1b4b;color:white;border-radius:22px;padding:28px}.passport span{font-size:9px;font-weight:900;letter-spacing:.15em;color:#c7d2fe}.passport h2{font-size:36px;margin:7px 0}.passport p{color:#d8d8e7}.passport small{color:#c7c8dc}.actions{display:grid;gap:9px;margin-top:14px}.actions a,.primary{padding:11px 13px;border:1px solid #ddd;border-radius:12px}.primary{background:#4f46e5;color:white!important;border-color:#4f46e5!important;width:max-content}.error{margin-top:16px;background:#fef2f2;color:#991b1b;border:1px solid #fecaca;border-radius:14px;padding:14px}`