from pathlib import Path

path = Path('components/teacher/LessonPlanModal.tsx')
text = path.read_text()

replacements = [
    ("label: 'Introduction (5-7 min)'", "label: 'Introduction'"),
    ("label: 'Development (20-25 min)'", "label: 'Development'"),
    ("label: 'Consolidation (8-10 min)'", "label: 'Consolidation'"),
    ("label: 'Assessment Hook'", "label: 'Assessment Check'"),
    ("<span>✦</span> Generate Lesson Plan", "<span>✦</span> Build Lesson Plan · No AI"),
    ("<span>Generated by Twin · CBC aligned</span>", "<span>{canonicalIdentity ? 'Built from Scheme + VibeSchool Content · No AI' : 'Built from Scheme · No AI'}</span>"),
    ("generated_by: 'twin'", "generated_by: 'deterministic'"),
    (">Regenerate</button>", ">Create another version · No AI</button>"),
    ("Generate {action.label}", "View · Edit · Assign · Share {action.label}"),
]

for old, new in replacements:
    count = text.count(old)
    if count != 1:
        raise SystemExit(f'Expected exactly one occurrence of {old!r}; found {count}')
    text = text.replace(old, new)

legacy_forbidden = [
    'Generated by Twin · CBC aligned',
    'Generate Lesson Plan',
    "generated_by: 'twin'",
    'Introduction (5-7 min)',
    'Development (20-25 min)',
    'Consolidation (8-10 min)',
]
for stale in legacy_forbidden:
    if stale in text:
        raise SystemExit(f'Legacy zero-AI UX string remains: {stale}')

path.write_text(text)
