import fs from 'node:fs'
import crypto from 'node:crypto'

const contractPath='docs/ai-governance/CYBORG_ENGINE.json'
const dagPath='docs/ai-governance/CYBORG_DEPENDENCY_DAG.json'
const statePath=process.env.CYBORG_STATE_PATH||'.cyborg/engine-state.json'
const contract=JSON.parse(fs.readFileSync(contractPath,'utf8'))
const dag=fs.existsSync(dagPath)?JSON.parse(fs.readFileSync(dagPath,'utf8')):null
const command=process.argv[2]||'status'
const arg=process.argv[3]

function hash(v){return crypto.createHash('sha256').update(JSON.stringify(v)).digest('hex')}
function load(){if(!fs.existsSync(statePath))return null;return JSON.parse(fs.readFileSync(statePath,'utf8'))}
function save(s){fs.mkdirSync(pathDir(statePath),{recursive:true});fs.writeFileSync(statePath,JSON.stringify(s,null,2)+'\n');return s}
function pathDir(p){const i=p.lastIndexOf('/');return i<0?'.':p.slice(0,i)||'.'}
function assertExactHead(s){const current=process.env.CYBORG_HEAD_SHA||process.env.GITHUB_SHA;if(current&&s.headSha&&current!==s.headSha)throw new Error(`STALE_EVIDENCE: mission head ${s.headSha} != current head ${current}`)}
function dependentsOf(node){if(!dag?.nodes?.[node])return new Set([node]);const affected=new Set([node]);let changed=true;while(changed){changed=false;for(const [id,cfg] of Object.entries(dag.nodes)){if(!affected.has(id)&&(cfg.dependsOn||[]).some(dep=>affected.has(dep))){affected.add(id);changed=true}}}return affected}
function evidenceNode(kind){const map={'exact-head-ci':'exact-head-ci','independent-assurance':'independent-assurance','certification':'certification','merge':'merge','post-merge':'post-merge','learning':'learning','security':'security','test-integrity':'test-integrity','preflight':'preflight','implementation':'implementation','contracts':'contracts','truth':'truth'};return map[kind]||kind}
function invalidate(s,kind,reason){const affected=dependentsOf(evidenceNode(kind));const now=new Date().toISOString();for(const e of s.evidence){if(e.result==='PASS'&&affected.has(evidenceNode(e.kind))&&!e.invalidatedAt){e.invalidatedAt=now;e.invalidatedBy=kind;e.invalidationReason=reason||`Contrary ${kind} evidence`}}
if(s.certification?.valid&&affected.has('certification'))s.certification={...s.certification,valid:false,invalidatedBy:kind,invalidatedAt:now};s.invalidations=s.invalidations||[];s.invalidations.push({kind,affected:[...affected],at:now,reason:reason||`Contrary ${kind} evidence`});return affected}
function validPass(s,kind){return s.evidence.some(e=>e.headSha===s.headSha&&e.kind===kind&&e.result==='PASS'&&!e.invalidatedAt)}
function init(){const mission=arg||process.env.CYBORG_MISSION;if(!mission)throw new Error('Mission is required');const baseSha=process.env.CYBORG_BASE_SHA;const headSha=process.env.CYBORG_HEAD_SHA||process.env.GITHUB_SHA;if(!baseSha||!headSha)throw new Error('Exact base/head SHA required');return save({schemaVersion:2,engine:contract.id,contractVersion:contract.version,mission,baseSha,headSha,state:contract.initialState,lastValidCheckpoint:contract.initialState,selectedSkills:[],evidence:[],invalidations:[],history:[{from:null,to:contract.initialState,reason:'mission initialized'}],certification:null,activation:{runtime:false,schedulers:false,publishing:false,payments:false,consequentialAuthority:false}})}
function transition(next,reason=''){const s=load();if(!s)throw new Error('Initialize mission first');assertExactHead(s);const allowed=contract.transitions[s.state]||[];if(!allowed.includes(next))throw new Error(`Illegal Cyborg transition ${s.state} -> ${next}`);if(['CERTIFY','MERGE_GATE','MERGE','COMPLETE'].includes(next)){const failed=s.selectedSkills.filter(x=>['FAIL','BLOCKED','PENDING'].includes(x.result));if(failed.length)throw new Error(`Blocked by skills: ${failed.map(x=>x.id).join(', ')}`)}if(next==='CERTIFY'&&!validPass(s,'exact-head-ci'))throw new Error('CERTIFY requires fresh, non-invalidated PASS exact-head-ci evidence');if(next==='MERGE'&&!s.certification?.valid)throw new Error('MERGE requires valid certification');s.history.push({from:s.state,to:next,reason});s.state=next;if(!['REPAIR','BLOCKED'].includes(next))s.lastValidCheckpoint=next;if(next==='CERTIFY')s.certification={valid:true,headSha:s.headSha,evidenceDigest:hash(s.evidence.filter(e=>!e.invalidatedAt)),certifiedAt:new Date().toISOString()};return save(s)}
function addEvidence(){const s=load();if(!s)throw new Error('Initialize mission first');assertExactHead(s);const evidence=JSON.parse(arg||'{}');if(!evidence.kind||!evidence.result)throw new Error('Evidence needs kind and result');if(!['PASS','FAIL','BLOCKED','PENDING'].includes(evidence.result))throw new Error('Unsupported evidence result');evidence.headSha=s.headSha;evidence.recordedAt=new Date().toISOString();s.evidence.push(evidence);if(['FAIL','BLOCKED'].includes(evidence.result))invalidate(s,evidence.kind,evidence.source||`Evidence ${evidence.result}`);return save(s)}
function setSkills(){const s=load();if(!s)throw new Error('Initialize mission first');assertExactHead(s);const items=JSON.parse(arg||'[]');const prior=new Map(s.selectedSkills.map(x=>[x.id,x]));s.selectedSkills=items;for(const item of items){if(['FAIL','BLOCKED'].includes(item.result)&&prior.get(item.id)?.result==='PASS')invalidate(s,'exact-head-ci',`Skill ${item.id} regressed to ${item.result}`)}return save(s)}
let out
if(command==='init')out=init();else if(command==='transition')out=transition(arg,process.argv.slice(4).join(' '));else if(command==='evidence')out=addEvidence();else if(command==='skills')out=setSkills();else if(command==='status')out=load();else throw new Error(`Unknown command: ${command}`)
console.log(JSON.stringify(out,null,2))
