import assert from 'node:assert/strict'
import fs from 'node:fs'

const migration = fs.readFileSync('supabase/migrations/20260902095200_teacher_class_self_service_current.sql', 'utf8')
const optionalClassMigration = fs.readFileSync('supabase/migrations/20260927170000_teacher_optional_class_onboarding.sql', 'utf8')
const form = fs.readFileSync('components/teacher/TeacherClassForm.tsx', 'utf8')
const classHub = fs.readFileSync('app/teacher/classhub/page.tsx', 'utf8')
const addPage = fs.readFileSync('app/teacher/classhub/add/page.tsx', 'utf8')
const onboarding = fs.readFileSync('app/teacher/onboarding/class/page.tsx', 'utf8')
const scheme = fs.readFileSync('app/teacher/scheme/AuthoritySchemePage.jsx', 'utf8')
const reconciliation = fs.readFileSync('supabase/migrations/20260927214500_teacher_context_authority_reconciliation.sql', 'utf8')

assert.match(migration, /create or replace function public\.create_teacher_class_assignment/i)
assert.match(migration, /security definer/i)
assert.match(migration, /set search_path = public, auth, pg_temp/i)
assert.match(migration, /teacher_school_membership_required/i)
assert.match(migration, /sm\.profile_id = v_uid[\s\S]*sm\.school_id = p_school_id[\s\S]*sm\.role::text = 'teacher'/i)
assert.match(migration, /s\.school_id is null[\s\S]*lower\(btrim\(s\.name\)\) = lower\(v_subject_input\)/i)
assert.match(migration, /pg_advisory_xact_lock/i)
assert.match(migration, /on conflict\s*\(\s*teacher_id\s*,\s*class_id\s*,\s*subject_id\s*\)\s*do update/i)
assert.match(migration, /revoke all on function public\.create_teacher_class_assignment[\s\S]*service_role/i)
assert.match(migration, /grant execute on function public\.create_teacher_class_assignment[\s\S]*to authenticated/i)

assert.match(optionalClassMigration, /create or replace function public\.get_my_auth_journey_state\(\)/i)
assert.match(optionalClassMigration, /if p\.role='teacher'[\s\S]*v_has_school/i)
assert.match(optionalClassMigration, /'state','ready','destination','\/teacher\/pulse','reason_code','OK'/i)
assert.doesNotMatch(optionalClassMigration, /TEACHER_CLASS_REQUIRED/)
assert.doesNotMatch(optionalClassMigration, /'state','needs_class'/)

assert.match(form, /\.from\('subjects'\)\.select\('name'\)\.is\('school_id', null\)/)
assert.doesNotMatch(form, /TEACHER_SUBJECTS/)
assert.match(form, /create_teacher_class_assignment/)
assert.match(form, /class_teacher/)
assert.match(addPage, /\.rpc\('get_my_teacher_school_context'\)/)
assert.doesNotMatch(addPage, /\.from\('school_members'\)/)
assert.doesNotMatch(onboarding, /teacher_profiles/)
assert.doesNotMatch(onboarding, /\.from\('school_members'\)/)
assert.doesNotMatch(onboarding, /\.from\('schools'\)/)
assert.match(onboarding, /\.rpc\('get_my_teacher_school_context'\)/)
assert.match(onboarding, /withTimeout/)
assert.match(onboarding, /requestId\.current/)
assert.match(onboarding, /Skip — go to Teacher OS/)
assert.match(onboarding, /router\.replace\('\/teacher\/pulse'\)/)
assert.match(classHub, /\/teacher\/classhub\/add/)
assert.match(classHub, /Student progress/)
assert.match(classHub, /teacher_get_operating_context/)
assert.doesNotMatch(classHub, /classes'\)\.select\('id,name,stream,subject'/)
assert.match(scheme, /teacher_get_operating_context/)
assert.doesNotMatch(scheme, /teacher_profiles'\)\.select\('school_id'/)
assert.doesNotMatch(scheme, /profiles'\)\.select\('school_id'/)
assert.match(reconciliation, /create or replace function public\.onboard_teacher_class/i)
assert.match(reconciliation, /return public\.create_teacher_class_assignment/i)
assert.match(reconciliation, /v_uid is null or v_uid <> p_teacher_id/i)

console.log('Teacher class self-service current-main contract: PASS')
