import { NextRequest, NextResponse } from "next/server"
import { createClient } from "@supabase/supabase-js"

function admin(){return createClient(process.env.NEXT_PUBLIC_SUPABASE_URL!,process.env.SUPABASE_SERVICE_ROLE_KEY!,{auth:{autoRefreshToken:false,persistSession:false,detectSessionInUrl:false}})}
async function actor(req:NextRequest){const token=(req.headers.get("authorization")||"").replace(/^Bearer\s+/,"");if(!token)return null;const s=admin();const{data}=await s.auth.getUser(token);if(!data.user)return null;const{data:member}=await s.from("hq_human_members").select("role,status,permissions,access_expires_at").eq("profile_id",data.user.id).maybeSingle();if(!member||member.status!=="active"||(member.access_expires_at&&new Date(member.access_expires_at).getTime()<=Date.now()))return null;return{s,user:data.user,member}}
function isFounder(a:NonNullable<Awaited<ReturnType<typeof actor>>>){return a.member.role==="founder"}
async function log(s:ReturnType<typeof admin>,actorId:string,targetId:string|null,action:string,after:unknown){await s.from("hq_human_audit_log").insert({actor_id:actorId,target_id:targetId,action,after_state:after})}

export async function GET(req:NextRequest){const a=await actor(req);if(!a)return NextResponse.json({error:"Active HQ membership required"},{status:403});let assignments=a.s.from("hq_human_assignments").select("*").order("created_at",{ascending:false}).limit(100);if(!["founder","partner_admin","hq_admin"].includes(a.member.role))assignments=assignments.eq("assignee_id",a.user.id);const[{data:assignmentRows,error:assignmentError},{data:approvals,error:approvalError},{data:preferences}]=await Promise.all([assignments,a.s.from("hq_human_approvals").select("*").order("created_at",{ascending:false}).limit(100),a.s.from("hq_human_notification_preferences").select("preferences").eq("profile_id",a.user.id).maybeSingle()]);if(assignmentError||approvalError)return NextResponse.json({error:assignmentError?.message||approvalError?.message},{status:500});return NextResponse.json({assignments:assignmentRows||[],approvals:approvals||[],preferences:preferences?.preferences||{security:true,assignments:true,approvals:true,content:true,finance:true,workforce:true},actorId:a.user.id})}

export async function POST(req:NextRequest){const a=await actor(req);if(!a)return NextResponse.json({error:"Active HQ membership required"},{status:403});const b=await req.json();const action=String(b.action||"");if(action==="create_assignment"){if(!isFounder(a))return NextResponse.json({error:"Founder authority required"},{status:403});const row={assignee_id:String(b.assigneeId||""),assigned_by:a.user.id,kind:String(b.kind||"hq_task"),subject_id:String(b.subjectId||crypto.randomUUID()),title:String(b.title||"").trim(),due_at:b.dueAt||null};if(!row.assignee_id||!row.title)return NextResponse.json({error:"Assignee and title are required"},{status:400});const{data,error}=await a.s.from("hq_human_assignments").insert(row).select("*").single();if(error)return NextResponse.json({error:error.message},{status:500});await log(a.s,a.user.id,row.assignee_id,"assignment.created",data);return NextResponse.json({ok:true,assignment:data})}
if(action==="request_approval"){if(!isFounder(a))return NextResponse.json({error:"Founder authority required"},{status:403});const required=Math.max(1,Math.min(2,Number(b.requiredApprovals||2)));const row={action_key:String(b.actionKey||"critical_action"),subject_id:String(b.subjectId||crypto.randomUUID()),requested_by:a.user.id,required_approvals:required,expires_at:b.expiresAt||null};const{data,error}=await a.s.from("hq_human_approvals").insert(row).select("*").single();if(error)return NextResponse.json({error:error.message},{status:500});await log(a.s,a.user.id,null,"approval.requested",data);return NextResponse.json({ok:true,approval:data})}
return NextResponse.json({error:"Unsupported action"},{status:400})}

export async function PATCH(req:NextRequest){const a=await actor(req);if(!a)return NextResponse.json({error:"Active HQ membership required"},{status:403});const b=await req.json();const action=String(b.action||"");if(action==="assignment_status"){const id=String(b.id||"");const status=String(b.status||"");if(!["open","in_progress","done","cancelled"].includes(status))return NextResponse.json({error:"Invalid assignment status"},{status:400});const{data:row}=await a.s.from("hq_human_assignments").select("assignee_id").eq("id",id).maybeSingle();if(!row||(!isFounder(a)&&row.assignee_id!==a.user.id))return NextResponse.json({error:"Assignment authority denied"},{status:403});const{error}=await a.s.from("hq_human_assignments").update({status,updated_at:new Date().toISOString()}).eq("id",id);if(error)return NextResponse.json({error:error.message},{status:500});await log(a.s,a.user.id,row.assignee_id,"assignment.status_changed",{id,status});return NextResponse.json({ok:true})}
if(action==="approval_decision"){const id=String(b.id||"");const decision=String(b.decision||"");if(!["approve","reject"].includes(decision))return NextResponse.json({error:"Invalid decision"},{status:400});const{data:row,error:readError}=await a.s.from("hq_human_approvals").select("*").eq("id",id).maybeSingle();if(readError||!row)return NextResponse.json({error:readError?.message||"Approval not found"},{status:404});if(row.status!=="pending")return NextResponse.json({error:"Approval is already closed"},{status:409});if(row.expires_at&&new Date(row.expires_at).getTime()<=Date.now())return NextResponse.json({error:"Approval request expired"},{status:409});if(row.requested_by===a.user.id)return NextResponse.json({error:"Requester cannot approve their own consequential action"},{status:403});const current=Array.isArray(row.approvals)?row.approvals:[];if(current.some((x:any)=>x?.actor_id===a.user.id))return NextResponse.json({error:"You already decided this approval"},{status:409});const next=[...current,{actor_id:a.user.id,decision,at:new Date().toISOString()}];const approvedCount=next.filter((x:any)=>x.decision==="approve").length;const status=decision==="reject"?"rejected":approvedCount>=row.required_approvals?"approved":"pending";const{error}=await a.s.from("hq_human_approvals").update({approvals:next,status}).eq("id",id).eq("status","pending");if(error)return NextResponse.json({error:error.message},{status:500});await log(a.s,a.user.id,null,"approval.decided",{id,decision,status});return NextResponse.json({ok:true,status})}
if(action==="preferences"){const preferences=b.preferences&&typeof b.preferences==="object"?b.preferences:{};const{error}=await a.s.from("hq_human_notification_preferences").upsert({profile_id:a.user.id,preferences,updated_at:new Date().toISOString()},{onConflict:"profile_id"});if(error)return NextResponse.json({error:error.message},{status:500});return NextResponse.json({ok:true})}
return NextResponse.json({error:"Unsupported action"},{status:400})}
