"use client"

import { useCallback, useEffect, useState } from "react"
import { useRouter } from "next/navigation"
import { supabase } from "@/lib/supabase"
const rpc=supabase.rpc.bind(supabase) as any
const C={bg:"#07111f",panel:"#0d1b2f",line:"rgba(255,255,255,.09)",text:"#f8fafc",muted:"rgba(255,255,255,.48)",green:"#34d399",amber:"#f59e0b",red:"#fb7185",blue:"#60a5fa"}
type Q={id:string;question_text:string;question_type:string;difficulty:string|null;bloom_level:string|null;marks:number;status:string;review_status:string;usage_count:number;curriculum_id:string;updated_at:string}
type Cur={id:string;grade:string;subject:string;term:number;week:number;strand:string;sub_strand:string;topic:string}
export default function ExamStudio(){const router=useRouter();const[qs,setQs]=useState<Q[]>([]);const[cur,setCur]=useState<Cur[]>([]);const[error,setError]=useState("");const[busy,setBusy]=useState("");const[text,setText]=useState("");const[curriculumId,setCurriculumId]=useState("")
 const load=useCallback(async()=>{const[a,c]=await Promise.all([rpc("hq_list_assessment_bank",{p_limit:300}),rpc("hq_list_curriculum_rows",{p_limit:500})]);const e=a.error||c.error;if(e)setError(e.message);else{setQs(a.data??[]);setCur(c.data??[]);if(!curriculumId&&c.data?.[0]?.id)setCurriculumId(c.data[0].id)}},[curriculumId]);useEffect(()=>{void load()},[load])
 async function create(){if(!text.trim()||!curriculumId)return;setBusy("create");const{error:e}=await rpc("hq_create_assessment_question",{p_curriculum_id:curriculumId,p_question_text:text.trim(),p_question_type:"written",p_difficulty:"medium",p_marks:1});if(e)setError(e.message);else{setText("");await load()}setBusy("")}
 async function review(id:string,status:string){setBusy(id);const{error:e}=await rpc("hq_review_assessment_question",{p_question_id:id,p_review_status:status});if(e)setError(e.message);else await load();setBusy("")}
 return <main style={{minHeight:"100dvh",background:C.bg,color:C.text,padding:18,fontFamily:"Inter,system-ui,sans-serif"}}><div style={{maxWidth:1100,margin:"0 auto"}}><button onClick={()=>router.push("/hq/studio")} style={btn}>← Studio</button><h1>Exam & Question Bank</h1><p style={{color:C.muted,fontSize:12}}>Real curriculum-linked assessment questions. New HQ questions begin as drafts and require explicit review.</p>{error&&<div style={{color:"#fecdd3",padding:10,border:`1px solid ${C.red}55`,borderRadius:10}}>{error}</div>}
 <section style={panel}><h2 style={{fontSize:14}}>Add draft question</h2><select value={curriculumId} onChange={e=>setCurriculumId(e.target.value)} style={input}>{cur.map(c=><option key={c.id} value={c.id}>{c.grade} · {c.subject} · T{c.term} W{c.week} · {c.sub_strand||c.topic}</option>)}</select><textarea value={text} onChange={e=>setText(e.target.value)} rows={3} placeholder="Question text" style={{...input,marginTop:8,resize:"vertical"}}/><button disabled={busy==="create"} onClick={()=>void create()} style={{...btn,marginTop:8,color:C.green}}>{busy==="create"?"Creating…":"Create draft"}</button></section>
 <section style={{...panel,marginTop:12}}><div style={{fontSize:12,color:C.muted,marginBottom:8}}>{qs.length} recent bank questions</div>{qs.length===0?<div style={{color:C.muted}}>No bank questions yet.</div>:qs.map((q,i)=><div key={q.id} style={{padding:"11px 0",borderTop:i?`1px solid ${C.line}`:0}}><div style={{display:"flex",gap:9,alignItems:"start"}}><div style={{flex:1}}><div style={{fontSize:12.5,fontWeight:800}}>{q.question_text}</div><div style={{fontSize:10.5,color:C.muted,marginTop:4}}>{q.question_type} · {q.difficulty||"—"} · {q.marks} mark(s) · used {q.usage_count??0} · review {q.review_status}</div></div><button disabled={busy===q.id} onClick={()=>void review(q.id,"approved")} style={{...btn,color:C.green}}>Approve</button><button disabled={busy===q.id} onClick={()=>void review(q.id,"rejected")} style={{...btn,color:C.red}}>Reject</button></div></div>)}</section></div></main>}
const panel:React.CSSProperties={background:C.panel,border:`1px solid ${C.line}`,borderRadius:14,padding:14};const btn:React.CSSProperties={border:`1px solid ${C.line}`,background:"rgba(255,255,255,.04)",color:C.text,borderRadius:9,padding:"8px 10px",fontSize:11,fontWeight:800,cursor:"pointer"};const input:React.CSSProperties={width:"100%",boxSizing:"border-box",background:"#0a1628",border:`1px solid ${C.line}`,borderRadius:9,padding:10,color:C.text}
