"use client"

export const dynamic="force-dynamic"

import Link from "next/link"
import { useCallback,useEffect,useState } from "react"
import { useParams } from "next/navigation"
import { hqSupabase } from "@/lib/hq/supabase"
import { HQPage,HQPanel,HQ_THEME as C } from "@/components/hq/HQShell"

type School360={identity:{id:string;name:string;status:string;knec_code:string|null;nemis_code:string|null;moe_registration_no:string|null;tsc_code:string|null;school_type:string|null;school_category:string|null;ownership_type:string|null;accommodation_type:string|null;gender_type:string|null;directory_source:string|null;directory_source_ref:string|null;last_verified_at:string|null};location:{country_code:string;county:string|null;sub_county:string|null;ward:string|null;latitude:number|null;longitude:number|null;precision:string|null;postal_address:string|null};population:{reported_students:number|null;reported_staff:number|null;linked_learners:number;linked_teachers:number;linked_admins:number;linked_parents:number;linked_profiles:number;penetration_claimable:boolean};activity:{window_days:number;events:number;active_users:number;last_activity:string|null};revenue:{currency:string;school_attributed_orders:{paid_orders:number;paid_kes:number;last_paid_at:string|null};linked_user_orders:{paid_orders:number;paid_kes:number;last_paid_at:string|null};combined_unique_attribution:{paid_orders:number;paid_kes:number;last_paid_at:string|null};institution_paid_claimable:boolean;note:string};entitlements:{total:number;active:number};operations:{open_support_cases:number};provenance:Record<string,string>;generated_at:string}
type Learning={window_days:number;teaching:{occurrences:number;completed:number;active_teachers:number};attendance:{marks:number;learners_seen:number;teachers_marking:number};homework:{created:number;teachers:number;submissions:number;submitting_learners:number};assessments:{attempts:number;submitted:number;learners:number};adoption:{teacher_os:boolean;attendance:boolean;homework:boolean;assessments:boolean};semantics:{usage_only:boolean;learning_outcome_claimed:boolean;retention_claimed:boolean};generated_at:string}

function Value({label,value,note}:{label:string;value:string|number;note?:string}){return <div className="s360-value"><span>{label}</span><strong>{value}</strong>{note&&<small>{note}</small>}</div>}
function Row({label,value}:{label:string;value:string|number|null|undefined}){return <div className="s360-row"><span>{label}</span><strong>{value===null||value===undefined||value===""?"Unknown":String(value)}</strong></div>}
const money=(n:number)=>`KES ${Number(n||0).toLocaleString()}`

export default function HQSchool360Page(){
 const params=useParams<{schoolId:string}>();const schoolId=params.schoolId;const [days,setDays]=useState(30);const [data,setData]=useState<School360|null>(null);const [learning,setLearning]=useState<Learning|null>(null);const [loading,setLoading]=useState(true);const [error,setError]=useState<string|null>(null)
 const load=useCallback(async()=>{setLoading(true);setError(null);const [{data:d,error:e},{data:l,error:le}]=await Promise.all([hqSupabase.rpc("hq_school_network_school_360",{p_school_id:schoolId,p_days:days}),hqSupabase.rpc("hq_school_network_school_learning",{p_school_id:schoolId,p_days:days})]);if(e){setData(null);setError("School 360 is not commissioned for this environment or this school is unavailable.")}else setData(d as School360);setLearning(le?null:l as Learning);setLoading(false)},[schoolId,days]);useEffect(()=>{void load()},[load]);const title=data?.identity.name||"School 360"
 return <HQPage title={title} description="Canonical institution profile: identity, location, people, adoption, learning activity, revenue attribution and operations."><div className="s360-stack">
  <div className="s360-top"><Link href="/hq/schools">← Schools</Link><div className="s360-period">{[7,30,90].map(d=><button key={d} className={days===d?"active":""} onClick={()=>setDays(d)}>{d}D</button>)}</div></div>
  {data&&<nav className="s360-nav" aria-label="School profile sections"><a href="#overview">Overview</a><a href="#people">People</a><a href="#adoption">Adoption</a><a href="#learning">Learning</a><a href="#revenue">Revenue</a><a href="#operations">Operations</a><a href="#identity">Identity</a></nav>}
  {error&&<div className="s360-notice" role="status"><div><strong>School profile unavailable</strong><span>{error}</span></div><button onClick={()=>void load()}>Retry</button></div>}{loading?<div className="s360-loading">Loading School 360…</div>:data?<>
   <section id="overview" className="s360-hero"><div><span className="s360-kicker">SCHOOL 360</span><h2>{data.identity.name}</h2><p>{[data.location.ward,data.location.sub_county,data.location.county,"Kenya"].filter(Boolean).join(" · ")}</p></div><div className="s360-badges"><span>{data.identity.status}</span><span>{data.identity.last_verified_at?"Verified evidence":"Verification date unavailable"}</span></div></section>
   <section className="s360-metrics"><Value label="Linked learners" value={data.population.linked_learners} note="Canonical current relationships"/><Value label="Linked teachers" value={data.population.linked_teachers}/><Value label="Parents" value={data.population.linked_parents}/><Value label="Active users" value={data.activity.active_users} note={`${days} day activity`}/><Value label="Attributed revenue" value={money(data.revenue.combined_unique_attribution.paid_kes)}/><Value label="Open support" value={data.operations.open_support_cases}/></section>
   <section id="people" className="s360-grid"><HQPanel title="People & population" description="Linked VibeSchool people are not treated as the institution's full population."><div className="s360-people"><Value label="Reported learners" value={data.population.reported_students??"Unknown"}/><Value label="VibeSchool learners" value={data.population.linked_learners}/><Value label="Reported staff" value={data.population.reported_staff??"Unknown"}/><Value label="VibeSchool teachers" value={data.population.linked_teachers}/><Value label="Administrators" value={data.population.linked_admins}/><Value label="Parents" value={data.population.linked_parents}/></div><div className="s360-evidence">Penetration is withheld until an authoritative school population denominator exists.</div></HQPanel><HQPanel title="Activity" description={`School-scoped product evidence during the last ${days} days.`}><div className="s360-activity"><Value label="Events" value={data.activity.events}/><Value label="Active users" value={data.activity.active_users}/><Value label="Last activity" value={data.activity.last_activity?new Date(data.activity.last_activity).toLocaleString():"Unknown"}/></div></HQPanel></section>
   <section id="adoption"><HQPanel title="Product adoption" description="Observed use only. No adoption state is inferred from registration alone.">{learning?<div className="s360-adoption">{Object.entries(learning.adoption).map(([k,v])=><div key={k}><span>{k.replaceAll("_"," ")}</span><strong>{v?"Used":"No evidence"}</strong></div>)}</div>:<div className="s360-evidence">Adoption evidence unavailable.</div>}</HQPanel></section>
   <section id="learning"><HQPanel title="Learning & teaching activity" description={`Aggregate usage evidence for ${days} days; this does not claim learning outcomes or retention.`}>{learning?<div className="s360-learning"><Value label="Teaching occurrences" value={learning.teaching.occurrences} note={`${learning.teaching.completed} completed`}/><Value label="Active teachers" value={learning.teaching.active_teachers}/><Value label="Attendance marks" value={learning.attendance.marks} note={`${learning.attendance.learners_seen} learners seen`}/><Value label="Homework created" value={learning.homework.created} note={`${learning.homework.submissions} submissions`}/><Value label="Assessment attempts" value={learning.assessments.attempts} note={`${learning.assessments.submitted} submitted`}/><Value label="Assessment learners" value={learning.assessments.learners}/></div>:<div className="s360-evidence">Learning activity evidence unavailable.</div>}</HQPanel></section>
   <section id="revenue"><HQPanel title="Commercial relationship" description="Settlement/order evidence. Institutional payment is not claimed without payer evidence."><div className="s360-revenue"><Value label="School-attributed" value={money(data.revenue.school_attributed_orders.paid_kes)} note={`${data.revenue.school_attributed_orders.paid_orders} paid orders`}/><Value label="Linked-user revenue" value={money(data.revenue.linked_user_orders.paid_kes)} note={`${data.revenue.linked_user_orders.paid_orders} paid orders`}/><Value label="Combined unique" value={money(data.revenue.combined_unique_attribution.paid_kes)} note={`${data.revenue.combined_unique_attribution.paid_orders} unique paid orders`}/><Value label="Active entitlements" value={data.entitlements.active} note={`${data.entitlements.total} total`}/></div><div className="s360-evidence">{data.revenue.note}</div></HQPanel></section>
   <section id="operations" className="s360-grid"><HQPanel title="Operations"><div className="s360-people"><Value label="Open support cases" value={data.operations.open_support_cases}/><Value label="Last meaningful activity" value={data.activity.last_activity?new Date(data.activity.last_activity).toLocaleString():"Unknown"}/></div></HQPanel><HQPanel title="Location" description="Map rendering is withheld when governed coordinates are unavailable."><div className="s360-rows"><Row label="Country" value={data.location.country_code}/><Row label="County" value={data.location.county}/><Row label="Sub-county" value={data.location.sub_county}/><Row label="Ward" value={data.location.ward}/><Row label="Precision" value={data.location.precision}/><Row label="Latitude" value={data.location.latitude}/><Row label="Longitude" value={data.location.longitude}/></div>{data.location.latitude!==null&&data.location.longitude!==null?<div className="s360-map-ready">Governed coordinates available. A locator can render this school safely.</div>:<div className="s360-evidence">No governed coordinates available. A locator is not fabricated.</div>}</HQPanel></section>
   <section id="identity" className="s360-grid"><HQPanel title="Identity & provenance"><div className="s360-rows"><Row label="KNEC" value={data.identity.knec_code}/><Row label="NEMIS" value={data.identity.nemis_code}/><Row label="MoE registration" value={data.identity.moe_registration_no}/><Row label="TSC code" value={data.identity.tsc_code}/><Row label="School type" value={data.identity.school_type}/><Row label="Category" value={data.identity.school_category}/><Row label="Ownership" value={data.identity.ownership_type}/><Row label="Accommodation" value={data.identity.accommodation_type}/><Row label="Gender" value={data.identity.gender_type}/><Row label="Source" value={data.identity.directory_source}/><Row label="Last verified" value={data.identity.last_verified_at?new Date(data.identity.last_verified_at).toLocaleString():null}/></div></HQPanel><HQPanel title="Evidence lineage"><div className="s360-provenance">{Object.entries(data.provenance).map(([k,v])=><div key={k}><span>{k.replaceAll("_"," ")}</span><strong>{v}</strong></div>)}</div></HQPanel></section>
  </>:null}</div><style jsx global>{`
   html{scroll-behavior:smooth}.s360-stack{display:grid;gap:14px}.s360-top{display:flex;justify-content:space-between;align-items:center}.s360-top>a,.s360-nav a{color:#93c5fd;text-decoration:none;font-size:11px;font-weight:850}.s360-period{display:flex;gap:4px}.s360-period button,.s360-notice button{min-height:40px;min-width:46px;border:1px solid ${C.border};border-radius:9px;background:rgba(255,255,255,.04);color:${C.muted};font-weight:850}.s360-period button.active{background:rgba(59,130,246,.2);color:#fff}.s360-nav{position:sticky;top:8px;z-index:10;display:flex;gap:5px;overflow:auto;padding:6px;border:1px solid ${C.border};border-radius:11px;background:rgba(6,16,29,.92);backdrop-filter:blur(14px)}.s360-nav a{padding:8px 10px;white-space:nowrap;border-radius:8px}.s360-nav a:hover{background:rgba(59,130,246,.12)}.s360-notice{display:flex;justify-content:space-between;gap:12px;align-items:center;padding:13px;border:1px solid rgba(245,158,11,.25);background:rgba(245,158,11,.07);border-radius:12px}.s360-notice strong,.s360-notice span{display:block}.s360-notice span{font-size:10px;color:${C.muted}}.s360-loading{padding:18px;color:${C.muted}}
   .s360-hero{display:flex;justify-content:space-between;gap:16px;align-items:flex-end;padding:18px;border:1px solid ${C.border};border-radius:15px;background:linear-gradient(135deg,rgba(37,99,235,.14),rgba(34,197,94,.05)),${C.panel}}.s360-kicker{font-size:9px;color:#93c5fd;font-weight:900}.s360-hero h2{margin:5px 0 4px;font-size:22px}.s360-hero p{margin:0;color:${C.muted};font-size:11px}.s360-badges{display:flex;gap:6px;flex-wrap:wrap}.s360-badges span{padding:6px 8px;border:1px solid ${C.border};border-radius:999px;font-size:9px;color:#cbd5e1}.s360-metrics,.s360-revenue,.s360-learning,.s360-people{display:grid;grid-template-columns:repeat(6,minmax(0,1fr));gap:8px}.s360-revenue,.s360-learning,.s360-people{padding:14px}.s360-revenue{grid-template-columns:repeat(4,minmax(0,1fr))}.s360-learning{grid-template-columns:repeat(3,minmax(0,1fr))}.s360-people{grid-template-columns:repeat(3,minmax(0,1fr))}.s360-value{min-width:0;padding:12px;border:1px solid ${C.border};border-radius:11px;background:rgba(255,255,255,.018)}.s360-value span,.s360-value small{display:block}.s360-value span{font-size:9px;color:${C.muted};font-weight:850}.s360-value strong{display:block;font-size:18px;margin:6px 0 3px;overflow-wrap:anywhere}.s360-value small{font-size:8.5px;color:#71869f}.s360-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:14px}.s360-activity{padding:14px;display:grid;grid-template-columns:1fr;gap:8px}.s360-adoption{display:grid;grid-template-columns:repeat(4,1fr);gap:8px;padding:14px}.s360-adoption>div{padding:12px;border:1px solid ${C.border};border-radius:10px}.s360-adoption span,.s360-adoption strong{display:block}.s360-adoption span{font-size:9px;color:${C.muted};text-transform:capitalize}.s360-adoption strong{font-size:12px;margin-top:6px}.s360-evidence,.s360-map-ready{margin:0 14px 14px;padding:10px;border-radius:9px;background:rgba(148,163,184,.055);color:${C.muted};font-size:9.5px;line-height:1.45}.s360-map-ready{background:rgba(34,197,94,.07);color:#bbf7d0}.s360-rows{padding:8px 14px 14px}.s360-row{display:grid;grid-template-columns:minmax(120px,.7fr) minmax(0,1.3fr);gap:12px;padding:9px 0;border-bottom:1px solid ${C.border}}.s360-row span{font-size:9px;color:${C.muted}}.s360-row strong{font-size:10px;text-align:right;overflow-wrap:anywhere}.s360-provenance{padding:12px 14px;display:grid;gap:8px}.s360-provenance>div{padding:9px;border:1px solid ${C.border};border-radius:9px}.s360-provenance span,.s360-provenance strong{display:block}.s360-provenance span{font-size:8px;color:${C.muted};text-transform:uppercase}.s360-provenance strong{font-size:9px;margin-top:4px}
   @media(max-width:1180px){.s360-metrics{grid-template-columns:repeat(3,1fr)}.s360-revenue{grid-template-columns:repeat(2,1fr)}}@media(max-width:900px){.hq-sidebar{display:none!important}.hq-page{margin-left:0!important;padding-top:60px!important}.hq-mobile-topbar{display:flex!important;position:fixed!important;top:0!important;left:0!important;right:0!important;z-index:120!important;height:60px!important;padding:0 13px!important;align-items:center!important;justify-content:space-between!important;background:rgba(6,16,29,.96)!important}.hq-bottom-nav{display:grid!important}.s360-grid{grid-template-columns:1fr}.s360-learning,.s360-people{grid-template-columns:repeat(2,1fr)}.s360-adoption{grid-template-columns:repeat(2,1fr)}.s360-nav{top:66px}}@media(max-width:520px){.s360-metrics{grid-template-columns:repeat(2,1fr)}.s360-hero{display:block}.s360-badges{margin-top:12px}.s360-revenue,.s360-learning,.s360-people{grid-template-columns:1fr 1fr}.s360-value strong{font-size:16px}.s360-row{grid-template-columns:1fr}.s360-row strong{text-align:left}}
  `}</style></HQPage>
}
