import type { CSSProperties } from 'react'
import Link from 'next/link'
import { PublicHeader } from '@/components/public/PublicHeader'
import { PublicFooter } from '@/components/public/PublicFooter'

const tracks=[
 {pathway:'STEM',track:'Pure Sciences',code:'ST1',examples:['Core Mathematics · Biology · Chemistry','Core Mathematics · Biology · Physics','Core Mathematics · Chemistry · Physics']},
 {pathway:'STEM',track:'Applied Sciences',code:'ST2',examples:['Agriculture · Geography · Physics','Business Studies · Computer Studies · Physics','Agriculture · Biology · Geography']},
 {pathway:'STEM',track:'Technical Studies',code:'ST3',examples:['Core Mathematics · Electricity · Geography','Computer Studies · Geography · Power Mechanics','Geography · Physics · Wood Work']},
 {pathway:'Social Sciences',track:'Languages & Literature',code:'SS1',examples:['Fasihi ya Kiswahili · German · Indigenous Language','Business Studies · Fasihi ya Kiswahili · Literature in English','Christian Religious Education · Fasihi ya Kiswahili · Indigenous Language']},
 {pathway:'Social Sciences',track:'Humanities & Business Studies',code:'SS2',examples:['Christian Religious Education · Geography · History & Citizenship','Business Studies · Geography · Literature in English','Computer Studies · Geography · History & Citizenship']},
 {pathway:'Arts & Sports Science',track:'Arts',code:'AS1',examples:['Biology · Fine Arts · Music & Dance','Fine Arts · Literature in English · Theatre & Film','Computer Studies · Music & Dance · Theatre & Film']},
 {pathway:'Arts & Sports Science',track:'Sports',code:'AS2',examples:['Biology · Computer Studies · Sports & Recreation','Core Mathematics · General Science · Sports & Recreation','General Science · History & Citizenship · Sports & Recreation']},
] as const

export default function SubjectsPage(){return <div style={S.root}>
<PublicHeader product="Pathways" />
<main id="main-content"><div style={S.shell}>
<nav aria-label="Pathways section" style={S.top}><Link href="/pathways" style={S.back}>← Pathways overview</Link><Link href="/pathways/schools" style={S.link}>Find schools</Link></nav>
<p style={S.kicker}>SENIOR SCHOOL SUBJECTS</p><h1 style={S.h1}>See how subjects form a pathway.</h1>
<p style={S.lead}>Senior School choices are made as three-subject combinations inside a track. Explore the seven tracks below, then compare combinations and schools that actually offer them.</p>
<div style={S.rule}><strong>How to read this</strong><span>Pathway → Track → 3-subject combination → schools offering that combination.</span></div>
<div style={S.grid}>{tracks.map(t=><article key={t.track} style={S.card}><div style={S.cardTop}><span style={S.pathway}>{t.pathway}</span><span style={S.code}>{t.code}</span></div><h2 style={S.h2}>{t.track}</h2><p style={S.small}>Examples from the Ministry Grade 10 Selection System</p><div style={S.examples}>{t.examples.map(x=><div key={x} style={S.combo}><span style={S.dot}>3</span><span>{x}</span></div>)}</div><Link href="/pathways/schools" style={S.action}>Find schools offering combinations →</Link></article>)}</div>
<section style={S.note}><strong>Evidence boundary</strong><p>These examples explain the national structure. VibeSchool only labels a specific combination or school offering as verified when source evidence has been ingested and resolved. A school can offer only a subset of national combinations.</p></section>
<section style={S.next}><div><strong>Not sure which track fits?</strong><span>Use the Quick Check for an early, explainable signal rather than guessing from a subject list.</span></div><Link href="/pathways/check" style={S.nextAction}>Check my direction</Link></section>
</div></main>
<PublicFooter />
</div>}

const S:Record<string,CSSProperties>={root:{minHeight:'100dvh',background:'#f7f7fb',color:'#111827'},shell:{maxWidth:1050,margin:'0 auto',padding:'18px 16px 28px'},top:{minHeight:48,display:'flex',alignItems:'center',justifyContent:'space-between',gap:16},back:{color:'#4f46e5',textDecoration:'none',fontWeight:850,fontSize:13},link:{color:'#4f46e5',textDecoration:'none',fontWeight:800,fontSize:13},kicker:{marginTop:36,color:'#725815',fontSize:10,fontWeight:900,letterSpacing:'.16em'},h1:{fontSize:'clamp(38px,7vw,62px)',lineHeight:1.02,letterSpacing:'-.045em',margin:'8px 0 16px',maxWidth:760},lead:{maxWidth:760,color:'#5b6475',fontSize:16,lineHeight:1.65},rule:{display:'grid',gap:5,background:'#eef2ff',border:'1px solid #dbe3ff',borderRadius:16,padding:16,margin:'26px 0',fontSize:13,color:'#3730a3'},grid:{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(285px,1fr))',gap:14},card:{display:'flex',flexDirection:'column',background:'#fff',border:'1px solid #e1e3ea',borderRadius:20,padding:20,minHeight:330},cardTop:{display:'flex',justifyContent:'space-between',gap:10,alignItems:'center'},pathway:{fontSize:10,fontWeight:900,letterSpacing:'.1em',color:'#725815'},code:{fontSize:10,fontWeight:900,background:'#f3f4f6',borderRadius:999,padding:'6px 8px',color:'#6b7280'},h2:{fontSize:24,letterSpacing:'-.025em',margin:'13px 0 4px'},small:{fontSize:11,color:'#6b7280',lineHeight:1.5},examples:{display:'grid',gap:8,marginTop:14},combo:{display:'flex',alignItems:'flex-start',gap:9,background:'#f8fafc',borderRadius:12,padding:11,fontSize:12,lineHeight:1.45,color:'#374151'},dot:{display:'grid',placeItems:'center',minWidth:22,height:22,borderRadius:7,background:'#eef2ff',color:'#4338ca',fontWeight:900,fontSize:10},action:{marginTop:'auto',paddingTop:18,color:'#4f46e5',fontSize:12,fontWeight:850,textDecoration:'none'},note:{marginTop:24,background:'#fffbeb',border:'1px solid #fde68a',borderRadius:16,padding:18,fontSize:12,lineHeight:1.6,color:'#66551a'},next:{margin:'30px 0 24px',display:'flex',alignItems:'center',justifyContent:'space-between',gap:18,flexWrap:'wrap',background:'#111827',color:'#fff',borderRadius:18,padding:20},nextAction:{display:'inline-flex',padding:'11px 14px',borderRadius:11,background:'#fff',color:'#111827',fontWeight:850,fontSize:13,textDecoration:'none'}}