'use client';

import {useCallback,useEffect,useRef,useState} from 'react';
import Link from 'next/link';
import {useParams,useRouter} from 'next/navigation';
import {supabase} from '@/lib/supabase';
import {loadWorkbook} from '@/lib/class-workbook/data';
import type {Data} from '@/lib/class-workbook/model';

type Duty={id:string;duty_code:string;title:string;starts_on:string;ends_on:string;members:Array<{student_id:string;student_name:string;active:boolean}>};
type Loan={id:string;student_id:string;student_name:string;book_id:string;book_title:string;issued_at:string;due_date:string;returned_at:string|null;condition_out:string;condition_in:string|null};
type Book={id:string;title:string;author:string|null;available_copies:number};
type Operations={duties:Duty[];borrowings:Loan[];books:Book[]};
const empty:Operations={duties:[],borrowings:[],books:[]};
const today=()=>new Date().toLocaleDateString('en-CA',{timeZone:'Africa/Nairobi'});
const input:React.CSSProperties={width:'100%',minHeight:44,border:'1px solid #cbd5e1',borderRadius:10,padding:'8px 10px',fontSize:14,boxSizing:'border-box'};
const card:React.CSSProperties={background:'#fff',border:'1px solid #e5e7eb',borderRadius:16,padding:14};
const button:React.CSSProperties={minHeight:42,border:0,borderRadius:10,padding:'0 14px',background:'#173f32',color:'#fff',fontWeight:800,cursor:'pointer'};

export default function ClassOperationsPage(){
 const {id:classId}=useParams<{id:string}>();const router=useRouter();
 const issueRequest=useRef<{payload:string;id:string}|null>(null)
 const [classData,setClassData]=useState<Data|null>(null);const [operations,setOperations]=useState(empty);const [loading,setLoading]=useState(true);const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [message,setMessage]=useState('');
 const [dutyCode,setDutyCode]=useState('classroom');const [dutyTitle,setDutyTitle]=useState('Classroom care');const [startsOn,setStartsOn]=useState(today());const [endsOn,setEndsOn]=useState(today());const [members,setMembers]=useState<string[]>([]);
 const [studentId,setStudentId]=useState('');const [bookId,setBookId]=useState('');const [dueDate,setDueDate]=useState('');
 const load=useCallback(async()=>{const workbook=await loadWorkbook(classId);const result=await supabase.rpc('teacher_get_class_operations' as never,{p_class_id:classId} as never);if(result.error)throw result.error;const value=result.data as Operations;setClassData(workbook.data);setOperations({...empty,...value});},[classId]);
 useEffect(()=>{let current=true;setLoading(true);void load().catch(e=>{if(current)setError(e instanceof Error?e.message:'Class operations could not be loaded.');}).finally(()=>{if(current)setLoading(false);});return()=>{current=false;};},[load]);
 async function act(fn:()=>Promise<void>){if(busy)return;setBusy(true);setError('');setMessage('');try{await fn();}catch(e){setError(e instanceof Error?e.message:'The change could not be saved. Check the class and retry.');}finally{setBusy(false);}}
 function toggleMember(id:string){setMembers(current=>current.includes(id)?current.filter(x=>x!==id):current.length<8?[...current,id]:current);}
 if(loading)return <main style={{padding:16}}><p role="status">Opening class operations…</p></main>;
 if(!classData)return <main style={{padding:16}}><p role="alert">{error||'This class is unavailable.'}</p><Link href="/teacher/classhub">My classes</Link> <button onClick={()=>void act(load)}>Retry</button></main>;
 const classTeacher=classData.isClassTeacher;
 const activeLoans=operations.borrowings.filter(loan=>!loan.returned_at);
 return <main style={{maxWidth:920,margin:'0 auto',padding:'16px 14px 40px',display:'grid',gap:12,color:'#0f172a'}}>
  <header style={{...card,background:'linear-gradient(130deg,#173f32,#155e75)',color:'#fff'}}><Link href={`/teacher/classhub/${classId}`} style={{color:'#d1fae5'}}>← Back to class</Link><h1 style={{fontSize:23,margin:'10px 0 4px'}}>{classData.className} · Run the class</h1><p style={{fontSize:13,margin:0,color:'#d1fae5'}}>Class duties and learner borrowing stay with this class. Book circulation uses the school library record.</p><div style={{display:'flex',flexWrap:'wrap',gap:8,marginTop:13}}><Link style={{...button,textDecoration:'none',display:'grid',placeItems:'center',background:'#fff',color:'#173f32'}} href={`/teacher/attendance?classId=${classId}`}>Attendance</Link><Link style={{...button,textDecoration:'none',display:'grid',placeItems:'center',background:'#fff',color:'#173f32'}} href={`/teacher/classhub/${classId}/homework`}>Homework</Link><Link style={{...button,textDecoration:'none',display:'grid',placeItems:'center',background:'#fff',color:'#173f32'}} href={`/teacher/assessment?classId=${classId}`}>Assessment</Link></div></header>
  {error&&<div role="alert" style={{...card,borderColor:'#fecaca',background:'#fef2f2',color:'#991b1b'}}>{error}<button style={{marginLeft:10}} onClick={()=>void act(load)}>Retry</button></div>}{message&&<div role="status" style={{...card,background:'#ecfdf5',color:'#065f46'}}>{message}</div>}
  <section style={card}><h2 style={{fontSize:17,marginTop:0}}>Duty roster</h2><p style={{fontSize:13,color:'#475569'}}>Assign one duty to one learner or a small shared team for a date range. Reassigning keeps the previous assignment in the history.</p>
   {classTeacher&&<div style={{display:'grid',gap:9,background:'#f8fafc',padding:12,borderRadius:12}}><label style={{fontSize:12,fontWeight:800}}>Duty<select style={input} value={dutyCode} onChange={e=>{setDutyCode(e.target.value);setDutyTitle(e.target.options[e.target.selectedIndex].text);}}><option value="classroom">Classroom care</option><option value="board">Board monitor</option><option value="materials">Learning materials</option><option value="line_leader">Line leader</option><option value="attendance_helper">Attendance helper</option><option value="other">Other responsibility</option></select></label>{dutyCode==='other'&&<label style={{fontSize:12,fontWeight:800}}>Responsibility name<input style={input} maxLength={80} value={dutyTitle} onChange={e=>setDutyTitle(e.target.value)}/></label>}<div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(145px,1fr))',gap:9}}><label style={{fontSize:12,fontWeight:800}}>From<input style={input} type="date" value={startsOn} onChange={e=>setStartsOn(e.target.value)}/></label><label style={{fontSize:12,fontWeight:800}}>Through<input style={input} type="date" min={startsOn} value={endsOn} onChange={e=>setEndsOn(e.target.value)}/></label></div><fieldset style={{border:'1px solid #cbd5e1',borderRadius:10}}><legend style={{fontSize:12,fontWeight:800}}>Learners sharing this duty · choose up to 8</legend><div style={{maxHeight:180,overflowY:'auto',display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(180px,1fr))',gap:4}}>{classData.learners.map(learner=><label key={learner.id} style={{fontSize:13,padding:4}}><input type="checkbox" checked={members.includes(learner.id)} onChange={()=>toggleMember(learner.id)}/> {learner.name}</label>)}</div></fieldset><button disabled={busy||!members.length||!dutyTitle.trim()||endsOn<startsOn} style={button} onClick={()=>void act(async()=>{const result=await supabase.rpc('teacher_save_class_duty_roster' as never,{p_class_id:classId,p_duty_code:dutyCode,p_title:dutyTitle,p_starts_on:startsOn,p_ends_on:endsOn,p_student_ids:members} as never);if(result.error)throw result.error;await load();setMessage('Duty roster saved for this class.');setMembers([]);})}>Save duty roster</button></div>}
   {!classTeacher&&<p style={{padding:10,background:'#f8fafc',borderRadius:10,fontSize:13}}>Only the class teacher can change the class duty roster. You can view the current assignments.</p>}
   <div style={{display:'grid',gap:8,marginTop:12}}>{operations.duties.length?operations.duties.map(duty=><article key={duty.id} style={{border:'1px solid #e2e8f0',borderRadius:12,padding:11}}><strong>{duty.title}</strong><div style={{fontSize:12,color:'#64748b',margin:'4px 0 8px'}}>{duty.starts_on} to {duty.ends_on}</div><div style={{display:'flex',gap:6,flexWrap:'wrap'}}>{duty.members.map(person=><span key={person.student_id} style={{fontSize:12,padding:'4px 8px',borderRadius:999,background:person.active?'#ecfdf5':'#f1f5f9'}}>{person.student_name}{!person.active?' · previous':''}</span>)}</div></article>):<p style={{fontSize:13,color:'#64748b'}}>No class duties have been scheduled yet.</p>}</div>
  </section>
  <section style={card}><h2 style={{fontSize:17,marginTop:0}}>Books borrowed by learners</h2><p style={{fontSize:13,color:'#475569'}}>Issue and return a school library book here. The transaction remains in the school library and appears in this class and learner’s history.</p>
   <div style={{display:'grid',gap:9,background:'#f8fafc',padding:12,borderRadius:12}}><label style={{fontSize:12,fontWeight:800}}>Learner<select style={input} value={studentId} onChange={e=>setStudentId(e.target.value)}><option value="">Choose learner</option>{classData.learners.map(learner=><option key={learner.id} value={learner.id}>{learner.name}</option>)}</select></label><label style={{fontSize:12,fontWeight:800}}>School library book<select style={input} value={bookId} onChange={e=>setBookId(e.target.value)}><option value="">Choose book</option>{operations.books.filter(book=>book.available_copies>0).map(book=><option key={book.id} value={book.id}>{book.title} · {book.available_copies} available</option>)}</select></label><label style={{fontSize:12,fontWeight:800}}>Return by<input style={input} type="date" min={today()} value={dueDate} onChange={e=>setDueDate(e.target.value)}/></label><button disabled={busy||!studentId||!bookId||!dueDate} style={button} onClick={()=>void act(async()=>{const args={p_class_id:classId,p_student_id:studentId,p_book_id:bookId,p_due_date:dueDate,p_condition:'good'};const payload=JSON.stringify(args);if(issueRequest.current?.payload!==payload)issueRequest.current={payload,id:crypto.randomUUID()};const requestId=issueRequest.current!.id;const result=await supabase.rpc('teacher_issue_class_library_book' as never,{...args,p_request_id:requestId} as never);if(result.error)throw result.error;issueRequest.current=null;await load();setMessage('Book issued and linked to the learner and this class.');setBookId('');setDueDate('');})}>Record borrowed book</button></div>
   <h3 style={{fontSize:14,marginTop:18}}>Outstanding returns · {activeLoans.length}</h3>{activeLoans.length?activeLoans.map(loan=><div key={loan.id} style={{display:'flex',justifyContent:'space-between',alignItems:'center',gap:10,borderTop:'1px solid #e2e8f0',padding:'10px 0'}}><div><Link href={`/teacher/classhub/${classId}/student/${loan.student_id}`}><strong>{loan.student_name}</strong></Link><div style={{fontSize:12,color:'#475569'}}>{loan.book_title} · return by {loan.due_date}</div></div><button disabled={busy} style={{...button,minHeight:36}} onClick={()=>void act(async()=>{const result=await supabase.rpc('teacher_return_class_library_book' as never,{p_borrowing_id:loan.id,p_condition_in:'good'} as never);if(result.error)throw result.error;await load();setMessage('Book return recorded and school stock updated.');})}>Record return</button></div>):<p style={{fontSize:13,color:'#64748b'}}>No books are waiting to be returned.</p>}
   <details style={{marginTop:12}}><summary style={{cursor:'pointer',fontWeight:800,fontSize:13}}>Borrowing history</summary>{operations.borrowings.length?operations.borrowings.map(loan=><p key={loan.id} style={{fontSize:12,borderBottom:'1px solid #e2e8f0',paddingBottom:7}}><strong>{loan.student_name}</strong> · {loan.book_title} · issued {loan.issued_at.slice(0,10)} · {loan.returned_at?`returned ${loan.returned_at.slice(0,10)}`:`due ${loan.due_date}`}</p>):<p style={{fontSize:12,color:'#64748b'}}>No borrowing history for this class.</p>}</details>
  </section>
  <button onClick={()=>router.push(`/teacher/classhub/${classId}`)} style={{...button,background:'#334155'}}>Return to class overview</button>
 </main>;
}
