import { serve } from "https://deno.land/std@0.168.0/http/server.ts"
import { anthropicText, invokeCyborgEdgeModel } from "../_shared/cyborg-model-client.ts"

const SUPABASE_URL = Deno.env.get("SUPABASE_URL") ?? ""
const SUPABASE_ANON_KEY = Deno.env.get("SUPABASE_ANON_KEY") ?? ""
const MODEL = "claude-haiku-4-5-20251001"
const CORS = { "Access-Control-Allow-Origin": "*", "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type" }
type Row = Record<string, unknown>
const row = (v: unknown): Row => v && typeof v === "object" && !Array.isArray(v) ? v as Row : {}
const text = (v: unknown): string => typeof v === "string" ? v : ""
const arr = (v: unknown): unknown[] => Array.isArray(v) ? v : []
async function sessionKey(req:Request):Promise<string>{const auth=req.headers.get("authorization")??"";const digest=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(auth));return Array.from(new Uint8Array(digest)).slice(0,12).map(v=>v.toString(16).padStart(2,"0")).join("")}
async function rpc(req: Request, name: string, body: Row): Promise<unknown> {
  const authorization = req.headers.get("authorization") ?? ""
  if (!authorization.toLowerCase().startsWith("bearer ")) throw new Error("not_authenticated")
  const res = await fetch(`${SUPABASE_URL}/rest/v1/rpc/${name}`, { method: "POST", headers: { "Content-Type": "application/json", apikey: SUPABASE_ANON_KEY, Authorization: authorization }, body: JSON.stringify(body) })
  const payload = await res.json().catch(() => null)
  if (!res.ok) throw new Error(text(row(payload).message) || `${name}_failed`)
  return payload
}
function parseJson(raw: string): Row | null { const cleaned=raw.trim().replace(/^```json\s*/i,"").replace(/^```\s*/,"").replace(/```\s*$/,"").trim(); try{return row(JSON.parse(cleaned))}catch{return null} }
function validQuestions(value:unknown,blockIds:Set<string>,limit:number):Row[]{const out:Row[]=[];for(const item of arr(value)){const q=row(item);const prompt=text(q.prompt).trim();if(!prompt)continue;const options=arr(q.options).filter((v):v is string=>typeof v==="string"&&v.trim().length>0).map(v=>v.trim()).slice(0,6);const sourceBlockId=text(q.sourceBlockId);const question:Row={prompt,marks:Math.max(1,Math.min(20,Number(q.marks)||1)),difficulty:["easy","medium","hard"].includes(text(q.difficulty))?text(q.difficulty):"medium",bloomLevel:text(q.bloomLevel)||"understand",answer:text(q.answer),sourceBlockId:blockIds.has(sourceBlockId)?sourceBlockId:""};if(options.length>=2){question.options=options;const index=Number(q.correctIndex);question.correctIndex=Number.isInteger(index)&&index>=0&&index<options.length?index:0}out.push(question);if(out.length>=limit)break}return out}
function fallbackQuestions(ctx:Row,limit:number):Row[]{const blocks=arr(ctx.blocks).map(row);const authored=blocks.filter(b=>b.is_assessable===true&&text(b.text).trim());const source=authored.length?authored:blocks.filter(b=>text(b.text).trim());return source.slice(0,limit).map(b=>({prompt:b.is_assessable===true?text(b.text).trim():`Explain this idea from the source: ${text(b.text).trim().slice(0,220)}`,marks:2,difficulty:"medium",bloomLevel:"understand",answer:b.is_assessable===true?"Review against the authored source and teacher marking guide.":text(b.text).trim().slice(0,500),sourceBlockId:text(b.id)}))}
serve(async(req)=>{if(req.method==="OPTIONS")return new Response("ok",{headers:CORS});try{
 const body=row(await req.json().catch(()=>({})));const chapterId=text(body.chapterId);const assessmentType=text(body.assessmentType)||"quiz";const requestedCount=Math.max(1,Math.min(30,Number(body.questionCount)||(assessmentType==="exam"?15:assessmentType==="test"?10:6)))
 if(!chapterId)return new Response(JSON.stringify({error:"chapter_required"}),{status:400,headers:{...CORS,"Content-Type":"application/json"}});if(!["quiz","test","exam"].includes(assessmentType))return new Response(JSON.stringify({error:"unsupported_assessment_type"}),{status:400,headers:{...CORS,"Content-Type":"application/json"}})
 const ctx=row(await rpc(req,"ce_get_teacher_derivation_context",{p_chapter_id:chapterId}));const blocks=arr(ctx.blocks).map(row);const blockIds=new Set(blocks.map(b=>text(b.id)).filter(Boolean));let questions:Row[]=[];let model:string|null=null;let lineage:unknown=null
 const prompt=`You are Vibeschool's teacher assessment drafting assistant. Generate a ${assessmentType} using ONLY the authorized source below. Never invent facts outside the source. Every question must identify the exact sourceBlockId from the supplied blocks. Prefer authored assessable/question blocks when available. Keep Kenyan secondary-school wording clear and teacher-editable. Return STRICT JSON only: {"questions":[{"prompt":"...","options":["..."],"correctIndex":0,"answer":"...","marks":1,"difficulty":"easy|medium|hard","bloomLevel":"remember|understand|apply|analyze|evaluate|create","sourceBlockId":"uuid"}]}. Use MCQ or short-answer as appropriate. Requested question count: ${requestedCount}.\n\nPublication: ${text(ctx.publication_title)}\nChapter: ${text(ctx.chapter_title)}\nGrade: ${text(ctx.grade)}\nSubject: ${text(ctx.subject)}\nLearning outcomes: ${JSON.stringify(ctx.learning_outcomes??[])}\nBlocks with IDs: ${JSON.stringify(blocks)}\n\nAUTHORIZED SOURCE TEXT:\n${text(ctx.source_text)}`
 try{const actor=await sessionKey(req);const governed=await invokeCyborgEdgeModel({callerServiceId:"edge.content-assessment-generate",actorKey:`auth:${actor}`,externalChatId:`assessment:${actor}:${chapterId}:${assessmentType}`,objective:"Draft one governed source-grounded teacher assessment",provider:"anthropic",model:MODEL,maxTokens:3600,messages:[{role:"user",content:prompt}],metadata:{feature:"content-assessment-generate",temperature:0.15},dataClassification:"confidential"});const parsed=parseJson(anthropicText(governed.output));if(parsed){questions=validQuestions(parsed.questions,blockIds,requestedCount);if(questions.length){model=MODEL;lineage=governed.lineage}}}catch(error){console.warn("[content-assessment-generate] Cyborg model degraded",error instanceof Error?error.message:String(error))}
 if(!questions.length)questions=fallbackQuestions(ctx,requestedCount);if(!questions.length)throw new Error("source_has_no_assessable_content")
 const title=text(body.title).trim()||`${text(ctx.chapter_title)||"Chapter"} ${assessmentType}`;const saved=row(await rpc(req,"ce_create_generated_assessment_from_payload",{p_chapter_id:chapterId,p_assessment_type:assessmentType,p_title:title,p_questions:questions}))
 return new Response(JSON.stringify({...saved,title,assessmentType,questions,model,degraded:model===null,source:{publicationId:text(ctx.publication_id),chapterId},lineage}),{headers:{...CORS,"Content-Type":"application/json"}})
}catch(err){const message=err instanceof Error?err.message:String(err);const status=message==="not_authenticated"?401:/Teacher role|required|not available/.test(message)?403:500;return new Response(JSON.stringify({error:message}),{status,headers:{...CORS,"Content-Type":"application/json"}})}})
