'use client'

import Link from 'next/link'
import { FormEvent, useEffect, useState } from 'react'
import { useParams } from 'next/navigation'
import { PublicHeader } from '@/components/public/PublicHeader'
import { PublicFooter } from '@/components/public/PublicFooter'
import { supabase } from '@/lib/supabase'
import styles from '../schools.module.css'

type ProfileRow={school_id:string;school_name:string;county:string|null;sub_county:string|null;school_category:string|null;ownership_type:string|null;gender_type:string|null;accommodation_type:string|null;cluster:string|null;knec_code:string|null;pathway_slug:string|null;pathway_name:string|null;combination_slug:string|null;combination_name:string|null;verified_at:string|null;source_authority:string|null;source_name:string|null;source_url:string|null;source_reference:string|null;source_observed_at:string|null}
type TrustRow={school_id:string;verified_claim_count:number;profile_completeness:number;trust_state:'canonical_identity'|'verified_claims';last_verified_at:string|null}

export default function SchoolProfilePage(){
 const params=useParams<{schoolId:string}>();const schoolId=params.schoolId
 const [rows,setRows]=useState<ProfileRow[]>([]);const [trust,setTrust]=useState<TrustRow|null>(null);const [loading,setLoading]=useState(true);const [error,setError]=useState('')
 const [showCorrection,setShowCorrection]=useState(false);const [notes,setNotes]=useState('');const [showClaim,setShowClaim]=useState(false);const [claimRole,setClaimRole]=useState('');const [claimEvidence,setClaimEvidence]=useState('');const [claimPhone,setClaimPhone]=useState('');const [saving,setSaving]=useState(false);const [feedback,setFeedback]=useState('')
 useEffect(()=>{let cancelled=false;void(async()=>{const [profileResult,trustResult]=await Promise.all([supabase.rpc('schools_get_public_profile_v1',{p_school_id:schoolId}),supabase.rpc('schools_profile_trust_public_v1',{p_school_id:schoolId})]);if(cancelled)return;if(profileResult.error){setError('This school profile could not be loaded.');setRows([])}else setRows((profileResult.data??[]) as ProfileRow[]);if(!trustResult.error)setTrust(((trustResult.data??[])[0]??null) as TrustRow|null);setLoading(false)})();return()=>{cancelled=true}},[schoolId])
 async function requireUser(){const {data:{user}}=await supabase.auth.getUser();return user}
 async function submitCorrection(e:FormEvent){e.preventDefault();setFeedback('');if(notes.trim().length<10){setFeedback('Please describe the correction in a little more detail.');return}setSaving(true);const user=await requireUser();if(!user){setSaving(false);setFeedback('Sign in first so VibeSchool can retain and review your correction.');return}const {data,error}=await supabase.rpc('submit_school_correction_request',{p_school_id:schoolId,p_notes:notes.trim(),p_contact_name:null,p_contact_phone:null});setSaving(false);setFeedback(error?'We could not save this correction right now. Please try again.':`Correction ${String(data).slice(0,8)} received for review. The public profile will not change until it is verified.`)}
 async function submitClaim(e:FormEvent){e.preventDefault();setFeedback('');if(claimRole.trim().length<2){setFeedback('Tell us your role at the school.');return}setSaving(true);const user=await requireUser();if(!user){setSaving(false);setFeedback('Sign in first so VibeSchool can verify who is requesting management access.');return}const {data,error}=await supabase.rpc('submit_school_profile_claim_v1',{p_school_id:schoolId,p_role_at_school:claimRole.trim(),p_evidence_note:claimEvidence.trim()||null,p_contact_phone:claimPhone.trim()||null});setSaving(false);setFeedback(error?'We could not submit this claim. It may already be awaiting review.':`Claim ${String(data).slice(0,8)} received. Nothing on the public profile changes until VibeSchool verifies your authority.`)}
 const school=rows[0];const offerings=rows.filter(r=>r.pathway_slug)
 const completeness=trust?.profile_completeness??0
 return <div className={styles.page}><PublicHeader product="Schools"/><main id="main-content" className={styles.main}><Link href="/schools" className={styles.back}>← School directory</Link>
 {loading&&<div className={styles.status}>Loading school profile…</div>}{error&&<div role="alert" className={`${styles.status} ${styles.error}`}>{error}</div>}{!loading&&!error&&!school&&<div className={styles.status}>This school is not available in the public directory.</div>}
 {school&&<><section className={styles.profileHero}><span className={styles.eyebrow}>VIBESCHOOL SCHOOL PROFILE</span><h1 className={styles.title}>{school.school_name}</h1><p className={styles.lead}>{[school.sub_county,school.county].filter(Boolean).join(' · ')||'Location not yet verified'}</p><div className={styles.chips}>{[school.school_category,school.ownership_type,school.gender_type,school.accommodation_type].filter(Boolean).map(v=><span className={styles.chip} key={v}>{v}</span>)}<span className={styles.verified}>✓ Canonical identity</span></div></section>
 <section className={styles.trustPanel}><div><span className={styles.eyebrow}>PROFILE TRUST</span><h2>{completeness}% profile complete</h2><div className={styles.progress} aria-label={`${completeness}% profile complete`}><span style={{width:`${completeness}%`}}/></div><p className={styles.meta}>Completeness measures available profile fields. It is not a school ranking or quality score.</p></div><div><strong>{trust?.verified_claim_count??0}</strong><span className={styles.meta}> source-backed profile claims</span>{trust?.last_verified_at&&<p className={styles.small}>Last offering verification {new Date(trust.last_verified_at).toLocaleDateString()}</p>}</div></section>
 <section className={styles.facts}>{[['County',school.county],['Sub-county',school.sub_county],['School code',school.knec_code],['Level',school.school_category],['Ownership',school.ownership_type],['Boarding / day',school.accommodation_type]].map(([label,value])=><div className={styles.fact} key={label}><strong>{label}</strong><span>{value||'Not yet verified'}</span></div>)}</section>
 <section className={styles.section}><span className={styles.eyebrow}>PATHWAYS & OFFERINGS</span><h2>Verified senior-school information</h2>{offerings.length===0?<div className={styles.notice}><strong>Not yet verified here.</strong> A missing pathway means VibeSchool has not verified that claim here; it does not mean the school does not offer it.</div>:offerings.map((o,index)=><article className={styles.offering} key={`${o.pathway_slug}-${o.combination_slug??index}`}><span className={styles.verified}>✓ Verified offering</span><h3>{o.pathway_name}</h3>{o.combination_name&&<p>{o.combination_name}</p>}<p className={styles.source}>{[o.source_authority,o.source_name].filter(Boolean).join(' · ')}</p>{o.source_url&&<a href={o.source_url} target="_blank" rel="noreferrer noopener">View source ↗</a>}</article>)}</section>
 <section className={`${styles.panel} ${styles.section}`}><span className={styles.eyebrow}>SCHOOL MANAGEMENT</span><h2>Do you manage this school?</h2><p className={styles.meta}>Authorized representatives can request management access. Claiming a profile does not make school-supplied information “VibeSchool verified”; evidence remains labelled by source.</p>{!showClaim?<div className={styles.actions}><button className={styles.primary} onClick={()=>{setShowClaim(true);setShowCorrection(false);setFeedback('')}}>Claim this school</button></div>:<form onSubmit={submitClaim}><div className={styles.searchGrid}><label className={styles.field}><span>Your role *</span><input className={styles.input} value={claimRole} onChange={e=>setClaimRole(e.target.value)} placeholder="Headteacher, deputy, administrator…"/></label><label className={styles.field}><span>School contact</span><input className={styles.input} value={claimPhone} onChange={e=>setClaimPhone(e.target.value)} placeholder="Optional phone"/></label><label className={styles.field}><span>Evidence / context</span><input className={styles.input} value={claimEvidence} onChange={e=>setClaimEvidence(e.target.value)} placeholder="How can VibeSchool verify your authority?"/></label></div>{feedback&&<div className={`${styles.status} ${feedback.startsWith('Claim ') ? styles.success:styles.error}`}>{feedback}{feedback.startsWith('Sign in')&&<> <Link href="/login/global">Sign in</Link></>}</div>}<div className={styles.actions}><button className={styles.primary} disabled={saving}>{saving?'Sending…':'Request management access'}</button><button type="button" className={styles.secondary} onClick={()=>setShowClaim(false)}>Cancel</button></div></form>}</section>
 <section className={`${styles.panel} ${styles.section}`}><span className={styles.eyebrow}>COMMUNITY ASSISTED, VERIFIED BEFORE PUBLISHING</span><h2>Something missing or incorrect?</h2><p className={styles.meta}>Send a correction. It enters a review queue and cannot overwrite the canonical school record automatically.</p>{!showCorrection?<div className={styles.actions}><button className={styles.secondary} onClick={()=>{setShowCorrection(true);setShowClaim(false);setFeedback('')}}>Suggest a correction</button></div>:<form onSubmit={submitCorrection}><label className={styles.field}><span>What should VibeSchool check?</span><textarea className={styles.textarea} value={notes} onChange={e=>setNotes(e.target.value)} placeholder="Describe the correction and, if possible, the evidence."/></label>{feedback&&<div className={`${styles.status} ${feedback.startsWith('Correction')?styles.success:styles.error}`}>{feedback}{feedback.startsWith('Sign in')&&<> <Link href="/login/global">Sign in</Link></>}</div>}<div className={styles.actions}><button className={styles.primary} disabled={saving}>{saving?'Sending…':'Send for review'}</button><button type="button" className={styles.secondary} onClick={()=>setShowCorrection(false)}>Cancel</button></div></form>}</section>
 </>}</main><PublicFooter/></div>
}
