"use client"
import Link from "next/link"
import {useCallback,useEffect,useState} from "react"
import {HQPage,HQPanel,HQ_THEME as C,hqButtonStyle} from "@/components/hq/HQShell"
import {listHQDepartments,loadHQWorkroom,type HQDepartment,type HQWorkItem,type HQWorkroomSnapshot,type HQWorkroomView} from "@/lib/hq/operating"
const views:Array<[HQWorkroomView,string,string]>=[["attention","Needs attention","Risk, deadlines, missing ownership or evidence"],["my_work","My work","Items assigned to this HQ identity"],["founder_decisions","Founder decisions","Consequential approval boundary"],["journeys","Journeys at risk","School, admin, teacher, student and parent impact"],["active","All active","Every unfinished company mission"],["closed","Closed","Resolved and cancelled history"]]
const statusTone:Record<string,string>={blocked:C.red,failed:C.red,waiting_approval:C.amber,verifying:C.violet,delivered:C.cyan,resolved:C.green,cancelled:C.muted,in_progress:C.blue,assigned:C.blue,open:C.muted}
export default function HQWorkroomPage(){
 const[data,setData]=useState<HQWorkroomSnapshot|null>(null);const[departments,setDepartments]=useState<HQDepartment[]>([]);const[view,setView]=useState<HQWorkroomView>("attention");const[department,setDepartment]=useState<string|null>(null);const[loading,setLoading]=useState(true);const[error,setError]=useState("")
 const refresh=useCallback(async()=>{setLoading(true);setError("");try{const[s,d]=await Promise.all([loadHQWorkroom(view,department),listHQDepartments()]);setData(s);setDepartments(d)}catch(e){setError(e instanceof Error?e.message:"Workroom could not be loaded.")}finally{setLoading(false)}},[department,view]);useEffect(()=>{void refresh()},[refresh]);const actor=data?.actor,c=data?.counts
 return <HQPage title="HQ Workroom" description="Accountable missions · clear next actions · evidence · delivery · governed decisions" actions={<button onClick={()=>void refresh()} disabled={loading} style={hqButtonStyle}>{loading?"Refreshing…":"Refresh"}</button>}>
  {actor&&<section aria-label="Current Workroom authority" style={{padding:12,marginBottom:12,border:`1px solid ${C.border}`,borderRadius:12,background:C.panelSoft,display:"flex",gap:8,alignItems:"center",flexWrap:"wrap"}}><strong>{actor.display_name||"HQ operator"}</strong><Tag color={actor.is_founder?C.green:C.blue}>{actor.role.replaceAll("_"," ")}</Tag><span style={{fontSize:11,color:C.muted}}>{actor.is_founder?"Founder authority":actor.can_coordinate?"Can coordinate and escalate · founder approval remains protected":"Read-only visibility"}</span></section>}
  {error&&<div role="alert" style={{padding:12,marginBottom:12,border:"1px solid rgba(239,68,68,.4)",borderRadius:10,color:"#fecaca"}}>{friendly(error)}</div>}
  {c&&<section aria-label="Workroom health" style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(125px,1fr))",gap:8,marginBottom:12}}>{[["Active",c.active,C.blue],["My work",c.mine,C.green],["Blocked",c.blocked,c.blocked?C.red:C.green],["Approvals",c.waiting_approval,c.waiting_approval?C.amber:C.green],["Overdue",c.overdue,c.overdue?C.red:C.green],["Unassigned",c.unassigned,c.unassigned?C.amber:C.green],["Journeys at risk",c.journeys_at_risk,c.journeys_at_risk?C.red:C.green]].map(([label,value,color])=><Metric key={String(label)} label={String(label)} value={Number(value)} color={String(color)}/>)}</section>}
  <HQPanel title="Operating views" description="Choose the work you are trying to move; the database enforces what this identity may do."><div style={{padding:12,display:"grid",gap:10}}><div style={{display:"flex",gap:7,overflowX:"auto",paddingBottom:3}}>{views.map(([key,label])=><button key={key} onClick={()=>setView(key)} aria-pressed={view===key} style={{...hqButtonStyle,flex:"0 0 auto",color:view===key?C.green:C.muted}}>{label}</button>)}</div><div style={{display:"flex",gap:8,alignItems:"center",flexWrap:"wrap"}}><span style={{fontSize:11,color:C.muted}}>{views.find(x=>x[0]===view)?.[2]}</span><select aria-label="Department" value={department||""} onChange={e=>setDepartment(e.target.value||null)} style={{marginLeft:"auto",minHeight:40,borderRadius:9,border:`1px solid ${C.border}`,background:C.panel,color:C.text,padding:"0 10px"}}><option value="">All departments</option>{departments.map(d=><option key={d.key} value={d.key}>{d.name}</option>)}</select></div></div></HQPanel>
  <section style={{display:"grid",gap:10,marginTop:12}}>{loading&&!data?<Empty>Loading authoritative work state…</Empty>:data?.items.length?data.items.map(item=><WorkCard key={item.id} item={item}/>):<Empty>No work matches this view. Choose All active to inspect the complete queue.</Empty>}</section>
 </HQPage>}
function WorkCard({item}:{item:HQWorkItem}){const overdue=Boolean(item.due_at&&new Date(item.due_at).getTime()<Date.now()&&!['resolved','cancelled'].includes(item.status));return <article style={{padding:14,border:`1px solid ${item.status==='blocked'||item.status==='failed'?'rgba(239,68,68,.35)':C.border}`,borderRadius:13,background:C.panel}}><div className="hq-mobile-stack"><div style={{minWidth:0}}><div style={{display:"flex",gap:6,alignItems:"center",flexWrap:"wrap"}}><Tag color={item.priority==='critical'?C.red:item.priority==='high'?C.amber:C.muted}>{item.priority}</Tag><Tag color={statusTone[item.status]||C.muted}>{item.status.replaceAll('_',' ')}</Tag><Tag color={item.evidence_status==='verified'?C.green:item.evidence_status==='failed'?C.red:C.muted}>evidence {item.evidence_status}</Tag>{item.affected_persona&&<Tag color={C.cyan}>{item.affected_persona.replaceAll('_',' ')}</Tag>}{overdue&&<Tag color={C.red}>overdue</Tag>}</div><h2 style={{fontSize:15,margin:"9px 0 0"}}>{item.title}</h2>{item.summary&&<p style={{fontSize:11.5,lineHeight:1.55,color:C.muted,margin:"5px 0 0"}}>{item.summary}</p>}<div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(170px,1fr))",gap:7,marginTop:10}}><Fact label="Accountability" value={item.assignee_id?"Assigned":"Unassigned — coordination required"} danger={!item.assignee_id}/><Fact label="Next action" value={item.next_action||"Not defined — clarify before execution"} danger={!item.next_action}/><Fact label="Delivery" value={item.delivery_status.replaceAll('_',' ')}/><Fact label="Authority" value={item.authority_required}/></div>{item.blocker&&<div role="status" style={{marginTop:9,padding:9,borderRadius:9,background:"rgba(239,68,68,.08)",color:"#fecaca",fontSize:11}}><strong>Blocked:</strong> {item.blocker}</div>}</div><Link href={`/hq/workroom/${item.id}`} style={{...hqButtonStyle,display:"inline-flex",alignItems:"center",justifyContent:"center",textDecoration:"none",color:C.green}}>Open mission</Link></div></article>}
function Metric({label,value,color}:{label:string;value:number;color:string}){return <div style={{padding:12,border:`1px solid ${C.border}`,borderRadius:12,background:C.panelSoft}}><b style={{fontSize:22,color}}>{value}</b><div style={{fontSize:10.5,color:C.muted}}>{label}</div></div>}
function Tag({children,color}:{children:React.ReactNode;color:string}){return <span className="hq-status" style={{color}}>{children}</span>}
function Fact({label,value,danger=false}:{label:string;value:string;danger?:boolean}){return <div><small style={{display:"block",fontSize:9,color:C.muted,textTransform:"uppercase",fontWeight:900}}>{label}</small><span style={{fontSize:11,color:danger?C.amber:C.text}}>{value}</span></div>}
function Empty({children}:{children:React.ReactNode}){return <div style={{padding:28,textAlign:"center",fontSize:12,color:C.muted,border:`1px solid ${C.border}`,borderRadius:12}}>{children}</div>}
function friendly(error:string){if(error.includes("permission_denied"))return "This HQ identity does not have Workroom access. Ask the Founder to grant the specific permission required.";return error}
