import type { Metadata } from 'next'
import Link from 'next/link'
import trustPack from '@/config/school-trust-pack.json'
import { PublicHeader } from '@/components/public/PublicHeader'
import { PublicFooter } from '@/components/public/PublicFooter'
import { TrustPackActions } from '@/components/public/TrustPackActions'

export const metadata: Metadata={
  alternates:{canonical:'/trust/schools'},
  title:'School Trust Pack | Security, Privacy & Due Diligence',
  description:'Inspect VibeSchool’s school due-diligence position across security, access, child safety, privacy, AI, retention, incidents, migration and implementation.',
}

const diligence=[
  ['Identity & authority','Who authenticates? What creates a teacher, family or administrator relationship? Which actions are enforced in the server/database rather than the browser?'],
  ['Learner data','What learner data is needed for the selected workflow? What is optional? Who can see it and what happens when a relationship is revoked?'],
  ['Security testing','Which exact deployment routes/RPCs/storage paths have been adversarially tested for cross-school or cross-family access? Which remain under validation?'],
  ['Retention & exit','Which records must be retained, which can be deleted, how are rights requests handled and what does an institution receive or remove at exit?'],
  ['AI & automation','Which features use automation or AI, what evidence they may act on, what they may never decide alone and what human review remains required?'],
  ['Implementation','What source data is migrated, who validates it, how pilot acceptance is measured and how the school can stop/revert before wider rollout?'],
  ['Reliability','Which devices/connectivity/offline conditions are in scope and what evidence proves the selected workflow survives them?'],
  ['Commercial / support','What is included in price, support, service levels, escalation and renewal — and which commitments are contractual rather than marketing language?'],
] as const

export default function SchoolTrustPackPage(){return <div className="page"><PublicHeader product="School Trust Pack"/><main id="main-content">
<section className="hero"><div className="wrap"><Link className="back" href="/trust">← Trust Centre</Link><p className="eyebrow">PROCUREMENT-GRADE TRUST</p><h1>Inspect what is proven, what is still being validated and what must be agreed before a school depends on VibeSchool.</h1><p className="lead">Marketing trust is not institutional due diligence. This pack exposes the current boundary instead of converting architecture work into certifications VibeSchool has not earned.</p><TrustPackActions/></div></section>
<section className="section wrap"><p className="eyebrow dark">CURRENT TRUST LEDGER</p><h2>Capability and certification are not the same status.</h2><div className="ledger">{trustPack.items.map(item=><article key={item.area}><div><h3>{item.area}</h3><p>{item.evidence}</p></div><strong data-status={item.status}>{item.status}</strong></article>)}</div><p className="review">Trust Pack reviewed {trustPack.reviewed_on}. Status vocabulary is limited to Available / Validation / Planned.</p></section>
<section className="section alt"><div className="wrap"><p className="eyebrow dark">SECURITY ARCHITECTURE</p><h2>Authority should survive a hostile client.</h2><div className="grid"><article><h3>Identity</h3><p>Authentication identifies the caller. Product role, school authority and family/learner relationships must be resolved separately rather than trusted from a UI choice.</p></article><article><h3>Authorization</h3><p>Sensitive data and mutations should be constrained by role, relationship, assignment and school scope at server/database boundaries. Browser navigation is not treated as authorization.</p></article><article><h3>Data minimisation</h3><p>Public experiences should not need private learner data. Institutional workflows should use only the learner, staff or school information required for the defined purpose.</p></article><article><h3>Audit & verification</h3><p>Consequential changes should leave enough lineage to reconstruct identity, authority, mutation and outcome. Where that chain is not yet certified, the Trust Pack keeps the item in Validation.</p></article></div></div></section>
<section className="section wrap"><div className="two"><div><p className="eyebrow dark">CHILD SAFETY & PRIVACY</p><h2>Children need stronger boundaries than ordinary SaaS users.</h2></div><div><p>VibeSchool’s published privacy position says learner information is not sold, learner personal information is not used for behavioural advertising, and child data requires stronger authority/consent/best-interest safeguards.</p><p>Institutional due diligence should still establish the school’s role, VibeSchool’s role, the lawful basis for each required processing purpose, the minimum fields needed and the process for access/correction/deletion requests.</p><div className="links"><Link href="/legal/privacy">Privacy Policy →</Link><Link href="/trust/child-safety">Child-safety approach →</Link></div></div></div></section>
<section className="section dark"><div className="wrap two"><div><p className="eyebrow">AI & AUTOMATION</p><h2>Automation may assist; authority must remain governed.</h2></div><div><p>VibeSchool should distinguish suggestions, deterministic automation and consequential decisions. AI output is not automatically curriculum truth, learner mastery, school authority or permission to change sensitive records.</p><p>Any institutional pilot should document the exact automated features in scope, their data inputs, human review, escalation and disable/rollback path.</p><Link className="lightLink" href="/trust/responsible-ai">Responsible AI approach →</Link></div></div></section>
<section className="section wrap" id="due-diligence"><p className="eyebrow dark">BUYER CHECKLIST</p><h2>Questions to resolve before procurement or pilot sign-off.</h2><div className="questions">{diligence.map(([title,body])=><article key={title}><h3>{title}</h3><p>{body}</p></article>)}</div></section>
<section className="section alt"><div className="wrap two"><div><p className="eyebrow dark">IMPLEMENTATION & DATA MIGRATION</p><h2>Discover → Diagnose → Pilot → Measure → Expand.</h2></div><div><ol><li><strong>Discover:</strong> define the school problem and users.</li><li><strong>Diagnose:</strong> map current workflow, data, authority and baseline.</li><li><strong>Pilot:</strong> configure one bounded workflow and acceptance criteria.</li><li><strong>Measure:</strong> test reliability, workload, usefulness and authorization under real conditions.</li><li><strong>Expand:</strong> only after the previous scope earns trust and evidence.</li></ol><p>Migration follows the same rule: inspect actual source records and identifiers before promising import coverage.</p></div></div></section>
<section className="section wrap"><div className="two"><div><p className="eyebrow dark">EXTERNAL DUE-DILIGENCE SOURCES</p><h2>Institutional review does not end on VibeSchool’s website.</h2></div><div className="external"><a href="https://www.odpc.go.ke/guidelines-2/" target="_blank" rel="noopener noreferrer">ODPC guidance, including Education Sector, Children's Data and DPIA ↗</a><a href="https://ppra.go.ke/standard-tender-documents/" target="_blank" rel="noopener noreferrer">PPRA standard tender documents, including Information Technology ↗</a><a href="https://ppra.go.ke/circulars/" target="_blank" rel="noopener noreferrer">PPRA current procurement circulars ↗</a><Link href="/contact">Ask VibeSchool a due-diligence question →</Link></div></div></section>
</main><PublicFooter/><style>{styles}</style></div>}

const styles=`.page{background:#f8f8f5;color:#101827;font-family:var(--font-jakarta),Arial,sans-serif;line-height:1.7}.page *{box-sizing:border-box}.wrap{max-width:1120px;margin:auto}.hero{background:#07111f;color:#fff;padding:86px 24px}.back{color:#c5cfda;text-decoration:none}.eyebrow{font:850 11px var(--font-mono);letter-spacing:.15em;color:#d0b154;margin-top:28px}.eyebrow.dark{color:#755b17}h1,h2{font-family:var(--font-display),Arial,sans-serif;letter-spacing:-.04em;line-height:1.06}h1{font-size:clamp(42px,5.8vw,70px);max-width:960px;margin:12px 0 20px}h2{font-size:clamp(31px,4.3vw,48px);margin:9px 0 25px}.lead{font-size:18px;color:#c6cfda;max-width:850px}.section{padding:80px 24px}.alt{background:#eeeae0}.dark{background:#13243a;color:#fff}.ledger{display:grid;gap:10px}.ledger article{display:flex;justify-content:space-between;gap:20px;background:#fff;border:1px solid #dfe2e7;border-radius:14px;padding:21px}.ledger h3{margin:0}.ledger p{color:#606976;margin:5px 0}.ledger strong{white-space:nowrap;height:max-content;border-radius:999px;padding:7px 10px;font-size:12px;background:#eef0f4}.ledger strong[data-status='Available']{background:#e7f4eb;color:#205c35}.ledger strong[data-status='Validation']{background:#fff2cf;color:#76580c}.review{font-size:13px;color:#707782}.grid,.questions{display:grid;grid-template-columns:repeat(2,1fr);gap:12px}.grid article,.questions article{background:#fff;border:1px solid #dfe2e7;border-radius:14px;padding:22px}.grid h3,.questions h3{margin:0}.grid p,.questions p,.two p{color:#5e6875}.two{display:grid;grid-template-columns:1fr 1fr;gap:64px}.dark .two p{color:#c5cfda}.links,.external{display:grid;gap:8px}.links a,.external a{color:#654f13;font-weight:800}.lightLink{color:#e2c66e;font-weight:850}.two ol{padding-left:20px;color:#5e6875}.two li{margin-bottom:8px}@media(max-width:760px){.hero,.section{padding:60px 18px}.grid,.questions,.two{grid-template-columns:1fr}.two{gap:15px}.ledger article{flex-direction:column}}`
