"use client"
import {useCallback,useEffect,useState} from "react"
import {hqSupabase} from "@/lib/hq/supabase"
import {HQPage,HQPanel,HQ_THEME as C,hqButtonStyle} from "@/components/hq/HQShell"
type R={summary:{active:number;trialing:number;past_due:number;cancelled:number;revenue_30d:number};subscriptions:Array<{id:string;profile_id:string;full_name:string|null;plan_key:string;status:string;currency:string;amount:number;billing_interval:string;current_period_end:string|null}>}
type O=Record<string,any>
function Stat({label,value,tone=C.text,note}:{label:string;value:unknown;tone?:string;note?:string}){return <div style={{padding:14,border:`1px solid ${C.border}`,borderRadius:13,background:C.panelSoft}}><strong style={{display:"block",fontSize:23,color:tone}}>{String(value??"—")}</strong><span style={{fontSize:10.5,color:C.muted}}>{label}</span>{note&&<small style={{display:"block",marginTop:4,color:C.muted,lineHeight:1.4}}>{note}</small>}</div>}
export default function HQBilling(){const[d,setD]=useState<R|null>(null),[ops,setOps]=useState<O|null>(null),[error,setError]=useState(""),[loading,setLoading]=useState(true);const load=useCallback(async()=>{setLoading(true);setError("");try{const[b,o]=await Promise.all([hqSupabase.rpc("hq_billing_overview",{p_limit:200}),(hqSupabase as any).rpc("hq_revenue_operations_snapshot")]);if(b.error)throw b.error;if(o.error)throw o.error;setD(b.data as R);setOps(o.data as O)}catch(e){setError(e instanceof Error?e.message:"Revenue operations could not be loaded.")}finally{setLoading(false)}},[]);useEffect(()=>{void load()},[load]);const m=ops?.mpesa??{},orders=ops?.orders??{},attempts=ops?.payment_attempts??{},callbacks=ops?.callbacks??{},ent=ops?.entitlements??{},rec=ops?.reconciliation??{};return <HQPage title="Revenue Operations" description="Subscription, M-Pesa, settlement, fulfillment and entitlement truth — each state remains distinct." actions={<button onClick={()=>void load()} style={hqButtonStyle} disabled={loading}>{loading?"Refreshing…":"Refresh"}</button>}>
{error&&<div role="alert" style={{color:"#fecaca",border:`1px solid ${C.red}55`,padding:11,borderRadius:10,marginBottom:12}}>{error}</div>}
<section style={{padding:14,border:`1px solid ${m.initiation_enabled?C.green:C.amber}55`,borderRadius:14,marginBottom:12,background:m.initiation_enabled?`${C.green}0d`:`${C.amber}0d`}}><strong style={{color:m.initiation_enabled?C.green:C.amber}}>M-Pesa initiation {m.initiation_enabled?"ON":"OFF"}</strong><div style={{marginTop:5,fontSize:11,color:C.muted}}>An inactive payment pipeline is not reported as successful revenue. Initiation, callback, settlement, fulfillment and entitlement are certified separately.</div></section>
<section style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(145px,1fr))",gap:9,marginBottom:12}}><Stat label="Orders" value={orders.total}/><Stat label="Initiated / pending" value={orders.initiated}/><Stat label="Paid" value={orders.paid}/><Stat label="Fulfilled" value={orders.fulfilled}/><Stat label="Paid not fulfilled" value={orders.paid_not_fulfilled} tone={orders.paid_not_fulfilled?C.red:C.green}/><Stat label="Active entitlements" value={ent.active}/></section>
<div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(280px,1fr))",gap:12,marginBottom:12}}><HQPanel title="M-Pesa execution chain"><div style={{padding:14,display:"grid",gap:8,fontSize:11.5}}><div>Requests · 7d <strong>{String(attempts.requested_7d??"—")}</strong></div><div>Callbacks received · 7d <strong>{String(attempts.callback_received_7d??"—")}</strong></div><div>Settled · 7d <strong>{String(attempts.settled_7d??"—")}</strong></div><div>Missing callback &gt;15m <strong style={{color:attempts.callback_missing_over_15m?C.red:C.green}}>{String(attempts.callback_missing_over_15m??"—")}</strong></div><div>Attempt processing errors · 7d <strong style={{color:attempts.processing_errors_7d?C.red:C.green}}>{String(attempts.processing_errors_7d??"—")}</strong></div><div>Unprocessed callbacks <strong style={{color:callbacks.unprocessed?C.red:C.green}}>{String(callbacks.unprocessed??"—")}</strong></div></div></HQPanel><HQPanel title="Reconciliation exceptions"><div style={{padding:14,display:"grid",gap:8,fontSize:11.5}}><div>Callback without attempt <strong style={{color:rec.callback_without_attempt?C.red:C.green}}>{String(rec.callback_without_attempt??"—")}</strong></div><div>Paid without entitlement <strong style={{color:rec.paid_without_entitlement?C.red:C.green}}>{String(rec.paid_without_entitlement??"—")}</strong></div><div>Refunded orders <strong>{String(orders.refunded??"—")}</strong></div><div>Cancelled orders <strong>{String(orders.cancelled??"—")}</strong></div></div></HQPanel></div>
<section style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(150px,1fr))",gap:10,marginBottom:12}}>{[["Active subscriptions",d?.summary.active],["Trialing",d?.summary.trialing],["Past due",d?.summary.past_due],["Cancelled",d?.summary.cancelled],["30d subscription total",d?`${d.summary.revenue_30d} KES`:"—"]].map(([a,v])=><HQPanel key={String(a)} title={String(a)}><div style={{padding:14,fontSize:24,fontWeight:900}}>{v??"—"}</div></HQPanel>)}</section>
<HQPanel title="Account subscription status">{d?.subscriptions?.length?d.subscriptions.map(s=><div key={s.id} style={{padding:"12px 14px",borderTop:`1px solid ${C.border}`,display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(130px,1fr))",gap:10,fontSize:12}}><div><b>{s.full_name||s.profile_id}</b><div style={{color:C.muted,fontSize:10}}>{s.plan_key}</div></div><div style={{color:s.status==='active'?C.green:C.amber}}>{s.status}</div><div>{s.amount} {s.currency}/{s.billing_interval}</div><div>{s.current_period_end?new Date(s.current_period_end).toLocaleDateString():"—"}</div></div>):<div style={{padding:14,color:C.muted}}>No account billing records. This is an empty billing state, not evidence of payment success.</div>}</HQPanel></HQPage>}
