"use client"
import {useEffect,useState} from "react"
import {hqSupabase} from "@/lib/hq/supabase"
import {HQPage,HQPanel,HQ_THEME as C} from "@/components/hq/HQShell"

type SubscriptionOverview={summary:{active:number;trialing:number;past_due:number;cancelled:number;revenue_30d:number};subscriptions:Array<{id:string;profile_id:string;full_name:string|null;plan_key:string;status:string;currency:string;amount:number;billing_interval:string;current_period_end:string|null}>}
type PaymentOverview={runtime:{initiation_enabled?:boolean;activation_reason?:string|null;activated_at?:string|null;updated_at?:string|null};summary:{initiated:number;successful:number;pending:number;failed:number;reconciliation_required:number;active_entitlements:number;reconciled_revenue_kes:number;reconciled_revenue_30d_kes:number};recent:Array<{attempt_id:string;order_id:string;state:string;amount_kes:number;currency:string;product_id:string;checkout_request_id:string|null;provider_receipt:string|null;receipt_number:string|null;issued_at:string|null;processing_error:string|null;created_at:string;updated_at:string}>;reconciliation:Array<{attempt_id:string;order_id:string;state:string;amount_kes:number;checkout_request_id:string|null;processing_error:string|null;created_at:string;updated_at:string}>}

export default function HQBilling(){
 const [d,setD]=useState<SubscriptionOverview|null>(null),[p,setP]=useState<PaymentOverview|null>(null),[error,setError]=useState("")
 useEffect(()=>{void(async()=>{const [billing,payments]=await Promise.all([hqSupabase.rpc("hq_billing_overview",{p_limit:200}),hqSupabase.rpc("hq_payment_finance_overview",{p_limit:200})]);if(billing.error||payments.error)setError(billing.error?.message||payments.error?.message||"Finance state unavailable");else{setD(billing.data as SubscriptionOverview);setP(payments.data as PaymentOverview)}})()},[])
 const paymentTone=p?.runtime?.initiation_enabled?C.green:C.amber
 return <HQPage title="Billing & payment integrity" description="Owner-only view of subscriptions, M-Pesa financial truth, entitlements and reconciliation state.">
  {error&&<div style={{color:C.red,marginBottom:12}}>{error}</div>}
  <section style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(150px,1fr))",gap:10,marginBottom:12}}>
   {[['Active',d?.summary.active],['Trialing',d?.summary.trialing],['Past due',d?.summary.past_due],['Cancelled',d?.summary.cancelled],['30d subscription signals',d?`${d.summary.revenue_30d} KES`:"—"]].map(([a,v])=><HQPanel key={String(a)} title={String(a)}><div style={{padding:14,fontSize:24,fontWeight:900}}>{v??"—"}</div></HQPanel>)}
  </section>
  <HQPanel title="M-Pesa operating state"><div style={{padding:14,display:"grid",gap:6,fontSize:12}}><b style={{color:paymentTone}}>{p?.runtime?.initiation_enabled?"Initiation ON":"Initiation OFF"}</b><span style={{color:C.muted}}>OFF blocks new STK pushes while callbacks, status and reconciliation remain available.</span>{p?.runtime?.activation_reason&&<span style={{color:C.muted}}>Reason: {p.runtime.activation_reason}</span>}</div></HQPanel>
  <section style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(150px,1fr))",gap:10,margin:"12px 0"}}>
   {[['STK initiated',p?.summary.initiated],['Confirmed payments',p?.summary.successful],['Pending',p?.summary.pending],['Failed/cancelled/expired',p?.summary.failed],['Needs reconciliation',p?.summary.reconciliation_required],['Active paid entitlements',p?.summary.active_entitlements],['Reconciled revenue',p?`${p.summary.reconciled_revenue_kes} KES`:"—"],['30d reconciled revenue',p?`${p.summary.reconciled_revenue_30d_kes} KES`:"—"]].map(([a,v])=><HQPanel key={String(a)} title={String(a)}><div style={{padding:14,fontSize:22,fontWeight:900,color:String(a)==='Needs reconciliation'&&Number(v)>0?C.red:undefined}}>{v??"—"}</div></HQPanel>)}
  </section>
  <HQPanel title="Payment reconciliation queue">{p?.reconciliation?.length?p.reconciliation.map(x=><div key={x.attempt_id} style={{padding:"12px 14px",borderTop:`1px solid ${C.border}`,display:"grid",gridTemplateColumns:"1.3fr .7fr 1.2fr 2fr",gap:10,fontSize:11}}><div><b>{x.attempt_id}</b><div style={{color:C.muted}}>{x.order_id}</div></div><div>{x.amount_kes} KES</div><div style={{color:C.red}}>{x.state}</div><div style={{color:C.muted}}>{x.processing_error||"Provider evidence requires review"}</div></div>):<div style={{padding:14,color:C.muted}}>No payments require reconciliation.</div>}</HQPanel>
  <HQPanel title="Recent M-Pesa payments">{p?.recent?.length?p.recent.map(x=><div key={x.attempt_id} style={{padding:"12px 14px",borderTop:`1px solid ${C.border}`,display:"grid",gridTemplateColumns:"1.4fr .7fr .8fr 1fr",gap:10,fontSize:11}}><div><b>{x.receipt_number||x.attempt_id}</b><div style={{color:C.muted}}>{x.order_id}</div></div><div>{x.amount_kes} {x.currency}</div><div style={{color:x.state==='settled'?C.green:x.state==='reconciliation_required'?C.red:C.amber}}>{x.state}</div><div style={{color:C.muted}}>{x.provider_receipt||"No confirmed M-Pesa receipt"}</div></div>):<div style={{padding:14,color:C.muted}}>No M-Pesa payment attempts yet.</div>}</HQPanel>
  <HQPanel title="Account billing status">{d?.subscriptions?.length?d.subscriptions.map(s=><div key={s.id} style={{padding:"12px 14px",borderTop:`1px solid ${C.border}`,display:"grid",gridTemplateColumns:"2fr 1fr 1fr 1fr",gap:10,fontSize:12}}><div><b>{s.full_name||s.profile_id}</b><div style={{color:C.muted,fontSize:10}}>{s.plan_key}</div></div><div style={{color:s.status==='active'?C.green:C.amber}}>{s.status}</div><div>{s.amount} {s.currency}/{s.billing_interval}</div><div>{s.current_period_end?new Date(s.current_period_end).toLocaleDateString():"—"}</div></div>):<div style={{padding:14,color:C.muted}}>No account billing records.</div>}</HQPanel>
 </HQPage>
}
