"use client"

import { useEffect, useMemo, useState } from "react"
import { useRouter } from "next/navigation"
import { HQPage, HQPanel, HQ_THEME, hqButtonStyle } from "@/components/hq/HQShell"
import { acknowledgeHQNotification, loadHQFounderBrief, loadHQNotifications, markHQNotificationRead, openHQNotificationWorkroom, resolveHQNotification, setHQNotificationFeedback, type HQFounderBrief, type HQNotification, type HQNotificationClass } from "@/lib/hq/operating"

type View="active"|"all"|"resolved"|"overdue"|"opportunities"|HQNotificationClass
const views:Array<{key:View;label:string}>=[{key:"active",label:"Active"},{key:"critical",label:"Act now"},{key:"action_required",label:"Action required"},{key:"overdue",label:"Overdue"},{key:"opportunities",label:"Opportunities"},{key:"important",label:"Important"},{key:"digest",label:"Digest"},{key:"resolved",label:"Resolved"},{key:"all",label:"All"}]
const classLabel:Record<HQNotificationClass,string>={critical:"Act now",action_required:"Action required",important:"Important",digest:"Digest"}
const severityColor:Record<HQNotification["severity"],string>={info:HQ_THEME.blue,success:HQ_THEME.green,warning:HQ_THEME.amber,critical:HQ_THEME.red}
function formatTime(value:string){const date=new Date(value);return Number.isNaN(date.getTime())?"Time unavailable":date.toLocaleString("en-KE")}
function dueLabel(item:HQNotification){if(!item.due_at||item.status==="resolved")return null;const ms=new Date(item.due_at).getTime()-Date.now();const mins=Math.round(Math.abs(ms)/60000);if(ms<0)return `Overdue ${mins<60?`${mins}m`:`${Math.round(mins/60)}h`}`;return `Due ${mins<60?`${mins}m`:`${Math.round(mins/60)}h`}`}
function matchesView(item:HQNotification,view:View){if(view==="all")return true;if(view==="active")return item.status!=="resolved";if(view==="resolved")return item.status==="resolved";if(view==="overdue")return item.status!=="resolved"&&!!item.due_at&&new Date(item.due_at).getTime()<Date.now();if(view==="opportunities")return item.status!=="resolved"&&typeof item.metadata?.opportunity_type==="string";return item.status!=="resolved"&&item.notification_class===view}
export default function HQNotificationsPage(){
 const router=useRouter();const[items,setItems]=useState<HQNotification[]>([]);const[brief,setBrief]=useState<HQFounderBrief|null>(null);const[view,setView]=useState<View>("active");const[query,setQuery]=useState("");const[loading,setLoading]=useState(true);const[error,setError]=useState<string|null>(null);const[busy,setBusy]=useState("")
 async function refresh(){setLoading(true);setError(null);try{const[nextItems,nextBrief]=await Promise.all([loadHQNotifications(250),loadHQFounderBrief()]);setItems(Array.isArray(nextItems)?nextItems:[]);setBrief(nextBrief??null)}catch{setError("Signals could not be loaded. Nothing was changed. Try again.")}finally{setLoading(false)}}
 useEffect(()=>{void refresh();const timer=window.setInterval(()=>void refresh(),60000);return()=>window.clearInterval(timer)},[])
 const summary=useMemo(()=>{const active=items.filter(item=>item.status!=="resolved");return{active:active.length,critical:active.filter(item=>item.notification_class==="critical").length,action:active.filter(item=>item.notification_class==="action_required").length,overdue:active.filter(item=>item.due_at&&new Date(item.due_at).getTime()<Date.now()).length}},[items])
 const visible=useMemo(()=>{const normalized=query.trim().toLowerCase();return items.filter(item=>matchesView(item,view)&&(!normalized||`${item.title} ${item.body} ${item.category} ${item.owner_department??""}`.toLowerCase().includes(normalized)))},[items,query,view])
 async function act(id:string,fn:()=>Promise<void>,after:()=>void){setBusy(id);setError(null);try{await fn();after()}catch{setError("That signal action could not be completed. Nothing should be assumed changed; refresh before retrying.")}finally{setBusy("")}}
 async function openSignal(item:HQNotification){if(item.status==="unread"){try{await markHQNotificationRead(item.id);setItems(current=>current.map(entry=>entry.id===item.id?{...entry,status:"read"}:entry))}catch{setError("The signal opened, but its read status could not be saved.")}}if(item.route)router.push(item.route)}
 async function openWorkroom(item:HQNotification){setBusy(item.id);setError(null);try{const workItemId=item.work_item_id??await openHQNotificationWorkroom(item.id);if(!workItemId){setError("A workroom could not be created for this signal.");return}setItems(current=>current.map(entry=>entry.id===item.id?{...entry,work_item_id:workItemId}:entry));router.push(`/hq/workroom/${workItemId}`)}catch{setError("The workroom could not be opened. Nothing was changed.")}finally{setBusy("")}}
 return <HQPage title="Signal Center" description="What needs attention, why it matters, who owns it, and what you can do next." actions={<button style={hqButtonStyle} onClick={()=>void refresh()} disabled={loading}>{loading?"Refreshing…":"Refresh"}</button>}>
  <div className="sig-metrics"><Metric label="Active" value={summary.active}/><Metric label="Act now" value={summary.critical} accent={HQ_THEME.red}/><Metric label="Action required" value={summary.action} accent={HQ_THEME.amber}/><Metric label="Overdue" value={summary.overdue} accent={summary.overdue?HQ_THEME.red:HQ_THEME.green}/><Metric label="Opportunities" value={brief?.headline?.opportunities??0} accent={HQ_THEME.green}/></div>
  {brief&&<HQPanel title="Founder brief" description={`Updated ${formatTime(brief.generated_at)}`}><div className="sig-brief"><BriefStat label="New users today" value={brief.headline?.new_users_today??0} note={`Yesterday ${brief.headline?.new_users_yesterday??0}`}/><BriefStat label="Open incidents" value={brief.headline?.open_incidents??0}/><BriefStat label="Payment failures · 24h" value={brief.headline?.payment_failures_24h??0}/><BriefStat label="Opportunities" value={brief.headline?.opportunities??0}/></div></HQPanel>}
  <div style={{height:14}}/><HQPanel><div className="sig-toolbar"><div className="sig-tabs">{views.map(option=><button key={option.key} onClick={()=>setView(option.key)} style={{...hqButtonStyle,minHeight:38,padding:"0 10px",whiteSpace:"nowrap",background:view===option.key?"rgba(52,211,153,.1)":hqButtonStyle.background,borderColor:view===option.key?"rgba(52,211,153,.3)":HQ_THEME.border}}>{option.label}</button>)}</div><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search signals" aria-label="Search HQ signals" className="sig-search"/></div>
  {error&&<div role="alert" className="sig-error">{error}</div>}{!loading&&!error&&visible.length===0&&<div className="sig-empty">No signals need attention in this view.</div>}
  <div>{visible.map(item=>{const needsAck=(item.notification_class==="critical"||item.notification_class==="action_required")&&!item.acknowledged_at&&item.status!=="resolved";const due=dueLabel(item);return <article key={item.id} className="sig-card"><div className="sig-copy"><div className="sig-meta"><span style={{color:severityColor[item.severity]}}>{classLabel[item.notification_class]}</span><span>{item.category.replaceAll("_"," ")}</span>{item.owner_department&&<span>Owner: {item.owner_department.replaceAll("_"," ")}</span>}{due&&<span style={{color:due.startsWith("Overdue")?HQ_THEME.red:HQ_THEME.muted}}>{due}</span>}{item.escalation_level>0&&<span style={{color:HQ_THEME.red}}>Escalated</span>}{item.occurrence_count>1&&<span>Seen {item.occurrence_count} times</span>}</div><h2>{item.title}</h2>{item.body&&<p>{item.body}</p>}<small>Last seen {formatTime(item.last_seen_at||item.created_at)}{item.acknowledged_at?" · acknowledged":""}{item.status==="resolved"?" · resolved":""}</small></div><div className="sig-actions">{item.route&&item.status!=="resolved"&&<button style={hqButtonStyle} disabled={busy===item.id} onClick={()=>void openSignal(item)}>{item.action_label||"Review"}</button>}{(item.notification_class==="critical"||item.notification_class==="action_required")&&item.status!=="resolved"&&<button style={hqButtonStyle} disabled={busy===item.id} onClick={()=>void openWorkroom(item)}>Work on this</button>}{needsAck&&<button style={hqButtonStyle} disabled={busy===item.id} onClick={()=>void act(item.id,()=>acknowledgeHQNotification(item.id),()=>setItems(current=>current.map(entry=>entry.id===item.id?{...entry,status:entry.status==="unread"?"read":entry.status,acknowledged_at:entry.acknowledged_at??new Date().toISOString()}:entry)))}>Acknowledge</button>}{item.status!=="resolved"&&<button style={hqButtonStyle} disabled={busy===item.id} onClick={()=>void act(item.id,()=>setHQNotificationFeedback(item.id,"useful"),()=>setItems(current=>current.map(entry=>entry.id===item.id?{...entry,feedback:"useful",feedback_at:new Date().toISOString()}:entry)))}>Useful</button>}{item.status!=="resolved"&&<button style={hqButtonStyle} disabled={busy===item.id} onClick={()=>void act(item.id,()=>resolveHQNotification(item.id),()=>setItems(current=>current.map(entry=>entry.id===item.id?{...entry,status:"resolved"}:entry)))}>Resolve</button>}</div></article>})}</div></HQPanel>
  <style jsx global>{`.sig-metrics{display:grid;grid-template-columns:repeat(auto-fit,minmax(140px,1fr));gap:10px;margin-bottom:14px}.sig-brief{display:grid;grid-template-columns:repeat(auto-fit,minmax(160px,1fr));gap:10px;padding:12px}.sig-toolbar{padding:12px;border-bottom:1px solid ${HQ_THEME.border};display:flex;gap:8px;align-items:center}.sig-tabs{display:flex;gap:6px;overflow-x:auto;flex:1;scrollbar-width:none}.sig-search{min-height:38px;min-width:210px;border-radius:10px;border:1px solid ${HQ_THEME.border};background:rgba(255,255,255,.035);color:${HQ_THEME.text};padding:0 11px;font-size:12px}.sig-error{margin:14px;padding:12px;border-radius:10px;border:1px solid rgba(251,113,133,.35);color:#fecdd3}.sig-empty{padding:32px 18px;text-align:center;color:${HQ_THEME.muted}}.sig-card{padding:16px;border-bottom:1px solid ${HQ_THEME.border};display:grid;grid-template-columns:minmax(0,1fr) auto;gap:16px}.sig-copy{min-width:0}.sig-meta{display:flex;gap:8px;flex-wrap:wrap;align-items:center;font-size:10px;font-weight:900;text-transform:uppercase;color:${HQ_THEME.muted}}.sig-card h2{margin:7px 0 4px;font-size:15px;line-height:1.35}.sig-card p{margin:0;color:rgba(248,250,252,.66);font-size:12px;line-height:1.55}.sig-card small{display:block;margin-top:8px;color:rgba(248,250,252,.38);font-size:10.5px}.sig-actions{display:flex;gap:7px;align-items:flex-start;flex-wrap:wrap;justify-content:flex-end;max-width:300px}@media(max-width:720px){.sig-metrics{grid-template-columns:repeat(2,1fr)}.sig-toolbar{display:block}.sig-search{width:100%;min-width:0;margin-top:10px}.sig-card{grid-template-columns:1fr;padding:15px 14px}.sig-actions{display:grid;grid-template-columns:1fr 1fr;max-width:none}.sig-actions button{width:100%;min-height:44px}.sig-meta{line-height:1.45}.sig-card h2{font-size:16px}.sig-card p{font-size:13px}}@media(max-width:380px){.sig-metrics,.sig-actions{grid-template-columns:1fr}}`}</style>
 </HQPage>
}
function Metric({label,value,accent=HQ_THEME.text}:{label:string;value:number;accent?:string}){return <div style={{border:`1px solid ${HQ_THEME.border}`,borderRadius:14,background:"rgba(255,255,255,.025)",padding:14}}><div style={{color:accent,fontSize:26,fontWeight:950}}>{value}</div><div style={{color:HQ_THEME.muted,fontSize:10.5,fontWeight:800,marginTop:5}}>{label}</div></div>}
function BriefStat({label,value,note}:{label:string;value:number;note?:string}){return <div style={{border:`1px solid ${HQ_THEME.border}`,borderRadius:12,padding:12,background:"rgba(255,255,255,.02)"}}><div style={{fontSize:10,color:HQ_THEME.muted,textTransform:"uppercase",fontWeight:850}}>{label}</div><div style={{fontSize:22,fontWeight:950,marginTop:4}}>{value}</div>{note&&<div style={{color:HQ_THEME.muted,fontSize:10.5,marginTop:2}}>{note}</div>}</div>}
