-- Preserve the valuable old Academy Studio on the real courses/modules/topics model.
create or replace function public.hq_list_academy_catalog()
returns jsonb language plpgsql security definer set search_path=public as $$
begin
 perform public.hq_assert_owner();
 return jsonb_build_object(
  'courses',coalesce((select jsonb_agg(to_jsonb(x)) from (select id,slug,title,institution,level,duration_label,domain,status,badge,description,weeks_count,modules_count,created_at from courses order by title) x),'[]'::jsonb),
  'modules',coalesce((select jsonb_agg(to_jsonb(x)) from (select id,course_id,slug,title,sequence_number,weeks_label,created_at from modules order by course_id,sequence_number) x),'[]'::jsonb),
  'topics',coalesce((select jsonb_agg(to_jsonb(x)) from (select id,module_id,slug,title,subtitle,sequence_number,week_number,concept_tab,kenya_context_tab,common_errors_tab,clinical_tip_tab,content_status,created_at from topics order by module_id,sequence_number) x),'[]'::jsonb)
 );
end $$;

create or replace function public.hq_upsert_academy_course(p_id uuid default null,p_slug text default null,p_title text default null,p_institution text default null,p_level text default null,p_duration_label text default null,p_domain text default 'education',p_status text default 'coming_soon',p_badge text default null,p_description text default null,p_weeks_count integer default null)
returns uuid language plpgsql security definer set search_path=public as $$
declare v_id uuid; v_slug text:=lower(regexp_replace(btrim(coalesce(p_slug,p_title,'')),'[^a-zA-Z0-9]+','-','g')); begin perform public.hq_assert_owner(); if nullif(btrim(coalesce(p_title,'')),'') is null or v_slug='' then raise exception 'Course title and slug are required'; end if; if p_domain not in ('health','tech','education','trade') then raise exception 'Invalid course domain'; end if; if p_status not in ('live','coming_soon') then raise exception 'Invalid course status'; end if; if p_id is null then insert into courses(slug,title,institution,level,duration_label,domain,status,badge,description,weeks_count,modules_count) values(v_slug,btrim(p_title),nullif(btrim(coalesce(p_institution,'')),''),nullif(btrim(coalesce(p_level,'')),''),nullif(btrim(coalesce(p_duration_label,'')),''),p_domain,p_status,nullif(btrim(coalesce(p_badge,'')),''),nullif(btrim(coalesce(p_description,'')),''),p_weeks_count,0) returning id into v_id; else update courses set slug=v_slug,title=btrim(p_title),institution=nullif(btrim(coalesce(p_institution,'')),''),level=nullif(btrim(coalesce(p_level,'')),''),duration_label=nullif(btrim(coalesce(p_duration_label,'')),''),domain=p_domain,status=p_status,badge=nullif(btrim(coalesce(p_badge,'')),''),description=nullif(btrim(coalesce(p_description,'')),''),weeks_count=p_weeks_count where id=p_id returning id into v_id; if v_id is null then raise exception 'Course not found'; end if; end if; return v_id; end $$;

create or replace function public.hq_upsert_academy_module(p_id uuid default null,p_course_id uuid default null,p_slug text default null,p_title text default null,p_sequence_number integer default 1,p_weeks_label text default null)
returns uuid language plpgsql security definer set search_path=public as $$
declare v_id uuid; v_slug text:=lower(regexp_replace(btrim(coalesce(p_slug,p_title,'')),'[^a-zA-Z0-9]+','-','g')); begin perform public.hq_assert_owner(); if p_course_id is null or nullif(btrim(coalesce(p_title,'')),'') is null then raise exception 'Course and module title are required'; end if; if p_id is null then insert into modules(course_id,slug,title,sequence_number,weeks_label) values(p_course_id,v_slug,btrim(p_title),greatest(p_sequence_number,1),nullif(btrim(coalesce(p_weeks_label,'')),'')) returning id into v_id; else update modules set course_id=p_course_id,slug=v_slug,title=btrim(p_title),sequence_number=greatest(p_sequence_number,1),weeks_label=nullif(btrim(coalesce(p_weeks_label,'')),'') where id=p_id returning id into v_id; if v_id is null then raise exception 'Module not found'; end if; end if; update courses set modules_count=(select count(*) from modules where course_id=p_course_id) where id=p_course_id; return v_id; end $$;

create or replace function public.hq_upsert_academy_topic(p_id uuid default null,p_module_id uuid default null,p_slug text default null,p_title text default null,p_subtitle text default null,p_sequence_number integer default 1,p_week_number integer default null,p_concept text default null,p_kenya_context text default null,p_common_errors text default null,p_clinical_tip text default null,p_content_status text default 'draft')
returns uuid language plpgsql security definer set search_path=public as $$
declare v_id uuid; v_slug text:=lower(regexp_replace(btrim(coalesce(p_slug,p_title,'')),'[^a-zA-Z0-9]+','-','g')); begin perform public.hq_assert_owner(); if p_module_id is null or nullif(btrim(coalesce(p_title,'')),'') is null then raise exception 'Module and topic title are required'; end if; if p_content_status not in ('draft','in_review','published') then raise exception 'Invalid topic status'; end if; if p_id is null then insert into topics(module_id,slug,title,subtitle,sequence_number,week_number,concept_tab,kenya_context_tab,common_errors_tab,clinical_tip_tab,content_status) values(p_module_id,v_slug,btrim(p_title),nullif(btrim(coalesce(p_subtitle,'')),''),greatest(p_sequence_number,1),p_week_number,jsonb_build_object('text',coalesce(p_concept,'')),jsonb_build_object('text',coalesce(p_kenya_context,'')),jsonb_build_object('text',coalesce(p_common_errors,'')),jsonb_build_object('text',coalesce(p_clinical_tip,'')),p_content_status) returning id into v_id; else update topics set module_id=p_module_id,slug=v_slug,title=btrim(p_title),subtitle=nullif(btrim(coalesce(p_subtitle,'')),''),sequence_number=greatest(p_sequence_number,1),week_number=p_week_number,concept_tab=jsonb_build_object('text',coalesce(p_concept,'')),kenya_context_tab=jsonb_build_object('text',coalesce(p_kenya_context,'')),common_errors_tab=jsonb_build_object('text',coalesce(p_common_errors,'')),clinical_tip_tab=jsonb_build_object('text',coalesce(p_clinical_tip,'')),content_status=p_content_status where id=p_id returning id into v_id; if v_id is null then raise exception 'Topic not found'; end if; end if; return v_id; end $$;

revoke all on function public.hq_list_academy_catalog() from public,anon;
revoke all on function public.hq_upsert_academy_course(uuid,text,text,text,text,text,text,text,text,text,integer) from public,anon;
revoke all on function public.hq_upsert_academy_module(uuid,uuid,text,text,integer,text) from public,anon;
revoke all on function public.hq_upsert_academy_topic(uuid,uuid,text,text,text,integer,integer,text,text,text,text,text) from public,anon;
grant execute on function public.hq_list_academy_catalog() to authenticated;
grant execute on function public.hq_upsert_academy_course(uuid,text,text,text,text,text,text,text,text,text,integer) to authenticated;
grant execute on function public.hq_upsert_academy_module(uuid,uuid,text,text,integer,text) to authenticated;
grant execute on function public.hq_upsert_academy_topic(uuid,uuid,text,text,text,integer,integer,text,text,text,text,text) to authenticated;
