-- VLR-ASSESS-001B: deliver grounded mistakes through the existing revision workspace.
create or replace function public.student_get_revision_workspace(p_subject text default null::text,p_topic text default null::text)
returns jsonb language plpgsql security definer set search_path=public,pg_temp as $function$
declare v_student uuid:=auth.uid(); v_readiness jsonb; v_days integer; v_mode text;
begin
 if v_student is null then raise exception 'Authentication required'; end if;
 select public.student_get_exam_readiness_brief() into v_readiness;
 v_days:=coalesce((v_readiness->>'days_remaining')::integer,999);
 v_mode:=case when v_days<=14 then 'final_sprint' when v_days<=60 then 'exam_revision' else 'steady_revision' end;
 return jsonb_build_object(
  'revision_mode',jsonb_build_object('mode',v_mode,'days_remaining',v_days,'message',case v_mode when 'final_sprint' then 'Protect sleep, practise under time, and review mistakes—not everything.' when 'exam_revision' then 'Use focused daily practice and weekly full-paper simulation.' else 'Build mastery steadily and close weak-topic gaps.' end),
  'today_plan',coalesce((select jsonb_agg(jsonb_build_object('id',id,'date',plan_date,'subject',subject,'topic',topic,'activity_type',activity_type,'target_minutes',target_minutes,'priority',priority,'reason',reason,'action_url',action_url,'status',status) order by priority,subject,topic) from public.student_revision_plan_items where student_id=v_student and plan_date=current_date),'[]'::jsonb),
  'week_plan',coalesce((select jsonb_agg(jsonb_build_object('id',id,'date',plan_date,'subject',subject,'topic',topic,'activity_type',activity_type,'target_minutes',target_minutes,'priority',priority,'reason',reason,'action_url',action_url,'status',status) order by plan_date,priority) from public.student_revision_plan_items where student_id=v_student and plan_date between current_date and current_date+6),'[]'::jsonb),
  'mistakes',coalesce((select jsonb_agg(jsonb_build_object('id',id,'question_id',exam_question_id,'source_block_id',source_block_id,'source_publication_id',source_publication_id,'source_chapter_id',source_chapter_id,'outcome_id',outcome_id,'review_url',case when source_block_id is not null and source_publication_id is not null and source_chapter_id is not null then '/read/textbook/'||source_publication_id::text||'?chapter='||source_chapter_id::text||'&block='||source_block_id::text else null end,'subject',subject,'topic',topic,'prompt',prompt_snapshot,'selected_index',selected_index,'correct_index',correct_index,'explanation',explanation_snapshot,'hint',hint_snapshot,'repeat_count',repeat_count,'status',status,'last_missed_at',last_missed_at) order by case status when 'open' then 0 when 'practising' then 1 else 2 end,repeat_count desc,last_missed_at desc) from public.student_mistake_notebook where student_id=v_student limit 40),'[]'::jsonb),
  'weak_topics',coalesce((select jsonb_agg(x) from (select subject,topic,count(*) filter(where not is_correct) misses,count(*) attempts,round(100.0*avg(case when is_correct then 1 else 0 end),0) accuracy from public.student_practice_attempts where student_id=v_student group by subject,topic order by misses desc,accuracy asc limit 12)x),'[]'::jsonb),
  'journey',jsonb_build_object('practice_attempts',(select count(*) from public.student_practice_attempts where student_id=v_student),'correct_answers',(select count(*) from public.student_practice_attempts where student_id=v_student and is_correct),'open_mistakes',(select count(*) from public.student_mistake_notebook where student_id=v_student and status<>'resolved'),'resolved_mistakes',(select count(*) from public.student_mistake_notebook where student_id=v_student and status='resolved'),'books_started',(select count(distinct publication_id) from public.vibe_reading_progress where viewer_id=v_student),'chapters_completed',(select count(*) from public.vibe_reading_progress where viewer_id=v_student and completed_at is not null),'learning_events_30d',(select count(*) from public.student_learning_events where student_id=v_student and occurred_at>=now()-interval '30 days')),
  'topic_workspace',case when nullif(btrim(coalesce(p_subject,'')),'') is null or nullif(btrim(coalesce(p_topic,'')),'') is null then null else jsonb_build_object(
   'subject',p_subject,'topic',p_topic,
   'note',(select note_text from public.student_topic_notes where student_id=v_student and lower(subject)=lower(p_subject) and lower(topic)=lower(p_topic)),
   'resources',coalesce((select jsonb_agg(jsonb_build_object('id',id,'title',title,'description',description,'source_type',source_type,'publication_id',publication_id,'chapter_id',chapter_id)) from public.learning_resources where status='published' and lower(coalesce(subject,''))=lower(p_subject) and (lower(coalesce(strand,''))=lower(p_topic) or title ilike '%'||p_topic||'%') limit 12),'[]'::jsonb),
   'questions',coalesce((select jsonb_agg(jsonb_build_object('id',id,'difficulty',difficulty::text,'question',question,'options',options,'hint',hint,'explanation',explanation)) from public.exam_question_bank where status='published' and lower(subject::text)=lower(p_subject) and lower(topic)=lower(p_topic) limit 20),'[]'::jsonb),
   'mistakes',coalesce((select jsonb_agg(jsonb_build_object('id',id,'question_id',exam_question_id,'source_block_id',source_block_id,'review_url',case when source_block_id is not null and source_publication_id is not null and source_chapter_id is not null then '/read/textbook/'||source_publication_id::text||'?chapter='||source_chapter_id::text||'&block='||source_block_id::text else null end,'prompt',prompt_snapshot,'repeat_count',repeat_count,'status',status)) from public.student_mistake_notebook where student_id=v_student and lower(subject)=lower(p_subject) and lower(topic)=lower(p_topic)),'[]'::jsonb),
   'stats',jsonb_build_object('attempts',(select count(*) from public.student_practice_attempts where student_id=v_student and lower(subject)=lower(p_subject) and lower(topic)=lower(p_topic)),'accuracy',(select round(100.0*avg(case when is_correct then 1 else 0 end),0) from public.student_practice_attempts where student_id=v_student and lower(subject)=lower(p_subject) and lower(topic)=lower(p_topic)))
  ) end
 );
end;$function$;

revoke execute on function public.student_get_revision_workspace(text,text) from public,anon;
grant execute on function public.student_get_revision_workspace(text,text) to authenticated;
