-- Recovered verbatim from the production Supabase migration ledger for L0 replay parity.
create table if not exists public.hq_workforce_evidence_policies(id uuid primary key default gen_random_uuid(),policy_key text not null unique,min_events integer not null default 3 check(min_events>0),relevance_days integer not null default 90 check(relevance_days>0),allow_high_severity_override boolean not null default true,active boolean not null default true,created_at timestamptz not null default now()); insert into public.hq_workforce_evidence_policies(policy_key,min_events,relevance_days,allow_high_severity_override) values('default',3,90,true) on conflict(policy_key) do nothing;
create table if not exists public.hq_workforce_evidence_qualifications(id uuid primary key default gen_random_uuid(),qualification_key text not null unique,skill_key text not null,lane_key text,qualification_signature text not null,status text not null check(status in ('qualifying','qualified_for_compilation','contradicted','expired')),eligible_count integer not null default 0,contradiction_count integer not null default 0,high_severity_override boolean not null default false,evidence_event_ids uuid[] not null default '{}'::uuid[],evaluated_at timestamptz not null default now());
create table if not exists public.hq_workforce_replay_results(id uuid primary key default gen_random_uuid(),promotion_id uuid not null references public.hq_workforce_skill_promotions(id),historical_run_id uuid references public.hq_workforce_runs(id),passed boolean not null,execution_match boolean,outcome_match boolean,evidence jsonb not null default '{}'::jsonb,created_at timestamptz not null default now(),unique(promotion_id,historical_run_id));
create table if not exists public.hq_workforce_probation_policies(id uuid primary key default gen_random_uuid(),policy_key text not null unique,min_verified_runs integer not null default 3,allowed_failures integer not null default 0,min_confidence numeric not null default .70 check(min_confidence between 0 and 1),require_all_outcomes_verified boolean not null default true,active boolean not null default true); insert into public.hq_workforce_probation_policies(policy_key,min_verified_runs,allowed_failures,min_confidence,require_all_outcomes_verified) values('default',3,0,.70,true) on conflict(policy_key) do nothing;
create table if not exists public.hq_workforce_monitoring_alerts(id uuid primary key default gen_random_uuid(),alert_key text not null unique,alert_type text not null,severity text not null check(severity in ('info','warning','high','critical')),subject_type text not null,subject_key text not null,details jsonb not null default '{}'::jsonb,status text not null default 'open' check(status in ('open','acknowledged','resolved')),created_at timestamptz not null default now(),resolved_at timestamptz);
alter table public.hq_workforce_evidence_policies enable row level security; alter table public.hq_workforce_evidence_qualifications enable row level security; alter table public.hq_workforce_replay_results enable row level security; alter table public.hq_workforce_probation_policies enable row level security; alter table public.hq_workforce_monitoring_alerts enable row level security;
create or replace function public.hq_workforce_qualification_state(p_count integer,p_has_contradiction boolean,p_stale boolean,p_high_severity boolean,p_min integer default 3) returns text language sql immutable as $$ select case when p_has_contradiction then 'contradicted' when p_stale then 'expired' when p_high_severity then 'qualified_for_compilation' when p_count>=p_min then 'qualified_for_compilation' else 'qualifying' end $$;
create or replace function public.hq_workforce_probation_state(p_verified_runs integer,p_failures integer,p_lowest_confidence numeric,p_unverified_outcomes integer,p_min_runs integer default 3,p_allowed_failures integer default 0,p_min_confidence numeric default .70) returns text language sql immutable as $$ select case when p_failures>p_allowed_failures or coalesce(p_lowest_confidence,0)<p_min_confidence or p_unverified_outcomes>0 then 'rollback' when p_verified_runs>=p_min_runs then 'promote' else 'probation' end $$;
create or replace function public.hq_workforce_record_positive_outcome(p_evidence_id uuid,p_status text,p_evidence jsonb) returns text language plpgsql security invoker set search_path=public as $$ begin if p_status not in ('verified','failed','unverified') then raise exception 'Invalid outcome status'; end if; update public.hq_workforce_positive_evidence set outcome_status=p_status,outcome_evidence=coalesce(p_evidence,'{}') where id=p_evidence_id; if not found then raise exception 'Evidence not found'; end if; if p_status<>'verified' then insert into public.hq_workforce_monitoring_alerts(alert_key,alert_type,severity,subject_type,subject_key,details) values('positive-outcome-'||p_evidence_id,'APPROVED_ACTION_OUTCOME_FAILURE','high','positive_evidence',p_evidence_id::text,jsonb_build_object('outcome_status',p_status,'evidence',p_evidence)) on conflict(alert_key) do nothing; end if; return p_status; end $$;
create or replace function public.hq_workforce_monitor_health() returns integer language plpgsql security invoker set search_path=public as $$ declare n integer:=0; begin insert into public.hq_workforce_monitoring_alerts(alert_key,alert_type,severity,subject_type,subject_key,details) select 'stuck-run-'||r.id,'STUCK_WORKER_RUN','high','run',r.id::text,jsonb_build_object('status',r.status,'created_at',r.created_at) from public.hq_workforce_runs r where r.status in ('queued','running') and r.created_at<now()-interval '1 hour' on conflict(alert_key) do nothing; get diagnostics n=row_count; return n; end $$;
revoke all on table public.hq_workforce_evidence_policies,public.hq_workforce_evidence_qualifications,public.hq_workforce_replay_results,public.hq_workforce_probation_policies,public.hq_workforce_monitoring_alerts from anon,authenticated; revoke all on function public.hq_workforce_qualification_state(integer,boolean,boolean,boolean,integer) from public,anon,authenticated; revoke all on function public.hq_workforce_probation_state(integer,integer,numeric,integer,integer,integer,numeric) from public,anon,authenticated; revoke all on function public.hq_workforce_record_positive_outcome(uuid,text,jsonb) from public,anon,authenticated; revoke all on function public.hq_workforce_monitor_health() from public,anon,authenticated;
