-- Recovered verbatim from the production Supabase migration ledger for L0 replay parity.
create table if not exists public.hq_workforce_lanes(lane_key text primary key,title text not null,department_key text not null,mission text not null,owner_worker_id uuid references public.hq_workforce_workers(id),event_types text[] not null default '{}',schedule_keys text[] not null default '{}',active boolean not null default true,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.hq_workforce_skills(id uuid primary key default gen_random_uuid(),skill_key text not null,version integer not null check(version>0),title text not null,lane_key text references public.hq_workforce_lanes(lane_key),execution_method text not null default 'none' check(execution_method in ('none','local_algorithm','local_model','human','external_model')),required_context text[] not null default '{}',required_competencies text[] not null default '{}',procedure jsonb not null default '[]'::jsonb,verification jsonb not null default '[]'::jsonb,recovery jsonb not null default '[]'::jsonb,status text not null default 'draft' check(status in ('draft','probation','certified','retired')),created_at timestamptz not null default now(),unique(skill_key,version));
create table if not exists public.hq_workforce_contract_clauses(id uuid primary key default gen_random_uuid(),clause_key text not null,version integer not null check(version>0),clause_type text not null,scope_type text not null,scope_key text,rule jsonb not null,status text not null default 'draft' check(status in ('draft','active','retired')),effective_at timestamptz not null default now(),created_at timestamptz not null default now(),unique(clause_key,version));
create table if not exists public.hq_workforce_gap_signals(id uuid primary key default gen_random_uuid(),gap_key text not null unique,source_type text not null,source_ref text not null,lane_key text,signal_type text not null,metrics_snapshot jsonb not null default '{}'::jsonb,severity text not null check(severity in ('low','medium','high','critical')),status text not null default 'candidate' check(status in ('candidate','evaluating','accepted','rejected','resolved')),detected_at timestamptz not null default now());
create table if not exists public.hq_workforce_gap_evaluations(id uuid primary key default gen_random_uuid(),gap_id uuid not null references public.hq_workforce_gap_signals(id),diagnosis text not null,decision text not null,evidence_snapshot_id uuid references public.hq_context_decision_snapshots(id),reason text not null,execution_method text not null default 'local_algorithm',created_at timestamptz not null default now());
create table if not exists public.hq_workforce_learning_candidates(id uuid primary key default gen_random_uuid(),scope_type text not null,scope_key text,learning_type text not null,statement text not null,evidence_refs text[] not null default '{}',confidence numeric not null check(confidence between 0 and 1),confidence_source text not null,status text not null default 'candidate' check(status in ('candidate','approved','rejected','promoted','superseded')),approved_by uuid references auth.users(id),approved_at timestamptz,created_at timestamptz not null default now());
create table if not exists public.hq_workforce_outcome_verifications(id uuid primary key default gen_random_uuid(),assignment_id uuid references public.hq_workforce_assignments(id),expected_outcome jsonb not null,actual_outcome jsonb not null,execution_certified boolean not null default false,outcome_verified boolean not null default false,verification_method text not null,evidence jsonb not null default '{}'::jsonb,verified_at timestamptz not null default now());
create table if not exists public.hq_workforce_decisions(id uuid primary key default gen_random_uuid(),decision_key text not null unique,worker_id uuid references public.hq_workforce_workers(id),lane_key text references public.hq_workforce_lanes(lane_key),job_key text references public.hq_workforce_jobs(key),proposed_action text not null,reason text not null,evidence_snapshot_id uuid references public.hq_context_decision_snapshots(id),risk text not null check(risk in ('low','normal','high','critical')),status text not null default 'pending' check(status in ('pending','approved','revision_requested','rejected','skipped','executed','verified')),revision text,decided_by uuid references auth.users(id),decided_at timestamptz,created_at timestamptz not null default now());
create index if not exists hq_gap_status_idx on public.hq_workforce_gap_signals(status,severity,detected_at desc); create index if not exists hq_decision_pending_idx on public.hq_workforce_decisions(status,risk,created_at); create index if not exists hq_skill_lane_idx on public.hq_workforce_skills(lane_key,status,skill_key,version desc);
alter table public.hq_workforce_lanes enable row level security; alter table public.hq_workforce_skills enable row level security; alter table public.hq_workforce_contract_clauses enable row level security; alter table public.hq_workforce_gap_signals enable row level security; alter table public.hq_workforce_gap_evaluations enable row level security; alter table public.hq_workforce_learning_candidates enable row level security; alter table public.hq_workforce_outcome_verifications enable row level security; alter table public.hq_workforce_decisions enable row level security;
