-- HQ authority contract v1: typed policy registry, safe rollout metadata, acknowledgements and observed-state verification.
begin;
create table if not exists public.hq_policy_registry(id uuid primary key default gen_random_uuid(),policy_key text not null unique,domain text not null,owner_department text not null references public.hq_departments(key),value_type text not null check(value_type in('boolean','integer','number','string','json')),default_value jsonb not null,allowed_products text[] not null default '{}',risk_level text not null default 'normal' check(risk_level in('low','normal','high','critical')),failure_mode text not null default 'last_known_good' check(failure_mode in('fail_open','fail_closed','last_known_good')),min_number numeric,max_number numeric,allowed_values jsonb,description text not null,active boolean not null default true,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.hq_product_policy_state(id uuid primary key default gen_random_uuid(),product_key text not null,policy_key text not null references public.hq_policy_registry(policy_key),source_decision_id uuid references public.hq_decisions(id),source_version integer,desired_value jsonb not null,received_value jsonb,observed_value jsonb,state text not null default 'published' check(state in('published','received','evaluated','enforced','observed','verified','drift','failed')),received_at timestamptz,evaluated_at timestamptz,enforced_at timestamptz,observed_at timestamptz,verified_at timestamptz,last_error text,updated_at timestamptz not null default now(),unique(product_key,policy_key));
create table if not exists public.hq_policy_evaluations(id bigint generated always as identity primary key,product_key text not null,policy_key text not null,source_decision_id uuid,source_version integer,value jsonb,reason text not null,fallback_used boolean not null default false,context jsonb not null default '{}',created_at timestamptz not null default now());
create index if not exists hq_policy_eval_recent on public.hq_policy_evaluations(product_key,policy_key,created_at desc);
alter table public.hq_policy_registry enable row level security;alter table public.hq_product_policy_state enable row level security;alter table public.hq_policy_evaluations enable row level security;
revoke all on public.hq_policy_registry,public.hq_product_policy_state,public.hq_policy_evaluations from anon,authenticated;
do $$ begin create policy hq_policy_registry_owner on public.hq_policy_registry for all to authenticated using((select public.is_platform_owner())) with check((select public.is_platform_owner())); exception when duplicate_object then null;end $$;
do $$ begin create policy hq_policy_state_owner on public.hq_product_policy_state for all to authenticated using((select public.is_platform_owner())) with check((select public.is_platform_owner())); exception when duplicate_object then null;end $$;
do $$ begin create policy hq_policy_eval_owner on public.hq_policy_evaluations for select to authenticated using((select public.is_platform_owner())); exception when duplicate_object then null;end $$;

create or replace function public.hq_validate_policy_value(p_policy_key text,p_product_key text,p_value jsonb) returns void language plpgsql security definer set search_path=public as $$ declare r public.hq_policy_registry%rowtype;n numeric;t text;begin select * into r from hq_policy_registry where policy_key=p_policy_key and active;if not found then raise exception 'Unregistered HQ policy: %',p_policy_key;end if;if not(p_product_key=any(r.allowed_products) or 'global'=any(r.allowed_products)) then raise exception 'Policy % is not allowed for product %',p_policy_key,p_product_key;end if;t:=jsonb_typeof(p_value);if r.value_type='boolean' and t<>'boolean' then raise exception 'Policy % requires boolean',p_policy_key;elsif r.value_type='string' and t<>'string' then raise exception 'Policy % requires string',p_policy_key;elsif r.value_type in('integer','number') then if t<>'number' then raise exception 'Policy % requires number',p_policy_key;end if;n:=(p_value#>>'{}')::numeric;if r.value_type='integer' and trunc(n)<>n then raise exception 'Policy % requires integer',p_policy_key;end if;if r.min_number is not null and n<r.min_number then raise exception 'Policy % below minimum',p_policy_key;end if;if r.max_number is not null and n>r.max_number then raise exception 'Policy % above maximum',p_policy_key;end if;end if;if r.allowed_values is not null and not(r.allowed_values @> jsonb_build_array(p_value)) then raise exception 'Policy % value is not allowed',p_policy_key;end if;end $$;
revoke all on function public.hq_validate_policy_value(text,text,jsonb) from public,anon,authenticated;

create or replace function public.hq_publish_policy_state(p_decision_id uuid) returns void language plpgsql security definer set search_path=public as $$ declare d hq_decisions%rowtype;p text;v int;begin select * into d from hq_decisions where id=p_decision_id;if d.rule_key is null then return;end if;select coalesce(max(version),1) into v from hq_decision_versions where decision_id=d.id;foreach p in array d.affected_products loop perform public.hq_validate_policy_value(d.rule_key,p,d.rule_value);insert into hq_product_policy_state(product_key,policy_key,source_decision_id,source_version,desired_value,state,updated_at) values(p,d.rule_key,d.id,v,d.rule_value,'published',now()) on conflict(product_key,policy_key) do update set source_decision_id=excluded.source_decision_id,source_version=excluded.source_version,desired_value=excluded.desired_value,received_value=null,observed_value=null,state='published',received_at=null,evaluated_at=null,enforced_at=null,observed_at=null,verified_at=null,last_error=null,updated_at=now();end loop;end $$;
revoke all on function public.hq_publish_policy_state(uuid) from public,anon,authenticated;

create or replace function public.hq_ack_policy(p_product_key text,p_policy_key text,p_value jsonb,p_stage text default 'enforced') returns void language plpgsql security definer set search_path=public as $$ begin if p_stage not in('received','evaluated','enforced') then raise exception 'Invalid acknowledgement stage';end if;perform public.hq_validate_policy_value(p_policy_key,p_product_key,p_value);update hq_product_policy_state set received_value=p_value,state=p_stage,received_at=coalesce(received_at,now()),evaluated_at=case when p_stage in('evaluated','enforced') then now() else evaluated_at end,enforced_at=case when p_stage='enforced' then now() else enforced_at end,updated_at=now() where product_key=p_product_key and policy_key=p_policy_key;if not found then raise exception 'No published desired policy state';end if;end $$;
revoke all on function public.hq_ack_policy(text,text,jsonb,text) from public,anon;grant execute on function public.hq_ack_policy(text,text,jsonb,text) to authenticated;

create or replace function public.hq_observe_policy(p_product_key text,p_policy_key text,p_observed jsonb) returns jsonb language plpgsql security definer set search_path=public as $$ declare s hq_product_policy_state%rowtype;ok boolean;begin perform public.hq_assert_owner();select * into s from hq_product_policy_state where product_key=p_product_key and policy_key=p_policy_key for update;if not found then raise exception 'No policy state';end if;ok:=p_observed is not distinct from s.desired_value;update hq_product_policy_state set observed_value=p_observed,observed_at=now(),verified_at=case when ok then now() else verified_at end,state=case when ok then 'verified' else 'drift' end,last_error=case when ok then null else 'Observed behavior does not match desired policy' end,updated_at=now() where id=s.id;if not ok then insert into hq_incidents(incident_type,severity,status,title,summary,evidence,route) select 'policy_drift',case r.risk_level when 'critical' then 'critical' else 'warning' end,'open','Product policy drift detected',p_product_key||' does not match '||p_policy_key,jsonb_build_object('product',p_product_key,'policy',p_policy_key,'desired',s.desired_value,'observed',p_observed),'/hq/decisions' from hq_policy_registry r where r.policy_key=p_policy_key and not exists(select 1 from hq_incidents i where i.status<>'resolved' and i.incident_type='policy_drift' and i.evidence->>'product'=p_product_key and i.evidence->>'policy'=p_policy_key);end if;return jsonb_build_object('verified',ok,'desired',s.desired_value,'observed',p_observed);end $$;
revoke all on function public.hq_observe_policy(text,text,jsonb) from public,anon;grant execute on function public.hq_observe_policy(text,text,jsonb) to authenticated;

create or replace function public.hq_evaluate_policy(p_product_key text,p_policy_key text,p_context jsonb default '{}'::jsonb) returns jsonb language plpgsql security definer set search_path=public as $$ declare r hq_policy_registry%rowtype;c hq_product_configs%rowtype;v jsonb;reason text;fallback boolean:=false;begin select * into r from hq_policy_registry where policy_key=p_policy_key and active;if not found then raise exception 'Unknown policy %',p_policy_key;end if;select * into c from hq_product_configs where product_key=p_product_key and config_key=p_policy_key and active and effective_at<=now() order by updated_at desc limit 1;if found then v:=c.config_value;reason:='company_policy';else v:=r.default_value;reason:='registry_default';fallback:=true;end if;perform public.hq_validate_policy_value(p_policy_key,p_product_key,v);insert into hq_policy_evaluations(product_key,policy_key,source_decision_id,source_version,value,reason,fallback_used,context) values(p_product_key,p_policy_key,c.source_decision_id,c.source_version,v,reason,fallback,coalesce(p_context,'{}'));update hq_product_policy_state set received_value=v,state=case when state='published' then 'evaluated' else state end,received_at=coalesce(received_at,now()),evaluated_at=now(),updated_at=now() where product_key=p_product_key and policy_key=p_policy_key;return jsonb_build_object('value',v,'policyKey',p_policy_key,'productKey',p_product_key,'decisionId',c.source_decision_id,'version',c.source_version,'reason',reason,'fallbackUsed',fallback,'failureMode',r.failure_mode);end $$;
revoke all on function public.hq_evaluate_policy(text,text,jsonb) from public,anon;grant execute on function public.hq_evaluate_policy(text,text,jsonb) to authenticated;

insert into hq_policy_registry(policy_key,domain,owner_department,value_type,default_value,allowed_products,risk_level,failure_mode,min_number,max_number,description) values
('platform.maintenance_mode','operations','engineering','boolean','false'::jsonb,array['global'],'critical','last_known_good',null,null,'Global maintenance state'),
('twin.enabled','product','product','boolean','true'::jsonb,array['twin'],'high','last_known_good',null,null,'Whether Twin service is available'),
('student.free_daily_twin_sessions','commercial','finance','integer','5'::jsonb,array['student','twin'],'normal','last_known_good',0,100,'Daily Twin session entitlement for free learners'),
('vibelabs.enabled','product','product','boolean','true'::jsonb,array['vibelabs'],'high','last_known_good',null,null,'Whether VibeLabs is available'),
('publication.release_enabled','publishing','content','boolean','true'::jsonb,array['vibebooks','vibelearn'],'high','fail_closed',null,null,'Whether publication release operations are permitted')
on conflict(policy_key) do update set domain=excluded.domain,owner_department=excluded.owner_department,value_type=excluded.value_type,default_value=excluded.default_value,allowed_products=excluded.allowed_products,risk_level=excluded.risk_level,failure_mode=excluded.failure_mode,min_number=excluded.min_number,max_number=excluded.max_number,description=excluded.description,active=true,updated_at=now();
commit;