create or replace function public.connect_teacher_to_school(p_school_id uuid)
returns uuid language plpgsql security definer set search_path=public as $$ declare v_uid uuid:=auth.uid(); begin if v_uid is null then raise exception 'Authentication required'; end if; if not exists(select 1 from public.profiles where id=v_uid) then raise exception 'Profile not found'; end if; if not exists(select 1 from public.schools where id=p_school_id and deleted_at is null and status in ('pending','active')) then raise exception 'School not available'; end if; insert into public.school_members(school_id,profile_id,role) values(p_school_id,v_uid,'teacher') on conflict(school_id,profile_id) do nothing; update public.profiles set school_id=p_school_id where id=v_uid; insert into public.teacher_profiles(profile_id,school_id) values(v_uid,p_school_id) on conflict(profile_id) do update set school_id=excluded.school_id; return p_school_id; end; $$;
revoke all on function public.connect_teacher_to_school(uuid) from public,anon; grant execute on function public.connect_teacher_to_school(uuid) to authenticated;

create or replace function public.connect_teacher_to_directory_school(p_directory_id uuid)
returns uuid language plpgsql security definer set search_path=public as $$ declare v_uid uuid:=auth.uid(); d record; v_school uuid; begin if v_uid is null then raise exception 'Authentication required'; end if; select * into d from public.schools_directory where id=p_directory_id and lower(coalesce(status,'active')) <> 'closed'; if not found then raise exception 'Directory school not found'; end if; select id into v_school from public.schools where deleted_at is null and ((d.knec_code is not null and knec_code=d.knec_code) or (d.nemis_code is not null and nemis_code=d.nemis_code) or (lower(name)=lower(d.name) and coalesce(lower(county),'')=coalesce(lower(d.county),''))) order by case when knec_code=d.knec_code and d.knec_code is not null then 0 when nemis_code=d.nemis_code and d.nemis_code is not null then 1 else 2 end limit 1; if v_school is null then insert into public.schools(name,timezone,country_code,status,created_by,requires_dual_approval,county,sub_county,gps_lat,gps_lng,knec_code,nemis_code,school_type,directory_source,directory_source_ref,last_verified_at) values(d.name,'Africa/Nairobi','KE','active',v_uid,true,d.county,d.sub_county,d.latitude,d.longitude,d.knec_code,d.nemis_code,d.type,'schools_directory',d.id::text,now()) returning id into v_school; end if; insert into public.school_members(school_id,profile_id,role) values(v_school,v_uid,'teacher') on conflict(school_id,profile_id) do nothing; update public.profiles set school_id=v_school where id=v_uid; insert into public.teacher_profiles(profile_id,school_id) values(v_uid,v_school) on conflict(profile_id) do update set school_id=excluded.school_id; return v_school; end; $$;
revoke all on function public.connect_teacher_to_directory_school(uuid) from public,anon; grant execute on function public.connect_teacher_to_directory_school(uuid) to authenticated;

create table if not exists public.school_discovery_requests(id uuid primary key default gen_random_uuid(),requested_by uuid not null references public.profiles(id) on delete cascade,name text not null,county text,sub_county text,level text,notes text,status text not null default 'pending' check(status in ('pending','matched','rejected')),created_at timestamptz not null default now(),resolved_at timestamptz);
create index if not exists school_discovery_requests_status_idx on public.school_discovery_requests(status,created_at desc);
alter table public.school_discovery_requests enable row level security;
drop policy if exists school_discovery_requests_insert_own on public.school_discovery_requests;
create policy school_discovery_requests_insert_own on public.school_discovery_requests for insert to authenticated with check(requested_by=auth.uid());
drop policy if exists school_discovery_requests_select_own on public.school_discovery_requests;
create policy school_discovery_requests_select_own on public.school_discovery_requests for select to authenticated using(requested_by=auth.uid());