begin;
create or replace function public.hq_global_search(p_query text,p_limit integer default 40)
returns table(result_type text,result_id text,title text,subtitle text,status text,route text,updated_at timestamptz,rank integer)
language plpgsql security definer set search_path=public as $$
declare v_query text:=left(btrim(coalesce(p_query,'')),160); v_pattern text; v_limit integer:=greatest(1,least(coalesce(p_limit,40),80));
begin
 perform public.hq_assert_owner();
 if char_length(v_query)<2 then return; end if;
 v_pattern:='%'||replace(replace(replace(v_query,'\','\\'),'%','\%'),'_','\_')||'%';
 return query with candidates as (
 select 'work_item'::text,w.id::text,w.title,concat_ws(' · ',nullif(w.department_key,''),nullif(w.summary,'')),w.status,('/hq/workroom/'||w.id::text)::text,w.updated_at,case when lower(w.title)=lower(v_query) then 0 when w.title ilike v_pattern escape '\' then 10 else 20 end from public.hq_work_items w where w.title ilike v_pattern escape '\' or coalesce(w.summary,'') ilike v_pattern escape '\' or coalesce(w.department_key,'') ilike v_pattern escape '\'
 union all select 'decision',d.id::text,d.title,concat_ws(' · ',nullif(d.code,''),nullif(d.category,''),nullif(d.reason,'')),d.status,'/hq/decisions',d.updated_at,case when lower(d.title)=lower(v_query) then 0 when d.title ilike v_pattern escape '\' then 10 else 25 end from public.hq_decisions d where d.title ilike v_pattern escape '\' or coalesce(d.code,'') ilike v_pattern escape '\' or coalesce(d.reason,'') ilike v_pattern escape '\'
 union all select 'artifact',a.id::text,a.title,concat_ws(' · ',nullif(a.artifact_type,''),nullif(a.department_key,''),nullif(a.purpose,'')),coalesce(a.approval_state,a.lifecycle_state),case when a.work_item_id is not null then '/hq/workroom/'||a.work_item_id::text else '/hq/content' end,a.updated_at,case when lower(a.title)=lower(v_query) then 0 when a.title ilike v_pattern escape '\' then 10 else 25 end from public.hq_artifacts a where a.title ilike v_pattern escape '\' or coalesce(a.purpose,'') ilike v_pattern escape '\'
 union all select 'notification',n.id::text,n.title,concat_ws(' · ',nullif(n.category,''),nullif(n.body,'')),n.status,coalesce(n.route,'/hq/notifications'),n.last_seen_at,case when lower(n.title)=lower(v_query) then 0 when n.title ilike v_pattern escape '\' then 10 else 25 end from public.hq_notifications n where n.title ilike v_pattern escape '\' or coalesce(n.body,'') ilike v_pattern escape '\'
 union all select 'incident',i.id::text,i.title,concat_ws(' · ',nullif(i.severity,''),nullif(i.summary,'')),i.status,coalesce(i.route,'/hq/security'),coalesce(i.resolved_at,i.detected_at),case when lower(i.title)=lower(v_query) then 0 when i.title ilike v_pattern escape '\' then 10 else 25 end from public.hq_incidents i where i.title ilike v_pattern escape '\' or coalesce(i.summary,'') ilike v_pattern escape '\'
 union all select 'worker',w.id::text,w.title,concat_ws(' · ',nullif(w.worker_key,''),nullif(w.department_key,''),nullif(w.mission,'')),w.status,'/hq/workforce',w.updated_at,case when lower(w.title)=lower(v_query) then 0 when w.title ilike v_pattern escape '\' then 10 else 25 end from public.hq_workforce_workers w where w.title ilike v_pattern escape '\' or coalesce(w.worker_key,'') ilike v_pattern escape '\' or coalesce(w.mission,'') ilike v_pattern escape '\'
 union all select 'workforce_job',j.key,j.title,concat_ws(' · ',nullif(j.key,''),nullif(j.purpose,'')),case when j.active then 'active' else 'inactive' end,'/hq/workforce',j.created_at,case when lower(j.title)=lower(v_query) then 0 when j.title ilike v_pattern escape '\' then 10 else 25 end from public.hq_workforce_jobs j where j.title ilike v_pattern escape '\' or coalesce(j.purpose,'') ilike v_pattern escape '\'
 union all select 'school',s.id::text,s.name::text,concat_ws(' · ',nullif(s.county::text,''),nullif(s.sub_county::text,''),nullif(s.knec_code::text,'')),s.status::text,'/hq/schools/'||s.id::text,s.updated_at,case when lower(s.name::text)=lower(v_query) then 0 when s.name::text ilike v_pattern escape '\' then 10 else 25 end from public.schools s where s.deleted_at is null and (s.name::text ilike v_pattern escape '\' or coalesce(s.knec_code::text,'') ilike v_pattern escape '\' or coalesce(s.nemis_code::text,'') ilike v_pattern escape '\' or coalesce(s.county::text,'') ilike v_pattern escape '\')
 union all select 'publication',p.id::text,p.title,concat_ws(' · ',nullif(p.cbc_grade,''),nullif(p.cbc_subject,''),nullif(p.subtitle,'')),p.status,'/hq/content',p.updated_at,case when lower(p.title)=lower(v_query) then 0 when p.title ilike v_pattern escape '\' then 10 else 25 end from public.vibe_publications p where p.title ilike v_pattern escape '\' or coalesce(p.subtitle,'') ilike v_pattern escape '\' or coalesce(p.cbc_subject,'') ilike v_pattern escape '\'
 union all select 'curriculum_outcome',o.id::text,coalesce(nullif(o.outcome_code,''),'Learning outcome'),o.outcome_text,o.status,'/hq/curriculum-authority',o.updated_at,case when lower(coalesce(o.outcome_code,''))=lower(v_query) then 0 when coalesce(o.outcome_code,'') ilike v_pattern escape '\' then 10 else 25 end from public.curriculum_learning_outcomes o where o.outcome_text ilike v_pattern escape '\' or coalesce(o.outcome_code,'') ilike v_pattern escape '\'
 ) select c.result_type,c.result_id,c.title,left(coalesce(c.subtitle,''),360),c.status,c.route,c.updated_at,c.rank from candidates c order by c.rank,c.updated_at desc nulls last,c.title limit v_limit;
end;$$;
revoke all on function public.hq_global_search(text,integer) from public,anon;
grant execute on function public.hq_global_search(text,integer) to authenticated;
comment on function public.hq_global_search(text,integer) is 'Owner-gated global search across HQ operational, workforce, school, publication and curriculum records.';
commit;
