-- VibeSchool Pathways truth + acquisition foundation. Additive only.
create table if not exists public.pathway_sources(id uuid primary key default gen_random_uuid(),authority_name text not null,source_name text not null,source_url text not null,source_reference text,source_kind text not null check(source_kind in('official_portal','official_document','professional_body','institution_verified','editorial_guidance')),observed_at timestamptz not null,effective_from date,effective_to date,content_checksum text,status text not null default 'active' check(status in('active','superseded','withdrawn')),is_public boolean not null default true,metadata jsonb not null default '{}'::jsonb,created_at timestamptz not null default now());
alter table public.pathway_sources enable row level security; revoke all on public.pathway_sources from public,anon,authenticated; grant select on public.pathway_sources to anon,authenticated; grant all on public.pathway_sources to service_role; create policy pathway_sources_public_read on public.pathway_sources for select to anon,authenticated using(is_public and status='active');
-- authorization-test: public.pathway_sources public readers see active public provenance; writes service-only.
create table if not exists public.pathway_source_observations(id uuid primary key default gen_random_uuid(),source_id uuid not null references public.pathway_sources(id),external_key text not null,entity_kind text not null check(entity_kind in('pathway','track','subject_combination','career','school_offering')),observed_payload jsonb not null,observed_at timestamptz not null,content_checksum text not null,resolution_state text not null default 'unresolved' check(resolution_state in('unresolved','resolved','disputed','retired')),resolved_entity_id uuid,created_at timestamptz not null default now(),unique(source_id,external_key,content_checksum));
alter table public.pathway_source_observations enable row level security; revoke all on public.pathway_source_observations from public,anon,authenticated; grant all on public.pathway_source_observations to service_role;
-- access: service-only public.pathway_source_observations
-- authorization-test: public.pathway_source_observations client access denied.
create table if not exists public.pathways(id uuid primary key default gen_random_uuid(),slug text not null unique,official_code text,name text not null,summary text not null default '',source_id uuid not null references public.pathway_sources(id),verification_state text not null default 'unverified' check(verification_state in('verified','unverified','disputed','stale','retired')),status text not null default 'draft' check(status in('draft','published','retired')),effective_from date,effective_to date,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
alter table public.pathways enable row level security; revoke all on public.pathways from public,anon,authenticated; grant select on public.pathways to anon,authenticated; grant all on public.pathways to service_role; create policy pathways_verified_public_read on public.pathways for select to anon,authenticated using(status='published' and verification_state='verified');
-- authorization-test: public.pathways exposes only verified published truth.
create table if not exists public.pathway_tracks(id uuid primary key default gen_random_uuid(),pathway_id uuid not null references public.pathways(id) on delete cascade,slug text not null,official_code text,name text not null,summary text not null default '',source_id uuid not null references public.pathway_sources(id),verification_state text not null default 'unverified' check(verification_state in('verified','unverified','disputed','stale','retired')),status text not null default 'draft' check(status in('draft','published','retired')),created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(pathway_id,slug));
alter table public.pathway_tracks enable row level security; revoke all on public.pathway_tracks from public,anon,authenticated; grant select on public.pathway_tracks to anon,authenticated; grant all on public.pathway_tracks to service_role; create policy pathway_tracks_verified_public_read on public.pathway_tracks for select to anon,authenticated using(status='published' and verification_state='verified' and exists(select 1 from public.pathways p where p.id=pathway_id and p.status='published' and p.verification_state='verified'));
-- authorization-test: public.pathway_tracks exposes only verified published tracks.
create table if not exists public.pathway_subject_combinations(id uuid primary key default gen_random_uuid(),pathway_id uuid not null references public.pathways(id),track_id uuid references public.pathway_tracks(id),slug text not null,official_code text,display_name text not null,source_id uuid not null references public.pathway_sources(id),verification_state text not null default 'unverified' check(verification_state in('verified','unverified','disputed','stale','retired')),status text not null default 'draft' check(status in('draft','published','retired')),created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(pathway_id,slug));
alter table public.pathway_subject_combinations enable row level security; revoke all on public.pathway_subject_combinations from public,anon,authenticated; grant select on public.pathway_subject_combinations to anon,authenticated; grant all on public.pathway_subject_combinations to service_role; create policy pathway_combinations_verified_public_read on public.pathway_subject_combinations for select to anon,authenticated using(status='published' and verification_state='verified');
-- authorization-test: public.pathway_subject_combinations exposes only verified published combinations.
create table if not exists public.pathway_combination_subject_claims(combination_id uuid not null references public.pathway_subject_combinations(id) on delete cascade,subject_name text not null,subject_code text,subject_order smallint not null check(subject_order>0),source_id uuid not null references public.pathway_sources(id),resolved_subject_id uuid references public.subjects(id),resolution_state text not null default 'unresolved' check(resolution_state in('unresolved','resolved','ambiguous','disputed')),created_at timestamptz not null default now(),primary key(combination_id,subject_order));
alter table public.pathway_combination_subject_claims enable row level security; revoke all on public.pathway_combination_subject_claims from public,anon,authenticated; grant select on public.pathway_combination_subject_claims to anon,authenticated; grant all on public.pathway_combination_subject_claims to service_role; create policy pathway_subject_claims_verified_public_read on public.pathway_combination_subject_claims for select to anon,authenticated using(exists(select 1 from public.pathway_subject_combinations c where c.id=combination_id and c.status='published' and c.verification_state='verified'));
-- authorization-test: public.pathway_combination_subject_claims remain evidence and resolve into canonical public.subjects.
create table if not exists public.pathway_careers(id uuid primary key default gen_random_uuid(),slug text not null unique,name text not null,summary text not null default '',source_id uuid not null references public.pathway_sources(id),verification_state text not null default 'unverified' check(verification_state in('verified','unverified','disputed','stale','retired')),status text not null default 'draft' check(status in('draft','published','retired')),created_at timestamptz not null default now(),updated_at timestamptz not null default now());
alter table public.pathway_careers enable row level security; revoke all on public.pathway_careers from public,anon,authenticated; grant select on public.pathway_careers to anon,authenticated; grant all on public.pathway_careers to service_role; create policy pathway_careers_verified_public_read on public.pathway_careers for select to anon,authenticated using(status='published' and verification_state='verified');
-- authorization-test: public.pathway_careers expose only verified published truth.
create table if not exists public.pathway_career_links(career_id uuid not null references public.pathway_careers(id) on delete cascade,pathway_id uuid not null references public.pathways(id) on delete cascade,track_id uuid references public.pathway_tracks(id),relationship_type text not null check(relationship_type in('official','professional_requirement','guidance')),explanation text not null default '',source_id uuid not null references public.pathway_sources(id),verification_state text not null default 'unverified' check(verification_state in('verified','unverified','disputed','stale','retired')),created_at timestamptz not null default now(),primary key(career_id,pathway_id,relationship_type));
alter table public.pathway_career_links enable row level security; revoke all on public.pathway_career_links from public,anon,authenticated; grant select on public.pathway_career_links to anon,authenticated; grant all on public.pathway_career_links to service_role; create policy pathway_career_links_verified_public_read on public.pathway_career_links for select to anon,authenticated using(verification_state='verified');
-- authorization-test: public.pathway_career_links expose verified relationships only.
create table if not exists public.pathway_school_offerings(id uuid primary key default gen_random_uuid(),school_id uuid not null references public.schools(id),pathway_id uuid not null references public.pathways(id),track_id uuid references public.pathway_tracks(id),combination_id uuid references public.pathway_subject_combinations(id),source_id uuid not null references public.pathway_sources(id),verification_state text not null default 'unverified' check(verification_state in('verified','unverified','disputed','stale','retired')),observed_at timestamptz not null,verified_at timestamptz,effective_from date,effective_to date,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
alter table public.pathway_school_offerings enable row level security; revoke all on public.pathway_school_offerings from public,anon,authenticated; grant select on public.pathway_school_offerings to anon,authenticated; grant all on public.pathway_school_offerings to service_role; create policy pathway_school_offerings_verified_public_read on public.pathway_school_offerings for select to anon,authenticated using(verification_state='verified' and verified_at is not null and(effective_to is null or effective_to>=current_date)); create unique index if not exists pathway_school_offering_identity_idx on public.pathway_school_offerings(school_id,pathway_id,coalesce(combination_id,'00000000-0000-0000-0000-000000000000'::uuid),source_id);
-- authorization-test: public.pathway_school_offerings reference canonical schools and expose current verified claims only.
create table if not exists public.pathway_profile_decisions(id uuid primary key default gen_random_uuid(),profile_id uuid not null references public.profiles(id) on delete cascade,pathway_id uuid not null references public.pathways(id),decision_type text not null check(decision_type in('quick_check_saved','adopted','changed','reviewed')),evidence_snapshot jsonb not null default '{}'::jsonb,rule_version text not null,idempotency_key text not null,created_at timestamptz not null default now(),unique(profile_id,idempotency_key));
alter table public.pathway_profile_decisions enable row level security; revoke all on public.pathway_profile_decisions from public,anon,authenticated; grant select on public.pathway_profile_decisions to authenticated; grant all on public.pathway_profile_decisions to service_role; create policy pathway_profile_decisions_own_read on public.pathway_profile_decisions for select to authenticated using(profile_id=(select auth.uid()));
-- authorization-test: public.pathway_profile_decisions learner decision history is self-readable and RPC/service writable only.
create table if not exists public.pathway_profile_passports(profile_id uuid primary key references public.profiles(id) on delete cascade,pathway_id uuid not null references public.pathways(id),source_decision_id uuid not null references public.pathway_profile_decisions(id),rule_version text not null,evidence_snapshot jsonb not null default '{}'::jsonb,adopted_at timestamptz not null default now(),reviewed_at timestamptz,updated_at timestamptz not null default now());
alter table public.pathway_profile_passports enable row level security; revoke all on public.pathway_profile_passports from public,anon,authenticated; grant select on public.pathway_profile_passports to authenticated; grant all on public.pathway_profile_passports to service_role; create policy pathway_profile_passports_own_read on public.pathway_profile_passports for select to authenticated using(profile_id=(select auth.uid()));
-- authorization-test: public.pathway_profile_passports learner passport is self-readable and RPC/service writable only.
create index if not exists pathway_observations_source_idx on public.pathway_source_observations(source_id,entity_kind,resolution_state); create index if not exists pathway_offerings_school_idx on public.pathway_school_offerings(school_id,verification_state); create index if not exists pathway_decisions_profile_idx on public.pathway_profile_decisions(profile_id,created_at desc);
create or replace function public.pathways_save_my_quick_check(p_pathway_slug text,p_answers jsonb,p_scores jsonb,p_rule_version text,p_idempotency_key text) returns jsonb language plpgsql security definer set search_path=public,pg_temp as $$ declare caller uuid:=auth.uid();caller_role text;chosen public.pathways%rowtype;decision_id uuid; begin if caller is null then raise exception 'not_authenticated';end if; select role into caller_role from public.profiles where id=caller; if caller_role not in ('student','global_user') then raise exception 'learner_role_required';end if; if p_idempotency_key is null or length(p_idempotency_key)<8 or length(p_idempotency_key)>128 then raise exception 'invalid_idempotency_key';end if; if jsonb_typeof(coalesce(p_answers,'{}'::jsonb))<>'object' or jsonb_typeof(coalesce(p_scores,'{}'::jsonb))<>'object' then raise exception 'invalid_payload_shape';end if; select * into chosen from public.pathways where slug=lower(trim(p_pathway_slug)) and status='published' and verification_state='verified'; if not found then raise exception 'verified_pathway_not_found';end if; insert into public.pathway_profile_decisions(profile_id,pathway_id,decision_type,evidence_snapshot,rule_version,idempotency_key) values(caller,chosen.id,'quick_check_saved',jsonb_build_object('evidence_class','learner_supplied_quick_check','answers',coalesce(p_answers,'{}'::jsonb),'scores',coalesce(p_scores,'{}'::jsonb),'disclaimer','VibeSchool guidance; not an official placement decision.'),p_rule_version,p_idempotency_key) on conflict(profile_id,idempotency_key) do update set idempotency_key=excluded.idempotency_key returning id into decision_id; insert into public.pathway_profile_passports(profile_id,pathway_id,source_decision_id,rule_version,evidence_snapshot,adopted_at,updated_at) values(caller,chosen.id,decision_id,p_rule_version,jsonb_build_object('scores',coalesce(p_scores,'{}'::jsonb)),now(),now()) on conflict(profile_id) do update set pathway_id=excluded.pathway_id,source_decision_id=excluded.source_decision_id,rule_version=excluded.rule_version,evidence_snapshot=excluded.evidence_snapshot,adopted_at=excluded.adopted_at,updated_at=now(); return jsonb_build_object('ok',true,'pathway_slug',chosen.slug,'pathway_name',chosen.name,'decision_id',decision_id); end $$;
revoke all on function public.pathways_save_my_quick_check(text,jsonb,jsonb,text,text) from public, anon; grant execute on function public.pathways_save_my_quick_check(text,jsonb,jsonb,text,text) to authenticated;
create or replace function public.pathways_get_my_passport() returns jsonb language sql stable security invoker set search_path=public as $$ select coalesce((select jsonb_build_object('pathway_slug',p.slug,'pathway_name',p.name,'summary',p.summary,'rule_version',pp.rule_version,'evidence_snapshot',pp.evidence_snapshot,'adopted_at',pp.adopted_at,'reviewed_at',pp.reviewed_at,'updated_at',pp.updated_at) from public.pathway_profile_passports pp join public.pathways p on p.id=pp.pathway_id where pp.profile_id=auth.uid()),'null'::jsonb) $$; revoke all on function public.pathways_get_my_passport() from public,anon; grant execute on function public.pathways_get_my_passport() to authenticated;
create or replace function public.pathways_search_public_schools(p_query text default null,p_county text default null,p_pathway_slug text default null,p_combination_slug text default null,p_limit integer default 30) returns table(school_id uuid,school_name text,county text,sub_county text,school_category text,ownership_type text,gender_type text,accommodation_type text,cluster text,knec_code text,pathway_slug text,pathway_name text,combination_slug text,combination_name text,verified_at timestamptz) language sql stable security definer set search_path=public,pg_temp as $$ select s.id,s.name::text,s.county::text,s.sub_county::text,s.school_category::text,s.ownership_type,s.gender_type,s.accommodation_type,s.cluster,s.knec_code::text,p.slug,p.name,c.slug,c.display_name,o.verified_at from public.schools s left join public.pathway_school_offerings o on o.school_id=s.id and o.verification_state='verified' and o.verified_at is not null and(o.effective_to is null or o.effective_to>=current_date) left join public.pathways p on p.id=o.pathway_id and p.status='published' and p.verification_state='verified' left join public.pathway_subject_combinations c on c.id=o.combination_id and c.status='published' and c.verification_state='verified' where s.deleted_at is null and s.status='active' and(p_query is null or trim(p_query)='' or lower(s.name) like '%'||lower(trim(p_query))||'%') and(p_county is null or trim(p_county)='' or lower(coalesce(s.county,''))=lower(trim(p_county))) and(p_pathway_slug is null or p.slug=lower(trim(p_pathway_slug))) and(p_combination_slug is null or c.slug=lower(trim(p_combination_slug))) order by s.name limit greatest(1,least(coalesce(p_limit,30),50)) $$; revoke all on function public.pathways_search_public_schools(text,text,text,text,integer) from public; grant execute on function public.pathways_search_public_schools(text,text,text,text,integer) to anon,authenticated;
insert into public.pathway_sources(id,authority_name,source_name,source_url,source_reference,source_kind,observed_at,status,is_public,metadata) values('bdb736d5-fc4f-4f42-aec8-7cda7f4b0091','Kenya Ministry of Education','Grade 10 School & Pathway Selection System','https://selection.education.go.ke/about','Grade 10 School & Pathway Selection System — About','official_portal','2026-08-16T00:00:00Z','active',true,jsonb_build_object('jurisdiction','Kenya','scope','Grade 9 to Senior School transition')) on conflict(id) do nothing;
insert into public.pathways(id,slug,name,summary,source_id,verification_state,status) values('34476b83-1aad-4f94-a958-c2996311079e','stem','STEM','Science, technology, engineering and mathematics.','bdb736d5-fc4f-4f42-aec8-7cda7f4b0091','verified','published'),('d9a19fd7-4f15-45de-9131-f0de50c376a0','social-sciences','Social Sciences','Social sciences pathway.','bdb736d5-fc4f-4f42-aec8-7cda7f4b0091','verified','published'),('74d3d667-e0a1-4b48-8904-31203208d139','arts-and-sports-science','Arts & Sports Science','Arts and sports pathway.','bdb736d5-fc4f-4f42-aec8-7cda7f4b0091','verified','published') on conflict(id) do nothing;