-- Curriculum Intelligence engine hardening: atomic claims, retries/dead-letter,
-- evidence-derived health signals, and post-edit effectiveness measurement.

alter table public.curriculum_editorial_actions add column if not exists attempt_count integer not null default 0;
alter table public.curriculum_editorial_actions add column if not exists max_attempts integer not null default 3;
alter table public.curriculum_editorial_actions add column if not exists last_error text;
alter table public.curriculum_editorial_actions add column if not exists locked_at timestamptz;
alter table public.curriculum_editorial_actions add column if not exists locked_by uuid;
alter table public.curriculum_editorial_actions add column if not exists next_attempt_at timestamptz;
alter table public.curriculum_editorial_actions add column if not exists completed_at timestamptz;
alter table public.curriculum_editorial_actions add column if not exists output jsonb not null default '{}'::jsonb;
alter table public.curriculum_editorial_actions drop constraint if exists curriculum_editorial_actions_status_check;
alter table public.curriculum_editorial_actions add constraint curriculum_editorial_actions_status_check check (status in ('queued','in_progress','failed','dead_letter','proposal_created','approved','rejected','completed'));
create index if not exists idx_curriculum_editorial_actions_claim on public.curriculum_editorial_actions(status,next_attempt_at,priority desc,created_at) where status in ('queued','failed');

create table if not exists public.curriculum_editorial_effectiveness (
 id uuid primary key default gen_random_uuid(), proposal_id uuid not null references public.curriculum_intelligence_proposals(id) on delete cascade,
 publication_id uuid references public.vibe_publications(id) on delete cascade, chapter_id uuid references public.vibe_chapters(id) on delete cascade,
 outcome_id uuid references public.curriculum_learning_outcomes(id) on delete set null,
 baseline jsonb not null default '{}'::jsonb, followup jsonb not null default '{}'::jsonb,
 baseline_started_at timestamptz, applied_at timestamptz, evaluation_due_at timestamptz, evaluated_at timestamptz,
 verdict text not null default 'pending' check (verdict in ('pending','improved','neutral','worse','insufficient_evidence')),
 effect_score numeric, sample_size integer not null default 0, notes text, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(proposal_id,outcome_id)
);
alter table public.curriculum_editorial_effectiveness enable row level security;
drop policy if exists "hq owners manage curriculum editorial effectiveness" on public.curriculum_editorial_effectiveness;
create policy "hq owners manage curriculum editorial effectiveness" on public.curriculum_editorial_effectiveness for all to authenticated using (public.is_platform_owner()) with check (public.is_platform_owner());
revoke all on public.curriculum_editorial_effectiveness from anon; grant select,insert,update,delete on public.curriculum_editorial_effectiveness to authenticated;

create or replace function public.hq_claim_next_editorial_action(p_action_id uuid default null) returns public.curriculum_editorial_actions language plpgsql security definer set search_path='public','pg_temp' as $$
declare a public.curriculum_editorial_actions%rowtype; begin
 if not public.is_platform_owner() then raise exception 'HQ platform owner required'; end if;
 select * into a from public.curriculum_editorial_actions where (p_action_id is null or id=p_action_id) and status in ('queued','failed') and attempt_count<max_attempts and (next_attempt_at is null or next_attempt_at<=now()) and (locked_at is null or locked_at<now()-interval '15 minutes') order by priority desc,created_at asc for update skip locked limit 1;
 if not found then return null; end if;
 update public.curriculum_editorial_actions set status='in_progress',attempt_count=attempt_count+1,locked_at=now(),locked_by=auth.uid(),last_error=null,updated_at=now() where id=a.id returning * into a; return a; end $$;
revoke all on function public.hq_claim_next_editorial_action(uuid) from public,anon; grant execute on function public.hq_claim_next_editorial_action(uuid) to authenticated;

create or replace function public.hq_fail_editorial_action(p_action_id uuid,p_error text) returns public.curriculum_editorial_actions language plpgsql security definer set search_path='public','pg_temp' as $$
declare a public.curriculum_editorial_actions%rowtype; begin if not public.is_platform_owner() then raise exception 'HQ platform owner required'; end if;
 update public.curriculum_editorial_actions set status=case when attempt_count>=max_attempts then 'dead_letter' else 'failed' end,last_error=left(coalesce(p_error,'unknown error'),2000),locked_at=null,locked_by=null,next_attempt_at=case when attempt_count>=max_attempts then null else now()+make_interval(mins=>least(60,greatest(1,attempt_count*5))) end,updated_at=now() where id=p_action_id returning * into a; return a; end $$;
revoke all on function public.hq_fail_editorial_action(uuid,text) from public,anon; grant execute on function public.hq_fail_editorial_action(uuid,text) to authenticated;

create or replace function public.hq_refresh_content_health_signals(p_publication_id uuid default null) returns jsonb language plpgsql security definer set search_path='public','pg_temp' as $$
declare v_mastery int:=0;v_assessment int:=0;v_confusion int:=0;begin if not public.is_platform_owner() then raise exception 'HQ platform owner required'; end if;
 insert into public.curriculum_content_health_signals(publication_id,chapter_id,outcome_id,signal_type,severity,score,evidence_count,evidence,status,last_detected_at,updated_at)
 select cb.publication_id,cb.chapter_id,som.outcome_id,'low_mastery',case when avg(som.mastery_score)<0.35 then 'high' else 'medium' end,greatest(0,least(1,1-avg(som.mastery_score)))::numeric,count(*)::int,jsonb_build_object('average_mastery',round(avg(som.mastery_score)::numeric,3),'learners',count(distinct som.student_id),'source','student_outcome_mastery'),'open',now(),now() from public.student_outcome_mastery som join public.content_block_outcome_links l on l.outcome_id=som.outcome_id join public.content_blocks cb on cb.id=l.content_block_id where som.evidence_count>0 and (p_publication_id is null or cb.publication_id=p_publication_id) group by cb.publication_id,cb.chapter_id,som.outcome_id having count(distinct som.student_id)>=5 and avg(som.mastery_score)<0.55
 on conflict(publication_id,chapter_id,outcome_id,signal_type) where outcome_id is not null and status in ('open','watching','proposal_created') do update set severity=excluded.severity,score=excluded.score,evidence_count=excluded.evidence_count,evidence=excluded.evidence,last_detected_at=now(),updated_at=now(); get diagnostics v_mastery=row_count;
 insert into public.curriculum_content_health_signals(publication_id,chapter_id,outcome_id,signal_type,severity,score,evidence_count,evidence,status,last_detected_at,updated_at)
 select cb.publication_id,cb.chapter_id,l.outcome_id,'assessment_failure',case when avg(case when (e.metadata->>'correct')::boolean then 1 else 0 end)<0.3 then 'high' else 'medium' end,1-avg(case when (e.metadata->>'correct')::boolean then 1 else 0 end),count(*)::int,jsonb_build_object('accuracy',round(avg(case when (e.metadata->>'correct')::boolean then 1 else 0 end)::numeric,3),'learners',count(distinct e.student_id),'source','student_learning_events.practice_answered'),'open',now(),now() from public.student_learning_events e join public.content_block_outcome_links l on l.outcome_id=(e.metadata->>'outcome_id')::uuid join public.content_blocks cb on cb.id=l.content_block_id where e.event_type='practice_answered' and e.metadata?'correct' and e.metadata?'outcome_id' and (p_publication_id is null or cb.publication_id=p_publication_id) and e.occurred_at>=now()-interval '30 days' group by cb.publication_id,cb.chapter_id,l.outcome_id having count(distinct e.student_id)>=5 and avg(case when (e.metadata->>'correct')::boolean then 1 else 0 end)<0.5
 on conflict(publication_id,chapter_id,outcome_id,signal_type) where outcome_id is not null and status in ('open','watching','proposal_created') do update set severity=excluded.severity,score=excluded.score,evidence_count=excluded.evidence_count,evidence=excluded.evidence,last_detected_at=now(),updated_at=now(); get diagnostics v_assessment=row_count;
 insert into public.curriculum_content_health_signals(publication_id,chapter_id,signal_type,severity,score,evidence_count,evidence,status,last_detected_at,updated_at)
 select vc.publication_id,vc.id,'learner_confusion','medium',least(1,count(*)::numeric/10),count(*)::int,jsonb_build_object('learners',count(distinct e.student_id),'source','student_learning_events.learning_representation_not_helpful'),'open',now(),now() from public.student_learning_events e join public.vibe_chapters vc on vc.id=(e.metadata->>'chapter_id')::uuid where e.event_type='learning_representation_not_helpful' and nullif(e.metadata->>'chapter_id','') is not null and (p_publication_id is null or vc.publication_id=p_publication_id) and e.occurred_at>=now()-interval '30 days' group by vc.publication_id,vc.id having count(distinct e.student_id)>=5 and not exists(select 1 from public.curriculum_content_health_signals s where s.chapter_id=vc.id and s.signal_type='learner_confusion' and s.status in ('open','watching','proposal_created')); get diagnostics v_confusion=row_count;
 return jsonb_build_object('low_mastery',v_mastery,'assessment_failure',v_assessment,'learner_confusion',v_confusion,'refreshed_at',now()); end $$;
revoke all on function public.hq_refresh_content_health_signals(uuid) from public,anon; grant execute on function public.hq_refresh_content_health_signals(uuid) to authenticated;

create or replace function public.curriculum_editorial_capture_baseline() returns trigger language plpgsql security definer set search_path='public','pg_temp' as $$ begin
 if new.status='approved' and old.status is distinct from new.status and new.chapter_id is not null then insert into public.curriculum_editorial_effectiveness(proposal_id,publication_id,chapter_id,outcome_id,baseline,baseline_started_at,evaluation_due_at) select new.id,new.publication_id,new.chapter_id,l.outcome_id,jsonb_build_object('avg_mastery',round(avg(som.mastery_score)::numeric,4),'learners',count(distinct som.student_id),'evidence_rows',count(som.*)),now(),now()+interval '14 days' from public.content_blocks cb join public.content_block_outcome_links l on l.content_block_id=cb.id left join public.student_outcome_mastery som on som.outcome_id=l.outcome_id where cb.chapter_id=new.chapter_id group by l.outcome_id on conflict(proposal_id,outcome_id) do nothing; end if;
 if new.status='applied' and old.status is distinct from new.status then update public.curriculum_editorial_effectiveness set applied_at=coalesce(new.applied_at,now()),evaluation_due_at=coalesce(evaluation_due_at,now()+interval '14 days'),updated_at=now() where proposal_id=new.id; end if; return new; end $$;
drop trigger if exists trg_curriculum_editorial_capture_baseline on public.curriculum_intelligence_proposals; create trigger trg_curriculum_editorial_capture_baseline after update of status on public.curriculum_intelligence_proposals for each row execute function public.curriculum_editorial_capture_baseline(); revoke all on function public.curriculum_editorial_capture_baseline() from public,anon,authenticated;

create or replace function public.hq_evaluate_editorial_effectiveness(p_proposal_id uuid) returns jsonb language plpgsql security definer set search_path='public','pg_temp' as $$
declare r record;improved int:=0;worse int:=0;neutral int:=0;insufficient int:=0;begin if not public.is_platform_owner() then raise exception 'HQ platform owner required'; end if;
 for r in select * from public.curriculum_editorial_effectiveness where proposal_id=p_proposal_id for update loop update public.curriculum_editorial_effectiveness e set followup=s.x,sample_size=(s.x->>'learners')::int,effect_score=case when (e.baseline->>'avg_mastery') is null or (s.x->>'avg_mastery') is null then null else (s.x->>'avg_mastery')::numeric-(e.baseline->>'avg_mastery')::numeric end,verdict=case when coalesce((s.x->>'learners')::int,0)<5 then 'insufficient_evidence' when (e.baseline->>'avg_mastery') is null then 'insufficient_evidence' when (s.x->>'avg_mastery')::numeric-(e.baseline->>'avg_mastery')::numeric>=0.05 then 'improved' when (s.x->>'avg_mastery')::numeric-(e.baseline->>'avg_mastery')::numeric<=-0.05 then 'worse' else 'neutral' end,evaluated_at=now(),updated_at=now() from (select jsonb_build_object('avg_mastery',round(avg(som.mastery_score)::numeric,4),'learners',count(distinct som.student_id),'evidence_rows',count(*)) x from public.student_outcome_mastery som where som.outcome_id=r.outcome_id) s where e.id=r.id; end loop;
 select count(*) filter(where verdict='improved'),count(*) filter(where verdict='worse'),count(*) filter(where verdict='neutral'),count(*) filter(where verdict='insufficient_evidence') into improved,worse,neutral,insufficient from public.curriculum_editorial_effectiveness where proposal_id=p_proposal_id; return jsonb_build_object('improved',improved,'worse',worse,'neutral',neutral,'insufficient_evidence',insufficient); end $$;
revoke all on function public.hq_evaluate_editorial_effectiveness(uuid) from public,anon; grant execute on function public.hq_evaluate_editorial_effectiveness(uuid) to authenticated;

create or replace function public.hq_effectiveness_decision(p_proposal_id uuid) returns jsonb language plpgsql security definer set search_path='public','pg_temp' as $$ declare x jsonb;w int;i int;ins int;decision text;begin if not public.is_platform_owner() then raise exception 'HQ platform owner required'; end if; x:=public.hq_evaluate_editorial_effectiveness(p_proposal_id);w:=(x->>'worse')::int;i:=(x->>'improved')::int;ins:=(x->>'insufficient_evidence')::int; decision:=case when w>0 and w>=i then 'review_or_revert' when i>0 and w=0 then 'retain' when ins>0 and i=0 and w=0 then 'collect_more_evidence' else 'editorial_review' end; return x||jsonb_build_object('decision',decision); end $$;
revoke all on function public.hq_effectiveness_decision(uuid) from public,anon; grant execute on function public.hq_effectiveness_decision(uuid) to authenticated;