-- Restore repository <-> production parity for the KCSE Candidate OS.
--
-- A blank migration replay retained the original profile-keyed Candidate OS,
-- while production had a later dual account/canonical learner definition that
-- was not represented in repository migration history. Normalize both
-- environments to the known production predecessor before the immediately
-- following canonical student identity migration removes the dual-domain
-- academic predicates.

create or replace function public.student_get_kcse_candidate_os()
returns jsonb
language plpgsql
security definer
set search_path = 'public','pg_temp'
as $$
declare
 v_user uuid:=auth.uid(); v_student uuid; v_class uuid; v_class_name text; v_home public.student_home_state%rowtype; v_ready public.student_exam_readiness_state%rowtype;
 v_subjects jsonb:='[]'::jsonb; v_projection jsonb:='{}'::jsonb; v_coverage jsonb:='[]'::jsonb; v_caps jsonb:='{}'::jsonb; v_errors jsonb:='[]'::jsonb; v_conf jsonb:='[]'::jsonb; v_consistency jsonb:='{}'::jsonb; v_days integer; v_mode text; v_avg numeric; v_attempts integer;
begin
 if v_user is null then raise exception 'Authentication required'; end if;
 select s.id,coalesce(sc.class_id,s.class_id),c.name into v_student,v_class,v_class_name from public.students s left join public.student_classes sc on sc.student_id=s.id and sc.is_current left join public.classes c on c.id=coalesce(sc.class_id,s.class_id) where s.profile_id=v_user and s.deleted_at is null order by sc.joined_at desc nulls last limit 1;
 if v_student is null then raise exception 'Student profile not found'; end if;
 insert into public.student_home_state(student_id) values(v_student) on conflict(student_id) do nothing;
 insert into public.student_exam_readiness_state(student_id) values(v_user) on conflict(student_id) do nothing;
 select * into v_home from public.student_home_state where student_id=v_student;
 select * into v_ready from public.student_exam_readiness_state where student_id=v_user;
 v_days:=case when v_ready.exam_date is null then null else greatest(v_ready.exam_date-current_date,0) end;
 v_mode:=case when not v_ready.kcse_candidate_opt_in then 'setup' when v_days is null then 'setup' when v_days<=7 then 'final_week' when v_days<=21 then 'final_sprint' when v_days<=60 then 'exam_revision' else 'steady_revision' end;
 select round(avg(a.percentage)::numeric,1),count(*) into v_avg,v_attempts from public.assessment_attempts a where a.student_id=v_student and a.percentage is not null and a.status in ('submitted','auto_marked','teacher_reviewed');
 select coalesce(jsonb_agg(jsonb_build_object('subject_id',x.subject_id,'subject',x.subject_name,'assessment_attempts',x.attempts,'average_percentage',x.avg_pct,'target_percentage',case when v_home.subject_targets ? x.subject_id::text then (v_home.subject_targets->>x.subject_id::text)::numeric else null end) order by x.subject_name),'[]'::jsonb) into v_subjects from (select ad.subject_id,coalesce(su.name,'General') subject_name,count(*) attempts,round(avg(a.percentage)::numeric,1) avg_pct from public.assessment_attempts a join public.assessment_definitions ad on ad.id=a.assessment_id left join public.subjects su on su.id=ad.subject_id where a.student_id=v_student and a.percentage is not null and a.status in ('submitted','auto_marked','teacher_reviewed') group by ad.subject_id,su.name) x;
 v_projection:=jsonb_build_object('evidence_attempts',coalesce(v_attempts,0),'average_percentage',v_avg,'readiness_band',case when v_avg is null then 'insufficient_evidence' when v_avg>=80 then 'very_strong' when v_avg>=70 then 'strong' when v_avg>=60 then 'developing_strong' when v_avg>=50 then 'developing' else 'needs_recovery' end,'target_grade',v_home.kcse_target_grade,'trend_disclaimer','This is a Vibeschool evidence projection, not an official KNEC grade prediction.');
 select coalesce(jsonb_agg(jsonb_build_object('subject',z.subject,'syllabus_topics',z.syllabus_topics,'verified_outcomes',z.verified_outcomes,'published_form4_questions',z.questions,'evidence_state',case when z.syllabus_topics=0 then 'syllabus_unavailable' when z.questions=0 then 'practice_unavailable' else 'available' end) order by z.subject),'[]'::jsonb) into v_coverage from (
   with subject_names as (
     select distinct su.name subject from public.teacher_classes tc join public.subjects su on su.id=tc.subject_id where tc.class_id=v_class
     union select distinct subject::text from public.exam_question_bank where form::text='Form 4'
     union select distinct subject from public.curriculum where lower(grade) in ('form 4','form4')
   ) select sn.subject,
     (select count(distinct c.topic) from public.curriculum c where lower(c.grade) in ('form 4','form4') and lower(c.subject)=lower(sn.subject)) syllabus_topics,
     (select count(*) from public.curriculum_learning_outcomes o join public.curriculum c on c.id=o.curriculum_id where lower(c.grade) in ('form 4','form4') and lower(c.subject)=lower(sn.subject) and o.status='verified') verified_outcomes,
     (select count(*) from public.exam_question_bank q where q.status='published' and q.form::text='Form 4' and lower(q.subject::text)=lower(sn.subject)) questions
   from subject_names sn
 ) z;
 select coalesce(jsonb_agg(jsonb_build_object('error_type',e.error_type,'count',e.error_count) order by e.error_count desc),'[]'::jsonb) into v_errors from (select coalesce(ec.error_type,'unclassified') error_type,count(*) error_count from public.student_mistake_notebook m left join public.student_kcse_error_classifications ec on ec.mistake_id=m.id and ec.student_id=v_user where m.student_id=v_user and m.status<>'resolved' group by coalesce(ec.error_type,'unclassified')) e;
 select coalesce(jsonb_agg(jsonb_build_object('subject',c.subject,'confidence',c.confidence,'performance_percentage',p.avg_pct,'alignment',case when p.avg_pct is null then 'no_performance_evidence' when c.confidence>=4 and p.avg_pct<60 then 'overconfident_risk' when c.confidence<=2 and p.avg_pct>=70 then 'underconfident' else 'aligned' end) order by c.subject),'[]'::jsonb) into v_conf from public.student_kcse_subject_confidence c left join (select lower(subject) subject,round(100.0*avg(case when is_correct then 1 else 0 end),0) avg_pct from public.student_practice_attempts where student_id=v_user group by lower(subject)) p on p.subject=lower(c.subject) where c.student_id=v_user;
 v_consistency:=jsonb_build_object('learning_days_7d',(select count(distinct occurred_at::date) from public.student_learning_events where student_id in (v_user,v_student) and occurred_at>=now()-interval '7 days'),'learning_actions_7d',(select count(*) from public.student_learning_events where student_id in (v_user,v_student) and occurred_at>=now()-interval '7 days'),'due_retests',(select count(*) from public.student_kcse_retest_schedule where student_id=v_user and mastery_state<>'mastered' and due_date<=current_date),'average_response_seconds',(select round(avg(response_ms)/1000.0,1) from public.student_practice_attempts where student_id=v_user and response_ms is not null and attempted_at>=now()-interval '30 days'));
 v_caps:=jsonb_build_object('candidate_onboarding',true,'verified_form4_syllabus',(select count(*)>0 from public.curriculum where lower(grade) in ('form 4','form4')),'verified_form4_outcomes',(select count(*)>0 from public.curriculum_learning_outcomes o join public.curriculum c on c.id=o.curriculum_id where lower(c.grade) in ('form 4','form4') and o.status='verified'),'verified_form4_question_bank',(select count(*)>0 from public.exam_question_bank where status='published' and form::text='Form 4'),'verified_past_paper_provenance',(select count(*)>0 from public.exam_question_bank where status='published' and form::text='Form 4' and provenance_status='official_verified'),'verified_paper_blueprints',(select count(*)>0 from public.kcse_paper_blueprints where verification_status='verified'),'topic_dependencies',(select count(*)>0 from public.kcse_topic_dependencies where verification_status='verified'),'rubric_marking',(select count(*)>0 from public.assessment_rubrics where status<>'draft'),'long_response_items',(select count(*)>0 from public.assessment_items where question_type not in ('mcq','multiple_choice') and status<>'draft'),'practical_items',(select count(*)>0 from public.assessment_items where lower(question_type) like '%practical%' and status<>'draft'),'oral_items',(select count(*)>0 from public.assessment_items where lower(question_type) in ('oral','listening','speaking','audio') and status<>'draft'),'grounded_textbook_practice',(select count(*)>0 from public.content_blocks where status='published' and is_assessable and block_type='question'),'spaced_retesting',true,'resumable_mock_engine',true,'mistake_taxonomy',true,'search',true,'peer_ranking_disabled',true);
 return jsonb_build_object('student_id',v_student,'class_id',v_class,'class_name',v_class_name,'eligible',v_ready.kcse_candidate_opt_in,'onboarding',jsonb_build_object('kcse_candidate_opt_in',v_ready.kcse_candidate_opt_in,'target_grade',v_home.kcse_target_grade,'exam_date',v_ready.exam_date,'daily_revision_minutes',v_ready.daily_revision_minutes,'confidence_check',v_ready.confidence_check,'subject_targets',v_home.subject_targets,'complete',v_ready.kcse_candidate_opt_in and v_home.kcse_target_grade is not null and v_ready.exam_date is not null),'countdown',jsonb_build_object('days_remaining',v_days,'mode',v_mode,'message',case when not v_ready.kcse_candidate_opt_in then 'Turn on KCSE Candidate Mode to use exam countdown and candidate planning.' when v_mode='setup' then 'Set your KCSE date and target before relying on a countdown plan.' when v_mode='final_week' then 'Final week: protect sleep, confidence, timing and high-yield recall.' when v_mode='final_sprint' then 'Final sprint: prioritise mistakes, spaced retests and timed papers.' when v_mode='exam_revision' then 'Exam revision: mix weak-topic recovery with timed paper practice.' else 'Steady revision: build complete coverage and durable mastery.' end),'projection',v_projection,'subjects',v_subjects,'coverage',v_coverage,'confidence_vs_performance',v_conf,'open_error_patterns',v_errors,'consistency',v_consistency,'due_retests',coalesce((select jsonb_agg(jsonb_build_object('id',id,'subject',subject,'topic',topic,'due_date',due_date,'interval_days',interval_days,'successful_retests',successful_retests,'mastery_state',mastery_state) order by due_date,subject,topic) from public.student_kcse_retest_schedule where student_id=v_user and mastery_state<>'mastered'),'[]'::jsonb),'recent_mocks',coalesce((select jsonb_agg(jsonb_build_object('id',id,'subject',subject,'paper_code',paper_code,'title',title,'status',status,'percentage',percentage,'started_at',started_at,'action_url','/student/vibelearn/kcse/mock/'||id::text) order by created_at desc) from (select * from public.student_kcse_mock_sessions where student_id=v_user order by created_at desc limit 8)m),'[]'::jsonb),'paper_blueprints',coalesce((select jsonb_agg(jsonb_build_object('id',id,'subject',subject,'paper_code',paper_code,'title',title,'duration_minutes',duration_minutes,'total_marks',total_marks,'source_type',source_type,'source_ref',source_ref) order by subject,paper_code) from public.kcse_paper_blueprints where verification_status='verified'),'[]'::jsonb),'capabilities',v_caps,'guardrails',jsonb_build_object('no_public_ranking',true,'no_official_grade_claim',true,'no_unverified_kcse_content_presented_as_authoritative',true,'tutor_blocked_during_timed_mock',true));
end
$$;

revoke all on function public.student_get_kcse_candidate_os() from public;
revoke all on function public.student_get_kcse_candidate_os() from anon;
grant execute on function public.student_get_kcse_candidate_os() to authenticated;
grant execute on function public.student_get_kcse_candidate_os() to service_role;
