-- HQ company control plane final schema alignment, applied to production 2026-08-09.
-- This migration records the decision authority, digital workforce, scheduled activation and executive work creation.

create table if not exists public.hq_decisions (
  id uuid primary key default gen_random_uuid(), code text not null unique, title text not null,
  category text not null, decision_type text not null,
  status text not null default 'draft' check (status in ('draft','reviewed','approved','locked','active','superseded','rolled_back','cancelled')),
  rule_key text, rule_value jsonb not null default '{}'::jsonb, reason text,
  affected_products text[] not null default '{}', effective_at timestamptz,
  approved_by uuid references auth.users(id), approved_at timestamptz,
  locked_by uuid references auth.users(id), locked_at timestamptz,
  supersedes_id uuid references public.hq_decisions(id), rollback_of_id uuid references public.hq_decisions(id),
  created_by uuid not null references auth.users(id), created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create table if not exists public.hq_decision_versions (id uuid primary key default gen_random_uuid(),decision_id uuid not null references public.hq_decisions(id) on delete cascade,version integer not null,snapshot jsonb not null,changed_by uuid not null references auth.users(id),changed_at timestamptz not null default now(),unique(decision_id,version));
create table if not exists public.hq_product_configs (id uuid primary key default gen_random_uuid(),product_key text not null,config_key text not null,config_value jsonb not null,source_decision_id uuid references public.hq_decisions(id),source_version integer,effective_at timestamptz not null default now(),active boolean not null default true,updated_at timestamptz not null default now(),is_secret boolean not null default false);
create unique index if not exists hq_product_configs_one_active on public.hq_product_configs(product_key,config_key) where active=true;
create table if not exists public.hq_propagation_targets (id uuid primary key default gen_random_uuid(),decision_id uuid not null references public.hq_decisions(id) on delete cascade,product_key text not null,expected_config_key text,expected_value jsonb,status text not null default 'pending' check(status in('pending','applied','drift','failed','not_applicable')),applied_at timestamptz,verified_at timestamptz,error text,unique(decision_id,product_key,expected_config_key));
create table if not exists public.hq_decision_audit (id uuid primary key default gen_random_uuid(),decision_id uuid references public.hq_decisions(id),action text not null,actor_id uuid references auth.users(id),details jsonb not null default '{}'::jsonb,created_at timestamptz not null default now());

alter table public.hq_decisions enable row level security; alter table public.hq_decision_versions enable row level security; alter table public.hq_product_configs enable row level security; alter table public.hq_propagation_targets enable row level security; alter table public.hq_decision_audit enable row level security;
revoke all on public.hq_decisions,public.hq_decision_versions,public.hq_product_configs,public.hq_propagation_targets,public.hq_decision_audit from anon,authenticated;
do $$ begin create policy hq_decisions_owner_select on public.hq_decisions for select to authenticated using ((select public.is_platform_owner())); exception when duplicate_object then null; end $$;
do $$ begin create policy hq_versions_owner_select on public.hq_decision_versions for select to authenticated using ((select public.is_platform_owner())); exception when duplicate_object then null; end $$;
do $$ begin create policy hq_configs_owner_select on public.hq_product_configs for select to authenticated using ((select public.is_platform_owner())); exception when duplicate_object then null; end $$;
do $$ begin create policy hq_targets_owner_select on public.hq_propagation_targets for select to authenticated using ((select public.is_platform_owner())); exception when duplicate_object then null; end $$;
do $$ begin create policy hq_audit_owner_select on public.hq_decision_audit for select to authenticated using ((select public.is_platform_owner())); exception when duplicate_object then null; end $$;

create or replace function public.hq_next_decision_code() returns text language sql security definer set search_path=public as $$ select 'HQ-DEC-'||lpad((coalesce(max(substring(code from '[0-9]+$')::int),0)+1)::text,4,'0') from public.hq_decisions $$;
revoke all on function public.hq_next_decision_code() from public,anon,authenticated;
create or replace function public.hq_activate_due_decisions() returns integer language plpgsql security definer set search_path=public as $$ declare r record;n int:=0;begin for r in select id,effective_at from public.hq_decisions where status='locked' and effective_at is not null and effective_at<=now() for update loop update public.hq_decisions set status='active',updated_at=now() where id=r.id;insert into public.hq_decision_audit(decision_id,action,actor_id,details) values(r.id,'activated',null,jsonb_build_object('effective_at',r.effective_at));n:=n+1;end loop;return n;end $$;
revoke all on function public.hq_activate_due_decisions() from public,anon,authenticated;

create or replace function public.hq_create_decision(p_title text,p_category text,p_decision_type text,p_rule_key text,p_rule_value jsonb,p_reason text,p_affected_products text[],p_effective_at timestamptz default null) returns uuid language plpgsql security definer set search_path=public as $$ declare v_id uuid;v_code text;begin perform public.hq_assert_owner();v_code:=public.hq_next_decision_code();insert into public.hq_decisions(code,title,category,decision_type,rule_key,rule_value,reason,affected_products,effective_at,created_by) values(v_code,p_title,p_category,p_decision_type,p_rule_key,coalesce(p_rule_value,'{}'::jsonb),p_reason,coalesce(p_affected_products,'{}'),p_effective_at,auth.uid()) returning id into v_id;insert into public.hq_decision_versions(decision_id,version,snapshot,changed_by) select v_id,1,to_jsonb(d),auth.uid() from public.hq_decisions d where d.id=v_id;insert into public.hq_decision_audit(decision_id,action,actor_id,details) values(v_id,'created',auth.uid(),jsonb_build_object('code',v_code));return v_id;end $$;
create or replace function public.hq_update_draft_decision(p_id uuid,p_title text,p_category text,p_decision_type text,p_rule_key text,p_rule_value jsonb,p_reason text,p_affected_products text[],p_effective_at timestamptz default null) returns void language plpgsql security definer set search_path=public as $$ declare s text;v int;begin perform public.hq_assert_owner();select status into s from public.hq_decisions where id=p_id for update;if s not in('draft','reviewed') then raise exception 'Locked or approved decisions cannot be edited';end if;update public.hq_decisions set title=p_title,category=p_category,decision_type=p_decision_type,rule_key=p_rule_key,rule_value=coalesce(p_rule_value,'{}'::jsonb),reason=p_reason,affected_products=coalesce(p_affected_products,'{}'),effective_at=p_effective_at,status='draft',updated_at=now() where id=p_id;select coalesce(max(version),0)+1 into v from public.hq_decision_versions where decision_id=p_id;insert into public.hq_decision_versions(decision_id,version,snapshot,changed_by) select p_id,v,to_jsonb(d),auth.uid() from public.hq_decisions d where id=p_id;insert into public.hq_decision_audit(decision_id,action,actor_id,details) values(p_id,'edited',auth.uid(),jsonb_build_object('version',v));end $$;
create or replace function public.hq_mark_decision_reviewed(p_id uuid) returns void language plpgsql security definer set search_path=public as $$ begin perform public.hq_assert_owner();update public.hq_decisions set status='reviewed',updated_at=now() where id=p_id and status='draft';if not found then raise exception 'Only draft decisions can be marked reviewed';end if;insert into public.hq_decision_audit(decision_id,action,actor_id) values(p_id,'reviewed',auth.uid());end $$;
create or replace function public.hq_approve_decision(p_id uuid) returns void language plpgsql security definer set search_path=public as $$ begin perform public.hq_assert_owner();update public.hq_decisions set status='approved',approved_by=auth.uid(),approved_at=now(),updated_at=now() where id=p_id and status in('draft','reviewed');if not found then raise exception 'Decision cannot be approved from current state';end if;insert into public.hq_decision_audit(decision_id,action,actor_id) values(p_id,'approved',auth.uid());end $$;
create or replace function public.hq_cancel_decision(p_id uuid,p_reason text default null) returns void language plpgsql security definer set search_path=public as $$ declare s text;begin perform public.hq_assert_owner();select status into s from public.hq_decisions where id=p_id for update;if s is null then raise exception 'Decision not found';end if;if s not in('draft','reviewed','approved') then raise exception 'Only non-locked decisions can be cancelled';end if;update public.hq_decisions set status='cancelled',updated_at=now() where id=p_id;insert into public.hq_decision_audit(decision_id,action,actor_id,details) values(p_id,'cancelled',auth.uid(),jsonb_build_object('reason',p_reason));end $$;
create or replace function public.hq_create_amendment(p_old_id uuid,p_title text default null,p_rule_value jsonb default null,p_reason text default null,p_effective_at timestamptz default null) returns uuid language plpgsql security definer set search_path=public as $$ declare old public.hq_decisions%rowtype;v_id uuid;v_code text;begin perform public.hq_assert_owner();select * into old from public.hq_decisions where id=p_old_id;if old.status not in('active','locked') then raise exception 'Only active/locked decisions can be amended';end if;v_code:=public.hq_next_decision_code();insert into public.hq_decisions(code,title,category,decision_type,status,rule_key,rule_value,reason,affected_products,effective_at,supersedes_id,created_by) values(v_code,coalesce(p_title,'Amend: '||old.title),old.category,old.decision_type,'draft',old.rule_key,coalesce(p_rule_value,old.rule_value),coalesce(p_reason,'Amendment of '||old.code),old.affected_products,p_effective_at,p_old_id,auth.uid()) returning id into v_id;insert into public.hq_decision_versions(decision_id,version,snapshot,changed_by) select v_id,1,to_jsonb(d),auth.uid() from public.hq_decisions d where d.id=v_id;insert into public.hq_decision_audit(decision_id,action,actor_id,details) values(v_id,'amendment_created',auth.uid(),jsonb_build_object('supersedes',p_old_id));return v_id;end $$;
create or replace function public.hq_lock_decision(p_id uuid) returns void language plpgsql security definer set search_path=public as $$ declare d public.hq_decisions%rowtype;v int;p text;begin perform public.hq_assert_owner();select * into d from public.hq_decisions where id=p_id for update;if d.status<>'approved' then raise exception 'Decision must be approved before locking';end if;update public.hq_decisions set status=case when effective_at is null or effective_at<=now() then 'active' else 'locked' end,locked_by=auth.uid(),locked_at=now(),updated_at=now() where id=p_id returning * into d;select coalesce(max(version),0)+1 into v from public.hq_decision_versions where decision_id=p_id;insert into public.hq_decision_versions(decision_id,version,snapshot,changed_by) values(p_id,v,to_jsonb(d),auth.uid());foreach p in array d.affected_products loop insert into public.hq_propagation_targets(decision_id,product_key,expected_config_key,expected_value,status) values(p_id,p,d.rule_key,d.rule_value,'pending') on conflict(decision_id,product_key,expected_config_key) do update set expected_value=excluded.expected_value,status='pending',error=null;if d.rule_key is not null then update public.hq_product_configs set active=false,updated_at=now() where product_key=p and config_key=d.rule_key and active=true;insert into public.hq_product_configs(product_key,config_key,config_value,source_decision_id,source_version,effective_at,active,is_secret) values(p,d.rule_key,d.rule_value,p_id,v,coalesce(d.effective_at,now()),true,false);update public.hq_propagation_targets set status='applied',applied_at=now(),verified_at=now() where decision_id=p_id and product_key=p and expected_config_key=d.rule_key;else update public.hq_propagation_targets set status='not_applicable',verified_at=now() where decision_id=p_id and product_key=p;end if;end loop;if d.supersedes_id is not null then update public.hq_decisions set status='superseded',updated_at=now() where id=d.supersedes_id and status in('active','locked');insert into public.hq_decision_audit(decision_id,action,actor_id,details) values(d.supersedes_id,'superseded',auth.uid(),jsonb_build_object('replacement',p_id));end if;insert into public.hq_decision_audit(decision_id,action,actor_id,details) values(p_id,'locked',auth.uid(),jsonb_build_object('version',v));insert into public.hq_notifications(category,severity,title,body,route,status,metadata) values('decision','success','Decision locked',d.code||' · '||d.title,'/hq/decisions','unread',jsonb_build_object('decision_id',p_id,'products',d.affected_products));end $$;
create or replace function public.hq_get_product_config(p_product_key text,p_config_key text) returns jsonb language plpgsql security definer set search_path=public as $$ declare v jsonb;begin perform public.hq_activate_due_decisions();select config_value into v from public.hq_product_configs where product_key=p_product_key and config_key=p_config_key and active=true and effective_at<=now() and is_secret=false order by updated_at desc limit 1;return v;end $$;
create or replace function public.hq_verify_decision_propagation(p_id uuid) returns jsonb language plpgsql security definer set search_path=public as $$ declare r record;actual jsonb;drift_count int:=0;applied_count int:=0;begin perform public.hq_assert_owner();for r in select * from public.hq_propagation_targets where decision_id=p_id loop if r.expected_config_key is null then continue;end if;select config_value into actual from public.hq_product_configs where product_key=r.product_key and config_key=r.expected_config_key and active=true and effective_at<=now() order by updated_at desc limit 1;if actual is not distinct from r.expected_value then update public.hq_propagation_targets set status='applied',verified_at=now(),error=null where id=r.id;applied_count:=applied_count+1;else update public.hq_propagation_targets set status='drift',verified_at=now(),error='Configured value does not match locked decision' where id=r.id;drift_count:=drift_count+1;end if;end loop;if drift_count>0 then insert into public.hq_incidents(incident_type,severity,status,title,summary,evidence,route) values('config_drift','warning','open','HQ decision drift detected','One or more products do not match a locked HQ decision.',jsonb_build_object('decision_id',p_id,'drift_count',drift_count),'/hq/decisions');end if;return jsonb_build_object('applied',applied_count,'drift',drift_count);end $$;
create or replace function public.hq_list_decisions(p_limit int default 100) returns setof public.hq_decisions language plpgsql security definer set search_path=public as $$ begin perform public.hq_assert_owner();perform public.hq_activate_due_decisions();return query select * from public.hq_decisions order by created_at desc limit greatest(1,least(coalesce(p_limit,100),500));end $$;
create or replace function public.hq_get_decision_detail(p_id uuid) returns jsonb language plpgsql security definer set search_path=public as $$ declare v jsonb;begin perform public.hq_assert_owner();select jsonb_build_object('decision',to_jsonb(d),'versions',coalesce((select jsonb_agg(to_jsonb(vv) order by vv.version desc) from public.hq_decision_versions vv where vv.decision_id=d.id),'[]'::jsonb),'targets',coalesce((select jsonb_agg(to_jsonb(t) order by t.product_key) from public.hq_propagation_targets t where t.decision_id=d.id),'[]'::jsonb),'audit',coalesce((select jsonb_agg(to_jsonb(a) order by a.created_at desc) from public.hq_decision_audit a where a.decision_id=d.id),'[]'::jsonb)) into v from public.hq_decisions d where d.id=p_id;return v;end $$;
create or replace function public.hq_rollback_decision(p_id uuid,p_reason text default null) returns uuid language plpgsql security definer set search_path=public as $$ declare d public.hq_decisions%rowtype;old public.hq_decisions%rowtype;v_id uuid;v_code text;p text;v int;begin perform public.hq_assert_owner();select * into d from public.hq_decisions where id=p_id for update;if d.status not in('active','locked') then raise exception 'Only active/locked decisions can be rolled back';end if;if d.supersedes_id is null then raise exception 'No previous decision version is available for rollback';end if;select * into old from public.hq_decisions where id=d.supersedes_id;if old.id is null then raise exception 'Previous decision not found';end if;v_code:=public.hq_next_decision_code();insert into public.hq_decisions(code,title,category,decision_type,status,rule_key,rule_value,reason,affected_products,effective_at,approved_by,approved_at,locked_by,locked_at,supersedes_id,rollback_of_id,created_by) values(v_code,'Rollback: '||old.title,old.category,old.decision_type,'active',old.rule_key,old.rule_value,coalesce(p_reason,'Rollback of '||d.code),old.affected_products,now(),auth.uid(),now(),auth.uid(),now(),d.id,p_id,auth.uid()) returning id into v_id;update public.hq_decisions set status='rolled_back',updated_at=now() where id=p_id;select coalesce(max(version),0)+1 into v from public.hq_decision_versions where decision_id=v_id;insert into public.hq_decision_versions(decision_id,version,snapshot,changed_by) select v_id,v,to_jsonb(x),auth.uid() from public.hq_decisions x where id=v_id;foreach p in array old.affected_products loop if old.rule_key is not null then update public.hq_product_configs set active=false,updated_at=now() where product_key=p and config_key=old.rule_key and active=true;insert into public.hq_product_configs(product_key,config_key,config_value,source_decision_id,source_version,effective_at,active,is_secret) values(p,old.rule_key,old.rule_value,v_id,v,now(),true,false);insert into public.hq_propagation_targets(decision_id,product_key,expected_config_key,expected_value,status,applied_at,verified_at) values(v_id,p,old.rule_key,old.rule_value,'applied',now(),now()) on conflict(decision_id,product_key,expected_config_key) do nothing;end if;end loop;insert into public.hq_decision_audit(decision_id,action,actor_id,details) values(p_id,'rolled_back',auth.uid(),jsonb_build_object('rollback_decision_id',v_id,'reason',p_reason));return v_id;end $$;

create table if not exists public.hq_departments(key text primary key,name text not null,mandate text not null,icon text,sort_order integer not null default 100,active boolean not null default true,created_at timestamptz not null default now());
create table if not exists public.hq_work_items(id uuid primary key default gen_random_uuid(),department_key text not null references public.hq_departments(key),work_type text not null,priority text not null default 'normal' check(priority in('low','normal','high','critical')),status text not null default 'open' check(status in('open','in_progress','waiting_approval','resolved','cancelled')),title text not null,summary text,source_type text,source_id uuid,route text,approval_required boolean not null default false,due_at timestamptz,evidence jsonb not null default '{}'::jsonb,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),resolved_at timestamptz);
create index if not exists hq_work_items_department_status_idx on public.hq_work_items(department_key,status,priority,created_at desc);
alter table public.hq_departments enable row level security;alter table public.hq_work_items enable row level security;revoke all on public.hq_departments,public.hq_work_items from anon,authenticated;
do $$ begin create policy hq_departments_owner_select on public.hq_departments for select to authenticated using ((select public.is_platform_owner())); exception when duplicate_object then null; end $$;
do $$ begin create policy hq_work_items_owner_select on public.hq_work_items for select to authenticated using ((select public.is_platform_owner())); exception when duplicate_object then null; end $$;
do $$ begin create policy hq_platform_events_owner_select on public.platform_events for select to authenticated using ((select public.is_platform_owner())); exception when duplicate_object then null; end $$;
do $$ begin create policy hq_notifications_owner_select on public.hq_notifications for select to authenticated using ((select public.is_platform_owner())); exception when duplicate_object then null; end $$;
do $$ begin create policy hq_incidents_owner_select on public.hq_incidents for select to authenticated using ((select public.is_platform_owner())); exception when duplicate_object then null; end $$;
insert into public.hq_departments(key,name,mandate,icon,sort_order) values ('executive','Executive','Decisions, priorities, approvals and company direction','boardroom',10),('finance','Finance','Revenue, expenses, receivables, reconciliations and controls','finance',20),('technology','Technology & Security','Platform health, incidents, releases, security and reliability','technology',30),('operations','Operations','School operations, teaching throughput, service levels and bottlenecks','operations',40),('product','Product','Feature adoption, funnels, retention, quality and user friction','product',50),('growth','Growth & Sales','Acquisition, activation, leads, partnerships and conversion','growth',60),('customer','Customer Success & Support','Onboarding, support, communication, retention and escalations','support',70),('content','Content & Curriculum','Curriculum coverage, publishing, VibeLabs, editorial and moderation','content',80),('people','People Operations','Staff access, responsibilities, onboarding, leave and performance workflows','people',90),('trust','Legal, Risk & Compliance','Privacy, consent, contracts, safeguarding, audit and risk','trust',100),('marketing','Marketing & Communications','Campaigns, brand, announcements, PR and communication calendar','marketing',110),('procurement','Procurement & Vendors','Vendors, purchases, renewals, contracts and service costs','procurement',120),('programs','Programs & Projects','Initiatives, milestones, dependencies, blocked work and delivery','programs',130),('data','Data & BI','Metric definitions, analytics, cohorts, forecasts and reporting','data',140),('quality','Quality & Release','Regression, release readiness, defects and content quality','quality',150),('knowledge','Knowledge & SOP','Policies, SOPs, company memory and operating documentation','knowledge',160) on conflict(key) do update set name=excluded.name,mandate=excluded.mandate,icon=excluded.icon,sort_order=excluded.sort_order;
create or replace function public.hq_route_work_items() returns integer language plpgsql security definer set search_path=public as $$ declare total_count int:=0;added_count int:=0;begin perform public.hq_assert_owner();insert into public.hq_work_items(department_key,work_type,priority,status,title,summary,source_type,source_id,route,approval_required,evidence) select case when i.incident_type ilike '%security%' or i.incident_type ilike '%auth%' then 'technology' when i.incident_type ilike '%config%' then 'technology' when i.incident_type ilike '%mark%' or i.incident_type ilike '%lesson%' then 'operations' else 'executive' end,'incident',case when i.severity='critical' then 'critical' else 'high' end,'open',i.title,i.summary,'incident',i.id,i.route,false,i.evidence from public.hq_incidents i where i.status<>'resolved' and not exists(select 1 from public.hq_work_items w where w.source_type='incident' and w.source_id=i.id);get diagnostics added_count=row_count;total_count:=total_count+added_count;insert into public.hq_work_items(department_key,work_type,priority,status,title,summary,source_type,source_id,route,approval_required,evidence) select case hn.category when 'content' then 'content' when 'finance' then 'finance' when 'security' then 'technology' when 'teaching' then 'operations' else 'customer' end,'notification',case when hn.severity='critical' then 'critical' when hn.severity='warning' then 'high' else 'normal' end,'open',hn.title,hn.body,'notification',hn.id,hn.route,false,hn.metadata from public.hq_notifications hn where hn.status<>'resolved' and hn.severity in('warning','critical') and not exists(select 1 from public.hq_work_items w where w.source_type='notification' and w.source_id=hn.id);get diagnostics added_count=row_count;total_count:=total_count+added_count;return total_count;end $$;
create or replace function public.hq_list_departments() returns table(key text,name text,mandate text,icon text,open_count bigint,critical_count bigint,waiting_approval_count bigint) language plpgsql security definer set search_path=public as $$ begin perform public.hq_assert_owner();perform public.hq_route_work_items();return query select d.key,d.name,d.mandate,d.icon,count(w.id) filter(where w.status in('open','in_progress','waiting_approval')),count(w.id) filter(where w.status in('open','in_progress','waiting_approval') and w.priority='critical'),count(w.id) filter(where w.status='waiting_approval') from public.hq_departments d left join public.hq_work_items w on w.department_key=d.key where d.active group by d.key,d.name,d.mandate,d.icon,d.sort_order order by d.sort_order;end $$;
create or replace function public.hq_list_work_items(p_department text default null,p_limit int default 100) returns setof public.hq_work_items language plpgsql security definer set search_path=public as $$ begin perform public.hq_assert_owner();perform public.hq_route_work_items();return query select * from public.hq_work_items where(p_department is null or department_key=p_department) order by case priority when 'critical' then 1 when 'high' then 2 when 'normal' then 3 else 4 end,created_at desc limit greatest(1,least(coalesce(p_limit,100),500));end $$;
create or replace function public.hq_create_work_item(p_department text,p_title text,p_summary text default null,p_priority text default 'normal',p_due_at timestamptz default null,p_approval_required boolean default false,p_route text default null,p_evidence jsonb default '{}'::jsonb) returns uuid language plpgsql security definer set search_path=public as $$ declare v_id uuid;begin perform public.hq_assert_owner();if not exists(select 1 from public.hq_departments where key=p_department and active) then raise exception 'Unknown department';end if;if p_priority not in('low','normal','high','critical') then raise exception 'Invalid priority';end if;insert into public.hq_work_items(department_key,work_type,priority,status,title,summary,route,approval_required,due_at,evidence) values(p_department,'manual',p_priority,case when p_approval_required then 'waiting_approval' else 'open' end,p_title,p_summary,p_route,p_approval_required,p_due_at,coalesce(p_evidence,'{}'::jsonb)) returning id into v_id;insert into public.hq_notifications(category,severity,title,body,route,status,metadata) values('operations',case when p_priority='critical' then 'critical' when p_priority='high' then 'warning' else 'info' end,'HQ work created',p_title,coalesce(p_route,'/hq/departments'),'unread',jsonb_build_object('work_item_id',v_id,'department',p_department));return v_id;end $$;
create or replace function public.hq_update_work_item(p_id uuid,p_status text) returns void language plpgsql security definer set search_path=public as $$ begin perform public.hq_assert_owner();if p_status not in('open','in_progress','waiting_approval','resolved','cancelled') then raise exception 'Invalid status';end if;update public.hq_work_items set status=p_status,updated_at=now(),resolved_at=case when p_status='resolved' then now() else resolved_at end where id=p_id;end $$;
create or replace function public.hq_get_morning_brief() returns jsonb language plpgsql security definer set search_path=public as $$ declare v jsonb;begin perform public.hq_assert_owner();perform public.hq_activate_due_decisions();perform public.hq_route_work_items();select jsonb_build_object('generated_at',now(),'headline',jsonb_build_object('new_users_today',(select count(*) from public.profiles where created_at>=date_trunc('day',now())),'active_schools',(select count(*) from public.schools where deleted_at is null and status::text='active'),'lesson_plans_today',(select count(*) from public.lesson_plans where created_at>=date_trunc('day',now())),'submissions_today',(select count(*) from public.homework_submissions where submitted_at>=date_trunc('day',now())),'open_incidents',(select count(*) from public.hq_incidents where status<>'resolved'),'decisions_waiting',(select count(*) from public.hq_decisions where status in('draft','reviewed','approved')),'work_waiting_approval',(select count(*) from public.hq_work_items where status='waiting_approval')),'priorities',coalesce((select jsonb_agg(x) from(select jsonb_build_object('department',department_key,'priority',priority,'title',title,'summary',summary,'route',route)x from public.hq_work_items where status in('open','in_progress','waiting_approval') order by case priority when 'critical' then 1 when 'high' then 2 else 3 end,created_at desc limit 7)q),'[]'::jsonb),'decisions',coalesce((select jsonb_agg(jsonb_build_object('id',id,'code',code,'title',title,'status',status)) from(select * from public.hq_decisions where status in('draft','reviewed','approved','locked') order by created_at desc limit 5)d),'[]'::jsonb)) into v;return v;end $$;

revoke all on function public.hq_create_decision(text,text,text,text,jsonb,text,text[],timestamptz),public.hq_update_draft_decision(uuid,text,text,text,text,jsonb,text,text[],timestamptz),public.hq_mark_decision_reviewed(uuid),public.hq_approve_decision(uuid),public.hq_cancel_decision(uuid,text),public.hq_create_amendment(uuid,text,jsonb,text,timestamptz),public.hq_lock_decision(uuid),public.hq_verify_decision_propagation(uuid),public.hq_rollback_decision(uuid,text),public.hq_list_decisions(int),public.hq_get_decision_detail(uuid),public.hq_route_work_items(),public.hq_list_departments(),public.hq_list_work_items(text,int),public.hq_create_work_item(text,text,text,text,timestamptz,boolean,text,jsonb),public.hq_update_work_item(uuid,text),public.hq_get_morning_brief() from public,anon;
grant execute on function public.hq_create_decision(text,text,text,text,jsonb,text,text[],timestamptz),public.hq_update_draft_decision(uuid,text,text,text,text,jsonb,text,text[],timestamptz),public.hq_mark_decision_reviewed(uuid),public.hq_approve_decision(uuid),public.hq_cancel_decision(uuid,text),public.hq_create_amendment(uuid,text,jsonb,text,timestamptz),public.hq_lock_decision(uuid),public.hq_verify_decision_propagation(uuid),public.hq_rollback_decision(uuid,text),public.hq_list_decisions(int),public.hq_get_decision_detail(uuid),public.hq_route_work_items(),public.hq_list_departments(),public.hq_list_work_items(text,int),public.hq_create_work_item(text,text,text,text,timestamptz,boolean,text,jsonb),public.hq_update_work_item(uuid,text),public.hq_get_morning_brief(),public.hq_get_product_config(text,text) to authenticated;
revoke execute on function public.hq_assert_owner() from authenticated;
