create or replace function public.search_school_directory(p_query text default null,p_level text default null,p_county text default null,p_sub_county text default null,p_lat numeric default null,p_lng numeric default null,p_limit integer default 30)
returns table(id uuid,name text,county text,sub_county text,ward text,school_type text,school_category text,ownership_type text,gender_type text,accommodation_type text,cluster text,knec_code text,nemis_code text,gps_lat numeric,gps_lng numeric,levels text[],match_score real,distance_km numeric,source text)
language sql stable security invoker set search_path=public as $$
with q as (select lower(regexp_replace(trim(coalesce(p_query,'')),'[^a-zA-Z0-9]+','','g')) n), unified as (
 select s.id,s.name::text,s.county::text,s.sub_county::text,s.ward::text,s.school_type::text,s.school_category::text,s.ownership_type,s.gender_type,s.accommodation_type,s.cluster,s.knec_code::text,s.nemis_code::text,s.gps_lat,s.gps_lng,coalesce(array_agg(distinct sl.level) filter(where sl.level is not null),'{}'::text[]) levels,'CANONICAL'::text source
 from public.schools s cross join q left join public.school_levels sl on sl.school_id=s.id where s.deleted_at is null and (p_county is null or s.county=p_county) and (p_sub_county is null or s.sub_county=p_sub_county) and (q.n='' or s.name ilike '%'||trim(p_query)||'%' or coalesce(s.name_normalized,'') like '%'||q.n||'%' or s.knec_code=trim(p_query) or s.nemis_code=trim(p_query)) group by s.id
 union all
 select d.id,d.name,d.county,d.sub_county,null,d.type,null,null,null,null,null,null,null,d.latitude::numeric,d.longitude::numeric,case when lower(coalesce(d.type,'')) like '%junior%' then array['JUNIOR']::text[] when lower(coalesce(d.type,'')) like '%secondary%' or lower(coalesce(d.type,'')) like '%senior%' then array['SENIOR_SECONDARY']::text[] else array['PRIMARY']::text[] end,'DIRECTORY'
 from public.schools_directory d cross join q where lower(coalesce(d.status,'active')) <> 'closed' and (p_county is null or d.county=p_county) and (p_sub_county is null or d.sub_county=p_sub_county) and (q.n='' or d.name ilike '%'||trim(p_query)||'%' or lower(regexp_replace(d.name,'[^a-zA-Z0-9]+','','g')) like '%'||q.n||'%')
), dedup as (select u.*,row_number() over(partition by lower(regexp_replace(u.name,'[^a-zA-Z0-9]+','','g')),coalesce(lower(u.county),''),coalesce(lower(u.sub_county),''),coalesce(u.knec_code,''),coalesce(u.nemis_code,'') order by case when u.source='CANONICAL' then 0 else 1 end) rn from unified u), ranked as (select d.*,greatest(extensions.similarity(lower(regexp_replace(d.name,'[^a-zA-Z0-9]+','','g')),q.n),0)::real match_score from dedup d cross join q where d.rn=1 and (p_level is null or p_level=any(d.levels) or (p_level='JUNIOR' and 'PRIMARY'=any(d.levels))))
select r.id,r.name,r.county,r.sub_county,r.ward,r.school_type,r.school_category,r.ownership_type,r.gender_type,r.accommodation_type,r.cluster,r.knec_code,r.nemis_code,r.gps_lat,r.gps_lng,r.levels,r.match_score,case when p_lat is not null and p_lng is not null and r.gps_lat is not null and r.gps_lng is not null then round((6371*2*asin(sqrt(power(sin(radians((r.gps_lat-p_lat)/2)),2)+cos(radians(p_lat))*cos(radians(r.gps_lat))*power(sin(radians((r.gps_lng-p_lng)/2)),2))))::numeric,2) else null end,r.source from ranked r order by r.match_score desc,case when p_lat is not null and p_lng is not null and r.gps_lat is not null and r.gps_lng is not null then 6371*2*asin(sqrt(power(sin(radians((r.gps_lat-p_lat)/2)),2)+cos(radians(p_lat))*cos(radians(r.gps_lat))*power(sin(radians((r.gps_lng-p_lng)/2)),2))) else 999999 end,r.name limit greatest(1,least(coalesce(p_limit,30),100));
$$;
revoke all on function public.search_school_directory(text,text,text,text,numeric,numeric,integer) from public,anon;
grant execute on function public.search_school_directory(text,text,text,text,numeric,numeric,integer) to authenticated;