-- Recovered verbatim from the production Supabase migration ledger for L0 replay parity.
create table if not exists public.hq_context_sources(id uuid primary key default gen_random_uuid(), source_key text not null unique, name text not null, source_type text not null check(source_type in ('table','query','external','manual','derived')), connection_ref text, owner text not null, reliability_method text not null, reliability_score numeric check(reliability_score between 0 and 1), active boolean not null default true, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.hq_context_fact_definitions(id uuid primary key default gen_random_uuid(), fact_key text not null, version integer not null check(version>0), computation_kind text not null check(computation_kind in ('sql','logic','aggregate','manual','external')), computation_ref text not null, source_id uuid not null references public.hq_context_sources(id), unit text, freshness_seconds integer not null check(freshness_seconds>0), confidence_method text not null check(confidence_method in ('deterministic','measured','corroborated','human_estimate','external_unverified','derived')), effective_at timestamptz not null default now(), retired_at timestamptz, created_at timestamptz not null default now(), unique(fact_key,version));
create table if not exists public.hq_context_scopes(id uuid primary key default gen_random_uuid(), scope_type text not null check(scope_type in ('company','department','lane','worker')), scope_owner_key text, allowed_fact_keys text[] not null default '{}', denied_fact_keys text[] not null default '{}', created_at timestamptz not null default now(), unique(scope_type,scope_owner_key));
create table if not exists public.hq_context_facts_cache(id uuid primary key default gen_random_uuid(), fact_key text not null, fact_definition_id uuid not null references public.hq_context_fact_definitions(id), scope_id uuid not null references public.hq_context_scopes(id), value jsonb not null, computed_at timestamptz not null default now(), freshness_expires_at timestamptz not null, confidence numeric not null check(confidence between 0 and 1), confidence_source text not null, confidence_evidence jsonb not null default '{}'::jsonb, unique(fact_key,fact_definition_id,scope_id,computed_at));
create table if not exists public.hq_context_decision_snapshots(id uuid primary key default gen_random_uuid(), decision_key text not null unique, decision_type text not null, taken_at timestamptz not null default now(), rules_version text not null, context_version text not null, facts jsonb not null, outcome jsonb, reason text not null, actor_type text not null check(actor_type in ('system','worker','human')), actor_key text not null, created_at timestamptz not null default now());
create table if not exists public.hq_context_provenance(id uuid primary key default gen_random_uuid(), snapshot_id uuid not null references public.hq_context_decision_snapshots(id) on delete restrict, fact_key text not null, fact_definition_id uuid not null references public.hq_context_fact_definitions(id), source_id uuid not null references public.hq_context_sources(id), raw_refs jsonb not null default '[]'::jsonb, computation_digest text not null, created_at timestamptz not null default now());
create index if not exists hq_context_fact_defs_key_idx on public.hq_context_fact_definitions(fact_key,version desc);
create index if not exists hq_context_cache_lookup_idx on public.hq_context_facts_cache(scope_id,fact_key,computed_at desc);
create index if not exists hq_context_snapshot_type_idx on public.hq_context_decision_snapshots(decision_type,taken_at desc);
create index if not exists hq_context_provenance_snapshot_idx on public.hq_context_provenance(snapshot_id,fact_key);
alter table public.hq_context_sources enable row level security; alter table public.hq_context_fact_definitions enable row level security; alter table public.hq_context_scopes enable row level security; alter table public.hq_context_facts_cache enable row level security; alter table public.hq_context_decision_snapshots enable row level security; alter table public.hq_context_provenance enable row level security;
comment on table public.hq_context_decision_snapshots is 'Immutable-at-application decision evidence. Application code must insert snapshots and never mutate them.';
