-- HQ company authority phase 2
-- Expands product governance, emergency recovery, deterministic intelligence,
-- goals/OKRs and evidence-backed certification. Applied to production first.

insert into public.hq_policy_registry(policy_key,domain,owner_department,value_type,default_value,allowed_products,risk_level,failure_mode,description,active)
values
('student.enabled','product','product','boolean','true'::jsonb,array['student'],'high','last_known_good','Student product availability',true),
('teacher.enabled','product','product','boolean','true'::jsonb,array['teacher'],'high','last_known_good','Teacher product availability',true),
('parent.enabled','product','product','boolean','true'::jsonb,array['parent'],'high','last_known_good','Parent product availability',true),
('school_admin.enabled','product','product','boolean','true'::jsonb,array['school_admin'],'high','last_known_good','School administration availability',true),
('vibelearn.enabled','product','product','boolean','true'::jsonb,array['vibelearn'],'high','last_known_good','VibeLearn availability',true),
('vibebooks.enabled','product','product','boolean','true'::jsonb,array['vibebooks'],'high','last_known_good','VibeBooks availability',true),
('billing.enabled','commercial','finance','boolean','true'::jsonb,array['billing'],'critical','fail_closed','Billing and subscription mutations enabled',true),
('billing.free_tier_enabled','commercial','finance','boolean','true'::jsonb,array['billing'],'normal','last_known_good','Free tier availability',true),
('billing.subscription_price_kes','commercial','finance','integer','0'::jsonb,array['billing'],'high','last_known_good','Canonical subscription price in KES',true),
('assessment.release_enabled','academic','learning','boolean','true'::jsonb,array['teacher','student'],'high','fail_closed','Assessment release authority',true),
('support.intake_enabled','operations','customer','boolean','true'::jsonb,array['global'],'normal','last_known_good','Customer support intake availability',true)
on conflict(policy_key) do update set domain=excluded.domain,owner_department=excluded.owner_department,value_type=excluded.value_type,default_value=excluded.default_value,allowed_products=excluded.allowed_products,risk_level=excluded.risk_level,failure_mode=excluded.failure_mode,description=excluded.description,active=true;

create table if not exists public.hq_goals(
 id uuid primary key default gen_random_uuid(), key text unique not null, department_key text not null references public.hq_departments(key), title text not null, metric_key text not null, target numeric not null, period text not null default 'quarter', direction text not null default 'gte' check(direction in('gte','lte')), status text not null default 'active' check(status in('active','paused','completed')), starts_at timestamptz not null default now(), ends_at timestamptz, created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create table if not exists public.hq_certification_results(
 id uuid primary key default gen_random_uuid(), certification_version text not null, question_no int not null check(question_no between 1 and 100), area text not null, question text not null, result text not null check(result in('PASS','PARTIAL','FAIL')), evidence jsonb not null default '{}'::jsonb, checked_at timestamptz not null default now(), unique(certification_version,question_no)
);

create or replace function public.hq_resolve_incident(p_id uuid,p_reason text default null) returns void language plpgsql security definer set search_path=public as $$ begin perform public.hq_assert_owner(); update hq_incidents set status='resolved',resolved_at=now(),evidence=coalesce(evidence,'{}'::jsonb)||jsonb_build_object('resolution_reason',coalesce(p_reason,'Resolved from HQ'),'resolved_by',auth.uid()) where id=p_id and status<>'resolved'; if not found then raise exception 'Open incident not found'; end if; insert into hq_notifications(category,severity,title,body,route,status,metadata) values('incident','success','Incident resolved',coalesce(p_reason,'Incident resolved'),'/hq','unread',jsonb_build_object('incident_id',p_id)); end $$;

create or replace function public.hq_emergency_control(p_policy_key text,p_product_key text,p_value jsonb,p_reason text) returns jsonb language plpgsql security definer set search_path=public as $$ declare v_decision uuid;v_incident uuid; begin perform public.hq_assert_owner(); if nullif(btrim(coalesce(p_reason,'')),'') is null then raise exception 'Emergency reason is required'; end if; v_incident:=public.hq_open_incident('policy_emergency','critical','Emergency control: '||p_policy_key,p_reason,jsonb_build_object('policy_key',p_policy_key,'product_key',p_product_key,'requested_value',p_value),'/hq/decisions'); v_decision:=public.hq_emergency_set_policy(p_policy_key,p_product_key,p_value,p_reason); update hq_incidents set evidence=evidence||jsonb_build_object('decision_id',v_decision) where id=v_incident; return jsonb_build_object('decisionId',v_decision,'incidentId',v_incident,'verificationRequired',true); end $$;

create or replace function public.hq_complete_emergency_recovery(p_decision_id uuid,p_incident_id uuid,p_reason text default null) returns jsonb language plpgsql security definer set search_path=public as $$ declare v jsonb; begin perform public.hq_assert_owner(); v:=public.hq_verify_decision_propagation(p_decision_id); if coalesce((v->>'drift')::int,0)>0 or coalesce((v->>'pending')::int,0)>0 then raise exception 'Recovery is not independently verified'; end if; perform public.hq_resolve_incident(p_incident_id,coalesce(p_reason,'Emergency recovery independently verified')); return v||jsonb_build_object('incidentResolved',true); end $$;

create or replace function public.hq_run_company_intelligence() returns jsonb language plpgsql security definer set search_path=public as $$ declare created_count int:=0;v_signups int;v_lessons int;v_submissions int;v_failures int; begin perform public.hq_assert_owner(); select count(*) into v_signups from profiles where created_at>=now()-interval '24 hours'; select count(*) into v_lessons from lesson_plans where created_at>=now()-interval '24 hours'; select count(*) into v_submissions from homework_submissions where created_at>=now()-interval '24 hours'; select count(*) into v_failures from hq_incidents where status<>'resolved' and severity in('high','critical'); if v_signups>=10 and v_lessons=0 then insert into hq_work_items(department_key,work_type,priority,status,title,summary,source_type,route,approval_required,due_at,evidence) select 'product','deterministic_finding','high','open','Activation risk: signups without lesson activity',format('%s signups in 24h but no lesson plans created',v_signups),'rule','/hq',false,now()+interval '24 hours',jsonb_build_object('signups_24h',v_signups,'lesson_plans_24h',v_lessons,'rule','signup_up_activation_down') where not exists(select 1 from hq_work_items where title='Activation risk: signups without lesson activity' and status in('open','in_progress','waiting_approval')); get diagnostics created_count=row_count; end if; if v_failures>0 then insert into hq_notifications(category,severity,title,body,route,status,metadata) select 'operations','critical','Critical operational incidents need attention',format('%s high/critical incidents remain unresolved',v_failures),'/hq','unread',jsonb_build_object('rule','critical_incidents_open','count',v_failures) where not exists(select 1 from hq_notifications where title='Critical operational incidents need attention' and status='unread'); end if; perform public.hq_generate_operational_alerts(); perform public.hq_route_work_items(); return jsonb_build_object('workCreated',created_count,'signups24h',v_signups,'lessonPlans24h',v_lessons,'submissions24h',v_submissions,'criticalOpen',v_failures,'ranAt',now()); end $$;

create or replace function public.hq_get_goal_progress() returns jsonb language plpgsql security definer set search_path=public as $$ declare r record;out jsonb:='[]'::jsonb;actual numeric; begin perform public.hq_assert_owner(); for r in select * from hq_goals where status='active' order by department_key,key loop actual:=case r.metric_key when 'active_users_30d' then (select count(distinct user_id) from hq_policy_evaluations where created_at>=now()-interval '30 days') when 'open_incidents' then (select count(*) from hq_incidents where status<>'resolved') when 'publications_live' then (select count(*) from vibe_publications where status='published') when 'submissions_30d' then (select count(*) from homework_submissions where created_at>=now()-interval '30 days') else null end; out:=out||jsonb_build_array(jsonb_build_object('key',r.key,'title',r.title,'department',r.department_key,'metric',r.metric_key,'actual',actual,'target',r.target,'direction',r.direction,'onTrack',case when actual is null then null when r.direction='gte' then actual>=r.target else actual<=r.target end)); end loop; return out; end $$;

revoke all on public.hq_goals,public.hq_certification_results from anon,authenticated;
grant select on public.hq_goals,public.hq_certification_results to authenticated;
grant execute on function public.hq_resolve_incident(uuid,text),public.hq_emergency_control(text,text,jsonb,text),public.hq_complete_emergency_recovery(uuid,uuid,text),public.hq_run_company_intelligence(),public.hq_get_goal_progress() to authenticated;