'use client';
import {useCallback,useEffect,useMemo,useRef,useState} from 'react';
import Link from 'next/link';
import {useParams,useSearchParams} from 'next/navigation';
import {supabase} from '@/lib/supabase';
import {nairobiDateStr} from '@/lib/time';
import {loadWorkbook,saveDocument} from '@/lib/class-workbook/data';
import type {Data,Document} from '@/lib/class-workbook/model';
import {classTimeline,ask,insights,picker,seatOrder,shuffled,summary,type Event} from '@/lib/classroom/model';
import {loadEvents,recordAction,resolveAction} from '@/lib/classroom/data';
import styles from '../workbook/ClassWorkbook.module.css';

type Details={name:string;admission_number:string|null;gender:string|null;date_of_birth:string|null};
type Departed={id:string;name:string;admission_number:string|null;left_at:string};
const questions=['Who needs attention','Who is improving','Who is declining','Missing homework','No assessment','No participation','Follow-ups due','Attendance problems'];
const metric=(v:number|null,suffix='')=>v===null?'No record':`${v}${suffix}`;
export default function ClassWorkspace(){
 const {id:classId}=useParams<{id:string}>();const search=useSearchParams();const requested=search.get('subjectId')??'';
 const [data,setData]=useState<Data|null>(null),[doc,setDoc]=useState<Document|null>(null),[revision,setRevision]=useState(0),[events,setEvents]=useState<Event[]>([]);
 const [loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState('');
 const [view,setView]=useState<'roster'|'tools'|'activity'>('roster');
 const [subject,setSubject]=useState(requested),[query,setQuery]=useState(''),[selected,setSelected]=useState<string[]>([]);
 const [note,setNote]=useState(''),[kind,setKind]=useState<'observation'|'participation'|'recognition'|'followup'|'parent_contact'|'management'>('observation'),[due,setDue]=useState('');
 const [seen,setSeen]=useState<string[]>([]),[picked,setPicked]=useState<string|null>(null),[columns,setColumns]=useState(4);
 const [groupA,setGroupA]=useState(''),[groupB,setGroupB]=useState(''),[otherClass,setOtherClass]=useState(''),[other,setOther]=useState<Data|null>(null);
 const [detail,setDetail]=useState<Details|null>(null),[original,setOriginal]=useState<Details|null>(null),[target,setTarget]=useState(''),[departed,setDeparted]=useState<Departed[]>([]);
 const request=useRef<{key:string;id:string}|null>(null);const actionRequest=useRef<{key:string;id:string}|null>(null);const detailGeneration=useRef(0);
 const load=useCallback(async()=>{const loaded=await loadWorkbook(classId);const activity=await loadEvents(loaded.data);return {...loaded,activity};},[classId]);
 useEffect(()=>{let current=true;setLoading(true);setData(null);setOther(null);setSelected([]);setError('');setSeen([]);setPicked(null);void load().then(result=>{if(!current)return;setData(result.data);setDoc(result.document);setRevision(result.revision);setEvents(result.activity);setSubject(requested||(!result.data.isClassTeacher?result.data.subjects[0]?.id??'':''));}).catch(e=>{if(current)setError(e instanceof Error?e.message:'The class could not be loaded.');}).finally(()=>{if(current)setLoading(false);});return()=>{current=false;};},[load,requested]);
 const refresh=async()=>{const r=await load();setData(r.data);setDoc(r.document);setRevision(r.revision);setEvents(r.activity);setSelected(ids=>ids.filter(id=>r.data.learners.some(l=>l.id===id)));};
 async function run(action:()=>Promise<void>){if(busy)return;setBusy(true);setError('');setMessage('');try{await action();}catch(e){setError(e instanceof Error?e.message:'The change could not be saved. Retry after checking the class.');}finally{setBusy(false);}}
 const rows=useMemo(()=>data?insights(data,events,subject,nairobiDateStr()):[],[data,events,subject]);const answer=useMemo(()=>ask(rows,query),[rows,query]);
 const seats=useMemo(()=>data&&doc?seatOrder(data,doc.cells.seating??{}):[],[data,doc]);
 const timeline=useMemo(()=>data?classTimeline(data,events,subject,selected):[],[data,events,subject,selected]);
 const one=selected.length===1?selected[0]:'';
 useEffect(()=>{const generation=++detailGeneration.current;setDetail(null);setOriginal(null);if(!one||!data?.isClassTeacher)return;void supabase.from('students').select('name,admission_number,gender,date_of_birth').eq('id',one).single().then(r=>{if(generation!==detailGeneration.current)return;if(r.error){setError(r.error.message);return;}setDetail(r.data);setOriginal(r.data);});},[one,data?.isClassTeacher]);
 if(loading)return <section className={styles.workbook}><p role="status">Opening your class workspace…</p></section>;
 if(!data||!doc)return <section className={styles.workbook}><p role="alert">{error||'Your class is unavailable.'}</p><Link href="/teacher/classhub">My classes</Link><button onClick={()=>void run(refresh)}>Retry</button></section>;
 const suffix=subject?`?subjectId=${subject}`:'';
 const chosen=rows.filter(r=>selected.includes(r.learner.id));
 const groupSummary=(id:string)=>summary(rows.filter(r=>data.members.some(m=>m.group_id===id&&m.student_id===r.learner.id)));
 const weak=Array.from(new Set(data.evidence.filter(e=>!subject||e.subject_id===subject).map(e=>e.outcome_id))).map(id=>{const evidence=data.evidence.filter(e=>e.outcome_id===id&&(!subject||e.subject_id===subject));const latest=new Map<string,typeof evidence[number]>();for(const e of evidence.sort((a,b)=>a.observed_at.localeCompare(b.observed_at)))latest.set(e.student_id,e);const support=[...latest.values()].filter(e=>e.proficiency==='BE'||e.proficiency==='AE'||e.max_score!==null&&e.max_score>0&&e.score!==null&&e.score/e.max_score<.5);return {id,title:data.outcomes.find(o=>o.id===id)?.outcome_text??'Recorded learning outcome',ids:support.map(e=>e.student_id),count:latest.size};}).filter(o=>o.ids.length).sort((a,b)=>b.ids.length-a.ids.length);
 const toggle=(id:string)=>setSelected(ids=>ids.includes(id)?ids.filter(x=>x!==id):[...ids,id]);
 async function arrange(ids:string[]){const next=structuredClone(doc!);if(!next.sheets.some(s=>s.id==='seating'))next.sheets.push({id:'seating',title:'Seating plan',kind:'custom',columns:[{id:'position',label:'Seat number',type:'number'}]});next.cells.seating=Object.fromEntries(ids.map((id,index)=>[id,{position:index+1}]));const rev=await saveDocument(data!,next,revision);setDoc(next);setRevision(rev);setMessage('Seating plan saved privately. Learner enrolment and marks are unchanged.');}
 async function manage(id:string,action:'edit'|'move'|'leave'|'restore'){
  if(!data)return;const payload=action==='edit'?{...detail,expected:original}:action==='move'?{target_class_id:target}:{};
  const key=JSON.stringify([classId,id,action,payload]);if(request.current?.key!==key)request.current={key,id:crypto.randomUUID()};
  const r=await supabase.rpc('teacher_manage_class_learner',{p_class_id:classId,p_student_id:id,p_action:action,p_payload:JSON.parse(JSON.stringify(payload)),p_request_id:request.current.id});if(r.error||r.data!==id)throw new Error(r.error?.message??'Learner change could not be confirmed.');await refresh();request.current=null;setDetail(null);setOriginal(null);setSelected([]);const removed=await supabase.rpc('teacher_get_departed_class_learners',{p_class_id:classId});if(removed.error)throw new Error(removed.error.message);setDeparted(removed.data??[]);setMessage('Learner record updated. Existing learning and attendance history is retained.');
 }
 return <section className={`${styles.workbook} ${styles.classWorkspace}`}>
  <header className={styles.header}><div><Link href={`/teacher/classhub/${classId}${subject?`?mode=subject&subjectId=${subject}`:''}`}>← Class</Link><h1>{data.className}</h1><p>Explore learners, organise the classroom and act on saved evidence.</p></div><div className={styles.actions}><Link href={`/teacher/results?classId=${classId}${subject?`&subjectId=${subject}`:''}`}>Exams</Link><Link href={`/teacher/classhub/${classId}/workbook${suffix}`}>Open class sheets</Link></div></header>
  {error&&<p role="alert" className={styles.error}>{error}</p>}{message&&<p role="status">{message}</p>}
  <nav className={styles.tabs} aria-label="Class workspace sections">{([['roster','Learners'],['tools','Classroom tools'],['activity','Activity']] as const).map(([value,label])=><button key={value} aria-pressed={view===value} className={view===value?styles.active:''} onClick={()=>setView(value)}>{label}</button>)}</nav>
  <p className={styles.muted}>{data.learners.length} learners · {selected.length} selected. Selection is kept when you change sections.</p>
  {view==='roster'&&<>
  <section className={styles.card}><div className={styles.toolbar}><label>Subject <select aria-label="Subject" value={subject} onChange={e=>{setSubject(e.target.value);setSelected([]);setOther(null);setOtherClass('');}}>{data.isClassTeacher&&<option value="">My class overview</option>}{data.subjects.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><button disabled={busy} onClick={()=>void run(refresh)}>Refresh evidence</button><Link href={`/teacher/classhub/${classId}/groups${suffix}`}>Groups & lists</Link><Link href={`/teacher/classhub/${classId}/games${suffix}`}>Class games</Link></div><input style={{width:'100%'}} aria-label="Ask about your class or find a learner" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Ask: Who is improving? Or find a learner"/><details><summary>Filter by recorded evidence</summary><div className={styles.actions}>{questions.map(q=><button key={q} onClick={()=>setQuery(q)}>{q}</button>)}</div></details><p>{answer.explanation}{query&&!answer.understood?' This question is not supported yet; showing matching names and admission numbers.':''}</p>
   <p>{answer.rows.length} learners shown · {selected.length} selected</p><button onClick={()=>setSelected(answer.rows.map(r=>r.learner.id))}>Select shown learners</button> <button onClick={()=>setSelected([])}>Clear selection</button>
   <div className={styles.scroll}><table className={`${styles.grid} ${styles.rosterGrid}`}><caption>Saved learner evidence — blank evidence stays unknown</caption><thead><tr><th aria-label="Select learners"><span style={{position:'absolute',width:1,height:1,overflow:'hidden',clipPath:'inset(50%)'}}>Choose</span></th><th>Learner</th><th>Attendance</th><th>Overdue work</th><th>Released average</th><th>Recent change</th><th>Why check in?</th></tr></thead><tbody>{answer.rows.map(r=><tr key={r.learner.id}><td><input type="checkbox" aria-label={`Select ${r.learner.name}`} checked={selected.includes(r.learner.id)} onChange={()=>toggle(r.learner.id)}/></td><th><Link href={`/teacher/classhub/${classId}/student/${r.learner.id}${suffix}`}>{r.learner.name}</Link></th><td>{metric(r.attendance,'%')}</td><td>{r.missing}</td><td>{metric(r.average,'%')}</td><td>{metric(r.change,' points')}</td><td>{r.reasons.join('; ')||'No attention signal in available records'}</td></tr>)}</tbody></table></div>
   <div className={styles.actions}><Link href={`/teacher/classhub/${classId}/groups?${new URLSearchParams({...(subject?{subjectId:subject}:{}),selected:selected.join(',')})}`}>Make groups or give selected learners work</Link><Link href={`/teacher/assessment/interventions?classId=${classId}${subject?'&subjectId='+subject:''}`}>Plan support and reassessment</Link></div>
  </section>
  <details className={styles.card}><summary>Compare learners, groups or streams</summary><p>Select two to four learners for a side-by-side view. Comparisons use recorded evidence and show its coverage.</p>{chosen.length>=2&&chosen.length<=4&&<div style={{overflowX:'auto'}}><table className={styles.grid}><thead><tr><th>Measure</th>{chosen.map(r=><th key={r.learner.id}>{r.learner.name}</th>)}</tr></thead><tbody>{[['Attendance',...chosen.map(r=>metric(r.attendance,'%'))],['Released assessment average',...chosen.map(r=>metric(r.average,'%'))],['Recent change',...chosen.map(r=>metric(r.change,' points'))],['Overdue work',...chosen.map(r=>r.missing)],['Recorded participation (7 days)',...chosen.map(r=>r.participation)]].map((r,i)=><tr key={i}>{r.map((cell,j)=>j===0?<th key={j}>{cell}</th>:<td key={j}>{cell}</td>)}</tr>)}</tbody></table></div>}
   <div className={styles.toolbar}><label>First group <select value={groupA} onChange={e=>setGroupA(e.target.value)}><option value="">Choose</option>{data.groups.map(g=><option key={g.id} value={g.id}>{g.name}</option>)}</select></label><label>Second group <select value={groupB} onChange={e=>setGroupB(e.target.value)}><option value="">Choose</option>{data.groups.map(g=><option key={g.id} value={g.id}>{g.name}</option>)}</select></label><label>Another assigned class <select value={otherClass} onChange={e=>{setOtherClass(e.target.value);setOther(null);}}><option value="">Choose</option>{data.classes.filter(c=>c.id!==classId).map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><button disabled={busy||!otherClass} onClick={()=>void run(async()=>{const r=await loadWorkbook(otherClass);if(subject&&!r.data.subjects.some(s=>s.id===subject))throw new Error('Choose a subject assigned to you in both classes.');setOther(r.data);})}>Compare class</button></div>
   {(groupA&&groupB&&groupA!==groupB||other)&&<div style={{overflowX:'auto'}}><table className={styles.grid}><thead><tr><th>Cohort</th><th>Learners</th><th>With released assessments</th><th>Average %</th><th>Attendance %</th><th>Overdue items</th></tr></thead><tbody>{(other?[{name:data.className,value:summary(rows)},{name:other.className,value:summary(insights(other,[],subject,nairobiDateStr()))}]:[{name:data.groups.find(g=>g.id===groupA)?.name,value:groupSummary(groupA)},{name:data.groups.find(g=>g.id===groupB)?.name,value:groupSummary(groupB)}]).map((item,i)=><tr key={i}><th>{item.name}</th><td>{item.value.learners}</td><td>{item.value.assessed}</td><td>{metric(item.value.average)}</td><td>{metric(item.value.attendance)}</td><td>{item.value.missing}</td></tr>)}</tbody></table></div>}<p>These are descriptive summaries of available records. Different tasks and coverage can make cohorts unsuitable for a ranking.</p>
  </details>
  <details className={styles.card}><summary>What should we practise next?</summary>{weak.length?weak.slice(0,10).map(o=><p key={o.id}>{o.title}: {o.ids.length} of {o.count} learners with recorded evidence need more practice. <button onClick={()=>setSelected(o.ids)}>Select these learners</button></p>):<p>No recorded outcome evidence identifies a practice group yet.</p>}<Link href={`/teacher/scheme?classId=${classId}${subject?'&subjectId='+subject:''}`}>Use this evidence when planning the next lesson</Link></details>
  </>}
  {view==='tools'&&<>
  <section className={styles.card}><h2>Record a classroom action</h2><p>Choose learners above. Notes stay private to you. A parent-contact note records a conversation; it sends no message.</p><select aria-label="Action type" value={kind} onChange={e=>setKind(e.target.value as typeof kind)}>{[['observation','Learning observation'],['participation','Participation'],['recognition','Recognition'],['followup','Follow-up'],['parent_contact','Parent conversation'],['management','Class duty or responsibility']].map(([value,label])=><option key={value} value={value}>{label}</option>)}</select><textarea aria-label="Factual teacher note" value={note} maxLength={2000} rows={3} onChange={e=>setNote(e.target.value)} placeholder="e.g. Needs another worked example on fractions"/>{kind==='followup'&&<label>Follow-up date <input type="date" value={due} onChange={e=>setDue(e.target.value)}/></label>}<button disabled={busy||!selected.length||!note.trim()||kind==='followup'&&!due} onClick={()=>void run(async()=>{const key=JSON.stringify([selected.slice().sort(),subject,note,kind,due]);if(actionRequest.current?.key!==key)actionRequest.current={key,id:crypto.randomUUID()};await recordAction(data,selected,subject,note,kind,due,actionRequest.current.id);setEvents(await loadEvents(data));actionRequest.current=null;setNote('');setMessage('Classroom action saved for the selected learners.');})}>Save for {selected.length} learners</button>
  </section>

  <section className={styles.card}><h2>Classroom tools</h2><h3>Pick a learner fairly</h3><p>Use selected learners, or the whole class. Everyone is picked once before you reset this round. Picking creates no participation record.</p><button onClick={()=>{const id=picker(selected.length?selected:data.learners.map(l=>l.id),seen);setPicked(id);if(id)setSeen(s=>[...s,id]);}}>{picked?'Pick next learner':'Pick a learner'}</button> <button onClick={()=>{setSeen([]);setPicked(null);}}>Reset round</button><p role="status">{picked?data.learners.find(l=>l.id===picked)?.name:seen.length?'All learners in this round have been picked.':'Ready to pick.'}</p><h3>My seating plan</h3><label>Seats across <input type="number" min={1} max={10} value={columns} onChange={e=>setColumns(Math.max(1,Math.min(10,Number(e.target.value)||1)))}/></label><div className={styles.actions}><button disabled={busy} onClick={()=>void run(()=>arrange([...data.learners].sort((a,b)=>a.name.localeCompare(b.name)).map(l=>l.id)))}>Save alphabetical seating</button><button disabled={busy} onClick={()=>void run(()=>arrange(shuffled(data.learners.map(l=>l.id))))}>Save random seating</button><button onClick={()=>window.print()}>Print class view</button></div><div style={{display:'grid',gridTemplateColumns:`repeat(${columns},minmax(80px,1fr))`,gap:8,overflowX:'auto',marginTop:12}}>{seats.map((learner,index)=><div key={learner.id} style={{border:'1px solid #d1d5db',borderRadius:8,padding:8}}><strong>{index+1}. {learner.name}</strong><div><button disabled={busy||index===0} aria-label={`Move ${learner.name} to previous seat`} onClick={()=>void run(async()=>{const ids=seats.map(l=>l.id);[ids[index-1],ids[index]]=[ids[index],ids[index-1]];await arrange(ids);})}>←</button><button disabled={busy||index===seats.length-1} aria-label={`Move ${learner.name} to next seat`} onClick={()=>void run(async()=>{const ids=seats.map(l=>l.id);[ids[index+1],ids[index]]=[ids[index],ids[index+1]];await arrange(ids);})}>→</button></div></div>)}</div></section>
  </>}
  {view==='activity'&&<section className={styles.card}><h2>Class activity history</h2><p>Showing the latest 100 visible attendance, work, released assessment and teacher activity records{selected.length?' for your selected learners':''}. Learner profiles include attendance, work and assessment history.</p>{timeline.length?timeline.map(e=><p key={e.id}><strong>{data.learners.find(l=>l.id===e.student_id)?.name??'Former learner'}</strong> · {e.event_kind.replaceAll('_',' ')} · {new Date(e.created_at).toLocaleDateString('en-KE')}<br/>{e.note}{e.due_at&&` · Due ${e.due_at.slice(0,10)}`}{e.resolved_at?' · Follow-up completed':e.event_kind==='followup'&&e.created_by===data.teacherId&&<button disabled={busy} onClick={()=>void run(async()=>{await resolveAction(e);setEvents(await loadEvents(data));setMessage('Follow-up completed.');})}>Mark followed up</button>}</p>):<p>No class activity has been recorded yet.</p>}</section>}
  {view==='roster'&&data.isClassTeacher&&<details className={styles.card}><summary>Correct learner details or enrolment</summary><p>Select one learner above. Moving and leaving preserve the learner identity and previous academic records.</p>{one&&detail&&original&&<><label>Name <input value={detail.name} maxLength={200} onChange={e=>setDetail({...detail,name:e.target.value})}/></label><label>Admission number (optional) <input value={detail.admission_number??''} maxLength={80} onChange={e=>setDetail({...detail,admission_number:e.target.value||null})}/></label><label>Gender (optional) <select value={detail.gender??''} onChange={e=>setDetail({...detail,gender:e.target.value||null})}><option value="">Not recorded</option><option value="male">Male</option><option value="female">Female</option><option value="other">Other</option></select></label><label>Date of birth (optional) <input type="date" max={nairobiDateStr()} value={detail.date_of_birth??''} onChange={e=>setDetail({...detail,date_of_birth:e.target.value||null})}/></label><button disabled={busy||!detail.name.trim()} onClick={()=>void run(()=>manage(one,'edit'))}>Save learner details</button><label>Move to my other class <select value={target} onChange={e=>setTarget(e.target.value)}><option value="">Choose</option>{data.classes.filter(c=>c.id!==classId&&c.isClassTeacher).map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><button disabled={busy||!target} onClick={()=>{if(window.confirm('Move this learner? Earlier records stay with the original class.'))void run(()=>manage(one,'move'));}}>Move learner</button><button disabled={busy} onClick={()=>{if(window.confirm('Mark this learner as having left the class? This keeps their history and can be restored if they have not joined another class.'))void run(()=>manage(one,'leave'));}}>Mark as left class</button></>}
   <button disabled={busy} onClick={()=>void run(async()=>{const r=await supabase.rpc('teacher_get_departed_class_learners',{p_class_id:classId});if(r.error)throw new Error(r.error.message);setDeparted(r.data??[]);setMessage(`${r.data?.length??0} departed learners can be restored.`);})}>Show departed learners</button>{departed.map(l=><p key={l.id}>{l.name} · Left {l.left_at.slice(0,10)} <button disabled={busy} onClick={()=>void run(()=>manage(l.id,'restore'))}>Restore to class</button></p>)}
  </details>}
 </section>;
}
