"use client"

import { useEffect, useMemo, useState } from "react"
import { useRouter } from "next/navigation"
import { hqSupabase } from "@/lib/hq/supabase"

const inputStyle: React.CSSProperties = {width:"100%",boxSizing:"border-box",marginTop:7,padding:"13px 14px",borderRadius:12,border:"1px solid rgba(255,255,255,.12)",background:"rgba(255,255,255,.05)",color:"white",fontSize:15,outline:"none"}

export default function HQAcceptInvitePage(){
  const router=useRouter();const[password,setPassword]=useState("");const[confirmPassword,setConfirmPassword]=useState("");const[showPassword,setShowPassword]=useState(false);const[ready,setReady]=useState(false);const[checking,setChecking]=useState(true);const[loading,setLoading]=useState(false);const[error,setError]=useState("");const[success,setSuccess]=useState("")
  const checks=useMemo(()=>({length:password.length>=12,letter:/[A-Za-z]/.test(password),number:/\d/.test(password),match:password.length>0&&password===confirmPassword}),[password,confirmPassword]);const validPassword=checks.length&&checks.letter&&checks.number&&checks.match
  useEffect(()=>{let mounted=true;async function establish(){try{const url=new URL(window.location.href);const code=url.searchParams.get("code");if(code){const{error:e}=await hqSupabase.auth.exchangeCodeForSession(code);if(e)throw e}else{const hash=new URLSearchParams(window.location.hash.replace(/^#/,""));const a=hash.get("access_token"),r=hash.get("refresh_token"),t=hash.get("type");if(a&&r&&(!t||t==="invite"||t==="signup")){const{error:e}=await hqSupabase.auth.setSession({access_token:a,refresh_token:r});if(e)throw e}}window.history.replaceState({},"",window.location.pathname);const{data,error:userError}=await hqSupabase.auth.getUser();if(!mounted)return;if(userError||!data.user)throw new Error("This HQ invitation is invalid, expired, or already used. Ask the Founder to send a new password setup email.");const{data:access,error:accessError}=await hqSupabase.rpc("hq_check_owner_access",{p_surface:"/hq/accept-invite"});if(accessError||!Boolean((access as{allowed?:boolean}|null)?.allowed))throw new Error("This invitation does not have active VibeSchool HQ authorization.");setReady(true)}catch(e){if(mounted)setError(e instanceof Error?e.message:"The HQ invitation could not be verified.")}finally{if(mounted)setChecking(false)}}void establish();return()=>{mounted=false}},[])
  async function activate(){setError("");if(!ready)return setError("A valid HQ invitation is required.");if(!validPassword)return setError("Use at least 12 characters, including letters and a number, and make sure both passwords match.");setLoading(true);try{const{error:updateError}=await hqSupabase.auth.updateUser({password,data:{hq_password_ready:true}});if(updateError)throw updateError;const{data:sessionData}=await hqSupabase.auth.getSession();const token=sessionData.session?.access_token;if(!token)throw new Error("Password was created but the HQ session expired. Sign in and retry.");const completion=await fetch("/api/hq/complete-password-setup",{method:"POST",headers:{Authorization:`Bearer ${token}`}});const completionBody=await completion.json();if(!completion.ok)throw new Error(completionBody.error||"HQ account status could not be activated.");await hqSupabase.auth.signOut({scope:"local"});setReady(false);setSuccess("HQ Partner/Admin account activated. Your password is ready. You can now sign in to VibeSchool HQ.");window.setTimeout(()=>router.replace("/hq/login?invite=success"),900)}catch(e){setError(e instanceof Error?e.message:"HQ account activation failed.");setLoading(false)}}
  const disabled=checking||!ready||loading||Boolean(success)
  return <main style={{minHeight:"100dvh",display:"grid",placeItems:"center",background:"radial-gradient(circle at top,#10233d 0,#07111f 46%,#040a12 100%)",color:"#f8fafc",padding:"24px 16px",fontFamily:"Inter,system-ui,sans-serif"}}><section style={{width:"100%",maxWidth:440,border:"1px solid rgba(255,255,255,.1)",borderRadius:24,padding:"clamp(22px,6vw,34px)",background:"rgba(7,17,31,.88)"}}><div style={{fontSize:11,fontWeight:950,letterSpacing:".13em",color:"#34d399",textTransform:"uppercase",marginBottom:10}}>VibeSchool HQ invitation</div><h1>Create your HQ password</h1><p style={{fontSize:13,lineHeight:1.6,color:"rgba(255,255,255,.52)"}}>Choose your own password. The Founder cannot see it. HQ becomes Active only after password setup completes successfully.</p>{checking&&<div role="status">Verifying HQ invitation…</div>}{error&&<div role="alert" style={{color:"#fecaca",marginBottom:12}}>{error}</div>}{success&&<div role="status" style={{color:"#bbf7d0",marginBottom:12}}>{success}</div>}<div><label htmlFor="invite-password">Create password</label><button type="button" onClick={()=>setShowPassword(v=>!v)} disabled={disabled} style={{float:"right"}}>{showPassword?"Hide":"Show"}</button></div><input id="invite-password" value={password} onChange={e=>setPassword(e.target.value)} type={showPassword?"text":"password"} autoComplete="new-password" minLength={12} disabled={disabled} style={{...inputStyle,marginBottom:14}}/><label htmlFor="invite-password-confirm">Confirm password</label><input id="invite-password-confirm" value={confirmPassword} onChange={e=>setConfirmPassword(e.target.value)} onKeyDown={e=>{if(e.key==="Enter"&&!disabled&&validPassword)void activate()}} type={showPassword?"text":"password"} autoComplete="new-password" minLength={12} disabled={disabled} style={{...inputStyle,marginBottom:14}}/><div style={{fontSize:11,marginBottom:18}}>{checks.length?"✓":"○"} 12+ characters · {checks.letter?"✓":"○"} letters · {checks.number?"✓":"○"} number · {checks.match?"✓":"○"} match</div><button disabled={disabled||!validPassword} onClick={()=>void activate()} style={{width:"100%",padding:14,borderRadius:12}}>{loading?"Activating HQ access…":"Create password & activate"}</button></section></main>
}
