"use client"
import Link from "next/link"
import {useEffect,useMemo,useRef,useState} from "react"
import {workerIdentity} from "@/lib/hq/workforceIdentity"
import {hqSupabase} from "@/lib/hq/supabase"
import styles from "./LiveWorkerEngineMap.module.css"

export type WorkerTruth=Record<string,unknown>
export type CommandSnapshot={generated_at:string;refresh_after_seconds?:number;engine?:Record<string,unknown>;fleet?:Record<string,unknown>;workers:WorkerTruth[]}
type Readiness="ready"|"repair"|"stopped"
type NavigateTarget="Assign"|"Worker Room"|"Evidence"|"Failures"
type SignalTone="warning"|"insight"|"reminder"

type Signal={tone:SignalTone;label:string;headline:string;body:string;action?:NavigateTarget;actionLabel?:string}

const zoneConfig={
 ready:{title:"PROFESSIONALLY READY",plain:"Ready to be assigned",symbol:"✓",className:styles.ready,color:"#22c55e",top:"rgba(22,101,52,.46)"},
 repair:{title:"REPAIR REQUIRED",plain:"Needs repair before trust",symbol:"⚒",className:styles.repair,color:"#f59e0b",top:"rgba(146,91,8,.43)"},
 stopped:{title:"NOT PROFESSIONALLY READY",plain:"Stopped or not cleared",symbol:"×",className:styles.stopped,color:"#94a3b8",top:"rgba(71,85,105,.38)"},
} as const

const GUIDE=[
 {term:"Global Stop",plain:"Emergency brake",meaning:"When it is applied, governed consequential worker actions must stop. It does not erase work or certification."},
 {term:"Runtime",plain:"Permission to actually act",meaning:"L0 / OFF means workers can be inspected and prepared, but autonomous consequential execution is not enabled."},
 {term:"Certified",plain:"Competence proven",meaning:"A certified worker has passed the required proof. Certification alone never grants permission to act."},
 {term:"Working",plain:"Doing assigned work now",meaning:"The worker has an active assignment or execution state. Open the worker to inspect the exact work."},
 {term:"Waiting for review",plain:"Needs another check",meaning:"The worker has reached a governance boundary and is waiting for independent or owner review."},
 {term:"Blocked",plain:"Cannot safely continue",meaning:"Something prevents progress. Open Problems to see the failure or repair path."},
 {term:"Authority",plain:"What the worker is allowed to do",meaning:"Authority stays separate from identity and certification. A worker can be capable but still have zero execution authority."},
]

const field=(row:WorkerTruth,key:string)=>row[key]
const record=(value:unknown):Record<string,unknown>=>{
 if(!value||typeof value!=="object"||Array.isArray(value))return {}
 return Object.fromEntries(Object.entries(value))
}
const isWorkerTruth=(value:unknown):value is WorkerTruth=>Boolean(value&&typeof value==="object"&&!Array.isArray(value))
const isCommandSnapshot=(value:unknown):value is CommandSnapshot=>{
 if(!value||typeof value!=="object"||Array.isArray(value))return false
 const entries=Object.fromEntries(Object.entries(value))
 return typeof entries.generated_at==="string"&&Array.isArray(entries.workers)&&entries.workers.every(isWorkerTruth)
}
function readiness(row:WorkerTruth):Readiness{
 if(field(row,"certification_state")==="CERTIFIED"&&field(row,"qualification_state")==="CERTIFIED"&&!field(row,"legacy_recertification_required"))return "ready"
 if(field(row,"certification_state")==="NEEDS_REPAIR"||field(row,"qualification_state")==="FAILED_QUALIFICATION"||field(row,"certification_state")==="EXPIRED")return "repair"
 return "stopped"
}
const readable=(value:unknown)=>String(value??"—").replaceAll("_"," ")
const date=(value:unknown)=>value?new Date(String(value)).toLocaleString("en-KE"):"—"
const expiry=(value:unknown)=>{if(!value)return null;const days=Math.ceil((new Date(String(value)).getTime()-Date.now())/86400000);return days<0?"Expired":days<=7?`Expires in ${days} day${days===1?"":"s"}`:null}
const operatingLabel=(row:WorkerTruth)=>{const assignment=record(field(row,"assignment"));const value=String(field(row,"operational_state")??assignment.status??"").toLowerCase();if(["working","assigned","in_progress","running"].includes(value))return "Working";if(["waiting_review","waiting_approval","review"].includes(value))return "Waiting for review";if(["blocked","failed"].includes(value))return "Blocked";if(["stopped","suspended","retired"].includes(value))return "Stopped";return "Available"}

export default function LiveWorkerEngineMap({snapshot,workers:legacyWorkers,generatedAt:legacyGeneratedAt,onRefresh,onNavigate}:{snapshot?:CommandSnapshot;workers?:WorkerTruth[];generatedAt?:string;onRefresh?:()=>void;onNavigate?:(target:NavigateTarget)=>void}){
 const[live,setLive]=useState<CommandSnapshot|null>(snapshot??null)
 const[selected,setSelected]=useState<WorkerTruth|null>(null)
 const[guideOpen,setGuideOpen]=useState(false)
 const[plainMode,setPlainMode]=useState(true)
 const closeRef=useRef<HTMLButtonElement>(null)
 const active=snapshot??live
 const workers=useMemo(()=>active?.workers??legacyWorkers??[],[active,legacyWorkers])
 const generatedAt=active?.generated_at??legacyGeneratedAt
 const engine=active?.engine??{}
 const fleet=active?.fleet??{}
 const groups=useMemo(()=>({ready:workers.filter(r=>readiness(r)==="ready"),repair:workers.filter(r=>readiness(r)==="repair"),stopped:workers.filter(r=>readiness(r)==="stopped")}),[workers])
 const laban=useMemo(()=>workers.find(r=>{const key=String(field(r,"worker_key")??"").toLowerCase();return key==="laban"||key.startsWith("laban-")})??null,[workers])
 const working=Number(fleet.working_now??workers.filter(w=>operatingLabel(w)==="Working").length)
 const blocked=Number(fleet.blocked??workers.filter(w=>operatingLabel(w)==="Blocked").length)
 const waiting=Number(fleet.waiting_review??workers.filter(w=>operatingLabel(w)==="Waiting for review").length)
 const expiringSoon=Number(fleet.expiring_soon??0)
 const globalStop=Boolean(engine.global_stop??engine.shadow_global_stop)
 const runtimeEnabled=Boolean(engine.runtime_enabled??engine.runtime_execution_enabled)
 const runtimeLevel=engine.runtime_level??engine.runtime_autonomy_level??0
 const ownerSummary=globalStop?`Your workforce is under the emergency brake. ${working} worker${working===1?" is":"s are"} visible as working, but consequential execution remains stopped by policy.`:runtimeEnabled?`${working} worker${working===1?" is":"s are"} working. ${blocked} blocked and ${waiting} waiting for review.`:`Your digital team is visible and manageable, but autonomous real-world action is OFF. ${working} worker${working===1?" is":"s are"} currently showing active work.`
 const signals=buildSignals({blocked,waiting,expiringSoon,ready:groups.ready.length,total:workers.length,globalStop,runtimeEnabled})
 const go=(target:NavigateTarget)=>{if(onNavigate)onNavigate(target);else window.dispatchEvent(new CustomEvent("workforce:navigate",{detail:target}))}

 useEffect(()=>{if(snapshot){setLive(snapshot);return}let alive=true;const refresh=async()=>{const{data,error}=await hqSupabase.rpc("hq_workforce_get_live_readiness_map");if(alive&&!error&&isCommandSnapshot(data))setLive(data)};void refresh();const timer=window.setInterval(()=>{if(document.visibilityState==="visible")void refresh()},15000);return()=>{alive=false;window.clearInterval(timer)}},[snapshot])
 useEffect(()=>{if(!selected)return;closeRef.current?.focus();const onKey=(e:KeyboardEvent)=>{if(e.key==="Escape")setSelected(null)};window.addEventListener("keydown",onKey);return()=>window.removeEventListener("keydown",onKey)},[selected])

 return <section className={styles.shell} aria-labelledby="worker-engine-map-title">
  <header className={styles.header}><div className={styles.headerRow}><div><div className={styles.eyebrow}>HQ · WORKFORCE</div><h2 id="worker-engine-map-title">FOUNDER WORKFORCE COMMAND CENTRE</h2><p>{plainMode?"See what your digital team is doing, what is safe, what needs attention and what needs you.":"Professional readiness · live work · bounded authority"}</p></div><div className={styles.headerActions}><button type="button" onClick={()=>setPlainMode(v=>!v)}>{plainMode?"Show technical terms":"Use normal language"}</button><button type="button" className={styles.helpButton} onClick={()=>setGuideOpen(v=>!v)} aria-expanded={guideOpen}>? Explain this screen</button></div></div><span className={styles.live}>LIVE SYSTEM VIEW · AUTO-UPDATES</span></header>
  <section className={styles.ownerBrief} aria-label="Owner briefing"><div><small>WHAT THIS MEANS RIGHT NOW</small><strong>{ownerSummary}</strong></div><div className={styles.quickActions}><button type="button" onClick={()=>go("Assign")}>Give work</button><button type="button" onClick={()=>go("Worker Room")}>Open mission room</button><button type="button" onClick={()=>go("Evidence")}>See proof</button><button type="button" onClick={()=>go("Failures")}>Fix problems</button></div></section>
  <section className={styles.signalGrid} aria-label="Warnings insights and reminders">{signals.map(signal=><SignalCard key={signal.tone} signal={signal} onNavigate={go}/>)}</section>
  {guideOpen&&<section className={styles.guide} aria-label="Worker Engine manual"><div className={styles.guideTop}><div><small>PLAIN-LANGUAGE GUIDE</small><h3>What the Worker Engine is telling you</h3><p>You do not need to understand the engineering words first. This guide translates them into normal decisions.</p></div><button type="button" onClick={()=>setGuideOpen(false)}>Close</button></div><div className={styles.guideGrid}>{GUIDE.map(item=><article key={item.term}><strong>{item.plain}</strong><span>{item.term}</span><p>{item.meaning}</p></article>)}</div></section>}
  <section className={styles.commandStrip} aria-label="Fleet command state"><Truth label={plainMode?"Emergency brake":"Global Stop"} value={globalStop?"ON — WORK HELD":"OFF"} tone={globalStop?"safe":"danger"} hint={plainMode?"When ON, consequential worker actions stay stopped.":undefined}/><Truth label={plainMode?"Permission to act":"Runtime"} value={runtimeEnabled?`ON · LEVEL ${runtimeLevel}`:"OFF — SAFE"} tone={runtimeEnabled?"warn":"safe"} hint={plainMode?"OFF means workers cannot autonomously take consequential action.":undefined}/><Truth label={plainMode?"Doing work now":"Working now"} value={working}/><Truth label={plainMode?"Cannot continue":"Blocked"} value={blocked} tone={blocked?"danger":"safe"}/><Truth label={plainMode?"Needs a check":"Waiting for review"} value={waiting} tone={waiting?"warn":"safe"}/><Truth label={plainMode?"Proof expiring soon":"Expiring ≤7d"} value={expiringSoon} tone={expiringSoon?"warn":"safe"}/></section>
  <section className={styles.labanCommand} aria-label="Laban command"><div className={styles.labanMark}>L</div><div className={styles.labanCopy}><small>COMMAND LAYER</small><h3>Laban</h3>{laban?<LabanSummary row={laban} plainMode={plainMode}/>:<><strong>No live Laban worker row is being reported here.</strong><p>That does not mean Laban does not exist. It means this view will not invent a mission. Open the mission room for stored command records.</p></>}</div><div className={styles.labanActions}>{laban&&<button type="button" onClick={()=>setSelected(laban)}>Open Laban</button>}<button type="button" onClick={()=>go("Worker Room")}>Mission room</button></div></section>
  <div className={styles.truthLegend}><span><i className={styles.professional}/>{plainMode?"Can I trust their skill?":"Professional"}</span><span><i className={styles.operational}/>{plainMode?"What are they doing now?":"Operational"}</span><span><i className={styles.authority}/>{plainMode?"What may they actually do?":"Authority"}</span></div>
  <div className={styles.layout}><div className={styles.hubWrap}><button type="button" className={styles.hub} onClick={()=>setGuideOpen(true)} aria-label="Open Worker Engine explanation"><div><strong>Governed<br/>Worker<br/>Engine</strong><span className={styles.gear} aria-hidden>⚙</span><small>{workers.length} DIGITAL WORKERS</small><em>{plainMode?"Tap and I will explain it":"Tap for operating doctrine"}</em></div></button></div>{(Object.keys(zoneConfig) as Readiness[]).map(key=><Zone key={key} kind={key} rows={groups[key]} onSelect={setSelected} plainMode={plainMode}/>)}</div>
  <footer className={styles.footer}>{plainMode?"Reminder: passing a test means a worker has proven skill. It does not automatically give that worker permission to act.":"Certification is competence—not activation. Operational state and authority are shown independently."} Updated {date(generatedAt)}.{onRefresh&&<button onClick={onRefresh}>Refresh now</button>}</footer>
  {selected&&<WorkerDialog row={selected} onClose={()=>setSelected(null)} closeRef={closeRef} onNavigate={go} plainMode={plainMode}/>} 
 </section>
}

function buildSignals({blocked,waiting,expiringSoon,ready,total,globalStop,runtimeEnabled}:{blocked:number;waiting:number;expiringSoon:number;ready:number;total:number;globalStop:boolean;runtimeEnabled:boolean}):Signal[]{
 const warning:Signal=blocked>0?{tone:"warning",label:"WARNING",headline:`${blocked} worker${blocked===1?" is":"s are"} stuck`,body:"They cannot safely continue. This deserves attention before you depend on their work.",action:"Failures",actionLabel:"See what is wrong"}:expiringSoon>0?{tone:"warning",label:"WARNING",headline:`${expiringSoon} worker proof${expiringSoon===1?"":"s"} expire soon`,body:"Their current certification is close to expiring. Re-check them before treating them as ready.",action:"Evidence",actionLabel:"Check proof"}:runtimeEnabled&&!globalStop?{tone:"warning",label:"WARNING",headline:"Workers have permission to take real action",body:"Runtime is on and the emergency brake is not applied. Watch authority and mission scope carefully.",action:"Worker Room",actionLabel:"Inspect missions"}:{tone:"warning",label:"WARNING",headline:"No urgent workforce warning",body:"Nothing in this live summary currently demands immediate repair. Keep watching blockers and expiring proof."}
 const insight:Signal={tone:"insight",label:"INSIGHT",headline:`${ready} of ${total} workers are professionally ready`,body:ready===total&&total>0?"Your visible team has passed its competence checks. That still does not mean every worker has authority to act.":"Some workers still need repair, certification or clearance before you should rely on them.",action:"Evidence",actionLabel:"See why"}
 const reminder:Signal=globalStop?{tone:"reminder",label:"REMINDER",headline:"The emergency brake is protecting you",body:"Workers may still appear busy or have assignments, but consequential execution is held by policy."}:!runtimeEnabled?{tone:"reminder",label:"REMINDER",headline:"Autonomous real-world action is still off",body:"You can inspect, assign and prepare workers without giving them broad permission to execute consequential actions."}:waiting>0?{tone:"reminder",label:"REMINDER",headline:`${waiting} item${waiting===1?" needs":"s need"} human or independent review`,body:"A review checkpoint is a deliberate safety boundary. Do not treat waiting work as completed."}:{tone:"reminder",label:"REMINDER",headline:"Skill, work and permission are three different things",body:"Always read competence, current activity and authority separately before trusting a worker action."}
 return [warning,insight,reminder]
}

function SignalCard({signal,onNavigate}:{signal:Signal;onNavigate:(target:NavigateTarget)=>void}){return <article className={`${styles.signalCard} ${styles[signal.tone]}`}><div className={styles.signalTop}><span>{signal.label}</span><i aria-hidden>{signal.tone==="warning"?"!":signal.tone==="insight"?"✦":"•"}</i></div><strong>{signal.headline}</strong><p>{signal.body}</p>{signal.action&&<button type="button" onClick={()=>onNavigate(signal.action!)}>{signal.actionLabel??"Open"}</button>}</article>}
function LabanSummary({row,plainMode}:{row:WorkerTruth;plainMode:boolean}){const assignment=record(field(row,"assignment"));return <><strong>{String(field(row,"mission")??assignment.title??"No mission title reported")}</strong><p>{plainMode?`Laban is ${operatingLabel(row).toLowerCase()}. Open the mission room to see what he has been given, what he handed off and what proof exists.`:`${readable(field(row,"operational_state"))} · ${readable(field(row,"certification_state"))} · ${readable(field(row,"qualification_state"))}`}</p></>}
function Truth({label,value,tone="neutral",hint}:{label:string;value:unknown;tone?:"neutral"|"safe"|"warn"|"danger";hint?:string}){return <div className={`${styles.truth} ${styles[tone]}`} title={hint}><small>{label}</small><strong>{String(value)}</strong>{hint&&<em>{hint}</em>}</div>}
function Zone({kind,rows,onSelect,plainMode}:{kind:Readiness;rows:WorkerTruth[];onSelect:(row:WorkerTruth)=>void;plainMode:boolean}){const config=zoneConfig[kind];return <section className={`${styles.zone} ${config.className}`} style={{"--zone-border":`${config.color}88`,"--zone-text":config.color,"--zone-top":config.top} as React.CSSProperties} aria-label={`${config.title}, ${rows.length} workers`}><header className={styles.zoneHeader}><span aria-hidden>{config.symbol}</span><div><h3>{plainMode?config.plain.toUpperCase():config.title} — {rows.length}</h3>{plainMode&&<small>{kind==="ready"?"Competence checks passed":kind==="repair"?"Do not depend on these yet":"Not available for normal trusted work"}</small>}</div></header><div className={styles.list}>{rows.length?rows.map(row=>{const identity=workerIdentity(String(field(row,"worker_key")??""),String(field(row,"title")??"")),warn=expiry(field(row,"expires_at")),authority=record(field(row,"authority"));return <button className={styles.worker} key={String(field(row,"worker_key")??identity.key)} onClick={()=>onSelect(row)} aria-label={`Open ${identity.name}, ${String(field(row,"title")??identity.role)}`}><span className={styles.avatar}>{identity.name.slice(0,1)}</span><span className={styles.copy}><strong>{identity.name}</strong><small>{identity.role} · {String(field(row,"department_key")??"—")}</small><em>{plainMode?operatingLabel(row):readable(field(row,"operational_state"))} · {plainMode?`permission level ${String(authority.runtime_level??0)}`:`L${String(authority.runtime_level??0)}`}{warn?` · ${warn}`:""}</em></span><span className={styles.risk}>{String(field(row,"risk_class")??"—")}</span></button>}):<div className={styles.empty}>No workers in this state.</div>}</div></section>}
function WorkerDialog({row,onClose,closeRef,onNavigate,plainMode}:{row:WorkerTruth;onClose:()=>void;closeRef:React.RefObject<HTMLButtonElement>;onNavigate:(target:NavigateTarget)=>void;plainMode:boolean}){const identity=workerIdentity(String(field(row,"worker_key")??""),String(field(row,"title")??"")),warn=expiry(field(row,"expires_at")),assessment=record(field(row,"assessment")),authority=record(field(row,"authority")),assignment=record(field(row,"assignment"));const go=(target:NavigateTarget)=>{onClose();onNavigate(target)};const repairAction=field(row,"repair_action");const latestFailure=record(field(row,"latest_failure"));return <div className={styles.modalLayer} role="presentation" onMouseDown={e=>{if(e.target===e.currentTarget)onClose()}}><section className={styles.modal} role="dialog" aria-modal="true" aria-labelledby="worker-readiness-title"><div className={styles.modalTop}><div><div className={styles.eyebrow}>{plainMode?"WORKER STATUS":"GOVERNED WORKER"}</div><h3 id="worker-readiness-title">{identity.name}</h3><p>{String(field(row,"mission")??identity.purpose)}</p></div><button ref={closeRef} className={styles.close} onClick={onClose} aria-label="Close worker details">×</button></div>
 <div className={styles.nowCard}><small>{plainMode?"WHAT IS HAPPENING":"OPERATIONAL STATE"}</small><strong>{operatingLabel(row)}</strong><p>{plainMode?plainStatusExplanation(operatingLabel(row),row):readable(field(row,"operational_state"))}</p></div>
 <div className={styles.tripleTruth}><Truth label={plainMode?"Has proven skill":"Professional"} value={field(row,"certification_state")==="CERTIFIED"?"YES — CERTIFIED":readable(field(row,"certification_state"))} tone={field(row,"certification_state")==="CERTIFIED"?"safe":field(row,"certification_state")==="NEEDS_REPAIR"?"warn":"danger"}/><Truth label={plainMode?"What they are doing":"Operational"} value={operatingLabel(row)} tone={operatingLabel(row)==="Blocked"?"danger":"neutral"}/><Truth label={plainMode?"Permission to act":"Authority"} value={plainMode?`LEVEL ${String(authority.runtime_level??0)} · RISK ${String(authority.risk_limit??0)}`:`L${String(authority.runtime_level??0)} · R${String(authority.risk_limit??0)}`} tone={Number(authority.runtime_level??0)>0?"warn":"safe"}/></div>{warn&&<div className={styles.warning} role="status">Reminder: {warn}. This worker needs independent recertification before you keep treating them as ready.</div>}
 {Object.keys(assignment).length>0&&<Panel title={plainMode?"What this worker is doing":"Current assignment"}><strong>{String(assignment.title??"Assigned work")}</strong><p>{readable(assignment.status)} · priority {readable(assignment.priority)} · updated {date(assignment.updated_at)}</p></Panel>}<Panel title={plainMode?"Why HQ is showing this status":"Why this state"}><p>{String(repairAction??assessment.summary??assessment.decision??`${String(field(row,"evidence_count")??0)} proof records support the current status.`)}</p>{Object.keys(latestFailure).length>0&&<p className={styles.failure}>Latest problem: {readable(latestFailure.severity)} · {readable(latestFailure.root_cause)} · {date(latestFailure.detected_at)}</p>}</Panel><Panel title={plainMode?"What this worker is actually allowed to do":"Boundaries"}><p>{String(authority.active_grants??0)} active permissions. Capabilities: {Array.isArray(authority.capabilities)?authority.capabilities.map(String).join(", ")||"none":"none"}. A worker name or certification never grants permission by itself.</p></Panel>
 <details className={styles.technicalDetails}><summary>{plainMode?"Show engineering details":"Technical identity"}</summary><div className={styles.facts}><Fact label="Technical worker" value={field(row,"worker_key")}/><Fact label="Department" value={field(row,"department_key")}/><Fact label="Qualification" value={field(row,"qualification_state")}/><Fact label="Registry state" value={field(row,"registry_status")}/><Fact label="Risk class" value={field(row,"risk_class")}/><Fact label="Global Stop applies" value={authority.global_stop_applies?"Yes":"No"}/><Fact label="Certification evidence" value={`${String(field(row,"evidence_count")??0)} records`}/><Fact label="Expires" value={date(field(row,"expires_at"))}/></div></details>
 <div className={styles.actions}><button onClick={()=>go("Assign")}>Give Work</button><button onClick={()=>go("Worker Room")}>Mission Room</button><button onClick={()=>go("Evidence")}>See Proof</button>{repairAction&&<button onClick={()=>go("Failures")}>Fix This Problem</button>}<Link href="/hq/workforce/readiness">Full Readiness Evidence</Link></div></section></div>}
function plainStatusExplanation(status:string,row:WorkerTruth){const assignment=record(field(row,"assignment"));if(status==="Working")return assignment.title?`This worker is actively handling “${String(assignment.title)}”.`:"This worker is actively handling governed work.";if(status==="Waiting for review")return "The worker has reached a checkpoint. Someone else must check the work before it safely moves forward.";if(status==="Blocked")return "The worker cannot safely continue. Open Fix problems to see what is stopping it.";if(status==="Stopped")return "This worker is not available for normal work right now.";return "This worker is available, but being available does not mean automatic permission to act."}
function Panel({title,children}:{title:string;children:React.ReactNode}){return <section className={styles.panel}><h4>{title}</h4>{children}</section>}
function Fact({label,value}:{label:string;value:unknown}){return <div className={styles.fact}><small>{label}</small><strong>{readable(value)}</strong></div>}
