"use client"
import Link from "next/link"
import {useEffect,useMemo,useRef,useState} from "react"
import {workerIdentity} from "@/lib/hq/workforceIdentity"
import {hqSupabase} from "@/lib/hq/supabase"
import styles from "./LiveWorkerEngineMap.module.css"
export type WorkerTruth=Record<string,any>
export type CommandSnapshot={generated_at:string;refresh_after_seconds?:number;engine?:Record<string,any>;fleet?:Record<string,any>;workers:WorkerTruth[]}
type Readiness="ready"|"repair"|"stopped"
type NavigateTarget="Assign"|"Worker Room"|"Evidence"|"Failures"
const zoneConfig={ready:{title:"PROFESSIONALLY READY",plain:"Ready to be assigned",symbol:"✓",className:styles.ready,color:"#22c55e",top:"rgba(22,101,52,.46)"},repair:{title:"REPAIR REQUIRED",plain:"Needs repair before trust",symbol:"⚒",className:styles.repair,color:"#f59e0b",top:"rgba(146,91,8,.43)"},stopped:{title:"NOT PROFESSIONALLY READY",plain:"Stopped or not cleared",symbol:"×",className:styles.stopped,color:"#94a3b8",top:"rgba(71,85,105,.38)"}} as const
const GUIDE=[
 {term:"Global Stop",plain:"Emergency brake",meaning:"When it is applied, governed consequential worker actions must stop. It does not erase work or certification."},
 {term:"Runtime",plain:"Permission to actually act",meaning:"L0 / OFF means workers can be inspected and prepared, but autonomous consequential execution is not enabled."},
 {term:"Certified",plain:"Competence proven",meaning:"A certified worker has passed the required proof. Certification alone never grants permission to act."},
 {term:"Working",plain:"Doing assigned work now",meaning:"The worker has an active assignment or execution state. Open the worker to inspect the exact work."},
 {term:"Waiting for review",plain:"Needs another check",meaning:"The worker has reached a governance boundary and is waiting for independent or owner review."},
 {term:"Blocked",plain:"Cannot safely continue",meaning:"Something prevents progress. Open Problems to see the failure or repair path."},
 {term:"Authority",plain:"What the worker is allowed to do",meaning:"Authority stays separate from identity and certification. A worker can be capable but still have zero execution authority."},
]
function readiness(row:WorkerTruth):Readiness{if(row.certification_state==="CERTIFIED"&&row.qualification_state==="CERTIFIED"&&!row.legacy_recertification_required)return "ready";if(row.certification_state==="NEEDS_REPAIR"||row.qualification_state==="FAILED_QUALIFICATION"||row.certification_state==="EXPIRED")return "repair";return "stopped"}
const readable=(value:unknown)=>String(value??"—").replaceAll("_"," ")
const date=(value:unknown)=>value?new Date(String(value)).toLocaleString("en-KE"):"—"
const expiry=(value:unknown)=>{if(!value)return null;const days=Math.ceil((new Date(String(value)).getTime()-Date.now())/86400000);return days<0?"Expired":days<=7?`Expires in ${days} day${days===1?"":"s"}`:null}
const operatingLabel=(row:WorkerTruth)=>{const value=String(row.operational_state??row.assignment?.status??"").toLowerCase();if(["working","assigned","in_progress","running"].includes(value))return "Working";if(["waiting_review","waiting_approval","review"].includes(value))return "Waiting for review";if(["blocked","failed"].includes(value))return "Blocked";if(["stopped","suspended","retired"].includes(value))return "Stopped";return "Available"}
export default function LiveWorkerEngineMap({snapshot,workers:legacyWorkers,generatedAt:legacyGeneratedAt,onRefresh,onNavigate}:{snapshot?:CommandSnapshot;workers?:WorkerTruth[];generatedAt?:string;onRefresh?:()=>void;onNavigate?:(target:NavigateTarget)=>void}){
 const[live,setLive]=useState<CommandSnapshot|null>(snapshot??null);const[selected,setSelected]=useState<WorkerTruth|null>(null);const[guideOpen,setGuideOpen]=useState(false);const[plainMode,setPlainMode]=useState(true);const closeRef=useRef<HTMLButtonElement>(null);const active=snapshot??live;const workers=useMemo(()=>active?.workers??legacyWorkers??[],[active,legacyWorkers]),generatedAt=active?.generated_at??legacyGeneratedAt,engine=active?.engine??{},fleet=active?.fleet??{};const groups=useMemo(()=>({ready:workers.filter(r=>readiness(r)==="ready"),repair:workers.filter(r=>readiness(r)==="repair"),stopped:workers.filter(r=>readiness(r)==="stopped")}),[workers])
 const laban=useMemo(()=>workers.find(r=>String(r.worker_key??"").toLowerCase()==="laban"||String(r.worker_key??"").toLowerCase().startsWith("laban-"))??null,[workers])
 const working=Number(fleet.working_now??workers.filter(w=>operatingLabel(w)==="Working").length),blocked=Number(fleet.blocked??workers.filter(w=>operatingLabel(w)==="Blocked").length),waiting=Number(fleet.waiting_review??workers.filter(w=>operatingLabel(w)==="Waiting for review").length)
 const globalStop=Boolean(engine.global_stop??engine.shadow_global_stop);const runtimeEnabled=Boolean(engine.runtime_enabled??engine.runtime_execution_enabled);const runtimeLevel=engine.runtime_level??engine.runtime_autonomy_level??0
 const ownerSummary=globalStop?`Your workforce is under the emergency brake. ${working} worker${working===1?" is":"s are"} visible as working, but consequential execution remains stopped by policy.`:runtimeEnabled?`${working} worker${working===1?" is":"s are"} working. ${blocked} blocked and ${waiting} waiting for review.`:`The workforce is visible and governable, but autonomous consequential execution is OFF. ${working} worker${working===1?" is":"s are"} currently showing active work.`
 const go=(target:NavigateTarget)=>{if(onNavigate)onNavigate(target);else window.dispatchEvent(new CustomEvent("workforce:navigate",{detail:target}))}
 useEffect(()=>{if(snapshot){setLive(snapshot);return}let alive=true;const refresh=async()=>{const{data,error}=await(hqSupabase as any).rpc("hq_workforce_get_live_readiness_map");if(alive&&!error&&data)setLive(data as CommandSnapshot)};void refresh();const timer=window.setInterval(()=>{if(document.visibilityState==="visible")void refresh()},15000);return()=>{alive=false;window.clearInterval(timer)}},[snapshot])
 useEffect(()=>{if(!selected)return;closeRef.current?.focus();const onKey=(e:KeyboardEvent)=>{if(e.key==="Escape")setSelected(null)};window.addEventListener("keydown",onKey);return()=>window.removeEventListener("keydown",onKey)},[selected])
 return <section className={styles.shell} aria-labelledby="worker-engine-map-title"><header className={styles.header}><div className={styles.headerRow}><div><div className={styles.eyebrow}>HQ · WORKFORCE</div><h2 id="worker-engine-map-title">FOUNDER WORKFORCE COMMAND CENTRE</h2><p>{plainMode?"See what your digital team is doing, what is safe, what is blocked and what needs you.":"Professional readiness · live work · bounded authority"}</p></div><div className={styles.headerActions}><button type="button" onClick={()=>setPlainMode(v=>!v)}>{plainMode?"Show technical terms":"Use simple language"}</button><button type="button" className={styles.helpButton} onClick={()=>setGuideOpen(v=>!v)} aria-expanded={guideOpen}>? Worker manual</button></div></div><span className={styles.live}>PRODUCTION TRUTH · AUTO-UPDATES</span></header>
 <section className={styles.ownerBrief} aria-label="Owner briefing"><div><small>WHAT THIS MEANS NOW</small><strong>{ownerSummary}</strong></div><div className={styles.quickActions}><button type="button" onClick={()=>go("Assign")}>Assign work</button><button type="button" onClick={()=>go("Worker Room")}>Mission room</button><button type="button" onClick={()=>go("Evidence")}>See proof</button><button type="button" onClick={()=>go("Failures")}>Problems & repair</button></div></section>
 {guideOpen&&<section className={styles.guide} aria-label="Worker Engine manual"><div className={styles.guideTop}><div><small>OWNER MANUAL</small><h3>The Worker Engine in normal language</h3><p>You do not need to remember engineering vocabulary. Each technical signal below is translated into what it means for you.</p></div><button type="button" onClick={()=>setGuideOpen(false)}>Close</button></div><div className={styles.guideGrid}>{GUIDE.map(item=><article key={item.term}><strong>{item.term}</strong><span>{item.plain}</span><p>{item.meaning}</p></article>)}</div></section>}
 <section className={styles.commandStrip} aria-label="Fleet command state"><Truth label={plainMode?"Emergency brake":"Global Stop"} value={globalStop?"APPLIED":"NOT APPLIED"} tone={globalStop?"safe":"danger"} hint={plainMode?"Applied means consequential worker actions stay stopped.":undefined}/><Truth label={plainMode?"Real action permission":"Runtime"} value={runtimeEnabled?`L${runtimeLevel} · R${engine.max_risk??"—"}`:"L0 · OFF"} tone={runtimeEnabled?"warn":"safe"} hint={plainMode?"OFF means no autonomous consequential execution.":undefined}/><Truth label="Working now" value={working}/><Truth label="Blocked" value={blocked} tone={blocked?"danger":"safe"}/><Truth label="Waiting for review" value={waiting} tone={waiting?"warn":"safe"}/><Truth label={plainMode?"Certification expiring":"Expiring ≤7d"} value={fleet.expiring_soon??0} tone={fleet.expiring_soon?"warn":"safe"}/></section>
 <section className={styles.labanCommand} aria-label="Laban command"><div className={styles.labanMark}>L</div><div className={styles.labanCopy}><small>COMMAND LAYER</small><h3>Laban</h3>{laban?<><strong>{laban.mission||laban.assignment?.title||"No mission title reported"}</strong><p>{plainMode?`Laban is ${operatingLabel(laban).toLowerCase()}. Open the mission room to inspect his assignment, handoffs and evidence.`:`${readable(laban.operational_state)} · ${readable(laban.certification_state)} · ${readable(laban.qualification_state)}`}</p></>:<><strong>Command architecture is not projected as a worker row in this snapshot.</strong><p>This screen will not invent a mission. Use Mission room for stored assignments and command records.</p></>}</div><div className={styles.labanActions}>{laban&&<button type="button" onClick={()=>setSelected(laban)}>Open Laban</button>}<button type="button" onClick={()=>go("Worker Room")}>Open mission room</button></div></section>
 <div className={styles.truthLegend}><span><i className={styles.professional}/>{plainMode?"Can we trust their competence?":"Professional"}</span><span><i className={styles.operational}/>{plainMode?"What are they doing now?":"Operational"}</span><span><i className={styles.authority}/>{plainMode?"What are they allowed to do?":"Authority"}</span></div>
 <div className={styles.layout}><div className={styles.hubWrap}><button type="button" className={styles.hub} onClick={()=>setGuideOpen(true)} aria-label="Open Worker Engine manual"><div><strong>Governed<br/>Worker<br/>Engine</strong><span className={styles.gear} aria-hidden>⚙</span><small>{workers.length} TECHNICAL WORKERS</small><em>{plainMode?"Tap to understand the engine":"Tap for operating doctrine"}</em></div></button></div>{(Object.keys(zoneConfig) as Readiness[]).map(key=><Zone key={key} kind={key} rows={groups[key]} onSelect={setSelected} plainMode={plainMode}/>)}</div>
 <footer className={styles.footer}>{plainMode?"Being certified means a worker has proven competence. It does not automatically give permission to act.":"Certification is competence—not activation. Operational state and authority are shown independently."} Updated {date(generatedAt)}.{onRefresh&&<button onClick={onRefresh}>Refresh now</button>}</footer>{selected&&<WorkerDialog row={selected} onClose={()=>setSelected(null)} closeRef={closeRef} onNavigate={go} plainMode={plainMode}/>}</section>
}
function Truth({label,value,tone="neutral",hint}:{label:string;value:unknown;tone?:"neutral"|"safe"|"warn"|"danger";hint?:string}){return <div className={`${styles.truth} ${styles[tone]}`} title={hint}><small>{label}</small><strong>{String(value)}</strong>{hint&&<em>{hint}</em>}</div>}
function Zone({kind,rows,onSelect,plainMode}:{kind:Readiness;rows:WorkerTruth[];onSelect:(row:WorkerTruth)=>void;plainMode:boolean}){const config=zoneConfig[kind];return <section className={`${styles.zone} ${config.className}`} style={{"--zone-border":`${config.color}88`,"--zone-text":config.color,"--zone-top":config.top} as React.CSSProperties} aria-label={`${config.title}, ${rows.length} workers`}><header className={styles.zoneHeader}><span aria-hidden>{config.symbol}</span><div><h3>{config.title} — {rows.length}</h3>{plainMode&&<small>{config.plain}</small>}</div></header><div className={styles.list}>{rows.length?rows.map(row=>{const identity=workerIdentity(row.worker_key,row.title),warn=expiry(row.expires_at);return <button className={styles.worker} key={row.worker_key} onClick={()=>onSelect(row)} aria-label={`Open ${identity.name}, ${row.title}`}><span className={styles.avatar}>{identity.name.slice(0,1)}</span><span className={styles.copy}><strong>{identity.name}</strong><small>{identity.role} · {row.department_key}</small><em>{plainMode?operatingLabel(row):readable(row.operational_state)} · L{row.authority?.runtime_level??0}{warn?` · ${warn}`:""}</em></span><span className={styles.risk}>{row.risk_class??"—"}</span></button>}):<div className={styles.empty}>No workers in this state.</div>}</div></section>}
function WorkerDialog({row,onClose,closeRef,onNavigate,plainMode}:{row:WorkerTruth;onClose:()=>void;closeRef:React.RefObject<HTMLButtonElement>;onNavigate:(target:NavigateTarget)=>void;plainMode:boolean}){const identity=workerIdentity(row.worker_key,row.title),warn=expiry(row.expires_at),assessment=row.assessment??{},authority=row.authority??{};const go=(target:NavigateTarget)=>{onClose();onNavigate(target)};return <div className={styles.modalLayer} role="presentation" onMouseDown={e=>{if(e.target===e.currentTarget)onClose()}}><section className={styles.modal} role="dialog" aria-modal="true" aria-labelledby="worker-readiness-title"><div className={styles.modalTop}><div><div className={styles.eyebrow}>{plainMode?"WORKER STATUS":"GOVERNED WORKER"}</div><h3 id="worker-readiness-title">{identity.name}</h3><p>{row.mission||identity.purpose}</p></div><button ref={closeRef} className={styles.close} onClick={onClose} aria-label="Close worker details">×</button></div>
 <div className={styles.nowCard}><small>{plainMode?"WHAT IS HAPPENING":"OPERATIONAL STATE"}</small><strong>{operatingLabel(row)}</strong><p>{plainMode?plainStatusExplanation(operatingLabel(row),row):readable(row.operational_state)}</p></div>
 <div className={styles.tripleTruth}><Truth label={plainMode?"Competence":"Professional"} value={readable(row.certification_state)} tone={row.certification_state==="CERTIFIED"?"safe":row.certification_state==="NEEDS_REPAIR"?"warn":"danger"}/><Truth label={plainMode?"Current activity":"Operational"} value={operatingLabel(row)} tone={operatingLabel(row)==="Blocked"?"danger":"neutral"}/><Truth label={plainMode?"Action permission":"Authority"} value={`L${authority.runtime_level??0} · R${authority.risk_limit??0}`} tone={(authority.runtime_level??0)>0?"warn":"safe"}/></div>{warn&&<div className={styles.warning} role="status">{warn}. Independent recertification is required before continued readiness.</div>}
 {row.assignment&&<Panel title={plainMode?"What this worker is doing":"Current assignment"}><strong>{row.assignment.title}</strong><p>{readable(row.assignment.status)} · priority {readable(row.assignment.priority)} · updated {date(row.assignment.updated_at)}</p></Panel>}<Panel title={plainMode?"Why HQ shows this status":"Why this state"}><p>{row.repair_action||assessment.summary||assessment.decision||`${row.evidence_count??0} certification evidence records support the current state.`}</p>{row.latest_failure&&<p className={styles.failure}>Latest issue: {readable(row.latest_failure.severity)} · {readable(row.latest_failure.root_cause)} · {date(row.latest_failure.detected_at)}</p>}</Panel><Panel title={plainMode?"What this worker may do":"Boundaries"}><p>{authority.active_grants??0} active grants. Capabilities: {(authority.capabilities??[]).join(", ")||"none"}. A worker name or certification never grants authority by itself.</p></Panel>
 <details className={styles.technicalDetails}><summary>{plainMode?"Show technical details":"Technical identity"}</summary><div className={styles.facts}><Fact label="Technical worker" value={row.worker_key}/><Fact label="Department" value={row.department_key}/><Fact label="Qualification" value={row.qualification_state}/><Fact label="Registry state" value={row.registry_status}/><Fact label="Risk class" value={row.risk_class}/><Fact label="Global Stop applies" value={authority.global_stop_applies?"Yes":"No"}/><Fact label="Certification evidence" value={`${row.evidence_count??0} records`}/><Fact label="Expires" value={date(row.expires_at)}/></div></details>
 <div className={styles.actions}><button onClick={()=>go("Assign")}>Assign Work</button><button onClick={()=>go("Worker Room")}>Mission Room</button><button onClick={()=>go("Evidence")}>View Proof</button>{row.repair_action&&<button onClick={()=>go("Failures")}>Open Repair Plan</button>}<Link href="/hq/workforce/readiness">Commissioning Evidence</Link></div></section></div>}
function plainStatusExplanation(status:string,row:WorkerTruth){if(status==="Working")return row.assignment?.title?`This worker is actively handling “${row.assignment.title}”.`:"This worker is actively handling governed work.";if(status==="Waiting for review")return "The worker has reached a checkpoint and should not silently pass it without the required review.";if(status==="Blocked")return "The worker cannot safely continue. Open Problems & repair to inspect the blocker.";if(status==="Stopped")return "This worker is not available for normal work right now.";return "This worker is available, but availability does not mean automatic permission to act."}
function Panel({title,children}:{title:string;children:React.ReactNode}){return <section className={styles.panel}><h4>{title}</h4>{children}</section>}
function Fact({label,value}:{label:string;value:unknown}){return <div className={styles.fact}><small>{label}</small><strong>{readable(value)}</strong></div>}
