"use client"
export const dynamic="force-dynamic"

import {useCallback,useEffect,useMemo,useState} from "react"
import {supabase} from "@/lib/supabase"
import {HQPage,HQPanel,HQ_THEME as C,hqButtonStyle} from "@/components/hq/HQShell"

type Obj=Record<string,any>
type Snapshot={generated_at:string;engine:Obj|null;counts:Obj;workers:Obj[];jobs:Obj[];shadow_candidates:Obj[];shadow_runs:Obj[];decisions:Obj[];skills:Obj[];authority:Obj[];evidence:Obj[];failures:{anomalies:Obj[];dead_letters:Obj[]};resources:Obj[]}
type Tab="Overview"|"Workers"|"Jobs"|"Shadow Runs"|"Decisions"|"Skills"|"Authority"|"Evidence"|"Failures"|"Resources"
const sb=supabase as any
const tabs:Tab[]=["Overview","Workers","Jobs","Shadow Runs","Decisions","Skills","Authority","Evidence","Failures","Resources"]
const yes=(v:any)=>v===true
const tone=(kind:string)=>kind==="bad"?C.red:kind==="warn"?C.amber:kind==="good"?C.green:C.blue
const when=(v:any)=>v?new Date(String(v)).toLocaleString("en-KE"):"—"
const short=(v:any,n=90)=>{const s=typeof v==="string"?v:JSON.stringify(v??{});return s.length>n?s.slice(0,n)+"…":s}

function Badge({children,kind="info"}:{children:any;kind?:"info"|"good"|"warn"|"bad"}){return <span style={{display:"inline-flex",alignItems:"center",minHeight:24,padding:"0 8px",borderRadius:999,border:`1px solid ${tone(kind)}44`,background:`${tone(kind)}12`,color:tone(kind),fontSize:10,fontWeight:900}}>{children}</span>}
function Metric({label,value,kind="info"}:{label:string;value:any;kind?:"info"|"good"|"warn"|"bad"}){return <div style={{padding:13,border:`1px solid ${C.border}`,borderRadius:14,background:C.panelSoft}}><div style={{fontSize:22,fontWeight:950,color:tone(kind)}}>{String(value??0)}</div><div style={{marginTop:4,fontSize:10.5,color:C.muted}}>{label}</div></div>}
function Rows({items,render}:{items:Obj[];render:(x:Obj)=>React.ReactNode}){return <div style={{display:"grid",gap:8}}>{items.length?items.map((x,i)=><div key={String(x.id??x.trace_id??x.worker_key??x.skill_key??i)} style={{padding:12,borderBottom:i===items.length-1?"none":`1px solid ${C.border}`}}>{render(x)}</div>):<div style={{padding:24,textAlign:"center",fontSize:11.5,color:C.muted}}>No records.</div>}</div>}

export default function WorkerEngineControlRoom(){
 const[data,setData]=useState<Snapshot|null>(null);const[tab,setTab]=useState<Tab>("Overview");const[loading,setLoading]=useState(true);const[error,setError]=useState("")
 const load=useCallback(async()=>{setLoading(true);setError("");try{const{data,error}=await sb.rpc("hq_workforce_get_control_room_snapshot",{p_recent_limit:50});if(error)throw error;setData(data as Snapshot)}catch(e){setError(e instanceof Error?e.message:"Worker Engine Control Room could not be loaded.")}finally{setLoading(false)}},[])
 useEffect(()=>{void load()},[load])
 const e=data?.engine??{}
 const safety=useMemo(()=>({runtimeOff:!yes(e.runtime_execution_enabled)&&Number(e.runtime_autonomy_level??0)===0,shadowStopped:!yes(e.shadow_enabled)&&!yes(e.shadow_scheduler_enabled)&&yes(e.shadow_global_stop),factoryOff:!yes(e.factory_enabled),heartbeatOff:!yes(e.heartbeat_enabled)}),[e])
 async function review(id:string,state:"approved"|"rejected"|"revise"){const rationale=window.prompt(state==="approved"?"Optional review rationale":"Review rationale")??"";if(state!=="approved"&&!rationale.trim())return;setError("");const{error}=await sb.rpc("hq_workforce_owner_review_shadow_decision",{p_decision_id:id,p_state:state,p_rationale:rationale||null});if(error){setError(error.message);return}await load()}
 return <HQPage title="Worker Engine Control Room" description="Governed digital workforce · observe, explain and review before any consequential authority" actions={<button onClick={()=>void load()} disabled={loading} style={hqButtonStyle}>{loading?"Refreshing…":"Refresh"}</button>}>
  {error&&<div role="alert" style={{marginBottom:12,padding:12,border:"1px solid rgba(251,113,133,.3)",borderRadius:11,background:"rgba(251,113,133,.08)",color:"#fecdd3",fontSize:11.5}}>{error}</div>}
  <div style={{display:"flex",gap:6,overflowX:"auto",paddingBottom:10}}>{tabs.map(t=><button key={t} onClick={()=>setTab(t)} style={{...hqButtonStyle,minHeight:34,whiteSpace:"nowrap",color:tab===t?C.green:C.muted,borderColor:tab===t?`${C.green}55`:C.border}}>{t}</button>)}</div>
  {!data?<HQPanel><div style={{padding:28,color:C.muted,fontSize:12}}>{loading?"Loading governed runtime state…":"No control-room snapshot available."}</div></HQPanel>:<>
   {tab==="Overview"&&<div style={{display:"grid",gap:12}}>
    <section style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(130px,1fr))",gap:8}}><Metric label="Workers" value={data.counts.workers}/><Metric label="Active workers" value={data.counts.active_workers}/><Metric label="Open work" value={data.counts.open_work_items}/><Metric label="Shadow candidates" value={data.counts.shadow_candidates}/><Metric label="Review decisions" value={data.counts.decisions_waiting} kind={Number(data.counts.decisions_waiting)>0?"warn":"good"}/><Metric label="Open anomalies" value={data.counts.open_anomalies} kind={Number(data.counts.open_anomalies)>0?"bad":"good"}/></section>
    <HQPanel title="Safety kernel" description="A green boundary means the production executor is still structurally disabled."><div style={{padding:14,display:"flex",gap:8,flexWrap:"wrap"}}><Badge kind={safety.runtimeOff?"good":"bad"}>Runtime {safety.runtimeOff?"L0 / OFF":"ACTIVE"}</Badge><Badge kind={safety.shadowStopped?"good":"bad"}>Shadow {safety.shadowStopped?"STOPPED":"ENABLED"}</Badge><Badge kind={safety.factoryOff?"good":"bad"}>Factory {safety.factoryOff?"OFF":"ON"}</Badge><Badge kind={safety.heartbeatOff?"good":"bad"}>Heartbeat {safety.heartbeatOff?"OFF":"ON"}</Badge><Badge kind={yes(e.shadow_anomaly_paused)?"warn":"good"}>Anomaly pause {yes(e.shadow_anomaly_paused)?"ON":"clear"}</Badge></div><div style={{padding:"0 14px 14px",fontSize:10.5,color:C.muted}}>Autonomy L{String(e.runtime_autonomy_level??0)} · max risk R{String(e.runtime_max_risk??0)} · snapshot {when(data.generated_at)}</div></HQPanel>
    <HQPanel title="Certification posture" description="Shadow authority remains zero until explicitly promoted through owner gates."><div style={{padding:14,display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(150px,1fr))",gap:8}}><Metric label="Certified skills" value={data.counts.certified_skills}/><Metric label="Shadow-capable skills" value={data.counts.shadow_capable_skills}/><Metric label="Authority denials" value={data.counts.authority_denials}/><Metric label="Dead letters" value={data.counts.dead_letters} kind={Number(data.counts.dead_letters)>0?"warn":"good"}/></div></HQPanel>
   </div>}
   {tab==="Workers"&&<HQPanel title="Workers" description="Identity, lane and current lifecycle."><Rows items={data.workers} render={x=><><div style={{display:"flex",gap:7,alignItems:"center",flexWrap:"wrap"}}><strong style={{fontSize:12.5}}>{x.title}</strong><Badge kind={x.status==="active"?"good":x.status==="suspended"?"bad":"warn"}>{x.status}</Badge><Badge>{x.department_key}</Badge></div><div style={{marginTop:5,fontSize:10.5,color:C.muted}}>{x.worker_key} · {x.reasoning_mode} · paid AI {x.paid_ai_allowed?"allowed":"off"} · {when(x.updated_at)}</div></>}/></HQPanel>}
   {tab==="Jobs"&&<HQPanel title="Detected operational work" description="Source work remains unchanged by Shadow Mode."><Rows items={data.jobs} render={x=><><div style={{display:"flex",gap:7,alignItems:"center",flexWrap:"wrap"}}><strong style={{fontSize:12}}>{x.title}</strong><Badge kind={x.priority==="critical"?"bad":x.priority==="high"?"warn":"info"}>{x.priority}</Badge><Badge>{x.status}</Badge></div><div style={{marginTop:5,fontSize:10.5,color:C.muted}}>{x.department_key} · {x.work_type} · due {when(x.due_at)}</div></>}/></HQPanel>}
   {tab==="Shadow Runs"&&<div style={{display:"grid",gap:12}}><HQPanel title="Candidate queue" description="Deduplicated observations before recommendation."><Rows items={data.shadow_candidates} render={x=><><div style={{display:"flex",gap:7,flexWrap:"wrap"}}><Badge>{x.lane_key}</Badge><Badge kind={x.status==="escalated"?"warn":"info"}>{x.status}</Badge><strong style={{fontSize:11.5}}>Priority {x.priority}</strong></div><div style={{marginTop:6,fontSize:10.5,color:C.muted}}>{short(x.reasoning_summary)} · confidence {x.confidence??"—"}</div></>}/></HQPanel><HQPanel title="Trace runs" description="Every consequential recommendation must remain reconstructable end-to-end."><Rows items={data.shadow_runs} render={x=><><div style={{display:"flex",gap:7,flexWrap:"wrap"}}><strong style={{fontSize:11.5}}>{x.trace_id}</strong><Badge>{x.status}</Badge>{x.consequential_action_performed?<Badge kind="bad">CONSEQUENTIAL WRITE</Badge>:<Badge kind="good">No production action</Badge>}</div><div style={{marginTop:5,fontSize:10.5,color:C.muted}}>{x.worker_key} · {x.lane_key??"—"} · {x.scope_type} · {when(x.started_at)}</div></>}/></HQPanel></div>}
   {tab==="Decisions"&&<HQPanel title="Shadow Decision Inbox" description="Approve means judgment agreement only; it does not authorize execution."><Rows items={data.decisions} render={x=><><div style={{display:"flex",gap:7,alignItems:"center",flexWrap:"wrap"}}><strong style={{fontSize:12}}>{x.decision_key}</strong><Badge kind={x.hypothetical_authority_result==="deny"?"bad":x.hypothetical_authority_result==="escalate"?"warn":"good"}>{x.hypothetical_authority_result}</Badge><Badge>{x.state}</Badge></div><div style={{marginTop:6,fontSize:11}}>{short(x.proposed_action,130)}</div><div style={{marginTop:5,fontSize:10.5,color:C.muted}}>{x.authority_reason} · trace {x.trace_id}</div>{["proposed","awaiting_review","revise"].includes(x.state)&&<div style={{display:"flex",gap:6,marginTop:9,flexWrap:"wrap"}}><button onClick={()=>void review(x.id,"approved")} style={{...hqButtonStyle,minHeight:32,color:C.green}}>Approve judgment</button><button onClick={()=>void review(x.id,"revise")} style={{...hqButtonStyle,minHeight:32,color:C.violet}}>Revise</button><button onClick={()=>void review(x.id,"rejected")} style={{...hqButtonStyle,minHeight:32,color:C.red}}>Reject</button></div>}</>}/></HQPanel>}
   {tab==="Skills"&&<HQPanel title="Skill Registry" description="Uncertified skill = zero autonomous execution authority."><Rows items={data.skills} render={x=><><div style={{display:"flex",gap:7,flexWrap:"wrap",alignItems:"center"}}><strong style={{fontSize:12}}>{x.skill_key}@{x.version}</strong><Badge kind={x.certification_status==="certified"?"good":x.certification_status==="revoked"?"bad":"warn"}>{x.certification_status}</Badge><Badge kind={x.shadow_capable?"good":"info"}>{x.shadow_capable?"shadow capable":"not shadow capable"}</Badge><Badge>R{x.risk_class} · L{x.autonomy_required}</Badge></div><div style={{marginTop:5,fontSize:10.5,color:C.muted}}>Attempts ≤ {x.max_attempts} · runtime ≤ {x.max_runtime_ms} ms · expires {when(x.expires_at)}</div></>}/></HQPanel>}
   {tab==="Authority"&&<HQPanel title="Authority decisions" description="Allowed and denied requests with scope and reason."><Rows items={data.authority} render={x=><><div style={{display:"flex",gap:7,flexWrap:"wrap"}}><Badge kind={x.decision==="deny"?"bad":"good"}>{x.decision}</Badge><strong style={{fontSize:11.5}}>{x.worker_key}</strong><Badge>{x.skill_key}</Badge><Badge>R{x.risk_class} · L{x.autonomy_level}</Badge></div><div style={{marginTop:5,fontSize:10.5,color:C.muted}}>{x.reason_code} · {x.scope_type} · {when(x.occurred_at)}</div></>}/></HQPanel>}
   {tab==="Evidence"&&<HQPanel title="Evidence & provenance" description="Inputs, outputs, verification and classification linked to trace IDs."><Rows items={data.evidence} render={x=><><div style={{display:"flex",gap:7,flexWrap:"wrap"}}><Badge>{x.evidence_kind}</Badge><Badge kind={String(x.classification).includes("sensitive")?"warn":"info"}>{x.classification}</Badge><strong style={{fontSize:11}}>{x.source_type}</strong></div><div style={{marginTop:5,fontSize:10.5,color:C.muted}}>Trace {x.trace_id} · source {x.source_ref??"—"} · {when(x.created_at)}</div></>}/></HQPanel>}
   {tab==="Failures"&&<div style={{display:"grid",gap:12}}><HQPanel title="Shadow anomalies"><Rows items={data.failures.anomalies} render={x=><><div style={{display:"flex",gap:7,flexWrap:"wrap"}}><Badge kind={x.severity==="critical"?"bad":"warn"}>{x.severity}</Badge><Badge>{x.action}</Badge><strong style={{fontSize:11.5}}>{x.anomaly_key}</strong></div><div style={{marginTop:5,fontSize:10.5,color:C.muted}}>{short(x.details)} · {when(x.created_at)}</div></>}/></HQPanel><HQPanel title="Dead-letter work"><Rows items={data.failures.dead_letters} render={x=><><strong style={{fontSize:11.5}}>{x.error_code}</strong><div style={{marginTop:5,fontSize:10.5,color:C.muted}}>{x.worker_key} · attempts {x.attempts} · {short(x.error_detail)}</div></>}/></HQPanel></div>}
   {tab==="Resources"&&<HQPanel title="Resource governance" description="Cycles, recommendations, retries, denials and escalations against bounded windows."><Rows items={data.resources} render={x=><><div style={{display:"flex",gap:7,flexWrap:"wrap"}}><Badge>{x.resource_kind}</Badge><strong style={{fontSize:11.5}}>{x.amount} {x.unit}</strong>{x.worker_key&&<Badge>{x.worker_key}</Badge>}</div><div style={{marginTop:5,fontSize:10.5,color:C.muted}}>Window {when(x.window_started_at)} · recorded {when(x.recorded_at)}</div></>}/></HQPanel>}
  </>}
 </HQPage>
}
