"use client"
export const dynamic="force-dynamic"

import {useCallback,useEffect,useMemo,useState} from "react"
import {supabase} from "@/lib/supabase"
import {HQPage,HQPanel,HQ_THEME as C,hqButtonStyle} from "@/components/hq/HQShell"

type Obj=Record<string,any>
type Core={generated_at:string;engine:Obj|null;counts:Obj;workers:Obj[];jobs:Obj[];shadow_candidates:Obj[];shadow_runs:Obj[];decisions:Obj[];skills:Obj[];authority:Obj[];evidence:Obj[];failures:{anomalies:Obj[];dead_letters:Obj[]};resources:Obj[]}
type Intel={generated_at:string;counts:Obj;architecture:Obj[];resources:Obj[];competencies:Obj[];objectives:Obj[];plans:Obj[];collaborations:Obj[];skill_candidates:Obj[];calibration:Obj[];memory:Obj[];factory_recommendations:Obj[]}
type Tab="Overview"|"Objectives"|"Plans"|"Resources"|"Competencies"|"Collaboration"|"Learning"|"Architecture"|"Workers"|"Shadow"|"Decisions"|"Evidence"|"Failures"
const sb=supabase as any
const tabs:Tab[]=["Overview","Objectives","Plans","Resources","Competencies","Collaboration","Learning","Architecture","Workers","Shadow","Decisions","Evidence","Failures"]
const yes=(v:any)=>v===true
const tone=(k:string)=>k==="bad"?C.red:k==="warn"?C.amber:k==="good"?C.green:C.blue
const when=(v:any)=>v?new Date(String(v)).toLocaleString("en-KE"):"—"
const short=(v:any,n=150)=>{const s=typeof v==="string"?v:JSON.stringify(v??{});return s.length>n?s.slice(0,n)+"…":s}
function Badge({children,kind="info"}:{children:any;kind?:"info"|"good"|"warn"|"bad"}){return <span style={{display:"inline-flex",alignItems:"center",minHeight:24,padding:"0 8px",borderRadius:999,border:`1px solid ${tone(kind)}44`,background:`${tone(kind)}12`,color:tone(kind),fontSize:10,fontWeight:900}}>{children}</span>}
function Metric({label,value,kind="info"}:{label:string;value:any;kind?:"info"|"good"|"warn"|"bad"}){return <div style={{padding:13,border:`1px solid ${C.border}`,borderRadius:14,background:C.panelSoft}}><div style={{fontSize:22,fontWeight:950,color:tone(kind)}}>{String(value??0)}</div><div style={{marginTop:4,fontSize:10.5,color:C.muted}}>{label}</div></div>}
function Rows({items,render}:{items:Obj[];render:(x:Obj)=>React.ReactNode}){return <div style={{display:"grid",gap:8}}>{items.length?items.map((x,i)=><div key={String(x.id??x.trace_id??x.worker_key??x.component_key??x.memory_key??x.dimension_key??i)} style={{padding:12,borderBottom:i===items.length-1?"none":`1px solid ${C.border}`}}>{render(x)}</div>):<div style={{padding:24,textAlign:"center",fontSize:11.5,color:C.muted}}>No records.</div>}</div>}

export default function WorkerEngineControlRoom(){
 const[core,setCore]=useState<Core|null>(null);const[intel,setIntel]=useState<Intel|null>(null);const[tab,setTab]=useState<Tab>("Overview");const[loading,setLoading]=useState(true);const[error,setError]=useState("")
 const load=useCallback(async()=>{setLoading(true);setError("");try{const[a,b]=await Promise.all([sb.rpc("hq_workforce_get_control_room_snapshot",{p_recent_limit:50}),sb.rpc("hq_workforce_get_intelligence_snapshot",{p_recent_limit:50})]);if(a.error)throw a.error;if(b.error)throw b.error;setCore(a.data as Core);setIntel(b.data as Intel)}catch(e){setError(e instanceof Error?e.message:"Worker Engine Control Room could not be loaded.")}finally{setLoading(false)}},[])
 useEffect(()=>{void load()},[load])
 const e=core?.engine??{}
 const safety=useMemo(()=>({runtimeOff:!yes(e.runtime_execution_enabled)&&Number(e.runtime_autonomy_level??0)===0,factoryOff:!yes(e.factory_enabled),heartbeatOff:!yes(e.heartbeat_enabled),shadow:yes(e.shadow_enabled)&&yes(e.shadow_scheduler_enabled)&&!yes(e.shadow_global_stop)}),[e])
 async function review(id:string,state:"approved"|"rejected"|"revise"){const rationale=window.prompt(state==="approved"?"Optional review rationale":"Review rationale")??"";if(state!=="approved"&&!rationale.trim())return;const{error}=await sb.rpc("hq_workforce_owner_review_shadow_decision",{p_decision_id:id,p_state:state,p_rationale:rationale||null});if(error){setError(error.message);return}await load()}
 return <HQPage title="Worker Engine Control Room" description="Global Capability Intelligence Fabric · objective-first planning, evidence, governance and measurable Shadow operations" actions={<button onClick={()=>void load()} disabled={loading} style={hqButtonStyle}>{loading?"Refreshing…":"Refresh"}</button>}>
  {error&&<div role="alert" style={{marginBottom:12,padding:12,border:`1px solid ${C.red}55`,borderRadius:11,color:C.red,fontSize:11.5}}>{error}</div>}
  <div style={{display:"flex",gap:6,overflowX:"auto",paddingBottom:10}}>{tabs.map(t=><button key={t} onClick={()=>setTab(t)} style={{...hqButtonStyle,minHeight:34,whiteSpace:"nowrap",color:tab===t?C.green:C.muted,borderColor:tab===t?`${C.green}55`:C.border}}>{t}</button>)}</div>
  {!core||!intel?<HQPanel><div style={{padding:28,color:C.muted,fontSize:12}}>{loading?"Loading governed intelligence state…":"No snapshot available."}</div></HQPanel>:<>
   {tab==="Overview"&&<div style={{display:"grid",gap:12}}>
    <section style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(130px,1fr))",gap:8}}><Metric label="Open work" value={core.counts.open_work_items}/><Metric label="Objectives" value={intel.counts.objectives}/><Metric label="Plans" value={intel.counts.plans}/><Metric label="Registered resources" value={intel.counts.resources}/><Metric label="Certified competencies" value={intel.counts.certified_competencies}/><Metric label="Review decisions" value={core.counts.decisions_waiting} kind={Number(core.counts.decisions_waiting)>0?"warn":"good"}/></section>
    <HQPanel title="Safety & authority boundary" description="Intelligence may expand; consequential authority may not silently expand."><div style={{padding:14,display:"flex",gap:8,flexWrap:"wrap"}}><Badge kind={safety.runtimeOff?"good":"bad"}>Runtime {safety.runtimeOff?"L0 / OFF":"ACTIVE"}</Badge><Badge kind={safety.shadow?"good":"warn"}>Shadow {safety.shadow?"OBSERVING":"STOPPED"}</Badge><Badge kind={safety.factoryOff?"good":"bad"}>Factory {safety.factoryOff?"OFF":"ON"}</Badge><Badge kind={safety.heartbeatOff?"good":"bad"}>Legacy heartbeat {safety.heartbeatOff?"OFF":"ON"}</Badge><Badge kind={yes(e.shadow_anomaly_paused)?"warn":"good"}>Anomaly {yes(e.shadow_anomaly_paused)?"PAUSED":"clear"}</Badge></div></HQPanel>
    <HQPanel title="Canonical intelligence posture" description="One architecture: objectives → competencies → capabilities → resources → plan → evidence → decision."><div style={{padding:14,display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(150px,1fr))",gap:8}}><Metric label="Canonical components" value={intel.counts.canonical_components} kind="good"/><Metric label="Superseded legacy" value={intel.counts.superseded_components}/><Metric label="Skill candidates" value={intel.counts.skill_candidates}/><Metric label="Evaluations" value={intel.counts.evaluations}/><Metric label="Memory records" value={intel.counts.memories}/><Metric label="Factory recommendations" value={intel.counts.factory_recommendations} kind="warn"/></div></HQPanel>
   </div>}
   {tab==="Objectives"&&<HQPanel title="Objectives" description="Primary intelligence objects; jobs are subordinate implementation units."><Rows items={intel.objectives} render={x=><><div style={{display:"flex",gap:7,flexWrap:"wrap"}}><strong>{x.statement}</strong><Badge>{x.status}</Badge><Badge>R{x.risk_ceiling} · L{x.autonomy_ceiling}</Badge></div><div style={{marginTop:6,fontSize:10.5,color:C.muted}}>{x.objective_key} · competencies {short(x.required_competencies)} · {x.scope_type}/{x.jurisdiction}</div></>}/></HQPanel>}
   {tab==="Plans"&&<HQPanel title="Planning Graphs" description="Least-powerful sufficient strategies and their auditable capability steps."><Rows items={intel.plans} render={x=>{const p=x.plan??{};const steps=x.steps??[];return <><div style={{display:"flex",gap:7,flexWrap:"wrap"}}><strong>{p.strategy_key}</strong><Badge kind={p.status==="recommended"?"good":"info"}>{p.status}</Badge><Badge>R{p.required_risk} · L{p.required_autonomy}</Badge><Badge>confidence {p.confidence??"—"}</Badge></div><div style={{marginTop:6,fontSize:10.5,color:C.muted}}>quality {p.expected_quality??"—"} · cost {p.estimated_cost} · latency {p.estimated_latency_ms} ms</div><div style={{marginTop:7,display:"grid",gap:5}}>{steps.map((s:Obj)=><div key={s.id} style={{padding:8,border:`1px solid ${C.border}`,borderRadius:9,fontSize:10.5}}>{s.ordinal}. {s.step_key} · {s.worker_key??"unassigned"} · {short(s.required_competencies,80)}</div>)}</div></>}}/></HQPanel>}
   {tab==="Resources"&&<HQPanel title="Global Resource Registry" description="Resources are chosen by trust, health, authority, risk, cost and latency—not hidden availability."><Rows items={intel.resources} render={x=><><div style={{display:"flex",gap:7,flexWrap:"wrap"}}><strong>{x.display_name}</strong><Badge kind={x.enabled&&x.shadow_capable?"good":"warn"}>{x.health_status}</Badge><Badge>{x.resource_type}</Badge><Badge>trust {x.trust_tier}/5</Badge><Badge>R{x.risk_class} · L{x.required_autonomy}</Badge></div><div style={{marginTop:5,fontSize:10.5,color:C.muted}}>{x.resource_key}@{x.version} · operations {short(x.allowed_operations)}</div></>}/></HQPanel>}
   {tab==="Competencies"&&<HQPanel title="Competency Graph" description="Workers are routed by certified multidimensional competence rather than department equality."><Rows items={intel.competencies} render={x=><><div style={{display:"flex",gap:7,flexWrap:"wrap"}}><strong>{x.worker_key}</strong><Badge kind={x.certification_status==="certified"?"good":"warn"}>{x.certification_status}</Badge><Badge>{x.competency_key}</Badge></div><div style={{marginTop:5,fontSize:10.5,color:C.muted}}>proficiency {x.proficiency} · reliability {x.reliability??"unmeasured"} · expires {when(x.expires_at)}</div></>}/></HQPanel>}
   {tab==="Collaboration"&&<HQPanel title="Cross-worker Collaboration" description="Consultation and handoff share traces but never amplify authority."><Rows items={intel.collaborations} render={x=><><div style={{display:"flex",gap:7,flexWrap:"wrap"}}><strong>{x.from_worker_key} → {x.to_worker_key}</strong><Badge>{x.collaboration_type}</Badge><Badge>{x.status}</Badge></div><div style={{marginTop:5,fontSize:10.5,color:C.muted}}>competencies {short(x.requested_competencies)} · authority {short(x.authority_snapshot)}</div></>}/></HQPanel>}
   {tab==="Learning"&&<div style={{display:"grid",gap:12}}><HQPanel title="Skill Genesis" description="The engine may propose missing capability contracts; it may never self-certify them."><Rows items={intel.skill_candidates} render={x=><><div style={{display:"flex",gap:7,flexWrap:"wrap"}}><strong>{x.candidate_key}</strong><Badge>{x.status}</Badge>{x.certification_allowed?<Badge kind="bad">SELF-CERTIFY ENABLED</Badge>:<Badge kind="good">Independent certification required</Badge>}</div><div style={{marginTop:5,fontSize:10.5,color:C.muted}}>{short(x.detected_gap)}</div></>}/></HQPanel><HQPanel title="Empirical Calibration"><Rows items={intel.calibration} render={x=><><strong>{x.dimension_type}:{x.dimension_key}</strong><div style={{marginTop:5,fontSize:10.5,color:C.muted}}>samples {x.sample_count} · predicted {x.mean_predicted??"—"} · observed {x.mean_observed??"—"} · error {x.calibration_error??"—"} · reliability {x.reliability??"—"}</div></>}/></HQPanel><HQPanel title="Organisational Memory"><Rows items={intel.memory} render={x=><><div style={{display:"flex",gap:7,flexWrap:"wrap"}}><strong>{x.memory_key}@{x.version}</strong><Badge>{x.memory_type}</Badge>{x.authoritative&&<Badge kind="good">authoritative</Badge>}{x.contradiction_group&&<Badge kind="warn">contradiction tracked</Badge>}</div><div style={{marginTop:5,fontSize:10.5,color:C.muted}}>confidence {x.confidence} · {x.scope_type} · valid until {when(x.valid_until)}</div></>}/></HQPanel></div>}
   {tab==="Architecture"&&<div style={{display:"grid",gap:12}}><HQPanel title="Canonical / Legacy Reconciliation" description="Historical controls are preserved; inferior intelligence assumptions are explicitly superseded."><Rows items={intel.architecture} render={x=><><div style={{display:"flex",gap:7,flexWrap:"wrap"}}><strong>{x.component_key}</strong><Badge kind={x.canonical?"good":x.disposition==="supersede"?"warn":"info"}>{x.canonical?"CANONICAL":String(x.disposition).toUpperCase()}</Badge><Badge>{x.lineage}</Badge></div><div style={{marginTop:5,fontSize:10.5,color:C.muted}}>{x.rationale}{x.replacement_component_key?` → ${x.replacement_component_key}`:""}</div></>}/></HQPanel><HQPanel title="Factory Recommendation Mode" description="Worker creation is the last diagnosis, never the first reaction to backlog."><Rows items={intel.factory_recommendations} render={x=><><div style={{display:"flex",gap:7,flexWrap:"wrap"}}><strong>{x.diagnosis}</strong><Badge kind={x.worker_creation_recommended?"warn":"good"}>{x.worker_creation_recommended?"worker proposal only":"reuse/repair first"}</Badge><Badge>{x.status}</Badge></div><div style={{marginTop:5,fontSize:10.5,color:C.muted}}>{short(x.proposed_action)} · evidence {short(x.evidence)}</div></>}/></HQPanel></div>}
   {tab==="Workers"&&<HQPanel title="Workers"><Rows items={core.workers} render={x=><><div style={{display:"flex",gap:7,flexWrap:"wrap"}}><strong>{x.title}</strong><Badge kind={x.status==="active"?"good":"warn"}>{x.status}</Badge><Badge>{x.department_key}</Badge></div><div style={{marginTop:5,fontSize:10.5,color:C.muted}}>{x.worker_key} · {x.reasoning_mode}</div></>}/></HQPanel>}
   {tab==="Shadow"&&<div style={{display:"grid",gap:12}}><HQPanel title="Candidates"><Rows items={core.shadow_candidates} render={x=><><div style={{display:"flex",gap:7,flexWrap:"wrap"}}><Badge>{x.lane_key}</Badge><Badge>{x.status}</Badge><strong>Priority {x.priority}</strong></div><div style={{marginTop:5,fontSize:10.5,color:C.muted}}>{short(x.reasoning_summary)} · worker {x.worker_key??"unassigned"}</div></>}/></HQPanel><HQPanel title="Operational Traces"><Rows items={core.shadow_runs} render={x=><><div style={{display:"flex",gap:7,flexWrap:"wrap"}}><strong>{x.trace_id}</strong><Badge>{x.status}</Badge>{x.consequential_action_performed?<Badge kind="bad">CONSEQUENTIAL</Badge>:<Badge kind="good">No production action</Badge>}</div><div style={{marginTop:5,fontSize:10.5,color:C.muted}}>{x.worker_key} · {when(x.started_at)}</div></>}/></HQPanel></div>}
   {tab==="Decisions"&&<HQPanel title="Shadow Decision Inbox" description="Approval records judgment only; execution authority is separate."><Rows items={core.decisions} render={x=><><div style={{display:"flex",gap:7,flexWrap:"wrap"}}><strong>{x.decision_key}</strong><Badge kind={x.hypothetical_authority_result==="deny"?"bad":"good"}>{x.hypothetical_authority_result}</Badge><Badge>{x.state}</Badge></div><div style={{marginTop:6,fontSize:10.5,color:C.muted}}>{short(x.proposed_action)} · {x.authority_reason}</div>{["proposed","awaiting_review","revise"].includes(x.state)&&<div style={{display:"flex",gap:6,marginTop:9}}><button onClick={()=>void review(x.id,"approved")} style={{...hqButtonStyle,color:C.green}}>Approve judgment</button><button onClick={()=>void review(x.id,"revise")} style={hqButtonStyle}>Revise</button><button onClick={()=>void review(x.id,"rejected")} style={{...hqButtonStyle,color:C.red}}>Reject</button></div>}</>}/></HQPanel>}
   {tab==="Evidence"&&<HQPanel title="Evidence & Provenance"><Rows items={core.evidence} render={x=><><div style={{display:"flex",gap:7,flexWrap:"wrap"}}><Badge>{x.evidence_kind}</Badge><strong>{x.source_type}</strong><Badge>{x.classification}</Badge></div><div style={{marginTop:5,fontSize:10.5,color:C.muted}}>trace {x.trace_id} · {x.source_ref??"—"} · {when(x.created_at)}</div></>}/></HQPanel>}
   {tab==="Failures"&&<div style={{display:"grid",gap:12}}><HQPanel title="Anomalies"><Rows items={core.failures.anomalies} render={x=><><Badge kind="warn">{x.severity}</Badge> <strong>{x.anomaly_key}</strong><div style={{marginTop:5,fontSize:10.5,color:C.muted}}>{short(x.details)}</div></>}/></HQPanel><HQPanel title="Dead Letters"><Rows items={core.failures.dead_letters} render={x=><><strong>{x.error_code}</strong><div style={{marginTop:5,fontSize:10.5,color:C.muted}}>{x.worker_key} · attempts {x.attempts} · {short(x.error_detail)}</div></>}/></HQPanel></div>}
  </>}
 </HQPage>
}
