"use client"
export const dynamic="force-dynamic"
import {useCallback,useEffect,useMemo,useState} from "react"
import {supabase} from "@/lib/supabase"
import {HQPage,HQPanel,HQ_THEME as C,hqButtonStyle} from "@/components/hq/HQShell"
import {workerIdentity} from "@/lib/hq/workforceIdentity"
import Task15OwnerControls from "./Task15OwnerControls"
import WorkerCommunication from "./WorkerCommunication"
import {AssignmentBoard,CompletionProof,IdentityRegistry,OrganizationView,WorkerDirectory} from "./WorkforceTeam"
type Obj=Record<string,any>
type Snapshot={generated_at:string;engine:Obj|null;counts:Obj;workers:Obj[];jobs:Obj[];shadow_candidates:Obj[];shadow_runs:Obj[];decisions:Obj[];skills:Obj[];authority:Obj[];evidence:Obj[];failures:{anomalies:Obj[];dead_letters:Obj[]};resources:Obj[]}
type TeamSnapshot={assignments:Obj[];collaborations:Obj[];identity_registry:Obj[]}
type Tab="Control Room"|"Team"|"Assign"|"Worker Room"|"Proof"|"Registry"|"Jobs"|"Runs"|"Decisions"|"Skills"|"Authority"|"Evidence"|"Failures"|"Resources"
const sb=supabase as any
const primary:Tab[]=["Control Room","Team","Assign","Worker Room","Proof"]
const secondary:Tab[]=["Registry","Jobs","Runs","Decisions","Skills","Authority","Evidence","Failures","Resources"]
const yes=(v:any)=>v===true,tone=(k:string)=>k==="bad"?C.red:k==="warn"?C.amber:k==="good"?C.green:C.blue,when=(v:any)=>v?new Date(String(v)).toLocaleString("en-KE"):"—",short=(v:any,n=100)=>{const s=typeof v==="string"?v:JSON.stringify(v??{});return s.length>n?s.slice(0,n)+"…":s}
function Badge({children,kind="info"}:{children:React.ReactNode;kind?:string}){return <span style={{display:"inline-flex",padding:"5px 8px",borderRadius:999,border:`1px solid ${tone(kind)}44`,color:tone(kind),fontSize:10,fontWeight:900}}>{children}</span>}
function Metric({label,value,kind="info"}:{label:string;value:any;kind?:string}){return <div style={{padding:13,border:`1px solid ${C.border}`,borderRadius:14,background:C.panelSoft}}><div style={{fontSize:21,fontWeight:950,color:tone(kind)}}>{String(value??0)}</div><div style={{marginTop:4,fontSize:10.5,color:C.muted}}>{label}</div></div>}
function Rows({items,render}:{items:Obj[];render:(x:Obj)=>React.ReactNode}){return <div style={{display:"grid",gap:8}}>{items.length?items.map((x,i)=><div key={String(x.id??x.trace_id??x.worker_key??x.skill_key??i)} style={{padding:12,borderBottom:i===items.length-1?"none":`1px solid ${C.border}`}}>{render(x)}</div>):<div style={{padding:24,textAlign:"center",fontSize:11.5,color:C.muted}}>No records.</div>}</div>}
export default function WorkerEngineControlRoom(){
 const[data,setData]=useState<Snapshot|null>(null),[team,setTeam]=useState<TeamSnapshot>({assignments:[],collaborations:[],identity_registry:[]}),[tab,setTab]=useState<Tab>("Control Room"),[loading,setLoading]=useState(true),[error,setError]=useState(""),[teamLayerAvailable,setTeamLayerAvailable]=useState(true)
 const load=useCallback(async()=>{setLoading(true);setError("");try{const [r,t]=await Promise.all([sb.rpc("hq_workforce_get_control_room_snapshot",{p_recent_limit:100}),sb.rpc("hq_workforce_named_team_snapshot",{p_recent_limit:120})]);if(r.error)throw r.error;setData(r.data as Snapshot);if(t.error){setTeamLayerAvailable(false);setTeam({assignments:[],collaborations:[],identity_registry:[]})}else{setTeamLayerAvailable(true);setTeam((t.data??{assignments:[],collaborations:[],identity_registry:[]}) as TeamSnapshot)}}catch(e){setError(e instanceof Error?e.message:"VibeSchool Workforce could not be loaded.")}finally{setLoading(false)}},[]);useEffect(()=>{void load()},[load])
 const e=data?.engine??{},safety=useMemo(()=>({runtimeOff:!yes(e.runtime_execution_enabled)&&Number(e.runtime_autonomy_level??0)===0,shadowStopped:!yes(e.shadow_enabled)&&!yes(e.shadow_scheduler_enabled)&&yes(e.shadow_global_stop),factoryOff:!yes(e.factory_enabled),heartbeatOff:!yes(e.heartbeat_enabled)}),[e])
 async function review(id:string,state:"approved"|"rejected"|"revise"){const rationale=window.prompt(state==="approved"?"Optional review rationale":"Review rationale")??"";if(state!=="approved"&&!rationale.trim())return;const r=await sb.rpc("hq_workforce_owner_review_shadow_decision",{p_decision_id:id,p_state:state,p_rationale:rationale||null});if(r.error)setError(r.error.message);else await load()}
 return <HQPage title="VibeSchool Workforce" description="Your governed digital team: assign work, see collaboration, inspect proof and intervene only when needed" actions={<button onClick={()=>void load()} disabled={loading} style={hqButtonStyle}>{loading?"Refreshing…":"Refresh"}</button>}>
 {error&&<div role="alert" style={{marginBottom:12,padding:12,border:`1px solid ${C.red}55`,borderRadius:11,color:C.red}}>{error}</div>}
 {!teamLayerAvailable&&<div role="status" style={{marginBottom:12,padding:11,border:`1px solid ${C.amber}55`,borderRadius:11,color:C.amber,fontSize:11}}>Named-team persistence is waiting for its database migration. Existing Worker Engine views remain available; assignment controls stay fail-closed.</div>}
 <nav aria-label="Workforce sections" style={{display:"grid",gridTemplateColumns:"repeat(3,minmax(0,1fr))",gap:6,marginBottom:8}}>{primary.map(t=><button key={t} onClick={()=>setTab(t)} style={{...hqButtonStyle,minHeight:42,padding:"8px 6px",color:tab===t?C.green:C.muted}}>{t}</button>)}</nav>
 <select aria-label="More workforce sections" value={secondary.includes(tab)?tab:""} onChange={e=>{if(e.target.value)setTab(e.target.value as Tab)}} style={{width:"100%",minHeight:40,marginBottom:12,border:`1px solid ${C.border}`,borderRadius:10,background:C.panelSoft,color:C.muted,padding:"0 10px"}}><option value="">More: registry, technical evidence and controls</option>{secondary.map(t=><option key={t} value={t}>{t}</option>)}</select>
 {!data?<HQPanel><div style={{padding:28,color:C.muted}}>{loading?"Loading governed workforce state…":"No snapshot available."}</div></HQPanel>:<>
 {tab==="Control Room"&&<div style={{display:"grid",gap:12}}><Task15OwnerControls/><section style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(130px,1fr))",gap:8}}><Metric label="Team identities" value={11}/><Metric label="Governed workers" value={data.counts.workers}/><Metric label="Active assignments" value={team.assignments.filter(a=>!["completed","cancelled"].includes(a.status)).length}/><Metric label="Review decisions" value={data.counts.decisions_waiting} kind={Number(data.counts.decisions_waiting)>0?"warn":"good"}/><Metric label="Open anomalies" value={data.counts.open_anomalies} kind={Number(data.counts.open_anomalies)>0?"bad":"good"}/></section><HQPanel title="Safety kernel"><div style={{padding:14,display:"flex",gap:8,flexWrap:"wrap"}}><Badge kind={safety.runtimeOff?"good":"bad"}>Runtime {safety.runtimeOff?"L0 / OFF":"ACTIVE"}</Badge><Badge kind={safety.shadowStopped?"good":"bad"}>Shadow {safety.shadowStopped?"STOPPED":"ENABLED"}</Badge><Badge kind={safety.factoryOff?"good":"bad"}>Factory {safety.factoryOff?"OFF":"ON"}</Badge><Badge kind={safety.heartbeatOff?"good":"bad"}>Heartbeat {safety.heartbeatOff?"OFF":"ON"}</Badge></div></HQPanel><OrganizationView workers={data.workers}/></div>}
 {tab==="Team"&&<WorkerDirectory workers={data.workers} jobs={data.jobs} assignments={team.assignments} collaborations={team.collaborations} authority={data.authority} evidence={data.evidence} decisions={data.decisions} failures={data.failures}/>} 
 {tab==="Assign"&&(teamLayerAvailable?<AssignmentBoard workers={data.workers} jobs={data.jobs} assignments={team.assignments} onRefresh={load} onError={setError}/>:<HQPanel title="Assignments unavailable"><div style={{padding:20,color:C.amber}}>The named-team persistence migration has not reached this environment. Assignment is intentionally disabled rather than stored unreliably.</div></HQPanel>)}
 {tab==="Worker Room"&&<WorkerCommunication workers={data.workers} jobs={data.jobs} shadowRuns={data.shadow_runs} decisions={data.decisions} authority={data.authority} evidence={data.evidence} collaborations={team.collaborations} assignments={team.assignments}/>} 
 {tab==="Proof"&&<CompletionProof assignments={team.assignments} evidence={data.evidence} collaborations={team.collaborations}/>} 
 {tab==="Registry"&&<IdentityRegistry workers={data.workers}/>} 
 {tab==="Jobs"&&<HQPanel title="Operational work"><Rows items={data.jobs} render={x=>{const key=String(x.route??"").startsWith("worker:")?String(x.route).slice(7):null;const id=key?workerIdentity(key):null;return <><strong>{x.title}</strong> <Badge>{x.status}</Badge><div style={{fontSize:10.5,color:C.muted}}>{id?`${id.name} · `:""}{x.department_key} · {x.work_type} · due {when(x.due_at)}</div></>}}/></HQPanel>}
 {tab==="Runs"&&<HQPanel title="Execution traces"><Rows items={data.shadow_runs} render={x=>{const w=workerIdentity(x.worker_key);return <><strong>{w.name}</strong> <Badge>{x.status}</Badge>{x.consequential_action_performed?<Badge kind="bad">CONSEQUENTIAL WRITE</Badge>:<Badge kind="good">No production action</Badge>}<div style={{fontSize:10.5,color:C.muted}}>Trace {x.trace_id} · {x.worker_key} · {when(x.started_at)}</div></>}}/></HQPanel>}
 {tab==="Decisions"&&<HQPanel title="Decision Inbox" description="Approve is judgment agreement, not execution authority."><Rows items={data.decisions} render={x=><><strong>{x.decision_key}</strong> <Badge>{x.state}</Badge><div style={{fontSize:11}}>{short(x.proposed_action,130)}</div>{["proposed","awaiting_review","revise"].includes(x.state)&&<div style={{display:"flex",gap:6,marginTop:8,flexWrap:"wrap"}}><button onClick={()=>void review(x.id,"approved")} style={hqButtonStyle}>Approve judgment</button><button onClick={()=>void review(x.id,"rejected")} style={hqButtonStyle}>Reject</button></div>}</>}/></HQPanel>}
 {tab==="Skills"&&<HQPanel title="Skill Registry"><Rows items={data.skills} render={x=><><strong>{x.skill_key}@{x.version}</strong> <Badge>{x.certification_status}</Badge><div style={{fontSize:10.5,color:C.muted}}>R{x.risk_class} · L{x.autonomy_required}</div></>}/></HQPanel>}
 {tab==="Authority"&&<HQPanel title="Authority decisions"><Rows items={data.authority} render={x=>{const w=workerIdentity(x.worker_key);return <><Badge kind={x.decision==="deny"?"bad":"good"}>{x.decision}</Badge> <strong>{w.name}</strong><div style={{fontSize:10.5,color:C.muted}}>{x.worker_key} · {x.reason_code} · {x.scope_type}</div></>}}/></HQPanel>}
 {tab==="Evidence"&&<HQPanel title="Evidence & provenance"><Rows items={data.evidence} render={x=><><Badge>{x.evidence_kind}</Badge> <strong>{x.source_type}</strong><div style={{fontSize:10.5,color:C.muted}}>Trace {x.trace_id} · {when(x.created_at)}</div></>}/></HQPanel>}
 {tab==="Failures"&&<div style={{display:"grid",gap:12}}><HQPanel title="Shadow anomalies"><Rows items={data.failures.anomalies} render={x=><><Badge kind="warn">{x.severity}</Badge> <strong>{x.anomaly_key}</strong><div style={{fontSize:10.5,color:C.muted}}>{short(x.details)}</div></>}/></HQPanel><HQPanel title="Dead-letter work"><Rows items={data.failures.dead_letters} render={x=>{const w=workerIdentity(x.worker_key);return <><strong>{x.error_code}</strong><div style={{fontSize:10.5,color:C.muted}}>{w.name} ({x.worker_key}) · {short(x.error_detail)}</div></>}}/></HQPanel></div>}
 {tab==="Resources"&&<HQPanel title="Resource governance"><Rows items={data.resources} render={x=><><Badge>{x.resource_kind}</Badge> <strong>{x.amount} {x.unit}</strong><div style={{fontSize:10.5,color:C.muted}}>{when(x.recorded_at)}</div></>}/></HQPanel>}
 </>}
 </HQPage>
}
