import type { Metadata } from "next";
import type { ReactNode } from "react";
import { ReadingAnalyticsTracker } from "@/components/read/ReadingAnalyticsTracker";
import { ReaderListenContinuity } from "@/components/read/ReaderListenContinuity";
import { ReaderContinuityCoordinator } from "@/components/read/ReaderContinuityCoordinator";
import { ReaderStudyInteractions } from "@/components/read/ReaderStudyInteractions";
import { ReaderAnnotationManager } from "@/components/read/ReaderAnnotationManager";
import { ReaderTermExplainer } from "@/components/read/ReaderTermExplainer";
import { ReaderLearningLauncher } from "@/components/read/ReaderLearningLauncher";
import { ReaderAssessmentLauncher } from "@/components/read/ReaderAssessmentLauncher";
import { ReaderPurchaseBar } from "@/components/read/ReaderPurchaseBar";
import { getSupabaseServerClient } from "@/lib/supabaseServer";

const SITE_URL = "https://www.vibeschool.co.ke";
type PublicationMetadata = { id:string; title:string|null; description:string|null; cover_url:string|null; cbc_subject:string|null; cbc_grade:string|null; status:string|null; published_at:string|null; updated_at:string|null };
async function getPublishedPublication(publicationId:string):Promise<PublicationMetadata|null>{try{const supabase=getSupabaseServerClient();const{data}=await supabase.from("vibe_publications").select("id,title,description,cover_url,cbc_subject,cbc_grade,status,published_at,updated_at").eq("id",publicationId).maybeSingle();const p=data as PublicationMetadata|null;return p?.status==="published"?p:null}catch{return null}}
export async function generateMetadata({params}:{params:{publicationId:string}}):Promise<Metadata>{const p=await getPublishedPublication(params.publicationId);if(!p)return{title:"VibeSchool Textbook",robots:{index:false,follow:false}};const title=p.title?.trim()||"VibeSchool Textbook";const description=p.description?.trim()||[p.cbc_grade,p.cbc_subject].filter(Boolean).join(" · ")||"A published educational resource from VibeSchool.";const canonical=`${SITE_URL}/read/textbook/${p.id}`;return{title,description,alternates:{canonical},robots:{index:true,follow:true},openGraph:{type:"book",url:canonical,title,description,siteName:"VibeSchool",locale:"en_KE",...(p.cover_url?{images:[{url:p.cover_url,alt:title}]}:{})}}}
export default async function TextbookReaderLayout({children,params}:{children:ReactNode;params:{publicationId:string}}){const p=await getPublishedPublication(params.publicationId);const title=p?.title?.trim()||"VibeSchool Textbook";const description=p?.description?.trim()||[p?.cbc_grade,p?.cbc_subject].filter(Boolean).join(" · ")||"A published educational resource from VibeSchool.";const canonical=`${SITE_URL}/read/textbook/${params.publicationId}`;const schema=p?{"@context":"https://schema.org","@type":"Book","@id":`${canonical}#book`,name:title,description,url:canonical,inLanguage:"en-KE",publisher:{"@type":"EducationalOrganization",name:"VibeSchool",url:SITE_URL},...(p.cover_url?{image:p.cover_url}:{}),...(p.published_at?{datePublished:p.published_at}:{}),...(p.updated_at?{dateModified:p.updated_at}:{}),...(p.cbc_grade?{educationalLevel:p.cbc_grade}:{}),...(p.cbc_subject?{about:p.cbc_subject}:{}),mainEntityOfPage:{"@type":"WebPage","@id":canonical}}:null;return <div id="vibetextbook-reader-shell" data-reader-mode="read">{schema?<script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(schema)}}/>:null}<ReadingAnalyticsTracker/><ReaderListenContinuity publicationId={params.publicationId}/><div id="vibetextbook-reading-content" tabIndex={-1}><ReaderContinuityCoordinator/><ReaderStudyInteractions/><ReaderTermExplainer/><ReaderAnnotationManager/>{children}</div><ReaderPurchaseBar publicationId={params.publicationId}/><ReaderLearningLauncher/><ReaderAssessmentLauncher/></div>}
