import type { Metadata } from 'next'
import Link from 'next/link'
import { PublicHeader } from '@/components/public/PublicHeader'
import { PublicFooter } from '@/components/public/PublicFooter'

export const metadata: Metadata = { title:'Trust Centre | VibeSchool', description:'Plain-language information about privacy, child safety, security, educational evidence and responsible technology at VibeSchool.' }

const cards=[
['Child safety','Children deserve stronger safeguards, not merely smaller versions of adult accounts. VibeSchool designs learner access, adult relationships and data use around legitimate authority and the learner’s interests.','/trust/child-safety','Read child-safety approach'],
['Privacy','We aim to collect and expose information for a defined educational or operational purpose. Public exploration should not become a route into private learner, family, staff or school information.','/legal/privacy','Read Privacy Policy'],
['Security & authority','A browser choice should never create institutional authority. Sensitive actions should be constrained by authenticated identity, verified role or relationship and server/database enforcement.','/trust/security','Read security approach'],
['Educational evidence','Guidance, incomplete information and verified claims are different things. Consequential catalogue and Pathways information should preserve provenance and avoid silently guessing missing truth.','/pathways','Inspect Pathways evidence'],
['AI & automation','Technology may assist learning and operations, but high-consequence educational or authority decisions need appropriate evidence, safeguards and human responsibility.','/trust/responsible-ai','Read responsible AI approach'],
['Honest product communication','We do not need fabricated adoption numbers, fake vacancies or unsupported credentials to look established. Product maturity and evidence should be represented honestly.','/about','Why VibeSchool exists'],
] as const
export default function TrustPage(){return <div className="page"><PublicHeader product="Trust"/><main id="main-content"><section className="hero"><div className="wrap"><p className="eyebrow">VIBESCHOOL TRUST CENTRE</p><h1>Trust should be understandable before it becomes legal language.</h1><p className="lead">This page explains the principles behind VibeSchool’s approach to learners, data, authority, educational evidence and responsible technology. The formal policies remain available for people who need the full terms.</p></div></section><section className="section wrap"><div className="grid">{cards.map(([t,d,href,action])=><article key={t}><h2>{t}</h2><p>{d}</p><Link href={href}>{action} →</Link></article>)}</div></section><section className="section alt"><div className="wrap two"><div><p className="eyebrow dark">WHEN SOMETHING GOES WRONG</p><h2 className="big">A trustworthy system needs a route for questions and problems.</h2></div><div><p>If you believe information is wrong, an account is unsafe, a learner may be at risk, or VibeSchool is handling information inappropriately, contact us. Account-specific support uses authenticated channels where identity matters; general enquiries can start through the public Contact page.</p><Link className="button" href="/contact">Contact VibeSchool</Link></div></div></section><section className="section wrap"><p className="eyebrow dark">FORMAL POLICIES</p><h2 className="big">Read the underlying rules.</h2><div className="policies"><Link href="/legal/privacy"><strong>Privacy Policy</strong><span>Personal data, rights and handling principles →</span></Link><Link href="/legal/terms"><strong>Terms of Service</strong><span>Rules governing use of VibeSchool →</span></Link><Link href="/legal/aup"><strong>Acceptable Use</strong><span>Safe, respectful and lawful use →</span></Link><Link href="/legal"><strong>Policy hub</strong><span>All current trust and policy documents →</span></Link></div></section><section className="institution"><div className="wrap"><h2>Evaluating VibeSchool for a school, institution or public-sector use?</h2><p>Review the institutional adoption and due-diligence surface before contacting us.</p><Link href="/institutions">For institutions & government →</Link></div></section></main><PublicFooter/><style>{styles}</style></div>}
const styles=`.page{background:#f8f8f5;color:#101827;font-family:var(--font-jakarta),Arial,sans-serif;line-height:1.7}.page *{box-sizing:border-box}.wrap{max-width:1100px;margin:auto}.hero{background:#07111f;color:#fff;padding:90px 24px}.eyebrow{font:850 11px var(--font-mono),monospace;letter-spacing:.15em;color:#d0b154}.eyebrow.dark{color:#755b17}h1,.big{font-family:var(--font-display),Arial,sans-serif;letter-spacing:-.04em;line-height:1.05}h1{font-size:clamp(42px,6vw,70px);max-width:900px;margin:14px 0 24px}.lead{font-size:18px;color:#c6cfda;max-width:780px}.section{padding:84px 24px}.grid{display:grid;grid-template-columns:repeat(2,1fr);gap:14px}.grid article{background:#fff;border:1px solid #e0e3e7;border-radius:14px;padding:28px}.grid h2{font-size:21px;margin:0 0 8px}.grid p,.two p{color:#5d6674}.grid a{font-weight:850;color:#6f5615;text-decoration:none}.alt{background:#eeeae0}.two{display:grid;grid-template-columns:1fr 1fr;gap:65px}.big{font-size:clamp(31px,4.3vw,48px);margin:10px 0}.button{display:inline-flex;margin-top:14px;padding:12px 18px;border-radius:10px;background:#101827;color:#fff;text-decoration:none;font-weight:850}.policies{display:grid;grid-template-columns:repeat(2,1fr);gap:12px}.policies a{display:grid;gap:5px;padding:22px;border:1px solid #dedfe5;border-radius:13px;background:#fff;text-decoration:none;color:#171720}.policies span{font-size:14px;color:#666e79}.institution{background:#13243a;color:#fff;padding:66px 24px}.institution h2{font-size:30px;margin:0}.institution p{color:#c6cfda}.institution a{color:#e2c66e;font-weight:850;text-decoration:none}@media(max-width:700px){.hero,.section{padding:62px 18px}.grid,.two,.policies{grid-template-columns:1fr}.two{gap:18px}}`