import type { Metadata } from 'next'
import Link from 'next/link'
import { PublicHeader } from '@/components/public/PublicHeader'
import { PublicFooter } from '@/components/public/PublicFooter'

export const metadata: Metadata = {
  alternates:{canonical:'/institutions'},
  title:'VibeSchool for Schools | Academics, learning, families and operations connected',
  description:'Explore VibeSchool for Kenyan schools: curriculum, teaching, assessment, learner evidence, families, Pathways and institutional operations connected around the learner.'
}

const workspaces = [
  ['Academics & teaching','Curriculum, schemes, lesson planning, teaching activity, attendance, homework, assessment, reporting and teacher evidence belong to one educational workflow.'],
  ['Learner progress','Learning activity, evidence, assessment and progress can be understood as a continuing learner story rather than isolated end-term marks.'],
  ['Families & communication','Family relationships, learning summaries, messages and school context are designed to connect authorised supporters to the information appropriate to them.'],
  ['School operations','Institutional architecture spans school identity, staff, finance, payments, resources and operational records while preserving role boundaries.'],
  ['Senior School Pathways','Pathways, tracks, subject combinations, careers and school offerings connect future-direction decisions to evidence and learner context.'],
  ['Trust & governance','Role authority, provenance, auditability, child protection and clear evidence boundaries are treated as product requirements.'],
]

const adoption = [
  ['01','Choose the first workflow','Start with a real school problem such as curriculum delivery, assessment, learner progress, family visibility or a bounded operational workflow.'],
  ['02','Map people and authority','Confirm who is a learner, teacher, family member or administrator and what each relationship is allowed to see or change.'],
  ['03','Bring the school context','Set up the institution, classes, people and required data without forcing every module into day one.'],
  ['04','Run a measured pilot','Use the workflow with real users and measure completion, reliability, support needs and educational usefulness.'],
  ['05','Expand from evidence','Add more of VibeSchool only when the previous workflow has earned trust and demonstrated value.'],
]

const faqs = [
  ['Does VibeSchool support Kenya’s CBC / CBE context?','VibeSchool is designed around Kenyan curriculum structure and Senior School Pathways. A school should still verify the exact grades, subjects, curriculum evidence and workflow coverage it intends to rely on during the pilot rather than assuming every curriculum area is equally mature.'],
  ['Do we have to replace every system on day one?','No. The recommended adoption model starts with one consequential workflow, maps the people and authority around it, proves that workflow with real users, then expands only where the evidence supports expansion.'],
  ['Will it work on teachers’ phones?','Mobile usability is a product requirement and public experiences are designed for ordinary phones. Before a school depends on a particular private workflow, that exact workflow should be tested on the devices and connectivity conditions staff actually use.'],
  ['What about weak internet or offline work?','VibeSchool is designed with low-bandwidth realities in mind, but offline completeness varies by workflow. A pilot should explicitly test the workflows that must survive poor connectivity; we do not present every feature as fully offline-certified today.'],
  ['How is learner information protected?','The product is designed around role and relationship authority so learners, teachers, families and administrators do not receive one universal all-access view. Specific access boundaries should be included in pilot acceptance testing before real school use.'],
  ['Can you import our existing data?','Migration should be scoped from the actual source files and systems a school has. VibeSchool should not promise a universal one-click migration before inspecting the data quality, identifiers, relationships and records that need to be preserved.'],
  ['How much does VibeSchool cost?','Final public institutional pricing is not locked on this page. Commercial terms should follow the workflow, learner scale, support needs and pilot scope rather than publishing an unvalidated price simply to appear cheaper than other systems.'],
  ['What support or uptime SLA do schools receive?','Support expectations and any contractual service levels should be agreed for the actual deployment. VibeSchool does not publish an invented support or uptime guarantee before those operating commitments are formally approved.'],
  ['Do parents and learners need to use every part of VibeSchool?','No. Participation should follow the workflow and the person’s legitimate role. A school can start teacher-first and introduce learner or family experiences where they create useful continuity and the access model has been validated.'],
]

export default function InstitutionsPage(){return <div className="page"><PublicHeader product="Schools"/><main id="main-content">
<section className="hero"><div className="wrap"><p className="eyebrow">VIBESCHOOL FOR SCHOOLS · KENYA</p><h1>Run the institution. Understand the learning.</h1><p className="lead">VibeSchool connects curriculum, teaching, assessment, learner evidence, families, future pathways and school operations around one continuous educational picture — so school leaders can see more than administration alone.</p><div className="actions"><Link className="primary" href="/contact">Discuss your school</Link><Link className="secondary" href="/pathways">Explore Pathways</Link></div><div className="signals"><span>CBC / CBE aware</span><span>Mobile-first</span><span>Role-based access</span><span>Evidence-led</span><span>Built for Kenyan school context</span></div></div></section>
<section className="section wrap"><p className="eyebrow dark">WHAT A SCHOOL CAN BRING TOGETHER</p><h2>More than a school management dashboard.</h2><p className="intro">VibeSchool is designed so administrative records, classroom work and learner progress do not become separate islands. Each workspace serves a different responsibility while contributing to the wider learning picture.</p><div className="grid">{workspaces.map(([t,d])=><article key={t}><h3>{t}</h3><p>{d}</p></article>)}</div></section>
<section className="section alt"><div className="wrap"><p className="eyebrow dark">THE EDUCATIONAL CHAIN</p><div className="two"><h2>What was planned, taught and learned should connect.</h2><div><p><strong>Curriculum → scheme → lesson.</strong> Planning begins from educational intent rather than an isolated document generator.</p><p><strong>Teaching → evidence → assessment.</strong> Classroom activity and learner work create evidence that can inform understanding.</p><p><strong>Understanding → intervention → next action.</strong> Progress should help teachers and learners decide what needs attention next.</p><p><strong>Family → school → future direction.</strong> Families and institutions receive the context appropriate to their role, including Senior School Pathways where relevant.</p></div></div></div></section>
<section className="section dark"><div className="wrap"><p className="eyebrow">IMPLEMENTATION PRINCIPLE</p><h2>Start with one consequential workflow. Prove it. Then expand.</h2><p className="lead small">A serious school should not be forced to switch every process on day one. VibeSchool adoption is intended to be bounded, measurable and reversible while the institution earns confidence in the platform.</p><div className="steps">{adoption.map(([n,t,d])=><div key={n}><span>{n}</span><strong>{t}</strong><p>{d}</p></div>)}</div></div></section>
<section className="section wrap"><p className="eyebrow dark">BEFORE ADOPTION</p><div className="two"><h2>Ask harder questions than “does it have the feature?”</h2><div><p><strong>Does the information connect?</strong> A report is more useful when its evidence can be traced back to real learning activity.</p><p><strong>Can each role do only what it should?</strong> Convenience should not erase learner, teacher, family and administrator boundaries.</p><p><strong>Will staff actually use it?</strong> Mobile access, clarity, onboarding and normal school workflows matter as much as module count.</p><p><strong>Can the school start small?</strong> Adoption should be possible around one real problem before expanding.</p><div className="actions"><Link className="primary" href="/contact">Talk to VibeSchool</Link><Link className="outline" href="/trust">Review Trust Centre</Link></div></div></div></section>
<section className="section faqSection"><div className="wrap"><p className="eyebrow dark">QUESTIONS A SCHOOL SHOULD ASK BEFORE BUYING</p><h2>Clear answers are part of the sales process.</h2><p className="intro">These answers deliberately avoid promises that have not yet been contractually or operationally proven.</p><div className="faqs">{faqs.map(([q,a])=><details key={q}><summary>{q}</summary><p>{a}</p></details>)}</div><div className="actions"><Link className="primary" href="/contact">Discuss your first workflow</Link><Link className="outline" href="/product">Review product status</Link></div></div></section>
</main><PublicFooter/><style>{styles}</style></div>}

const styles=`.page{background:#f8f8f5;color:#101827;font-family:var(--font-jakarta),Arial,sans-serif;line-height:1.7}.page *{box-sizing:border-box}.wrap{max-width:1160px;margin:auto}.hero{background:#07111f;color:#fff;padding:92px 24px 100px;background-image:radial-gradient(circle at 82% 10%,rgba(208,177,84,.13),transparent 30%)}.eyebrow{font:850 11px var(--font-mono),monospace;letter-spacing:.15em;color:#d0b154}.eyebrow.dark{color:#755b17}h1,h2{font-family:var(--font-display),Arial,sans-serif;letter-spacing:-.04em;line-height:1.05}h1{font-size:clamp(44px,6.2vw,76px);max-width:930px;margin:14px 0 24px}h2{font-size:clamp(32px,4.5vw,52px);margin:10px 0 20px}.lead{font-size:19px;color:#c5ced8;max-width:840px}.lead.small{font-size:17px}.intro{max-width:820px;color:#5d6673;font-size:17px;margin-bottom:32px}.actions{display:flex;gap:12px;flex-wrap:wrap;margin-top:28px}.actions a{padding:12px 18px;border-radius:10px;font-weight:850;text-decoration:none}.primary{background:#d0b154;color:#07111f}.secondary{border:1px solid #697789;color:#fff}.outline{border:1px solid #c9ccd3;color:#242a35}.signals{display:flex;flex-wrap:wrap;gap:8px;margin-top:28px}.signals span{padding:8px 10px;border:1px solid rgba(255,255,255,.16);border-radius:999px;color:#d8dee7;font-size:12px;font-weight:750}.section{padding:88px 24px}.grid{display:grid;grid-template-columns:repeat(3,1fr);gap:14px}.grid article{background:#fff;border:1px solid #e0e3e6;border-radius:16px;padding:27px;min-height:210px}.grid h3{margin:0 0 8px;font-size:21px}.grid p,.two p{color:#5d6673}.alt{background:#eeeae0}.two{display:grid;grid-template-columns:1fr 1fr;gap:70px}.dark{background:#13243a;color:#fff}.steps{display:grid;grid-template-columns:repeat(5,1fr);gap:1px;background:#344357;margin-top:38px}.steps div{background:#13243a;padding:22px;display:flex;flex-direction:column;gap:8px}.steps span{font:800 11px var(--font-mono);color:#d0b154}.steps p{margin:0;color:#aeb9c7;font-size:13px;line-height:1.55}.steps strong{font-size:15px}.faqSection{background:#f0f1f5}.faqs{display:grid;gap:10px;max-width:920px}.faqs details{background:#fff;border:1px solid #dfe2e7;border-radius:14px;padding:0 20px}.faqs summary{cursor:pointer;font-weight:850;padding:19px 0;line-height:1.4}.faqs details[open] summary{border-bottom:1px solid #eceef2}.faqs p{color:#5d6673;padding:0 0 18px;margin:14px 0 0}@media(max-width:980px){.grid{grid-template-columns:repeat(2,1fr)}.steps{grid-template-columns:1fr 1fr}}@media(max-width:760px){.hero,.section{padding:64px 18px}.grid,.two,.steps{grid-template-columns:1fr}.two{gap:18px}}`
