import type { Metadata } from 'next'
import Link from 'next/link'
import { PublicHeader } from '@/components/public/PublicHeader'
import { PublicFooter } from '@/components/public/PublicFooter'

export const metadata: Metadata = { title: 'Institutions & Government | VibeSchool', description: 'How schools, education institutions, partners and public-sector stakeholders can understand and engage with VibeSchool.' }

const areas = [
  ['Schools', 'Connect curriculum, teaching, learner evidence and school context without turning the public website into a private-data surface.'],
  ['Education institutions', 'Evaluate the platform through its educational model, governance boundaries, evidence practices and implementation approach.'],
  ['Government & public sector', 'Inspect how VibeSchool approaches provenance, child protection, privacy, role authority and Kenyan education context before discussing collaboration.'],
  ['Partners & funders', 'Understand what is already built, what remains under development and where partnership could create measurable educational value.'],
]

export default function InstitutionsPage(){return <div className="page"><PublicHeader product="Institutions"/><main id="main-content">
<section className="hero"><div className="wrap"><p className="eyebrow">INSTITUTIONS · SCHOOLS · PUBLIC SECTOR</p><h1>Understand the system before you are asked to trust it.</h1><p className="lead">VibeSchool is building connected education infrastructure around the learner. Institutional conversations should begin with what the product does, how authority is bounded, what evidence supports consequential information and what an implementation would require.</p><div className="actions"><Link className="primary" href="/contact">Discuss an institutional need</Link><Link className="secondary" href="/trust">Review trust practices</Link></div></div></section>
<section className="section wrap"><p className="eyebrow dark">WHO THIS IS FOR</p><h2>Different stakeholders need different evidence.</h2><div className="grid">{areas.map(([t,d])=><article key={t}><h3>{t}</h3><p>{d}</p></article>)}</div></section>
<section className="section alt"><div className="wrap"><p className="eyebrow dark">WHAT TO EVALUATE</p><div className="two"><h2>Do not evaluate VibeSchool only by screenshots.</h2><div><p><strong>Educational model.</strong> Curriculum, learning activity, evidence, understanding and future direction are designed as connected objects.</p><p><strong>Authority.</strong> Learner, parent, teacher and administrator access should come from verified relationships and roles, not from a button selected in the browser.</p><p><strong>Evidence.</strong> Consequential catalogue and Pathways claims should distinguish verified evidence from guidance or incomplete information.</p><p><strong>Privacy and child protection.</strong> Public discovery must remain separate from private learner and institutional data.</p><p><strong>Operational fit.</strong> Mobile access, bandwidth, support, onboarding and the realities of Kenyan schools are implementation requirements, not afterthoughts.</p></div></div></div></section>
<section className="section dark"><div className="wrap"><p className="eyebrow">ADOPTION PRINCIPLE</p><h2>Start with a bounded problem. Prove value. Expand responsibly.</h2><p className="lead small">An institution should not need to adopt every VibeSchool capability at once. A responsible engagement defines the users, educational objective, data boundary, success measure, support model and review point before expansion.</p><div className="steps">{['Define the educational problem','Agree users and authority','Confirm data and safeguarding boundaries','Pilot a bounded workflow','Measure outcomes and usability','Expand only when evidence supports it'].map((x,i)=><div key={x}><span>0{i+1}</span><strong>{x}</strong></div>)}</div></div></section>
<section className="section wrap"><p className="eyebrow dark">DUE DILIGENCE</p><div className="two"><h2>Questions are welcome.</h2><div><p>We would rather answer a difficult implementation, privacy, evidence or governance question than hide it behind promotional language.</p><p>For policies and plain-language trust explanations, use the Trust Centre. For a school, government, NGO, research, funding or partnership discussion, contact VibeSchool directly.</p><div className="actions"><Link className="primary" href="/trust">Open Trust Centre</Link><Link className="outline" href="/contact">Contact VibeSchool</Link></div></div></div></section>
</main><PublicFooter/><style>{styles}</style></div>}

const styles=`.page{background:#f8f8f5;color:#101827;font-family:var(--font-jakarta),Arial,sans-serif;line-height:1.7}.page *{box-sizing:border-box}.wrap{max-width:1160px;margin:auto}.hero{background:#07111f;color:#fff;padding:92px 24px 100px}.eyebrow{font:850 11px var(--font-mono),monospace;letter-spacing:.15em;color:#d0b154}.eyebrow.dark{color:#755b17}h1,h2{font-family:var(--font-display),Arial,sans-serif;letter-spacing:-.04em;line-height:1.05}h1{font-size:clamp(42px,6vw,72px);max-width:930px;margin:14px 0 24px}h2{font-size:clamp(32px,4.5vw,52px);margin:10px 0 28px}.lead{font-size:18px;color:#c5ced8;max-width:800px}.lead.small{font-size:17px}.actions{display:flex;gap:12px;flex-wrap:wrap;margin-top:28px}.actions a{padding:12px 18px;border-radius:10px;font-weight:850;text-decoration:none}.primary{background:#d0b154;color:#07111f}.secondary{border:1px solid #697789;color:#fff}.outline{border:1px solid #c9ccd3;color:#242a35}.section{padding:88px 24px}.grid{display:grid;grid-template-columns:repeat(2,1fr);gap:14px}.grid article{background:#fff;border:1px solid #e0e3e6;border-radius:14px;padding:27px}.grid h3{margin:0 0 8px;font-size:21px}.grid p,.two p{color:#5d6673}.alt{background:#eeeae0}.two{display:grid;grid-template-columns:1fr 1fr;gap:70px}.dark{background:#13243a;color:#fff}.steps{display:grid;grid-template-columns:repeat(3,1fr);gap:1px;background:#344357;margin-top:38px}.steps div{background:#13243a;padding:24px;display:grid;gap:8px}.steps span{font:800 11px var(--font-mono);color:#d0b154}@media(max-width:760px){.hero,.section{padding:64px 18px}.grid,.two,.steps{grid-template-columns:1fr}.two{gap:18px}}`