"use client"

export const dynamic = "force-dynamic"

import { useEffect, useMemo, useState } from "react"
import { useRouter } from "next/navigation"
import { supabase } from "@/lib/supabase"

type School={id:string;name:string;county:string|null;sub_county:string|null;school_type:string|null;ownership_type:string|null;gender_type:string|null;levels:string[];distance_km:number|null;source:"CANONICAL"|"DIRECTORY";knec_code:string|null}
const LEVELS=[["PRIMARY","Primary","PP1–Grade 6"],["JUNIOR","Junior School","Grade 7–9"],["SENIOR_SECONDARY","Senior Secondary","Grade 10–12"]] as const
const COUNTIES=["Baringo","Bomet","Bungoma","Busia","Elgeyo Marakwet","Embu","Garissa","Homa Bay","Isiolo","Kajiado","Kakamega","Kericho","Kiambu","Kilifi","Kirinyaga","Kisii","Kisumu","Kitui","Kwale","Laikipia","Lamu","Machakos","Makueni","Mandera","Marsabit","Meru","Migori","Mombasa","Murang’a","Nairobi","Nakuru","Nandi","Narok","Nyamira","Nyandarua","Nyeri","Samburu","Siaya","Taita Taveta","Tana River","Tharaka Nithi","Trans Nzoia","Turkana","Uasin Gishu","Vihiga","Wajir","West Pokot"]

export default function SchoolDiscovery(){
 const router=useRouter(); const [level,setLevel]=useState(""); const [q,setQ]=useState(""); const [county,setCounty]=useState(""); const [subCounty,setSubCounty]=useState(""); const [rows,setRows]=useState<School[]>([]); const [picked,setPicked]=useState<School|null>(null); const [busy,setBusy]=useState(false); const [searching,setSearching]=useState(false); const [msg,setMsg]=useState(""); const [lat,setLat]=useState<number|null>(null); const [lng,setLng]=useState<number|null>(null)
 useEffect(()=>{navigator.geolocation?.getCurrentPosition(p=>{setLat(p.coords.latitude);setLng(p.coords.longitude)},()=>{},{maximumAge:300000,timeout:3500})},[])
 useEffect(()=>{if(!level||q.trim().length<2){setRows([]);setSearching(false);return} const timer=setTimeout(async()=>{setSearching(true);const {data,error}=await supabase.rpc("search_school_directory",{p_query:q.trim(),p_level:level,p_county:county||null,p_sub_county:subCounty||null,p_lat:lat,p_lng:lng,p_limit:40});setSearching(false);if(error){setMsg("School search is temporarily unavailable. Please try again.");return}setMsg("");setRows((data||[]) as School[])},180);return()=>clearTimeout(timer)},[q,level,county,subCounty,lat,lng])
 const ambiguous=useMemo(()=>{const counts=new Map<string,number>();for(const r of rows){const k=`${r.name.toLowerCase().replace(/[^a-z0-9]/g,"")}|${(r.county||"").toLowerCase()}|${(r.sub_county||"").toLowerCase()}`;counts.set(k,(counts.get(k)||0)+1)}return [...counts.values()].some(n=>n>1)},[rows])
 async function claim(){if(!picked||!level)return;setBusy(true);setMsg("");const fn=picked.source==="DIRECTORY"?"connect_teacher_to_directory_school":"connect_teacher_to_school";const args=picked.source==="DIRECTORY"?{p_directory_id:picked.id,p_level:level}:{p_school_id:picked.id,p_level:level};const {error}=await supabase.rpc(fn,args);setBusy(false);if(error){setMsg("We could not submit your school claim. Please retry.");return}router.push("/teacher/onboarding/school/pending")}
 return <main style={{minHeight:"100vh",background:"#f3f4f6",padding:16,fontFamily:"system-ui"}}><section style={{maxWidth:560,margin:"40px auto",background:"#fff",borderRadius:20,padding:24,boxShadow:"0 4px 20px rgba(0,0,0,.08)"}}>
  <h1 style={{marginTop:0,marginBottom:8}}>Find your school</h1><p style={{color:"#667085",marginTop:0}}>Choose the school where you teach. Selecting a school submits a verification claim; it does not grant school access until an authorized reviewer approves it.</p>
  <div style={{display:"grid",gridTemplateColumns:"repeat(3,1fr)",gap:8}}>{LEVELS.map(([v,l,h])=><button key={v} onClick={()=>{setLevel(v);setPicked(null);setMsg("")}} style={{padding:12,borderRadius:12,border:level===v?"2px solid #16a34a":"1px solid #ddd",background:level===v?"#f0fdf4":"#fff"}}><b>{l}</b><small style={{display:"block",marginTop:4,color:"#667085"}}>{h}</small></button>)}</div>
  <input disabled={!level} value={q} onChange={e=>{setQ(e.target.value);setPicked(null)}} placeholder={level?"School name or code":"Choose a level first"} style={{width:"100%",boxSizing:"border-box",marginTop:14,padding:14,borderRadius:12,border:"1px solid #ccc",fontSize:16}}/>
  <select value={county} onChange={e=>setCounty(e.target.value)} style={{width:"100%",boxSizing:"border-box",marginTop:8,padding:14,borderRadius:12,border:"1px solid #ccc"}}><option value="">Any county</option>{COUNTIES.map(c=><option key={c}>{c}</option>)}</select>
  <input value={subCounty} onChange={e=>setSubCounty(e.target.value)} placeholder="Sub-county (optional)" style={{width:"100%",boxSizing:"border-box",marginTop:8,padding:14,borderRadius:12,border:"1px solid #ccc"}}/>
  <div style={{fontSize:13,color:"#667085",marginTop:8}}>{lat!=null&&lng!=null?"Using your location to rank nearby schools.":"Location is optional and only helps distinguish similar school names."}</div>
  {searching&&<p style={{color:"#667085",fontSize:13}}>Searching schools…</p>}{ambiguous&&<div style={{marginTop:12,padding:12,background:"#fffaeb",border:"1px solid #fedf89",borderRadius:12,fontSize:13}}><b>Similar school names found.</b> Check county and sub-county before selecting.</div>}
  {rows.map(s=><button key={`${s.source}-${s.id}`} onClick={()=>{setPicked(s);setMsg("")}} style={{display:"block",width:"100%",textAlign:"left",padding:13,marginTop:8,borderRadius:12,border:picked?.id===s.id&&picked?.source===s.source?"2px solid #16a34a":"1px solid #e5e7eb",background:picked?.id===s.id&&picked?.source===s.source?"#f0fdf4":"#fff"}}><b>{s.name}</b><div style={{fontSize:12,color:"#667085",marginTop:4}}>{[s.sub_county,s.county,s.ownership_type,s.gender_type].filter(Boolean).join(" · ")||"Location details being verified"}</div></button>)}
  {msg&&<p role="alert" style={{color:"#b42318",fontWeight:600}}>{msg}</p>}{picked&&<button disabled={busy} onClick={claim} style={{width:"100%",marginTop:12,padding:14,border:0,borderRadius:12,background:"#16a34a",color:"#fff",fontWeight:700}}>{busy?"Submitting…":"Submit school for verification →"}</button>}
 </section></main>
}
