'use client'

import Link from 'next/link'
import { useEffect,useState } from 'react'
import { supabase } from '@/lib/supabase'

type Learner={student_id:string;student_name:string;pathway_slug:string|null;pathway_name:string|null;adopted_at:string|null;reviewed_at:string|null}
type Draft={id:string;status:string;updated_at:string;pathways:{slug:string;name:string}|null}

export default function ParentPathwaysPage(){
 const[learners,setLearners]=useState<Learner[]>([]),[drafts,setDrafts]=useState<Draft[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState('')
 useEffect(()=>{let live=true;void(async()=>{const client=supabase as any;const[a,b]=await Promise.all([client.rpc('parent_get_linked_pathway_passports'),client.from('parent_pathway_drafts').select('id,status,updated_at,pathways(slug,name)').order('updated_at',{ascending:false})]);if(!live)return;if(a.error||b.error){setError('Family Pathways support could not be loaded safely.');setLoading(false);return}setLearners((a.data??[]) as Learner[]);setDrafts((b.data??[]) as Draft[]);setLoading(false)})();return()=>{live=false}},[])
 return <main className="page"><div className="wrap"><Link href="/parent" className="back">← Parent home</Link><p className="eyebrow">FAMILY PATHWAYS SUPPORT</p><h1>Support the learner’s decision without taking ownership of it.</h1><p className="lead">Your drafts belong to your adult account. A learner Passport belongs to that learner.</p>{loading&&<section className="card">Loading…</section>}{error&&<section className="error" role="alert">{error}</section>}{!loading&&!error&&<><section className="card"><strong>Linked learners</strong>{learners.length===0?<p>No linked learners available yet.</p>:learners.map(l=><div className="row" key={l.student_id}><div><b>{l.student_name}</b><p>{l.pathway_name??'No learner-owned Passport yet.'}</p></div>{l.pathway_slug&&<Link href={`/pathways/${encodeURIComponent(l.pathway_slug)}`}>Understand →</Link>}</div>)}</section><section className="card"><strong>My planning drafts</strong>{drafts.length===0?<p>No adult-owned drafts saved yet.</p>:drafts.map(d=><div className="row" key={d.id}><div><b>{d.pathways?.name??'Saved direction'}</b><p>{d.status.replaceAll('_',' ')} · updated {new Date(d.updated_at).toLocaleDateString('en-KE')}</p></div>{d.pathways?.slug&&<Link href={`/pathways/${encodeURIComponent(d.pathways.slug)}`}>Explore →</Link>}</div>)}</section><section className="notice"><strong>Support boundary</strong><p>This page has no control that can overwrite a learner Passport.</p></section></>}</div><style jsx>{styles}</style></main>
}

const styles=`.page{min-height:100dvh;background:#f7f7fb;color:#111827}.wrap{max-width:760px;margin:0 auto;padding:24px 16px 60px}.back,.row a{color:#4f46e5;font-weight:800;text-decoration:none}.eyebrow{margin:28px 0 8px;font-size:10px;font-weight:900;letter-spacing:.15em;color:#4f46e5}h1{font-size:clamp(31px,6vw,46px);line-height:1.07;letter-spacing:-.04em;margin:0}.lead,.card p,.notice p{color:#626b7b;line-height:1.6}.card{margin-top:16px;background:#fff;border:1px solid #e5e7eb;border-radius:18px;padding:20px}.row{display:flex;justify-content:space-between;gap:12px;padding:13px 0;border-bottom:1px solid #f0f1f4}.row p{margin:4px 0 0;font-size:12px}.notice{margin-top:16px;background:#eef2ff;border:1px solid #c7d2fe;border-radius:16px;padding:16px}.error{margin-top:16px;background:#fef2f2;color:#991b1b;border:1px solid #fecaca;border-radius:14px;padding:14px}`