"use client"

import { useCallback, useEffect, useMemo, useState } from "react"
import { HQPage, HQPanel } from "@/components/hq/HQShell"
import { supabase } from "@/lib/supabase"

type GeoItem={id:string;name:string;country_id?:string;county_id?:string;subcounty_id?:string;verification_state?:string}
type Hierarchy={countries:GeoItem[];counties:GeoItem[];subcounties:GeoItem[];wards:GeoItem[]}
type Summary={scope:Record<string,unknown>;schools:{total:number;verified_geography:number;unresolved_geography:number;conflicting_geography:number;mapped_coordinates:number};users:{school_memberships:number;unique_staff?:number;teachers:number;school_admins:number;learners:number;parents:number};activity:{events:number;active_schools:number;evidence:string};support:{open_cases:number;incidents:number};measurement?:{certified_from:string|null;historical_retention_claimable:boolean};freshness:{generated_at:string;activity_window_days:number}}
type Quality={total_schools:number;without_mapping:number;without_county:number;without_subcounty:number;without_ward:number;without_coordinates:number;conflicting:number;unresolved:number;legacy_text_county_only:number;generated_at:string}
type Breakdown={id:string;name:string;school_count:number;verified_school_count:number;active_school_count:number}
type Growth={window_days:number;new_schools:number;new_staff_accounts:number;new_learner_accounts:number;active_users:number;previous_active_users:number;measurement_certified_from:string|null;generated_at:string}
type Opportunity={school_id:string;school_name:string;learners:number;teachers:number;active_teachers:number;signal:string;evidence_summary:string}
type SchoolRow={id:string;name:string;knec_code:string|null;nemis_code:string|null;status:string;school_level:string;geography_state:string|null;county:string|null;subcounty:string|null;ward:string|null;teachers:number;learners:number;active_events:number}
type School360={identity:{id:string;name:string;knec_code:string|null;nemis_code:string|null;moe_registration_no:string|null;status:string;last_verified_at:string|null;aliases:Array<{alias:string;source:string|null;verified:boolean;confidence:number|null}>};institution:{school_type:string|null;school_category:string|null;ownership_type:string|null;levels:Array<{level:string;source:string|null}>};geography:{verification_state:string;county?:string|null;subcounty?:string|null;ward?:string|null;latitude?:number|null;longitude?:number|null;location_precision?:string|null;source_key?:string|null;source_version?:string|null;last_verified_at?:string|null};community:{teachers:number;admins:number;learners:number;parents:number};engagement:{events:number;active_users:number;teacher_events:number;learner_events:number;evidence:string};operations:{open_support_cases:number;open_incidents:number};freshness:{generated_at:string;activity_window_days:number;measurement_certified_from:string|null}}

const emptySummary:Summary={scope:{},schools:{total:0,verified_geography:0,unresolved_geography:0,conflicting_geography:0,mapped_coordinates:0},users:{school_memberships:0,teachers:0,school_admins:0,learners:0,parents:0},activity:{events:0,active_schools:0,evidence:"insufficient_evidence"},support:{open_cases:0,incidents:0},freshness:{generated_at:"",activity_window_days:30}}
const emptyGrowth:Growth={window_days:30,new_schools:0,new_staff_accounts:0,new_learner_accounts:0,active_users:0,previous_active_users:0,measurement_certified_from:null,generated_at:""}

function Metric({label,value,note}:{label:string;value:number|string;note?:string}){return <div className="geo-metric"><span>{label}</span><strong>{value}</strong>{note&&<small>{note}</small>}</div>}
function Field({label,value,onChange,items,disabled=false}:{label:string;value:string;onChange:(value:string)=>void;items:GeoItem[];disabled?:boolean}){return <label className="geo-field"><span>{label}</span><select value={value} onChange={e=>onChange(e.target.value)} disabled={disabled}><option value="">All / national</option>{items.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label>}
function Evidence({children}:{children:React.ReactNode}){return <div className="geo-evidence">{children}</div>}

export default function HQGeographyPage(){
  const [hierarchy,setHierarchy]=useState<Hierarchy>({countries:[],counties:[],subcounties:[],wards:[]})
  const [summary,setSummary]=useState<Summary>(emptySummary)
  const [quality,setQuality]=useState<Quality|null>(null)
  const [breakdown,setBreakdown]=useState<Breakdown[]>([])
  const [growth,setGrowth]=useState<Growth>(emptyGrowth)
  const [opportunities,setOpportunities]=useState<Opportunity[]>([])
  const [schools,setSchools]=useState<SchoolRow[]>([])
  const [school360,setSchool360]=useState<School360|null>(null)
  const [selectedSchool,setSelectedSchool]=useState("")
  const [country,setCountry]=useState("")
  const [county,setCounty]=useState("")
  const [subcounty,setSubcounty]=useState("")
  const [ward,setWard]=useState("")
  const [days,setDays]=useState("30")
  const [level,setLevel]=useState("")
  const [search,setSearch]=useState("")
  const [error,setError]=useState<string|null>(null)
  const [loading,setLoading]=useState(true)

  const counties=useMemo(()=>hierarchy.counties.filter(x=>!country||x.country_id===country),[hierarchy.counties,country])
  const subcounties=useMemo(()=>hierarchy.subcounties.filter(x=>!county||x.county_id===county),[hierarchy.subcounties,county])
  const wards=useMemo(()=>hierarchy.wards.filter(x=>!subcounty||x.subcounty_id===subcounty),[hierarchy.wards,subcounty])

  const load=useCallback(async()=>{
    setLoading(true);setError(null)
    const scope={p_country_id:country||null,p_county_id:county||null,p_subcounty_id:subcounty||null,p_ward_id:ward||null}
    const [{data:h,error:he},{data:q,error:qe},{data:s,error:se},{data:g,error:ge},{data:o,error:oe},{data:sl,error:sle}]=await Promise.all([
      supabase.rpc("hq_geography_hierarchy"),
      supabase.rpc("hq_geographic_data_quality"),
      supabase.rpc("hq_geography_summary",{...scope,p_school_id:null,p_days:Number(days)}),
      supabase.rpc("hq_geography_growth",{...scope,p_days:Number(days)}),
      supabase.rpc("hq_geography_opportunities",{...scope,p_days:Number(days),p_limit:50}),
      supabase.rpc("hq_geography_school_list",{...scope,p_level:level||null,p_search:search.trim()||null,p_days:Number(days),p_limit:100}),
    ])
    if(he||qe||se||ge||oe||sle){setError("National intelligence is unavailable. No fallback data is being shown.");setLoading(false);return}
    setHierarchy((h??{countries:[],counties:[],subcounties:[],wards:[]}) as Hierarchy);setQuality(q as Quality);setSummary((s??emptySummary) as Summary);setGrowth((g??emptyGrowth) as Growth);setOpportunities((o??[]) as Opportunity[]);setSchools((sl??[]) as SchoolRow[])
    const parentType=ward?null:subcounty?"subcounty":county?"county":"country";const parentId=subcounty||county||country||null
    if(parentType){const {data:b}=await supabase.rpc("hq_geography_region_breakdown",{p_parent_type:parentType,p_parent_id:parentId,p_days:Number(days)});setBreakdown((b??[]) as Breakdown[])}else setBreakdown([])
    setLoading(false)
  },[country,county,subcounty,ward,days,level,search])

  useEffect(()=>{void load()},[load])
  const openSchool=async(id:string)=>{setSelectedSchool(id);setSchool360(null);const {data,error:e}=await supabase.rpc("hq_school_360",{p_school_id:id,p_days:Number(days)});if(e){setError("School 360 is unavailable for this school.");return}setSchool360(data as School360)}
  const resetCountry=(v:string)=>{setCountry(v);setCounty("");setSubcounty("");setWard("");setSelectedSchool("");setSchool360(null)}
  const resetCounty=(v:string)=>{setCounty(v);setSubcounty("");setWard("");setSelectedSchool("");setSchool360(null)}
  const resetSubcounty=(v:string)=>{setSubcounty(v);setWard("");setSelectedSchool("");setSchool360(null)}
  const geoCoverage=summary.schools.total?Math.round(summary.schools.verified_geography/summary.schools.total*100):null
  const mapCoverage=summary.schools.total?Math.round(summary.schools.mapped_coordinates/summary.schools.total*100):null
  const activeDelta=growth.previous_active_users?Math.round((growth.active_users-growth.previous_active_users)/growth.previous_active_users*100):null
  const maxRegion=Math.max(1,...breakdown.map(x=>x.school_count))

  return <HQPage title="National Intelligence" description="Founder intelligence across geography, schools, users, growth and evidence quality. Unknown evidence remains unknown.">
    <div className="geo-stack">
      <HQPanel title="Scope" description="One canonical scope drives every read model on this surface."><div className="geo-filters">
        <Field label="Country" value={country} onChange={resetCountry} items={hierarchy.countries}/><Field label="County" value={county} onChange={resetCounty} items={counties} disabled={!country&&hierarchy.countries.length>0}/><Field label="Sub-County" value={subcounty} onChange={resetSubcounty} items={subcounties} disabled={!county}/><Field label="Ward" value={ward} onChange={setWard} items={wards} disabled={!subcounty}/>
        <label className="geo-field"><span>Period</span><select value={days} onChange={e=>setDays(e.target.value)}><option value="7">7 days</option><option value="30">30 days</option><option value="90">90 days</option></select></label>
      </div></HQPanel>
      {error&&<div role="alert" className="geo-alert">{error}</div>}
      {loading?<div className="geo-loading">Loading owner-authorized evidence…</div>:<>
        <HQPanel title="NOW — Founder attention" description="Signals are deterministic and evidence-backed; they do not authorize action."><div className="geo-now">
          <Metric label="Identity / geography gaps" value={summary.schools.unresolved_geography+summary.schools.conflicting_geography} note="Unresolved + conflicting school geography"/><Metric label="Teacher activation opportunities" value={opportunities.length} note="Enrolled learners with no teacher activity in selected window"/><Metric label="Open support pressure" value={summary.support.open_cases}/><Metric label="Open incidents" value={summary.support.incidents}/>
        </div></HQPanel>
        <section className="geo-metrics" aria-label="National summary metrics"><Metric label="Canonical schools" value={summary.schools.total}/><Metric label="Verified geography" value={summary.schools.verified_geography} note={geoCoverage===null?"Coverage unavailable":`${geoCoverage}% scoped coverage`}/><Metric label="Mapped schools" value={summary.schools.mapped_coordinates} note={mapCoverage===null?"Coverage unavailable":`${mapCoverage}% coordinate coverage`}/><Metric label="Teachers" value={summary.users.teachers}/><Metric label="Learners" value={summary.users.learners}/><Metric label="Parents" value={summary.users.parents}/><Metric label="School admins" value={summary.users.school_admins}/><Metric label="Active schools" value={summary.activity.evidence==="available"?summary.activity.active_schools:"Unknown"}/></section>
        <div className="geo-grid"><HQPanel title="TREND — Growth" description="Registration and activity counts use canonical evidence; retention is withheld before certified measurement coverage."><div className="geo-quality"><Metric label="New schools" value={growth.new_schools}/><Metric label="New staff accounts" value={growth.new_staff_accounts}/><Metric label="New learner accounts" value={growth.new_learner_accounts}/><Metric label="Active users" value={growth.active_users} note={activeDelta===null?"Previous-window comparison unavailable":`${activeDelta>=0?"+":""}${activeDelta}% vs previous window`}/></div><Evidence>Measurement certified from: {growth.measurement_certified_from?new Date(growth.measurement_certified_from).toLocaleString():"Unavailable"}. D1/D7/D30 retention is not claimed before this boundary.</Evidence></HQPanel><HQPanel title="Data quality" description="Coverage is separate from business performance.">{quality?<div className="geo-quality"><Metric label="Without governed mapping" value={quality.without_mapping}/><Metric label="Without county" value={quality.without_county}/><Metric label="Without sub-county" value={quality.without_subcounty}/><Metric label="Without ward" value={quality.without_ward}/><Metric label="Without coordinates" value={quality.without_coordinates}/><Metric label="Conflicting" value={quality.conflicting}/></div>:<div className="geo-empty">Quality evidence unavailable.</div>}</HQPanel></div>
        <HQPanel title="WHERE — Regional intensity" description="Accessible county/sub-county/ward equivalent of the heat map. Polygon rendering remains gated by governed boundary data.">{breakdown.length===0?<div className="geo-empty">No governed administrative breakdown is available at this scope.</div>:<div className="geo-heat" role="list" aria-label="Regional intensity ranking">{breakdown.map(row=><div className="geo-heat-row" role="listitem" key={row.id}><div><strong>{row.name}</strong><small>{row.school_count} schools · {row.verified_school_count} verified · {row.active_school_count} active</small></div><div className="geo-bar" aria-label={`${row.name}: ${row.school_count} schools`}><span style={{width:`${Math.max(4,row.school_count/maxRegion*100)}%`}}/></div></div>)}</div>}</HQPanel>
        <HQPanel title="NEXT — Opportunity signals" description="Evidence → scope → recommended investigation. No automated outreach or consequential action.">{opportunities.length===0?<div className="geo-empty">No teacher-activation opportunity is evidenced in this scope.</div>:<div className="geo-table-wrap"><table className="geo-table"><thead><tr><th>School</th><th>Learners</th><th>Teachers</th><th>Active teachers</th><th>Evidence</th></tr></thead><tbody>{opportunities.map(o=><tr key={o.school_id}><td><button className="geo-link" onClick={()=>void openSchool(o.school_id)}>{o.school_name}</button></td><td>{o.learners}</td><td>{o.teachers}</td><td>{o.active_teachers}</td><td>{o.evidence_summary}</td></tr>)}</tbody></table></div>}</HQPanel>
        <HQPanel title="Schools" description="Canonical school search. Alias, KNEC and NEMIS matching never mutates school identity."><div className="geo-school-tools"><label className="geo-field"><span>School level</span><select value={level} onChange={e=>setLevel(e.target.value)}><option value="">All / Unknown included</option><option>Primary</option><option>Junior School</option><option>Secondary</option></select></label><label className="geo-field"><span>Search</span><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Name, alias, KNEC or NEMIS"/></label></div><div className="geo-table-wrap"><table className="geo-table"><thead><tr><th>School</th><th>Level</th><th>Region</th><th>Teachers</th><th>Learners</th><th>Activity</th></tr></thead><tbody>{schools.map(s=><tr key={s.id} className={selectedSchool===s.id?"geo-selected":""}><td><button className="geo-link" onClick={()=>void openSchool(s.id)}>{s.name}</button><small className="geo-sub">{s.knec_code||s.nemis_code||s.geography_state||"Identity evidence limited"}</small></td><td>{s.school_level||"Unknown"}</td><td>{[s.ward,s.subcounty,s.county].filter(Boolean).join(", ")||"Unknown"}</td><td>{s.teachers}</td><td>{s.learners}</td><td>{s.active_events}</td></tr>)}</tbody></table></div></HQPanel>
        {selectedSchool&&<HQPanel title="School 360" description="Aggregate-first institutional intelligence. No unrestricted child or private-family records.">{!school360?<div className="geo-loading">Loading School 360…</div>:<div className="geo-360"><div><h3>{school360.identity.name}</h3><p>{school360.identity.knec_code?`KNEC ${school360.identity.knec_code}`:"No verified KNEC identifier"} · {school360.identity.status}</p></div><div className="geo-metrics"><Metric label="Teachers" value={school360.community.teachers}/><Metric label="Learners" value={school360.community.learners}/><Metric label="Parents" value={school360.community.parents}/><Metric label="Admins" value={school360.community.admins}/><Metric label="Active users" value={school360.engagement.evidence==="available"?school360.engagement.active_users:"Unknown"}/><Metric label="Support cases" value={school360.operations.open_support_cases}/></div><div className="geo-grid"><Evidence><strong>Geography</strong><br/>{[school360.geography.ward,school360.geography.subcounty,school360.geography.county].filter(Boolean).join(", ")||"Unknown"}<br/>State: {school360.geography.verification_state}{school360.geography.latitude!=null&&school360.geography.longitude!=null?<><br/>Coordinates: {school360.geography.latitude}, {school360.geography.longitude} ({school360.geography.location_precision||"precision unknown"})</>:null}</Evidence><Evidence><strong>Institution</strong><br/>Level: {school360.institution.levels.map(x=>x.level).join(", ")||school360.institution.school_type||"Unknown"}<br/>Category: {school360.institution.school_category||"Unknown"}<br/>Ownership: {school360.institution.ownership_type||"Unknown"}</Evidence></div><Evidence><strong>Aliases & provenance</strong><br/>{school360.identity.aliases.length?school360.identity.aliases.map(a=>`${a.alias}${a.verified?" (verified)":""}`).join(" · "):"No aliases recorded"}<br/>Measurement certified from: {school360.freshness.measurement_certified_from?new Date(school360.freshness.measurement_certified_from).toLocaleString():"Unavailable"}</Evidence></div>}</HQPanel>}
        <HQPanel title="Kenya map & school locator" description="Maps are analytical tools, not decoration. Polygon and point rendering activates only when governed evidence is sufficient."><div className="geo-map-hold"><strong>Map evidence not ready</strong><p>Production currently lacks governed school coordinates and complete county/sub-county/ward mappings. Rendering a national choropleth or school locator now would imply false precision. The regional intensity list above remains the canonical accessible alternative until verified boundary and coordinate coverage exists.</p></div></HQPanel>
      </>}
    </div>
    <style jsx global>{`
      .geo-stack{display:grid;gap:14px}.geo-filters,.geo-school-tools{display:grid;grid-template-columns:repeat(5,minmax(0,1fr));gap:10px;padding:14px}.geo-school-tools{grid-template-columns:220px 1fr}.geo-field{display:grid;gap:6px}.geo-field span{font-size:11px;font-weight:850;color:#8fa2ba;text-transform:uppercase;letter-spacing:.04em}.geo-field select,.geo-field input{min-height:44px;border-radius:10px;border:1px solid rgba(148,163,184,.18);background:#091727;color:#f8fafc;padding:0 10px}.geo-metrics,.geo-now{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:10px}.geo-metric{min-width:0;border:1px solid rgba(148,163,184,.13);border-radius:13px;background:#0b1728;padding:14px}.geo-metric span{display:block;color:#8fa2ba;font-size:11px;font-weight:800}.geo-metric strong{display:block;margin-top:5px;font-size:22px}.geo-metric small,.geo-sub{display:block;margin-top:5px;color:#8fa2ba;font-size:10px;line-height:1.35}.geo-grid{display:grid;grid-template-columns:1.4fr 1fr;gap:14px}.geo-table-wrap{overflow:auto}.geo-table{width:100%;border-collapse:collapse;font-size:12px}.geo-table th,.geo-table td{padding:12px 14px;border-bottom:1px solid rgba(148,163,184,.1);text-align:left;vertical-align:top}.geo-table th{color:#8fa2ba;font-size:10px;text-transform:uppercase;letter-spacing:.05em}.geo-quality{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:8px;padding:12px}.geo-empty,.geo-loading{padding:24px;color:#8fa2ba;font-size:13px}.geo-alert{border:1px solid rgba(245,158,11,.35);background:rgba(245,158,11,.08);color:#fde68a;padding:12px 14px;border-radius:12px}.geo-map-hold,.geo-evidence{padding:18px;line-height:1.55;font-size:12px;color:#a8b8ca}.geo-evidence{border:1px solid rgba(148,163,184,.12);border-radius:12px;background:#091727}.geo-map-hold strong,.geo-evidence strong{color:#f8fafc}.geo-map-hold p{margin:7px 0 0;color:#8fa2ba}.geo-heat{display:grid;gap:10px;padding:14px}.geo-heat-row{display:grid;grid-template-columns:minmax(170px,260px) 1fr;gap:14px;align-items:center}.geo-heat-row strong,.geo-heat-row small{display:block}.geo-heat-row small{color:#8fa2ba;margin-top:3px}.geo-bar{height:12px;border-radius:999px;background:rgba(148,163,184,.12);overflow:hidden}.geo-bar span{display:block;height:100%;background:linear-gradient(90deg,#38bdf8,#22c55e);border-radius:999px}.geo-link{border:0;background:transparent;color:#7dd3fc;text-align:left;padding:0;font:inherit;cursor:pointer;text-decoration:underline;text-underline-offset:3px}.geo-selected{background:rgba(56,189,248,.06)}.geo-360{display:grid;gap:14px;padding:14px}.geo-360 h3{margin:0;font-size:20px}.geo-360 p{margin:4px 0 0;color:#8fa2ba}
      @media(max-width:1100px){.geo-filters{grid-template-columns:repeat(3,minmax(0,1fr))}.geo-metrics,.geo-now{grid-template-columns:repeat(2,minmax(0,1fr))}}
      @media(max-width:720px){.geo-filters,.geo-school-tools{grid-template-columns:1fr 1fr}.geo-grid{grid-template-columns:1fr}.geo-quality{grid-template-columns:1fr 1fr}.geo-table th,.geo-table td{padding:11px 10px}.geo-heat-row{grid-template-columns:1fr}.geo-bar{height:10px}}
      @media(max-width:390px){.geo-filters,.geo-school-tools{grid-template-columns:1fr}.geo-metrics,.geo-now{grid-template-columns:1fr 1fr}.geo-metric strong{font-size:19px}}
    `}</style>
  </HQPage>
}
