"use client"

import { useCallback,useEffect,useState } from "react"
import { useRouter } from "next/navigation"
import { supabase } from "@/lib/supabase"
const rpc=supabase.rpc.bind(supabase) as any
const C={bg:'#07111f',panel:'#0d1b2f',line:'rgba(255,255,255,.09)',text:'#f8fafc',muted:'rgba(255,255,255,.48)',green:'#34d399',amber:'#f59e0b',red:'#fb7185',blue:'#60a5fa'}
type Revision={id:string;publication_id:string;publication_title:string;publication_format:string;revision_number:number;reason:string|null;created_at:string};type Source={id:string;authority_name:string;source_url:string|null;source_ref:string|null;curriculum_name:string;grade:string;subject:string;version_label:string|null;status:string;updated_at:string}
const blank={authority:'Kenya Institute of Curriculum Development',curriculum:'Kenya Curriculum',grade:'',subject:'',url:'',ref:'',version:'',notes:''}
export default function Governance(){const router=useRouter();const[revs,setRevs]=useState<Revision[]>([]);const[sources,setSources]=useState<Source[]>([]);const[form,setForm]=useState(blank);const[error,setError]=useState('');const[busy,setBusy]=useState('')
 const load=useCallback(async()=>{const[r,s]=await Promise.all([rpc('hq_list_publication_revisions',{p_limit:300}),rpc('hq_list_curriculum_imports',{p_limit:300})]);const e=r.error||s.error;if(e)setError(e.message);else{setRevs(r.data??[]);setSources(s.data??[])}},[]);useEffect(()=>{void load()},[load])
 async function register(){setBusy('new');const{error:e}=await rpc('hq_register_curriculum_source',{p_authority_name:form.authority,p_curriculum_name:form.curriculum,p_grade:form.grade,p_subject:form.subject,p_source_url:form.url,p_source_ref:form.ref,p_version_label:form.version,p_notes:form.notes});if(e)setError(e.message);else{setForm(blank);await load()}setBusy('')}
 async function review(id:string,status:string){setBusy(id);const{error:e}=await rpc('hq_review_curriculum_import',{p_id:id,p_status:status});if(e)setError(e.message);else await load();setBusy('')}
 return <main style={{minHeight:'100dvh',background:C.bg,color:C.text,padding:18,fontFamily:'Inter,system-ui,sans-serif'}}><div style={{maxWidth:1120,margin:'0 auto'}}><button onClick={()=>router.push('/hq/studio')} style={btn}>← Studio</button><h1>Sources & Revision History</h1><p style={{color:C.muted,fontSize:12}}>Curriculum provenance and publication versions are separate evidence trails. Registering a source never marks it verified automatically.</p>{error&&<div style={{color:'#fecdd3'}}>{error}</div>}<div style={{display:'grid',gridTemplateColumns:'minmax(320px,.75fr) minmax(0,1fr)',gap:12}}><section style={panel}><h2 style={{fontSize:14}}>Register curriculum source</h2>{[['Authority','authority'],['Curriculum','curriculum'],['Grade / Form','grade'],['Subject','subject'],['Official URL','url'],['Source reference','ref'],['Version / edition','version'],['Notes','notes']].map(([label,key])=><label key={key} style={lab}>{label}<input value={(form as any)[key]} onChange={e=>setForm({...form,[key]:e.target.value})} style={input}/></label>)}<button disabled={busy==='new'} onClick={()=>void register()} style={{...btn,color:C.green}}>Register as draft</button><div style={{borderTop:`1px solid ${C.line}`,margin:'16px 0'}}/><h2 style={{fontSize:14}}>Source review</h2>{sources.slice(0,80).map((s,i)=><div key={s.id} style={{padding:'10px 0',borderTop:i?`1px solid ${C.line}`:0}}><div style={{fontSize:12,fontWeight:800}}>{s.grade} · {s.subject}</div><div style={{fontSize:10.5,color:C.muted,marginTop:3}}>{s.authority_name} · {s.status}{s.version_label?` · ${s.version_label}`:''}</div>{s.source_url&&<a href={s.source_url} target="_blank" rel="noopener noreferrer" style={{fontSize:10.5,color:C.blue}}>Open source ↗</a>}<div style={{display:'flex',gap:5,marginTop:6}}><button disabled={busy===s.id} onClick={()=>void review(s.id,'reviewed')} style={{...btn,color:C.amber}}>Reviewed</button><button disabled={busy===s.id} onClick={()=>void review(s.id,'verified')} style={{...btn,color:C.green}}>Verify</button><button disabled={busy===s.id} onClick={()=>void review(s.id,'rejected')} style={{...btn,color:C.red}}>Reject</button></div></div>)}</section><section style={panel}><h2 style={{fontSize:14}}>Publication revisions</h2>{revs.length===0?<div style={{color:C.muted}}>No revision snapshots yet.</div>:revs.map((r,i)=><div key={r.id} style={{padding:'11px 0',borderTop:i?`1px solid ${C.line}`:0}}><div style={{display:'flex',justifyContent:'space-between',gap:10}}><strong style={{fontSize:12}}>{r.publication_title||'Untitled'}</strong><span style={{fontSize:10,color:C.green}}>Revision {r.revision_number}</span></div><div style={{fontSize:10.5,color:C.muted,marginTop:4}}>{r.publication_format} · {r.reason||'Published update'} · {new Date(r.created_at).toLocaleString('en-KE')}</div></div>)}</section></div></div></main>}
const panel:React.CSSProperties={background:C.panel,border:`1px solid ${C.line}`,borderRadius:14,padding:14,maxHeight:'76dvh',overflow:'auto'};const btn:React.CSSProperties={border:`1px solid ${C.line}`,background:'rgba(255,255,255,.04)',color:C.text,borderRadius:9,padding:'8px 10px',fontSize:11,fontWeight:800,cursor:'pointer'};const input:React.CSSProperties={width:'100%',boxSizing:'border-box',background:'#0a1628',border:`1px solid ${C.line}`,borderRadius:9,padding:9,color:C.text,marginTop:4};const lab:React.CSSProperties={display:'block',fontSize:10,color:C.muted,fontWeight:800,marginBottom:8}
