import assert from "node:assert/strict"
import test from "node:test"
import { claimGovernedTrigger, executeGovernedWorker, persistGovernedClarification } from "./governed-runtime"
import type { DigitalWorkerDefinition, WorkEnvelope, WorkerExecutionResult } from "./types"

const now = new Date().toISOString()
const worker = { key:"proof-worker", name:"Proof Worker", department:"quality", mission:"Governed runtime proof", executionOrder:["rules","model"], authority:[{action:"read",mode:"allow",risk:"R0"},{action:"publish",mode:"deny",risk:"R3"},{action:"finance",mode:"approval_required",risk:"R3",approvalRole:"founder_ceo"}], contextPolicy:{denyKeys:["secret"],allowKeys:[],redactKeys:[]}, fallbackPolicy:{requireApprovalOnFallback:true}, triggers:[] } as unknown as DigitalWorkerDefinition
const envelope=(payload:Record<string,unknown>={})=>({id:"env-proof",type:"task",from:"hq",to:worker.key,createdAt:now,payload}) as WorkEnvelope<Record<string,unknown>>
const persistence=(overrides:Record<string,unknown>={})=>({claimTrigger:async()=>true,requestApproval:async()=>"approval-proof",persistClarification:async()=>"clarification-proof",...overrides}) as any
const healthy={telemetryUpdatedAt:now,workerHeartbeatAt:now}
const execute=async():Promise<WorkerExecutionResult>=>({status:"completed",workerKey:worker.key,workflowKey:"proof"} as WorkerExecutionResult)

test("watchdog fail-closes before execution",async()=>{let called=false;const result=await executeGovernedWorker({worker,workflowKey:"proof",action:"read",envelope:envelope(),mode:"rules" as any,watchdogSnapshot:{telemetryUpdatedAt:null,workerHeartbeatAt:null} as any,persistence:persistence(),execute:async()=>{called=true;return execute()}});assert.equal(result.status,"blocked");assert.equal(called,false)})
test("authority deny blocks execution",async()=>{let called=false;const result=await executeGovernedWorker({worker,workflowKey:"proof",action:"publish",envelope:envelope(),mode:"rules" as any,watchdogSnapshot:healthy as any,persistence:persistence(),execute:async()=>{called=true;return execute()}});assert.equal(result.status,"blocked");assert.equal(called,false)})
test("authority approval persists and stops",async()=>{let approvals=0,called=false;const result=await executeGovernedWorker({worker,workflowKey:"proof",action:"finance",envelope:envelope(),mode:"rules" as any,watchdogSnapshot:healthy as any,persistence:persistence({requestApproval:async()=>{approvals++;return"approval-proof"}}),execute:async()=>{called=true;return execute()}});assert.equal(result.status,"approval_required");assert.equal(approvals,1);assert.equal(called,false)})
test("fallback requires approval",async()=>{let called=false;const result=await executeGovernedWorker({worker,workflowKey:"proof",action:"read",envelope:envelope(),mode:"model" as any,watchdogSnapshot:healthy as any,persistence:persistence(),execute:async()=>{called=true;return execute()}});assert.equal(result.status,"approval_required");assert.equal(called,false)})
test("context is sanitized before executor",async()=>{let seen:Record<string,unknown>|undefined;await executeGovernedWorker({worker,workflowKey:"proof",action:"read",envelope:envelope({safe:"yes",secret:"never"}),mode:"rules" as any,watchdogSnapshot:healthy as any,persistence:persistence(),execute:async safe=>{seen=safe.payload;return execute()}});assert.equal(seen?.secret,undefined)})
test("metric trigger delegates durable admission",async()=>{let claims=0;const trigger={key:"metric-proof",source:"metric",metricKey:"errors",operator:">=",threshold:1,cooldownSeconds:60,dedupeWindowSeconds:60} as any;const accepted=await claimGovernedTrigger({worker,trigger,signal:{metricKey:"errors",metricValue:2},dedupeKey:"same",persistence:persistence({claimTrigger:async()=>{claims++;return claims===1}})});assert.equal(accepted,true);assert.equal(claims,1)})
test("persistence failure fails closed",async()=>{let called=false;await assert.rejects(()=>executeGovernedWorker({worker,workflowKey:"proof",action:"finance",envelope:envelope(),mode:"rules" as any,watchdogSnapshot:healthy as any,persistence:persistence({requestApproval:async()=>{throw new Error("DB_DOWN")}}),execute:async()=>{called=true;return execute()}}));assert.equal(called,false)})
test("clarification must be structured",async()=>{const bad={...envelope(),type:"clarify",payload:{questionKey:"",requiredFields:[]}} as any;await assert.rejects(()=>persistGovernedClarification(persistence(),"clarify:bad",bad),/INVALID_STRUCTURED_CLARIFICATION/)})
